### ISSUE TITLE
Flaky test test_operator_gpu.test_convolution_options @ Python2: MKLDNN-GPU

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10141]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/487/pipeline

```
======================================================================

FAIL: test_operator_gpu.test_convolution_options

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 520, in test_convolution_options

    check_consistency_NxM([sym, sym_no_cudnn], ctx_list)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 462, in check_consistency_NxM

    check_consistency(np.repeat(sym_list, len(ctx_list)), ctx_list * len(sym_list))

  File "/work/mxnet/python/mxnet/test_utils.py", line 1346, in check_consistency

    raise e

AssertionError: 

Items are not equal:

Error 1.159781 exceeds tolerance rtol=0.000010, atol=0.000010.  Location of maximum error:(2, 1, 0, 1, 0), a=0.672441, b=0.672422

 a: array([[[[[-248.01697024,  269.81250577,  230.7183668 ],

          [1307.21985885, -870.16663314,  317.35937973],

          [1066.71441871, -142.70123584, -192.51917322]],...

 b: array([[[[[-248.01697331,  269.81249749,  230.71837436],

          [1307.21981004, -870.16662222,  317.35938429],

          [1066.71438428, -142.70123247, -192.5191708 ]],...

-------------------- >> begin captured stdout << ---------------------

Train Err: ctx 2 vs ctx 0 at conv_weight



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1010398644 to reproduce.

--------------------- >> end captured logging << ---------------------

```

**Comment by zheng-da** [comment]
This test is interesting. It tested the code with very precision. the tol is 1e-5. It seems it's running with float64. I don't think MKLDNN can do conv with float64. The CPU code actually falls back to the native MXNet implementation, as far as I can tell.

**Comment by pengzhao-intel** [comment]
@marcoabreu could you double check if this case still fails?

It works on my side and the MKL-DNN results matches with GPU as below.

> [patric@mlt-skx082 workspace]$ export MXNET_TEST_SEED=1010398644
> [patric@mlt-skx082 workspace]$ export MKLDNN_VERBOSE=1
> [patric@mlt-skx082 workspace]$ nosetests --verbose tests/python/gpu/test_operator_gpu.py:test_convolution_options
> [INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1024541609 to reproduce.
> [WARNING] *** test-level seed set: all "@with_seed()" tests run deterministically ***
> test_operator_gpu.test_convolution_options ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1010398644 to reproduce.
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.219971
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0148926
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0141602
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0251465
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0930176
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0129395
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh3sh1dh0ph1_iw7ow7kw3sw1dw0pw1,0.0439453
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0119629
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.00805664
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0078125
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0100098
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0249023
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh2dh0ph0_iw7ow3kw3sw2dw0pw0,0.0339355
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0100098
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.00805664
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0109863
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0241699
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh3kh3sh1dh1ph0_iw7ow3kw3sw1dw1pw0,0.0249023
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.0090332
> mkldnn_verbose,exec,convolution,gemm:blas,forward_inference,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.00708008
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.00708008
> mkldnn_verbose,exec,convolution,gemm:blas,forward_training,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.00708008
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.0078125
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.0288086
> mkldnn_verbose,exec,convolution,gemm:blas,backward_data,fsrc:nchw fwei:oihw fbia:undef fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.019043
> mkldnn_verbose,exec,convolution,gemm:blas,backward_weights,fsrc:nchw fwei:oihw fbia:x fdst:nchw,alg:convolution_direct,mb2_g1ic2oc3_ih7oh7kh1sh1dh0ph0_iw7ow7kw1sw1dw0pw0,0.0290527
> ok
> 
> ----------------------------------------------------------------------
> Ran 1 test in 2.758s
> 
> OK
>

**Comment by marcoabreu** [comment]
@zheng-da would you mind assisting me here?

**Comment by pengzhao-intel** [comment]
@zheng-da could you help double check?

**Comment by zheng-da** [comment]
As I comment before, this isn't an MKLDNN error.
https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/test_utils.py#L1252
From the error message above, it shows that it's using rtol=0.000010, atol=0.000010 as tolerance.
It means it's using double precision floating point. The CPU execution falls to native MXNet implementation.

The error message shows that the results are very similar (a=0.672441, b=0.672422). The difference is a little higher than the threshold. At this point, you can't tell which result is correct. I was told that GPU is usually less accurate than CPU, it's possible the GPU result might be a little off from the actual truth.

**Comment by marcoabreu** [comment]
Thank you!

**Comment by zheng-da** [comment]
I tried running the test for 10,000 times, and still can't reproduce the bug.

**Comment by marcoabreu** [comment]
@zheng-da http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1062/pipeline/

**Comment by pengzhao-intel** [comment]
> Error 1.112584 exceeds tolerance rtol=0.000010, atol=0.000010.  Location of maximum error:(2, 1, 1, 0, 2), a=0.457128, b=0.457144

Looks the precision issue and the diff looks acceptable.

**Comment by szha** [comment]
@zheng-da @pengzhao-intel ping. Any progress?

**Comment by lupesko** [comment]
@pengzhao-intel  what's the next step?

**Comment by pengzhao-intel** [comment]
@szha @lupesko will look it next week. sorry I forgot this issue.

**Comment by pengzhao-intel** [comment]
Can't reproduce this case w/ or w/o the fixed seed.
@marcoabreu Could you open this test and let us see if the issue happen again?

[patric@mlt-gpu203 incubator-mxnet]$ nosetests --verbose tests/python/gpu/test_operator_gpu.py:test_convolution_options
/home/patric/.local/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=331160543 to reproduce.
test_operator_gpu.test_convolution_options ... [10:43:30] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
ok

----------------------------------------------------------------------
Ran 1 test in 5.392s

OK
