### ISSUE TITLE
Failing unit tests on Master branch

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [apache/incubator-mxnet#10182]
Working off the master branch on commit [067590bd](https://github.com/apache/incubator-mxnet/tree/067590bd22721fcb08ba09e8d898997e5c1905b1), the Python unit tests fail on Mac OSX in Python3
```
$ git log | head -1
commit 067590bd22721fcb08ba09e8d898997e5c1905b1
$ make && cd python && python3 ./setup.py test
Makefile:244: WARNING: Significant performance increases can be achieved by installing and enabling gperftools or jemalloc development packages
cd /Users/macaidan/edu/incubator-mxnet/dmlc-core; /Library/Developer/CommandLineTools/usr/bin/make libdmlc.a USE_SSE=1 config=/Users/macaidan/edu/incubator-mxnet/make/config.mk; cd /Users/macaidan/edu/incubator-mxnet
make[1]: `libdmlc.a' is up to date.
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
running test
Searching for numpy<=1.13.3,>=1.8.2
Best match: numpy 1.13.3
Processing numpy-1.13.3-py3.6-macosx-10.12-x86_64.egg

Using /Users/macaidan/edu/incubator-mxnet/python/.eggs/numpy-1.13.3-py3.6-macosx-10.12-x86_64.egg
/usr/local/lib/python3.6/site-packages/setuptools/dist.py:464: UserWarning: Module numpy was already imported from /usr/local/lib/python3.6/site-packages/numpy/__init__.py, but /Users/macaidan/edu/incubator-mxnet/python/.eggs/numpy-1.13.3-py3.6-macosx-10.12-x86_64.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running egg_info
writing mxnet.egg-info/PKG-INFO
writing dependency_links to mxnet.egg-info/dependency_links.txt
writing requirements to mxnet.egg-info/requires.txt
writing top-level names to mxnet.egg-info/top_level.txt
reading manifest file 'mxnet.egg-info/SOURCES.txt'
writing manifest file 'mxnet.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "./setup.py", line 109, in <module>
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 226, in run
    self.run_tests()
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 248, in run_tests
    exit=False,
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 118, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 229, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/usr/local/lib/python3.6/site-packages/setuptools/command/test.py", line 52, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/loader.py", line 211, in loadTestsFromName
    (obj, test))
TypeError: calling <function alexnet at 0x11cd828c8> returned AlexNet(
  (features): HybridSequential(
    (0): Conv2D(None -> 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(0, 0), ceil_mode=False)
    (2): Conv2D(None -> 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (3): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(0, 0), ceil_mode=False)
    (4): Conv2D(None -> 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (5): Conv2D(None -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): Conv2D(None -> 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): MaxPool2D(size=(3, 3), stride=(2, 2), padding=(0, 0), ceil_mode=False)
    (8): Flatten
    (9): Dense(None -> 4096, Activation(relu))
    (10): Dropout(p = 0.5, axes=())
    (11): Dense(None -> 4096, Activation(relu))
    (12): Dropout(p = 0.5, axes=())
  )
  (output): Dense(None -> 1000, linear)
), not a test
```

**Comment by sxjscience** [comment]
I usually use “nosetests tests/python/unittests” to run the test. Not sure if “python setup.py test” works.

**Comment by aidan-plenert-macdonald** [comment]
Yes. nosetests works
