### ISSUE TITLE
test_ndarray.test_reduce fails in v1.0.0

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#10274]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

## Environment info (Required)
```
(mxnet_py3_local) piotr@raspberrypi:~/devel/mxnet$ python diagnose.py
----------Python Info----------
Version      : 3.5.3
Compiler     : GCC 6.3.0 20170124
Build        : ('default', 'Jan 19 2017 14:11:04')
Arch         : ('32bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.3
Directory    : /home/piotr/mxnet_py3_local/lib/python3.5/site-packages/pip
----------MXNet Info-----------
Version      : 1.0.0
Directory    : /home/piotr/devel/incubator-mxnet/python/mxnet
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Linux-4.9.53-v7+-armv7l-with-debian-9.1
system       : Linux
node         : raspberrypi
release      : 4.9.53-v7+
version      : #1040 SMP Fri Oct 6 14:19:18 BST 2017
----------Hardware Info----------
machine      : armv7l
processor    :
Architecture:          armv7l
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model:                 4
Model name:            ARMv7 Processor rev 4 (v7l)
CPU max MHz:           1200.0000
CPU min MHz:           600.0000
BogoMIPS:              76.80
Flags:                 half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0417 sec, LOAD: 1.9344 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1800 sec, LOAD: 0.9307 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0554 sec, LOAD: 0.9979 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1190 sec, LOAD: 0.5036 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0443 sec, LOAD: 0.3027 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0333 sec, LOAD: 0.2825 sec.
(mxnet_py3_local) piotr@raspberrypi:~/devel/mxnet$
```

MXNet commit hash:
a4a2f6cce56cc62f02cd2803f97c5d48b72eb26c

Build config:
```
export CC = gcc
export CXX = g++
export NVCC = nvcc
DEV = 0
DEBUG = 0
USE_PROFILER =
USE_SIGNAL_HANDLER =
ADD_LDFLAGS =
ADD_CFLAGS =
USE_CUDA = 0
USE_CUDA_PATH = NONE
USE_CUDNN = 0
USE_NCCL = 0
USE_NCCL_PATH = NONE
USE_OPENCV = 1
USE_LIBJPEG_TURBO = 0
USE_LIBJPEG_TURBO_PATH = NONE
USE_OPENMP = 1
MKLML_ROOT=/usr/local
USE_MKL2017 = 0
USE_MKL2017_EXPERIMENTAL = 0
USE_NNPACK = 0
UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif
USE_LAPACK = 1
USE_LAPACK_PATH =
ifeq ($(USE_BLAS), mkl)
USE_LAPACK = 0
endif
USE_INTEL_PATH = NONE
ifeq ($(USE_MKL2017), 0)
ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
endif
else
USE_STATIC_MKL = NONE
endif
ARCH := $(shell uname -a)
ifneq (,$(filter $(ARCH), armv6l armv7l powerpc64le ppc64le aarch64))
        USE_SSE=0
else
        USE_SSE=1
endif
USE_DIST_KVSTORE = 0
USE_HDFS = 0
LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server
USE_S3 = 0
USE_OPERATOR_TUNING = 1
USE_GPERFTOOLS = 1
USE_JEMALLOC = 1
EXTRA_OPERATORS =
USE_CPP_PACKAGE = 0

```
## Error Message:
(Paste the complete error message, including stack trace.)
```

======================================================================
ERROR: test_ndarray.test_reduce
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/piotr/mxnet_py3_local/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/piotr/devel/incubator-mxnet/tests/python/unittest/test_ndarray.py", line 413, in test_reduce
    mx.nd.argmax, False)
  File "/home/piotr/devel/incubator-mxnet/tests/python/unittest/test_ndarray.py", line 398, in test_reduce_inner
    ndarray_ret = nd_reduce_func(mx.nd.array(dat), axis=axes, keepdims=keepdims)
  File "<string>", line 57, in argmax
  File "/home/piotr/devel/incubator-mxnet/python/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/piotr/devel/incubator-mxnet/python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:13:47] /home/piotr/devel/incubator-mxnet/src/operator/tensor/./broadcast_reduce_op.h:121: Check failed: axis < ndim && axis >= -ndim axis 42855152 exceeds the input dimension of 5

Stack trace returned 9 entries:
[bt] (0) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x28) [0x6fa0414c]
[bt] (1) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(_ZN5mxnet2op19ReduceAxisShapeImplERKN4nnvm6TShapeERKN4dmlc8optionalIiEEb+0xd4) [0x6ff13ac8]
[bt] (2) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(_ZN5mxnet2op15ReduceAxisShapeERKN4nnvm9NodeAttrsEPSt6vectorINS1_6TShapeESaIS6_EES9_+0x204) [0x6ff149f0]
[bt] (3) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(_ZN5mxnet10imperative12SetShapeTypeERKNS_7ContextERKN4nnvm9NodeAttrsERKSt6vectorIPNS_7NDArrayESaISA_EESE_PNS_12DispatchModeE+0x3c4) [0x6fad602c]
[bt] (4) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(_ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKSt6vectorIPNS_7NDArrayESaISA_EESE_+0x2b0) [0x6fac8c74]
[bt] (5) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(_Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_+0x278) [0x6fa2957c]
[bt] (6) /home/piotr/devel/incubator-mxnet/python/mxnet/libmxnet.so(MXImperativeInvokeEx+0x1e0) [0x6fa29e28]
[bt] (7) /home/piotr/mxnet_py3_local/lib/python3.5/lib-dynload/_ctypes.cpython-35m-arm-linux-gnueabihf.so(ffi_call_VFP+0x54) [0x761cda90]
[bt] (8) /home/piotr/mxnet_py3_local/lib/python3.5/lib-dynload/_ctypes.cpython-35m-arm-linux-gnueabihf.so(ffi_call+0x12c) [0x761cd528]

```
## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
python -m nose -s -v test_ndarray.py 2>&1 | tee test_.log

## What have you tried to solve it?

**Comment by smarthi** [comment]
Please use JIRA for reporting issues, and desist from opening any new github issues.

**Comment by larroy** [comment]
@smarthi Since when are we using JIRA to report issues?, I just spent many hours diagnosing a problem reported by an Amazon customer, I don't appreciate you closing this issue like this.

**Comment by larroy** [comment]
This bug is not observed while compiling with gcc-4.9 directly on the PI

**Comment by marcoabreu** [comment]
As long as JIRA is not mature, we don't decline issue on GitHub.

@smarthi according to https://lists.apache.org/thread.html/bdc250216a16c2af1abc4ca94014993a0a385021e93eee5dbce7455d@%3Cdev.mxnet.apache.org%3E, GitHub is still totally fine for reporting - please elaborate why you jumped in on only exactly one ticket instead of closing all tickets that fall under that category.

**Comment by anirudhacharya** [comment]
@marcoabreu Please tag this - "NDArray", "Test"

**Comment by ankkhedia** [comment]
Tested on master for d6813efa2206afb5be98c2da16dd6e2efaf44cda using gcc-6 (Ubuntu 6.4.0-17ubuntu1~16.04) 6.4.0 20180424, could not reproduce

**Comment by marcoabreu** [comment]
It could be ARM related. Lets leave it open for now and we'll have a look later on.
