### ISSUE TITLE
Failing test_operator_gpu.test_sparse_quadratic_function and test_flip

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10279]
```
test_operator_gpu.test_sparse_quadratic_function ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1862592620 to reproduce.

ERROR

test_operator_gpu.test_flip ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=170826886 to reproduce.

ERROR

test_operator_gpu.test_stn ... [00:04:00] src/operator/tensor/./.././../common/../operator/mxnet_op.h:576: Check failed: (err) == (cudaSuccess) Name: mxnet_generic_kernel ErrStr:invalid configuration argument

/work/runtime_functions.sh: line 391:     7 Aborted                 (core dumped) nosetests-2.7 --verbose tests/python/gpu

build.py: 2018-03-27 00:04:01,588 Running of command in container failed: nvidia-docker run --rm -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

build.py: 2018-03-27 00:04:01,589 You can try to get into the container by using the following command: nvidia-docker run --rm -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 -ti --entrypoint bash mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

Traceback (most recent call last):

  File "ci/build.py", line 179, in <module>

    sys.exit(main())

  File "ci/build.py", line 159, in main

    container_run(platform, docker_binary, command)

  File "ci/build.py", line 110, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'nvidia-docker run --rm -v /home/jenkins_slave/workspace/ut-python2-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-gpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu' returned non-zero exit status 134

script returned exit code 1
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/546/pipeline

https://issues.apache.org/jira/browse/MXNET-237

**Comment by eric-haibin-lin** [comment]
Fixed by https://github.com/apache/incubator-mxnet/pull/10259
