### ISSUE TITLE
MemoryError on linear classification with 400million dimension feature input

### ISSUE THREAD

**Issue by zhanglistar** [apache/incubator-mxnet#10310]
## Description
I am trying to train a modele using linear classification. My dataset's feature is 400million dimension,  
36846 instances. 
I am using the example code under example/sparse/linear_classification and modify the path to hdfs path.
When I run python train.py, I got error with MemoryError, details  as below.

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 5.4.0 20160609')
('Build        :', ('default', 'Nov 20 2017 18:23:56'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.3')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------

('Version      :', '1.2.0')
('Directory    :', '/data1/zhangzhibiao/incubator-mxnet/python/mxnet')
Hashtag not found. Not installed from pre-built package.
----------System Info----------
('Platform     :', 'Linux-4.9.20-040920-generic-x86_64-with-Ubuntu-16.04-xenial')
('system       :', 'Linux')
('node         :', 'bigo')
('release      :', '4.9.20-040920-generic')
('version      :', '#201703310531 SMP Fri Mar 31 09:33:05 UTC 2017')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               2299.951
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4201.60
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0319 sec, LOAD: 1.3650 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0025 sec, LOAD: 0.2229 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1591 sec, LOAD: 0.9004 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0610 sec, LOAD: 0.0714 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.1707 sec, LOAD: 0.1365 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1932 sec, LOAD: 0.8162 sec.

```

Package used (Python/R/Scala/Julia):
(I'm using ...) Python

MXNet commit hash:
69883163ef8e76c22a1d2cd7deb219f04a9ce82f

Build config:
make -j8 USE_OPENCV=1 USE_BLAS=openblas USE_HDFS=1

## Error Message:
```
2018-03-29 11:42:56,811 Namespace(batch_size=8192, kvstore=None, num_epoch=1, optimizer='ftrl')
2018-03-29 11:43:02,269 Training started ...
2018-03-29 11:43:33,506 epoch 0, eval nll = 0.731035470963 
2018-03-29 11:44:04,000 Saved checkpoint to "checkpoint-0000.params"
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    mod.save_checkpoint("checkpoint", epoch, save_optimizer_states=save_optimizer_states)
  File "/data1/zhangzhibiao/incubator-mxnet/python/mxnet/module/module.py", line 183, in save_checkpoint
    self.save_optimizer_states(state_name)
  File "/data1/zhangzhibiao/incubator-mxnet/python/mxnet/module/module.py", line 773, in save_optimizer_states
    fout.write(self._updater.get_states())
  File "/data1/zhangzhibiao/incubator-mxnet/python/mxnet/optimizer.py", line 1504, in get_states
    return pickle.dumps((self.states, self.optimizer) if dump_optimizer else self.states)
  File "/usr/lib/python2.7/pickle.py", line 1380, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/lib/python2.7/pickle.py", line 401, in save_reduce
    save(args)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/lib/python2.7/pickle.py", line 505, in save_unicode
    obj = obj.replace("\n", "\\u000a")
MemoryError
```

## Minimum reproducible example
incubator-mxnet/example/sparse/linear_classification

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.modify path to my hdfs path containing my samples.
2.python train.py

## What have you tried to solve it?

1.Reading the source code.
2.Try to google but without an answer.

**Comment by eric-haibin-lin** [comment]
What's the number of classes you try to classify? 400M is quite large.. Do you actually have that many active features?

**Comment by zhanglistar** [comment]
Number of classes is 2. Yes, I have that many features. I can train it on spark using fregata.

**Comment by zhanglistar** [comment]
I also have trilion features.

**Comment by zhanglistar** [comment]
Because it's linear model, I have to do many feature enigeering work. But if I switch to dnn, maybe not so many features.

**Comment by zhanglistar** [comment]
Do you know how the mx-net manage memory? I am shocked that mx-net used so many memory while the model just 400M * 8B = 3.2GB, and I triain it using batch, so it should not use so many memory in my opinion. I have to read the code to find why.

**Comment by sxjscience** [comment]
I feel that the memory cost should be `batch_size * 400M * 8B` if you do not use coordinate descent.

**Comment by eric-haibin-lin** [comment]
The caveat is that row sparse format comes with auxiliary indices, which is 8 bytes per row(feature)

**Comment by zhanglistar** [comment]
Is there any matrials aboult the design of mx-net? So I can understand the code faster.

**Comment by moveforever** [comment]
I came across with same error. The reason of the error is to save  intermediate optimization statement variable while saving checkpoint.
you can fix like this:
mod.save_checkpoint("checkpoint", epoch, save_optimizer_states=False)

**Comment by eric-haibin-lin** [comment]
Hi @zhanglistar 
Some notes on architecture of MXNet: http://mxnet.incubator.apache.org/architecture/index.html 
paper: https://arxiv.org/pdf/1512.01274.pdf
sparse op code walk-through: https://cwiki.apache.org/confluence/display/MXNET/A+Guide+to+Implementing+Sparse+Operators+in+MXNet+Backend

if you have specific questions regarding sparsity, I'm happy to chat on [Slack](https://mxnet.incubator.apache.org/versions/master/community/index.html)
