### ISSUE TITLE
Flaky test_gluon.test_lambda

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10376]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10373/1/pipeline

```
======================================================================

FAIL: test_gluon.test_lambda

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_gluon.py", line 720, in test_lambda

    assert_almost_equal(out1.asnumpy(), out2.asnumpy(), rtol=1e-3)

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 8.938683 exceeds tolerance rtol=0.001000, atol=0.000000.  Location of maximum error:(0, 0, 1, 1), a=0.000009, b=0.000009

 a: array([[[[0.5227292 , 0.02360163, 0.42252338, ..., 0.26800904,

          0.15513279, 0.59319496],

         [0.59968483, 0.00000948, 0.53139716, ..., 0.50179493,...

 b: array([[[[0.52272916, 0.02360159, 0.42252332, ..., 0.26800907,

          0.15513274, 0.59319496],

         [0.59968483, 0.00000939, 0.5313972 , ..., 0.5017949 ,...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=703294434 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by haojin2** [comment]
I met the same failure in: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10371/6/pipeline. I guess maybe the atol is too strict?

**Comment by reminisce** [comment]
That's the problem of using too small `atol` for comparing two values close to zero. @haojin2 Can you change `atol` to `1e-3` along with your PR?

**Comment by haojin2** [comment]
@reminisce Sure np!

**Comment by piiswrong** [comment]
fix merged
