### ISSUE TITLE
Flaky test_operator_gpu.test_deconvolution_options

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#10380]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/613/pipeline

```
======================================================================

FAIL: test_operator_gpu.test_deconvolution_options

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py2\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\test_operator_gpu.py", line 642, in test_deconvolution_options

    check_consistency_NxM([sym, sym_no_cudnn], ctx_list)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\test_operator_gpu.py", line 462, in check_consistency_NxM

    check_consistency(np.repeat(sym_list, len(ctx_list)), ctx_list * len(sym_list))

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 1346, in check_consistency

    raise e

AssertionError: 

Items are not equal:

Error 1.068359 exceeds tolerance rtol=0.100000, atol=0.100000.  Location of maximum error:(0, 1, 0, 1), a=-0.100403, b=0.007164

 a: array([[[[-113.        ,  103.8125    ,   69.125     ],

         [  58.6875    ,  -37.75      ,  -24.140625  ],

         [ 126.        ,  -58.3125    ,  -94.75      ]],...

 b: array([[[[-112.9375    ,  103.8125    ,   69.1875    ],

         [  58.65625   ,  -37.75      ,  -24.125     ],

         [ 126.        ,  -58.34375   ,  -94.75      ]],...

-------------------- >> begin captured stdout << ---------------------

Train Err: ctx 7 vs ctx 0 at deconv_weight



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=851023305 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by szha** [comment]
Fixed in #11529
