### ISSUE TITLE
Flaky test - ONNX

### ISSUE THREAD

**Issue by anirudh2290** [apache/incubator-mxnet#10403]
```


    @contextmanager

    def _error_catcher(self):

        """

            Catch low-level python exceptions, instead re-raising urllib3

            variants, so that low-level exceptions are not leaked in the

            high-level api.

    

            On exit, release the connection back to the pool.

            """

        clean_exit = False

    

        try:

            try:

                yield

    

            except SocketTimeout:

                # FIXME: Ideally we'd like to include the url in the ReadTimeoutError but

                # there is yet no clean way to get at it from this context.

                raise ReadTimeoutError(self._pool, None, 'Read timed out.')

    

            except BaseSSLError as e:

                # FIXME: Is there a better way to differentiate between SSLErrors?

                if 'read operation timed out' not in str(e):  # Defensive:

                    # This shouldn't happen but just in case we're missing an edge

                    # case, let's avoid swallowing SSL errors.

                    raise

    

                raise ReadTimeoutError(self._pool, None, 'Read timed out.')

    

            except (HTTPException, SocketError) as e:

                # This includes IncompleteRead.

>               raise ProtocolError('Connection broken: %r' % e, e)

E               urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))



/usr/local/lib/python3.5/dist-packages/urllib3/response.py:320: ProtocolError



During handling of the above exception, another exception occurred:



    def test_bvlc_rcnn_ilsvrc13():

        """Tests the bvlc rcnn model"""

>       model_path, inputs, outputs = get_test_files('bvlc_reference_rcnn_ilsvrc13')



tests/python-pytest/onnx/onnx_test.py:232: 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

tests/python-pytest/onnx/onnx_test.py:155: in get_test_files

    tar_name = download(URLS.get(name), dirname=CURR_PATH.__str__())

python/mxnet/test_utils.py:1417: in download

    for chunk in r.iter_content(chunk_size=1024):

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 



    def generate():

        # Special case for urllib3.

        if hasattr(self.raw, 'stream'):

            try:

                for chunk in self.raw.stream(chunk_size, decode_content=True):

                    yield chunk

            except ProtocolError as e:

>               raise ChunkedEncodingError(e)

E               requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))



/usr/local/lib/python3.5/dist-packages/requests/models.py:748: ChunkedEncodingError

===================== 1 failed, 9 passed in 350.06 seconds =====================

build.py: 2018-04-04 19:36:41,846 Running of command in container failed (1): docker run --rm -v /home/jenkins_slave/workspace/it-onnx-cpu:/work/mxnet -v /home/jenkins_slave/workspace/it-onnx-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh integrationtest_ubuntu_cpu_onnx

build.py: 2018-04-04 19:36:41,846 You can try to get into the container by using the following command: docker run --rm -v /home/jenkins_slave/workspace/it-onnx-cpu:/work/mxnet -v /home/jenkins_slave/workspace/it-onnx-cpu/build:/work/build -u 1001:1001 -ti --entrypoint /bin/bash mxnet/build.ubuntu_cpu /work/runtime_functions.sh integrationtest_ubuntu_cpu_onnx

into container: False

Traceback (most recent call last):

  File "ci/build.py", line 253, in <module>

    sys.exit(main())

  File "ci/build.py", line 193, in main

    container_run(platform, docker_binary, command)

  File "ci/build.py", line 119, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker run --rm -v /home/jenkins_slave/workspace/it-onnx-cpu:/work/mxnet -v /home/jenkins_slave/workspace/it-onnx-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh integrationtest_ubuntu_cpu_onnx' returned non-zero exit status 1

script returned exit code 1
```

Please see: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10400/2/pipeline/1252

**Comment by anirudhacharya** [comment]
The test failed while trying to read a file from S3. It failed on the ``download`` method of ``mxnet.test_utils`` module (which is common code used by a lot of other tests too), here
```python
r = requests.get(url, stream=True)
assert r.status_code == 200, "failed to open %s" % url
with open(fname, 'wb') as f:
  for chunk in r.iter_content(chunk_size=1024):
```
The error logs say it failed while trying fetch the HTTP Response object because the connection was broken. Will look into how we can prevent this and ensure the test is not flaky.

@sandeep-krishnamurthy  can we add "ONNX" as a new label to this issue.
