### ISSUE TITLE
Cannot build ubuntu_gpu CI docker image (java8 sdk missing)

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#10586]
@marcoabreu 

`sudo ci/build.py --platform ubuntu_gpu`

```
Step 9/28 : RUN /work/ubuntu_scala.sh
 ---> Running in ba4601ca7f3c
+ apt-get install -y software-properties-common
Reading package lists...
Building dependency tree...
Reading state information...
software-properties-common is already the newest version (0.96.20.7).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
+ add-apt-repository -y ppa:webupd8team/java
gpg: keyring `/tmp/tmpv26svozn/secring.gpg' created
gpg: keyring `/tmp/tmpv26svozn/pubring.gpg' created
gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpv26svozn/trustdb.gpg: trustdb created
gpg: key EEA14886: public key "Launchpad VLC" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
+ apt-get update
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:3 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease [17.5 kB]
Ign:4 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Ign:6 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease
Hit:7 http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release
Hit:8 http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release
Get:11 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial/main amd64 Packages [3146 B]
Get:12 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 327 kB in 0s (398 kB/s)
Reading package lists...
+ echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true'
+ debconf-set-selections
+ apt-get install -y oracle-java8-installer
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  gsfonts gsfonts-x11 java-common libfontenc1 libxfont1 locales
  oracle-java8-set-default xfonts-encodings xfonts-utils
Suggested packages:
  binfmt-support visualvm ttf-baekmuk | ttf-unfonts | ttf-unfonts-core
  ttf-kochi-gothic | ttf-sazanami-gothic ttf-kochi-mincho
  | ttf-sazanami-mincho ttf-arphic-uming firefox | firefox-2 | iceweasel
  | mozilla-firefox | iceape-browser | mozilla-browser | epiphany-gecko
  | epiphany-webkit | epiphany-browser | galeon | midbrowser
  | moblin-web-browser | xulrunner | xulrunner-1.9 | konqueror
  | chromium-browser | midori | google-chrome
The following NEW packages will be installed:
  gsfonts gsfonts-x11 java-common libfontenc1 libxfont1 locales
  oracle-java8-installer oracle-java8-set-default xfonts-encodings
  xfonts-utils
0 upgraded, 10 newly installed, 0 to remove and 4 not upgraded.
Need to get 7398 kB of archives.
After this operation, 20.5 MB of additional disk space will be used.
Get:1 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial/main amd64 oracle-java8-installer all 8u161-1~webupd8~0 [33.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial/main amd64 java-common all 0.56ubuntu2 [7742 B]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 locales all 2.23-0ubuntu10 [3213 kB]
Get:4 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial/main amd64 oracle-java8-set-default all 8u161-1~webupd8~0 [6830 B]
Get:5 http://archive.ubuntu.com/ubuntu xenial/main amd64 gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.2ubuntu1 [3374 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial/main amd64 libfontenc1 amd64 1:1.1.3-1 [13.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libxfont1 amd64 1:1.5.1-1ubuntu0.16.04.4 [95.0 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial/main amd64 xfonts-encodings all 1:1.0.4-2 [573 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 xfonts-utils amd64 1:7.7+3ubuntu0.16.04.2 [74.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial/universe amd64 gsfonts-x11 all 0.24 [7314 B]
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Fetched 7398 kB in 1s (5891 kB/s)
Selecting previously unselected package java-common.
(Reading database ... 25814 files and directories currently installed.)
Preparing to unpack .../java-common_0.56ubuntu2_all.deb ...
Unpacking java-common (0.56ubuntu2) ...
Selecting previously unselected package locales.
Preparing to unpack .../locales_2.23-0ubuntu10_all.deb ...
Unpacking locales (2.23-0ubuntu10) ...
Selecting previously unselected package oracle-java8-installer.
Preparing to unpack .../oracle-java8-installer_8u161-1~webupd8~0_all.deb ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
oracle-license-v1-1 license has already been accepted
Unpacking oracle-java8-installer (8u161-1~webupd8~0) ...
Processing triggers for man-db (2.7.5-1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for shared-mime-info (1.5-2ubuntu0.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up java-common (0.56ubuntu2) ...
Setting up locales (2.23-0ubuntu10) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Generating locales (this might take a while)...
Generation complete.
Setting up oracle-java8-installer (8u161-1~webupd8~0) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
No /var/cache/oracle-jdk8-installer/wgetrc file found.
Creating /var/cache/oracle-jdk8-installer/wgetrc and
using default oracle-java8-installer wgetrc settings for it.
Downloading Oracle Java 8...
--2018-04-17 22:41:17--  http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
Resolving download.oracle.com (download.oracle.com)... 23.46.60.117
Connecting to download.oracle.com (download.oracle.com)|23.46.60.117|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz [following]
--2018-04-17 22:41:18--  https://edelivery.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
Resolving edelivery.oracle.com (edelivery.oracle.com)... 23.49.182.138, 2600:1407:10:284::2d3e, 2600:1407:10:2af::2d3e
Connecting to edelivery.oracle.com (edelivery.oracle.com)|23.49.182.138|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz?AuthParam=1524004998_8d72137f4e78fb30bef3899b61850211 [following]
--2018-04-17 22:41:18--  http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz?AuthParam=1524004998_8d72137f4e78fb30bef3899b61850211
Connecting to download.oracle.com (download.oracle.com)|23.46.60.117|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-17 22:41:19 ERROR 404: Not Found.

download failed
Oracle JDK 8 is NOT installed.
dpkg: error processing package oracle-java8-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java8-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c /work/ubuntu_scala.sh' returned a non-zero code: 100
Traceback (most recent call last):
  File "ci/build.py", line 252, in <module>
    sys.exit(main())
  File "ci/build.py", line 186, in main
    build_docker(platform, docker_binary)
  File "ci/build.py", line 73, in build_docker
    check_call(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-f', 'docker/Dockerfile.build.ubuntu_gpu', '--build-arg', 'USER_ID=0', '-t', 'mxnet/build.ubuntu_gpu', 'docker']' returned non-zero exit status 100

```

Checking the comments of this [page](https://tecadmin.net/install-oracle-java-8-ubuntu-via-ppa/), it looks like recently there has been this bug.

Common recurrent issue webup8 are getting behind the official releases: [SO issue](https://stackoverflow.com/questions/46815254/oracle-java8-installer-webupd8-ppa-404-not-found)

**Comment by ThomasDelteil** [comment]
Could we just use the openjdk ?

**Comment by marcoabreu** [comment]
I'm indifferent to that.

**Comment by spidyDev** [comment]
@ThomasDelteil  @marcoabreu  Could we tag this issue appropriately? Thanks.

**Comment by marcoabreu** [comment]
https://github.com/apache/incubator-mxnet/pull/10642

**Comment by ThomasDelteil** [comment]
Switched to the openjdk
