### ISSUE TITLE
Flaky test_correlation

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#10735]
```
test_operator_gpu.test_correlation ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1596554413 to reproduce.

FAIL: test_operator_gpu.test_correlation

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/usr/local/lib/python3.5/dist-packages/nose/util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/../unittest/test_operator.py", line 2427, in test_correlation

    unittest_correlation((5,1,15,15), kernel_size = 1,max_displacement = 5,stride1 = 1,stride2 = 1,pad_size = 5,is_multiply = False, dtype = dtype)

  File "/work/mxnet/tests/python/gpu/../unittest/test_operator.py", line 2397, in unittest_correlation

    assert_almost_equal(exe1.grad_dict['img1'].asnumpy(), grad1, rtol=1e-3, atol=1e-4)

  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 23.501763 exceeds tolerance rtol=0.001000, atol=0.000100.  Location of maximum error:(2, 0, 12, 7), a=87.000000, b=85.000000

 a: array([[[[105.,  39.,  99., ...,  63., 107.,  53.],

         [ 39.,  25., 111., ..., 101.,  99.,  79.],

         [121., 103.,  43., ...,  15.,  39., 111.],...

 b: array([[[[105.,  39.,  99., ...,  63., 107.,  53.],

         [ 39.,  25., 111., ..., 101.,  99.,  79.],

         [121., 103.,  43., ...,  15.,  39., 111.],...

```

**Comment by marcoabreu** [comment]
Tracked at https://github.com/apache/incubator-mxnet/issues/10280
