### ISSUE TITLE
Flaky test_random.test_sample_multinomial

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#10838]
Link to the failed build: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10533/34/pipeline
```
======================================================================

FAIL: test_random.test_sample_multinomial

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py2\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_random.py", line 400, in test_sample_multinomial

    mx.test_utils.assert_almost_equal(freq, x[i], rtol=0.20)

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 10000000317344786.000000 exceeds tolerance rtol=0.200000, atol=0.000000.  Location of maximum error:(4,), a=0.000200, b=0.000000

 a: array([ 0.3922,  0.3044,  0.2064,  0.0968,  0.0002])

 b: array([ 0.40000001,  0.30000001,  0.2       ,  0.1       ,  0.        ], dtype=float32)

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=22688242 to reproduce.

--------------------- >> end captured logging << ---------------------

```

**Comment by larroy** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11186/3/pipeline

**Comment by aaronmarkham** [comment]
Failed here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11157/8/pipeline

**Comment by anirudh2290** [comment]
Can be reproduced with:
```
MXNET_TEST_SEED=1599588672 nosetests -v --logging-level=DEBUG tests/python/unittest/test_random.py:test_sample_multinomial
```
