### ISSUE TITLE
test_sparse_operator.py:test_sparse_mathematical_core fails under scipy v1.1

### ISSUE THREAD

**Issue by DickJC123** [apache/incubator-mxnet#10896]
## Description
Our CI systems pull in scipy via 'pip install scipy' and are now getting version 1.1 from the public server, rather than the previous 1.0.  The trouble with this is that the function scipy.special.psi() has a different behavior in the two versions when passed a 0 argument and this causes test_sparse_operator.py:test_sparse_mathematical_core to fail.

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 5.4.0 20160609')
('Build        :', ('default', 'Dec  4 2017 14:50:18'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '10.0.1')
('Directory    :', '/home/dcarter/.local/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
/home/dcarter/mxnet_dev/dgx/mxnet/python/mxnet/optimizer.py:136: UserWarning: WARNING: New optimizer mxnet.optimizer.NAG is overriding existing optimizer mxnet.optimizer.NAG
  Optimizer.opt_registry[name].__name__))
('Version      :', '1.1.0')
('Directory    :', '/home/dcarter/mxnet_dev/dgx/mxnet/python/mxnet')
Hashtag not found. Not installed from pre-built package.
----------System Info----------
('Platform     :', 'Linux-4.4.0-121-generic-x86_64-with-Ubuntu-16.04-xenial')
('system       :', 'Linux')
('node         :', 'DCARTER-DT')
('release      :', '4.4.0-121-generic')
('version      :', '#145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                12
On-line CPU(s) list:   0-11
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz
Stepping:              2
CPU MHz:               1292.539
CPU max MHz:           3700.0000
CPU min MHz:           1200.0000
BogoMIPS:              6996.26
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              15360K
NUMA node0 CPU(s):     0-11
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single retpoline kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts

```

## Error Message:

See the end of 'Steps to reproduce'

## Steps to reproduce:

Normal/correct behavior:

```
$ python -c "import numpy; print(numpy.__version__)"
1.14.3
$ python -c "import scipy; print(scipy.__version__)"
1.0.0
$ python -c "import scipy.special; print(scipy.special.psi(0))"
inf
$ nosetests tests/python/unittest/test_sparse_operator.py:test_sparse_mathematical_core
 ...
OK
```
Problematic behavior:
```
$ sudo pip install scipy==1.1 --force-reinstall
$ python -c "import numpy; print(numpy.__version__)"
1.14.3
$ python -c "import scipy; print(scipy.__version__)"
1.1.0
$ python -c "import scipy.special; print(scipy.special.psi(0))"
-inf             <------------  Note minus inf, different than with scipy v1.0
$ nosetests tests/python/unittest/test_sparse_operator.py:test_sparse_mathematical_core
/home/dcarter/mxnet_dev/dgx/mxnet/python/mxnet/optimizer.py:136: UserWarning: WARNING: New optimizer mxnet.optimizer.NAG is overriding existing optimizer mxnet.optimizer.NAG
  Optimizer.opt_registry[name].__name__))
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=900978872 to reproduce.
[INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=2040547495 to reproduce.
F
======================================================================
FAIL: test_sparse_operator.test_sparse_mathematical_core
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/dcarter/mxnet_dev/dgx/mxnet/tests/python/unittest/common.py", line 152, in test_new
    orig_test(*args, **kwargs)
  File "/home/dcarter/mxnet_dev/dgx/mxnet/tests/python/unittest/test_sparse_operator.py", line 1069, in test_sparse_mathematical_core
    density=density, ograd_density=ograd_density)
  File "/home/dcarter/mxnet_dev/dgx/mxnet/tests/python/unittest/test_sparse_operator.py", line 1044, in check_mathematical_core
    density=density, ograd_density=ograd_density)
  File "/home/dcarter/mxnet_dev/dgx/mxnet/tests/python/unittest/test_sparse_operator.py", line 687, in check_sparse_mathematical_core
    assert_almost_equal(arr_grad, input_grad, equal_nan=True)
  File "/home/dcarter/mxnet_dev/dgx/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error nan exceeds tolerance rtol=0.000010, atol=0.000000.  Location of maximum error:(0, 0), a=inf, b=-inf
 a: array([[inf, inf],
       [inf, inf],
       [inf, inf],...
 b: array([[-inf, -inf],
       [-inf, -inf],
       [-inf, -inf],...
-------------------- >> begin captured stdout << ---------------------
('pass', 0)
0.0, 0.0, False

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
common: INFO: Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=900978872 to reproduce.
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=2040547495 to reproduce.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.036s

FAILED (failures=1)
```

## What have you tried to solve it?

We've hardcoded our scipy install command to grab the 1.0 version that works:

pip install scipy==1.0

As I dug into the test, I discovered that the psi operator was being passed an argument of 0.  The psi function is discontinuous at 0, and could be though of as having either a +inf or -inf value depending on whether 0 is approached from the positive or negative x-axis.  I felt the creator of the test would be the best one to adapt the test to the new behavior of psi() under scipy v1.1.  Note that the failure shown occurs for any seed.

**Comment by eric-haibin-lin** [comment]
Thanks for looking into this! Closed via https://github.com/apache/incubator-mxnet/pull/10961
