### ISSUE TITLE
Flaky test: test_tutorials.test_onnx_inference_on_onnx_model

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#10947]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10913/12/pipeline

```
FAIL: test_tutorials.test_onnx_inference_on_onnx_model

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/tutorials/test_tutorials.py", line 161, in test_onnx_inference_on_onnx_model

    assert _test_tutorial_nb('onnx/inference_on_onnx_model')

AssertionError: 

-------------------- >> begin captured stdout << ---------------------

An error occurred while executing the following cell:

------------------

mx.test_utils.download(url, dirname = model_folder)

if not os.path.isdir(os.path.join(model_folder, current_model)):

    print('Extracting model...')

    tar = tarfile.open(archive_file, "r:gz")

    tar.extractall(model_folder)

    tar.close()

    print('Extracted')

------------------





ConnectionResetErrorTraceback (most recent call last)

/usr/local/lib/python3.5/dist-packages/urllib3/response.py in _error_catcher(self)

    301             try:

--> 302                 yield

    303 



/usr/local/lib/python3.5/dist-packages/urllib3/response.py in read(self, amt, decode_content, cache_content)

    383                 cache_content = False

--> 384                 data = self._fp.read(amt)

    385                 if amt != 0 and not data:  # Platform-specific: Buggy versions of Python.



/usr/lib/python3.5/http/client.py in read(self, amt)

    447             b = bytearray(amt)

--> 448             n = self.readinto(b)

    449             return memoryview(b)[:n].tobytes()



/usr/lib/python3.5/http/client.py in readinto(self, b)

    487         # (for example, reading in 1k chunks)

--> 488         n = self.fp.readinto(b)

    489         if not n and b:



/usr/lib/python3.5/socket.py in readinto(self, b)

    574             try:

--> 575                 return self._sock.recv_into(b)

    576             except timeout:



/usr/lib/python3.5/ssl.py in recv_into(self, buffer, nbytes, flags)

    928                   self.__class__)

--> 929             return self.read(nbytes, buffer)

    930         else:



/usr/lib/python3.5/ssl.py in read(self, len, buffer)

    790         try:

--> 791             return self._sslobj.read(len, buffer)

    792         except SSLError as x:



/usr/lib/python3.5/ssl.py in read(self, len, buffer)

    574         if buffer is not None:

--> 575             v = self._sslobj.read(len, buffer)

    576         else:



ConnectionResetError: [Errno 104] Connection reset by peer



During handling of the above exception, another exception occurred:



ProtocolErrorTraceback (most recent call last)

/usr/local/lib/python3.5/dist-packages/requests/models.py in generate()

    744                 try:

--> 745                     for chunk in self.raw.stream(chunk_size, decode_content=True):

    746                         yield chunk



/usr/local/lib/python3.5/dist-packages/urllib3/response.py in stream(self, amt, decode_content)

    435             while not is_fp_closed(self._fp):

--> 436                 data = self.read(amt=amt, decode_content=decode_content)

    437 



/usr/local/lib/python3.5/dist-packages/urllib3/response.py in read(self, amt, decode_content, cache_content)

    400                         # Content-Length are caught.

--> 401                         raise IncompleteRead(self._fp_bytes_read, self.length_remaining)

    402 



/usr/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)

     76             try:

---> 77                 self.gen.throw(type, value, traceback)

     78                 raise RuntimeError("generator didn't stop after throw()")



/usr/local/lib/python3.5/dist-packages/urllib3/response.py in _error_catcher(self)

    319                 # This includes IncompleteRead.

--> 320                 raise ProtocolError('Connection broken: %r' % e, e)

    321 



ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))



During handling of the above exception, another exception occurred:



ChunkedEncodingErrorTraceback (most recent call last)

<ipython-input-4-e599fff213cd> in <module>()

----> 1 mx.test_utils.download(url, dirname = model_folder)

      2 if not os.path.isdir(os.path.join(model_folder, current_model)):

      3     print('Extracting model...')

      4     tar = tarfile.open(archive_file, "r:gz")

      5     tar.extractall(model_folder)



/work/mxnet/python/mxnet/test_utils.py in download(url, fname, dirname, overwrite)

   1415     assert r.status_code == 200, "failed to open %s" % url

   1416     with open(fname, 'wb') as f:

-> 1417         for chunk in r.iter_content(chunk_size=1024):

   1418             if chunk: # filter out keep-alive new chunks

   1419                 f.write(chunk)



/usr/local/lib/python3.5/dist-packages/requests/models.py in generate()

    746                         yield chunk

    747                 except ProtocolError as e:

--> 748                     raise ChunkedEncodingError(e)

    749                 except DecodeError as e:

    750                     raise ContentDecodingError(e)



ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))





--------------------- >> end captured stdout << ----------------------



----------------------------------------------------------------------

```

**Comment by ThomasDelteil** [comment]
@KellenSunderland just wanted to check what is the status of the retry logic on the mx.test_utils.download() ? That would help with that particular bug. 

@eric-haibin-lin I have moved all models that were 500MB+ to <50MB models, so the likeliness of download errors will decrease.

**Comment by ThomasDelteil** [comment]
@eric-haibin-lin this should be solved by https://github.com/apache/incubator-mxnet/pull/11181 please consider closing (tutorial tests are moving to nightly as well)
