### ISSUE TITLE
Flaky test: test_operator_gpu.test_sample_multinomial

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#10958]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10939/6/pipeline/
```
======================================================================

FAIL: test_operator_gpu.test_sample_multinomial

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_random.py", line 400, in test_sample_multinomial

    mx.test_utils.assert_almost_equal(freq, x[i], rtol=0.20)

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 10000000317344786.000000 exceeds tolerance rtol=0.200000, atol=0.000000.  Location of maximum error:(4,), a=0.000200, b=0.000000

 a: array([ 0.4042,  0.2992,  0.194 ,  0.1024,  0.0002])

 b: array([ 0.40000001,  0.30000001,  0.2       ,  0.1       ,  0.        ], dtype=float32)

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1909654132 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by haojin2** [comment]
This issue was already raised by me earlier... #10838
