### ISSUE TITLE
CI bug R-CPU no space left on device

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#10960]
See http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10956/2/pipeline

```
Traceback (most recent call last):

  File "/usr/lib/python3.5/logging/__init__.py", line 984, in emit

    self.flush()

  File "/usr/lib/python3.5/logging/__init__.py", line 964, in flush

    self.stream.flush()

OSError: [Errno 28] No space left on device

Call stack:

  File "ci/build.py", line 263, in <module>

  File "ci/build.py", line 204, in main

  File "ci/build.py", line 124, in container_run

Message: 'Running of command in container failed (%s): %s'

Arguments: (1, 'docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-r-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-r-cpu/build:/work/build -u 1001:1001 mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_cpu_R')

build.py: 2018-05-15 21:34:43,421 You can try to get into the container by using the following command: docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-r-cpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-r-cpu/build:/work/build -u 1001:1001 -ti --entrypoint /bin/bash mxnet/build.ubuntu_cpu /work/runtime_functions.sh unittest_ubuntu_cpu_R

--- Logging error ---

Traceback (most recent call last):

  File "/usr/lib/python3.5/logging/__init__.py", line 984, in emit

    self.flush()

  File "/usr/lib/python3.5/logging/__init__.py", line 964, in flush

    self.stream.flush()

OSError: [Errno 28] No space left on device

Call stack:
```

@marcoabreu could that be related to the new autoscaling CI ? I have seen this error at time when /dev/shm is full.

**Comment by ThomasDelteil** [comment]
Another one, on the jetson build: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10956/4/pipeline/69
