### ISSUE TITLE
../../tools/launch.py -n 2 -s 2 --launcher yarn  python train_mnist.py --network lenet --kv-store dist_sync

### ISSUE THREAD

**Issue by liuzx32** [apache/incubator-mxnet#11011]
Traceback (most recent call last):
  File "./launcher.py", line 81, in <module>
    main()
  File "./launcher.py", line 76, in main
    ret = subprocess.call(args=sys.argv[1:], env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Comment by ankkhedia** [comment]
@liuzx32 Could you please give more context of the environment and error. At first sight, it seems like a permission and error and  you can try running this as sudo in case you are using ubuntu.

@sandeep-krishnamurthy Could you please tag this as Pending requester info and python

**Comment by liuzx32** [comment]
OSError: [Errno 13] Permission denied from ../../example/image-classification/train_mnist.py.
chmod 775 ../../example/image-classification/train_mnist.py and run it  local success.
##
But run it yarn will failed exitCode=1

**Comment by liuzx32** [comment]
@ankkhedia @sandeep-krishnamurthy Thanks very much, Maybe mxnet can give some examples about mxnet on yarn.

**Comment by liuzx32** [comment]
@sandeep-krishnamurthy Thank you very much!

**Comment by CanoeFZH** [comment]
get same errror here:
```LogType:stderr
Log Upload Time:Thu Jun 21 07:11:09 +0000 2018
LogLength:523
Log Contents:
Traceback (most recent call last):
  File "./launcher.py", line 85, in <module>
    main()
  File "./launcher.py", line 80, in main
    ret = subprocess.call(args=sys.argv[1:], env=env)
  File "/usr/lib64/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
End of LogType:stderr

LogType:stdout
Log Upload Time:Thu Jun 21 07:11:09 +0000 2018
LogLength:0
Log Contents:
End of LogType:stdout


```
