### ISSUE TITLE
Flaky test: test_operator.test_op_roi_align

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#11064]
```
======================================================================

FAIL: test_operator.test_op_roi_align

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 157, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 6170, in test_op_roi_align

    test_roi_align_value()

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 6149, in test_roi_align_value

    assert np.allclose(data.grad.asnumpy(), dx, atol = 1e-6), np.abs(data.grad.asnumpy() - dx).max()

AssertionError: 1.3150275e-06

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1619190489 to reproduce.

--------------------- >> end captured logging << ---------------------

```
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11058/1/pipeline

**Comment by zhreshold** [comment]
Relax with rtol should be fine, the diff is acceptable

**Comment by haojin2** [comment]
@zhreshold increased the rtol to 1e-4 and passed 500 consecutive test runs, the change is included in #11058

**Comment by anirudhacharya** [comment]
This failure persists - http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-11229/runs/9/nodes/752/log/?start=0

**Comment by marcoabreu** [comment]
Hi @anirudhacharya, please note that the problem is not this test but many tests are failing if you scroll up. This is documented in https://github.com/apache/incubator-mxnet/issues/11395

**Comment by jlcontreras** [comment]
Seems to still happen:

```
======================================================================
FAIL: test_operator_gpu.test_op_roi_align
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 173, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/gpu/../unittest/test_operator.py", line 6994, in test_op_roi_align
    test_roi_align_value()
  File "/work/mxnet/tests/python/gpu/../unittest/test_operator.py", line 6970, in test_roi_align_value
    assert np.allclose(output.asnumpy(), real_output)
    AssertionError: 
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=35650200 to reproduce.
--------------------- >> end captured logging << ---------------------
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/master/45/pipeline

**Comment by zhreshold** [comment]
Maybe we should take another look, however, the log won't show the detailed error anymore?

**Comment by wkcn** [comment]
Maybe there is some difference between C++ implementation and Python implementation. I will test and fix it.

**Comment by wkcn** [comment]
When MXNET_TEST_SEED=35650200, the error shows that:
```
AssertionError: 
Items are not equal:
Error 3.147267 exceeds tolerance rtol=0.000010, atol=0.000000.  Location of maximum error:(6, 0, 0, 1), a=0.005887, b=0.005887
 a: array([[[[  172.60527039,   173.5171814 ,   174.42907715,   175.34100342],
         [  195.92706299,   196.83895874,   197.75085449,   198.6627655 ],
         [  219.24882507,   220.16073608,   221.07263184,   221.98455811]],...
 b: array([[[[  172.60527627,   173.51718251,   174.42908875,   175.34099499],
         [  195.9270587 ,   196.83896494,   197.75087118,   198.66277742],
         [  219.24884113,   220.16074737,   221.07265361,   221.98455985]],...
```

It's strange.
