### ISSUE TITLE
Problem with test_contrib_io.test_contrib_DataLoaderIter

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#11103]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10931/11/pipeline/719

======================================================================

ERROR: test_contrib_io.test_contrib_DataLoaderIter

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/test_contrib_io.py", line 39, in test_contrib_DataLoaderIter

    test_mnist_batches(50, num_examples // 50, 'discard')

  File "/work/mxnet/tests/python/unittest/test_contrib_io.py", line 26, in test_mnist_batches

    dataset = MNIST(train=False)

  File "/work/mxnet/python/mxnet/gluon/data/vision/datasets.py", line 66, in __init__

    super(MNIST, self).__init__(root, transform)

  File "/work/mxnet/python/mxnet/gluon/data/dataset.py", line 197, in __init__

    self._get_data()

  File "/work/mxnet/python/mxnet/gluon/data/vision/datasets.py", line 77, in _get_data

    sha1_hash=data[1])

  File "/work/mxnet/python/mxnet/gluon/utils.py", line 212, in download

    raise RuntimeError("Failed downloading url %s"%url)

RuntimeError: Failed downloading url https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/mnist/t10k-images-idx3-ubyte.gz

-------------------- >> begin captured stdout << ---------------------

**Comment by lanking520** [comment]
@haojin2 @eric-haibin-lin It seemed this issue came from download. Is there any way we can resolve that?

**Comment by eric-haibin-lin** [comment]
we can add retry logic to download

**Comment by anirudh2290** [comment]
assigned to haibin. @haojin2  is working on this.

**Comment by haojin2** [comment]
Caused by a broken link, the link is fixed now so closing this.
