### ISSUE TITLE
Flaky test: test_io.test_LibSVMIter

### ISSUE THREAD

**Issue by ThomasDelteil** [apache/incubator-mxnet#11172]
test_io.test_LibSVMIter

Download issue, we really need to implement retries on test_utils.download()

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-10524/7/pipeline/

```

======================================================================

FAIL: test_io.test_LibSVMIter

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_io.py", line 281, in test_LibSVMIter

    check_libSVMIter_news_data()

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_io.py", line 240, in check_libSVMIter_news_data

    news_metadata['origin_name'])

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 1569, in get_bz2_data

    download(url, fname=data_origin_name, dirname=data_dir, overwrite=False)

  File "C:\jenkins_slave\workspace\ut-python-gpu\pkg_vc14_gpu\python\mxnet\test_utils.py", line 1415, in download

    assert r.status_code == 200, "failed to open %s" % url

AssertionError: failed to open https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/news20.t.bz2

-------------------- >> begin captured logging << --------------------

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): apache-mxnet.s3-accelerate.dualstack.amazonaws.com

requests.packages.urllib3.connectionpool: DEBUG: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com:443 "GET /gluon/dataset/news20.t.bz2 HTTP/1.1" 504 958

--------------------- >> end captured logging << ---------------------


```

**Comment by kalyc** [comment]
Thanks for submitting this issue @ThomasDelteil

**Comment by ThomasDelteil** [comment]
I implemented the retry logic in `test_utils.download` and `gluon.utils.download`, hopefully this will not happen again 👍

**Comment by kalyc** [comment]
Thanks for your contributions @ThomasDelteil - could you add a link to the PR here?

**Comment by ThomasDelteil** [comment]
https://github.com/apache/incubator-mxnet/pull/11181
