### ISSUE TITLE
Flaky CI: apt-get update failure

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#11228]
A simple apt-get update failed.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11157/6/pipeline/

```
+ apt-get update

Ign:1 http://cran.rstudio.com/bin/linux/ubuntu trusty/ InRelease

Get:2 http://cran.rstudio.com/bin/linux/ubuntu trusty/ Release [3066 B]

Get:3 http://cran.rstudio.com/bin/linux/ubuntu trusty/ Release.gpg [473 B]

Ign:3 http://cran.rstudio.com/bin/linux/ubuntu trusty/ Release.gpg

Get:4 http://cran.rstudio.com/bin/linux/ubuntu trusty/ Packages [261 kB]

Ign:5 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  InRelease

Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  InRelease

Hit:7 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64  Release

Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1604/x86_64  Release

Hit:11 http://security.ubuntu.com/ubuntu xenial-security InRelease

Hit:12 http://archive.ubuntu.com/ubuntu xenial InRelease

Ign:13 https://dl.bintray.com/sbt/debian  InRelease

Hit:14 http://archive.ubuntu.com/ubuntu xenial-updates InRelease

Get:15 https://dl.bintray.com/sbt/debian  Release [815 B]

Hit:15 https://dl.bintray.com/sbt/debian  Release

Hit:17 http://archive.ubuntu.com/ubuntu xenial-backports InRelease

Fetched 265 kB in 0s (365 kB/s)

Reading package lists...

W: GPG error: http://cran.rstudio.com/bin/linux/ubuntu trusty/ Release: The following signatures were invalid: BADSIG 51716619E084DAB9 Michael Rutter <marutter@gmail.com>

W: The repository 'http://cran.rstudio.com/bin/linux/ubuntu trusty/ Release' is not signed.

+ apt-get install -y r-base r-base-dev libxml2-dev libssl-dev libxt-dev

Reading package lists...

Building dependency tree...

Reading state information...

libxt-dev is already the newest version (1:1.1.5-0ubuntu1).

libxt-dev set to manually installed.

The following additional packages will be installed:

  autoconf automake bzip2-doc cdbs dh-translations icu-devtools ifupdown

  intltool iproute2 isc-dhcp-client isc-dhcp-common libatm1

  libauthen-sasl-perl libbz2-dev libdns-export162 libencode-locale-perl

  libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl

  libfile-mimeinfo-perl libfont-afm-perl libfontenc1 libhtml-form-perl

  libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl

  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl

  libhttp-message-perl libhttp-negotiate-perl libicu-dev libio-html-perl

  libio-socket-ssl-perl libipc-system-simple-perl libisc-export160

  liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl libmnl0

  libncurses5-dev libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl

  libnet-ssleay-perl libpaper-utils libpaper1 libreadline-dev libreadline6-dev

  libsigsegv2 libssl-doc libtcl8.6 libtext-iconv-perl libtie-ixhash-perl

  libtinfo-dev libtk8.6 liburi-perl libwww-perl libwww-robotrules-perl

  libx11-protocol-perl libxaw7 libxcb-shape0 libxml-parser-perl

  libxml-twig-perl libxml-xpathengine-perl libxpm4 libxss1 libxtables11 libxv1

  libxxf86dga1 m4 netbase python-pkg-resources python-scour python-six

  r-base-core r-base-html r-cran-boot r-cran-class r-cran-cluster

  r-cran-codetools r-cran-foreign r-cran-kernsmooth r-cran-lattice r-cran-mass

  r-cran-matrix r-cran-mgcv r-cran-nlme r-cran-nnet r-cran-rpart

  r-cran-spatial r-cran-survival r-doc-html r-recommended tzdata x11-utils

  x11-xserver-utils xdg-utils zip

Suggested packages:

  autoconf-archive gnu-standards autoconf-doc libtool devscripts ppp rdnssd

  iproute2-doc resolvconf avahi-autoipd isc-dhcp-client-ddns apparmor

  libdigest-hmac-perl libgssapi-perl libdata-dump-perl icu-doc

  libcrypt-ssleay-perl ncurses-doc readline-doc tcl8.6 tk8.6

  libauthen-ntlm-perl libunicode-map8-perl libunicode-string-perl

  xml-twig-tools python-setuptools python-rsvg python-cairo ess r-doc-info

  | r-doc-pdf r-mathlib texlive-base texlive-latex-base

  texlive-generic-recommended texlive-fonts-recommended texlive-fonts-extra

  texlive-extra-utils texlive-latex-recommended texlive-latex-extra texinfo

  mozilla | www-browser mesa-utils nickle cairo-5c xorg-docs-core gvfs-bin

The following NEW packages will be installed:

  autoconf automake bzip2-doc cdbs dh-translations icu-devtools ifupdown

  intltool iproute2 isc-dhcp-client isc-dhcp-common libatm1

  libauthen-sasl-perl libbz2-dev libdns-export162 libencode-locale-perl

  libfile-basedir-perl libfile-desktopentry-perl libfile-listing-perl

  libfile-mimeinfo-perl libfont-afm-perl libfontenc1 libhtml-form-perl

  libhtml-format-perl libhtml-parser-perl libhtml-tagset-perl

  libhtml-tree-perl libhttp-cookies-perl libhttp-daemon-perl libhttp-date-perl

  libhttp-message-perl libhttp-negotiate-perl libicu-dev libio-html-perl

  libio-socket-ssl-perl libipc-system-simple-perl libisc-export160

  liblwp-mediatypes-perl liblwp-protocol-https-perl libmailtools-perl libmnl0

  libncurses5-dev libnet-dbus-perl libnet-http-perl libnet-smtp-ssl-perl

  libnet-ssleay-perl libpaper-utils libpaper1 libreadline-dev libreadline6-dev

  libsigsegv2 libssl-dev libssl-doc libtcl8.6 libtext-iconv-perl

  libtie-ixhash-perl libtinfo-dev libtk8.6 liburi-perl libwww-perl

  libwww-robotrules-perl libx11-protocol-perl libxaw7 libxcb-shape0

  libxml-parser-perl libxml-twig-perl libxml-xpathengine-perl libxml2-dev

  libxpm4 libxss1 libxtables11 libxv1 libxxf86dga1 m4 netbase

  python-pkg-resources python-scour python-six r-base r-base-core r-base-dev

  r-base-html r-cran-boot r-cran-class r-cran-cluster r-cran-codetools

  r-cran-foreign r-cran-kernsmooth r-cran-lattice r-cran-mass r-cran-matrix

  r-cran-mgcv r-cran-nlme r-cran-nnet r-cran-rpart r-cran-spatial

  r-cran-survival r-doc-html r-recommended tzdata x11-utils x11-xserver-utils

  xdg-utils zip

0 upgraded, 104 newly installed, 0 to remove and 5 not upgraded.

Need to get 60.3 MB of archives.

After this operation, 151 MB of additional disk space will be used.

WARNING: The following packages cannot be authenticated!

  r-base-core r-cran-boot r-cran-cluster r-cran-foreign r-cran-mass

  r-cran-kernsmooth r-cran-lattice r-cran-nlme r-cran-matrix r-cran-mgcv

  r-cran-rpart r-cran-survival r-cran-class r-cran-nnet r-cran-codetools

  r-recommended r-base r-base-dev r-base-html r-doc-html

E: There were unauthenticated packages and -y was used without --allow-unauthenticated

The command '/bin/sh -c /work/ubuntu_r.sh' returned a non-zero code: 100

into container: False

Traceback (most recent call last):

  File "ci/build.py", line 318, in <module>

    sys.exit(main())

  File "ci/build.py", line 246, in main

    build_docker(platform, docker_binary, registry=docker_registry)

  File "ci/build.py", line 81, in build_docker

    check_call(cmd)

  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['nvidia-docker', 'build', '-f', 'docker/Dockerfile.build.ubuntu_gpu', '--build-arg', 'USER_ID=1001', '--cache-from', 'mxnetci/build.ubuntu_gpu', '-t', 'mxnetci/build.ubuntu_gpu', 'docker']' returned non-zero exit status 100

script returned exit code 1
```

**Comment by marcoabreu** [comment]
Not much we can do about that. We usually cache the Docker layers, but if people make modifications, there's no way around re-installing the packages

**Comment by KellenSunderland** [comment]
@marcoabreu @aaronmarkham I'm seeing more of these errors and don't see why this isn't fixable.  Can we reopen this issue?
