### ISSUE TITLE
Flaky test test_operator_gpu.test_scatter_gather_nd

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#11290]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11199/28/pipeline/712

```
test_operator_gpu.test_scatter_gather_nd ... [19:15:16] src/operator/tensor/./.././../common/../operator/mxnet_op.h:576: Check failed: (err) == (cudaSuccess) Name: mxnet_generic_kernel ErrStr:an illegal memory access was encountered

/work/runtime_functions.sh: line 593:     7 Aborted                 (core dumped) python3.6 -m "nose" --with-xunit --xunit-file nosetests_gpu.xml --verbose tests/python/gpu

build.py: 2018-06-14 19:15:18,486 Running of command in container failed (134): nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/build-centos7-gpu:/work/mxnet -v /home/jenkins_slave/workspace/build-centos7-gpu/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=10G -e CCACHE_DIR=/work/ccache mxnetci/build.centos7_gpu /work/runtime_functions.sh unittest_centos7_gpu

build.py: 2018-06-14 19:15:18,486 You can try to get into the container by using the following command: nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/build-centos7-gpu:/work/mxnet -v /home/jenkins_slave/workspace/build-centos7-gpu/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -ti --entrypoint /bin/bash -e CCACHE_MAXSIZE=10G -e CCACHE_DIR=/work/ccache mxnetci/build.centos7_gpu /work/runtime_functions.sh unittest_centos7_gpu

Traceback (most recent call last):

  File "ci/build.py", line 353, in <module>

    sys.exit(main())

  File "ci/build.py", line 286, in main

    command=command, docker_registry=args.docker_registry, local_ccache_dir=args.ccache_dir)

  File "ci/build.py", line 180, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/build-centos7-gpu:/work/mxnet -v /home/jenkins_slave/workspace/build-centos7-gpu/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=10G -e CCACHE_DIR=/work/ccache mxnetci/build.centos7_gpu /work/runtime_functions.sh unittest_centos7_gpu' returned non-zero exit status 134
```

**Comment by kalyc** [comment]
Thanks for submitting this issue @marcoabreu

**Comment by access2rohit** [comment]
Hi Marco,
    I ran the test 70k times but its not giving me an error. Can you share the steps to reproduce it ?

**Comment by anirudh2290** [comment]
assigned to @reminisce . @access2rohit is working on this.

**Comment by lupesko** [comment]
@marcoabreu looks like @access2rohit asked for more info a while back... can you look into it please?

**Comment by access2rohit** [comment]
@marcoabreu Can you please provide the setup to reproduce the issue ?

**Comment by marcoabreu** [comment]
Hello @access2rohit , the instructions to recreate the setup are available at https://cwiki.apache.org/confluence/display/MXNET/Reproducing+test+results

**Comment by access2rohit** [comment]
@marcoabreu I already tested it using the steps given in the document you mentioned 70k times 
Command: 
MXNET_TEST_COUNT=70000 nosetests --logging-level=DEBUG --verbose -s /home/ubuntu/mxnet/tests/python/gpu/test_operator_gpu.py:test_scatter_gather_nd

using p2.8xLarge instance and I still cannot reproduce the issue.

**Comment by marcoabreu** [comment]
To me it looks like you are running on your local environment instead of docker as described in the guide. I don't think it will make much of a difference, but it could be possible that a dependency we use is causing the problems. We experienced that a few times in the past. Would you mind trying that out just to be sure?
