### ISSUE TITLE
Corrupt image fails Caffe converter test

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#11407]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11358/9/pipeline

```
INFO:root:getting image http://writm.com/wp-content/uploads/2016/08/Cat-hd-wallpapers.jpg

OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115

Traceback (most recent call last):

  File "tools/caffe_converter/test_converter.py", line 108, in <module>

    main()

  File "tools/caffe_converter/test_converter.py", line 102, in main

    test_model_weights_and_outputs(m, args.image_url, gpus[0])

  File "tools/caffe_converter/test_converter.py", line 77, in test_model_weights_and_outputs

    mean_diff_allowed=1e-03, max_diff_allowed=1e-01)

  File "/work/mxnet/tools/caffe_converter/compare_layers.py", line 120, in convert_and_compare_caffe_to_mxnet

    img_rgb = read_image(image_url, image_dims, caffe_mean)

  File "/work/mxnet/tools/caffe_converter/compare_layers.py", line 51, in read_image

    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor



build.py: 2018-06-26 22:42:35,570 Running of command in container failed (1): nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/it-caffe:/work/mxnet -v /home/jenkins_slave/workspace/it-caffe/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_gpu /work/runtime_functions.sh integrationtest_ubuntu_gpu_caffe

build.py: 2018-06-26 22:42:35,570 You can try to get into the container by using the following command: nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/it-caffe:/work/mxnet -v /home/jenkins_slave/workspace/it-caffe/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -ti --entrypoint /bin/bash -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_gpu /work/runtime_functions.sh integrationtest_ubuntu_gpu_caffe

Traceback (most recent call last):

  File "ci/build.py", line 358, in <module>

    sys.exit(main())

  File "ci/build.py", line 291, in main

    command=command, docker_registry=args.docker_registry, local_ccache_dir=args.ccache_dir)

  File "ci/build.py", line 185, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/it-caffe:/work/mxnet -v /home/jenkins_slave/workspace/it-caffe/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_gpu /work/runtime_functions.sh integrationtest_ubuntu_gpu_caffe' returned non-zero exit status 1

script returned exit code 1
```

**Comment by marcoabreu** [comment]
It seems like http://writm.com/wp-content/uploads/2016/08/Cat-hd-wallpapers.jpg is gone now and thus the test is failing. This is breaking CI.

**Comment by cjolivier01** [comment]
can’t you just use any car picture as a replacement?

**Comment by frankfliu** [comment]
@marcoabreu Thank you for reporting the Flaky test, this is added to the to do test improvements

**Comment by ThomasDelteil** [comment]
it's there: https://github.com/dmlc/web-data/blob/master/mxnet/doc/tutorials/python/predict_image/cat.jpg?raw=true

**Comment by KellenSunderland** [comment]
Still getting occasional failures pulling from github.  

Sample output:
```
INFO:root:getting image https://github.com/dmlc/web-data/raw/master/mxnet/doc/tutorials/python/predict_image/cat.jpg
OpenCV(3.4.1) Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /io/opencv/modules/imgproc/src/color.cpp, line 11115
Traceback (most recent call last):
  File "tools/caffe_converter/test_converter.py", line 109, in <module>
    main()
  File "tools/caffe_converter/test_converter.py", line 103, in main
    test_model_weights_and_outputs(m, args.image_url, gpus[0])
  File "tools/caffe_converter/test_converter.py", line 77, in test_model_weights_and_outputs
    mean_diff_allowed=1e-03, max_diff_allowed=1e-01)
  File "/work/mxnet/tools/caffe_converter/compare_layers.py", line 120, in convert_and_compare_caffe_to_mxnet
    img_rgb = read_image(image_url, image_dims, caffe_mean)
  File "/work/mxnet/tools/caffe_converter/compare_layers.py", line 51, in read_image
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(3.4.1) /io/opencv/modules/imgproc/src/color.cpp:11115: error: (-215) scn == 3 || scn == 4 in function cvtColor
```

Reference failed build:
 http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1207/pipeline

**Comment by szha** [comment]
Caffe converter should be deprecated in 2.0 since caffe maintenance has been stopped for a long time.
