### ISSUE TITLE
Flaky test test_operator_gpu.test_scatter_gather_nd

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#11439]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1055/pipeline/

```
test_operator_gpu.test_scatter_gather_nd ... [18:34:15] src/operator/tensor/./.././../common/../operator/mxnet_op.h:576: Check failed: (err) == (cudaSuccess) Name: mxnet_generic_kernel ErrStr:an illegal memory access was encountered

/work/runtime_functions.sh: line 575:     7 Aborted                 (core dumped) nosetests-2.7 $NOSE_COVERAGE_ARGUMENTS --with-xunit --xunit-file nosetests_gpu.xml --verbose tests/python/gpu

build.py: 2018-06-26 18:34:17,456 Running of command in container failed (134): nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-mkldnn-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-mkldnn-gpu/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

build.py: 2018-06-26 18:34:17,456 You can try to get into the container by using the following command: nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-mkldnn-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-mkldnn-gpu/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -ti --entrypoint /bin/bash -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu

Traceback (most recent call last):

  File "ci/build.py", line 358, in <module>

    sys.exit(main())

  File "ci/build.py", line 291, in main

    command=command, docker_registry=args.docker_registry, local_ccache_dir=args.ccache_dir)

  File "ci/build.py", line 185, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'nvidia-docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/ut-python2-mkldnn-gpu:/work/mxnet -v /home/jenkins_slave/workspace/ut-python2-mkldnn-gpu/build:/work/build -v /tmp/ci_ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_gpu /work/runtime_functions.sh unittest_ubuntu_python2_gpu' returned non-zero exit status 134

script returned exit code 1
```

**Comment by marcoabreu** [comment]
Duplicate of https://github.com/apache/incubator-mxnet/issues/11290
