### ISSUE TITLE
test_sample_multinomial test is flaky

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#11487]
test_sample_multinomial is failing non-deterministically.  

Reference test runs:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1082/pipeline
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/master/runs/1082/nodes/735/log/?start=0

Failure output:
```
======================================================================

FAIL: test_operator_gpu.test_sample_multinomial
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 157, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/gpu/../unittest/test_random.py", line 384, in test_sample_multinomial
    mx.test_utils.assert_almost_equal(freq, x[i], rtol=0.20)
  File "/work/mxnet/python/mxnet/test_utils.py", line 493, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 10000000317344786.000000 exceeds tolerance rtol=0.200000, atol=0.000000.  Location of maximum error:(4,), a=0.000200, b=0.000000
 a: array([0.393 , 0.3046, 0.2002, 0.102 , 0.0002])
 b: array([0.4, 0.3, 0.2, 0.1, 0. ], dtype=float32)
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1296093936 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by frankfliu** [comment]
Thank you for submitting the issue! We are labeling it so MXNet community members can help resolve it.

**Comment by anirudh2290** [comment]
Enabled it back here: https://github.com/apache/incubator-mxnet/pull/11366/files. Closing.
