### ISSUE TITLE
NDarray should support __setitem__ with empty key, value

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#11550]
## Description
Consider

```python
import numpy as np
a = np.arange(3)
b = np.array([])
a[:len(b)] = b

import mxnet as mx
a = mx.nd.arange(3)
b = mx.nd.array([])
a[:len(b)] = b
```
The first half works fine, but mxnet fails on the second half:

```
Traceback (most recent call last):
  File "mxnet_test.py", line 10, in <module>
    a[:len(b)] = b
  File "/Users/lllausen/anaconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 444, in __setitem__
    self._set_nd_basic_indexing(key, value)
  File "/Users/lllausen/anaconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 735, in _set_nd_basic_indexing
    dim_size = _get_dim_size(start, stop, step)
  File "/Users/lllausen/anaconda3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2215, in _get_dim_size
    assert start < stop
AssertionError
```

## Environment info (Required)
At least mxnet 1.2 and master

**Comment by szha** [comment]
@reminisce

**Comment by reminisce** [comment]
MXNet does not support empty NDArrays in nature. What is the use case of creating an empty array in MXNet?

**Comment by leezu** [comment]
At least `mx.nd.array([])` doesn't raise an error. Also indexing an array to obtain an empty one works. My impression was that NDarray aims to model np.ndarray as close as feasible?

Regarding use-case, consider having a list of 1D ndarrays of varying length, with some being empty. Padding them to the same length (and creating a 2D array) following the code above will raise the issue. If mxnet matches the numpy behavior code can be simplified. Otherwise an extra if, else statement needs to be added to handle the special case of empty arrays.

**Comment by reminisce** [comment]
Operations on empty arrays will probably result in undefined behavior in MXNet. So not throwing exceptions is not a good indicator showing that it works.

MXNet NDArray is not designed to cover empty array use case as in numpy, because complete shape information (both inputs and outputs of operators) must be obtained in shape inference pass before moving to computation in either imperative or symbolic mode.

**Comment by leezu** [comment]
In that case, would it be better to be explicit about the lack of support for empty arrays and make sure they cannot be instantiated (i.e. raise an Exception)?

**Comment by reminisce** [comment]
I don't know whether forbidding `mx.nd.array([])` would lead to any backward compatibility concern, but it should fail when one of either inputs or outputs of an operator is shape-incomplete. I will check to see why `slice` does not fail when the output is an empty NDArray. Thanks.
