### ISSUE TITLE
Building .rec files fails with "TypeError: object of type 'NoneType' has no len()"

### ISSUE THREAD

**Issue by yharaskrik** [apache/incubator-mxnet#11607]
## Description
When running 
`python tools/im2rec.py --encoding .png mydata example/image-classification/training`

to create the .rec files OpenCV fails to read the image.

## Environment info (Required)
Python3
Windows 10 (Also tried on Linux Subsystem running Ubuntu 16.04

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
```

Package used (Python/R/Scala/Julia):
I'm using Python

## Error Message:
`Creating .rec file from /home/jaybell/incubator-mxnet/mydata_train.lst in /home/jaybell/incubator-mxnet
multiprocessing not available, fall back to single threaded encoding
imread read blank (None) image for file: /home/jaybell/incubator-mxnet/example/image-classification/training/gopro/964.png
Traceback (most recent call last):
  File "tools/im2rec.py", line 317, in <module>
    record.write_idx(item[0], s)
  File "/home/jaybell/building-multimedia-metadata-collections-capstone-499-mm-deep-learning-team/logo-scrape/venv/lib/python3.5/site-packages/mxnet/recordio.py", line 285, in write_idx
    self.write(buf)
  File "/home/jaybell/building-multimedia-metadata-collections-capstone-499-mm-deep-learning-team/logo-scrape/venv/lib/python3.5/site-packages/mxnet/recordio.py", line 135, in write
    ctypes.c_size_t(len(buf))))`

Using the base example in [https://github.com/apache/incubator-mxnet/tree/master/example/image-classification](https://github.com/apache/incubator-mxnet/tree/master/example/image-classification)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. python tools/im2rec.py --list --recursive --train-ratio 0.95 mydata example/image-classification/training/
2. python tools/im2rec.py --encoding .png mydata example/image-classification/training

## What have you tried to solve it?

1. Made sure the images are there (they are.)
2. On windows tried to switch up the file paths (using / instead of \ and vise versa)
3. Updated packages
4. Tried on both windows and linux. Same issue both times.
5. Ran diagnose script - nothing out of the ordinary came up.

**Comment by yharaskrik** [comment]
Thanks for the response! I look forward to seeing a solution!

**Comment by ankkhedia** [comment]
Hi @evanfitzking @yharaskrik Are you facing the above issue only with png dataset? I didn't face with standard imagenet dataset(.jpeg files). Also, if you could share a small sample of your dataset, it would be great help in debugging the issue.

**Comment by ankkhedia** [comment]
@evanfitzking @yharaskrik I even tried reproducing the issue with CIFAR dataset(png format files) but couldn't reproduce. Could you please provide more details as asked above.

**Comment by ankkhedia** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by yharaskrik** [comment]
My apologies I thought I responded to this issue. It turns out that the step before when I was converting the images to PNGs some of the metadata was missing/corrupted and thus building the .rec files failed.

**Comment by ankkhedia** [comment]
@nswamy @sandeep-krishnamurthy Could you please close this issue as the issue is resolved.
