### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by adaaaaaa** [apache/incubator-mxnet#11610]
Windows 10 x64
python 3.6.6
install mxnet and import correctly,but install mxnet-mkl import with an error like this:

`import mxnet
Traceback (most recent call last):

  File "<ipython-input-1-1eadd2d362f9>", line 1, in <module>
    import mxnet

  File "f:\python36\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned

  File "f:\python36\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass

  File "f:\python36\lib\site-packages\mxnet\base.py", line 174, in <module>
    _LIB = _load_lib()

  File "f:\python36\lib\site-packages\mxnet\base.py", line 166, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)

  File "f:\python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 126] 找不到指定的模块。`
how to deal...

**Comment by yajiedesign** [comment]
this because lost dll.please run depend(http://www.dependencywalker.com/) check what dll lost and tell me.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this _Windows_, _Build_

**Comment by adaaaaaa** [comment]
@yajiedesign what dll should i try to check? never use that software before...

**Comment by yajiedesign** [comment]
@adaaaaaa libmxnet.dll

**Comment by adaaaaaa** [comment]
@yajiedesign  tons of DLL?
![default](https://user-images.githubusercontent.com/23206387/43178484-508deada-9000-11e8-82fc-c47269ba18cd.png)

**Comment by adaaaaaa** [comment]
anyone can help?

**Comment by zhreshold** [comment]
@adaaaaaa  missing mkldnn.dll and mklml.dll ,  are they included in the package?

You can find mklml.dll here: https://github.com/intel/mkl-dnn/releases/download/v0.14/mklml_win_2018.0.3.20180406.zip
Not sure about mkldnn prebuilt dll, I think it's easier to build though.

**Comment by yajiedesign** [comment]
@adaaaaaa I do some fix.please wait tomorrow.

**Comment by kohillyang** [comment]
where can I find mkldnn.dll?

**Comment by adaaaaaa** [comment]
@yajiedesign gluon's tutorial "cnn-scratch" using mxnet-mkl version 20180731 perform badly...
executed in 3m 40s
while in linux using mxnet-cu92mkl use cpu it executed in 23.8s nearly 10 times less...

**Comment by kohillyang** [comment]
@adaaaaaa Do you have mkldnn.dll? Or can you tell me where should I find it? Thanks.

**Comment by adaaaaaa** [comment]
no i don't have...the newest version is fine now , don't need to fix the ***.dll now...

**Comment by yajiedesign** [comment]
@adaaaaaa i don't know,do you can test mxnet-cu92mkl in windows?

**Comment by adaaaaaa** [comment]
no...cuda is too big...i'm not going to try it in windows...
in Windows,i'm sure mxnet-mkl using cpu to executed "cnn-scratch" in 3m 40s
and in Linux using gpu to executed "cnn-scratch" in 5.9s,
in Linux using cpu to executed "cnn-scratch" in 23.8s.

**Comment by adaaaaaa** [comment]
really a big space to improve...
while other interesting things is i test single float point in aida64...
it shows that 1070ti is 10 times faster than i7-8700K
while in Linux "cnn-scratch benchmark" it's only 4 times faster...
something wrong in gpu version in mxnet?

**Comment by pengzhao-intel** [comment]
@adaaaaaa @kohillyang where is cnn-scratch?

**Comment by adaaaaaa** [comment]
other "benchmark" is the latest tutorial's lenet tutorial...
in Windows,using mxnet-mkl,cpu,executed in 26,27s every epoch
in Linux,using mxnet-cu92mkl,cpu,executed in 3.5 to 3.9s every epoch;
gpu,executed in 1.2 to 1.4s every epoch...
@yajiedesign @pengzhao-intel

**Comment by adaaaaaa** [comment]
any process now?

**Comment by pengzhao-intel** [comment]
WIP to verify the performance. 

FYI, the performance on Linux is fully validated; however, the Window is w/ lower priority.
And in our local, we don't have much windows system to reproduce the issue.

I suggest you try Linux first. If you see the same perf issue on Linux, it will be very helpful.
