### ISSUE TITLE
Write a new operator by myself,error says Backward is not implemented.but i write it indeed

### ISSUE THREAD

**Issue by Ericargus** [apache/incubator-mxnet#11640]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
I write a new operator ,(following by official operator),i cp it to src and rebuild mxnet, everything is fine.but when i run the  python code,the error says Backward is not implemented.I don't know where is wrong. 
## Environment info (Required)
mxnet 1.3.0
ubuntu 16.04
python 3.5
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.
src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:107: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "train_end2end.py", line 202, in <module>
    main()
  File "train_end2end.py", line 199, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_end2end.py", line 161, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/module/base_module.py", line 529, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/zxyu/rcnn/rcnn/core/module.py", line 227, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/module/module.py", line 772, in update_metric
    self._exec_group.update_metric(eval_metric, labels, pre_sliced)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/module/executor_group.py", line 639, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/metric.py", line 304, in update_dict
    metric.update_dict(labels, preds)
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/metric.py", line 132, in update_dict
    self.update(label, pred)
  File "/home/zxyu/rcnn/rcnn/core/metric.py", line 51, in update
    pred_label = mx.ndarray.argmax_channel(pred).asnumpy().astype('int32')
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/ndarray/ndarray.py", line 1910, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/base.py", line 210, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [12:15:16] include/mxnet/operator.h:110: Backward is not implemented

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x5b) [0x7f37abf6e98b]
[bt] (1) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f37abf6f4f8]
[bt] (2) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(mxnet::op::OperatorState::Backward(mxnet::OpContext const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::TBlob, std::allocator<mxnet::TBlob> > const&)+0x2ec) [0x7f37ae5e086c]
[bt] (3) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(mxnet::exec::StatefulComputeExecutor::Run(mxnet::RunContext, bool)+0x59) [0x7f37aec95d89]
[bt] (4) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(+0x39514f3) [0x7f37aec674f3]
[bt] (5) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(mxnet::engine::ThreadedEngine::ExecuteOprBlock(mxnet::RunContext, mxnet::engine::OprBlock*)+0x8e5) [0x7f37aebbd0f5]
[bt] (6) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(void mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0>(mxnet::Context, bool, mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0>*, std::shared_ptr<dmlc::ManualEvent> const&)+0xeb) [0x7f37aebd41fb]
[bt] (7) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(std::_Function_handler<void (std::shared_ptr<dmlc::ManualEvent>), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#3}::operator()() const::{lambda(std::shared_ptr<dmlc::ManualEvent>)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<dmlc::ManualEvent>&&)+0x4e) [0x7f37aebd446e]
[bt] (8) /usr/local/lib/python3.5/dist-packages/mxnet-1.3.0-py3.5.egg/mxnet/libmxnet.so(std::thread::_Impl<std::_Bind_simple<std::function<void (std::shared_ptr<dmlc::ManualEvent>)> (std::shared_ptr<dmlc::ManualEvent>)> >::_M_run()+0x4a) [0x7f37aebbc6fa]
[bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f377c544c80]


```

Package used (Python/R/Scala/Julia):
(I'm using ...)python

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
(Paste the complete error message, including stack trace.)

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by marcoabreu** [comment]
Hello, please show us your code.

**Comment by Ericargus** [comment]
I  have solved it.

**Comment by Ericargus** [comment]
@marcoabreu  i have solved it

**Comment by marcoabreu** [comment]
Awesome! Do you mind sharing what you did to solve the problem?

**Comment by Ericargus** [comment]
@marcoabreu but i have a new problem.(error reports "TBlob.get: device type do not match specified type";),I don't know what wrong.

**Comment by Ericargus** [comment]
@marcoabreu  I'm careless.I solved it by copy similar offical operator,and modified somwhere what i need.and the problem dissappear.but i get new issue that says TBlob.get: device type do not match specified type

**Comment by marcoabreu** [comment]
For these kind of things I'd like to to invite a thread at discuss.mxnet.io :)
P.s. it's probably related to you being in the wrong context (cpu or GPU) while the operator you wrote only supports a different context. Search for "cpu" "GPU" and "xpu" in your code :)
