### ISSUE TITLE
non-actionable exit code when rat check failed

### ISSUE THREAD

**Issue by srochel** [apache/incubator-mxnet#11666]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
RAT check failed, but end of build queue doesn't contain easy to understand exit message.

Example:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11325/34/pipeline
....
2018-07-12 09:49:55,633 The following files do not contain a valid license, you can use `python tools/license_header.py add [file]` to addthem automatically: 

....

build.py: 2018-07-12 09:49:56,001 Running of command in container failed (1): docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/sanity-lint:/work/mxnet -v /home/jenkins_slave/workspace/sanity-lint/build:/work/build -v /efs-ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_cpu /work/runtime_functions.sh sanity_check

build.py: 2018-07-12 09:49:56,001 You can try to get into the container by using the following command: docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/sanity-lint:/work/mxnet -v /home/jenkins_slave/workspace/sanity-lint/build:/work/build -v /efs-ccache:/work/ccache -u 1001:1001 -ti --entrypoint /bin/bash -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_cpu /work/runtime_functions.sh sanity_check

Traceback (most recent call last):

  File "ci/build.py", line 362, in <module>

    sys.exit(main())

  File "ci/build.py", line 295, in main

    command=command, docker_registry=args.docker_registry, local_ccache_dir=args.ccache_dir)

  File "ci/build.py", line 189, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/sanity-lint:/work/mxnet -v /home/jenkins_slave/workspace/sanity-lint/build:/work/build -v /efs-ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_cpu /work/runtime_functions.sh sanity_check' returned non-zero exit status 1

script returned exit code 1

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please label this _CI_

**Comment by marcoabreu** [comment]
Hello Steffen,

thanks for your feature request. Just to clarify: The error log you are seeing at the end is part of our Docker bootstrapping - I have separated it with a ``>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>`` in the following log:
```
2018-07-12 09:49:55,633 The following files do not contain a valid license, you can use `python tools/license_header.py add [file]` to addthem automatically: 

2018-07-12 09:49:55,633 tests/python/tensorrt/test_cycle.py

2018-07-12 09:49:55,633 tests/python/tensorrt/test_tensorrt_resnet_resnext.py

2018-07-12 09:49:55,633 example/image-classification/tensorrt/test_tensorrt_lenet5.sh

2018-07-12 09:49:55,633 example/image-classification/tensorrt/test_tensorrt_resnet_resnext.sh

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

build.py: 2018-07-12 09:49:56,001 Running of command in container failed (1): docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/sanity-lint:/work/mxnet -v /home/jenkins_slave/workspace/sanity-lint/build:/work/build -v /efs-ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_cpu /work/runtime_functions.sh sanity_check

build.py: 2018-07-12 09:49:56,001 You can try to get into the container by using the following command: docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/sanity-lint:/work/mxnet -v /home/jenkins_slave/workspace/sanity-lint/build:/work/build -v /efs-ccache:/work/ccache -u 1001:1001 -ti --entrypoint /bin/bash -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_cpu /work/runtime_functions.sh sanity_check

Traceback (most recent call last):

  File "ci/build.py", line 362, in <module>

    sys.exit(main())

  File "ci/build.py", line 295, in main

    command=command, docker_registry=args.docker_registry, local_ccache_dir=args.ccache_dir)

  File "ci/build.py", line 189, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker run --rm -t --shm-size=500m -v /home/jenkins_slave/workspace/sanity-lint:/work/mxnet -v /home/jenkins_slave/workspace/sanity-lint/build:/work/build -v /efs-ccache:/work/ccache -u 1001:1001 -e CCACHE_MAXSIZE=500G -e CCACHE_TEMPDIR=/tmp/ccache -e CCACHE_DIR=/work/ccache -e CCACHE_LOGFILE=/tmp/ccache.log mxnetci/build.ubuntu_cpu /work/runtime_functions.sh sanity_check' returned non-zero exit status 1

script returned exit code 1
```

Everything above that line is the error of the run and everything below that line is the usual boilerplate that is being printed because the docker run failed. 

Could you elaborate in how far you would like this to be improved?
