### ISSUE TITLE
Flaky Perl test: test_loss.test_dynamic

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#11680]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11326/13/pipeline
```
t/test_loss.t             (Wstat: 256 Tests: 30 Failed: 1)

  Failed test:  14

  Non-zero exit status: 1

Files=30, Tests=14686, 691 wallclock secs ( 1.31 usr  0.42 sys + 14102.01 cusr 95.05 csys = 14198.79 CPU)

Result: FAIL

Failed 1/30 test programs. 1/14686 subtests failed.

Makefile:1203: recipe for target 'test_dynamic' failed

make: *** [test_dynamic] Error 255

build.py: 2018-07-12 22:50:45,148 Running of command in container failed (255):

docker\

	run\

	--rm\

	-t\

	--shm-size=500m\

	-v\

	/home/jenkins_slave/workspace/ut-perl-cpu:/work/mxnet\

	-v\

	/home/jenkins_slave/workspace/ut-perl-cpu/build:/work/build\

	-v\

	/efs-ccache:/work/ccache\

	-u\

	1001:1001\

	-e\

	CCACHE_MAXSIZE=500G\

	-e\

	CCACHE_TEMPDIR=/tmp/ccache\

	-e\

	CCACHE_DIR=/work/ccache\

	-e\

	CCACHE_LOGFILE=/tmp/ccache.log\

	mxnetci/build.ubuntu_cpu\

	/work/runtime_functions.sh\

	unittest_ubuntu_cpugpu_perl



build.py: 2018-07-12 22:50:45,148 You can get into the container by adding the -i option

Traceback (most recent call last):

  File "ci/build.py", line 384, in <module>

    sys.exit(main())

  File "ci/build.py", line 313, in main

    local_ccache_dir=args.ccache_dir, interactive=args.interactive)

  File "ci/build.py", line 206, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker\

	run\

	--rm\

	-t\

	--shm-size=500m\

	-v\

	/home/jenkins_slave/workspace/ut-perl-cpu:/work/mxnet\

	-v\

	/home/jenkins_slave/workspace/ut-perl-cpu/build:/work/build\

	-v\

	/efs-ccache:/work/ccache\

	-u\

	1001:1001\

	-e\

	CCACHE_MAXSIZE=500G\

	-e\

	CCACHE_TEMPDIR=/tmp/ccache\

	-e\

	CCACHE_DIR=/work/ccache\

	-e\

	CCACHE_LOGFILE=/tmp/ccache.log\

	mxnetci/build.ubuntu_cpu\

	/work/runtime_functions.sh\

	unittest_ubuntu_cpugpu_perl' returned non-zero exit status 255

script returned exit code 1
```

**Comment by haojin2** [comment]
suggested labels: Perl, Flaky, Test

**Comment by sergeykolychev** [comment]
@haojin2 I'll take a look ad will fix.

**Comment by haojin2** [comment]
Thanks a lot for your quick response!

**Comment by haojin2** [comment]
@sergeykolychev Seems like `test_dynamic` is failing again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-11886/1/pipeline/865.

**Comment by sergeykolychev** [comment]
I'll take a look.

**Comment by sergeykolychev** [comment]
@haojin2 
That was network error in downloading from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-images-idx3-ubyte.gz
Btw @szha I noticed that all tests re-download all data files every time, back in travis days these were cached, is there any plans to implement caching in the current system ?

**Comment by haojin2** [comment]
@sergeykolychev I'm not sure about that part, maybe @marcoabreu has an answer?

**Comment by marcoabreu** [comment]
We thought about it but didn't have time to work on it. We will need a cache server for our edge devices most likely anyways, so we will probably then just use the same cache server for both locations.
