### ISSUE TITLE
test_executor.test_dot has fixed seed that can mask flakiness

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#11686]
The unit test in title have been using fixed seed to mask flakiness. Suggested action:
1. Evaluate whether the test is flaky without fixed seed. If not, remove seed. Else move to 2
2. If test is flaky, determine whether it's an actual uncaught edge case. If so, fix the operator. Else move to 3
3. If numerical instability is inevitable, adjust tolerance level appropriately.

**Comment by apeforest** [comment]
Thanks for filing this issue. We will investigate this Flaky test

**Comment by roywei** [comment]
Reproducible using seed: `MXNET_TEST_SEED=1509417289`
Will investigate and try to increase tolerance. 
```
Ran 1 test in 34.693s

FAILED (failures=1)
ubuntu@ip-172-31-81-100:~/incubator-mxnet$  MXNET_TEST_SEED=1509417289 nosetests --logging-level=DEBUG --verbose -s  tests/python/unittest/test_e
xecutor.py:test_dot
/usr/local/lib/python3.5/dist-packages/nose/util.py:453: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  inspect.getargspec(func)
[INFO] Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=633029204 to reproduce.
/home/ubuntu/incubator-mxnet/tests/python/unittest/common.py:244: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('*** test-level seed set: all "@with_seed()" tests run deterministically ***')
[WARNING] *** test-level seed set: all "@with_seed()" tests run deterministically ***
test_executor.test_dot ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1509417289 to reproduce.
FAIL

======================================================================
FAIL: test_executor.test_dot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/incubator-mxnet/tests/python/unittest/common.py", line 172, in test_new
    orig_test(*args, **kwargs)
  File "/home/ubuntu/incubator-mxnet/tests/python/unittest/test_executor.py", line 132, in test_dot
    sf = mx.symbol.dot)
  File "/home/ubuntu/incubator-mxnet/tests/python/unittest/test_executor.py", line 78, in check_bind_with_uniform
    assert reldiff(rhs_grad.asnumpy(), rhs_grad2) < 1e-6
AssertionError: 
-------------------- >> begin captured logging << --------------------
common: INFO: Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=633029204 to reproduce.
common: WARNING: *** test-level seed set: all "@with_seed()" tests run deterministically ***
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1509417289 to reproduce.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.153s

FAILED (failures=1)
```

**Comment by roywei** [comment]
#11978  should fix it
