### ISSUE TITLE
flaky kvstore test

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#11801]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1221/pipeline/

```

+ ../../tools/launch.py -n 7 --launcher local python dist_sync_kvstore.py --type=gluon_step_cpu

terminate called after throwing an instance of 'dmlc::Error'

  what():  [05:33:59] /work/mxnet/3rdparty/ps-lite/include/ps/kv_app.h:587: Check failed: lens->size() == keys.size() (2 vs. 1) 



Stack trace returned 9 entries:

[bt] (0) /work/mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x55) [0x7fccbfc095b5]

[bt] (1) /work/mxnet/python/mxnet/../../lib/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7fccbfc0a0e8]

[bt] (2) /work/mxnet/python/mxnet/../../lib/libmxnet.so(int ps::KVWorker<char>::Pull_<ps::SArray<char>, ps::SArray<int> >(ps::SArray<unsigned long> const&, ps::SArray<char>*, ps::SArray<int>*, int, std::function<void ()> const&)::{lambda()#1}::operator()()+0x71d) [0x7fccc2a7a5ed]

[bt] (3) /work/mxnet/python/mxnet/../../lib/libmxnet.so(ps::KVWorker<char>::RunCallback(int)+0xf6) [0x7fccc2a22f16]

[bt] (4) /work/mxnet/python/mxnet/../../lib/libmxnet.so(ps::KVWorker<char>::Process(ps::Message const&)+0x2b4) [0x7fccc2a75d54]

[bt] (5) /work/mxnet/python/mxnet/../../lib/libmxnet.so(ps::Customer::Receiving()+0x57c) [0x7fccc2a82c5c]

[bt] (6) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7fccbc442c80]

[bt] (7) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fccc724d6ba]

[bt] (8) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fccc6f8341d]





Exception in thread Thread-4:

Traceback (most recent call last):

  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

    self.run()

  File "/usr/lib/python2.7/threading.py", line 754, in run

    self.__target(*self.__args, **self.__kwargs)

  File "/work/mxnet/tools/../3rdparty/dmlc-core/tracker/dmlc_tracker/local.py", line 44, in exec_cmd

    raise RuntimeError('Get nonzero return code=%d' % ret)

RuntimeError: Get nonzero return code=-6



Sending interrupt signal to process

Terminated

script returned exit code 143
```

**Comment by larroy** [comment]
Is it failing? Why did it get reverted?
