### ISSUE TITLE
Segmentation fault when Fine-tuning an ONNX model with MXNet/Gluon

### ISSUE THREAD

**Issue by lyd911** [apache/incubator-mxnet#11816]
## Description
I got an segmentation when following the tutorial of MXNet doc Fine-tuning an ONNX model with MXNet/Gluon(http://mxnet.incubator.apache.org/versions/1.2.0/tutorials/onnx/fine_tuning_gluon.html). The segmentation fault occurred when doing Training loop, though get an output with decent Accuracy of 0.7812, the kernel died and couldn't continue next steps. I run the code on my own Mac with Jupyter Notebook.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.5
Compiler     : GCC 4.2.1 (Apple Inc. build 5666) (dot 3)
Build        : ('v3.6.5:f59c0932b4', 'Mar 28 2018 03:03:55')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 10.0.1
Directory    : /anaconda3/lib/python3.6/site-packages/pip
----------MXNet Info-----------
/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Version      : 1.2.0
Directory    : /anaconda3/lib/python3.6/site-packages/mxnet
Commit Hash   : 297c64fd2ee404612aa3ecc880b940fb2538039c
----------System Info----------
Platform     : Darwin-17.6.0-x86_64-i386-64bit
system       : Darwin
node         : ***deMacBook-Pro.local
release      : 17.6.0
version      : Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID SMAP RDSEED ADX IPT SGX FPU_CSDS MPX CLFSOPT'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'

```

## Build info (Required if built from source)

iPython 6.4.0
Jupyter Notebook 5.5.0, python 3 kernel.

## Error Message:

```
Segmentation fault: 11

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x0000000107a96684 libmxnet.so + 26244
[bt] (1) 1   libmxnet.so                         0x0000000109060886 MXTVMBridge + 3527126
[bt] (2) 2   libsystem_platform.dylib            0x00007fff641fff5a _sigtramp + 26
[bt] (3) 3   ???                                 0x00007000078df0e0 0x0 + 123145429053664
[bt] (4) 4   libmxnet.so                         0x0000000107aa1577 libmxnet.so + 71031
[bt] (5) 5   libmxnet.so                         0x0000000107aa1321 libmxnet.so + 70433
[bt] (6) 6   libmxnet.so                         0x0000000108cb032e MXNDListFree + 1309662
[bt] (7) 7   libmxnet.so                         0x0000000107a98709 libmxnet.so + 34569
[bt] (8) 8   libmxnet.so                         0x0000000107aa70e5 libmxnet.so + 94437
[bt] (9) 9   libmxnet.so                         0x0000000107c3ca9b libmxnet.so + 1755803
```

some following information:
```
[I 12:14:57.593 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
kernel aa9d9671-576d-42b2-8fea-5d9336aa5e4a restarted
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Address already in use
[I 12:15:00.615 NotebookApp] KernelRestarter: restarting kernel (2/5), keep random ports
kernel aa9d9671-576d-42b2-8fea-5d9336aa5e4a restarted
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Address already in use
[I 12:15:03.622 NotebookApp] KernelRestarter: restarting kernel (3/5), keep random ports
kernel aa9d9671-576d-42b2-8fea-5d9336aa5e4a restarted
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Address already in use
[I 12:15:06.631 NotebookApp] KernelRestarter: restarting kernel (4/5), keep random ports
kernel aa9d9671-576d-42b2-8fea-5d9336aa5e4a restarted
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
    raise ZMQError(errno)
zmq.error.ZMQError: Address already in use
[W 12:15:09.648 NotebookApp] KernelRestarter: restart failed
```

## Steps to reproduce

1. URL: http://mxnet.incubator.apache.org/versions/1.2.0/tutorials/onnx/fine_tuning_gluon.html
2. It will take some time in Training loop, my fault occurred after Batch[200] was trained

## Couple of lines in my ipynb
```
# The original code of Training loop
```
output:
Batch [20] loss: 3.3410
Batch [40] loss: 2.5544
Batch [60] loss: 3.3172
Batch [80] loss: 1.4596
Batch [100] loss: 1.2674
Batch [120] loss: 1.3009
Batch [140] loss: 1.1046
Batch [160] loss: 0.9612
Batch [180] loss: 1.0728
Batch [200] loss: 1.2947
Epoch [0] Test Accuracy 0.7812

**Comment by nswamy** [comment]
@Roshrini ?

**Comment by Roshrini** [comment]
@lyd911 Thank you for trying out this tutorial. I ran it in my environment: MacOS, jupyter notebook with python 3 kernel, MXNet v1.3 and ONNX v1.2.1
It takes lot of time but runs fine.. I didnt get any segmentation fault. Can you please check which ONNX version you are using? MXNet import, export functionality currently supports ONNX v1.2.1
