### ISSUE TITLE
All the tests in tools/coreml package are failing

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#11841]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
Currently all the tests for mxnet-to-coreml converter under the tools/coreml package are failing due to lack of maintenance. We need to update them to keep up with the latest release

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.15')
('Compiler     :', 'GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)')
('Build        :', ('default', 'May  1 2018 16:44:37'))
('Arch         :', ('64bit', ''))
------------Pip Info-----------
('Version      :', '10.0.1')
('Directory    :', '/Users/lnyuan/.virtualenvs/mxnet2/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '1.3.0')
('Directory    :', '/Users/lnyuan/work/incubator-mxnet/python/mxnet')
Hashtag not found. Not installed from pre-built package.
----------System Info----------
('Platform     :', 'Darwin-16.7.0-x86_64-i386-64bit')
('system       :', 'Darwin')
('node         :', '88e9fe759c49.ant.amazon.com')
('release      :', '16.7.0')
('version      :', 'Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'i386')
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 BMI2 INVPCID SMAP RDSEED ADX IPT SGX FPU_CSDS MPX CLFSOPT
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.brand_string: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0121 sec, LOAD: 0.6747 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0117 sec, LOAD: 0.4044 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0217 sec, LOAD: 0.1044 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0195 sec, LOAD: 0.0761 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0173 sec, LOAD: 0.2269 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0216 sec, LOAD: 0.1687 sec.
```

Package used (Python/R/Scala/Julia):
Python

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
g++

MXNet commit hash:
e4134c8270c1b944278b1e0331313074b1d97cc0

## Error Message:
======================================================================
ERROR: test_pred_vgg16 (test_mxnet_models.ModelsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/lnyuan/work/mxnet-master/tools/coreml/test/test_mxnet_models.py", line 141, in test_pred_vgg16
    "http://data.mxnet.io/models/imagenet/vgg/vgg16-0000.params"])
  File "/Users/lnyuan/work/mxnet-master/tools/coreml/test/test_mxnet_models.py", line 116, in _test_model
    coreml_pred = coreml_model.predict(_mxnet_remove_batch(input_data)).values()[0].flatten()
  File "/Users/lnyuan/.virtualenvs/mxnet2/lib/python2.7/site-packages/coremltools/models/model.py", line 267, in predict
    raise Exception('Model prediction is only supported on macOS version 10.13 or later.')
Exception: Model prediction is only supported on macOS version 10.13 or later.

## Minimum reproducible example
All the tests under tools/coreml/test

## Steps to reproduce
1. cd tools/coreml/test
2. nosetests -v .

## What have you tried to solve it?
1.
2.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy Please help to label this issue _Test_

**Comment by apeforest** [comment]
Created a [JIRA](https://issues.apache.org/jira/browse/MXNET-707) ticket to track this issue. I will work on it.

**Comment by apeforest** [comment]
As displayed in the error message "Exception: Model prediction is only supported on macOS version 10.13 or later.", the tests convert MXNet models into CoreML models and use CoreML to predict. This prediction is not supported on Mac OS 10.12. 

I have disabled the prediction and tests will pass.

**Comment by lupesko** [comment]
@apeforest any update?

**Comment by apeforest** [comment]
@lupesko I have created a simple test that can run on Mac OS 10.12. The PR is https://github.com/apache/incubator-mxnet/pull/11952

Since our CI does not include Mac OS platform, I am working with @marcoabreu to add this to the manual test suite.

**Comment by apeforest** [comment]
@sandeep-krishnamurthy @nswamy Please close this issue.
