### ISSUE TITLE
Scala OSX unittest failure

### ISSUE THREAD

**Issue by lanking520** [apache/incubator-mxnet#11988]
Currently Scala unittest is failed on master branch due to the missing links on the native packages. Open this issue to track the update on the fixes.

@nswamy @yzhliu @andrewfayres 
```
- plus *** FAILED ***
  java.util.NoSuchElementException: key not found: _plus_scalar
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at org.apache.mxnet.NDArray$.genericNDArrayFunctionInvoke(NDArray.scala:65)
  at org.apache.mxnet.NDArray.$plus(NDArray.scala:773)
  at org.apache.mxnet.NDArraySuite$$anonfun$9.apply(NDArraySuite.scala:70)
  at org.apache.mxnet.NDArraySuite$$anonfun$9.apply(NDArraySuite.scala:68)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
- minus *** FAILED ***
  java.util.NoSuchElementException: key not found: _minus_scalar
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at org.apache.mxnet.NDArray$.genericNDArrayFunctionInvoke(NDArray.scala:65)
  at org.apache.mxnet.NDArray.$minus(NDArray.scala:797)
  at org.apache.mxnet.NDArraySuite$$anonfun$10.apply(NDArraySuite.scala:81)
  at org.apache.mxnet.NDArraySuite$$anonfun$10.apply(NDArraySuite.scala:79)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
- multiplication *** FAILED ***
  java.util.NoSuchElementException: key not found: _mul_scalar
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at org.apache.mxnet.NDArray$.genericNDArrayFunctionInvoke(NDArray.scala:65)
  at org.apache.mxnet.NDArray.$times(NDArray.scala:821)
  at org.apache.mxnet.NDArraySuite$$anonfun$11.apply(NDArraySuite.scala:93)
  at org.apache.mxnet.NDArraySuite$$anonfun$11.apply(NDArraySuite.scala:91)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
- division *** FAILED ***
  java.util.NoSuchElementException: key not found: _minus_scalar
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at org.apache.mxnet.NDArray$.genericNDArrayFunctionInvoke(NDArray.scala:65)
  at org.apache.mxnet.NDArray.$minus(NDArray.scala:797)
  at org.apache.mxnet.NDArraySuite$$anonfun$12.apply(NDArraySuite.scala:104)
  at org.apache.mxnet.NDArraySuite$$anonfun$12.apply(NDArraySuite.scala:102)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
- full
- clip *** FAILED ***
  java.util.NoSuchElementException: key not found: clip
  at scala.collection.MapLike$class.default(MapLike.scala:228)
  at scala.collection.AbstractMap.default(Map.scala:59)
  at scala.collection.MapLike$class.apply(MapLike.scala:141)
  at scala.collection.AbstractMap.apply(Map.scala:59)
  at org.apache.mxnet.NDArray$.genericNDArrayFunctionInvoke(NDArray.scala:65)
  at org.apache.mxnet.NDArray$.clip(NDArray.scala:34)
  at org.apache.mxnet.NDArraySuite$$anonfun$14.apply(NDArraySuite.scala:124)
  at org.apache.mxnet.NDArraySuite$$anonfun$14.apply(NDArraySuite.scala:121)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
```

**Comment by lanking520** [comment]
Problem fixed now. Please reopen if you are facing something like this again.

**Comment by vandanavk** [comment]
@mxnet-label-bot [Scala, Test]
