### ISSUE TITLE
Backwards compatibility checker:  Parameter 'model.1._unfused.0.l_cell.i2h_bias' is missing in file 'lstm_gluon_save_parameters_api-params'

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#12046]
http://jenkins.mxnet-ci.amazon-ml.com/job/restricted-backwards-compatibility-checker/8/console

```
INFO:root:Assertion passed for model : lenet_gluon_hybrid_export_api
INFO:root:Performing inference for model/API lstm_gluon_save_parameters_api and model
INFO:root:Fetching files for MXNet version : 1.0.0
ERROR:root:No trained models found under path : 1.0.0/lstm_gluon_save_parameters_api
WARNING:root:No training files found for lstm_gluon_save_parameters_api for MXNet version : 1.0.0
INFO:root:Fetching files for MXNet version : 1.1.0
ERROR:root:No trained models found under path : 1.1.0/lstm_gluon_save_parameters_api
WARNING:root:No training files found for lstm_gluon_save_parameters_api for MXNet version : 1.1.0
INFO:root:Fetching files for MXNet version : 1.2.0
ERROR:root:No trained models found under path : 1.2.0/lstm_gluon_save_parameters_api
WARNING:root:No training files found for lstm_gluon_save_parameters_api for MXNet version : 1.2.0
INFO:root:Fetching files for MXNet version : 1.2.1
Traceback (most recent call last):
  File "model_backwards_compat_inference.py", line 137, in <module>
    test_lstm_gluon_load_parameters_api()
  File "model_backwards_compat_inference.py", line 124, in test_lstm_gluon_load_parameters_api
    loaded_model.load_parameters(model_name + '-params')
  File "/work/mxnet/python/mxnet/gluon/block.py", line 394, in load_parameters
    name, filename, _brief_print_list(loaded.keys()))
AssertionError: Parameter 'model.1._unfused.0.l_cell.i2h_bias' is missing in file 'lstm_gluon_save_parameters_api-params', which contains parameters: 'model.2.weight', 'model.0.weight', 'model.4.bias', ..., 'model.4.weight', 'model.1._unfused.0.i2h_weight', 'model.2.bias', 'model.1._unfused.0.i2h_bias'. Set allow_missing=True to ignore missing parameters.
```

**Comment by marcoabreu** [comment]
@piyushghai

**Comment by haojin2** [comment]
@szha

**Comment by haojin2** [comment]
@szha This should be closed as your fix is merged.

**Comment by lupesko** [comment]
@marcoabreu FYI fix is merged, you can close the issue unless you still see the failure on MBCC CI.

**Comment by marcoabreu** [comment]
Great, it works. Thanks a lot everybody for the great work and such a quick fix
