### ISSUE TITLE
flaky test: test_contrib_control_flow.test_while_loop_for_foreach

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#12112]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1374/pipeline
```
======================================================================

FAIL: test_contrib_control_flow.test_while_loop_for_foreach

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_contrib_control_flow.py", line 727, in test_while_loop_for_foreach

    n_steps=5,

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_contrib_control_flow.py", line 480, in case_4

    **params

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_contrib_control_flow.py", line 244, in _verify_while_loop

    assert_almost_equal(imp_grad, sym_grad, rtol=1e-4, atol=1e-4)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 493, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 2.176908 exceeds tolerance rtol=0.000100, atol=0.000100.  Location of maximum error:(1, 1, 4), a=-1.308214, b=-1.308716

 a: array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,

          0.        ,  0.        ],

        [ 0.        ,  0.        ,  0.        , ...,  0.        ,...

 b: array([[[ 0.        ,  0.        ,  0.        , ...,  0.        ,

          0.        ,  0.        ],

        [ 0.        ,  0.        ,  0.        , ...,  0.        ,...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=448101308 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by haojin2** [comment]
@mxnet-label-bot [Flaky, Test].

**Comment by haojin2** [comment]
@junrushao1994 @zheng-da This seems like a numerical tolerance issue, can you guys take a look?

**Comment by lanking520** [comment]
@mxnet-label-bot please add [Flaky, test] to this issue

**Comment by zheng-da** [comment]
@junrushao1994 could you please adjust the unit test?

**Comment by junrushao1994** [comment]
@zheng-da Will do. BTW, why `a=-1.308214, b=-1.308716` causes an error of `2.176908`?

> Error 2.176908 exceeds tolerance rtol=0.000100, atol=0.000100.  Location of maximum error:(1, 1, 4), a=-1.308214, b=-1.308716

**Comment by haojin2** [comment]
@junrushao1994 https://github.com/apache/incubator-mxnet/blob/master/python/mxnet/test_utils.py#L442

**Comment by larroy** [comment]
This test is still causing problems:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1421/pipeline

**Comment by junrushao1994** [comment]
See #12192

**Comment by haojin2** [comment]
Fix was merged and verified to pass >10000 times, closing this issue.
