### ISSUE TITLE
Broken link in test_gluon_model_zoo.test_models

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#12121]
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/master/runs/1371/nodes/890/steps/1310/log/?start=0
```
======================================================================
ERROR: test_gluon_model_zoo.test_models
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/unittest/common.py", line 172, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/unittest/test_gluon_model_zoo.py", line 44, in test_models
    model = get_model(model_name, pretrained=test_pretrain, root='model/')
  File "/work/mxnet/python/mxnet/gluon/model_zoo/vision/__init__.py", line 152, in get_model
    return models[name](**kwargs)
  File "/work/mxnet/python/mxnet/gluon/model_zoo/vision/squeezenet.py", line 169, in squeezenet1_1
    return get_squeezenet('1.1', **kwargs)
  File "/work/mxnet/python/mxnet/gluon/model_zoo/vision/squeezenet.py", line 136, in get_squeezenet
    net.load_parameters(get_model_file('squeezenet%s'%version, root=root), ctx=ctx)
  File "/work/mxnet/python/mxnet/gluon/model_zoo/model_store.py", line 113, in get_model_file
    with zipfile.ZipFile(zip_file_path) as zf:
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
BadZipfile: File is not a zip file
-------------------- >> begin captured stdout << ---------------------
```
```
-------------------- >> begin captured logging << --------------------
common: INFO: Setting module np/mx/python random seeds, use MXNET_MODULE_SEED=1817738085 to reproduce.
root: INFO: Model file not found. Downloading to model/squeezenet1.1-33ba0f93.params.
urllib3.connectionpool: DEBUG: Starting new HTTPS connection (1): apache-mxnet.s3-accelerate.dualstack.amazonaws.com
urllib3.connectionpool: DEBUG: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com:443 "GET /gluon/models/squeezenet1.1-33ba0f93.zip HTTP/1.1" 200 4602839
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=174613729 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by haojin2** [comment]
@hetong007

**Comment by haojin2** [comment]
@mxnet-label-bot [gluon, test]

**Comment by hetong007** [comment]
Cannot reproduce with the latest(1.3.0b20180810) pip package. It may due to unstable connection to the S3 bucket for pretrained models.

**Comment by haojin2** [comment]
@hetong007 maybe we can add retry logic in this test?

**Comment by hetong007** [comment]
@haojin2 Do we have an idea of how often does such kind of error show up?

**Comment by haojin2** [comment]
Not really sure, but seems like there're a few build failures caused by failed links from time to time.

**Comment by sandeep-krishnamurthy** [comment]
Under the hood, model_zoo->utils.download(), by default, retries for 5 times. I think this should be sufficient? May be we can't do anything more in the test case? 
@haojin2 / @marcoabreu / @hetong007 - Any suggested action items here?

To get a glimpse of the impact, I tried to see the last 25 failed only PR builds and none of them is failed due to this issue.

**Comment by hetong007** [comment]
I agree that 5 retires is sufficient, if no other improvement on the connection can be done.

**Comment by haojin2** [comment]
Closing this issue, I agree that the current settings for # of retries should be sufficient, we only need to keep an active eye on the links to the files and keep them up-to-date and accessible on CIs.
