### ISSUE TITLE
Flaky test test_operator_gpu.test_convolution_grouping

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#12210]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12204/1/pipeline
```
======================================================================

FAIL: test_operator_gpu.test_convolution_grouping

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 1619, in test_convolution_grouping

    np.testing.assert_allclose(arr1.asnumpy(), arr2.asnumpy(), rtol=1e-3, atol=1e-4)

  File "C:\Anaconda3\envs\py3\lib\site-packages\numpy\testing\utils.py", line 1411, in assert_allclose

    verbose=verbose, header=header, equal_nan=equal_nan)

  File "C:\Anaconda3\envs\py3\lib\site-packages\numpy\testing\utils.py", line 796, in assert_array_compare

    raise AssertionError(msg)

AssertionError: 

Not equal to tolerance rtol=0.001, atol=0.0001



(mismatch 1.3888888888888857%)

 x: array([[[[ -7.330719e+00,  -7.756371e+01,   1.965799e+01],

         [  9.080350e+01,  -8.899857e+01,  -8.073432e+01],

         [  2.778908e+01,  -5.207310e+01,  -6.087678e+01]],...

 y: array([[[[ -7.330627e+00,  -7.756369e+01,   1.965804e+01],

         [  9.080351e+01,  -8.899855e+01,  -8.073430e+01],

         [  2.778909e+01,  -5.207310e+01,  -6.087677e+01]],...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=938042730 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by lebeg** [comment]
Would you mind closing this one since [in code](https://github.com/apache/incubator-mxnet/blob/master/tests/python/unittest/test_operator.py#L1589) we track #12219?
