### ISSUE TITLE
flaky ARMv7 build

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#12258]
```
CMake Error at /usr/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):

  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)

Call Stack (most recent call first):

  /usr/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)

  /usr/share/cmake-3.11/Modules/FindOpenMP.cmake:451 (find_package_handle_standard_args)

  CMakeLists.txt:372 (find_package)



-- Configuring incomplete, errors occurred!

See also "/work/build/CMakeFiles/CMakeOutput.log".

See also "/work/build/CMakeFiles/CMakeError.log".

build.py: 2018-08-20 19:38:20,056 Running of command in container failed (1):

docker\

	run\

	--rm\

	-t\

	--shm-size=500m\

	-v\

	/home/jenkins_slave/workspace/build-ARMv7:/work/mxnet\

	-v\

	/home/jenkins_slave/workspace/build-ARMv7/build:/work/build\

	-v\

	/efs-ccache:/work/ccache\

	-u\

	1001:1001\

	-e\

	CCACHE_MAXSIZE=500G\

	-e\

	CCACHE_TEMPDIR=/tmp/ccache\

	-e\

	CCACHE_DIR=/work/ccache\

	-e\

	CCACHE_LOGFILE=/tmp/ccache.log\

	mxnetci/build.armv7\

	/work/runtime_functions.sh\

	build_armv7


build.py: 2018-08-20 19:38:20,056 You can get into the container by adding the -i option

Traceback (most recent call last):

  File "ci/build.py", line 394, in <module>

    sys.exit(main())

  File "ci/build.py", line 323, in main

    local_ccache_dir=args.ccache_dir, interactive=args.interactive)

  File "ci/build.py", line 210, in container_run

    raise subprocess.CalledProcessError(ret, cmd)

subprocess.CalledProcessError: Command 'docker\

	run\

	--rm\

	-t\

	--shm-size=500m\

	-v\

	/home/jenkins_slave/workspace/build-ARMv7:/work/mxnet\

	-v\

	/home/jenkins_slave/workspace/build-ARMv7/build:/work/build\

	-v\

	/efs-ccache:/work/ccache\

	-u\

	1001:1001\

	-e\

	CCACHE_MAXSIZE=500G\

	-e\

	CCACHE_TEMPDIR=/tmp/ccache\

	-e\

	CCACHE_DIR=/work/ccache\

	-e\

	CCACHE_LOGFILE=/tmp/ccache.log\

	mxnetci/build.armv7\

	/work/runtime_functions.sh\

	build_armv7' returned non-zero exit status 1

script returned exit code 1```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12209/4/pipeline

**Comment by haojin2** [comment]
@KellenSunderland @marcoabreu @larroy @lebeg Please take a look when you have time.
@mxnet-label-bot [Build, Bug]

**Comment by lanking520** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12256/1/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12256/2/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12256/3/pipeline

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12256/4/pipeline

Failed 4 times... Looks like not a flaky but a consistent crash

**Comment by zheng-da** [comment]
I also realize that. I tried multiple times and failed every time.

**Comment by zheng-da** [comment]
Tried an empty PR and failed again.
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12259/1/pipeline/116

@marcoabreu could you fix it?

**Comment by anirudhacharya** [comment]
one more instance - http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/incubator-mxnet/branches/PR-12230/runs/5/nodes/116/log/?start=0

**Comment by KellenSunderland** [comment]
All passed, can someone merge https://github.com/apache/incubator-mxnet/pull/12260

**Comment by haojin2** [comment]
@KellenSunderland it was merged just now.
