### ISSUE TITLE
Generated NDArray wrappers have wrong function argument declaration

### ISSUE THREAD

**Issue by samskalicky** [apache/incubator-mxnet#12286]
## Description
Generated Python wrapper for operators in the NDArray APIs do not have the correct function signature (argument list). 

## Error Message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 59, in softmax
  File "/Users/sskalic/projects/mxnet/sskalic_branch5/python/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/Users/sskalic/projects/mxnet/sskalic_branch5/python/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:09:02] src/c_api/../imperative/imperative_utils.h:336: Check failed: num_inputs == infered_num_inputs (0 vs. 1) Operator softmax expects 1 inputs, but got 0 instead.

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000103e98ae6 dmlc::StackTrace() + 1238
[bt] (1) 1   libmxnet.so                         0x0000000103e984d5 dmlc::LogMessageFatal::~LogMessageFatal() + 53
[bt] (2) 2   libmxnet.so                         0x0000000103e94655 dmlc::LogMessageFatal::~LogMessageFatal() + 21
[bt] (3) 3   libmxnet.so                         0x00000001067a895c mxnet::imperative::SetNumOutputs(nnvm::Op const*, nnvm::NodeAttrs const&, int const&, int*, int*) + 988
[bt] (4) 4   libmxnet.so                         0x00000001067a5612 MXImperativeInvokeImpl(void*, int, void**, int*, void***, int, char const**, char const**) + 210
[bt] (5) 5   libmxnet.so                         0x00000001067a8e08 MXImperativeInvokeEx + 184
[bt] (6) 6   _ctypes.so                          0x000000010319a7b7 ffi_call_unix64 + 79
```

The expected error message should be of the form:

```
TypeError: softmax() takes exactly # arguments (0 given)
```

## Minimum reproducible example
```
import mxnet as mx
mx.nd.softmax()
```

## Steps to reproduce
Execute above code

## What have you tried to solve it?
There is a deep underlying problem with the way we generate wrappers "on-the-fly". Heres an example:

```
# generic/unsafe function definition                                                                         
def sam1(*args, **kwargs):
    print(args)
    print(kwargs)

# specific function definition                                                                               
def sam2(size,joe):
    print(size)
    print(joe)

#valid function calls                                                                                        
sam1(2,joe=4)
sam2(2,joe=4)

#invalid function calls that do not fail                                                                     
sam1(1,2,3)
sam1(2,bob=4)

# invalid function calls that do fail                                                                        
try:
    sam2(1,2,3)
except TypeError as e:
    print('Dont do that! ',e)

try:
    sam2(2,bob=4)
except TypeError as e:
    print('Dont do that! ',e)
```

MXNet should be generating specific python function declarations, not generic ones. This leads to the bad error message above instead of the familiar one in Python.

**Comment by ankkhedia** [comment]
@mxnet-label-bot : [Python, NDArray]

**Comment by samskalicky** [comment]
Upon further investigation it seems that the actual issue is that there is automatically generated default values for each argument:

https://github.com/apache/incubator-mxnet/blob/76bdc8772c7f4edd3087bd1285025122fc837c06/python/mxnet/ndarray/register.py#L67-L88

This results in the following function signature for the smooth_l1 operator:
```
def smooth_l1(data=None, scalar=_Null, out=None, name=None, **kwargs)
```
The problem is that these default values end up getting passed down to the C++ operator implementation and cause the error shown in the description. Ideally, we should only set default values that the user provided when they registered the operator.

**Comment by samskalicky** [comment]
Instead, it looks like all we pass up is the name, type, and description

https://github.com/dmlc/tvm/blob/675216fbeb94c835e8267ae97aeed58f129c1c39/nnvm/src/c_api/c_api_symbolic.cc#L70-L78

If we could pass the default values (and a boolean to say whether there is one or not) then we could set the default value in the python argument list correctly. This would allow arguments with required values to fail natively as expected in the higher level language.

**Comment by piyushghai** [comment]
@samskalicky Looks like the PR referencing this issue has been merged. 
Can this issue be closed then ?

**Comment by samskalicky** [comment]
@piyushghai No, this is not a problem with a single operator. Its a problem with the architecture of generating the python wrappers in the way its currently done. 

The PR referencing this issue is not a solution for the actual problem, it was a solution for just the smooth_l1 operator argument issue in which this problem was discovered.
