### ISSUE TITLE
Flaky test: test_operator.test_dropout

### ISSUE THREAD

**Issue by Chancebair** [apache/incubator-mxnet#12329]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12311/1/pipeline

```
======================================================================
FAIL: test_operator.test_dropout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/unittest/common.py", line 172, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5844, in test_dropout
    check_dropout_ratio(0.0, shape)
  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5788, in check_dropout_ratio
    assert exe.outputs[0].asnumpy().min() == min_value
AssertionError: 
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=119185068 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by ankkhedia** [comment]
Hi @Chancebair Thanks for filing the issue. We will look into the test.

**Comment by perdasilva** [comment]
I've tested this locally. I ran the test 10k times and no errors. I also ran it with the suggested seed. Maybe this issue is gone?

**Comment by lebeg** [comment]
Unfortunately this test fails on the v1.3.x release branch:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/v1.3.x/97/pipeline
