### ISSUE TITLE
Flaky test_l2_normalization on GPU

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#12359]
```
FAIL: test_operator_gpu.test_l2_normalization

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 3138, in test_l2_normalization

    check_l2_normalization((nbatch, nchannel, height, width), mode, dtype)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_operator.py", line 3124, in check_l2_normalization

    check_numeric_gradient(out, [in_data], numeric_eps=1e-3, rtol=1e-2, atol=1e-3)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 912, in check_numeric_gradient

    ("NUMERICAL_%s"%name, "BACKWARD_%s"%name))

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 491, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 1.965590 exceeds tolerance rtol=0.010000, atol=0.001000.  Location of maximum error:(1, 0, 2, 1), a=1.024514, b=1.002837

 NUMERICAL_data: array([[[[ 0.57908893,  0.92928857,  0.74058771,  0.71989   , -0.13311952,

           0.88640302],

         [ 0.67391992, -0.2854988 ,  0.29365718,  0.06447732, -0.12926757,...

 BACKWARD_data: array([[[[ 0.57923657,  0.92928588,  0.74055588,  0.71992582, -0.13315882,

           0.88643396],

         [ 0.6739229 , -0.28549621,  0.29365593,  0.06447371, -0.12932251,...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=104900554 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by ankkhedia** [comment]
@reminisce Thanks for filing the issue. We will look into it.

**Comment by lebeg** [comment]
@reminisce This issue was tracked as https://github.com/apache/incubator-mxnet/issues/12417 as well and was fixed with https://github.com/apache/incubator-mxnet/pull/12429. If it's not an issue anymore it can be closed. Thanks!

**Comment by vandanavk** [comment]
@sandeep-krishnamurthy Please close this issue as the PR has been merged.

@reminisce Please feel free to reopen if you see this issue again.
