### ISSUE TITLE
macOS installation (build from source) fails

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12373]
Running the installation for "build from source" for mac fails.

https://mxnet.incubator.apache.org/install/index.html?platform=MacOS&language=Python&processor=CPU#validate-mxnet-installation

It has you run a shell script.

Two issues:

1. It detects a previous version, but fails to remove it.
```
MXNet 1.0.0.post4 is already installed.
This installation might interfere with current installation attempt.
Do you want to remove installed version? (y/n): y
Skipping mxnet as it is not installed.
MXNet 1.0.0.post4 is already installed.
This installation might interfere with current installation attempt.
Do you want to remove installed version? (y/n): y
Skipping mxnet as it is not installed.
MXNet 1.0.0.post4 is already installed.
This installation might interfere with current installation attempt.
```

2. Then later the test fails:
```
BEGIN: Test MXNet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/markhama/mxnet/python/mxnet/../../lib/libmxnet.so, 6): Library not loaded: /usr/local/opt/ffmpeg/lib/libavcodec.57.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_videoio.3.3.dylib
  Reason: image not found
0a1,2
> [[2. 2. 2.]
>  [2. 2. 2.]]
 
ERROR: Following files differ: mxnet_test.log mxnet_test.expected
ERROR: MXNet test failed
END: Test MXNet
 
:-(
```

Importing mxnet yields a warning:

```
>>> import mxnet
dyld: warning, LC_RPATH ${ORIGIN} in /Users/markhama/Library/Python/2.7/lib/python/site-packages/mxnet/libmxnet.so being ignored in restricted program because it is a relative path
>>> 
```

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Installation, Doc, OSX]

**Comment by srochel** [comment]
@mxnet-label-bot: ["Good First Issue"]

**Comment by aaronmarkham** [comment]
If we go with https://github.com/apache/incubator-mxnet/pull/12388 then this issue will be moot. We wouldn't be using that script. However, if we get the script updated and working, it can be an alternative install option for users.

**Comment by piyushghai** [comment]
@aaronmarkham Seems like the validate-mxnet-installation anchor link does not go to the intended page. Can you please check the URL once again ?

**Comment by aaronmarkham** [comment]
#12388 was merged and that removed this script from the instructions. I also moved validation to a separate page to reduce the complexity of the install page. 
@piyushghai Glad to hear that the instructions work for you!

This issue can be closed.
