### ISSUE TITLE
Scala: DataDesc IllegalArgumentException with simple example

### ISSUE THREAD

**Issue by mariussoutier** [apache/incubator-mxnet#12409]
## Description

Fitting using Scala and Module API throws an IAE.
Apparently the label shape of (50) doesn't correspond to expected the NCHW format.

## Environment info (Required)

macOS 10.13.6
IntelliJ 2018.2.2
Scala 2.11.12
Java 1.8.0_121
MXNet 1.2.1

## Error Message:

```scala
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: number of dimensions in shape :1 with shape: (50) should match the length of the layout: 4 with layout: NCHW
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.mxnet.DataDesc.<init>(IO.scala:233)
	at org.apache.mxnet.DataDesc$$anonfun$ListMap2Descs$1.apply(IO.scala:256)
	at org.apache.mxnet.DataDesc$$anonfun$ListMap2Descs$1.apply(IO.scala:256)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.mxnet.DataDesc$.ListMap2Descs(IO.scala:256)
	at org.apache.mxnet.module.BaseModule.fit(BaseModule.scala:399)
```

## Minimum reproducible example

```scala
    val trainDataIter = IO.ImageRecordIter(Map(
      "data_name" -> dataName,
      "path_imgrec" -> this.getClass.getResource("/data/mydata.rec").getFile,
      "data_shape" -> "(3,128,128)",
      "batch_size" -> "50"
    ))

val mod = new Module(mlp)
    mod.fit(
      trainDataIter,
      Some(testDataIter),
      numEpoch = 10,
      fitParams =
        new FitParams()
          .setOptimizer(new SGD(0.1f, 0.9f, 0.0001f))
    )
```

Tried debugging this, but pretty difficult to find out what's going on with a stringly typed API.

`println(trainDataIter.provideData)` -> Map(data -> (50,3,128,128))
`println(trainDataIter.provideLabel)` -> Map(label -> (50))

**Comment by anirudhacharya** [comment]
@mxnet-label-bot [Scala]

**Comment by lanking520** [comment]
Hi @mariussoutier this problem actually addressed in 1.3 in this PR: https://github.com/apache/incubator-mxnet/pull/11844. Try with this one!

**Comment by mariussoutier** [comment]
@lanking520 Is there a published version of that I can use or do I have to build it myself?

**Comment by nswamy** [comment]
@mariussoutier we are working on a 1.3.0 pre-release, we should be able to have a RC maven package in staging soon.

**Comment by mariussoutier** [comment]
Nice, looking forward to it.

**Comment by nswamy** [comment]
@mariussoutier we released the package to Staging here if you would like to test it.
https://repository.apache.org/content/repositories/staging/org/apache/mxnet/ 

See the instructions on how to use packages in Staging repo here:
https://cwiki.apache.org/confluence/display/MXNET/MXNet-Scala+Release+Process#MXNet-ScalaReleaseProcess-UsingPackagesinStagingRepository

**Comment by mariussoutier** [comment]
@nswamy Just tried it out, Module API seems to work now. Thanks!

**Comment by mariussoutier** [comment]
Is there any difference between Module and FeedForward anyway?

**Comment by mariussoutier** [comment]
Ok, makes sense. I've also used FeedForward for my CNN :-)

**Comment by mariussoutier** [comment]
One more issue, Module-based GPU training on Ubuntu fails during the second epoch with a SIGTERM. I don't know yet what's happening. FeedForward-based training in 1.2.1 works without a problem.

**Comment by nswamy** [comment]
could you please open a new issue with some reproducible code?

**Comment by mariussoutier** [comment]
Sure, will do.

**Comment by ddavydenko** [comment]
Seems like this extra question was filed and replied to in #12553. Could we close this issue as it has been addressed in comments above?
