### ISSUE TITLE
test_gluon.test_import failure in CI

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12415]
Windows env trying to access a model and some other process already has it.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12102/21/pipeline

```
======================================================================

ERROR: test_gluon.test_import

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-cpu@3\tests\python\unittest\common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-cpu@3\tests\python\unittest\test_gluon.py", line 813, in test_import

    prefix='resnet', ctx=ctx, pretrained=True)

  File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\gluon\model_zoo\vision\resnet.py", line 407, in resnet18_v1

    return get_resnet(1, 18, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\gluon\model_zoo\vision\resnet.py", line 391, in get_resnet

    root=root), ctx=ctx)

  File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\gluon\model_zoo\model_store.py", line 115, in get_model_file

    os.remove(zip_file_path)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 

'C:\\Windows\\system32\\config\\systemprofile\\AppData\\Roaming\\mxnet\\models\\resnet18_v1-a0666292.zip'
```

@mxnet-label-bot [Flaky, Test]

**Comment by aaronmarkham** [comment]
@mxnet-label-bot [Flaky, Test]

**Comment by kalyc** [comment]
Ran the test locally 500 times on Mac. Unable to reproduce. 

@aaronmarkham is this still persisting? Could you close the issue if it isn't? Maybe the failure was related some Git outage?

**Comment by aaronmarkham** [comment]
I haven't seen it since then.

**Comment by kalyc** [comment]
Could you close the issue?

**Comment by aaronmarkham** [comment]
Failed again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12667/2/pipeline

**Comment by aaronmarkham** [comment]
@kalyc It's failing on Windows so testing it on a Mac might not reproduce it.
