### ISSUE TITLE
Problem with Symbol.reshape and special value -2  [scala]

### ISSUE THREAD

**Issue by mdespriee** [apache/incubator-mxnet#12425]
## Description
I want to add an axis to an input, so I try to use Symbol.reshape with arg shape=(1, -2), but it fails with a cryptic message. Is there any workaround ?

## Environment info (Required)
- Linux setup using  https://raw.githubusercontent.com/apache/incubator-mxnet/1.2.1/ci/docker/install/ubuntu_core.sh (actually in a Docker)
- MXNet 1.2.1, scala 2.11.11

## Error Message:
```
[error] (run-main-0) org.apache.mxnet.MXNetError: Error in operator reshape0: [16:14:49] src/operator/tensor/./matrix_op-inl.h:187: Check failed: oshape.Size() == dshape.Size() (2 vs. 4) Target shape size is different to source. Target: [1,2]
[error] Source: [2,2]
[error]
[error] Stack trace returned 10 entries:
[error] [bt] (0) /tmp/mxnet2259072593884902973/mxnet-scala(dmlc::StackTrace[abi:cxx11]()+0x1bc) [0x7f705d82c4fc]
[error] [bt] (1) /tmp/mxnet2259072593884902973/mxnet-scala(dmlc::LogMessageFatal::~LogMessageFatal()+0x28) [0x7f705d82d718]
[error] [bt] (2) /tmp/mxnet2259072593884902973/mxnet-scala(mxnet::op::ReshapeShape(nnvm::NodeAttrs const&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >*)+0xa1c) [0x7f705df3886c]
[error] [bt] (3) /tmp/mxnet2259072593884902973/mxnet-scala(+0x20b0d61) [0x7f705f481d61]
[error] [bt] (4) /tmp/mxnet2259072593884902973/mxnet-scala(mxnet::exec::InferShape(nnvm::Graph&&, std::vector<nnvm::TShape, std::allocator<nnvm::TShape> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x1a7f) [0x7f705f483ebf]
[error] [bt] (5) /tmp/mxnet2259072593884902973/mxnet-scala(mxnet::exec::GraphExecutor::Init(nnvm::Symbol, mxnet::Context const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::Context, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::Context> > > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, mxnet::Executor*, std::unordered_map<nnvm::NodeEntry, mxnet::NDArray, nnvm::NodeEntryHash, nnvm::NodeEntryEqual, std::allocator<std::pair<nnvm::NodeEntry const, mxnet::NDArray> > > const&)+0x10ed) [0x7f705f461f3d]
[error] [bt] (6) /tmp/mxnet2259072593884902973/mxnet-scala(mxnet::Executor::Bind(nnvm::Symbol, mxnet::Context const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, mxnet::Context, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, mxnet::Context> > > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, std::vector<mxnet::NDArray, std::allocator<mxnet::NDArray> > const&, mxnet::Executor*)+0xe0) [0x7f705f463510]

(...)
[error] 	at org.apache.mxnet.Base$.checkCall(Base.scala:131)
[error] 	at org.apache.mxnet.Symbol.bindHelper(Symbol.scala:786)
[error] 	at org.apache.mxnet.Symbol.bind(Symbol.scala:711)
[error] 	at ReshapeTest$.delayedEndpoint$ReshapeTest$1(tt.scala:72)
[error] 	at ReshapeTest$delayedInit$body.apply(tt.scala:67)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at ReshapeTest$.main(tt.scala:67)
[error] 	at ReshapeTest.main(tt.scala)
```

## Minimum reproducible example
```scala
import org.apache.mxnet._

val a = Symbol.Variable("a")
val r = Symbol.reshape()(a)(Map("shape" -> (1,-2)))

val exec = r.bind(Context.defaultCtx, Map(
    "a" -> NDArray.array(Array(1, 2, 3, 4), Shape(2,2))
))
exec.forward()

```

**Comment by lanking520** [comment]
@mdespriee firstly the problem mentioned in the log means the shape of the data changed and there maybe data missing. As explained in [here](http://mxnet.apache.org/api/python/ndarray/ndarray.html#mxnet.ndarray.NDArray.reshape), users should not try to reshape the data with loss of data. However, I can use python to do the same thing without any issues:
```Python
import mxnet as mx
a = mx.nd.array([[1,2],[3,4]])
b = a.reshape(1, -2)
>>> b
[[1. 2.]]
<NDArray 1x2 @cpu(0)>
```
Not sure what is the issue here, will look into it and see....
@mxnet-label-bot please label [scala, bug]

**Comment by lanking520** [comment]
In fact, the returned output from Python looks not right. From the examples, the output should be [1, 2, 2] instead of [1, 2]

**Comment by nswamy** [comment]
AFAIK this is wrong usage of reshape. `-2`  is specifying to copy the remainder dimensions(after first) to the reshaped NDArray. here you are asking to reshape from (2,2) to (1, 2), hence you see the error.

**Comment by mdespriee** [comment]
Ok, I get it, I misunderstood the -2 option.

**Comment by nswamy** [comment]
closing the issue as not a problem.
