### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'clone'

### ISSUE THREAD

**Issue by lzh19961031** [apache/incubator-mxnet#12435]
Searching for graphviz
Reading http://pypi.python.org/simple/graphviz/
Couldn't find index page for 'graphviz' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
No local packages or download links found for graphviz
Best match: None
Traceback (most recent call last):
  File "setup.py", line 83, in <module>
    **kwargs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 76, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 104, in do_egg_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 211, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 427, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 478, in install_item
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 519, in process_distribution
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 563, in resolve
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 799, in best_match
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 811, in obtain
  File "build/bdist.linux-x86_64/egg/setuptools/command/easy_install.py", line 434, in easy_install
  File "build/bdist.linux-x86_64/egg/setuptools/package_index.py", line 475, in fetch_distribution
AttributeError: 'NoneType' object has no attribute 'clone'

**Comment by anirudhacharya** [comment]
@lzh19961031 can you please elaborate on the issue you are facing? What you are trying to do, errors you are facing, the environment in which you are running the program and a minimum reproducible example.

@mxnet-label-bot [Pending Requester Info]

**Comment by vrakesh** [comment]
@lzh19961031 Requesting , information regarding, your use-case, and what led to this particular error, and a reproducible example, This will help us get to the root of the issue. Thank you

**Comment by kalyc** [comment]
@lzh19961031 could you please update the issue? If it is not persisting anymore then could you resolve it?

**Comment by yzhliu** [comment]
Please feel free to reopen this issue if you found this issue has not been solved.
