### ISSUE TITLE
CI fails consistently in test_tvm_bridge

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#12473]
It seems a lot of PRs fail in the same place.

```
test_tvm_bridge.test_tvm_bridge ... ERROR


======================================================================

ERROR: test_tvm_bridge.test_tvm_bridge

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/test_tvm_bridge.py", line 61, in test_tvm_bridge

    check(tgt, dtype)

  File "/work/mxnet/tests/python/gpu/test_tvm_bridge.py", line 46, in check

    f = tvm.build(s, [x, y, zz, scale])

  File "/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/build_module.py", line 501, in build

    mhost = codegen.build_module(fhost, str(target_host))

  File "/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/codegen.py", line 20, in build_module

    return _Build(lowered_func, target)

  File "/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/_ffi/_ctypes/function.py", line 185, in __call__

    ctypes.byref(ret_val), ctypes.byref(ret_tcode)))

  File "/usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/_ffi/base.py", line 66, in check_call

    raise TVMError(py_str(_LIB.TVMGetLastError()))

TVMError: [17:52:36] /tmp/tvm/src/codegen/codegen.cc:27: Check failed: bf != nullptr Target llvm is not enabled


Stack trace returned 10 entries:

[bt] (0) /usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/libtvm.so(dmlc::StackTrace[abi:cxx11]()+0x5a) [0x7f16c88bd3aa]

[bt] (1) /usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/libtvm.so(tvm::codegen::Build(tvm::Array<tvm::LoweredFunc, void> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0xdc4) [0x7f16c896bef4]

[bt] (2) /usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/libtvm.so(+0x1d025d) [0x7f16c88bc25d]

[bt] (3) /usr/local/lib/python2.7/dist-packages/tvm-0.5.dev0-py2.7-linux-x86_64.egg/tvm/libtvm.so(TVMFuncCall+0x5e) [0x7f16c8cb273e]

[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f18c3167e40]

[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f18c31678ab]

[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f18c33773df]

[bt] (7) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f18c337bd82]

[bt] (8) /usr/bin/python2(PyEval_EvalFrameEx+0x578f) [0x4c15bf]

[bt] (9) /usr/bin/python2(PyEval_EvalCodeEx+0x306) [0x4b9ab6]
```

**Comment by marcoabreu** [comment]
The issue is not resolved.
