### ISSUE TITLE
[Scala] PrefetchingIter fails with labels and predictions should have the same length

### ISSUE THREAD

**Issue by mariussoutier** [apache/incubator-mxnet#12487]
## Description

Trying to use a `PrefetchingIter` to combine two `ImageRecordIter`. The two do not have the same number of images, but that shouldn't be a problem, right?

## Environment info (Required)

macOS 10.13.6
IntelliJ 2018.2.2
Scala 2.11.12
Java 1.8.0_121
MXNet 1.2.1

## Error Message:

```scala
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: labels and predictions should have the same length.
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.mxnet.Accuracy.update(EvalMetric.scala:106)
	at org.apache.mxnet.DataParallelExecutorGroup$$anonfun$updateMetric$1.apply(ExecutorManager.scala:528)
	at org.apache.mxnet.DataParallelExecutorGroup$$anonfun$updateMetric$1.apply(ExecutorManager.scala:526)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at org.apache.mxnet.DataParallelExecutorGroup.updateMetric(ExecutorManager.scala:526)
	at org.apache.mxnet.DataParallelExecutorManager.updateMetric(ExecutorManager.scala:168)
	at org.apache.mxnet.Model$$anonfun$trainMultiDevice$1.apply$mcVI$sp(Model.scala:313)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at org.apache.mxnet.Model$.trainMultiDevice(Model.scala:284)
	at org.apache.mxnet.FeedForward.fit(FeedForward.scala:377)
	at org.apache.mxnet.FeedForward.fit(FeedForward.scala:281)
	at org.apache.mxnet.FeedForward$Builder.build(FeedForward.scala:676)
	at com.mariussoutier.example.TrainChars74K$.trainFF(TrainChars74K.scala:86)
	at com.mariussoutier.example.TrainChars74K$.main(TrainChars74K.scala:177)
	at com.mariussoutier.example.TrainChars74K.main(TrainChars74K.scala)
```

## Minimum reproducible example

```scala
    val trainDataIterA = IO.ImageRecordIter(Map(
      "data_name" -> dataName,
      "path_imgrec" -> this.getClass.getResource("/data/mydataA.rec").getFile,
      "data_shape" -> "(3,128,128)",
      "batch_size" -> "50",
      "rand_crop" -> "True",
       "shuffle" -> "False"
    ))

    val trainDataIterB = IO.ImageRecordIter(Map(
      "data_name" -> dataName,
      "path_imgrec" -> this.getClass.getResource("/data/mydataB.rec").getFile,
      "data_shape" -> "(3,128,128)",
      "batch_size" -> "50",
      "rand_crop" -> "True",
      "shuffle" -> "False"
    ))

        val trainDataIter = new PrefetchingIter(
          IndexedSeq(trainDataIterA, trainDataIterB)
        )
```

**Comment by vrakesh** [comment]
@mariussoutier Thank you for reporting the issue. 

@mxnet-label-bot [Scala]

**Comment by zachgk** [comment]
@mariussoutier The PrefetchingIter has an IndexedSeq of inputs because some networks might require multiple data inputs. That is why the elements are read in parallel and there must be the same number of elements from each component iterator (since the network won't function with some inputs missing). You can see an example of the equivalent python function at https://mxnet.incubator.apache.org/api/python/io/io.html.

I think you are wanting to combine the two iterators such that it will feed the network one input that comes from either of the source iterators. In that case, you might want to create a new DataIter.

If you did intend to read them in parallel but allow missing elements, you need to modify one or both of the iterators to return a default for the missing elements.

**Comment by mariussoutier** [comment]
> I think you are wanting to combine the two iterators such that it will feed the network one input that comes from either of the source iterators. 

Exactly! Thanks.

**Comment by zachgk** [comment]
If you are interested, it should not be too difficult to create something like `AppendIter(iters: IndexedSeq[IndexedSeq[DataIter]])`. The [documentation](https://mxnet.incubator.apache.org/versions/master/api/scala/docs/index.html#org.apache.mxnet.DataIter) and the [SyntheticDataIter](https://github.com/apache/incubator-mxnet/blob/master/scala-package/examples/src/main/scala/org/apache/mxnetexamples/imclassification/datasets/SyntheticDataIter.scala) might be good references and it would be a great [contribution](https://mxnet.apache.org/community/contribute.html).

@mxnet-label-bot add [Call for Contribution, Good first Issue]

**Comment by lanking520** [comment]
@mxnet-label-bot add [Call for Contribution, Good First Issue]
