### ISSUE TITLE
gluon.nn.SymbolBlock.imports Error

### ISSUE THREAD

**Issue by kuonangzhe** [apache/incubator-mxnet#12486]
We use mxnet 1.3.0 on Ubuntu 16.04, python3.5, with model loading method SymbolBlock.imports. Then get error as follows:

```
[20:52:20] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.2.1. Attempting to upgrade...
[20:52:20] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/name/proj/demo.py", line 68, in <module>
    'param'])
  File "/home/name/proj/demo.py", line 22, in demo
    net_load = gluon.nn.SymbolBlock.imports(model_loc, ['data'], param_loc)
  File "/home/name/mxnet-1.3/python/mxnet/gluon/block.py", line 1023, in imports
    ret = SymbolBlock(sym, inputs)
  File "/home/name/mxnet-1.3/python/mxnet/gluon/block.py", line 1051, in __init__
    for j in i.get_internals():
  File "/home/name/mxnet-1.3/python/mxnet/symbol/symbol.py", line 93, in <genexpr>
    return (self[i] for i in self.list_outputs())
  File "/home/name/mxnet-1.3/python/mxnet/symbol/symbol.py", line 517, in __getitem__
    raise ValueError('There are multiple outputs with name \"%s\"' % index)
ValueError: There are multiple outputs with name "resmodel0_relu0_fwd_output"
```

While we tried with mxnet 1.2.1 and the program ran well. There might be some problems in the function but we are not sure. Are there any suggestions?

**Comment by vrakesh** [comment]
@kuonangzhe Thank you for reporting the issue, requesting to share a more detailed reproducible example 
@mxnet-label-bot [Gluon, Bug]

**Comment by kuonangzhe** [comment]
@vrakesh @sandeep-krishnamurthy Since there is confidentiality issues for the code, we cannot provide more details to reproduce the error, and it will also cost much time in locating the bad operator or mechanism in symbol, so sorry for the inconvenience. We finally changed to use load_parameters with consistent save and load method when dealing model to avoid the error, and now it works fine. Thanks for the kind help!
