### ISSUE TITLE
Improve error messages on shape inference (Operator)

### ISSUE THREAD

**Issue by mdespriee** [apache/incubator-mxnet#12565]
## Description
I'm trying to migrate to mxnet symbol a fairly complex flow, and I spent way too much time debugging "shape inference failed" errors when binding the module. 
What shape ? What symbol ? Which shape is ok, and which is missing ? Argh !

## Environment info (Required)
Using mxnet 1.3.0 on scala

## Error Message:
```
java.lang.IllegalArgumentException: requirement failed: shape inference failed
	at scala.Predef$.require(Predef.scala:224)
	at org.apache.mxnet.module.DataParallelExecutorGroup.org$apache$mxnet$module$DataParallelExecutorGroup$$bindIthExec(DataParallelExecutorGroup.scala:635)
	at org.apache.mxnet.module.DataParallelExecutorGroup$$anonfun$bindExec$2.apply(DataParallelExecutorGroup.scala:378)
	at org.apache.mxnet.module.DataParallelExecutorGroup$$anonfun$bindExec$2.apply(DataParallelExecutorGroup.scala:377)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.mxnet.module.DataParallelExecutorGroup.bindExec(DataParallelExecutorGroup.scala:377)
	at org.apache.mxnet.module.DataParallelExecutorGroup.<init>(DataParallelExecutorGroup.scala:322)
	at org.apache.mxnet.module.DataParallelExecutorGroup$Builder.build(DataParallelExecutorGroup.scala:223)
	at org.apache.mxnet.module.Module.bind(Module.scala:286)
```

**Comment by mdespriee** [comment]
More generally, I also suggest to review the use of require() scattered in the code, and make sure they all have meaningful messages.

**Comment by kalyc** [comment]
Thanks for submitting the issue @mdespriee, you can open a PR with the changes you have suggested and we can review them. 
@mxnet-label-bot[Scala, Good First Issue]

**Comment by gigasquid** [comment]
I agree. I've run into that one from the Clojure side as well and it could be improved.

**Comment by mdespriee** [comment]
After PR #12570 is merged, we'll go from this:
```
- failed inference *** FAILED ***
  java.lang.IllegalArgumentException: requirement failed: shape inference failed
  at scala.Predef$.require(Predef.scala:224)
```
to this:
```
- failed inference *** FAILED ***
  java.lang.IllegalArgumentException: requirement failed: Shape inference failed.Known shapes are Map(a -> (10,1,5)) for symbol arguments ArrayBuffer(a, constant) and aux states ArrayBuffer()
```

I think we can have even better from the backend, but that's progress.

**Comment by kalyc** [comment]
@mdespriee thanks for your contribution. Looks like the PR has been merged. Can this issue be closed?

**Comment by mdespriee** [comment]
Can it be improved from the backend side ?
If not, yes, we can close it for now.

**Comment by lanking520** [comment]
@apeforest @anirudh2290 Do you have any plan for this?

**Comment by szha** [comment]
The improvement would need to happen per operator. Let's create issues for individual operators when we discover more of these clear messages.
