### ISSUE TITLE
Extremely weird shape inference bug in foreach

### ISSUE THREAD

**Issue by taliesinb** [apache/incubator-mxnet#12760]
## Description

The foreach subgraph operator is sensitive to what should be irrelevant details of its construction, incorrectly failing when the inputs of a symmetric function are re-ordered.

## Environment info (Required)

Package used (Python/R/Scala/Julia):
I'm using Python.

## Error Message:

The error message is actually incorrect. The graph is shape-correct!

```
infer_shape error. Arguments:
  a: (1, 3)
  b: (1,)
Traceback (most recent call last):
  File "Untitled 9.py", line 68, in <module>
    print(sym.infer_shape(a=(1,3), b=(1,)))
  File "/Users/taliesinb/.anaconda3/lib/python3.6/site-packages/mxnet-1.3.0-py3.6.egg/mxnet/symbol/symbol.py", line 996, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/Users/taliesinb/.anaconda3/lib/python3.6/site-packages/mxnet-1.3.0-py3.6.egg/mxnet/symbol/symbol.py", line 1126, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/Users/taliesinb/.anaconda3/lib/python3.6/site-packages/mxnet-1.3.0-py3.6.egg/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator .: Error in operator mul2: [21:50:42] src/operator/contrib/../tensor/../elemwise_op_common.h:133: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node mul2 at 1-th input: expected [3], got [1]
```

## Minimum reproducible example

```
import mxnet as mx

json = """{
	"nodes":[
		{
			"op":"null",
			"name":"a",
			"inputs":[]
		},
		{
			"op":"null",
			"name":"b",
			"inputs":[]
		},
		{
			"op":"_foreach",
			"name":".",
			"attrs":{
				"in_data_locs":"[0]",
				"in_state_locs":"[]",
				"num_args":"3",
				"num_out_data":"1",
				"num_outputs":"1",
				"remain_locs":"[1]"
			},
			"inputs":[[0,0,0],[1,0,0]],
			"subgraphs":[
				{
					"nodes":[
						{
							"op":"null",
							"name":"inner_a",
							"inputs":[]
						},
						{
							"op":"null",
							"name":"inner_b",
							"inputs":[]
						},
						{
							"op":"broadcast_mul",
							"name":"mul1",
							"inputs":[[1,0,0],[0,0,0]]
						},
						{
							"op":"elemwise_mul",
							"name":"mul2",
							"inputs":[[2,0,0],[0,0,0]]
						}
					],
					"arg_nodes":[0,1],
					"heads":[[3,0,0]]
				}
			]
		}
	],
	"arg_nodes":[0,1],
	"heads":[[2,0,0]],
	"attrs":{
		"mxnet_version":[
			"int",
			10300
		]
	}
}""";

sym = mx.sym.load_json(json)
print(sym.infer_shape(a=(1,3), b=(1,)))
```

## Steps to reproduce

Run the above code in Python, you'll get an infer shape error.

if you flip the order of inputs in `mul2` from `[[2,0,0],[0,0,0]]` to `[[0,0,0],[2,0,0]]`, shape inference succeeds as expected.

## What have you tried to solve it?

I have no idea how to approach solving this.

**Comment by piyushghai** [comment]
@taliesinb Thanks for submitting this issue.
@mxnet-label-bot [Bug, Python, Operator]

**Comment by zheng-da** [comment]
Thanks for reporting the bug. I'll look into the bug.

**Comment by taliesinb** [comment]
Here's a simpler problem that I believe is the same issue:

```
import mxnet as mx

json = """{
	"nodes":[
		{
			"op":"null",
			"name":"a",
			"attrs":{},
			"inputs":[]
		},
		{
			"op":"null",
			"name":"b",
			"attrs":{},
			"inputs":[]
		},
		{
			"op":"_foreach",
			"name":"foreach",
			"attrs":{
				"in_data_locs":"[0,1]",
				"in_state_locs":"[]",
				"num_args":"3",
				"num_out_data":"2",
				"num_outputs":"2",
				"remain_locs":"[]"
			},
			"inputs":[[0,0,0],[1,0,0]],
			"subgraphs":[
				{
					"nodes":[
						{
							"op":"null",
							"name":"inner_a",
							"inputs":[]
						},
						{
							"op":"null",
							"name":"inner_b",
							"inputs":[]
						},
						{
							"op":"identity",
							"name":"id_a",
							"inputs":[[0,0,0]]
						},
						{
							"op":"identity",
							"name":"id_b",
							"inputs":[[1,0,0]]
						}						
					],
					"arg_nodes":[0,1],
					"heads":[[3,0,0],[2,0,0]]
				}
			]
		}
	],
	"arg_nodes":[0,1],
	"heads":[[2,0,0], [2,1,0]],
	"attrs":{
		"mxnet_version":[
			"int",
			10300
		]
	}
}"""

sym = mx.sym.load_json(json)
print(sym.infer_shape(a=(3,2), b=(3,5)))
```

This prints:

```
([(3, 2), (3, 5)], [(3, 2), (3, 5)], [])
```

But it should print:

```
([(3, 2), (3, 5)], [(3, 5), (3, 2)], [])
```

Changing the value of `"heads":[[3,0,0],[2,0,0]]` to `"heads":[[2,0,0],[3,0,0]]` does nothing! It should determine the order of outputs of the inner foreach op.

**Comment by taliesinb** [comment]
My hypothesis is that the subgraph's outputs are being visited in topological order rather than in the order given by `heads`.

**Comment by taliesinb** [comment]
@zheng-da any news on this? Seems like foreach is dangerous to use until this is fixed.

**Comment by taliesinb** [comment]
@zheng-da @xinyu-intel Checking in on this again. Any information would be helpful.

**Comment by taliesinb** [comment]
@zheng-da @xinyu-intel I'm not giving up hope yet 😛

**Comment by taliesinb** [comment]
@zheng-da @xinyu-intel Any info?

**Comment by junrushao1994** [comment]
@zheng-da I am struggling to graduate recently, and has been staying up late to 4am almost every day during these two weeks. I am afraid I don’t have enough capacity.
