### ISSUE TITLE
test_subgraph.test_pos_conv_bn_sum_relu fails in CI

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#12797]
Unrelated .js update failed in CI:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12781/4/pipeline

```
======================================================================

FAIL: test_subgraph.test_pos_conv_bn_sum_relu

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/test_subgraph.py", line 450, in test_pos_conv_bn_sum_relu

    check_fusion(net, data_shape, attrs)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/test_subgraph.py", line 123, in check_fusion

    assert_almost_equal(exe.outputs[i].asnumpy(), exe_sg.outputs[i].asnumpy(), rtol=1e-3, atol=1e-3)

  File "/work/mxnet/python/mxnet/test_utils.py", line 491, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 20188.939453 exceeds tolerance rtol=0.001000, atol=0.001000.  Location of maximum error:(2, 37, 4, 6), a=20.188940, b=-0.000000

 a: array([[[[-0.        , -0.        ,  1.0293951 , ...,  0.09606495,

          -0.        , -0.        ],

         [-0.        , -0.        , -0.        , ..., -0.        ,...

 b: array([[[[-0.        , -0.        ,  0.48512375, ..., -0.        ,

          -0.        , -0.        ],

         [-0.        , -0.        , -0.        , ..., -0.        ,...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=895845338 to reproduce.

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=219741914 to reproduce.

--------------------- >> end captured logging << ---------------------


```

**Comment by sandeep-krishnamurthy** [comment]
I have reverted my PR on Batchnorm that brought in this issue to master. Unblocking master and PR builds - https://github.com/apache/incubator-mxnet/commit/50d231330cf0d4f3862c368cdec4510f50ae6e91

Now pipeline is green. I am working on the fix - https://github.com/apache/incubator-mxnet/pull/12788

Resolving this issue as it is no more applicable.
