### ISSUE TITLE
MXNet doesn't work with scipy int64

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#12843]
The following code doesn't work.
```python
import numpy as np
import scipy as sp
import mxnet as mx

one = np.ones((2, 2), dtype='int64')
print(np.dtype(one.dtype).type == np.int64)
sp_one = sp.sparse.csr_matrix(one).data
mx.nd.array(sp_one, dtype=sp_one.dtype)
```
It generates the error as below:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    mx.nd.array(sp_one, dtype=sp_one.dtype)
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/utils.py", line 146, in array
    return _array(source_array, ctx=ctx, dtype=dtype)
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 2488, in array
    arr = empty(source_array.shape, ctx, dtype)
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 3874, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 139, in _new_alloc_handle
    ctypes.c_int(int(_DTYPE_NP_TO_MX[np.dtype(dtype).type])),
KeyError: <type 'numpy.int64'>
```

**Comment by lanking520** [comment]
@mxnet-label-bot please add [bug, python, feature]

**Comment by eric-haibin-lin** [comment]
I don't think this is a feature request. Removing label feature..

**Comment by wkcn** [comment]
The id of np.int64 in scipy is different from that in numpy.
```python
import numpy as np
import scipy as sp
import mxnet as mx

one = np.ones((2, 2), dtype='int64')
sp_one = sp.sparse.csr_matrix(one).data

print (np.dtype(sp_one.dtype).type)
print (id(np.dtype(sp_one.dtype).type))

print (np.dtype(np.int64).type)
print (id(np.dtype(np.int64).type))

print (np.int64)
print (id(np.int64))
```

```bash
<type 'numpy.int64'>
139671667680256
<type 'numpy.int64'>
139671667680672
<type 'numpy.int64'>
139671667680672
```

**Comment by vrakesh** [comment]
@zheng-da According to PR #12972  this is a scipy issue rather than a MXNet issue, do you think we should close this issue?

**Comment by lanking520** [comment]
@zheng-da Close this issue since it's been identify a Scipy bug rather than MXNet. Please feel free to reopen if you feel like some alternative action should be taken here.
