### ISSUE TITLE
test_prelu fails frequently.

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#12885]
```
======================================================================

FAIL: test_operator.test_prelu

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 172, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 827, in test_prelu

    check_symbolic_forward(y, [xa, gam_full], [ya_full], rtol=rtol, atol=atol, dtype=dtype)

  File "/work/mxnet/python/mxnet/test_utils.py", line 997, in check_symbolic_forward

    equal_nan=equal_nan)

  File "/work/mxnet/python/mxnet/test_utils.py", line 491, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 100.000000 exceeds tolerance rtol=0.010000, atol=0.001000.  Location of maximum error:(0, 0, 2, 2), a=-0.045013, b=117.000000

 EXPECTED_leakyrelu24_output: array([[[[-0.0745  ,  0.3264  ,  0.7534  , -0.0559  , -0.05847 ],

         [-0.0293  , -0.002966, -0.05618 , -0.0824  , -0.016   ],

         [-0.05652 , -0.0627  , -0.045   , -0.013756,  0.8813  ],...

 FORWARD_leakyrelu24_output: array([[[[ -0.0745  ,   0.3264  ,   0.7534  ,  -0.0559  ,  -0.05847 ],

         [ -0.0293  ,  -0.002966,  -0.05618 ,  -0.0824  ,  -0.016   ],

         [ -0.05652 ,  -0.0627  , 117.      ,   8.164   ,   0.8813  ],...

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=409746395 to reproduce.

--------------------- >> end captured logging << ---------------------
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12810/8/pipeline/1005
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12810/7/pipeline

**Comment by lanking520** [comment]
@mxnet-label-bot please add [Flaky, test, CI]

**Comment by lebeg** [comment]
Failed on master as well:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/1827/pipeline

**Comment by ChaiBapchya** [comment]
Fails for me too - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13045/3/pipeline/1005

**Comment by ChaiBapchya** [comment]
Would be great to know which PR fixed the flakiness issue. Like what was the reason behind its flakiness and how was it solved.
It's great that @larroy tested it and verified that its not flaky anymore. But curious to know the theoretical underpinning behind the solution.
