### ISSUE TITLE
AttributeError: 'str' object has no attribute 'rank'

### ISSUE THREAD

**Issue by TonyTangYu** [apache/incubator-mxnet#13058]
## Description
I run the ssd demo of mxnet from [this](https://github.com/zhreshold/mxnet-ssd). When 
I run python train.py --gpu 0 --batch-size 32 --lr 0.001 but I get the following problem.  I list all the information needed.

## Environment info (Required)
```
----------Python Info----------
('Version      :', '2.7.13')
('Compiler     :', 'GCC 4.4.7 20120313 (Red Hat 4.4.7-1)')
('Build        :', ('default', 'Dec 20 2016 23:09:15'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/THL5/home/daodao/anaconda2/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '0.11.0')
('Directory    :', '/THL5/home/daodao/softwares/mxnet0.11/python/mxnet')
Hashtag not found. Not installed from pre-built package.

```

Package used (Python/R/Scala/Julia):

I'm using Python2.7.13 and mxnet0.11

## Error Message:
[18:29:52] src/io/iter_image_det_recordio.cc:280: ImageDetRecordIOParser: /THL5/home/daodao/ty_project/incubator-mxnet-0.11.0/example/ssd/data/train.rec, use 27 threads for decoding..
[18:29:54] src/io/iter_image_det_recordio.cc:333: ImageDetRecordIOParser: /THL5/home/daodao/ty_project/incubator-mxnet-0.11.0/example/ssd/data/train.rec, label padding width: 350
[18:29:54] src/engine/threaded_engine_perdevice.cc:253: [added by cxt] engine is created by EnginePerDevice 
[18:29:54] src/io/iter_image_det_recordio.cc:280: ImageDetRecordIOParser: /THL5/home/daodao/ty_project/incubator-mxnet-0.11.0/example/ssd/data/val.rec, use 27 threads for decoding..
[18:29:55] src/io/iter_image_det_recordio.cc:333: ImageDetRecordIOParser: /THL5/home/daodao/ty_project/incubator-mxnet-0.11.0/example/ssd/data/val.rec, label padding width: 350
INFO:root:Start training with (gpu(0)) from pretrained model /THL5/home/daodao/ty_project/incubator-mxnet-0.11.0/example/ssd/model/vgg16_reduced
[18:29:57] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[18:29:57] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
INFO:root:Freezed parameters: [conv1_1_weight,conv1_1_bias,conv1_2_weight,conv1_2_bias,conv2_1_weight,conv2_1_bias,conv2_2_weight,conv2_2_bias]
[18:30:14] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[18:30:51] src/operator/convolution.cu:119: This convolution is not supported by cudnn, MXNET convolution is applied.
ff
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/THL5/home/daodao/ty_project/incubator-mxnet-0.11.0/example/ssd/train/train_net.py", line 274, in train_net
    allow_missing=True,
  File "/THL5/home/daodao/softwares/mxnet0.11/python/mxnet/module/base_module.py", line 568, in fit
    rank=kvstore.rank, total_iter=temp_count,
AttributeError: 'str' object has no attribute 'rank'

## Steps to reproduce
(Paste the commands you ran that produced the error.)
1. python train.py --gpu 0 --batch-size 32 --lr 0.001

Could someone do me a fovour? I am struck with it for several days. Thank you!

**Comment by wkcn** [comment]
It seems the SSD example doesn't support the old version of MXNet.
Please upgrade MXNet.
The latest version is 1.3.x.

**Comment by frankfliu** [comment]
@mxnet-label-bot [Python, Example]

**Comment by TonyTangYu** [comment]
@wkcn  Thank you for your response. I upgraded the version of MXNet. It works now. Thank you!

**Comment by wkcn** [comment]
@TonyTangYu I recommend to use the SSD example in gluon-cv github.com/dmlc/gluon-cv, which could reach the baseline.

**Comment by TonyTangYu** [comment]
@wkcn  Thanks for your help. I will take a try! Thank you!

**Comment by sandeep-krishnamurthy** [comment]
Resolving as it works with latest MXNet.
