### ISSUE TITLE
Crashed at the end of mnist distributed tranining

### ISSUE THREAD

**Issue by melody-rain** [apache/incubator-mxnet#1326]
2016-01-21 14:28:45,146 Node[1] Epoch[9] Validation-accuracy=0.995593
terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted
Aborted (core dumped)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/home/dl/dl0/develop/mxnet/tools/../ps-lite/tracker/tracker.py", line 351, in <lambda>
    self.thread = Thread(target = (lambda : subprocess.check_call(self.cmd, env=env, shell=True)), args = ())
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'python train_mnist.py --network lenet --kv-store dist_sync' returned non-zero exit status 134

This is the example provided by mxnet: mxnet/example/image-classification

I run it with mxnet/tools/launch.py -n 2 -H hosts --sync-dir /tmp/mxnet python train_mnist.py --network lenet --kv-store dist_sync. 

It crashes at the end of the training. Any ideas for that?

**Comment by mli** [comment]
how often does it happen? it is probably due the deconstruction of some data structures.

**Comment by melody-rain** [comment]
@mli It happens always. might be a bug?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
