### ISSUE TITLE
OpenCV 4.0 Compatibility

### ISSUE THREAD

**Issue by szha** [apache/incubator-mxnet#13288]
OpenCV 4 is happening soon https://github.com/opencv/opencv/wiki/ChangeLog#version400. The big changes include the switch to C++11 and API changes.

If you have experience trying it out with MXNet, please do share your findings here. Thank you.

**Comment by zachgk** [comment]
@mxnet-label-bot add [Build, OpenCV]

Thank you for submitting the issue! I'm labeling it so the MXNet community members can help resolve it.

**Comment by piyushghai** [comment]
Related PR got merged : https://github.com/apache/incubator-mxnet/pull/14313 

@szha Is this issue good to close now ?

**Comment by szha** [comment]
Yes, thanks for the fix @daleydeng and @wkcn

**Comment by ziyuang** [comment]
I still have linking errors in creating `bin/im2rec` with OpenCV 4.0.1 (MXNet HEAD: 09ba8be4be36135e2a8d6c439313f5eed729d4bc), mostly from not able to find `cv::String::allocate`, `cv::String::deallocate`, and `cv::error`. OpenCV 4 has moved to `std::string` so there are no methods of `allocate` or `deallocate`. 

```
(cd cpp-package/scripts; python OpWrapperGenerator.py mxnet/lib/libmxnet.so)
g++ -o bin/im2rec ... -L/usr/local/lib -lopencv_imgcodecs -lopencv_highgui -lopencv_imgproc -lopencv_core
Traceback (most recent call last):
  File "OpWrapperGenerator.py", line 432, in <module>
    raise(e)
  File "OpWrapperGenerator.py", line 426, in <module>
    f.write(patternStr % ParseAllOps())
  File "OpWrapperGenerator.py", line 320, in ParseAllOps
    cdll.libmxnet = cdll.LoadLibrary(sys.argv[1])
  File "~/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "~/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: mxnet/lib/libmxnet.so: undefined symbol: _ZN2cv6String8allocateEm
cpp-package/cpp-package.mk:39: recipe for target 'cpp-package/include/mxnet-cpp/op.h' failed
make: *** [cpp-package/include/mxnet-cpp/op.h] Error 1
...
```
The OpenCV 4 libraries have been installed to `/usr/local/lib`.

**Comment by rajkinra23** [comment]
> I still have linking errors in creating `bin/im2rec` with OpenCV 4.0.1 (MXNet HEAD: [09ba8be](https://github.com/apache/incubator-mxnet/commit/09ba8be4be36135e2a8d6c439313f5eed729d4bc)), mostly from not able to find `cv::String::allocate`, `cv::String::deallocate`, and `cv::error`. OpenCV 4 has moved to `std::string` so there are no methods of `allocate` or `deallocate`.
> 
> ```
> (cd cpp-package/scripts; python OpWrapperGenerator.py mxnet/lib/libmxnet.so)
> g++ -o bin/im2rec ... -L/usr/local/lib -lopencv_imgcodecs -lopencv_highgui -lopencv_imgproc -lopencv_core
> Traceback (most recent call last):
>   File "OpWrapperGenerator.py", line 432, in <module>
>     raise(e)
>   File "OpWrapperGenerator.py", line 426, in <module>
>     f.write(patternStr % ParseAllOps())
>   File "OpWrapperGenerator.py", line 320, in ParseAllOps
>     cdll.libmxnet = cdll.LoadLibrary(sys.argv[1])
>   File "~/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
>     return self._dlltype(name)
>   File "~/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: mxnet/lib/libmxnet.so: undefined symbol: _ZN2cv6String8allocateEm
> cpp-package/cpp-package.mk:39: recipe for target 'cpp-package/include/mxnet-cpp/op.h' failed
> make: *** [cpp-package/include/mxnet-cpp/op.h] Error 1
> ...
> ```
> 
> The OpenCV 4 libraries have been installed to `/usr/local/lib`.

+1, im having the exact same problem here.
