### ISSUE TITLE
inv_khatri_rao.OneInputMatrixTransposed segfaults on ARM

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#13342]
## Description

inv_khatri_rao.OneInputMatrixTransposed segfaults on ARM

## Environment info (Required)

ARMv7 using QEMU

mxnet_unit_tests --gtest_filter="inv_khatri_rao.OneInputMatrixTransposed"

reproduction info is sent in a separate PR:  #13334

**Comment by vdantu** [comment]
@mxnet-label-bot add [C++, Test, ARM, Bug]

**Comment by larroy** [comment]
Theres a crash because lapack is no available.

369+>  MXNET_LAPACK_UNAVAILABLE(dposv)

Crash when accessing the stream producing the fatal error.

```
(gdb) bt
#0  0xb68de2e6 in std::ostream::sentry::sentry(std::ostream&) () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#1  0xb68de794 in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, c
har const*, int) () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#2  0xb68dea6c in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
 () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
#3  0x013d7034 in mxnet_lapack_dposv(...) () at /work/mxnet/src/operator/contrib/../c_lapack_api.h:369
```

**Comment by leleamol** [comment]
@mxnet-label-bot update [ARM, Bug, Test]
