### ISSUE TITLE
Missing libgomp.so.1 on fresh ubuntu 18.04

### ISSUE THREAD

**Issue by frankfliu** [apache/incubator-mxnet#13366]
## Description
On fresh ubuntu instance, mxnet pip package didn't install all required shared libraries:

OSError: libgomp.so.1: cannot open shared object file: No such file or directory

## Environment info (Required)
Here is the step to reproduce:
1. Install fresh EC2 Ubuntu 18.04 c5.4xlarge instance
2. sudo apt-get update
3. sudo apt-get install python-dev
4. sudo apt-get install curl
5. curl -O https://bootstrap.pypa.io/get-pip.py
6. sudo python get-pip.py
7. sudo pip install mxnet
8. python
```
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/local/lib/python2.7/dist-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgomp.so.1: cannot open shared object file: No such file or directory
>>> 
```

Package used (Python/R/Scala/Julia):
I'm using python

**Comment by vdantu** [comment]
@mxnet-label-bot add [Python, pip, installation, question]
