### ISSUE TITLE
[Bug] ValueError: There are multiple outputs with name "resnetv1b0_layers1_relu0_fwd_output".

### ISSUE THREAD

**Issue by kohillyang** [apache/incubator-mxnet#13374]
Outputs of diagnose.py:
```
----------Python Info----------
('Version      :', '2.7.14')
('Compiler     :', 'GCC 7.2.0')
('Build        :', ('default', 'Dec  7 2017 17:05:42'))
('Arch         :', ('64bit', ''))
------------Pip Info-----------
('Version      :', '18.0')
('Directory    :', '/data1/zyx/Anaconda2/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
/data1/zyx/Anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('Version      :', '1.3.0')
('Directory    :', '/data1/zyx/Anaconda2/lib/python2.7/site-packages/mxnet')
('Commit Hash   :', 'b3be92f4a48bce62a5a8424271871c2f81c8f7f1')
----------System Info----------
('Platform     :', 'Linux-4.4.0-122-generic-x86_64-with-debian-stretch-sid')
('system       :', 'Linux')
('node         :', '7b5642bf21b5')
('release      :', '4.4.0-122-generic')
('version      :', '#146-Ubuntu SMP Mon Apr 23 15:34:04 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
Stepping:              1
CPU MHz:               1277.351
CPU max MHz:           3500.0000
CPU min MHz:           1200.0000
BogoMIPS:              5201.87
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              35840K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt retpoline kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts
----------Network Test----------
Setting timeout: 10
Error open MXNet: https://github.com/apache/incubator-mxnet, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, DNS finished in 0.301597118378 sec.
Error open PYPI: https://pypi.python.org/pypi/pip, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, DNS finished in 0.295644044876 sec.
Error open FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, DNS finished in 0.346220016479 sec.
Error open Conda: https://repo.continuum.io/pkgs/free/, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, DNS finished in 0.287996053696 sec.
Error open Gluon Tutorial(en): http://gluon.mxnet.io, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, DNS finished in 0.320595979691 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>, DNS finished in 0.320269107819 sec.
```

Error Message:
```
/data1/zyx/Anaconda2/bin/python /data3/zyx/yks/mx-detection/bug.py
/data1/zyx/Anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/data3/zyx/yks/mx-detection/bug.py", line 7, in <module>
    sym_block = mx.gluon.nn.SymbolBlock(sym, [data])
  File "/data1/zyx/Anaconda2/lib/python2.7/site-packages/mxnet/gluon/block.py", line 1051, in __init__
    for j in i.get_internals():
  File "/data1/zyx/Anaconda2/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 93, in <genexpr>
    return (self[i] for i in self.list_outputs())
  File "/data1/zyx/Anaconda2/lib/python2.7/site-packages/mxnet/symbol/symbol.py", line 517, in __getitem__
    raise ValueError('There are multiple outputs with name \"%s\"' % index)
ValueError: There are multiple outputs with name "resnetv1b0_layers1_relu0_fwd_output"
```
related issues:
[#12795](https://github.com/apache/incubator-mxnet/issues/12795)

# Minimum reproducible example
```python
import gluoncv
import mxnet as mx
data = mx.sym.var(name="data")
net = gluoncv.model_zoo.resnet50_v1b(pretrained=False)
net.initialize()
sym = net(data)
sym_block = mx.gluon.nn.SymbolBlock(sym, [data])

```

**Comment by vdantu** [comment]
@mxnet-label-bot add [Gluon, Question, Bug]

**Comment by thomelane** [comment]
+1 also effecting a user here https://discuss.mxnet.io/t/error-when-trying-to-import-a-trained-net-multiple-outputs-with-name/2426

**Comment by thomelane** [comment]
Seems that `mx.gluon.nn.SymbolBlock` constructs the graph based on output names, when it should use the index of outputs instead.

**Comment by shengfeng** [comment]
I also encounter this problem when using TextCNN, here is my model:

`class TextCNN(HybridBlock):
    def __init__(self, args, vocab, kernel_sizes, num_channels, **kwargs):
        super(TextCNN, self).__init__(**kwargs)
        self.embedding = nn.Embedding(len(vocab), args.embed_size)
        self.constant_embedding = nn.Embedding(len(vocab), args.embed_size)
        self.dropout = nn.Dropout(0.5)
        self.decoder = nn.Dense(5)
        self.pool = nn.GlobalMaxPool1D()
        self.convs = nn.HybridSequential()
        for c, k in zip(num_channels, kernel_sizes):
            self.convs.add(nn.Conv1D(c, k, activation='relu'))


    def hybrid_forward(self, F, inputs):
        embeddings = F.concat(self.embedding(inputs), self.constant_embedding(inputs), dim=2)
        embeddings = embeddings.transpose((0, 2, 1))
        encoding = F.concat(*[F.flatten(
            self.pool(conv(embeddings))) for conv in self.convs], dim=1)
        outputs = self.decoder(self.dropout(encoding))
        return F.softmax(outputs)
`

**Comment by karan6181** [comment]
Hi @**kohillyang**, could you please upgrade your gluoncv version to 0.4.0(latest) using `pip install gluoncv —upgrade` since the issue is fixed in the latest gluoncv version. I have tried below scripts and it's working for me:

```python
import gluoncv
import mxnet as mx
data = mx.sym.var(name="data")
net = gluoncv.model_zoo.resnet50_v1b(pretrained=False)
net.initialize()
sym = net(data)
sym_block = mx.gluon.nn.SymbolBlock(sym, [data])
```



```python
from mxnet import gluon, nd
from gluoncv.model_zoo import get_model

x = nd.zeros(shape=(32,3,256,256))
model = get_model("ResNet50_v1c", pretrained=True)
model.hybridize()
model(x)
model.export("net",epoch=0)
model2 = gluon.nn.SymbolBlock.imports("net-symbol.json", ['data'], "net-0000.params")
```



MXNet version: 1.4.0
gluoncv version: 0.4.0

**Comment by piyushghai** [comment]
@kohillyang This issue is indeed fixed in the latest version of MXNet and GluonCV. Please upgrade to both. 

I'm suggesting to close this issue. Please feel free to re-open if closed in error.

@Roshrini Can you please close this issue ?

**Comment by kohillyang** [comment]
Yes, this issue has been fixed, I'll close it. Thanks.
