### ISSUE TITLE
ARM QEMU test in CI failed unrelated PR

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#13410]
## Description
Test with ARM QEMU fails with some kind of network interruption...

Makes wonder about these network issues where dependencies fail to download... should we put in a retry function, so that we don't have to restart our PRs when there's a transient error?

## Error
```
runtime_functions.py: 2018-11-26 03:47:02,687 ['run_ut_py3_qemu']

 ⢎⡑ ⣰⡀ ⢀⣀ ⡀⣀ ⣰⡀ ⠄ ⣀⡀ ⢀⡀   ⡎⢱ ⣏⡉ ⡷⢾ ⡇⢸
 ⠢⠜ ⠘⠤ ⠣⠼ ⠏  ⠘⠤ ⠇ ⠇⠸ ⣑⡺   ⠣⠪ ⠧⠤ ⠇⠸ ⠣⠜

runtime_functions.py: 2018-11-26 03:47:02,765 Starting VM, ssh port redirected to localhost:2222 (inside docker, not exposed by default)

runtime_functions.py: 2018-11-26 03:47:02,765 Starting in non-interactive mode. Terminal output is disabled.

runtime_functions.py: 2018-11-26 03:47:02,766 waiting for ssh to be open in the VM (timeout 300s)

runtime_functions.py: 2018-11-26 03:47:46,729 wait_ssh_open: port 127.0.0.1:2222 is open and ssh is ready

runtime_functions.py: 2018-11-26 03:47:46,729 VM is online and SSH is up

runtime_functions.py: 2018-11-26 03:47:46,729 Provisioning the VM with artifacts and sources

ssh_exchange_identification: read: Connection reset by peer

rsync: safe_write failed to write 4 bytes to socket [sender]: Broken pipe (32)

rsync error: unexplained error (code 255) at io.c(320) [sender=3.1.1]

runtime_functions.py: 2018-11-26 03:47:46,916 Shutdown via ssh

ssh_exchange_identification: read: Connection reset by peer

Traceback (most recent call last):

  File "./runtime_functions.py", line 66, in run_ut_py3_qemu

    qemu_provision(vm.ssh_port)

  File "/work/vmcontrol.py", line 186, in qemu_provision

    qemu_rsync(ssh_port, x, 'mxnet_dist/')

  File "/work/vmcontrol.py", line 175, in qemu_rsync

    check_call(['rsync', '-e', 'ssh -o StrictHostKeyChecking=no -p{}'.format(ssh_port), '-a', local_path, 'qemu@localhost:{}'.format(remote_path)])

  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['rsync', '-e', 'ssh -o StrictHostKeyChecking=no -p2222', '-a', '/work/mxnet/build/mxnet-1.4.0-py2.py3-none-any.whl', 'qemu@localhost:mxnet_dist/']' returned non-zero exit status 255
```

**Comment by vdantu** [comment]
@mxnet-label-bot add [ARM, CI, test, question]

**Comment by aaronmarkham** [comment]
More ARM CI issues here:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-12977/2/pipeline
```
Step 1/15 : FROM mxnetci/dockcross-linux-armv6:08212018

pull access denied for mxnetci/dockcross-linux-armv6, repository does not exist or may require 'docker login'
```

**Comment by larroy** [comment]
Can this be closed?

**Comment by larroy** [comment]
Should be fixed by https://github.com/apache/incubator-mxnet/commit/f6f840110d74111f98c20eab5b08d64a46ebf0cd

**Comment by larroy** [comment]
@nswamy @anirudh2290 I suggest closing for now.
