### ISSUE TITLE
flaky test: test_random.test_randint_generator

### ISSUE THREAD

**Issue by zachgk** [apache/incubator-mxnet#13446]
test_random.test_randint_generator in "Python 3: GPU Win" failed on the CI at http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13364/4/pipeline/1096/ for an unrelated PR https://github.com/apache/incubator-mxnet/pull/13364. Error log shown below:

```
======================================================================

FAIL: test_random.test_randint_generator

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py3\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 173, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_random.py", line 878, in test_randint_generator

    verify_generator(generator=generator_mx_same_seed, buckets=buckets, probs=probs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 1966, in verify_generator

    str(buckets), str(probs)))

AssertionError: Generator test fails, Chi-square p=[0.0039778006662674397, 0.0038008926958397801, 0.026007793216137099, 0.00574968961725508, 5.5082198954479213e-05], obs_freq=[array([201090, 

200294, 199907, 200047, 198662]), array([199510, 199653, 200738, 201095, 199004]), array([200553, 199797, 200146, 200679, 198825]), array([201138, 199506, 200190, 200285, 198881]), 

array([200288, 200437, 199925, 201170, 198180])], expected_freq=[array([200000, 200000, 200000, 200000, 200000]), array([200000, 200000, 200000, 200000, 200000]), array([200000, 200000, 

200000, 200000, 200000]), array([200000, 200000, 200000, 200000, 200000]), array([200000, 200000, 200000, 200000, 200000])].

buckets=[[-50000000, -40001980], [-40001980, -30003960], [-30003960, -20005940], [-20005940, -10007920], [-10007920, -9900]], probs=[0.2, 0.2, 0.2, 0.2, 0.2]

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1389836864 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by zachgk** [comment]
Another example at http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13364/5/pipeline/1097. The flaky test was introduced in https://github.com/apache/incubator-mxnet/pull/12749

**Comment by zachgk** [comment]
Another from different PR https://github.com/apache/incubator-mxnet/pull/13105 http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-13105/6/pipeline/1093
