### ISSUE TITLE
Flaky test test_random.test_negative_binomial_generator

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#13506]
test_random.test_negative_binomial_generator failed for unrelated PR #13226 on CI -
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-13226/2/pipeline/

Error log shown below:
```
======================================================================
FAIL: test_random.test_negative_binomial_generator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py2\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 173, in test_new
    orig_test(*args, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_random.py", line 607, in test_negative_binomial_generator
    verify_generator(generator=generator_mx, buckets=buckets, probs=probs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 1966, in verify_generator
    str(buckets), str(probs)))
AssertionError: Generator test fails, Chi-square p=[0.0079457258252656846, 0.015837947946066393, 0.014982295381122585, 0.026195855013954258, 0.016633761926258255], obs_freq=[array([180916, 
241305, 200546, 377233]), array([181918, 242648, 200212, 375222]), array([181759, 241455, 200567, 376219]), array([179932, 243139, 201631, 375298]), array([180884, 241170, 201088, 376858])], 
expected_freq=[array([180800, 242483, 200907, 375809]), array([180800, 242483, 200907, 375809]), array([180800, 242483, 200907, 375809]), array([180800, 242483, 200907, 375809]), 
array([180800, 242483, 200907, 375809])].
buckets=[(-1.0, 2.5), (2.5, 5.5), (5.5, 8.5), (8.5, inf)], probs=[0.18080000000000004, 0.24248320000000032, 0.20090716159999938, 0.37580963840000026]
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=53079109 to reproduce.
--------------------- >> end captured logging << ---------------------

```

**Comment by vrakesh** [comment]
@mxnet-label-bot  add [Flaky, Test, Python]

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Flaky,Test,Python]

**Comment by jlcontreras** [comment]
Also seen here: 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/master/157/pipeline
