### ISSUE TITLE
flaky test ARMv7 QEMU

### ISSUE THREAD

**Issue by zheng-da** [apache/incubator-mxnet#13504]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fedge/detail/PR-13436/2/pipeline
```
ssh_exchange_identification: read: Connection reset by peer

Traceback (most recent call last):

  File "./runtime_functions.py", line 66, in run_ut_py3_qemu

    qemu_provision(vm.ssh_port)

  File "/work/vmcontrol.py", line 186, in qemu_provision

    qemu_rsync(ssh_port, x, 'mxnet_dist/')

  File "/work/vmcontrol.py", line 175, in qemu_rsync

    check_call(['rsync', '-e', 'ssh -o StrictHostKeyChecking=no -p{}'.format(ssh_port), '-a', local_path, 'qemu@localhost:{}'.format(remote_path)])

  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['rsync', '-e', 'ssh -o StrictHostKeyChecking=no -p2222', '-a', '/work/mxnet/build/mxnet-1.4.0-py2.py3-none-any.whl', 'qemu@localhost:mxnet_dist/']' returned non-zero exit status 255

```

**Comment by vrakesh** [comment]
@mxnet-label-bot add [Flaky, Test, ARM]

**Comment by ChaiBapchya** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fedge/detail/PR-13541/2/pipeline

Yet again.

**Comment by larroy** [comment]
True, sorry about this we need to add a retry or bail out if this happens.
