### ISSUE TITLE
libmxnet_predict.so runtime error

### ISSUE THREAD

**Issue by bryanlinnan** [apache/incubator-mxnet#13724]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
use c++ api to test libmxnet_predict.so on Android device, error occurred when execute the test code
## Environment info (Required)
mxnet 1.4
android 5.1  device
libmxnet_predict.so(anroid ndk r14b toolchain compile)

```
What to do:
1. compile the libmxnet_predict.so

2. push libmxnet_predict.so to the Android device, also the c++ test program

3. run the test program 

```
## Build info (Required if built from source)
mxnet 1.4 source code
android ndk-r14b standalong toolchain
Compiler (gcc/clang/mingw/visual studio):
clang

## Error Message:
in fect, there is no error message printed, and i add some log in the source code in mxnet_predict.cc,

## Minimum reproducible example
then i found it crashed in the API 'PushAsync', the whole call order is :MXPredCreate->_CreatePartialOut->CopyFromTo->PushAsync->exec_fun(RunContext{exec_ctx, &cpu_stream_}, callback);

## Steps to reproduce
(Paste the commands you ran that produced the error.)

error occurred everytime

## What have you tried to solve it?

1. exchange ndk verision, include r13b,r16b,r14b

**Comment by vrakesh** [comment]
@mxnet-label-bot add [C++, Android]

@bryanlinnan Thank you for reporting the issue.

**Comment by bryanlinnan** [comment]
@vrakesh hi vrakesh,good news is i found the reason, bad news is the reason seems to have no good solution, i finally located the problem is caused by the bad support for ARM, when using thread_local variant, it will fail to access it.

**Comment by vrakesh** [comment]
@bryanlinnan Sounds excellent could you elaborate further on the root cause and steps used to build. So that I can try reproduce it on my end.

**Comment by bryanlinnan** [comment]
@vrakesh hi vrakesh, i finnaly made it run on my device(Sumsang exynos 5410 arm), steps:
1.first, i use android ndk r14b to make standalone toolchain
cd ~/tool/android-ndk-r14b/build/tools
python make_standalone_toolchain.py --arch arm --api 22 --install-dir /usr/local/android-toolchain --stl=libc++
2.then i build openblas, everything is ok
3. and then i build my libmxnet_predict.so,  many issues come out,  i solved them one by one
1) need to modify the makefile in amalgamation, besides modify OpenBLAS path, need to change your export PATH to the android-toolchain/bin and export CXX=android-toolchain/bin/arm-linux-androideabi-clang++, and export CC=android-toolchain/bin/arm-linux-androideabi-clang, and add more include path in the CFLAGS:
-I../include -I${TPARTYDIR}/dmlc-core/include -I${TPARTYDIR}/tvm/nnvm/include -I${TPARTYDIR}/mshadow \
-I${TPARTYDIR}/dlpack/include -I${TPARTYDIR}/tvm/nnvm -I${TPARTYDIR}/ps-lite/include,
also need to add c++11 support in the CFLAGS,
2) after successfully build, i get some error when running the test program on the device, that's because some source code was not built into the library, so i check every missed symbol, then add it into the mxnet_predict0.cc, then rebuild the library.
my mxnet_predict0.cc :
#include "src/common/utils.cc"

#include "src/ndarray/ndarray_function.cc"
#include "src/ndarray/ndarray.cc"

#include "src/imperative/imperative.cc"
#include "src/imperative/cached_op.cc"

#include "src/engine/engine.cc"
#include "src/engine/naive_engine.cc"

#include "src/profiler/profiler.cc"

#include "src/executor/graph_executor.cc"
#include "src/executor/attach_op_execs_pass.cc"
#include "src/executor/attach_op_resource_pass.cc"
#include "src/executor/inplace_addto_detect_pass.cc"

#include "src/nnvm/legacy_json_util.cc"
#include "src/nnvm/legacy_op_util.cc"

#include "src/operator/operator.cc"
#include "src/operator/operator_util.cc"
#include "src/operator/slice_channel.cc"

#include "src/operator/nn/activation.cc"
#include "src/operator/nn/batch_norm.cc"
#include "src/operator/nn/concat.cc"
#include "src/operator/nn/convolution.cc"
#include "src/operator/nn/deconvolution.cc"
#include "src/operator/nn/dropout.cc"
#include "src/operator/nn/fully_connected.cc"
#include "src/operator/nn/pooling.cc"
#include "src/operator/nn/softmax_activation.cc"
#include "src/operator/nn/softmax.cc"

#include "src/operator/softmax_output.cc"
#include "src/operator/leaky_relu.cc"

#include "src/operator/tensor/elemwise_binary_broadcast_op_basic.cc"
#include "src/operator/tensor/elemwise_binary_op.cc"
#include "src/operator/tensor/elemwise_binary_op_basic.cc"
#include "src/operator/tensor/elemwise_binary_scalar_op_basic.cc"
#include "src/operator/tensor/elemwise_unary_op_basic.cc"
#include "src/operator/tensor/elemwise_unary_op_trig.cc"
#include "src/operator/tensor/matrix_op.cc"
#include "src/operator/tensor/init_op.cc"
#include "src/operator/tensor/dot.cc"
#include "src/operator/tensor/elemwise_sum.cc"
#include "src/operator/tensor/elemwise_binary_scalar_op_logic.cc"
#include "src/operator/tensor/control_flow_op.cc"

#include "src/operator/contrib/multibox_detection.cc"
#include "src/operator/contrib/multibox_prior.cc"
//#include "src/operator/contrib/multibox_target.cc"
#include "src/operator/contrib/bounding_box.cc"
#include "src/operator/regression_output.cc"

#include "src/storage/storage.cc"

#include "src/resource.cc"
#include "src/initialize.cc"

#include "src/c_api/c_predict_api.cc"
#include "src/c_api/c_api_symbolic.cc"
#include "src/c_api/c_api_ndarray.cc"
#include "src/c_api/c_api_error.cc"

#include "../3rdparty/dmlc-core/src/io/filesys.cc"
#include "../src/executor/infer_graph_attr_pass.cc"
#include "../src/executor/graph_executor.cc"
#include "../src/c_api/c_api_profile.cc"
#include "../src/imperative/imperative_utils.cc"
#include "../src/nnvm/graph_editor.cc"
#include "../src/profiler/aggregate_stats.cc"
#include "../src/engine/openmp.cc"
  
4. then i push the libmxnet_predict.so and the test program to the deviece it will run and failed in the thread_local variant which are is_train_ and is_recording_, so i change them directly to bool false, then the test program finnally work, but the result is different with PC, and it is definitely has something with the support with ARM i guess, so could you please help verify and fix this issue? thanks a lot

**Comment by leleamol** [comment]
@mxnet-label-bot update [C API]

**Comment by leleamol** [comment]
@mxnet-label-bot add [Android]

**Comment by bykim555** [comment]
1.first, i use ndk21, android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin and 
export CC=armv7a-linux-androideabi23-clang  
export CXX=armv7a-linux-androideabi23-clang++

2.then i build openblas, everything is ok
3. and then i build my libmxnet_predict.so, many issues come out, i solved them one by one

need to modify the 'makefile' in amalgamation, besides modify OpenBLAS path, need to change your export PATH to the  android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin and exportCC=armv7a-linux-androideabi23-clang, and export XX=armv7a-linux-androideabi23-clang++, and add more include path in the CFLAGS:
-I../include -I${TPARTYDIR}/dmlc-core/include -I${TPARTYDIR}/tvm/nnvm/include -I${TPARTYDIR}/mshadow
-I${TPARTYDIR}/dlpack/include -I${TPARTYDIR}/tvm/nnvm -I${TPARTYDIR}/ps-lite/include,
also need to add c++11 support in the CFLAGS, "LDFLAGS+= -Wl,--no-warn-mismatch -lm_hard" => LDFLAGS+= -Wl,--no-warn-mismatch -lm ....
after 'amalgamation.py' in amalgamation add blacklist = [ 'x86intrin.h'] , successfully build

then i push the libmxnet_predict.so and the test program to the deviece it will run and failed in the thread_local variant which are is_train_ and is_recording_, so i change them directly to bool false, then the test program finnally work, but the result is different with PC, and it is definitely has something with the support with ARM i guess, so could you please help verify and fix this issue? 
my error log is : E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tistory.webnautes.useopencvwithndk_build, PID: 17645
    java.lang.UnsatisfiedLinkError: dlopen failed: library "E:/2020/WorkSpace/AndroidStudioProjects_backup/UseOpenCVwithndkbuild/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libmxnet_predict.so" not found
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.tistory.webnautes.useopencvwithndk_build.MainActivity.<clinit>(MainActivity.java:48)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1095)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3083)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7224)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
I changed ndk version and api version... but error is same...
