### ISSUE TITLE
Centos 7: libcrypto.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by akond** [apache/incubator-mxnet#13765]
libcrypto.so.1.0.0:
## Description
when i'm trying to run `lein run -m cnn-text-classification.classifier` i get this error: `libcrypto.so.1.0.0: cannot open shared object file` which is a very old version of openssl. 

## Environment info (Required)

```
What to do:
----------Python Info----------
('Version      :', '2.7.5')
('Compiler     :', 'GCC 4.8.5 20150623 (Red Hat 4.8.5-36)')
('Build        :', ('default', 'Oct 30 2018 23:45:53'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '18.1')
('Directory    :', '/usr/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
('Platform     :', 'Linux-3.10.0-862.14.4.el7.x86_64-x86_64-with-centos-7.5.1804-Core')
('system       :', 'Linux')
('node         :', 'centos7.test')
('release      :', '3.10.0-862.14.4.el7.x86_64')
('version      :', '#1 SMP Wed Sep 26 15:12:11 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 30
Model name:            Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
Stepping:              5
CPU MHz:               1200.000
CPU max MHz:           2668.0000
CPU min MHz:           1200.0000
BogoMIPS:              5349.80
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              8192K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fx
sr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc a
perfmperf eagerfpu pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm ssbd ib
rs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida spec_ctrl intel_stibp flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0021 sec, LOAD: 1.1929 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0601 sec, LOAD: 1.2463 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-
labels-idx1-ubyte.gz, DNS: 0.0601 sec, LOAD: 1.3541 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0968 sec, LOAD: 0.3589 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.3330 sec, LOAD: 0.4460 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1293 sec, LOAD: 1.0332 sec.
```
I'm using Clojure
```
 :dependencies [[org.clojure/clojure "1.10.0"]                        
    [org.apache.mxnet.contrib.clojure/clojure-mxnet-linux-cpu "1.3.1"]]
```

## Error Message:
INFO  MXNetJVM: Try loading mxnet-scala from native path.
INFO  MXNetJVM: Try loading mxnet-scala-linux-x86_64-gpu from native path.
INFO  MXNetJVM: Try loading mxnet-scala-linux-x86_64-cpu from native path.
WARN  MXNetJVM: MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].
INFO  org.apache.mxnet.util.NativeLibraryLoader: Loading libmxnet-scala.so from /lib/native/ copying to mxnet-scala
ERROR org.apache.mxnet.util.NativeLibraryLoader: Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /tmp/mxnet5336879748181086879/mxnet-scala: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
ERROR MXNetJVM: Couldn't find native library mxnet-scala
Exception in thread "main" Syntax error compiling at (base.clj:21:19).
	at clojure.lang.Compiler$StaticMethodExpr.eval(Compiler.java:1740)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
	at clojure.lang.Compiler.eval(Compiler.java:7181)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at org.apache.clojure_mxnet.ndarray$eval185$loading__6706__auto____186.invoke(ndarray.clj:18)
	at org.apache.clojure_mxnet.ndarray$eval185.invokeStatic(ndarray.clj:18)
	at org.apache.clojure_mxnet.ndarray$eval185.invoke(ndarray.clj:18)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at cnn_text_classification.data_helper$eval163$loading__6706__auto____164.invoke(data_helper.clj:18)
	at cnn_text_classification.data_helper$eval163.invokeStatic(data_helper.clj:18)
	at cnn_text_classification.data_helper$eval163.invoke(data_helper.clj:18)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at cnn_text_classification.classifier$eval157$loading__6706__auto____158.invoke(classifier.clj:18)
	at cnn_text_classification.classifier$eval157.invokeStatic(classifier.clj:18)
	at cnn_text_classification.classifier$eval157.invoke(classifier.clj:18)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7165)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.RT.loadResourceScript(RT.java:381)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.load(RT.java:463)
	at clojure.lang.RT.load(RT.java:428)
	at clojure.core$load$fn__6824.invoke(core.clj:6126)
	at clojure.core$load.invokeStatic(core.clj:6125)
	at clojure.core$load.doInvoke(core.clj:6109)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invokeStatic(core.clj:5908)
	at clojure.core$load_one.invoke(core.clj:5903)
	at clojure.core$load_lib$fn__6765.invoke(core.clj:5948)
	at clojure.core$load_lib.invokeStatic(core.clj:5947)
	at clojure.core$load_lib.doInvoke(core.clj:5928)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$load_libs.invokeStatic(core.clj:5985)
	at clojure.core$load_libs.doInvoke(core.clj:5969)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$require.invokeStatic(core.clj:6007)
	at clojure.core$require.doInvoke(core.clj:6007)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval140$fn__144.invoke(form-init8960574831541602142.clj:1)
	at user$eval140.invokeStatic(form-init8960574831541602142.clj:1)
	at user$eval140.invoke(form-init8960574831541602142.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7166)
	at clojure.lang.Compiler.load(Compiler.java:7635)
	at clojure.lang.Compiler.loadFile(Compiler.java:7573)
	at clojure.main$load_script.invokeStatic(main.clj:452)
	at clojure.main$init_opt.invokeStatic(main.clj:454)
	at clojure.main$init_opt.invoke(main.clj:454)
	at clojure.main$initialize.invokeStatic(main.clj:485)
	at clojure.main$null_opt.invokeStatic(main.clj:519)
	at clojure.main$null_opt.invoke(main.clj:516)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/mxnet5336879748181086879/mxnet-scala: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.apache.mxnet.util.NativeLibraryLoader$.loadLibraryFromStream(NativeLibraryLoader.scala:140)
	at org.apache.mxnet.util.NativeLibraryLoader$.loadLibrary(NativeLibraryLoader.scala:93)
	at org.apache.mxnet.Base$.<init>(Base.scala:70)
	at org.apache.mxnet.Base$.<clinit>(Base.scala)
	at org.apache.mxnet.Base.MX_REAL_TYPE(Base.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
	at clojure.lang.Compiler$StaticMethodExpr.eval(Compiler.java:1733)
	... 127 more
INFO  org.apache.mxnet.util.NativeLibraryLoader: Deleting /tmp/mxnet5336879748181086879/mxnet-scala
INFO  org.apache.mxnet.util.NativeLibraryLoader: Deleting /tmp/mxnet5336879748181086879

## Steps to reproduce
`lein run -m cnn-text-classification.classifier`

**Comment by leleamol** [comment]
@mxnet-label-bot add [Build, Installation]

**Comment by leleamol** [comment]
Hi @akond ,
I tried running the cnn-text-classification.classifier on Ubuntu and did not get the error that you have mentioned.  I ran the `ldd` on libmxnet-scala.so (for 1.3.1) but it did not report its dependency on libcrypto.so

I noticed that you are running these tests on CentOS. I could reproduce this on CentOS.
Will try to dig deeper and update the issue with my observations.

@piyushghai @lanking520

**Comment by leleamol** [comment]
Hi @akond,

As mentioned in the [ReadMe] <https://github.com/apache/incubator-mxnet/tree/master/scala-package#stable> file, the Scala packages are currently not supported for CentOS. The support for CentOS will be available in future releases.

Meanwhile, these packages can be built from source for CentOS platform and used with clojure.
The instructions to build from source are [here] <https://github.com/apache/incubator-mxnet/tree/master/contrib/clojure-package#option-3-everything-from-source>

I hope this helps. Please update the issue if you have any questions regarding building from source.

**Comment by leleamol** [comment]
@mxnet-label-bot add [Pending Requester Info]

**Comment by akond** [comment]
i tried building from the source. here is what I've got during `make scalapkg`: 
```
[INFO] /bin/sh -c cd /home/akond/mxnet/scala-package/init-native/linux-x86_64 && g++ -shared -o/home/akond/mxnet/scala-package/init-native/linux-x86_64/target/libmxnet-init-scala-linux-x86_64.so target/objs/org_apache_mxnet_init_native_c_api.o -Wl,--whole-archive -Wl,--no-whole-archive -pthread -lm -fopenmp -lrt '-Wl,-rpath=$ORIGIN' -lmxnet -L/home/akond/mxnet/scala-package/../lib
/usr/bin/ld: cannot find -lmxnet
collect2: error: ld returned 1 exit status
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MXNet Scala Package - Parent 1.5.0-SNAPSHOT ........ SUCCESS [  2.005 s]
[INFO] MXNet Scala Package - Initializer .................. SUCCESS [  3.311 s]
[INFO] MXNet Scala Package - Initializer Native Parent .... SUCCESS [  0.104 s]
[INFO] MXNet Scala Package - Initializer Native Linux-x86_64 FAILURE [  1.366 s]
[INFO] MXNet Scala Package - Macros ....................... SKIPPED
[INFO] MXNet Scala Package - Core ......................... SKIPPED
[INFO] MXNet Scala Package - Native Parent ................ SKIPPED
[INFO] MXNet Scala Package - Native Linux-x86_64 CPU-only . SKIPPED
[INFO] MXNet Scala Package - Inference .................... SKIPPED
[INFO] MXNet Scala Package - Examples ..................... SKIPPED
[INFO] MXNet Scala Package - Spark ML ..................... SKIPPED
[INFO] MXNet Scala Package - Full Parent .................. SKIPPED
[INFO] MXNet Scala Package - Full Linux-x86_64 CPU-only 1.5.0-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.361 s
[INFO] Finished at: 2019-01-05T17:33:40+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:native-maven-plugin:1.0-alpha-7:link (default-link) on project libmxnet-init-scala-linux-x86_64: Error executing command line. Exit code:1 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :libmxnet-init-scala-linux-x86_64
```

**Comment by akond** [comment]
it seems i need to build libmxnet first, but i can't find any instructions on how to build them under centos.

**Comment by lanking520** [comment]
Hi @akond sorry to hear that. You can follow the following steps:
## Install Dependencies
```
./ci/docker/install/centos7_core.sh
./ci/docker/install/centos7_scala.sh
```
## Make the backend and scalapackage
```
make -j$(nrpoc)
make scalapkg
```

**Comment by piyushghai** [comment]
@akond Did these instructions help you out ?

**Comment by akond** [comment]
I switched to windows/GNU R to do the job, because mxnet installation on windows is instantaneous, contrary to my expectations.

**Comment by vdantu** [comment]
@akond : So you moved from Scala to R? Just curious, what are we tracking now with this issue? Also, could you please try @lanking520 's suggestion to see if it fixes your issue.

**Comment by akond** [comment]
Yeah, 
```
./ci/docker/install/centos7_core.sh
./ci/docker/install/centos7_scala.sh
```
went ok, but make failed with error:

> cv_imgproc -lopencv_legacy -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv
> _video -lopencv_videostab -llapack                                                                                    
> /tmp/cc68M0Wc.o: In function `main':                                                                                  
> im2rec.cc:(.text.startup+0x1f35): undefined reference to `vtable for cv::_InputArray'                                 
> im2rec.cc:(.text.startup+0x1f89): undefined reference to `cv::imdecode(cv::_InputArray const&, int)'                  
> im2rec.cc:(.text.startup+0x2362): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'                   
> im2rec.cc:(.text.startup+0x236f): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'               
> im2rec.cc:(.text.startup+0x23ac): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'               
> im2rec.cc:(.text.startup+0x23c8): undefined reference to `cv::imencode(std::string const&, cv::_InputArray const&, std
> ::vector<unsigned char, std::allocator<unsigned char> >&, std::vector<int, std::allocator<int> > const&)'             
> im2rec.cc:(.text.startup+0x3803): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'                   
> im2rec.cc:(.text.startup+0x3810): undefined reference to `cv::_InputArray::_InputArray(cv::Mat const&)'               
> im2rec.cc:(.text.startup+0x39b7): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'                   
> im2rec.cc:(.text.startup+0x3ce9): undefined reference to `cv::_OutputArray::_OutputArray(cv::Mat&)'                   
> build/src/io/image_aug_default.o: In function `mxnet::io::DefaultImageAugmenter::Process(cv::Mat const&, std::vector<f
> loat, std::allocator<float> >*, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11
> ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>*)':                                      
> image_aug_default.cc:(.text._ZN5mxnet2io21DefaultImageAugmenter7ProcessERKN2cv3MatEPSt6vectorIfSaIfEEPSt23mersenne_twi
> ster_engineImLm32ELm624ELm397ELm31ELm2567483615ELm11ELm4294967295ELm7ELm2636928640ELm15ELm4022730752ELm18ELm1812433253
> EE[_ZN5mxnet2io21DefaultImageAugmenter7ProcessERKN2cv3MatEPSt6vectorIfSaIfEEPSt23mersenne_twister_engineImLm32ELm624EL
> m397ELm31ELm2567483615ELm11ELm4294967295ELm7ELm2636928640ELm15ELm4022730752ELm18ELm1812433253EE]+0x1a9): undefined ref
> erence to `cv::_OutputArray::_OutputArray(cv::Mat&)'                                                                  
> image_aug_default.cc:(.text._ZN5mxnet2io21DefaultImageAugmenter7ProcessERKN2cv3MatEPSt6vectorIfSaIfEEPSt23mersenne_twi
> ster_engineImLm32ELm624ELm397ELm31ELm2567483615ELm11ELm4294967295ELm7ELm2636928640ELm15ELm4022730752ELm18ELm1812433253
> EE[_ZN5mxnet2io21DefaultImageAugmenter7ProcessERKN2cv3MatEPSt6vectorIfSaIfEEPSt23mersenne_twister_engineImLm32ELm624EL
> m397ELm31ELm2567483615ELm11ELm4294967295ELm7ELm2636928640ELm15ELm4022730752ELm18ELm1812433253EE]+0x1bc): undefined ref
> erence to `cv::_InputArray::_InputArray(cv::Mat const&)'                                                              
> image_aug_default.cc:(.text._ZN5mxnet2io21DefaultImageAugmenter7ProcessERKN2cv3MatEPSt6vectorIfSaIfEEPSt23mersenne_twi
> ster_engineImLm32ELm624ELm397ELm31ELm2567483615ELm11ELm4294967295ELm7ELm2636928640ELm15ELm4022730752ELm18ELm1812433253
> EE[_ZN5mxnet2io21DefaultImageAugmenter7ProcessERKN2cv3MatEPSt6vectorIfSaIfEEPSt23mersenne_twister_engineImLm32ELm624EL
> m397ELm31ELm2567483615ELm11ELm4294967295ELm7ELm2636928640ELm15ELm4022730752ELm18ELm1812433253EE]+0x57c): undefined ref
> erence to `cv::_InputArray::_InputArray(cv::Mat const&)'                                                              
>
