### ISSUE TITLE
mxnet.ndarray.random_randint API not found

### ISSUE THREAD

**Issue by myairforce1** [apache/incubator-mxnet#13770]
## Description
I installed mxnet version 1.3.1 by 
pip install mxnet-cu90

however,  the mxnet.ndarray.random.randint API is not found. 

As per the API doc, 
mxnet.ndarray.random.randint does exist.

https://mxnet.incubator.apache.org/api/python/ndarray/random.html#mxnet.ndarray.random.randint

## Environment info (Required)
mxnet-cu90

```
----------Python Info----------
Version      : 3.6.7
Compiler     : GCC 7.3.0
Build        : ('default', 'Oct 23 2018 19:16:44')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 18.1
Directory    : /home/eric/anaconda2/envs/mxenv/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.3.1
Directory    : /home/eric/anaconda2/envs/mxenv/lib/python3.6/site-packages/mxnet
Commit Hash   : 19c501680183237d52a862e6ae1dc4ddc296305b
----------System Info----------
Platform     : Linux-4.15.0-42-generic-x86_64-with-debian-stretch-sid
system       : Linux
node         : eric-B250M-D3H
release      : 4.15.0-42-generic
version      : #45~16.04.1-Ubuntu SMP Mon Nov 19 13:02:27 UTC 2018
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Stepping:              9
CPU MHz:               3610.006
CPU max MHz:           3800.0000
CPU min MHz:           800.0000
BogoMIPS:              6816.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              6144K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0088 sec, LOAD: 0.9419 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0098 sec, LOAD: 1.6748 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0101 sec, LOAD: 1.1191 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.2433 sec, LOAD: 0.8565 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0095 sec, LOAD: 2.9483 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0079 sec, LOAD: 0.7924 sec.


```

Package used (Python/R/Scala/Julia):
(I'm using  Python)

**Comment by leleamol** [comment]
Hello @myairforce1,

The 'mxnet.ndarray.random.randint' method is not implemented in 1.3.1 version.  The implementation and documentation for this method is available in 'master' version of the repository. It is not yet released.

The documentation link that is included in the report points to the "master" version.

I tried out the function with a nightly build (mxnet_cu90-1.5.0b20190103-py2.py3-none-manylinux1_x86_64.whl) and it is failing with following error.

```
>>> mx.nd.random.randint(5, 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet/ndarray/random.py", line 561, in randint
    return _random_helper(_internal._random_randint, None,
AttributeError: 'module' object has no attribute '_random_randint'
>>>
```

The code was recently added with pull request #12749 
@eric-haibin-lin @ChaiBapchya  can you please take a look?

**Comment by leleamol** [comment]
@mxnet-label-bot add [NDArray, Bug]

**Comment by leleamol** [comment]
I have tried the latest mxnet and mxnet-cu90 pip packages on fresh cpu and gpu machines.
The code is working as expected.  Please disregard my comment about failure with the latest nightly package.
```

Successfully installed mxnet-cu90-1.5.0b20190103 numpy-1.14.6 requests-2.21.0
ubuntu@ip-172:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> from mxnet import ndarray
>>> a = mx.nd.random.randint(5,200)
>>> a

[66]
<NDArray 1 @cpu(0)>
>>> a = mx.nd.random.randint(5,200, ctx=mx.gpu(0))

>>> a
[85]
<NDArray 1 @gpu(0)>
>>> 

```

As I mentioned above the randint() functionality is not available in the released version (1.3.1)  of MxNet.

I will remove the label "Bug" since it is working with the latest builds. I would propose to close this issue if it answers @myairforce1 's question.

**Comment by leleamol** [comment]
@mxnet-label-bot update [NDArray, Pending Requester Info]
