### ISSUE TITLE
Raspberry Pi 3  docker missing information ?

### ISSUE THREAD

**Issue by MyraBaba** [apache/incubator-mxnet#13790]
Hi,

According to the documentation : 

>  Build
> 
> Please use a Native build with gcc 4 as explained below, higher compiler versions currently cause test failures on ARM
> 
> The following command will build a container with dependencies and tools and then compile MXNet for ARMv7. The resulting artifact will be located in build/mxnet-x.x.x-py2.py3-none-any.whl, copy this file to your Raspberry Pi.
> 
> 
> ci/build.py -p armv7

I can't find the ci/build.py . command ?

is it a docker image I tried : docker run ci/build.py -p armv7 no such image ?

1 - What is the exact steps for compiling mxnet in docker which is host machine is mac os x. ? 

2 - I compiled on the Raspberry pi 3 but when I try to load models it gives Segmentation fault ? 

What is the working branch for Raspberry pi 3?

thanks

**Comment by zachgk** [comment]
You should be able to run the build script using `python3 ci/build.py -p armv7` from your incubator-mxnet directory. The master branch should work fine.

@mxnet-label-bot add [Build, Edge Devices]

**Comment by MyraBaba** [comment]
Thanks..

Is there ANY pre-build  raspberry pi 3 wheel for installing *

**Comment by MyraBaba** [comment]
@zachgk Hi I tried ci/build.py -p armv7 from incubator-mxnet I have below error after a while 👍 

OS is Mac os x and python 3 docker : Version 18.06.1-ce-mac73 (26764)

`Removing intermediate container 3a8023a7d627
 ---> f2bd1edb8bea
Step 14/19 : ARG USER_ID=0
 ---> Running in 50cae7e4d1ef
Removing intermediate container 50cae7e4d1ef
 ---> abd755483ded
Step 15/19 : ARG GROUP_ID=0
 ---> Running in 7bb7072eab1d
Removing intermediate container 7bb7072eab1d
 ---> 08a676ca7a71
Step 16/19 : COPY install/ubuntu_adduser.sh /work/
 ---> 9ed6e629fa4c
Step 17/19 : RUN /work/ubuntu_adduser.sh
 ---> Running in 44647e33f89c
+ [[ 501 -gt 0 ]]
+ [[ -n 20 ]]
+ [[ 20 -gt 0 ]]
+ groupadd --gid 20 --system jenkins_slave
groupadd: GID '20' already exists
The command '/bin/sh -c /work/ubuntu_adduser.sh' returned a non-zero code: 4
Traceback (most recent call last):
  File "ci/build.py", line 571, in <module>
    sys.exit(main())
  File "ci/build.py", line 485, in main
    num_retries=args.docker_build_retries, no_cache=args.no_cache)
  File "ci/build.py", line 160, in build_docker
    run_cmd()
  File "/Users/alpullu/incubator-mxnet/ci/util.py", line 77, in f_retry
    return f(*args, **kwargs)
  File "ci/build.py", line 158, in run_cmd
    check_call(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'build', '-f', 'docker/Dockerfile.build.armv7', '--build-arg', 'USER_ID=501', '--build-arg', 'GROUP_ID=20', '--cache-from', 'mxnetci/build.armv7', '-t', 'mxnetci/build.armv7', 'docker']' returned non-zero exit status 4.
`


I think same issue with the   [13759](https://github.com/apache/incubator-mxnet/issues/13759)
