### ISSUE TITLE
module 'mxnet.symbol' has no attribute 'WarpCTC'

### ISSUE THREAD

**Issue by mahmoodn** [apache/incubator-mxnet#14096]
I want to run speech recognition example and I have followed the steps in the readme file. Here are the commands I ran to prepare the example
```
pip install mxboard
pip install soundfile
git clone https://github.com/baidu-research/warp-ctc.git
cd warp-ctc/ && mkdir build  && cd build/
cmake .. && make
```
So, I can verify the preparations
```
$ cat Libri_sample.json 
{"duration": 2.9450625, "text": "and sharing her house which was near by", "key": "./Libri_sample/3830-12531-0030.wav"}
{"duration": 3.94, "text": "we were able to impart the information that we wanted", "key": "./Libri_sample/3830-12529-0005.wav"}
$ ls Libri_sample
3830-12529-0005.wav  3830-12531-0030.wav
$ echo $LD_LIBRARY_PATH
/home/mahmood/mx/mxnet/example/speech_recognition/warp-ctc/build::/usr/local/cuda-10.0/lib64
```

However, I the run isn't successful and I get the following error

```
$ python main.py --configfile default.cfg
================================================================================
[   DEBUG][2019/02/08 16:55:28.242] LabelUtil init
[    INFO][2019/02/08 16:55:28.243] Reading description file: ./Libri_sample.json for partition: train
[    INFO][2019/02/08 16:55:28.243] Reading description file: ./Libri_sample.json for partition: validation
[    INFO][2019/02/08 16:55:28.243] Generate mean and std from samples
[    INFO][2019/02/08 16:55:28.243] Calculating mean and std from samples
[    INFO][2019/02/08 16:55:28.356] End calculating mean and std from samples
[    INFO][2019/02/08 16:55:28.372] Config:
[    INFO][2019/02/08 16:55:28.373] [common]
[    INFO][2019/02/08 16:55:28.373] mode = train
[    INFO][2019/02/08 16:55:28.373] context = gpu0
[    INFO][2019/02/08 16:55:28.373] prefix = test_fc
[    INFO][2019/02/08 16:55:28.373] model_file = test_fc-0040
[    INFO][2019/02/08 16:55:28.373] batch_size = 2
[    INFO][2019/02/08 16:55:28.373] log_filename = test.log
[    INFO][2019/02/08 16:55:28.373] save_checkpoint_every_n_epoch = 20
[    INFO][2019/02/08 16:55:28.373] save_checkpoint_every_n_batch = 1000
[    INFO][2019/02/08 16:55:28.373] is_bi_graphemes = False
[    INFO][2019/02/08 16:55:28.373] mxboard_log_dir = mxlog/libri_sample
[    INFO][2019/02/08 16:55:28.373] mx_random_seed = 1234
[    INFO][2019/02/08 16:55:28.373] random_seed = 1234
[    INFO][2019/02/08 16:55:28.373] kvstore_option = device
[    INFO][2019/02/08 16:55:28.373] 
[    INFO][2019/02/08 16:55:28.374] [data]
[    INFO][2019/02/08 16:55:28.374] max_duration = 16.0
[    INFO][2019/02/08 16:55:28.374] train_json = ./Libri_sample.json
[    INFO][2019/02/08 16:55:28.374] test_json = ./Libri_sample.json
[    INFO][2019/02/08 16:55:28.374] val_json = ./Libri_sample.json
[    INFO][2019/02/08 16:55:28.374] language = en
[    INFO][2019/02/08 16:55:28.374] width = 161
[    INFO][2019/02/08 16:55:28.374] height = 1
[    INFO][2019/02/08 16:55:28.374] channel = 1
[    INFO][2019/02/08 16:55:28.374] stride = 1
[    INFO][2019/02/08 16:55:28.374] 
[    INFO][2019/02/08 16:55:28.374] [arch]
[    INFO][2019/02/08 16:55:28.374] channel_num = 32
[    INFO][2019/02/08 16:55:28.374] conv_layer1_filter_dim = [11, 41]
[    INFO][2019/02/08 16:55:28.374] conv_layer1_stride = [2, 2]
[    INFO][2019/02/08 16:55:28.374] conv_layer2_filter_dim = [11, 21]
[    INFO][2019/02/08 16:55:28.374] conv_layer2_stride = [1, 2]
[    INFO][2019/02/08 16:55:28.375] num_rnn_layer = 1
[    INFO][2019/02/08 16:55:28.375] num_hidden_rnn_list = [1760]
[    INFO][2019/02/08 16:55:28.375] num_hidden_proj = 0
[    INFO][2019/02/08 16:55:28.375] num_rear_fc_layers = 0
[    INFO][2019/02/08 16:55:28.375] num_hidden_rear_fc_list = []
[    INFO][2019/02/08 16:55:28.375] act_type_rear_fc_list = []
[    INFO][2019/02/08 16:55:28.375] rnn_type = bigru
[    INFO][2019/02/08 16:55:28.375] lstm_type = fc_lstm
[    INFO][2019/02/08 16:55:28.375] is_batchnorm = True
[    INFO][2019/02/08 16:55:28.375] is_bucketing = False
[    INFO][2019/02/08 16:55:28.375] buckets = []
[    INFO][2019/02/08 16:55:28.375] arch_file = arch_deepspeech
[    INFO][2019/02/08 16:55:28.375] n_classes = 28
[    INFO][2019/02/08 16:55:28.375] max_t_count = 393
[    INFO][2019/02/08 16:55:28.375] max_label_length = 53
[    INFO][2019/02/08 16:55:28.375] 
[    INFO][2019/02/08 16:55:28.375] [train]
[    INFO][2019/02/08 16:55:28.375] num_epoch = 50
[    INFO][2019/02/08 16:55:28.376] learning_rate = 0.005
[    INFO][2019/02/08 16:55:28.376] learning_rate_annealing = 1.1
[    INFO][2019/02/08 16:55:28.376] initializer = Xavier
[    INFO][2019/02/08 16:55:28.376] init_scale = 2
[    INFO][2019/02/08 16:55:28.376] factor_type = in
[    INFO][2019/02/08 16:55:28.376] show_every = 1
[    INFO][2019/02/08 16:55:28.376] save_optimizer_states = True
[    INFO][2019/02/08 16:55:28.376] normalize_target_k = 2
[    INFO][2019/02/08 16:55:28.376] overwrite_meta_files = True
[    INFO][2019/02/08 16:55:28.376] overwrite_bi_graphemes_dictionary = False
[    INFO][2019/02/08 16:55:28.376] save_feature_as_csvfile = False
[    INFO][2019/02/08 16:55:28.376] enable_logging_train_metric = True
[    INFO][2019/02/08 16:55:28.376] enable_logging_validation_metric = True
[    INFO][2019/02/08 16:55:28.376] 
[    INFO][2019/02/08 16:55:28.376] [load]
[    INFO][2019/02/08 16:55:28.376] load_optimizer_states = True
[    INFO][2019/02/08 16:55:28.376] is_start_from_batch = False
[    INFO][2019/02/08 16:55:28.376] 
[    INFO][2019/02/08 16:55:28.377] [optimizer]
[    INFO][2019/02/08 16:55:28.377] optimizer = adam
[    INFO][2019/02/08 16:55:28.377] optimizer_params_dictionary = {"beta1":0.9,"beta2":0.999}
[    INFO][2019/02/08 16:55:28.377] clip_gradient = 0
[    INFO][2019/02/08 16:55:28.377] weight_decay = 0.
[    INFO][2019/02/08 16:55:28.377] 
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    model_loaded, model_num_epoch = load_model(args, contexts, data_train)
  File "main.py", line 236, in load_model
    model_loaded = symbol_template.arch(args)
  File "/home/mahmood/mx/mxnet/example/speech_recognition/arch_deepspeech.py", line 186, in arch
    (args.config.getint('arch', 'n_classes') + 1))
  File "/home/mahmood/mx/mxnet/example/speech_recognition/stt_layer_warpctc.py", line 37, in warpctc_layer
    net = mx.sym.WarpCTC(data=net, label=label, label_length=num_label, input_length=seq_len)
AttributeError: module 'mxnet.symbol' has no attribute 'WarpCTC'

```
What is missing then?

**Comment by lanking520** [comment]
@mahmoodn Could you please provide more information of the code you have tried to run? You can find the fix in here: https://github.com/apache/incubator-mxnet/issues/9078

**Comment by ThomasDelteil** [comment]
@mahmoodn to run this example you need to compile MXNet from source with the warpCTC from Baidu due to licensing issues. Instructions are availables here:  https://github.com/apache/incubator-mxnet/tree/master/example/speech_recognition#environments
