### ISSUE TITLE
Flaky test_random.test_exponential_generator @ Python3: Centos 7 CPU

### ISSUE THREAD

**Issue by perdasilva** [apache/incubator-mxnet#14187]
## Description

Flaky test_random.test_exponential_generator, see [ci log](http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-cpu/detail/master/335/pipeline/)

Possibly related to: #13743 #9843

```
======================================================================
FAIL: test_random.test_exponential_generator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/unittest/common.py", line 173, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/unittest/test_random.py", line 568, in test_exponential_generator
    verify_generator(generator=generator_mx_same_seed, buckets=buckets, probs=probs)
  File "/work/mxnet/python/mxnet/test_utils.py", line 1981, in verify_generator
    str(buckets), str(probs)))

AssertionError: Generator test fails, Chi-square p=[0.04597345598851394, 0.00806215179160343, 0.49861699605777643, 0.027832358365877163, 0.0034672029357480033], obs_freq=[array([200307, 200598, 198996, 199563, 200536]), array([200871, 199038, 199284, 200744, 200063]), array([200479, 199348, 200133, 200026, 200014]), array([199379, 200671, 200180, 199084, 200686]), array([200063, 201074, 198606, 200173, 200084])], expected_freq=[array([200000, 200000, 200000, 200000, 200000], dtype=int32), array([200000, 200000, 200000, 200000, 200000], dtype=int32), array([200000, 200000, 200000, 200000, 200000], dtype=int32), array([200000, 200000, 200000, 200000, 200000], dtype=int32), array([200000, 200000, 200000, 200000, 200000], dtype=int32)].

buckets=[(0.0, 0.22314355131420976), (0.22314355131420976, 0.5108256237659907), (0.5108256237659907, 0.916290731874155), (0.916290731874155, 1.6094379124341005), (1.6094379124341005, inf)], probs=[0.2, 0.2, 0.2, 0.2, 0.2]

-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=802281670 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by perdasilva** [comment]
Fixed by #14287
