### ISSUE TITLE
"Convert symbol" tool Can't convert Softmaxwithloss from caffe to mxnet?

### ISSUE THREAD

**Issue by Ian8888** [apache/incubator-mxnet#14201]
I using Convert_symbol.py tool from https://mxnet.incubator.apache.org/versions/master/faq/caffe.html

I meet the question : 

Traceback (most recent call last):
  File "/home/mnxnet-cv307/mxnet/tools/caffe_converter/convert_model.py", line 231, in <module>
    main()
  File "/home/mnxnet-cv307/mxnet/tools/caffe_converter/convert_model.py", line 227, in main
    convert_model(args.prototxt, args.caffemodel, args.save_model_name)
  File "/home/mnxnet-cv307/mxnet/tools/caffe_converter/convert_model.py", line 67, in convert_model
    sym, input_dim = convert_symbol(prototxt_fname)
  File "/home/mnxnet-cv307/mxnet/tools/caffe_converter/convert_symbol.py", line 315, in convert_symbol
    sym, output_name, input_dim = _parse_proto(prototxt_fname)
  File "/home/mnxnet-cv307/mxnet/tools/caffe_converter/convert_symbol.py", line 264, in _parse_proto
    raise ValueError('Unknown layer %s %s!' % (layer.name, layer.type))
_ValueError: Unknown layer SoftmaxWithLoss_

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Caffe integration]
