### ISSUE TITLE
mxnet-cu92 and cuda 10 problem

### ISSUE THREAD

**Issue by mahmoodn** [apache/incubator-mxnet#14206]
I had no problem with mxnet and cuda 10 before, but now I can not make it run. Although I have installed `mxnet-cu92` and `mxnet`, I get the following error

```
$ python binary_rbm_gluon.py  --num-epoch 1 --num-hidden 10
Traceback (most recent call last):
  File "binary_rbm_gluon.py", line 21, in <module>
    import mxnet as mx
  File "/home/mahmood/.local/lib/python2.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/mahmood/.local/lib/python2.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/mahmood/.local/lib/python2.7/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/home/mahmood/.local/lib/python2.7/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.2: cannot open shared object file: No such file or directory

````

You can see below

```
$ pip install --user mxnet-cu92
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting mxnet-cu92
  Using cached https://files.pythonhosted.org/packages/3b/18/b4d7a80ee371bc18ac08e1714402a281af806e09aba108a10f6590720fff/mxnet_cu92-1.3.1-py2.py3-none-manylinux1_x86_64.whl
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /home/mahmood/.local/lib/python2.7/site-packages (from mxnet-cu92) (0.8.4)
Requirement already satisfied: numpy<1.15.0,>=1.8.2 in /home/mahmood/.local/lib/python2.7/site-packages (from mxnet-cu92) (1.14.6)
Requirement already satisfied: requests>=2.20.0 in /home/mahmood/.local/lib/python2.7/site-packages (from mxnet-cu92) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet-cu92) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet-cu92) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet-cu92) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet-cu92) (2.6)
Installing collected packages: mxnet-cu92
Successfully installed mxnet-cu92-1.3.1
```
and
```
$ pip install --user mxnet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: mxnet in /home/mahmood/.local/lib/python2.7/site-packages (1.3.1)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in /home/mahmood/.local/lib/python2.7/site-packages (from mxnet) (0.8.4)
Requirement already satisfied: numpy<1.15.0,>=1.8.2 in /home/mahmood/.local/lib/python2.7/site-packages (from mxnet) (1.14.6)
Requirement already satisfied: requests>=2.20.0 in /home/mahmood/.local/lib/python2.7/site-packages (from mxnet) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /home/mahmood/.local/lib/python2.7/site-packages (from requests>=2.20.0->mxnet) (2.6)
```
The cuda is 10
```
$ ls /usr/local/cuda-10.0/lib64/libcudart*
/usr/local/cuda-10.0/lib64/libcudart.so       /usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
/usr/local/cuda-10.0/lib64/libcudart.so.10.0  /usr/local/cuda-10.0/lib64/libcudart_static.a
```

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Installation, cuda]

**Comment by lanking520** [comment]
Hi @mahmoodn do you have CUDA 9.2 installed on your machine? It looks like the nvcc path is not properly configed. 

Note: Different CUDA version do not compatible with each other. Such as install CUDA 10 cannot run package built on CUDA 9.2
