### ISSUE TITLE
seed_state must be int

### ISSUE THREAD

**Issue by mahmoodn** [apache/incubator-mxnet#14233]
Hi,
May I know how to fix this error?
```
mahmood@orca:restricted-boltzmann-machine$ python binary_rbm_gluon.py 
Namespace(ais_batch_size=100, ais_burn_in_steps=10, ais_intermediate_steps=10, ais_num_batch=10, batch_size=80, cuda=True, data_loader_num_worker=4, device_id=0, k=30, learning_rate=0.1, momentum=0.3, num_epoch=130, num_hidden=500)
Traceback (most recent call last):
  File "binary_rbm_gluon.py", line 56, in <module>
    mx.random.seed(pyrnd.getrandbits(32))
  File "/home/mahmood/mx/mxnet/python/mxnet/random.py", line 94, in seed
    raise ValueError('seed_state must be int')
ValueError: seed_state must be int
```

Following packages are installed 
```
mahmood@orca:restricted-boltzmann-machine$ pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package                            Version     Location                     
---------------------------------- ----------- -----------------------------
asn1crypto                         0.24.0      
astroid                            1.6.5       
backports.functools-lru-cache      1.5         
backports.shutil-get-terminal-size 1.0.0       
certifi                            2018.11.29  
cffi                               1.12.1      
chardet                            3.0.4       
colorama                           0.4.1       
colorlog                           4.0.2       
configparser                       3.7.1       
cpplint                            1.3.0       
cryptography                       2.1.4       
cycler                             0.10.0      
Cython                             0.29.3      
darksky                            0.3         
darksky-catalog                    0.1.3       
decorator                          4.3.0       
dnspython                          1.15.0      
enum34                             1.1.6       
funcsigs                           1.0.2       
functools32                        3.2.3.post2 
futures                            3.2.0       
graphviz                           0.8.4       
h5py                               2.8.0rc1    
idna                               2.6         
ipaddress                          1.0.17      
ipython                            5.8.0       
ipython-genutils                   0.2.0       
isort                              4.3.4       
Keras                              2.2.4       
Keras-Applications                 1.0.7       
Keras-Preprocessing                1.0.9       
keyring                            10.6.0      
keyrings.alt                       3.0         
kiwisolver                         1.0.1       
lazy-object-proxy                  1.3.1       
mapq                               0.3         
matplotlib                         2.2.3       
mccabe                             0.6.1       
mock                               2.0.0       
mpmath                             1.1.0       
mxboard                            0.1.0       
mxnet                              1.5.0       /home/mahmood/mx/mxnet/python
nose                               1.3.7       
nose-timer                         0.7.4       
numpy                              1.14.6      
olefile                            0.46        
oletools                           0.53.1      
pathlib2                           2.3.3       
pbr                                5.1.1       
pexpect                            4.6.0       
pickleshare                        0.7.5       
Pillow                             5.4.1       
pip                                19.0.3      
prettytable                        0.7.2       
prompt-toolkit                     1.0.15      
protobuf                           3.6.1       
ptyprocess                         0.6.0       
pycparser                          2.19        
pycrypto                           2.6.1       
Pygments                           2.3.1       
pygobject                          3.26.1      
pylint                             1.8.3       
pyparsing                          2.3.1       
python-dateutil                    2.7.5       
pytz                               2018.9      
pyxdg                              0.25        
PyYAML                             3.13        
requests                           2.21.0      
scandir                            1.9.0       
scipy                              1.0.1       
SecretStorage                      2.3.1       
setuptools                         40.6.3      
simplegeneric                      0.8.1       
simplejson                         3.16.0      
singledispatch                     3.4.0.3     
six                                1.12.0      
SoundFile                          0.10.2      
subprocess32                       3.5.3       
sympy                              1.3         
thingking                          1.1.1       
traitlets                          4.3.2       
Unidecode                          1.0.23      
urllib3                            1.22        
vipermonkey                        0.7         
wcwidth                            0.1.7       
wheel                              0.32.3      
wrapt                              1.11.1      
xlrd                               1.2.0       
yt                                 3.5.0       
```

**Comment by frankfliu** [comment]
@mxnet-label-bot add [Gluon, question]

**Comment by mahmoodn** [comment]
Hi
Is there any temporary workaround for that?

**Comment by wkcn** [comment]
@mahmoodn 
Sorry for late reply. It is a bug since the type of pyrnd.getrandbits(32) is long in python2.

mx.random.seed(int(pyrnd.getrandbits(32))) will work.

**Comment by mahmoodn** [comment]
Thanks for the reply.

```$ grep random.seed /home/mahmood/mx/mxnet/python/mxnet/random.py
    `mx.random.seed(seed_state)` sets the state of each generator using `seed_state` and the
    >>> mx.random.seed(128)
    >>> mx.random.seed(128)
    >>> mx.random.seed(128)
    >>> mx.random.seed(128)
    >>> mx.random.seed(128, ctx=mx.gpu(0))
    >>> mx.random.seed(128, ctx=mx.gpu(1))
```
Should I change all of them?
Also, should I run make or `pip install --user -e .` or nothing?
