### ISSUE TITLE
[Flaky] test_operator_gpu.test_adamax

### ISSUE THREAD

**Issue by junrushao1994** [apache/incubator-mxnet#14292]
http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-gpu/branches/PR-14192/runs/6/nodes/271/log/?start=0

```
======================================================================
FAIL: test_operator_gpu.test_adamax
----------------------------------------------------------------------

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.7/dist-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 173, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/gpu/../unittest/test_optimizer.py", line 770, in test_adamax
    compare_optimizer(opt1(**kwarg), opt2(**kwarg), shape, dtype)
  File "/work/mxnet/python/mxnet/test_utils.py", line 2023, in compare_optimizer
    assert_almost_equal(w1.asnumpy(), w2.asnumpy(), rtol=rtol, atol=atol)
  File "/work/mxnet/python/mxnet/test_utils.py", line 495, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 

Items are not equal:
Error nan exceeds tolerance rtol=0.000100, atol=0.000010.  Location of maximum error:(1, 2, 1), a=nan, b=nan
 a: array([[[0.7721019 , 0.41911712, 0.3334103 , 0.51363254, 0.48365226],
        [0.7987629 , 0.83426726, 0.33189234, 0.09513346, 0.8376728 ],
        [0.8585542 , 0.4839913 , 0.43884215, 0.9665767 , 0.54798675],...
 b: array([[[0.7721019 , 0.41911712, 0.3334103 , 0.51363254, 0.48365226],
        [0.7987629 , 0.83426726, 0.33189234, 0.09513346, 0.8376728 ],
        [0.8585542 , 0.4839913 , 0.43884215, 0.9665767 , 0.54798675],...
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1084535268 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by junrushao1994** [comment]
@mxnet-label-bot add [Test, Flaky]

**Comment by szha** [comment]
Still occurring http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-gpu/branches/PR-18146/runs/18/nodes/425/steps/728/log/?start=0
