### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by mahmoodn** [apache/incubator-mxnet#14309]
I have converted an 3 minutes MP3 file to WAV and fed that to the speech recognition example. However, I get this error

```
$ python main.py --configfile default.cfg
================================================================================
[   DEBUG][2019/03/04 00:06:17.136] LabelUtil init
[    INFO][2019/03/04 00:06:17.137] Reading description file: ./Libri_sample.json for partition: train
[    INFO][2019/03/04 00:06:17.138] Reading description file: ./Libri_sample.json for partition: validation
[    INFO][2019/03/04 00:06:17.138] Generate mean and std from samples
[    INFO][2019/03/04 00:06:17.138] Calculating mean and std from samples
Traceback (most recent call last):
  File "main.py", line 299, in <module>
    data_train, data_val, args = load_data(args)
  File "main.py", line 115, in load_data
    datagen.sample_normalize(normalize_target_k, True)
  File "/home/mahmood/mx/mxnet/example/speech_recognition/stt_datagenerator.py", line 271, in sample_normalize
    feat = np.sum(np.vstack([item['feat'] for item in return_dict.values()]), axis=0)
  File "/home/mahmood/.local/lib/python2.7/site-packages/numpy/core/shape_base.py", line 234, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate
```

**Comment by piyushghai** [comment]
@mahmoodn Can you provide a minimum reproducible code for it ?
We'll try to help you out here.

@mxnet-label-bot Add [Python]
