### ISSUE TITLE
AssertionError: wx and wy should be equal

### ISSUE THREAD

**Issue by Cryptiex** [apache/incubator-mxnet#14398]
## Description
I am running the DeepIM implementation with MXNET as the backend. At some point the program always crashes and shows the error "_AssertionError: wx and wy should be equal_"

## Environment info (Required)
The system uses Ubuntu 16.04.

Error in CustomOp.forward: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mxnet/operator.py", line 987, in forward_entry
    aux=tensors[4])
  File "experiments/deepim/../../deepim/operator_py/zoom_flow.py", line 52, in forward
    assert wx == wy, 'wx and wy should be equal'
AssertionError: wx and wy should be equal

terminate called after throwing an instance of 'dmlc::Error'
  what():  [14:58:35] src/operator/custom/custom.cc:347: Check failed: reinterpret_cast<CustomOpFBFunc>( params.info->callbacks[kCustomOpForward])( ptrs.size(), const_cast<void**>(ptrs.data()), const_cast<int*>(tags.data()), reinterpret_cast<const int*>(req.data()), static_cast<int>(ctx.is_train), params.info->contexts[kCustomOpForward]) 

Stack trace returned 8 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x40123a) [0x7f271d3b823a]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x401851) [0x7f271d3b8851]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x6bc999) [0x7f271d673999]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x6d7110) [0x7f271d68e110]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x6bd8c8) [0x7f271d6748c8]
[bt] (5) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd8f0) [0x7f27648c18f0]
[bt] (6) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f27698c56db]
[bt] (7) /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f2769bfe88f]

**Comment by wkcn** [comment]
The bug seems to be related to DeepIM，rather than MXNet.

**Comment by andrewfayres** [comment]
@mxnet-label-bot add [Operator]

DeepIM has an [open issue](https://github.com/liyi14/mx-DeepIM/issues/24) for this.
