### ISSUE TITLE
[Flaky Test] Python 3: GPU WIN test_operator_gpu.test_multinomial_generator

### ISSUE THREAD

**Issue by perdasilva** [apache/incubator-mxnet#14457]
## Description

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/master/439/pipeline

Related to issue #14158, PR for disabling test: #14158

```
======================================================================
FAIL: test_operator_gpu.test_multinomial_generator
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python37\lib\site-packages\nose\util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_random.py", line 645, in test_multinomial_generator
    nsamples=samples, nrepeat=trials)
  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 1974, in verify_generator
    str(buckets), str(probs)))
AssertionError: Generator test fails, Chi-square p=[0.02041781458706078, 0.028884094494188908, 0.02219795510610374, 0.005126137072758969, 0.9090338945677532], obs_freq=[array([ 99260, 199877, 
300135,  49648, 150759, 200321]), array([ 99605, 199454, 299476,  49930, 150767, 200768]), array([100557, 199111, 300126,  50006, 150528, 199672]), array([ 99920, 199563, 299798,  49385, 
149686, 201648]), array([100259, 199951, 299738,  49862, 149669, 200521])], expected_freq=[array([100097, 200195, 299804,  49804, 149902, 200195]), array([100097, 200195, 299804,  49804, 
149902, 200195]), array([100097, 200195, 299804,  49804, 149902, 200195]), array([100097, 200195, 299804,  49804, 149902, 200195]), array([100097, 200195, 299804,  49804, 149902, 200195])].
buckets=[0, 1, 2, 3, 4, 5], probs=[0.10009766 0.20019531 0.29980469 0.04980469 0.14990234 0.20019531]
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1977809943 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by zachgk** [comment]
@mxnet-label-bot add [Test, Flaky, Windows, Python]
