### ISSUE TITLE
Unable to load mxnet-cu100 on Windows 10 after install

### ISSUE THREAD

**Issue by Rmwak** [apache/incubator-mxnet#14479]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)

Installed mxnet-cu100 on a new environment via pip. After the installation, a simple import mxnet throws "[WinError 126] The specified module could not be found". Regular mxnet or mxnet-mkl versions work correctly.

## Environment info (Required)

name: mxnet-gpu
channels:
  - defaults
dependencies:
  - certifi=2019.3.9=py36_0
  - pip=19.0.3=py36_0
  - python=3.6.8=h9f7ef89_7
  - setuptools=40.8.0=py36_0
  - sqlite=3.27.2=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.33.1=py36_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
    - chardet==3.0.4
    - idna==2.6
    - mxnet-cu100==1.4.0.post0
    - numpy==1.14.6
    - python-graphviz==0.8.4
    - requests==2.18.4
    - urllib3==1.22
prefix: C:\ProgramData\Anaconda3\envs\mxnet-gpu

```
----------Python Info----------
Version      : 3.6.8
Compiler     : MSC v.1916 64 bit (AMD64)
Build        : ('default', 'Feb 21 2019 18:30:04')
Arch         : ('64bit', 'WindowsPE')
------------Pip Info-----------
Version      : 19.0.3
Directory    : C:\ProgramData\Anaconda3\envs\mxnet-gpu\lib\site-packages\pip
----------MXNet Info-----------
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Windows-10-10.0.17134-SP0
system       : Windows
node         : DESKTOP-FOVF4T5
release      : 10
version      : 10.0.17134
----------Hardware Info----------
machine      : AMD64
processor    : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Name
Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0231 sec, LOAD: 1.1175 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0695 sec, LOAD: 0.8500 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1303 sec, LOAD: 0.8916 sec.
Error open FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>, DNS finished in 0.04058718681335449 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0205 sec, LOAD: 1.0213 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0465 sec, LOAD: 0.2884 sec.

```

```
nvidia-smi
Wed Mar 20 18:45:05 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 419.35       Driver Version: 419.35       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8    N/A /  N/A |     75MiB /  4096MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```
 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:26_Pacific_Standard_Time_2019
Cuda compilation tools, release 10.1, V10.1.105
```

## Error Message:

Python 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\mxnet-gpu\lib\site-packages\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\ProgramData\Anaconda3\envs\mxnet-gpu\lib\site-packages\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\ProgramData\Anaconda3\envs\mxnet-gpu\lib\site-packages\mxnet\base.py", line 213, in <module>
    _LIB = _load_lib()
  File "C:\ProgramData\Anaconda3\envs\mxnet-gpu\lib\site-packages\mxnet\base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "C:\ProgramData\Anaconda3\envs\mxnet-gpu\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

## Minimum reproducible example

The error happens as soon as imported after a fresh install.

```
conda create -n mxnet-gpu python=3.6
conda activate mxnet-gpu
pip install mxnet-cu100
```
open console

```
python
import mxnet as mx
```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

Same as before

## What have you tried to solve it?

Search for the posible .dll required but not listed in the error message (without luck).

**Comment by zachgk** [comment]
Hi @Rmwak, have you looked at our windows setup instructions https://mxnet.incubator.apache.org/versions/master/install/windows_setup.html? You need to install some extra dependencies for cuda and cudnn before it will work.

@mxnet-label-bot add [Installation, pip, Windows]

**Comment by Rmwak** [comment]
Hello zachgk.

The requirements in that link are:

> Install with CUDA Support
> The following steps will setup MXNet with CUDA. cuDNN can be enabled only when building from source.
> 
> Install Microsoft Visual Studio 2017 or Microsoft Visual Studio 2015.

Microsoft Visual Studio 2017 is in my system

> Download and install NVIDIA CUDA. CUDA versions 9.2 or 9.0 are recommended. Some issues with CUDA 9.1 have been identified in the past.

I have CUDA 10.1 installed in the system, for the mxnet-cu100 version

> Download and install NVIDIA_CUDA_DNN

Already in place, version 7.5
```
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 5
#define CUDNN_PATCHLEVEL 0
```

I'll add that I have installed and working in my system both pytorch(from pip) and tensorflow(from conda) in their gpu versions. For pytorch I had to install the nightly version since they had an issue with the windows version in the latest build.

Not sure which .dll may mxnet be looking for : /

**Comment by gabrielcrds** [comment]
Hello. Commenting just to remember about this issue, since it is from March and it is still open. I'm having the exact same problem! Exact same version for CUDA etc.

**Comment by zachgk** [comment]
You should need the CUDA version to match exactly. So, 10.0 for mxnet-cu100 or 10.1 for mxnet-cu101.

**Comment by commanderka** [comment]
Same problem with mxnet-cu100 here. Cuda 10.0 is installed and I get the same error message. Please fix!

**Comment by SyedMuhammadAli** [comment]
I have the same issue. Anyone found a fix for this yet?
