### ISSUE TITLE
mx.nd.Custom conflicts with memory management

### ISSUE THREAD

**Issue by YutingZhang** [apache/incubator-mxnet#14522]
When training/running a large neural network with CustomOP, mxnet can get stuck. My speculation is that if memory management (e.g., releasing/reallocating GPU memory, raising an "out of memory error") is needed while running CustomOP, mxnet can get stuck. 

A minimum piece code to show that CustomOP can deadlock with memory management ("out-of-memory in this case"):
As expected, main(1) should work. 
main(100) should give "out of GPU memory" error. However, it just got stuck.

The real-world problem I met is not just about inability to give an "out of memory" error. It seems MxNet can release/reallocate memory dynamically, but this probably also deadlock with CustomOP, so my program, which could fit into GPU memory, can also get stuck

```python
import mxnet as mx


class MyMulMax(mx.operator.CustomOp):

    def __init__(self):
        super().__init__()

    def forward(self, is_train, req, in_data, out_data, aux):
        a, b = in_data[0:2]
        c = mx.nd.batch_dot(a, b)
        d = mx.nd.max(c, axis=-1, keepdims=True)
        self.assign(out_data[0], req[0], d)

    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        self.assign(in_grad[0], req[0], 0)
        self.assign(in_grad[1], req[1], 0)


@mx.operator.register("MyMulMax")
class MyMulMaxProp(mx.operator.CustomOpProp):

    def __init__(self):
        super().__init__()

    def list_arguments(self):
        return ['a', 'b']

    def list_outputs(self):
        return ['d']

    def infer_shape(self, in_shape):
        return in_shape, [list(in_shape[0][:-1] + [1])]

    def create_operator(self, ctx, shapes, dtypes):
        return MyMulMax()


def main(n):
    with mx.Context(mx.gpu(0)):
        a = mx.nd.random.uniform(shape=(n, 6000, 1))
        b = mx.nd.random.uniform(shape=(n, 1, 7000))
        d = mx.nd.Custom(a, b, op_type="MyMulMax")
        d_np = d.asnumpy()


if __name__ == "__main__":
    main(1)
    print("DONE -- 1")
    main(100)
    print("DONE -- 2")
```

Tested with nightly build of mxnet-cu90mkl with Python3.6

**Comment by YutingZhang** [comment]
@arcadiaphy @wkcn @anirudh2290 Interested in looking into this?

**Comment by wkcn** [comment]
Does it reproduce the bug in old version of MXNet?

**Comment by YutingZhang** [comment]
@wkcn "the bug in old version": Do you mean the deadlock in subprocess? I thought https://github.com/apache/incubator-mxnet/pull/14451 solved this problem (I have not tried it out myself).

This thread is about a different problem. It happens in the main process on a single GPU.

**Comment by wkcn** [comment]
I mean that does this issue exists before the PR https://github.com/apache/incubator-mxnet/pull/14363 ?

**Comment by wkcn** [comment]
reproduce the bug in CPU environment, it get stuck too.

**Comment by wkcn** [comment]
I see. In `python/mxnet/ndarray/ndarray.py', the function `def copyto(self, other):` calls `_internal._copyto(self, out=other)`, which gets stuck.

**Comment by YutingZhang** [comment]
> I mean that does this issue exist before the PR #14363 ?

Both before an after. I believe it should be a different issue.

**Comment by arcadiaphy** [comment]
```
MXNET_ENGINE_TYPE=ThreadedEngine gdb python -ex 'b src/storage/pooled_storage_manager.h:145' -ex 'r reproduce.py'
```

![image](https://user-images.githubusercontent.com/4437140/55067902-86ab7200-50bb-11e9-91d7-9a4bc1f74778.png)


Pretty interesting bug, seems like `cuda out of memory` cannot be triggered in custom op.

**Comment by wkcn** [comment]
OOM on CPU gets stuck too.

**Comment by arcadiaphy** [comment]
@wkcn I think it's not related to OOM, looks more like LOG(FATAL) gets stuck.

**Comment by YutingZhang** [comment]
@arcadiaphy if LOG(FATAL) gets stuck, then there might be more stuff that can get stuck, which are harder to figure out.

**Comment by anirudh2290** [comment]
I think worth trying would be checking if cudaGetErrorString is not called does it still get stuck. Since custom op uses its own custom threads it may not handle exceptions very well but still std::terminate should be called for unhandled exception. I am surprised that its not happening here for the unhandled exception.

**Comment by larroy** [comment]
Hi

I'm investigating this one. With the provided example I believe the cause of the error is the following at least in CPU context (changing gpu to cpu context in the example above).

```
I believe the current example crashes in Gemm due to an integer overflow in GEMM in the following code in dot_engine-inl.h

   
    for (int i = 0; i < batch_count; ++i) {
      gemm(stream, transa, transb, m, n, k, alpha,
           A + i * m * k, lda, B + i * k * n, ldb,
           beta, C + i * m * n, ldc);
    }

When having a gemm with dimension 6000 * 7000 * 100 which is > 2^32 we have an overflow which leads to the crash.
 I would suggest checking matrix dimensions for overflow before dispatching to GEMM.
```

**Comment by arcadiaphy** [comment]
@anirudh2290 @wkcn @YutingZhang Finally figure out the reason:

Normally, when a exception is thrown in spawn thread, it should be caught in `std::exception_ptr` and re-thrown in main thread to ensure proper except handling and avoid `std::terminate`. This mechanism is introduced in #9681 to handle exceptions in operator.

But there are still two problems in the except handling of custom op:

1. The exception thrown in custom thread cannot be caught in main thread, causing program crash.
2. When exception happens in custom op, it will be caught, and re-throw in sync function `WaitForVar`. But the `WaitForVar` is deadlocked because the whole operation `CustomOperation` is skipped
https://github.com/apache/incubator-mxnet/blob/master/src/operator/custom/custom-inl.h#L128, making the write dependency of waiting ndarray not completed forever. By adding `c.wait_to_read()`, the exception is forced to be re-thrown, but the program still crashes due to Problem 1.

```
import mxnet as mx


class MyMulMax(mx.operator.CustomOp):
    def __init__(self):
        super(MyMulMax, self).__init__()

    def forward(self, is_train, req, in_data, out_data, aux):
        a, b = in_data[0:2]
        c = mx.nd.batch_dot(a, b)
        # force re-throw exception, program still crash due to uncaught exception
        # c.wait_to_read()
        d = mx.nd.max(c, axis=-1, keepdims=True)
        self.assign(out_data[0], req[0], d)

    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        self.assign(in_grad[0], req[0], 0)
        self.assign(in_grad[1], req[1], 0)


@mx.operator.register("MyMulMax")
class MyMulMaxProp(mx.operator.CustomOpProp):
    def __init__(self):
        super(MyMulMaxProp, self).__init__()

    def list_arguments(self):
        return ['a', 'b']

    def list_outputs(self):
        return ['d']

    def infer_shape(self, in_shape):
        return in_shape, [list(in_shape[0][:-1] + [1])]

    def create_operator(self, ctx, shapes, dtypes):
        return MyMulMax()


def custom(n):
    with mx.Context(mx.gpu(0)):
        a = mx.nd.random.uniform(shape=(n, 6000, 1))
        b = mx.nd.random.uniform(shape=(n, 1, 7000))
        d = mx.nd.Custom(a, b, op_type="MyMulMax")
        d.wait_to_read()


def direct(n):
    with mx.Context(mx.gpu(0)):
        a = mx.nd.random.uniform(shape=(n, 6000, 1))
        b = mx.nd.random.uniform(shape=(n, 1, 7000))
        c = mx.nd.batch_dot(a, b)
        d = mx.nd.max(c, axis=-1, keepdims=True)
        # deadlock due to skipped CustomOperation function
        d.wait_to_read()


if __name__ == "__main__":
    custom(100)
```

**Comment by arcadiaphy** [comment]
@wkcn @anirudh2290 Like what I've mentioned before, adding on_complete callback in CustomOperation is not a good design, since the calling may be skipped when exception happens:
https://github.com/apache/incubator-mxnet/blob/master/src/operator/custom/custom-inl.h#L128

Any good idea on how to avoid it?

**Comment by larroy** [comment]
In CPU I see a crash in sgemm. I don't see the relation with exceptions in CPU.

```
(lldb) r repro2.py
Process 6491 launched: '/Users/pllarroy/devel/mxnet/py3_venv/bin/python' (x86_64)
Process 6491 stopped
* thread #4, stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffff326c4800)
    frame #0: 0x0000000113fb3b4d libopenblasp-r0.3.5.dylib`sgemm_beta_HASWELL + 107
libopenblasp-r0.3.5.dylib`sgemm_beta_HASWELL:
->  0x113fb3b4d <+107>: movl   $0x0, (%rdx,%rax,4)
    0x113fb3b54 <+114>: incq   %rax
    0x113fb3b57 <+117>: jmp    0x113fb3b42               ; <+96>
    0x113fb3b59 <+119>: decq   %rsi
  thread #10, stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffff326c6c78)
    frame #0: 0x0000000113fb3b4d libopenblasp-r0.3.5.dylib`sgemm_beta_HASWELL + 107
libopenblasp-r0.3.5.dylib`sgemm_beta_HASWELL:
->  0x113fb3b4d <+107>: movl   $0x0, (%rdx,%rax,4)
    0x113fb3b54 <+114>: incq   %rax
    0x113fb3b57 <+117>: jmp    0x113fb3b42               ; <+96>
    0x113fb3b59 <+119>: decq   %rsi
  thread #11, stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffff326c90ec)
    frame #0: 0x0000000113fb3b4d libopenblasp-r0.3.5.dylib`sgemm_beta_HASWELL + 107
libopenblasp-r0.3.5.dylib`sgemm_beta_HASWELL:
->  0x113fb3b4d <+107>: movl   $0x0, (%rdx,%rax,4)
    0x113fb3b54 <+114>: incq   %rax
    0x113fb3b57 <+117>: jmp    0x113fb3b42               ; <+96>
    0x113fb3b59 <+119>: decq   %rsi
Target 0: (python) stopped.
(lldb)
```

**Comment by larroy** [comment]
In GPU this is the segmentation fault that I get. Are we talking about the same problem?

```
Thread 297 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffea9371700 (LWP 3786)]
0x00007fff31cdb240 in sgemm_beta_HASWELL () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
(gdb) bt 3
#0  0x00007fff31cdb240 in sgemm_beta_HASWELL () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
#1  0x00007fff30821d95 in ?? () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
#2  0x00007fff30969b52 in ?? () from /usr/lib/x86_64-linux-gnu/libopenblas.so.0
(More stack frames follow...)
(gdb)
```

**Comment by larroy** [comment]
I talked to @anirudh2290 and I understand we are talking about two separate issues here:

* Exception handling in custom ops
* The integer overflow problem that I described.

@arcadiaphy do you plan to send a fix for the handling of exceptions in custom ops?

I can work on the integer overflow problem.

**Comment by larroy** [comment]
This repro in imperative mode isolates from the exception handling problem in custom ops:

```
import mxnet as mx
n = 100
a = mx.nd.random.uniform(shape=(n, 6000, 1))
b = mx.nd.random.uniform(shape=(n, 1, 7000))
c = mx.nd.batch_dot(a, b)
c.wait_to_read()
print(c.shape)
```

**Comment by arcadiaphy** [comment]
@larroy Yes, two different issues here.

Reproduced the gemm bug too, but I'm focusing on the exception handling issue.

**Comment by anirudh2290** [comment]
Thanks @arcadiaphy ! Nice work! We can do this incrementally. Would you be willing to start with a PR for 1 ?

> 1. The exception thrown in custom thread cannot be caught in main thread, causing program crash.

**Comment by arcadiaphy** [comment]
@anirudh2290 Have started a PR for 1, but the really tricky one is 2.

**Comment by wkcn** [comment]
Great! Thanks fo your analysis!
I will read the comments and review the PR : )

**Comment by larroy** [comment]
nice!  I will work on a fix for tensor shapes in the Blas Engine, unless somebody else has a strong desire to help there.

**Comment by larroy** [comment]
@mxnet-label-bot [C++, Backend, Bug, Exception Handling]
