### ISSUE TITLE
Flaky backwards compatibility with 1.2.1 for lenet_gluon_save_params_api

### ISSUE THREAD

**Issue by lebeg** [apache/incubator-mxnet#14524]
## Description

Several failures for [backwards-compatibility-checker](http://jenkins.mxnet-ci.amazon-ml.com/job/restricted-backwards-compatibility-checker/) with different error values:

* http://jenkins.mxnet-ci.amazon-ml.com/job/restricted-backwards-compatibility-checker/420

```
INFO:root:Fetching files for MXNet version : 1.2.1 and model lenet_gluon_save_params_api
Traceback (most recent call last):
  File "model_backwards_compat_inference.py", line 135, in <module>
    test_lenet_gluon_load_params_api()
  File "model_backwards_compat_inference.py", line 72, in test_lenet_gluon_load_params_api
    assert_almost_equal(old_inference_results.asnumpy(), output.asnumpy(), rtol=rtol_default, atol=atol_default)
  File "/work/mxnet/python/mxnet/test_utils.py", line 495, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 9591.478516 exceeds tolerance rtol=0.000010, atol=0.000010.  Location of maximum error:(17, 0), a=-0.441335, b=-0.315189
 a: array([[-0.40397233, -0.19248717],
       [-0.34466907, -0.15791757],
       [-0.39881065, -0.2201823 ],...
 b: array([[-0.4039724 , -0.19248715],
       [-0.3446689 , -0.15791774],
       [-0.39881057, -0.22018239],...
```

* http://jenkins.mxnet-ci.amazon-ml.com/job/restricted-backwards-compatibility-checker/436

```
INFO:root:Fetching files for MXNet version : 1.2.1 and model lenet_gluon_save_params_api
Traceback (most recent call last):
  File "model_backwards_compat_inference.py", line 135, in <module>
    test_lenet_gluon_load_params_api()
  File "model_backwards_compat_inference.py", line 72, in test_lenet_gluon_load_params_api
    assert_almost_equal(old_inference_results.asnumpy(), output.asnumpy(), rtol=rtol_default, atol=atol_default)
  File "/work/mxnet/python/mxnet/test_utils.py", line 495, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 2926.058350 exceeds tolerance rtol=0.000010, atol=0.000010.  Location of maximum error:(16, 0), a=-0.378972, b=-0.339770
 a: array([[-0.40397233, -0.19248717],
       [-0.34466907, -0.15791757],
       [-0.39881065, -0.2201823 ],...
 b: array([[-0.4039724 , -0.19248715],
       [-0.3446689 , -0.15791774],
       [-0.39881057, -0.22018239],...
```

## Related

* https://github.com/apache/incubator-mxnet/issues/14234 Backwards compatibility out of bounds for 1.2.1

**Comment by vdantu** [comment]
@mxnet-label-bot add [ci, flaky, gluon]
