### ISSUE TITLE
Flaky: test_subgraph.test_pos_conv_bn_sum_relu

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#14552]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14545/2/pipeline#step-710-log-899

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14543/1/pipeline/241#step-703-log-893

======================================================================

FAIL: test_subgraph.test_pos_conv_bn_sum_relu

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/test_subgraph.py", line 578, in test_pos_conv_bn_sum_relu

    check_fusion(net, data_shape, attrs)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/test_subgraph.py", line 190, in check_fusion

    assert_almost_equal(exe.outputs[i].asnumpy(), exe_sg.outputs[i].asnumpy(), rtol=1e-3, atol=1e-3)

  File "/work/mxnet/python/mxnet/test_utils.py", line 495, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 2.103513 exceeds tolerance rtol=0.001000, atol=0.001000.  Location of maximum error:(22, 19, 13, 45), a=0.029479, b=0.031649

 a: array([[[[  398.53668  ,   314.83194  ,    -0.       , ...,

           1158.4216   ,   433.63675  ,    -0.       ],

         [  121.856995 ,   131.27039  ,    -0.       , ...,...

 b: array([[[[  398.53677  ,   314.83197  ,     0.       , ...,

           1158.4215   ,   433.63693  ,     0.       ],

         [  121.85688  ,   131.27037  ,     0.       , ...,...

-------------------- >> begin captured logging << --------------------

**Comment by vdantu** [comment]
@mxnet-label-bot add [Test, Flaky]

**Comment by TaoLv** [comment]
Hi @marcoabreu , is it possible to check the failure history of a certain case? Just wondering if this case is caused by some recent changes or has been there for a while.

**Comment by TaoLv** [comment]
Seems there are actually two failing cases:
test_subgraph.test_pos_conv_bn_sum_relu
test_subgraph.test_pos_conv_bn_relu
