### ISSUE TITLE
[MKL-DNN] Test failures in Python 2

### ISSUE THREAD

**Issue by perdasilva** [apache/incubator-mxnet#14675]
## Description

When executing the MKL-DNN tests against the latest mxnet-mkl pip package using python 2, I get the following errors:

```
======================================================================
ERROR: test_mkldnn.test_mkldnn_ndarray_slice
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/incubator-mxnet/tests/python/mkl/test_mkldnn.py", line 74, in test_mkldnn_ndarray_slice
    assert_almost_equal(y[0].asnumpy()[0, 0, 0], 0.3376348)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/test_utils.py", line 493, in assert_almost_equal
    % (rel, rtol, atol, str(index), a[index], b[index]),
TypeError: 'float' object has no attribute '__getitem__'

======================================================================
ERROR: test_mkldnn.test_mkldnn_engine_threading
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/incubator-mxnet/tests/python/mkl/test_mkldnn.py", line 98, in test_mkldnn_engine_threading
    assert_almost_equal(y[0, 0, 0, 0], 0.016711406)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/test_utils.py", line 493, in assert_almost_equal
    % (rel, rtol, atol, str(index), a[index], b[index]),
TypeError: 'float' object has no attribute '__getitem__'

----------------------------------------------------------------------
Ran 55 tests in 401.237s
```
## To reproduce

$ docker run -ti ubuntu:16.04 /bin/bash
Then in the container,

$ apt update && apt install -y python python-pip git
$ pip install mxnet-mkl==1.5.0b20190410 nose scipy
$ git clone https://github.com/apache/incubator-mxnet.git
$ nosetests incubator-mxnet/tests/python/mkl

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.12')
('Compiler     :', 'GCC 5.4.0 20160609')
('Build        :', ('default', 'Nov 12 2018 14:36:49'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '8.1.1')
('Directory    :', '/usr/lib/python2.7/dist-packages/pip')
----------MXNet Info-----------
('Version      :', '1.5.0')
('Directory    :', '/usr/local/lib/python2.7/dist-packages/mxnet')
('Commit Hash   :', 'b68f18c97d08193cded0630a2e0a04673e4a0410')
----------System Info----------
('Platform     :', 'Linux-4.9.125-linuxkit-x86_64-with-Ubuntu-16.04-xenial')
('system       :', 'Linux')
('node         :', '17247cd9de80')
('release      :', '4.9.125-linuxkit')
('version      :', '#1 SMP Fri Sep 7 08:20:28 UTC 2018')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 142
Model name:            Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
Stepping:              9
CPU MHz:               2500.000
BogoMIPS:              4768.85
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch kaiser fsgsbase bmi1 hle avx2 bmi2 erms rtm xsaveopt arat
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0536 sec, LOAD: 1.2237 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0585 sec, LOAD: 0.8487 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0762 sec, LOAD: 1.2741 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0505 sec, LOAD: 0.2754 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0796 sec, LOAD: 1.0294 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0741 sec, LOAD: 0.9458 sec.
```

**Comment by pengzhao-intel** [comment]
@TaoLv

**Comment by TaoLv** [comment]
I would say that it's a strange behavior of nosetests for me. We noticed that before. The test cases look problematic but they're not caught by CI. @juliusshufan please add more information.

**Comment by perdasilva** [comment]
As far as I could tell, CI isn't checking MKL against python 2 (or at least not running that specific suite with python 2) - @jlcontreras has kindly volunteered to add this step to CI. However, there will need to be some coordination with the fix, or the new step will fail =S

**Comment by perdasilva** [comment]
As far as I could tell, CI isn't checking MKL against python 2 (or at least not running that specific suite with python 2) - @jlcontreras has kindly volunteered to add this step to CI. However, there will need to be some coordination with the fix, or the new step will fail =S

**Comment by pengzhao-intel** [comment]
Any update in this case. BTW, the python2 will be deprecated :)
Closing this now and feel free to reopen if the issue still exists.
