### ISSUE TITLE
[Flaky] Flaky test 

### ISSUE THREAD

**Issue by stsukrov** [apache/incubator-mxnet#14718]
```
======================================================================

FAIL: test_random_size_crop (test_image.TestImage)

----------------------------------------------------------------------

Traceback (most recent call last):

File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 177, in test_new

orig_test(*args, **kwargs)

File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_image.py", line 368, in test_random_size_crop

assert ratio[0] <= float(new_w)/new_h <= ratio[1]

AssertionError:

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1948053179 to reproduce.

--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```
As seen: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/master/531/pipeline/115

**Comment by stsukrov** [comment]
@mxnet-label-bot add [Flaky, Test]

**Comment by anirudhacharya** [comment]
failure log - http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/PR-14503/runs/16/nodes/282/log/?start=0

**Comment by arcadiaphy** [comment]
another one:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-cpu/detail/PR-14894/1/pipeline

**Comment by eric-haibin-lin** [comment]
Another one: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14683/5/pipeline

**Comment by perdasilva** [comment]
Another one: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/master/659/pipeline#step-770-log-1733
