### ISSUE TITLE
mxnet.base.MXNetError: [10:30:40] src/io/iter_image_det_recordio.cc:326: ImageDetRecordIOParser: label_pad_width: 300 smaller than estimated width: 338

### ISSUE THREAD

**Issue by QJXX** [apache/incubator-mxnet#14715]
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/home/zsl/qjx/mxnet-dssd/train/train_net.py", line 188, in train_net
    label_pad_width=label_pad_width, path_imglist=train_list, **cfg.train)
  File "/home/zsl/qjx/mxnet-dssd/dataset/iterator.py", line 77, in __init__
    **kwargs)
  File "/home/zsl/Programs/anaconda2/lib/python2.7/site-packages/mxnet/io.py", line 886, in creator
    ctypes.byref(iter_handle)))
  File "/home/zsl/Programs/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:30:40] src/io/iter_image_det_recordio.cc:326: ImageDetRecordIOParser: label_pad_width: 300 smaller than estimated width: 338

**Comment by ZhennanQin** [comment]
I guess you're running symbolic ssd. Please add `--label-width=338` as script argument.
