### ISSUE TITLE
Flaky test_loss.test_poisson_nllloss failed CI

### ISSUE THREAD

**Issue by zachgk** [apache/incubator-mxnet#14723]
test_loss.test_poisson_nllloss failed the CI at http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14687/3/pipeline/ on unrelated PR https://github.com/apache/incubator-mxnet/pull/14687.

See output below:
```
======================================================================

FAIL: test_loss.test_poisson_nllloss

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/test_loss.py", line 396, in test_poisson_nllloss

    assert_almost_equal(np_loss_no_logits, loss_no_logits.asscalar())

  File "/work/mxnet/python/mxnet/test_utils.py", line 495, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 4.257397 exceeds tolerance rtol=0.000010, atol=0.000000.  Location of maximum error:(), a=0.000467, b=0.000467

 a: 0.00046688318

 b: 0.00046690306
```

**Comment by zachgk** [comment]
@mxnet-label-bot add [Test, Flaky, Python]
