### ISSUE TITLE
"terminate called without an active exception"

### ISSUE THREAD

**Issue by c00424162** [apache/incubator-mxnet#14775]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description
(Brief description of the problem in no more than 2 sentences.)
I run this code using launch.py in two contains , they communicate with ssh without password. When the code was  finished  and the result had been printed, the terminate reported the error : "terminate called without an active exception"
## Environment info (Required)

```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):

MXNet commit hash:
(Paste the output of `git rev-parse HEAD` here.)

Build config:
(Paste the content of config.mk, or the build command.)

## Error Message:
Epoch 0: Test_acc 0.463200
Epoch 0: Test_acc 0.470700
Epoch 1: Test_acc 0.619300
Epoch 1: Test_acc 0.614000
Epoch 2: Test_acc 0.692300
Epoch 2: Test_acc 0.690300
Epoch 3: Test_acc 0.699900
Epoch 3: Test_acc 0.705400
Epoch 4: Test_acc 0.727400
terminate called without an active exception
Epoch 4: Test_acc 0.725900
terminate called without an active exception
bash: line 1:   123 Aborted                 (core dumped) python /cgl/cifar10_dist.py
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dmlc_tracker/ssh.py", line 62, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 169.254.30.2 -p 22 'export DMLC_PS_ROOT_URI=169.254.30.2; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9091; export DMLC_NUM_WORKER=2; export DMLC_NODE_HOST=169.254.30.2; export DMLC_NUM_SERVER=2; cd /cgl/; python /cgl/cifar10_dist.py'' returned non-zero exit status 134

bash: line 1:    60 Aborted                 (core dumped) python /cgl/cifar10_dist.py
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dmlc_tracker/ssh.py", line 62, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 169.254.30.3 -p 22 'export DMLC_PS_ROOT_URI=169.254.30.2; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9091; export DMLC_NUM_WORKER=2; export DMLC_NODE_HOST=169.254.30.3; export DMLC_NUM_SERVER=2; cd /cgl/; python /cgl/cifar10_dist.py'' returned non-zero exit status 134

## Minimum reproducible example
(If you are using your own code, please provide a short script that reproduces the error. Otherwise, please provide link to the existing example.)

## Steps to reproduce
(Paste the commands you ran that produced the error.)
1.python /incubator-mxnet/tools/launch.py -n 2 -s 2 -H hosts --sync-dst-dir /cgl/ --launcher ssh "python /cgl/cifar10_dist.py"
2.  How to solve this problem？
## What have you tried to solve it?

1.
2.

**Comment by Adnios** [comment]
hello. I have met the same problem in Mxnet-1.4.1. Do you have solved this problem.
