### ISSUE TITLE
Flaky test: test_random_size_crop

### ISSUE THREAD

**Issue by anirudhacharya** [apache/incubator-mxnet#14803]
logs - http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/PR-14503/runs/16/nodes/282/log/?start=0

```bash
======================================================================

FAIL: test_random_size_crop (test_image.TestImage)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/work/mxnet/tests/python/unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_image.py", line 368, in test_random_size_crop

    assert ratio[0] <= float(new_w)/new_h <= ratio[1]

AssertionError: 

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1781948197 to reproduce.

--------------------- >> end captured logging << ---------------------

```

**Comment by anirudhacharya** [comment]
closing as a duplicate of this - https://github.com/apache/incubator-mxnet/issues/14718
