### ISSUE TITLE
Flaky test test_custom_op_exc

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#14835]
A PR that just changed build.py, got a failure on this test:

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-14815/1/pipeline/

**Comment by larroy** [comment]
@mxnet-label-bot add [Flaky, Test]

**Comment by wkcn** [comment]
```
Error in CustomOp.forward: Traceback (most recent call last):

  File "/work/mxnet/python/mxnet/operator.py", line 987, in forward_entry

    aux=tensors[4])

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5453, in forward

    fun_forward(in_data, out_data)

  File "/work/mxnet/tests/python/unittest/test_operator.py", line 5516, in f

    out_data[0][:] = mx.nd.dot(in_data[0], in_data[1])

  File "<string>", line 92, in dot

  File "/work/mxnet/python/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke

    ctypes.byref(out_stypes)))

  File "/work/mxnet/python/mxnet/base.py", line 254, in check_call

    raise MXNetError(py_str(_LIB.MXGetLastError()))

mxnet.base.MXNetError: [17:42:04] src/operator/tensor/./dot-inl.h:1261: Check failed: L[!Ta].Size() == R[Tb].Size() (2 vs. 1) : dot shape error: [4,2] X [1,4]
```

**Comment by TaoLv** [comment]
I think @arcadiaphy is working on this. Do you have any finding?

**Comment by arcadiaphy** [comment]
I'm stuck in reproducing the error. The bug in spawned process is hard to track, the only thing I've got is the non-zero exitcode.

I'll rewrite the test to bypass this error temporarily.
