### ISSUE TITLE
Invalid output shapes

### ISSUE THREAD

**Issue by androuino** [apache/incubator-mxnet#14913]
Hi @lanking520. After pulling your changes for the fix (#14804) of my issue, I tried it right away but am having now a strange error using the example of **ObjectDetection.java** class but I made some alteration to it to meet my requirements. Now it looks like this:
https://gist.github.com/androuino/7808b6fdf05e3122a03f35c63d3a5f89

I followed the step by step tutorial here https://github.com/apache/incubator-mxnet/tree/master/scala-package/mxnet-demo/java-demo for running the demo.

and this is the error am having:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation (NOP) logger implementation 
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details. 
[16:52:43] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.0. Attempting to upgrade... 
[16:52:43] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded! 
Exception in thread "main" java.lang.IllegalStateException: Invalid output shapes, expected: Vector(DataDesc[data,(1,3,512,512),float32,NCHW]).length, actual: ArrayBuffer((yolov30_slice_axis1_output,(1,100,1)), (yolov30_slice_axis2_output,(1,100,1)), (yolov30_slice_axis3_output,(1,100,4))).length. at org.apache.mxnet.infer.ObjectDetector.getImageClassifier(ObjectDetector.scala:202) at org.apache.mxnet.infer.ObjectDetector.<init>(ObjectDetector.scala:52) at org.apache.mxnet.infer.javaapi.ObjectDetector.<init>(ObjectDetector.scala:58) at mxnet.ObjectDetection.runObjectDetectionSingle(ObjectDetection.java:77) at mxnet.ObjectDetection.main(ObjectDetection.java:86)
```

The image I was used to test is **512x512** in size and the model that I've trained is also set to **512**.
This is my **train_yolo3.py** script: https://gist.github.com/androuino/af5212923534a204b155c01b3bacb7f1
Then run the script with this command **python train.py --gpus 0 --batch-size 2 --data-shape 512**

"_If you want the files that am using including the test image, I could email it you. I couldn't upload it publicly so I preferred to email it directly to you_".

Thanks for any enlightenment that you could give me with this error or at least tell me if I did something or missed something with the code: https://gist.github.com/androuino/7808b6fdf05e3122a03f35c63d3a5f89 .

**Comment by lanking520** [comment]
Have you seen the same problem with Predictor API? 
https://github.com/apache/incubator-mxnet/issues/14756#issuecomment-486769617
Try with this piece of code

**Comment by androuino** [comment]
Thanks for the response. It's working fine with **Predictor API**. I have an arrays of output **0's** and **1's** with length **512**. My question is, how would I apply the fix to Object Detection?

**Comment by androuino** [comment]
@lanking520 could you give me an example of **post processing tookit**? Thanks.

**Comment by lanking520** [comment]
> @lanking520 could you please give me an example of **post processing tookit**? Thanks.

I mean you may need to resolve your personal use cases. The predictor's result should bring you some bounding box probabilities and coordinates of the box in the image. To assist you better, I would like to know what does it mean to the output. If it is the same model, I remember there are three NDArrays output. What are they representing?

**Comment by androuino** [comment]
Thanks for the reply @lanking520, yes there are 3 outputs of NDArrays, actually yesterday, I've tried this in my code:
https://gist.github.com/androuino/f2250d2adae537ef2df1b8cea2190d5e

and it works fine with an output of:
```
[09:36:31] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v1.4.0. Attempting to upgrade...
[09:36:31] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
[09:36:34] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Predict with Float input
Probability : -1.0 Class : wheel
Predict with NDArray
Probability : -1.0 Class : wheel
```

Am thinking that maybe part of the code I used, I could pull the coordinates of the box in the image.

Yes there are 3 NDArrays output:
https://gist.github.com/androuino/cb09c22d834e7f06131f372e7dc395df

Thanks.
