### ISSUE TITLE
libiomp5.so not found

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#14999]
Can't load libmxnet, libiomp5.so not found.

libmxnet is linked dynamically with libomp

```
(py3_venv) piotr@ip-172-31-63-171:0:~/mxnet_master (master)+$ ldd lib/libmxnet.so | grep omp
        libiomp5.so => not found

```

System:  Ubuntu 18.04

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              72
On-line CPU(s) list: 0-71
Thread(s) per core:  2
Core(s) per socket:  18
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
Stepping:            4
CPU MHz:             1206.897
BogoMIPS:            6000.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0-17,36-53
NUMA node1 CPU(s):   18-35,54-71
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke
----------Python Info----------
Version      : 3.6.7
Compiler     : GCC 8.2.0
Build        : ('default', 'Oct 22 2018 11:32:17')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 19.1.1
Directory    : /home/piotr/mxnet_master/py3_venv/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Linux-4.15.0-1035-aws-x86_64-with-Ubuntu-18.04-bionic
system       : Linux
node         : ip-172-31-63-171
release      : 4.15.0-1035-aws
version      : #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0018 sec, LOAD: 0.6058 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0004 sec, LOAD: 0.1730 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0003 sec, LOAD: 0.0896 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0003 sec, LOAD: 0.0640 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0005 sec, LOAD: 0.1418 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0003 sec, LOAD: 0.0490 sec.
```

```
(py3_venv) piotr@ip-172-31-63-171:130:~/mxnet_master (master)+$ python
Python 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as ms
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/piotr/mxnet_master/python/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/piotr/mxnet_master/python/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/piotr/mxnet_master/python/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/home/piotr/mxnet_master/python/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiomp5.so: cannot open shared object file: No such file or directory
```

CMake configuration:
```
--- # CMake configuration
USE_CUDA: "OFF" # Build with CUDA support
USE_OLDCMAKECUDA: "OFF" # Build with old cmake cuda
USE_NCCL: "OFF" # Use NVidia NCCL with CUDA
USE_OPENCV: "ON" # Build with OpenCV support
USE_OPENMP: "ON" # Build with Openmp support
USE_CUDNN: "ON" # Build with cudnn support) # one could set CUDNN_ROOT for search path
USE_SSE: "ON" # Build with x86 SSE instruction support IF NOT ARM
USE_F16C: "ON" # Build with x86 F16C instruction support) # autodetects support if "ON"
USE_LAPACK: "ON" # Build with lapack support
USE_MKL_IF_AVAILABLE: "ON" # Use MKL if found
USE_MKLML_MKL: "ON" # Use MKLDNN variant of MKL (if MKL found) IF USE_MKL_IF_AVAILABLE AND (NOT APPLE)
USE_MKLDNN: "ON" # Use MKLDNN variant of MKL (if MKL found) IF USE_MKL_IF_AVAILABLE AND (NOT APPLE)
USE_OPERATOR_TUNING: "ON" # Enable auto-tuning of operators IF NOT MSVC
USE_GPERFTOOLS: "ON" # Build with GPerfTools support (if found)
USE_JEMALLOC: "ON" # Build with Jemalloc support
USE_PROFILER: "ON" # Build with Profiler support
USE_DIST_KVSTORE: "OFF" # Build with DIST_KVSTORE support
USE_PLUGINS_WARPCTC: "OFF" # Use WARPCTC Plugins
USE_PLUGIN_CAFFE: "OFF" # Use Caffe Plugin
USE_CPP_PACKAGE: "OFF" # Build C++ Package
USE_MXNET_LIB_NAMING: "ON" # Use MXNet library naming conventions.
USE_GPROF: "OFF" # Compile with gprof (profiling) flag
USE_CXX14_IF_AVAILABLE: "OFF" # Build with C++14 if the compiler supports it
USE_VTUNE: "OFF" # Enable use of Intel Amplifier XE (VTune)) # one could set VTUNE_ROOT for search path
ENABLE_CUDA_RTC: "ON" # Build with CUDA runtime compilation support
BUILD_CPP_EXAMPLES: "ON" # Build cpp examples
INSTALL_EXAMPLES: "OFF" # Install the example source files.
USE_SIGNAL_HANDLER: "ON" # Print stack traces on segfaults.
USE_TENSORRT: "OFF" # Enable infeference optimization with TensorRT.
USE_ASAN: "OFF" # Enable Clang/GCC ASAN sanitizers.
ENABLE_TESTCOVERAGE: "OFF" # Enable compilation with test coverage metric output
CMAKE_BUILD_TYPE: "Debug"
CMAKE_CUDA_COMPILER_LAUNCHER: "ccache"
CMAKE_C_COMPILER_LAUNCHER: "ccache"
CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
```

**Comment by vdantu** [comment]
@mxnet-label-bot add [build]

**Comment by pengzhao-intel** [comment]
@yinghu5 @NeoZhangJianyu could you help to take a look?

**Comment by pengzhao-intel** [comment]
cc @TaoLv

**Comment by yinghu5** [comment]
Hi Larroy,  is the libmxnet.lib build from latest source code +  cmake, right?  if it is based on Intel mkl-dnn,  then  I suppose there are some steps to copy all related dll into LD search environments like LD_LIBRARY_PATH or in the lib folder. 

What is the whole output   if run  ldd lib/libmxnet.so ? 

Here is one on my machine. 
ls lib  (may i had copied then manually) 
libiomp5.so   libmkldnn.so.0       libmklml_gnu.so    libmxnet.a
libmkldnn.so  libmkldnn.so.0.13.0  libmklml_intel.so  libmxnet.so

yhu5@dell-r640:~/MXNET/incubator-mxnet$ ldd lib/libmxnet.so
        linux-vdso.so.1 (0x00007ffe89bbb000)
        libmklml_intel.so => /home/yhu5/MXNET/incubator-mxnet/lib/libmklml_intel                                                                                                                                                             .so (0x00007fb76e2ff000)
        libiomp5.so => /home/yhu5/MXNET/incubator-mxnet/lib/libiomp5.so (0x00007                                                                                                                                                             fb76df5b000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fb76dd53000)
        libmkldnn.so.0 => /home/yhu5/MXNET/incubator-mxnet/lib/libmkldnn.so.0 (0                                                                                                                                                             x00007fb76d62a000)
        libopencv_core.so.2.4 => not found
        libopencv_highgui.so.2.4 => not found
        libopencv_imgproc.so.2.4 => not found
        liblapack.so.3 => /usr/lib/liblapack.so.3 (0x00007fb76ce46000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb76c                                                                                                                                                             abd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb76c71f000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb76c507000                                                                                                                                                             )
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb76c2e                                                                                                                                                             8000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb76bef7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fb77aabe000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb76bcf3000)
        libblas.so.3 => /usr/lib/libblas.so.3 (0x00007fb76bab5000)
        libatlas.so.3 => /usr/lib/libatlas.so.3 (0x00007fb76b517000)
        libgfortran.so.3 => /usr/lib/x86_64-linux-gnu/libgfortran.so.3 (0x00007f                                                                                                                                                             b76b1e6000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f                                                                                                                                                             b76afa6000)

**Comment by yinghu5** [comment]
Just check install from PIP,  all of the libraries including libiomp5.so and libmxnet.so, libmkldnn.so are in same folder. 

![mxnet](https://user-images.githubusercontent.com/43240216/58463006-a287ce80-8165-11e9-9ee9-adc18f9c2a4a.PNG)

so  please copy the libiom5md.so (and other dependency) into the lib directory.

**Comment by larroy** [comment]
Having to copy these libraries manually breaks development using the Python bindings which search for the library in predefined paths like build/ no?
