### ISSUE TITLE
[Flaky Test] test_operator.test_l2_normalization

### ISSUE THREAD

**Issue by perdasilva** [apache/incubator-mxnet#15004]
## Description

test_operator.test_l2_normalization is failing in CI. Possibly related to (#12417).

```
======================================================================
FAIL: test_operator.test_l2_normalization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\jenkins_slave\workspace\ut-python-cpu\tests\python\unittest\common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-cpu\tests\python\unittest\test_operator.py", line 3364, in test_l2_normalization
    check_l2_normalization((nbatch, nchannel, height, width), mode, dtype)
  File "C:\jenkins_slave\workspace\ut-python-cpu\tests\python\unittest\test_operator.py", line 3352, in check_l2_normalization
    check_numeric_gradient(out, [in_data], numeric_eps=1e-3, rtol=1e-2, atol=5e-3)
  File "C:\jenkins_slave\workspace\ut-python-cpu\windows_package\python\mxnet\test_utils.py", line 980, in check_numeric_gradient
    ("NUMERICAL_%s"%name, "BACKWARD_%s"%name))
  File "C:\jenkins_slave\workspace\ut-python-cpu\windows_package\python\mxnet\test_utils.py", line 503, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 2.102181 exceeds tolerance rtol=0.010000, atol=0.005000.  Location of maximum error:(0, 2, 3, 2), a=-23.500040, b=-24.015398
 NUMERICAL_data: array([[[[  1.8384606 ,  -0.1450032 ,   0.4991705 , ...,   1.023978  ,
            0.41557103,   0.16494095],
         [  0.6440282 ,   0.04217774,   0.34083053, ...,   0.79606843,...
 BACKWARD_data: array([[[[  1.8384222 ,  -0.14503051,   0.49919605, ...,   1.0241054 ,
            0.4155616 ,   0.16493562],
         [  0.6440544 ,   0.042174  ,   0.34083432, ...,   0.7960764 ,...
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1163638589 to reproduce.
--------------------- >> end captured logging << ---------------------
```

See http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-cpu/detail/master/640/pipeline for full logs.

**Comment by vdantu** [comment]
@mxnet-label-bot add [Test]
