### ISSUE TITLE
Issue in using nd.ones((3, 4), ctx=gpu()) , CUDA 10.1

### ISSUE THREAD

**Issue by kaivu1999** [apache/incubator-mxnet#15017]
## Description
Not able to use ctx=gpu() in nd.ones()

## Environment info (Required)

```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:10:27_PDT_2019
Cuda compilation tools, release 10.1, V10.1.168

```
```
x = nd.ones((3,4), ctx=gpu())
```
This leads to the following error
```
[14:03:41] src/imperative/./imperative_utils.h:90: GPU support is disabled. Compile MXNet with USE_CUDA=1 to enable GPU support.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 2421, in ones
    return _internal._ones(shape=shape, ctx=ctx, dtype=dtype, **kwargs)
  File "<string>", line 34, in _ones
  File "/home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:03:41] src/imperative/imperative.cc:79: Operator _ones is not implemented for GPU.

Stack trace returned 10 entries:
[bt] (0) /home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x23d55a) [0x7f85c9fb755a]
[bt] (1) /home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x23dbc1) [0x7f85c9fb7bc1]
[bt] (2) /home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/libmxnet.so(mxnet::Imperative::InvokeOp(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::OpReqType, std::allocator<mxnet::OpReqType> > const&, mxnet::DispatchMode, mxnet::OpStatePtr)+0x9fb) [0x7f85cc9a8abb]
[bt] (3) /home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/libmxnet.so(mxnet::Imperative::Invoke(mxnet::Context const&, nnvm::NodeAttrs const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&, std::vector<mxnet::NDArray*, std::allocator<mxnet::NDArray*> > const&)+0x38c) [0x7f85cc9a917c]
[bt] (4) /home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x2b34989) [0x7f85cc8ae989]
[bt] (5) /home/kaivalya/ntu/first/lib/python3.5/site-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x6f) [0x7f85cc8aef7f]
[bt] (6) /home/kaivalya/ntu/first/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f85e5a6fe20]
[bt] (7) /home/kaivalya/ntu/first/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x2eb) [0x7f85e5a6f88b]
[bt] (8) /home/kaivalya/ntu/first/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x49a) [0x7f85e5a6a01a]
[bt] (9) /home/kaivalya/ntu/first/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(+0x9fcb) [0x7f85e5a5dfcb]
```

Package used (Python/R/Scala/Julia):
(I'm using ...)
autopep8==1.4.4
backcall==0.1.0
certifi==2019.3.9
chardet==3.0.4
cycler==0.10.0
decorator==4.4.0
graphviz==0.8.4
idna==2.8
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.13.3
jupyter-client==5.2.4
jupyter-core==4.4.0
kiwisolver==1.1.0
matplotlib==3.0.3
mxnet==1.4.1
mxnet-cu101==1.5.0b20190516
numpy==1.14.6
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
prompt-toolkit==2.0.9
ptyprocess==0.6.0
pycodestyle==2.5.0
Pygments==2.4.0
pyparsing==2.4.0
python-dateutil==2.8.0
pyzmq==18.0.1
requests==2.22.0
six==1.12.0
tornado==6.0.2
traitlets==4.3.2
urllib3==1.25.2
wcwidth==0.1.7

I am new to MXNet and CUDA can someone help me, please?

**Comment by suyz526** [comment]
Have you installed mxnet from source?  You have probably forgotten to add some arguments to enable GPU support such as USE_CUDA=1.

**Comment by kaivu1999** [comment]
@suyz526  Are you suggeting to download form sources.
I directly used 
sudo apt-get install mxnet
sudo apt-get install mxnet-cu101

But as you know they won't work 
What do you suggest ?

**Comment by suyz526** [comment]
I have tried to install mxnet from source, or use pip. Both work in my machine.

**Comment by stu1130** [comment]
@kaivu1999 
I am using Deep Learning base ami ubuntu 16.04, mxnet-cu101(1.4.1), Driver Version: 418.39. I can't reproduce your issue.
```
>>> import mxnet as mx
>>> mx.nd.ones((3,4), ctx=mx.gpu())

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @gpu(0)>
```

**Comment by kaivu1999** [comment]
Yeah. I had messed up with my Nvidia drivers. I will update once I do the entire thing again

**Comment by kaivu1999** [comment]
Yeah, 
I had not configured NVIDIA drivers properly
It's working now !!
