### ISSUE TITLE
Problem in my Network.

### ISSUE THREAD

**Issue by kaivu1999** [apache/incubator-mxnet#15083]
## Description
I am trying to make vgg-11 net for Cifar10 data that is I need to have just 10 elements in the last layer.

## Environment info (Required)

```
CuDNN 7.1.4
Cuda 9.2
Nvcc V9.2.148

```

Package used (Python/R/Scala/Julia):
Using the following Python packages
backcall==0.1.0
certifi==2019.3.9
chardet==3.0.4
cycler==0.10.0
decorator==4.4.0
gluoncv==0.4.0.post0
graphviz==0.8.4
idna==2.8
ipython==7.5.0
ipython-genutils==0.2.0
jedi==0.13.3
kiwisolver==1.1.0
matplotlib==3.0.3
mxnet-cu92==1.4.1
numpy==1.14.6
parso==0.4.0
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.0.0
pkg-resources==0.0.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
Pygments==2.4.1
pyparsing==2.4.0
python-dateutil==2.8.0
requests==2.22.0
scipy==1.3.0
six==1.12.0
tqdm==4.32.1
traitlets==4.3.2
urllib3==1.25.2
wcwidth==0.1.7

## Code
```
from mxnet.gluon import nn
from mxnet import init
import mxnet as mx

net = nn.HybridSequential()
net.add(nn.Conv2D(channels=64, kernel_size=(3,3), in_channels=64, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=128, kernel_size=(3,3), in_channels=64, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=256, kernel_size=(3,3), in_channels=128, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.Conv2D(channels=256, kernel_size=(3,3), in_channels=128, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Dense(4096,in_units=25088, activation="relu"))
net.add(nn.Dropout(rate = 0.5))
net.add(nn.Dense(4096,in_units=4096, activation="relu"))
net.add(nn.Dropout(rate = 0.5))
net.add(nn.Dense(10,in_units=4096))
net.hybridize()

net.initialize(init=init.Xavier())

net(mx.nd.ones((1,3,224,224)))
```

## Error Message:
```
>>> net(mx.nd.ones((1,3,224,224)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaivalya/try/env_try1/lib/python3.5/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/home/kaivalya/try/env_try1/lib/python3.5/site-packages/mxnet/gluon/block.py", line 907, in forward
    return self._call_cached_op(x, *args)
  File "/home/kaivalya/try/env_try1/lib/python3.5/site-packages/mxnet/gluon/block.py", line 813, in _call_cached_op
    out = self._cached_op(*cargs)
  File "/home/kaivalya/try/env_try1/lib/python3.5/site-packages/mxnet/_ctypes/ndarray.py", line 150, in __call__
    ctypes.byref(out_stypes)))
  File "/home/kaivalya/try/env_try1/lib/python3.5/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator conv0_fwd: Shape inconsistent, Provided = [64,64,3,3], inferred shape=(64,3,3,3)
```

I don't understand is there a problem in my network ?
Can someone help ?

**Comment by kaivu1999** [comment]
Sorry my bad !!
This works 
'''
from mxnet.gluon import nn
from mxnet import init
import mxnet as mx

net = nn.HybridSequential()
net.add(nn.Conv2D(channels=64, kernel_size=(3,3), in_channels=3, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=128, kernel_size=(3,3), in_channels=64, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=256, kernel_size=(3,3), in_channels=128, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.Conv2D(channels=256, kernel_size=(3,3), in_channels=256, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=256, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.Conv2D(channels=512, kernel_size=(3,3), in_channels=512, strides=(1,1), padding=(1,1)))
net.add(nn.Activation('relu'))
net.add(nn.MaxPool2D(pool_size=(2,2), strides=(2,2), padding=(0,0), ceil_mode=False))
net.add(nn.Dense(4096,in_units=25088, activation="relu"))
net.add(nn.Dropout(rate = 0.5))
net.add(nn.Dense(4096,in_units=4096, activation="relu"))
net.add(nn.Dropout(rate = 0.5))
net.add(nn.Dense(10,in_units=4096))
net.hybridize()

net.initialize(init=init.Xavier())

net(mx.nd.ones((1,3,224,224)))
```
