### ISSUE TITLE
mxnet(mxnet-full_2.11-linux-x86_64-gpu-1.5.0-SNAPSHOT) cannot support cuda10.1?

### ISSUE THREAD

**Issue by tomoncle** [apache/incubator-mxnet#15254]
# mxnet(mxnet-full_2.11-linux-x86_64-gpu-1.5.0-SNAPSHOT) cannot support cuda10.1?
> i'm used `mxnet-full_2.11-linux-x86_64-gpu-1.5.0-SNAPSHOT` maven packages and check it

## ENV
* Java version:
```bash
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```

* Maven version:
```bash
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T03:00:29+08:00)
Maven home: /usr/local/maven
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: /usr/local/jdk1.8.0_191/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-51-generic", arch: "amd64", family: "unix"
```

* cuda version:
```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Fri_Feb__8_19:08:17_PST_2019
Cuda compilation tools, release 10.1, V10.1.105
```

* nvidia version:
```bash
Sun Jun 16 15:25:08 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.09       Driver Version: 430.09       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 166...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0     3W /  N/A |      0MiB /  5944MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

* os:
```bash
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
```

## Check and Test
```java
    @Test
    public void testGPU(){
        System.out.println(System.getenv().containsKey("SCALA_TEST_ON_GPU"));
    }
    //  result is false.
```

* for errors: `why find libcudart.so.9.2` ?:
```bash
15:32:05.129 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.infer.MXNetThreadPoolHandler - threadId: 18
15:32:05.150 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] INFO MXNetJVM - Try loading mxnet-scala from native path.
15:32:05.150 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] WARN MXNetJVM - MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].
15:32:05.151 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] WARN MXNetJVM - LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:
15:32:05.151 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] WARN MXNetJVM - java.library.path=/usr/local/cuda-10.1/lib64::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
15:32:05.159 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Attempting to load libmxnet-scala.so
15:32:05.160 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/libmxnet.so
15:32:10.770 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying libmxnet.so took 5.61 seconds.
15:32:10.771 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/libgfortran.so.3
15:32:10.776 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying libgfortran.so.3 took 0.005 seconds.
15:32:10.776 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/libquadmath.so.0
15:32:10.779 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying libquadmath.so.0 took 0.002 seconds.
15:32:10.779 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/libiomp5.so
15:32:10.789 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying libiomp5.so took 0.01 seconds.
15:32:10.789 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/libmklml_intel.so
15:32:11.290 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying libmklml_intel.so took 0.501 seconds.
15:32:11.291 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/libmkldnn.so.0
15:32:11.341 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying libmkldnn.so.0 took 0.05 seconds.
15:32:11.342 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - tempfile.getPath() = /tmp/mxnet7650335975263211746/mxnet-scala
15:32:11.343 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Copying mxnet-scala took 0.001 seconds.
15:32:11.343 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] DEBUG org.apache.mxnet.util.NativeLibraryLoader - Loading library from /tmp/mxnet7650335975263211746/mxnet-scala
15:32:11.343 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] ERROR org.apache.mxnet.util.NativeLibraryLoader - Couldn't load copied link file: java.lang.UnsatisfiedLinkError: /tmp/mxnet7650335975263211746/mxnet-scala: libcudart.so.9.2: 无法打开共享对象文件: 没有那个文件或目录
15:32:11.343 [org.apache.mxnet.infer.MXNetThreadPoolHandler-0] ERROR MXNetJVM - Couldn't find native library mxnet-scala
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/mxnet7650335975263211746/mxnet-scala: libcudart.so.9.2: 无法打开共享对象文件: 没有那个文件或目录
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.apache.mxnet.util.NativeLibraryLoader$.loadLibraryFromFile(NativeLibraryLoader.scala:131)
	at org.apache.mxnet.util.NativeLibraryLoader$.loadLibrary(NativeLibraryLoader.scala:99)
	at org.apache.mxnet.Base$.<init>(Base.scala:77)
	at org.apache.mxnet.Base$.<clinit>(Base.scala)
	at org.apache.mxnet.Symbol$.initSymbolModule(Symbol.scala:1134)
	at org.apache.mxnet.Symbol$.<init>(Symbol.scala:925)
	at org.apache.mxnet.Symbol$.<clinit>(Symbol.scala)
	at org.apache.mxnet.Model$.loadCheckpoint(Model.scala:70)
	at org.apache.mxnet.module.Module$.loadCheckpoint(Module.scala:644)
	at org.apache.mxnet.infer.Predictor$$anonfun$14.apply(Predictor.scala:256)
	at org.apache.mxnet.infer.Predictor$$anonfun$14.apply(Predictor.scala:256)
	at org.apache.mxnet.infer.MXNetThreadPoolHandler$$anon$4.call(MXNetHandler.scala:83)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

* for my compute:
```
tomoncle@test:/usr/local/cuda-10.1/lib64$ ls |grep libcuda
libcudadevrt.a
libcudart.so
libcudart.so.10.1
libcudart.so.10.1.105
libcudart_static.a
```

**Comment by leleamol** [comment]
@mxnet-label-bot add [Installation, Scala, Cuda]

**Comment by tomoncle** [comment]
**Thank you all. I lowered the CUDA version(9.2), and now it's OK. 
But my code can't use GPU. Do you have any suggestions?**

```java
@Test
public void testGPU(){
     System.out.println(System.getenv().containsKey("SCALA_TEST_ON_GPU"));
}

 //  result is false.
```

**Comment by piyushghai** [comment]
> **Thank you all. I lowered the CUDA version(9.2), and now it's OK. But my code can't use GPU. Do you have any suggestions?**
> 
> ```java
> @Test
> public void testGPU(){
>      System.out.println(System.getenv().containsKey("SCALA_TEST_ON_GPU"));
> }
> 
>  //  result is false.
> ```

@tomoncle This is merely an environment variable that is used for test/debugging purposes. 

In order to make the package use GPU, you need to set the context to use GPU. 
```List<Context> context = new ArrayList<Context>();
      context.add(Context.gpu());
```

**Comment by tomoncle** [comment]
@piyushghai  Thank you very much for your explanation, this has solved my problem.

**Comment by tomoncle** [comment]
## I'm testing a small example of using mxnet to detect entities and then tag specific locations. The specific processing logic is as follows:

* 1.  Use OpenCV to read the video of each frame and save it as a picture stream

* 2.  Then the pictures are processed by mxnet to be pictures with position and object labeled.

* 3.  Then it is echoed to the screen through opencv.



**Question** :  Processing speed is general, there is no change in the use of GPU. I wonder if there is something wrong with my processing logic. Do you have any good suggestions?

Sample code [click this](https://github.com/tomoncle/mxnet-spring-samples/blob/master/mxnet-spring-samples-camera-detecte/src/main/java/com/tomoncle/mxnet/camera/Application.java)

**Comment by piyushghai** [comment]
@tomoncle I had a look at your code processing code. It seems like the OpenCV operations are running on CPU only.
I'm not sure of how to run OpenCV on GPUs though. 
Maybe @lanking520 can provide some suggestions here ?

**Comment by lanking520** [comment]
For image preprocessing, you can use your personal processing toolkit. MXNet provide built-in OpenCV image conversion op. For high-performance computing, I recommend to use Java Image toolkit which is considerably supporting multi-threading that can help you get more throughput.

**Comment by tomoncle** [comment]
Thank you all so much for your warm support, including many constructive advice.

**Comment by zachgk** [comment]
@tomoncle I am closing this issue because it seems like all the problems were addressed. Please reopen if there are remaining problems
