### ISSUE TITLE
[Test failure]: test_custom_operator_profiling_naive_engine

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#15406]
## Description
Docs update PR failed on a test.

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-15117/4/pipeline

```
======================================================================

FAIL: test_profiler.test_custom_operator_profiling_naive_engine

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/test_profiler.py", line 445, in test_custom_operator_profiling_naive_engine

    'test_custom_operator_profiling_multiple_custom_ops_imperative_naive.json')

  File "/work/mxnet/tests/python/unittest/common.py", line 313, in run_in_spawned_process

    assert p.exitcode == 0, "Non-zero exit code %d from %s()." % (p.exitcode, func.__name__)

AssertionError: Non-zero exit code 255 from test_custom_operator_profiling_multiple_custom_ops_imperative().
```

**Comment by aaronmarkham** [comment]
Happened again:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-15117/6/pipeline

**Comment by anirudh2290** [comment]
@Zha0q1

**Comment by aaronmarkham** [comment]
And again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-15427/2/pipeline

**Comment by Zha0q1** [comment]
We are commenting this out for out. Will then take a closer look at this before tomorrow

**Comment by aaronmarkham** [comment]
> We are commenting this out for now. Will then take a closer look at this before tomorrow

This is happening a lot. Did it get removed yet?

**Comment by anirudh2290** [comment]
ya removed in this PR: https://github.com/apache/incubator-mxnet/pull/15436

**Comment by leezu** [comment]
`test_profile_create_domain_dept` is also problematic http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-18701/1/pipeline/378
