### ISSUE TITLE
Flaky test_profiler.test_custom_operator_profiling_naive_engine

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#15414]
```
======================================================================

FAIL: test_profiler.test_custom_operator_profiling_naive_engine

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/test_profiler.py", line 451, in test_custom_operator_profiling_naive_engine

    'test_custom_operator_profiling_multiple_custom_ops_symbolic_naive.json')

  File "/work/mxnet/tests/python/unittest/common.py", line 313, in run_in_spawned_process

    assert p.exitcode == 0, "Non-zero exit code %d from %s()." % (p.exitcode, func.__name__)

AssertionError: Non-zero exit code 255 from test_custom_operator_profiling_multiple_custom_ops_imperative().
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-15400/3/pipeline

**Comment by eric-haibin-lin** [comment]
duplicate: #15406
