### ISSUE TITLE
Flaky test test_metric.test_global_metric

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#15592]
For unrelated PR - https://github.com/apache/incubator-mxnet/pull/14243
Here's the error log - 
```
======================================================================
FAIL: test_metric.test_global_metric
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_metric.py", line 93, in test_global_metric
    _check_global_metric('pcc', shape=(10,2))
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_metric.py", line 81, in _check_global_metric
    assert m1.get() == m2.get()
AssertionError: 
```

Pipeline - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-14243/14/pipeline

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [Test, Flaky]

**Comment by ChaiBapchya** [comment]
Unrelated PR - https://github.com/apache/incubator-mxnet/pull/15601
Pipeline - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-15601/3/pipeline
