### ISSUE TITLE
Unable to convert reference model to ONNX

### ISSUE THREAD

**Issue by KellenSunderland** [apache/incubator-mxnet#15596]
## Description
I'm trying to use the reference python MXNet to ONNX conversion and I'm running into a few issues.  Probably something I'm doing that's wrong, but I can't figure out what.  

When I run:
```
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet
from mxnet.gluon.model_zoo import vision
import mxnet as mx
# import backend

url = 'https://github.com/dmlc/web-data/blob/master/mxnet/doc/tutorials/python/predict_image/cat.jpg?raw=true'
model_file_name = '/tmp/mobilenet_onnx_test'


def get_image(image_url):
    fname = mx.test_utils.download(image_url, fname=image_url.split('/')[-1].split('?')[0])
    img = mx.image.imread(fname)
    img = mx.image.imresize(img, 224, 224)  # Resize
    img = img.transpose((2, 0, 1))  # Channel first
    img = img.expand_dims(axis=0)  # Batchify
    img = mx.nd.cast(img, dtype=np.float32)
    return img / 255.0


input_data = get_image(url)
batch_shape = (1, 3, 224, 224)
mobilenet = vision.mobilenet_v2_1_0(pretrained=True)
mobilenet.hybridize()
mobilenet.forward(input_data)
mobilenet.export(model_file_name)
onnx_mxnet.export_model(sym=model_file_name + '-symbol.json', input_shape=batch_shape, verbose=True,
                        params=model_file_name + '-0000.params')
```
or
```
import numpy as np
from mxnet.contrib import onnx as onnx_mxnet
from mxnet.gluon.model_zoo import vision
import mxnet as mx

url = 'https://github.com/dmlc/web-data/blob/master/mxnet/doc/tutorials/python/predict_image/cat.jpg?raw=true'
model_file_name = 'mobilenet_onnx_test'


def get_image(image_url):
    fname = mx.test_utils.download(image_url, fname=image_url.split('/')[-1].split('?')[0])
    img = mx.image.imread(fname)
    img = mx.image.imresize(img, 224, 224)  # Resize
    img = img.transpose((2, 0, 1))  # Channel first
    img = img.expand_dims(axis=0)  # Batchify
    img = mx.nd.cast(img, dtype=np.float32)
    return img / 255.0


input_data = get_image(url)
batch_shape = (1, 3, 224, 224)
mobilenet = vision.mobilenet_v2_1_0(pretrained=True)
mobilenet.hybridize()
mobilenet.forward(input_data)
mobilenet.export(model_file_name)
sym, arg_params, aux_params = mx.model.load_checkpoint(model_file_name, 0)
executor = sym.simple_bind(ctx=mx.cpu(), data=batch_shape,
                           grad_req='null', force_rebind=True)
executor.copy_params_from(arg_params, aux_params)

all_params = {}

for k, v in arg_params.items():
    all_params[k] = v
for k, v in aux_params.items():
    all_params[k] = v

onnx_mxnet.export_model(sym=sym, input_shape=batch_shape, verbose=True, params=all_params)
```

I get 
```
/Users/kellens/miniconda3/bin/python /Users/kellens/Development/s3putter/mxnet_batchnorm_converter.py
Traceback (most recent call last):
  File "/Users/kellens/Development/s3putter/mxnet_batchnorm_converter.py", line 38, in <module>
    onnx_mxnet.export_model(sym=sym, input_shape=batch_shape, verbose=True, params=all_params)
  File "/Users/kellens/miniconda3/lib/python3.7/site-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 87, in export_model
    verbose=verbose)
  File "/Users/kellens/miniconda3/lib/python3.7/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 211, in create_onnx_graph_proto
    graph_outputs = MXNetGraph.get_outputs(sym, params, in_shape, output_label)
  File "/Users/kellens/miniconda3/lib/python3.7/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 138, in get_outputs
    in_shape)}
  File "/Users/kellens/miniconda3/lib/python3.7/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 137, in <dictcomp>
    inputs = {n: tuple(s) for n, s in zip([n for n in sym.list_inputs() if n not in params and n != in_label],
TypeError: 'int' object is not iterable
```

## Environment info (Required)
MXNet 1.4.1 pip installed, cpu verison.

## What have you tried to solve it?

1.  Run with TensorRT integration, which in theory also converts to ONNX, don't run into errors.

**Comment by vandanavk** [comment]
try adding batch_shape within [] in the export_model() call.

`onnx_mxnet.export_model(sym=sym, input_shape=[batch_shape], verbose=True, params=all_params)
`

**Comment by KellenSunderland** [comment]
Thanks @vandanavk!
