### ISSUE TITLE
LeNet-5 inference FAIL

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#15786]
PR #15783 
Build pipeline -
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15783/6/pipeline/
```
======================================================================
FAIL: Run LeNet-5 inference comparison between MXNet and TensorRT.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/work/mxnet/tests/python/tensorrt/test_tensorrt_lenet5.py", line 102, in test_tensorrt_inference
    MXNet = %f, TensorRT = %f""" % (absolute_accuracy_diff, epsilon, mx_pct, trt_pct)
AssertionError: Absolute diff. between MXNet & TensorRT accuracy (0.020000) exceeds threshold (0.010100):
           MXNet = 99.140000, TensorRT = 99.120000
-------------------- >> begin captured logging << --------------------
root: INFO: train-labels-idx1-ubyte.gz exists, skipping download
root: INFO: train-images-idx3-ubyte.gz exists, skipping download
root: INFO: t10k-labels-idx1-ubyte.gz exists, skipping download
root: INFO: t10k-images-idx3-ubyte.gz exists, skipping download
--------------------- >> end captured logging << ---------------------
```

**Comment by ChaiBapchya** [comment]
Not sure if this is Bug on MXNet side. Since MXNet accuracy higher than TensorRT
