### ISSUE TITLE
[CI] Windows CPU numpy module not found

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#15879]
Pipeline - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-cpu/detail/PR-15783/9/pipeline

Multiple occurrences of "module not found" 

One such error log:
```
======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'numpy')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Python37\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python37\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python37\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Python37\lib\imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "C:\Python37\lib\imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\jenkins_slave\workspace\ut-python-cpu@2\tests\python\unittest\test_viz.py", line 21, in <module>
    import mxnet as mx
  File "C:\jenkins_slave\workspace\ut-python-cpu@2\windows_package\python\mxnet\__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "C:\jenkins_slave\workspace\ut-python-cpu@2\windows_package\python\mxnet\context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "C:\jenkins_slave\workspace\ut-python-cpu@2\windows_package\python\mxnet\base.py", line 29, in <module>
    import numpy as _np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [CI]

**Comment by DickJC123** [comment]
I've seen a similar error in a pipeline of mine.  Your pipeline has a first mention of trouble:
```
powershell.exe : ERROR: Could not install packages due to an EnvironmentError: [WinError 2] The system cannot find the file specified: 

'c:\\python37\\Lib\\site-packages\\pygments\\formatters\\__pycache__\\html.cpython-37.pyc'
```
In a pipeline of mine (http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-cpu/detail/PR-15882/9/pipeline/), the error was:
```
Installing collected packages: funcsigs, six, mock, nose, nose-timer, wcwidth, prompt-toolkit, decorator, scandir, pathlib2, pickleshare, win-unicode-console, pygments, backports.shutil-get-terminal-size, colorama, simplegeneric, enum34, ipython-genutils, traitlets, ipython, numpy, scipy

ERROR: Could not install packages due to an EnvironmentError: [Error 2] The system cannot find the file specified: 'c:\\python27\\Lib\\site-packages\\funcsigs\\__init__.py'
```
@marcoabreu Can you have someone look into these sporadic build-machine issues that happen when pulling in python packages prior to running nosetests?

**Comment by marcoabreu** [comment]
@perdasilva can you have a look please?
