### ISSUE TITLE
KeyError using onnx2mx on basic Keras LSTM model

### ISSUE THREAD

**Issue by ceedubs** [apache/incubator-mxnet#15920]
## Description
`KeyError: 'dense_1/Sigmoid:01'` when using `onnx2mx` to import an LSTM model that was originally trained via keras and converted to ONNX format via `keras2onnx`.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.8
Compiler     : GCC 4.2.1 Compatible Clang 5.0.2 (tags/RELEASE_502/final)
Build        : ('default', 'Mar 24 2019 21:04:37')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.2.2
Directory    : /Users/cody.allen/code/work/mxnet-onnx-experiment/venv/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 1.5.0
Directory    : /Users/cody.allen/code/work/mxnet-onnx-experiment/venv/lib/python3.6/site-packages/mxnet
Commit Hash   : 75a9e187d00a8b7ebc71412a02ed0e3ae489d91f
Library      : ['/Users/cody.allen/code/work/mxnet-onnx-experiment/venv/lib/python3.6/site-packages/mxnet/libmxnet.so']
Build features:
✖ CUDA
✖ CUDNN
✖ NCCL
✖ CUDA_RTC
✖ TENSORRT
✔ CPU_SSE
✔ CPU_SSE2
✔ CPU_SSE3
✔ CPU_SSE4_1
✔ CPU_SSE4_2
✖ CPU_SSE4A
✔ CPU_AVX
✖ CPU_AVX2
✖ OPENMP
✖ SSE
✖ F16C
✖ JEMALLOC
✖ BLAS_OPEN
✖ BLAS_ATLAS
✖ BLAS_MKL
✖ BLAS_APPLE
✔ LAPACK
✖ MKLDNN
✔ OPENCV
✖ CAFFE
✖ PROFILER
✔ DIST_KVSTORE
✖ CXX14
✖ INT64_TENSOR_SIZE
✔ SIGNAL_HANDLER
✖ DEBUG
----------System Info----------
Platform     : Darwin-18.7.0-x86_64-i386-64bit
system       : Darwin
node         : codyallen-ltm.internal.salesforce.com
release      : 18.7.0
version      : Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET BMI1 AVX2 SMEP BMI2 ERMS INVPCID FPU_CSDS MDCLEAR IBRS STIBP L1DF SSBD'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT RDTSCP TSCI'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0029 sec, LOAD: 0.7550 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.2133 sec, LOAD: 0.1103 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0255 sec, LOAD: 1.8468 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0554 sec, LOAD: 0.6177 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0047 sec, LOAD: 0.3533 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0737 sec, LOAD: 0.0521 sec.
```

Package used (Python/R/Scala/Julia):
I'm using Python, along with `keras2onnx`.

Here are the direct dependencies:

```
keras==2.2.4
tensorflow==1.14.0
mxnet==1.5.0
keras2onnx==1.5.1
onnxruntime==0.5.0
```

## Error Message:
```
Traceback (most recent call last):
  File "cerealization/model-to-onnx.py", line 49, in <module>
    sym, arg, aux = mxnet_model = onnx_mxnet.import_model(onnx_file)
  File "/some-path/mxnet-onnx-experiment/venv/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/import_model.py", line 59, in import_model
    sym, arg_params, aux_params = graph.from_onnx(model_proto.graph)
  File "/some-path/mxnet-onnx-experiment/venv/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 115, in from_onnx
    inputs = [self._nodes[i] for i in node.input]
  File "/some-path/mxnet-onnx-experiment/venv/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 115, in <listcomp>
    inputs = [self._nodes[i] for i in node.input]
KeyError: 'dense_1/Sigmoid:01'
```

## Minimum reproducible example
A repo with a complete (and fairly minimal) reproduction of the error can be found [here](https://github.com/ceedubs/mxnet-onnx-experiment).

The most significant parts are this Keras model:

```python
    model = Sequential()
    model.add(Embedding(max_features, 128))
    model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
    model.add(Dense(1, activation='sigmoid'))

    # try using different optimizers and different optimizer configs
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
```

Along with this Keras -> ONNX -> MXNet code:

```python
onnx_model = keras2onnx.convert_keras(keras_model)

onnx.save_model(onnx_model, onnx_file)

# this fails with KeyError: 'activation_1/Sigmoid:01'
sym, arg, aux = mxnet_model = onnx_mxnet.import_model(onnx_file)
```

## Steps to reproduce
See the instructions in [this repo](https://github.com/ceedubs/mxnet-onnx-experiment#dependencies).

1. `git clone git@github.com:ceedubs/mxnet-onnx-experiment.git && cd mxnet-onnx-experiment`
2. `nix-shell --pure` (or `pip install -r requirements-frozen.txt` if you don't use Nix)
3. `python cerealization/model-to-onnx.py`

## What have you tried to solve it?

1. I tried running the ONNX model via the ONNX Python runtime instead of the MXNet runtime, and this worked fine.
2. I tried inspecting the model output names and noticed that `keras_model.outputs` returns `[<tf.Tensor 'dense_1/Sigmoid:0' shape=(?, 1) dtype=float32>]`. There seems to be a discrepancy between `Sigmoid:01` in the error message and `Sigmoid:0` in the keras output; I'm not sure whether that is part of the issue.
3. I tried using both `onnxmltools.convert_keras(keras_model)` and `keras2onnx.convert_keras(keras_model)`. They both produce the same error.

**Comment by lilipj** [comment]
I have the same problem with keras2onnx, and onnxmltools, but when I change the target_opset to 8 in onnxmltool.convert_keras function, it works. When target_opset is 9 , it fails
