### ISSUE TITLE
Tracking Large Tensor vector test coverage

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#15967]
As part of the ongoing effort to cover certain set of operators for testing large vector support (vector size > 2^32)

Few ops that haven't been covered yet / Need to be fixed

1. ndarray convert types
e.g. `a.tostype('row_sparse')`

2. nd.dot
3. nd.where
4. nd.sparse.where

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [Test]

**Comment by ChaiBapchya** [comment]
From @access2rohit PR #15943 
https://github.com/apache/incubator-mxnet/pull/15943/commits/9bff00f0480b6fd278221f9b04483ccda05e3cc4

**Comment by ChaiBapchya** [comment]
From my PR #15941 
SequenceLast
```
======================================================================
ERROR: test_large_vector.test_sequence_last
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/tests/nightly/test_large_vector.py", line 234, in test_sequence_last
    a[-1][0]=100
  File "/home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 655, in __getitem__
    return self._get_nd_basic_indexing(key)
  File "/home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 940, in _get_nd_basic_indexing
    ctypes.byref(handle),
  File "/home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:08:57] ../src/ndarray/ndarray.cc:278: Check failed: begin <= end (4294967294 vs. 0) : Invalid slicing range [4294967294, 0)
Stack trace:
  [bt] (0) /home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/../../build/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x34) [0x7fded2d7339a]
  [bt] (1) /home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/../../build/libmxnet.so(mxnet::NDArray::Slice(long, long) const+0x1b4) [0x7fded313329a]
  [bt] (2) /home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/../../build/libmxnet.so(mxnet::NDArray::SliceWithRecord(long, long)+0x5b) [0x7fded3133845]
  [bt] (3) /home/ubuntu/workspace/lts/lts_seq_last/incubator-mxnet/python/mxnet/../../build/libmxnet.so(MXNDArraySlice+0x81) [0x7fded2d68a7e]
  [bt] (4) /home/ubuntu/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7fdef6136ec0]
  [bt] (5) /home/ubuntu/anaconda3/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7fdef613687d]
  [bt] (6) /home/ubuntu/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fdef634be2e]
  [bt] (7) /home/ubuntu/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x12865) [0x7fdef634c865]
  [bt] (8) /home/ubuntu/anaconda3/bin/python(_PyObject_FastCallDict+0x8b) [0x55972dc79d7b]
```
