### ISSUE TITLE
Saving and loading singular arrays crashes the library

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#15988]
This should not crash the library, either propagate an exception or preferrably handle it successfullly.

```
In [20]: nd.save('/tmp/x',nd.array(1))                                                                                                                                                                         

In [21]: nd.load('/tmp/x')             
<bad things happening>
```

type_flag gets a garbage value on reading, presumably because the value is not read as the shape has 0 dimensions.
https://github.com/apache/incubator-mxnet/blob/master/src/ndarray/ndarray.cc#L1706

**Comment by larroy** [comment]
@mxnet-label-bot add [Bug, Breaking]

**Comment by larroy** [comment]
@reminisce @haojin2 @samskalicky

**Comment by samskalicky** [comment]
Can you please add this error message in the description:

```
Python(28036,0x7fff962d43c0) malloc: *** mach_vm_map(size=4575657221408428032) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/mxnet/ndarray/utils.py", line 175, in load
    ctypes.byref(names)))
  File "/usr/local/lib/python2.7/site-packages/mxnet/base.py", line 254, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: std::bad_alloc
```
