### ISSUE TITLE
ImportError: cannot import name 'ftml_update'

### ISSUE THREAD

**Issue by tianzheng4** [apache/incubator-mxnet#16056]
Operating system: Ubuntu 16.04
Cuda version: cuda 9.0
Python 3.6.6

I have installed mxnet-cu90==1.0.0 using pip3. However, when I try "import mxnet", I got the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mxnet/__init__.py", line 42, in <module>
    from . import optimizer
  File "/usr/local/lib/python3.6/dist-packages/mxnet/optimizer/__init__.py", line 19, in <module>
    from . import optimizer, contrib
  File "/usr/local/lib/python3.6/dist-packages/mxnet/optimizer/optimizer.py", line 28, in <module>
    from ..ndarray import (sgd_update, sgd_mom_update, adam_update, rmsprop_update, rmspropalex_update,
ImportError: cannot import name 'ftml_update

**Comment by tianzheng4** [comment]
@mxnet-label-bot add [Installation]
