### ISSUE TITLE
Sampling fails on mxnet-mkl==1.5.0?

### ISSUE THREAD

**Issue by lostella** [apache/incubator-mxnet#16135]
## Description
Some random sampling functions seem not to be working on mxnet-mkl version 1.5.0.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.8
Compiler     : GCC 8.3.0
Build        : ('default', 'Aug 20 2019 17:12:48')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /usr/lib/python3/dist-packages/pip
----------MXNet Info-----------
Version      : 1.5.0
Directory    : /usr/local/lib/python3.6/dist-packages/mxnet
Commit Hash   : 75a9e187d00a8b7ebc71412a02ed0e3ae489d91f
Library      : ['/usr/local/lib/python3.6/dist-packages/mxnet/libmxnet.so']
Build features:
No runtime build feature info available
----------System Info----------
Platform     : Linux-4.9.184-linuxkit-x86_64-with-Ubuntu-18.04-bionic
system       : Linux
node         : 052b8025cdde
release      : 4.9.184-linuxkit
version      : #1 SMP Tue Jul 2 22:58:16 UTC 2019
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
Stepping:            9
CPU MHz:             2500.000
BogoMIPS:            4992.00
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            4096K
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch kaiser fsgsbase bmi1 hle avx2 bmi2 erms rtm xsaveopt arat
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0417 sec, LOAD: 0.5915 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0663 sec, LOAD: 0.9574 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0654 sec, LOAD: 0.8602 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0557 sec, LOAD: 0.8515 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0422 sec, LOAD: 0.7237 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0470 sec, LOAD: 0.1490 sec.
----------Environment----------
```

I'm using Python, pip-freeze gives:

```
asn1crypto==0.24.0
certifi==2019.6.16
chardet==3.0.4
cryptography==2.1.4
graphviz==0.8.4
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
mxnet-mkl==1.5.0
numpy==1.17.2
pycrypto==2.6.1
pygobject==3.26.1
pyxdg==0.25
requests==2.22.0
SecretStorage==2.3.1
six==1.11.0
urllib3==1.25.3
```

## Error Message:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 68, in sample_normal
  File "/usr/local/lib/python3.6/dist-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 253, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: vector::_M_range_insert
```

## Minimum reproducible example

```python
import mxnet as mx
s = mx.nd.sample_normal(mu=mx.nd.array([10.0]), sigma=mx.nd.array([0.5]))
```

**Comment by lostella** [comment]
This still did not occur in `mxnet_mkl-1.4.1`, and appears to be still occurring in `mxnet_mkl-1.6.0b20190909`

**Comment by ChaiBapchya** [comment]
@mxnet-label-bot add [Operator, Bug]

**Comment by ChaiBapchya** [comment]
Thanks for pointing out.
I was able to reproduce this issue for `pip install mxnet==1.5.0`, `pip install mxnet==1.6.0`

No error for `pip install mxnet==1.4.0`
So likely introduced in patch release 1.4.1

**Comment by lostella** [comment]
> No error for `pip install mxnet==1.4.0`
> So likely introduced in patch release 1.4.1

I was not able to reproduce on 1.4.1, so probably introduced in 1.5.0

**Comment by reminisce** [comment]
Fixed in https://github.com/apache/incubator-mxnet/pull/16139.

**Comment by lostella** [comment]
@reminisce does the fix also fix sampling other than sample_normal? All other sampling functions also raise the same error on 1.5.0:
* `s = mx.nd.sample_uniform(low=mx.nd.array([10.0]), high=mx.nd.array([11.5]))`
* `s = mx.nd.sample_negative_binomial(k=mx.nd.array([3]), p=mx.nd.array([0.5]))`
* `s = mx.nd.sample_poisson(lam=mx.nd.array([1.5]))`
* ...

**Comment by asmushetzel** [comment]
The fix provided should fix all the samplers (i.e. for all distributions).
