### ISSUE TITLE
CI failure - test_operator_gpu.test_update_ops_mutation

### ISSUE THREAD

**Issue by aaronmarkham** [apache/incubator-mxnet#16217]
Failed a run on an unrelated update:
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-gpu/detail/PR-15883/39/pipeline/

**Comment by haojin2** [comment]
Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-16990/4/pipeline/
```
======================================================================

FAIL: test_ndarray.test_update_ops_mutation

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_ndarray.py", line 2023, in test_update_ops_mutation

    _test_update_ops_mutation_impl()

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_ndarray.py", line 2001, in _test_update_ops_mutation_impl

    'clip_gradient': 1e-3})

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_ndarray.py", line 1988, in test_op

    assert_mutate(pre_array, post_array)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_ndarray.py", line 1960, in assert_mutate

    AssertionError, assert_allclose, x, y)

  File "C:\Python27\lib\site-packages\numpy\testing\_private\utils.py", line 1295, in assert_raises

    return _d.assertRaises(*args,**kwargs)

AssertionError: AssertionError not raised

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1186395396 to reproduce.

--------------------- >> end captured logging << ---------------------
```
