### ISSUE TITLE
Authorization failed when loading data from S3

### ISSUE THREAD

**Issue by Yunrui** [apache/incubator-mxnet#1622]
Hi folks,

I installed a mxnet cluster in region cn-north-1 in AWS. When trying to load data in S3, I got the below error message. It seems that new S3 regions, like cn-north-1, deployed after January, 2014 only support V4, but dmlc-core still use sha1. 

2016-03-11 09:34:56,466 Node[0] start with arguments Namespace(batch_size=512, data_dir='s3://mydata/mnist/', gpus='0', kv_store='dist_sync', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='lenet', num_epochs=10, num_examples=60000)
[09:34:57] /home/ubuntu/mxnet/dmlc-core/include/dmlc/logging.h:241: [09:34:57] src/io/s3_filesys.cc:785: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>**_</RequestId><HostId>**_</HostId></Error>
Traceback (most recent call last):
  File "train_mnist.py", line 130, in <module>
    train_model.fit(args, net, get_iterator(data_shape))
  File "/tmp/mxnet/train_model.py", line 44, in fit
    (train, val) = data_loader(args, kv)
  File "train_mnist.py", line 74, in get_iterator_impl
    part_index  = kv.rank)
  File "/tmp/mxnet/mxnet/io.py", line 574, in creator
    ctypes.byref(iter_handle)))
  File "/tmp/mxnet/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

**Comment by tqchen** [comment]
i see, can you help to update the dmlc-core's S3 support? Thanks!

**Comment by Yunrui** [comment]
ok, I will take it.

**Comment by tqchen** [comment]
@Yunrui do we have any updates on this issue?

**Comment by Yunrui** [comment]
I got a prototype working with small data set, but got time-out when file size exceeds 1G, which I am thinking whether it's right approach to train 2T data set hosted in AWS. Currently, we attached big hard disks to work around this issue. Sorry having little time on this for now, but will look at it when I am free if nobody have a fix on it.

**Comment by ChaiBapchya** [comment]
@nswamy @szha Is this issue relevant anymore?
