### ISSUE TITLE
mxnet.base.MXNetError: [13:43:35] C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc:1755: Check failed: fi->Read(data) Invalid NDArray file format while loading resnet-18

### ISSUE THREAD

**Issue by Sumanth-393** [apache/incubator-mxnet#16224]
got Error while loading checkpoint from model.load_checkpoint

## Steps to reproduce
(Paste the commands you ran that produced the error.)

path='http://data.mxnet.io/models/imagenet/'
[
mx.test_utils.download(path+'resnet/18-layers/resnet-18-0000.params'),
 mx.test_utils.download(path+'resnet/18-layers/resnet-18-symbol.json'),
 mx.test_utils.download(path+'synset.txt')]
ctx = mx.cpu()
sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-18', 0)

error is as below:

E:\my_projects\mxnet_work>python Mxnet_imageClaify.py
[13:43:35] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:209: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[13:43:35] C:\Jenkins\workspace\mxnet-tag\mxnet\src\nnvm\legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "Mxnet_imageClaify.py", line 14, in <module>
    sym, arg_params, aux_params = mx.model.load_checkpoint('resnet-18', 0)
  File "C:\Users\bunny\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\model.py", line 439, in load_checkpoint
    save_dict = nd.load('%s-%04d.params' % (prefix, epoch))
  File "C:\Users\bunny\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\ndarray\utils.py", line 175, in load
    ctypes.byref(names)))
  File "C:\Users\bunny\AppData\Local\Programs\Python\Python36\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:43:35] C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc:1755: Check failed: fi->Read(data) Invalid NDArray file format

kindly help i'm new to mxnet

**Comment by zachgk** [comment]
I ran this and it seemed to work fine.

The mx.test_utils.download directory tries to download the files to the local directory. Can you try navigating to an empty directory before running this?


Can you also share your environment info:
```
What to do:
1. Download the diagnosis script from https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py
2. Run the script using `python diagnose.py` and paste its output here.

```

**Comment by Sumanth-393** [comment]
Thank You zachgk its working fine
