### ISSUE TITLE
CI Flaky Test: test_operator_gpu.test_np_around

### ISSUE THREAD

**Issue by rondogency** [apache/incubator-mxnet#16358]
Centos GPU test_operator_gpu.test_np_around fails on tolerance
should be a flaky test since it is the only occurrence I know

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-15921/52/pipeline
```
FAIL: test_operator_gpu.test_np_around
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.6/site-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/python/mxnet/util.py", line 307, in _with_np_shape
    return func(*args, **kwargs)
  File "/work/mxnet/python/mxnet/util.py", line 491, in _with_np_array
    return func(*args, **kwargs)
  File "/work/mxnet/tests/python/gpu/../unittest/test_numpy_op.py", line 2447, in test_np_around
    assert_almost_equal(mx_out.asnumpy(), np_out, rtol=rtol, atol=atol)
  File "/work/mxnet/python/mxnet/test_utils.py", line 533, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 1.457707 exceeds tolerance rtol=0.001000, atol=0.000010.  Location of maximum error:(), a=0.675000, b=0.676000
 a: array(0.675, dtype=float32)
 b: 0.676
```

**Comment by rondogency** [comment]
@mxnet-label-bot add [Test, Flaky]

**Comment by ChaiBapchya** [comment]
Fail - test_np_around in test_numpy_op.py file
Unrelated PR #16585 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-16585/8/pipeline
```
======================================================================

FAIL: test_numpy_op.test_np_around

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Python37\lib\site-packages\nose\case.py", line 198, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\util.py", line 315, in _with_np_shape

    return func(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\util.py", line 499, in _with_np_array

    return func(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_numpy_op.py", line 3088, in test_np_around

    assert_almost_equal(mx_out.asnumpy(), np_out, rtol=rtol, atol=atol)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\test_utils.py", line 627, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 3.937004 exceeds tolerance rtol=1.000000e-03, atol=1.000000e-05 (mismatch 16.666667%).

Location of maximum error: (0, 0, 1), a=2.51999998, b=2.52999997

 ACTUAL: array([[[ 0.79     ,  2.52     , -0.76     ],

        [-1.3      ,  0.88     ,  1.4100001]]], dtype=float32)

 DESIRED: array([[[ 0.79,  2.53, -0.76],

        [-1.3 ,  0.88,  1.41]]], dtype=float32)

-------------------- >> begin captured stdout << ---------------------


*** Maximum errors for vector of size 6:  rtol=0.001, atol=1e-05


  1: Error 3.937004  Location of error: (0, 0, 1), a=2.51999998, b=2.52999997


--------------------- >> end captured stdout << ----------------------
```
