### ISSUE TITLE
[Flaky] test_np_max_min on windows

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#16389]
```bash
 92607 ======================================================================
 92608 ERROR: test_numpy_op.test_np_max_min
 92609 ----------------------------------------------------------------------
 92610 Traceback (most recent call last):
 92611   File "C:\Python37\lib\site-packages\nose\case.py", line 198, in runTest
 92612     self.test(*self.arg)
 92613   File "C:\jenkins_slave\workspace\ut-python-cpu@3\tests\python\unittest\common.py", line 177, in test_new
 92614     orig_test(*args, **kwargs)
 92615   File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\util.py", line 307, in _with_np_shape
 92616     return func(*args, **kwargs)
 92617   File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\util.py", line 491, in _with_np_array
 92618     return func(*args, **kwargs)
 92619   File "C:\jenkins_slave\workspace\ut-python-cpu@3\tests\python\unittest\test_numpy_op.py", line 703, in test_np_max_min
 92620     expected_ret = _np.amax(x.asnumpy(), axis=axis, keepdims=keepdims)
 92621   File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\ndarray\ndarray.py", line 2504, in asnumpy
 92622     ctypes.c_size_t(data.size)))
 92623   File "C:\jenkins_slave\workspace\ut-python-cpu@3\windows_package\python\mxnet\base.py", line 254, in check_call
 92624     raise MXNetError(py_str(_LIB.MXGetLastError()))
 92625 mxnet.base.MXNetError: [18:36:00] c:\jenkins_slave\workspace\build-cpu\include\mxnet\tuple.h:390: Check failed: ndim >= -1 (-450807624 vs. -1) : shape ndim must be         >= -1, while received
 92626 -450807624
```
[windows.log](https://github.com/apache/incubator-mxnet/files/3699033/windows.log)
@stu1130

**Comment by stu1130** [comment]
observe the same error in np_mean windows_gpu
```
======================================================================

ERROR: test_numpy_op.test_np_mean

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Python37\lib\site-packages\nose\case.py", line 198, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\util.py", line 307, in _with_np_shape

    return func(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\util.py", line 491, in _with_np_array

    return func(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\test_numpy_op.py", line 800, in test_np_mean

    assert_almost_equal(mx_out.asnumpy(), np_out, rtol=1e-3, atol=1e-5, use_broadcast=False)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\ndarray\ndarray.py", line 2504, in asnumpy

    ctypes.c_size_t(data.size)))

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\base.py", line 254, in check_call

    raise MXNetError(py_str(_LIB.MXGetLastError()))

mxnet.base.MXNetError: [05:47:40] c:\jenkins_slave\workspace\build-gpu\include\mxnet\tuple.h:390: Check failed: ndim >= -1 (-278127078 vs. -1) : shape ndim must be >= -1, while received 

-278127078

-------------------- >> begin captured logging << --------------------

root: INFO: NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in 

the official NumPy library. Please DO NOT manually

 deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1811468884 to reproduce.
```

**Comment by ChaiBapchya** [comment]
Same error 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-16104/23/pipeline
#16104

**Comment by ChaiBapchya** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-16403/1/pipeline
Unrelated PR #16403

**Comment by ChaiBapchya** [comment]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-cpu/detail/PR-16328/16/pipeline/175
Unrelated PR #16328

**Comment by reminisce** [comment]
Fixed in https://github.com/apache/incubator-mxnet/pull/16415
