### ISSUE TITLE
Inconsistent behavior of calling dtype of NDArray

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#16402]
`mx.nd.dtype()` should either give the correct result or throw an error like in numpy.
mxnet:
```
>>> a=mx.random.uniform(shape(3,4,5))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'shape' is not defined
>>> a=mx.random.uniform(shape=(3,4,5))
>>> a.dtype
<class 'numpy.float32'>
>>> a.dtype()
0.0
>>> b=mx.nd.cast(a, dtype='int32')
>>> b.dtype
<class 'numpy.int32'>
>>> b.dtype()
0
```

numpy:
```
>>> a=np.random.rand(3,4,5)
>>> a.dtype
dtype('float64')
>>> a.dtype()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.dtype' object is not callable
>>> b=a.astype('int32')
>>> b.dtype
dtype('int32')
>>> b.dtype()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'numpy.dtype' object is not callable
>>>
```

**Comment by haojin2** [comment]
Nice catch! Verified that this also happens in the new numpy module, will devote some time on investigating this issue.
