### ISSUE TITLE
test_operator test_bulking_operator_gpu failing on centos gpu

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#16517]
Unrelated PR https://github.com/apache/incubator-mxnet/pull/16477

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-16477/5/pipeline

Maybe related to #14368
```
======================================================================

FAIL: test_operator_gpu.test_bulking_operator_gpu

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 2398, in test_bulking_operator_gpu

    _test_bulking(_test_bulking_in_process)

  File "/work/mxnet/tests/python/gpu/test_gluon_gpu.py", line 553, in _test_bulking

    time_per_iteration):

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 334, in run_in_spawned_process

    assert p.exitcode == 0, "Non-zero exit code %d from %s()." % (p.exitcode, func.__name__)

AssertionError: Non-zero exit code -6 from _test_bulking_in_process().

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=9942330 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by ChaiBapchya** [comment]
#16416 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-16416/7/pipeline
```
======================================================================

FAIL: test_operator_gpu.test_bulking_operator_gpu

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/lib/python3.6/site-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 2398, in test_bulking_operator_gpu

    _test_bulking(_test_bulking_in_process)

  File "/work/mxnet/tests/python/gpu/test_gluon_gpu.py", line 553, in _test_bulking

    time_per_iteration):

  File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 334, in run_in_spawned_process

    assert p.exitcode == 0, "Non-zero exit code %d from %s()." % (p.exitcode, func.__name__)

AssertionError: Non-zero exit code -6 from _test_bulking_in_process().

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1193875868 to reproduce.

--------------------- >> end captured logging << ---------------------


----------------------------------------------------------------------
```

**Comment by aaronmarkham** [comment]
Failed here: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-16512/4/pipeline
Really need to clean out these tests or figure out the infra side so that they're not so brittle...

**Comment by ChaiBapchya** [comment]
@roywei should I close this (coz this is related to https://github.com/apache/incubator-mxnet/issues/14970)
#14971 disabled `test_operator_gpu.test_bulking`
I can keep this issue open and open a PR that disables this particular test `test_operator_gpu.test_bulking_operator_gpu`

**Comment by roywei** [comment]
@ChaiBapchya 
Let's disable it properly and we can close either issue, just leave one open.
Thanks!

**Comment by roywei** [comment]
closing due to duplicate #14970
