### ISSUE TITLE
[Flaky] mx.np.linalg.inv

### ISSUE THREAD

**Issue by reminisce** [apache/incubator-mxnet#16776]
```
$ MXNET_TEST_SEED=639317673 nosetests --verbose --nocapture test_numpy_op:test_np_linalg_inv
test_numpy_op.test_np_linalg_inv ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=639317673 to reproduce.

*** Maximum errors for vector of size 54:  rtol=0.01, atol=0.01

  1: Error 1.057003  Location of error: (1, 2, 2, 0), a=1078269824.00000000, b=1089788928.00000000
  2: Error 1.056994  Location of error: (1, 2, 2, 1), a=451034368.00000000, b=455852704.00000000
  3: Error 1.056913  Location of error: (1, 2, 1, 0), a=-15699981312.00000000, b=-15867688960.00000000
  4: Error 1.056913  Location of error: (1, 2, 1, 1), a=-6567216128.00000000, b=-6637367296.00000000
  5: Error 1.056899  Location of error: (1, 2, 0, 0), a=-16766963712.00000000, b=-16946066432.00000000
  6: Error 1.056894  Location of error: (1, 2, 0, 1), a=-7013528576.00000000, b=-7088445952.00000000
  7: Error 1.056602  Location of error: (1, 2, 2, 2), a=8499509.00000000, b=8590274.00000000
  8: Error 1.056518  Location of error: (1, 2, 1, 2), a=-123755792.00000000, b=-125077256.00000000
  9: Error 1.056495  Location of error: (1, 2, 0, 2), a=-132166328.00000000, b=-133577568.00000000
FAIL

======================================================================
FAIL: test_numpy_op.test_np_linalg_inv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/unison/mxnet4/cpu/tests/python/unittest/common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "/home/ubuntu/unison/mxnet4/cpu/python/mxnet/util.py", line 315, in _with_np_shape
    return func(*args, **kwargs)
  File "/home/ubuntu/unison/mxnet4/cpu/python/mxnet/util.py", line 499, in _with_np_array
    return func(*args, **kwargs)
  File "/home/ubuntu/unison/mxnet4/cpu/tests/python/unittest/test_numpy_op.py", line 3176, in test_np_linalg_inv
    assert_almost_equal(data.grad.asnumpy(), backward_expected, rtol=rtol, atol=atol)
  File "/home/ubuntu/unison/mxnet4/cpu/python/mxnet/test_utils.py", line 627, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
Error 1.057003 exceeds tolerance rtol=1.000000e-02, atol=1.000000e-02 (mismatch 16.666667%).
Location of maximum error: (1, 2, 2, 0), a=1078269824.00000000, b=1089788928.00000000
 ACTUAL: array([[[[ 5.3463602e-03, -8.9685610e-03,  8.1861289e-03],
         [-2.5475242e-03,  4.2734919e-03, -3.9006653e-03],
         [-4.5920177e-03,  7.7031455e-03, -7.0311106e-03]],...
 DESIRED: array([[[[ 5.34636294e-03, -8.96856468e-03,  8.18613265e-03],
         [-2.54752557e-03,  4.27349377e-03, -3.90066742e-03],
         [-4.59202053e-03,  7.70314969e-03, -7.03111431e-03]],...
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=639317673 to reproduce.
root: INFO: NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in the official NumPy library. Please DO NOT manually deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.120s

FAILED (failures=1)
```
@vexilligera

**Comment by vexilligera** [comment]
WIP #16782

**Comment by szha** [comment]
still occurs. http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-gpu/branches/PR-18146/runs/36/nodes/416/steps/481/log/?start=0

added retry
