### ISSUE TITLE
Flaky test: test_higher_order_grad.test_arctanh

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#16839]
```
======================================================================

FAIL: test_higher_order_grad.test_arctanh

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_higher_order_grad.py", line 198, in test_arctanh

    check_second_order_unary(array, arctanh, grad_grad_op)

  File "/work/mxnet/tests/python/unittest/test_higher_order_grad.py", line 395, in check_second_order_unary

    check_nth_order_unary(x, op, grad_grad_op, 2, rtol, atol)

  File "/work/mxnet/tests/python/unittest/test_higher_order_grad.py", line 465, in check_nth_order_unary

    expected_grad, computed_grad.asnumpy(), rtol=rtol, atol=atol)

  File "/work/mxnet/python/mxnet/test_utils.py", line 627, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error nan exceeds tolerance rtol=1.000000e-05, atol=1.000000e-20 (mismatch 0.028935%).

Location of maximum error: (6, 6, 6, 1), a=-0.00000000, b=nan

 ACTUAL: array([[[[      0.92216814,   42981.31      ,      -0.14711247,

                5.1257977 ,       0.2521    ,      -0.17135271],

         [     -3.5826879 ,      -0.06391244,       0.03326308,...

 DESIRED: array([[[[      0.9221682 ,   42981.305     ,      -0.14711247,

                5.1257977 ,       0.25210005,      -0.17135271],

         [     -3.5826879 ,      -0.06391244,       0.03326308,...

-------------------- >> begin captured stdout << ---------------------
```

**Comment by haojin2** [comment]
Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-17009/3/pipeline/
```
======================================================================

FAIL: test_higher_order_grad.test_arctanh

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/work/mxnet/tests/python/unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/unittest/test_higher_order_grad.py", line 198, in test_arctanh

    check_second_order_unary(array, arctanh, grad_grad_op)

  File "/work/mxnet/tests/python/unittest/test_higher_order_grad.py", line 395, in check_second_order_unary

    check_nth_order_unary(x, op, grad_grad_op, 2, rtol, atol)

  File "/work/mxnet/tests/python/unittest/test_higher_order_grad.py", line 465, in check_nth_order_unary

    expected_grad, computed_grad.asnumpy(), rtol=rtol, atol=atol)

  File "/work/mxnet/python/mxnet/test_utils.py", line 627, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error nan exceeds tolerance rtol=1.000000e-05, atol=1.000000e-20 (mismatch 0.038580%).

Location of maximum error: (2, 8, 1, 5), a=0.00000000, b=nan

 ACTUAL: array([[[[      0.04066466,       0.01017862,      -6.5744696 , ...,

                0.99959856,      -0.24153744,      -0.03027739],

         [      0.00564343,       0.2744963 ,     -26.959145  , ...,...

 DESIRED: array([[[[      0.04066466,       0.01017862,      -6.5744686 , ...,

                0.9995985 ,      -0.24153744,      -0.03027739],

         [      0.00564343,       0.2744963 ,     -26.959148  , ...,...

-------------------- >> begin captured stdout << ---------------------



*** Maximum errors for vector of size 2592:  rtol=1e-05, atol=1e-20



  1: Error nan  Location of error: (2, 8, 1, 5), a=0.00000000, b=nan



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1499809122 to reproduce.

--------------------- >> end captured logging << ---------------------
```
