### ISSUE TITLE
[Numpy] expands_dims cannot suport scalar

### ISSUE THREAD

**Issue by stu1130** [apache/incubator-mxnet#16833]
build from source with codebase as of today

build flag:
```
cmake -GNinja -DUSE_CUDA=OFF -DBLAS=apple -DUSE_OPENCV=ON -DCMAKE_CXX_COMPILER_LAUNCHER=/usr/local/opt/ccache/bin/ccache -DCMAKE_C_COMPILER_LAUNCHER=/usr/local/opt/ccache/bin/ccache -DUSE_MKLDNN=ON -DUSE_OPENMP=OFF -DCMAKE_BUILD_TYPE=DEBUG ..
```

```
>>> from mxnet import npx, np
>>> npx.set_np()
>>> a = np.array(1)
>>> np.expand_dims(a, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/leecheng/workspace/incubator-mxnet/python/mxnet/numpy/multiarray.py", line 916, in __repr__
    array_str = self.asnumpy().__repr__()
  File "/Users/leecheng/workspace/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 2549, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/Users/leecheng/workspace/incubator-mxnet/python/mxnet/base.py", line 255, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:49:23] ../src/ndarray/ndarray.cc:487: MKLDNN doesn't support 0 dimensions
Stack trace:
  [bt] (0) 1   libmxnet.dylib                      0x00000001170fe729 dmlc::LogMessageFatal::~LogMessageFatal() + 57
  [bt] (1) 2   libmxnet.dylib                      0x000000011739ee8f mxnet::NDArray::Chunk::SetMKLMem(mxnet::TShape const&, int) + 511
  [bt] (2) 3   libmxnet.dylib                      0x000000011739fa15 mxnet::NDArray::GetMKLDNNData() const + 789
  [bt] (3) 4   libmxnet.dylib                      0x0000000117a57ebc mxnet::op::MKLDNNReshapeFwd::MKLDNNReshapeFwd(mxnet::OpReqType const&, mxnet::NDArray const&, mxnet::NDArray const&) + 140
  [bt] (4) 5   libmxnet.dylib                      0x0000000117a596cd mxnet::op::GetReshapeForward(mxnet::OpReqType const&, mxnet::NDArray const&, mxnet::NDArray const&) + 237
  [bt] (5) 6   libmxnet.dylib                      0x0000000117a5a6ed mxnet::op::MKLDNNReshapeForward(nnvm::NodeAttrs const&, mxnet::OpContext const&, mxnet::NDArray const&, mxnet::OpReqType const&, mxnet::NDArray const&) + 1005
  [bt] (6) 7   libmxnet.dylib                      0x00000001195d378d mxnet::op::ExpandDimEx(nnvm::NodeAttrs const&, mxnet::OpContext const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&) + 589
  [bt] (7) 8   libmxnet.dylib                      0x00000001172bc708 mxnet::imperative::PushFComputeEx(std::__1::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::__1::vector<mxnet::engine::Var*, std::__1::allocator<mxnet::engine::Var*> > const&, std::__1::vector<mxnet::engine::Var*, std::__1::allocator<mxnet::engine::Var*> > const&, std::__1::vector<mxnet::Resource, std::__1::allocator<mxnet::Resource> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&)::'lambda'(mxnet::RunContext)::operator()(mxnet::RunContext) const + 584
  [bt] (8) 9   libmxnet.dylib                      0x00000001172bcfcd std::__1::__function::__func<mxnet::imperative::PushFComputeEx(std::__1::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::__1::vector<mxnet::engine::Var*, std::__1::allocator<mxnet::engine::Var*> > const&, std::__1::vector<mxnet::engine::Var*, std::__1::allocator<mxnet::engine::Var*> > const&, std::__1::vector<mxnet::Resource, std::__1::allocator<mxnet::Resource> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&)::'lambda'(mxnet::RunContext), std::__1::allocator<mxnet::imperative::PushFComputeEx(std::__1::function<void (nnvm::NodeAttrs const&, mxnet::OpContext const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&)> const&, nnvm::Op const*, nnvm::NodeAttrs const&, mxnet::Context const&, std::__1::vector<mxnet::engine::Var*, std::__1::allocator<mxnet::engine::Var*> > const&, std::__1::vector<mxnet::engine::Var*, std::__1::allocator<mxnet::engine::Var*> > const&, std::__1::vector<mxnet::Resource, std::__1::allocator<mxnet::Resource> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::NDArray*, std::__1::allocator<mxnet::NDArray*> > const&, std::__1::vector<mxnet::OpReqType, std::__1::allocator<mxnet::OpReqType> > const&)::'lambda'(mxnet::RunContext)>, void (mxnet::RunContext)>::operator()(mxnet::RunContext&&) + 29

```

**Comment by reminisce** [comment]
@PatricZhao

**Comment by wuxun-zhang** [comment]
@stu1130 @reminisce Thanks for reporting this issue. I can reproduce this from my side. I just figured out the root cause, when input's ndim is 0, it should not execute MKL-DNN pass. Anyway, I will submit a PR to fix this issue soon. Sorry for any inconvenience. @pengzhao-intel 

Also tested below input, and no error.
```
>>> a = np.array([1])
>>> np.expand_dims(a, 0)
mkldnn_verbose,info,Intel MKL-DNN v1.0.4 (commit a0a87d662edeef38d01db4ac5dd25f59a1f0881f)
mkldnn_verbose,info,Detected ISA is Intel AVX-512 with Intel DL Boost
mkldnn_verbose,exec,cpu,reorder,simple:any,undef,src_f32::blocked:a:f0 dst_f32::blocked:a:f0,num:1,1,11.0342
array([[1.]])
>>>
```

**Comment by wuxun-zhang** [comment]
@stu1130 PR#16837 is filed. Please help check if it fix this issue. Thanks.
