### ISSUE TITLE
CI error in unix gpu test_quantization_gpu.test_quantized_conv

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#16830]
more details

http://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/unix-cpu/branches/PR-16810/runs/6/nodes/300/steps/700/log/?start=0
```
FAIL: test_quantization_mkldnn.test_quantized_conv
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/nose/util.py", line 620, in newfunc
    return func(*arg, **kw)
  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new
    orig_test(*args, **kwargs)
  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 277, in test_quantized_conv
    check_quantized_conv((3, 4, 28, 28), (3, 3), 128, (1, 1), (1, 1), False, qdtype)
  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 273, in check_quantized_conv
    assert cond == 0
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet
skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=752964439 to reproduce.
--------------------- >> end captured logging << ---------------------
```

**Comment by pengzhao-intel** [comment]
@xinyu-intel could you help take a look ?

**Comment by haojin2** [comment]
Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-16862/7/pipeline/299
```
======================================================================

FAIL: test_quantization_mkldnn.test_quantized_conv

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/usr/local/lib/python3.5/dist-packages/nose/util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 277, in test_quantized_conv

    check_quantized_conv((3, 4, 28, 28), (3, 3), 128, (1, 1), (1, 1), False, qdtype)

  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 273, in check_quantized_conv

    assert cond == 0

AssertionError: 

-------------------- >> begin captured stdout << ---------------------

skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet

skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=139132436 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by ChaiBapchya** [comment]
Happening again 
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-16894/9/pipeline
#16894

**Comment by haojin2** [comment]
Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/master/1325/pipeline
```

======================================================================

FAIL: test_quantization_mkldnn.test_quantized_conv

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/usr/local/lib/python3.5/dist-packages/nose/util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 277, in test_quantized_conv

    check_quantized_conv((3, 4, 28, 28), (3, 3), 128, (1, 1), (1, 1), False, qdtype)

  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 273, in check_quantized_conv

    assert cond == 0

AssertionError: 

-------------------- >> begin captured stdout << ---------------------

skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet

skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet
```
@xinyu-intel @PatricZhao Anyone could take a look?

**Comment by pengzhao-intel** [comment]
> Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/master/1325/pipeline
> 
> ```
> 
> ======================================================================
> 
> FAIL: test_quantization_mkldnn.test_quantized_conv
> 
> ----------------------------------------------------------------------
> 
> Traceback (most recent call last):
> 
>   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
> 
>     self.test(*self.arg)
> 
>   File "/usr/local/lib/python3.5/dist-packages/nose/util.py", line 620, in newfunc
> 
>     return func(*arg, **kw)
> 
>   File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new
> 
>     orig_test(*args, **kwargs)
> 
>   File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 277, in test_quantized_conv
> 
>     check_quantized_conv((3, 4, 28, 28), (3, 3), 128, (1, 1), (1, 1), False, qdtype)
> 
>   File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 273, in check_quantized_conv
> 
>     assert cond == 0
> 
> AssertionError: 
> 
> -------------------- >> begin captured stdout << ---------------------
> 
> skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet
> 
> skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet
> ```
> 
> @xinyu-intel @PatricZhao Anyone could take a look?

Yes, @xinyu-intel is looking for this and the PR is under the testing.

**Comment by pengzhao-intel** [comment]
https://github.com/apache/incubator-mxnet/pull/16866

**Comment by haojin2** [comment]
Happening again: http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-17016/1/pipeline
```

======================================================================

FAIL: test_quantization_mkldnn.test_quantized_conv

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

    self.test(*self.arg)

  File "/usr/local/lib/python3.5/dist-packages/nose/util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 277, in test_quantized_conv

    check_quantized_conv((3, 4, 28, 28), (3, 3), 128, (1, 1), (1, 1), False, qdtype)

  File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 273, in check_quantized_conv

    assert cond == 0

AssertionError: 

-------------------- >> begin captured stdout << ---------------------

skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet

skipped testing quantized_conv for mkldnn cpu int8 since it is not supported yet



--------------------- >> end captured stdout << ----------------------

-------------------- >> begin captured logging << --------------------

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1860264925 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by pengzhao-intel** [comment]
skip the test now and please merge the code.

**Comment by TaoLv** [comment]
Closed via https://github.com/apache/incubator-mxnet/pull/16866
