### ISSUE TITLE
Flaky Test: test_operator_gpu.test_np_linalg_svd

### ISSUE THREAD

**Issue by haojin2** [apache/incubator-mxnet#16842]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-16800/7/pipeline
```
======================================================================

ERROR: test_operator_gpu.test_np_linalg_svd

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\Python27\lib\site-packages\nose\util.py", line 620, in newfunc

    return func(*arg, **kw)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\common.py", line 177, in test_new

    orig_test(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\util.py", line 315, in _with_np_shape

    return func(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\util.py", line 499, in _with_np_array

    return func(*args, **kwargs)

  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\gpu\../unittest\test_numpy_op.py", line 3089, in test_np_linalg_svd

    UT = ret[0].asnumpy()

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\ndarray\ndarray.py", line 2549, in asnumpy

    ctypes.c_size_t(data.size)))

  File "C:\jenkins_slave\workspace\ut-python-gpu\windows_package\python\mxnet\base.py", line 255, in check_call

    raise MXNetError(py_str(_LIB.MXGetLastError()))

MXNetError: [10:16:12] c:\jenkins_slave\workspace\build-gpu\include\mxnet\tuple.h:390: Check failed: ndim >= -1 (-1135578640 vs. -1) : shape ndim must be >= -1, while received -1135578640

-------------------- >> begin captured logging << --------------------

root: INFO: NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in 

the official NumPy library. Please DO NOT manually deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.

common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=1278795976 to reproduce.

--------------------- >> end captured logging << ---------------------
```

**Comment by haojin2** [comment]
Not a flaky test, closing now.
