### ISSUE TITLE
[Numpy] additional default parameter for mxnet.numpy.max: axis=-1 

### ISSUE THREAD

**Issue by Alicia1529** [apache/incubator-mxnet#17011]
Max operator in official numpy can support argument axis=-1 and return max value from its last dimension. Wonder if deepnumpy can support this argument.
```
>>> import numpy as _np
>>> help(_np.max)

>>> from mxnet import numpy as np
>>> import numpy as _np
>>> a = np.arange(10).reshape(2,5)
>>> b = _np.arange(10).reshape(2,5)
>>> a
array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])
>>> b
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
>>> _np.max(b, axis=-1)
array([4, 9])
>>> np.max(a, axis=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 44, in max
  File "/Users/luoting/Desktop/mxnet/python/mxnet/_ctypes/ndarray.py", line 107, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/Users/luoting/Desktop/mxnet/python/mxnet/base.py", line 278, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:03:00] include/mxnet/tuple.h:220: Check failed: i >= 0 && i < ndim(): index = -1 must be in range [0, 2)
```

**Comment by xidulu** [comment]
Looks like the problem occurs in this line
https://github.com/apache/incubator-mxnet/blob/9b25db05b4de18b5bfed8467cfd934f2bfa4f11a/src/operator/numpy/np_broadcast_reduce_op.h#L190

I guess an additional check for bypassing the access to ishape tuple (`ishape[axes[i]]`) may solve the problem.

**Comment by haojin2** [comment]
PR merged, closing
