### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'MXNDArrayFree'

### ISSUE THREAD

**Issue by hnuhchen** [apache/incubator-mxnet#17033]
## Description
(A clear and concise description of what the bug is.)

Hello, i am using Cython to generate dynamic library files of mxnet project. But if i run my project through these dymanic library files, the problem AttributeError: 'NoneType' object has no attribute 'MXNDArrayFree' sometimes occurs, exactly the problem does not always come up.  It is strange that the problem comes up after all my code was executed.

Cython version 0.29.14
python version 3.5.2
mxnet version 1.5.1.post0

### Error Message
(Paste the complete error message, including stack trace.)

Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mxnet/_ctypes/ndarray.py", line 51, in __del__
AttributeError: 'NoneType' object has no attribute 'MXNDArrayFree'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mxnet/_ctypes/ndarray.py", line 51, in __del__
AttributeError: 'NoneType' object has no attribute 'MXNDArrayFree'
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mxnet/_ctypes/ndarray.py", line 51, in __del__
AttributeError: 'NoneType' object has no attribute 'MXNDArrayFree'

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by sxjscience** [comment]
@hnuhchen Thanks for submitting the issue. Is it possible to post a minimal reproducible example? That will help us solve the problem.
