### ISSUE TITLE
Seg Fault on dot product of sparse matrix with dense matrix

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#17182]
## Description
Seg Fault on master, 1.5.1

### Error Message
```
Segmentation fault: 11

Stack trace:
  [bt] (0) /home/ubuntu/anaconda3/envs/mxnet_pip_install/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2b64150) [0x7fadfffb3150]
  [bt] (1) /lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7fae14b354b0]
  [bt] (2) /home/ubuntu/anaconda3/envs/mxnet_pip_install/lib/python3.6/site-packages/mxnet/libmxnet.so(+0xf509a0) [0x7fadfe39f9a0]
  [bt] (3) /home/ubuntu/anaconda3/envs/mxnet_pip_install/bin/../lib/libgomp.so.1(+0x146d5) [0x7fae110456d5]
  [bt] (4) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fae14ed16ba]
  [bt] (5) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fae14c0741d]
```
## To Reproduce
```
import mxnet as mx
shape = (2,10)
from mxnet import nd
sp_mat1 = nd.sparse.csr_matrix(([2],[6],[0,1]),shape=shape)
mat2 = nd.ones((10,2))
out = nd.dot(sp_mat1, mat2)
```

### Steps to reproduce

1. pip install mxnet
2. python shell

## What have you tried to solve it?

1. Use gdb to find backtrace
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by ChaiBapchya** [comment]
Oh okay. So another way of creating sparse matrix is first create scipy.sparse matrix and then convert it to mxnet.
Scipy sparse matrix creation revealed the true error

```
>>> c = spsp.csr.csr_matrix((np.array([2]),np.array([6]),np.array([0,1])), shape=shape)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/conda_sparse/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 108, in __init__
    self.check_format(full_check=False)
  File "/home/ubuntu/anaconda3/envs/conda_sparse/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 172, in check_format
    "".format(len(self.indptr), major_dim + 1))
ValueError: index pointer size (2) should be (3)
```

So the error handling / messaging can be done better on MXNet side.

**Comment by ChaiBapchya** [comment]
TODO: Add a check during sparse matrix creation to ensure index array size corresponds to the shape of array creation

**Comment by samskalicky** [comment]
@apeforest assign [@ChaiBapchya ]
