### ISSUE TITLE
Flaky test: test_numpy_op.test_npi_boolean_assign

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#17219]
## Description
test_numpy_op.test_npi_boolean_assign

## Occurrences
```
MXNET_TEST_SEED=952277814 nosetests -s -v test_numpy_op:test_npi_boolean_assign
test_numpy_op.test_npi_boolean_assign ... [INFO] Setting test np/mx/python random seeds, use MXNET_TEST_SEED=952277814 to reproduce.
((3, 4), (3, 4), 0)
((3, 0), (3, 0), 0)
((), (), 0)
((2, 3, 4, 5), (2, 3), 0)
ERROR

======================================================================
ERROR: test_numpy_op.test_npi_boolean_assign
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lvtao/miniconda3/envs/mxnet/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/lvtao/Workspace/mxnet-official/tests/python/unittest/common.py", line 221, in test_new
    orig_test(*args, **kwargs)
  File "/home/lvtao/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/util.py", line 321, in _with_np_shape
    return func(*args, **kwargs)
  File "/home/lvtao/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/util.py", line 505, in _with_np_array
    return func(*args, **kwargs)
  File "/home/lvtao/Workspace/mxnet-official/tests/python/unittest/test_numpy_op.py", line 1327, in test_npi_boolean_assign
    np_data[np_mask, :, :] = val
ValueError: shape mismatch: value array of shape (0,) could not be broadcast to indexing result of shape (0,4,5)
-------------------- >> begin captured logging << --------------------
common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=952277814 to reproduce.
root: INFO: NumPy-shape semantics has been activated in your code. This is required for creating and manipulating scalar and zero-size tensors, which were not supported in MXNet before, as in the official NumPy library. Please DO NOT manually deactivate this semantics while using `mxnet.numpy` and `mxnet.numpy_extension` modules.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.052s

FAILED (errors=1)
```

## What have you tried to solve it?
None

**Comment by TaoLv** [comment]
@haojin2 @reminisce FYI.

**Comment by reminisce** [comment]
@Alicia1529

**Comment by haojin2** [comment]
@TaoLv This is actually hitting a case not supported by np, I think we should remove that case from that unit test, as what I've done in #17131 .
@Alicia1529  @reminisce
