### ISSUE TITLE
[Numpy] np.broadcast_to does not support scalar as input

### ISSUE THREAD

**Issue by xidulu** [apache/incubator-mxnet#17223]
## Description
As title

```python
>>> import numpy as onp
>>> onp.broadcast_to(1.0, (2,2))
array([[1., 1.],
       [1., 1.]])
>>> from mxnet import np, npx
>>> npx.set_np()
>>> np.broadcast_to(1.0, (2,2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 25, in broadcast_to
AssertionError: Argument array must have NDArray type, but got 1.0
```

**Comment by haojin2** [comment]
PR merged, closing
