### ISSUE TITLE
Error in mkldnn unit test

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#17352]
## Description
When I ran nosetests -v tests/python/mkl/test_mkldnn.py, all the tests passed. 
If I ran nosetests -v tests/python/mkl/test_mkldnn.py:test_mkldnn_engine_threading, it failed with 
```
test_mkldnn.test_mkldnn_engine_threading ... ERROR

======================================================================
ERROR: test_mkldnn.test_mkldnn_engine_threading
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/mxnet/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/ubuntu/src/mxnet/tests/python/mkl/test_mkldnn.py", line 98, in test_mkldnn_engine_threading
    assert_almost_equal(y[0, 0, 0, 0], np.array(0.016711406))
  File "/home/ubuntu/src/mxnet/python/mxnet/test_utils.py", line 610, in assert_almost_equal
    aTmp[index] = bTmp[index] = 0
TypeError: 'numpy.float32' object does not support item assignment
-------------------- >> begin captured stdout << ---------------------

*** Maximum errors for vector of size 1:  rtol=1e-05, atol=1e-20

  1: Error 1920385.369517  Location of error: (), a=0.33763480, b=0.01671141

--------------------- >> end captured stdout << ----------------------
```
## To Reproduce
nosetests -v tests/python/mkl/test_mkldnn.py:test_mkldnn_engine_threading

**Comment by apeforest** [comment]
@PatricZhao @TaoLv Did you encounter this before? Thanks

**Comment by TaoLv** [comment]
Yes, we're aware of this problem as in our local validation system, python tests are split into single run for each test. We didn't dive into the problem as we thought it's a problem of nosetests or how the nosetests file is implemented. I remember these was an similar issue but cannot find it anymore.

**Comment by TaoLv** [comment]
@juliusshufan
