### ISSUE TITLE
1.5.x branch fails with numpy.decorator issue

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#17398]
## Description
Numpy.decorator module not found
#17286 
### Error Message
```
======================================================================

ERROR: Failure: ModuleNotFoundError (No module named 'numpy.testing.decorators')

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest

    raise self.exc_val.with_traceback(self.tb)

  File "/usr/local/lib/python3.6/site-packages/nose/loader.py", line 418, in loadTestsFromName

    addr.filename, addr.module)

  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath

    return self.importFromDir(dir_path, fqname)

  File "/usr/local/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir

    mod = load_module(part_fqname, fh, filename, desc)

  File "/usr/lib64/python3.6/imp.py", line 235, in load_module

    return load_source(name, filename, file)

  File "/usr/lib64/python3.6/imp.py", line 172, in load_source

    module = _load(spec)

  File "<frozen importlib._bootstrap>", line 684, in _load

  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 678, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/work/mxnet/tests/python/gpu/test_operator_gpu.py", line 39, in <module>

    from test_random import *

  File "/work/mxnet/tests/python/gpu/../unittest/test_random.py", line 26, in <module>

    import scipy.stats as ss

  File "/usr/local/lib64/python3.6/site-packages/scipy/stats/__init__.py", line 345, in <module>

    from .morestats import *

  File "/usr/local/lib64/python3.6/site-packages/scipy/stats/morestats.py", line 12, in <module>

    from numpy.testing.decorators import setastest

ModuleNotFoundError: No module named 'numpy.testing.decorators'
```
## To Reproduce

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-17286/1/pipeline

**Comment by haojin2** [comment]
#17426 has been merged, I think this should be resolved. Feel free to reopen if errors still are present.
