### ISSUE TITLE
"Slice end index out of range" error , using io.ImageRecord and CNN

### ISSUE THREAD

**Issue by AlexZhou1995** [apache/incubator-mxnet#1743]
I use `make_list.py` and `im2rec.py` to generate .rec file for my data.
And then run the code below

``` python
import mxnet as mx
import argparse
import os, sys
#import train_model
import scipy.io as sio
import numpy as np

def get_lenet():

    data = mx.symbol.Variable('data')
    # first conv
    conv1 = mx.symbol.Convolution(data=data, kernel=(5,5), num_filter=20)
    tanh1 = mx.symbol.Activation(data=conv1, act_type="tanh")
    pool1 = mx.symbol.Pooling(data=tanh1, pool_type="max",
                              kernel=(2,2), stride=(2,2))
    # second conv
    conv2 = mx.symbol.Convolution(data=pool1, kernel=(4,4), num_filter=50)
    tanh2 = mx.symbol.Activation(data=conv2, act_type="tanh")
    pool2 = mx.symbol.Pooling(data=tanh2, pool_type="max",
                              kernel=(2,2), stride=(2,2))
    # 3rd conv
    conv3 = mx.symbol.Convolution(data=pool1, kernel=(5,5), num_filter=50)
    tanh3 = mx.symbol.Activation(data=conv2, act_type="tanh")
    pool3 = mx.symbol.Pooling(data=tanh2, pool_type="max",
                              kernel=(2,2), stride=(2,2))
    # first fullc
    flatten = mx.symbol.Flatten(data=pool3)
    fc1 = mx.symbol.FullyConnected(data=flatten, num_hidden=500)
    tanh4 = mx.symbol.Activation(data=fc1, act_type="tanh")
    # second fullc
    fc2 = mx.symbol.FullyConnected(data=tanh4, num_hidden=2)
    # loss
    lenet = mx.symbol.SoftmaxOutput(data=fc2, name='softmax')
    return lenet

if __name__ == '__main__':
    net = get_lenet()

    # train
    train           = mx.io.ImageRecordIter(
        path_imgrec = "/Users/handwin/Desktop/playground/pythonCNN/Data/train.rec",
        data_shape  = (1,50,50),
        batch_size  = 43)
    test            = mx.io.ImageRecordIter(
        path_imgrec = "/Users/handwin/Desktop/playground/pythonCNN/Data/test.rec",
        data_shape  = (1,50,50),
        batch_size  = 13)

    model = mx.model.FeedForward(
        ctx = mx.cpu(), symbol = net, num_epoch = 20,
        learning_rate = 0.1, momentum = 0.9, wd = 0.00001)
    model.fit(X=train, eval_data=test)
#train_model.fit(args, net, get_iterator(data_shape))
```

it show me a error as follow:

```
[10:34:04] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: /Users/handwin/Desktop/playground/pythonCNN/Data/train.rec, use 1 threads for decoding..
[10:34:05] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: /Users/handwin/Desktop/playground/pythonCNN/Data/test.rec, use 1 threads for decoding..
[10:35:12] /Users/handwin/Desktop/mxnet/dmlc-core/include/dmlc/logging.h:245: [10:35:12] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range
Traceback (most recent call last):
  File "AlexNet.py", line 91, in <module>
    model.fit(X=train, eval_data=test)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 770, in fit
    sym_gen=self.sym_gen)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 294, in _train_multi_device
    executor_manager.load_data_batch(eval_batch)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 381, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 232, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 86, in _load_data
    _load_general(batch.data, targets)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 82, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 236, in __getitem__
    return self._slice(in_slice.start, in_slice.stop)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 276, in _slice
    self.handle, start, stop, ctypes.byref(handle)))
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:35:12] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range
```

I have converted images to Gray Scale Image before I use `im2rec.py`, so I think data_shape should be (1,50,50)  (Actually, I tried (3,50,50), same error)

**Comment by TohnoSakuya** [comment]
I modified `train_cifar10.py` and use it to deal with my own data
It works for a while.....then show me the same error.

log:
```
2016-03-29 15:05:16,323 Node[0] start with arguments Namespace(batch_size=43, data_dir='/Users/handwin/Desktop/playground/pythonCNN/Data/', gpus=None, kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network=None, num_epochs=20, num_examples=4300, save_model_prefix=None)
[15:05:16] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: /Users/handwin/Desktop/playground/pythonCNN/Data/train.rec, use 1 threads for decoding..
[15:05:16] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: /Users/handwin/Desktop/playground/pythonCNN/Data/test.rec, use 1 threads for decoding..
2016-03-29 15:05:16,842 Node[0] Start training with [cpu(0)]
2016-03-29 15:05:49,256 Node[0] Epoch[0] Batch [50]	Speed: 67.76 samples/sec	Train-accuracy=0.609767
2016-03-29 15:05:49,256 Node[0] Epoch[0] Batch [50]	Speed: 67.76 samples/sec	Train-top_k_accuracy_5=1.000000
2016-03-29 15:05:49,256 Node[0] Epoch[0] Batch [50]	Speed: 67.76 samples/sec	Train-top_k_accuracy_10=1.000000
2016-03-29 15:05:49,256 Node[0] Epoch[0] Batch [50]	Speed: 67.76 samples/sec	Train-top_k_accuracy_20=1.000000
2016-03-29 15:06:18,566 Node[0] Epoch[0] Batch [100]	Speed: 73.35 samples/sec	Train-accuracy=0.615349
2016-03-29 15:06:18,567 Node[0] Epoch[0] Batch [100]	Speed: 73.35 samples/sec	Train-top_k_accuracy_5=1.000000
2016-03-29 15:06:18,567 Node[0] Epoch[0] Batch [100]	Speed: 73.35 samples/sec	Train-top_k_accuracy_10=1.000000
2016-03-29 15:06:18,567 Node[0] Epoch[0] Batch [100]	Speed: 73.35 samples/sec	Train-top_k_accuracy_20=1.000000
2016-03-29 15:06:18,607 Node[0] Epoch[0] Resetting Data Iterator
2016-03-29 15:06:18,607 Node[0] Epoch[0] Train-accuracy=0.615349
2016-03-29 15:06:18,607 Node[0] Epoch[0] Train-top_k_accuracy_5=1.000000
2016-03-29 15:06:18,608 Node[0] Epoch[0] Train-top_k_accuracy_10=1.000000
2016-03-29 15:06:18,608 Node[0] Epoch[0] Train-top_k_accuracy_20=1.000000
2016-03-29 15:06:18,608 Node[0] Epoch[0] Time cost=61.761
[15:06:18] /Users/handwin/Desktop/mxnet/dmlc-core/include/dmlc/logging.h:245: [15:06:18] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range
Traceback (most recent call last):
  File "MLPNet.py", line 98, in <module>
    train_model.fit(args, net, get_iterator)
  File "/Users/handwin/Desktop/playground/pythonCNN/train_model.py", line 99, in fit
    epoch_end_callback = checkpoint)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 770, in fit
    sym_gen=self.sym_gen)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 294, in _train_multi_device
    executor_manager.load_data_batch(eval_batch)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 381, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 232, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 86, in _load_data
    _load_general(batch.data, targets)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 82, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 236, in __getitem__
    return self._slice(in_slice.start, in_slice.stop)
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 276, in _slice
    self.handle, start, stop, ctypes.byref(handle)))
  File "/Users/handwin/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:06:18] include/mxnet/ndarray.h:230: Check failed: (shape_[0]) >= (end) Slice end index out of range

```
