### ISSUE TITLE
test_gluon_model_zoo.test_parallel_download IO error

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#17436]
## Description
Python 2 : GPU Win
Unrelated PR #16722

Error log (brief)
```
Downloading ./parallel_download\mobilenetv2_0.25-ae8f9392.zip7251db52-2879-49fd-8e29-53861b5f8e3c from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/mobilenetv2_0.25-ae8f9392.zip...
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 267, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\../unittest\test_gluon_model_zoo.py", line 54, in parallel_download
    model = get_model(model_name, pretrained=True, root='./parallel_download')
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\../../../python\mxnet\gluon\model_zoo\vision\__init__.py", line 152, in get_model
    return models[name](**kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\../../../python\mxnet\gluon\model_zoo\vision\mobilenet.py", line 375, in mobilenet_v2_0_25
    return get_mobilenet_v2(0.25, **kwargs)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\../../../python\mxnet\gluon\model_zoo\vision\mobilenet.py", line 250, in get_mobilenet_v2
    get_model_file('mobilenetv2_%s' % version_suffix, root=root), ctx=ctx)
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\../../../python\mxnet\gluon\model_zoo\model_store.py", line 125, in get_model_file
    if check_sha1(file_path, sha1_hash):
  File "C:\jenkins_slave\workspace\ut-python-gpu\tests\python\unittest\../../../python\mxnet\gluon\utils.py", line 188, in check_sha1
    with open(filename, 'rb') as f:
IOError: [Errno 13] Permission denied: './parallel_download\\mobilenetv2_0.25-ae8f9392.params'
```

Detailed - http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-16722/4/pipeline

**Comment by leezu** [comment]
CC @eric-haibin-lin

**Comment by eric-haibin-lin** [comment]
related: https://github.com/apache/incubator-mxnet/pull/17098#issuecomment-571439534
