### ISSUE TITLE
unix-cpu lib_tvm.so file too short

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#17504]
## Description
lib_tvm.so file too short

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Funix-cpu/detail/PR-17494/3/pipeline/

Unrelated PR #17494 

### Error Message
```
Traceback (most recent call last):

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/contrib/tvmop/compile.py", line 20, in <module>

[2020-01-31T23:26:15.355Z]     import tvm

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/3rdparty/tvm/python/tvm/__init__.py", line 27, in <module>

[2020-01-31T23:26:15.355Z]     from . import tensor

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/3rdparty/tvm/python/tvm/tensor.py", line 20, in <module>

[2020-01-31T23:26:15.355Z]     from ._ffi.node import NodeBase, NodeGeneric, register_node, convert_to_node

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/3rdparty/tvm/python/tvm/_ffi/node.py", line 24, in <module>

[2020-01-31T23:26:15.355Z]     from .object import Object, register_object, _set_class_node

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/3rdparty/tvm/python/tvm/_ffi/object.py", line 23, in <module>

[2020-01-31T23:26:15.355Z]     from .base import _FFI_MODE, _RUNTIME_ONLY, check_call, _LIB, c_str

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/3rdparty/tvm/python/tvm/_ffi/base.py", line 60, in <module>

[2020-01-31T23:26:15.355Z]     _LIB, _LIB_NAME = _load_lib()

[2020-01-31T23:26:15.355Z]   File "/work/mxnet/3rdparty/tvm/python/tvm/_ffi/base.py", line 52, in _load_lib

[2020-01-31T23:26:15.355Z]     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)

[2020-01-31T23:26:15.355Z]   File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__

[2020-01-31T23:26:15.355Z]     self._handle = _dlopen(self._name, mode)

[2020-01-31T23:26:15.355Z] OSError: /work/build/3rdparty/tvm/libtvm.so: file too short

[2020-01-31T23:26:25.279Z] ninja: build stopped: subcommand failed
```

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [all]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci [all]

**Comment by ChaiBapchya** [comment]
@mxnet-bot run ci all
