### ISSUE TITLE
Window-gpu: [WinError 5] Access is denied: 'C:\\Windows\\TEMP\\tmpfguakubg\\cmake-3.16.1-win64-x64\\bin\\cmake.exe'

### ISSUE THREAD

**Issue by TaoLv** [apache/incubator-mxnet#17558]
## Description
```
[2020-02-10T14:01:25.341Z] Traceback (most recent call last):
[2020-02-10T14:01:25.341Z]   File "ci/build_windows.py", line 273, in <module>
[2020-02-10T14:01:25.341Z]     sys.exit(main())
[2020-02-10T14:01:25.341Z]   File "ci/build_windows.py", line 261, in main
[2020-02-10T14:01:25.341Z]     windows_build(args)
[2020-02-10T14:01:25.341Z]   File "ci/build_windows.py", line 174, in windows_build
[2020-02-10T14:01:25.341Z]     datetime.timedelta(seconds=int(time.time() - t0))))
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\tempfile.py", line 805, in __exit__
[2020-02-10T14:01:25.341Z]     self.cleanup()
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\tempfile.py", line 809, in cleanup
[2020-02-10T14:01:25.341Z]     _shutil.rmtree(self.name)
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\shutil.py", line 513, in rmtree
[2020-02-10T14:01:25.341Z]     return _rmtree_unsafe(path, onerror)
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\shutil.py", line 392, in _rmtree_unsafe
[2020-02-10T14:01:25.341Z]     _rmtree_unsafe(fullname, onerror)
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\shutil.py", line 392, in _rmtree_unsafe
[2020-02-10T14:01:25.341Z]     _rmtree_unsafe(fullname, onerror)
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\shutil.py", line 397, in _rmtree_unsafe
[2020-02-10T14:01:25.341Z]     onerror(os.unlink, fullname, sys.exc_info())
[2020-02-10T14:01:25.341Z]   File "C:\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
[2020-02-10T14:01:25.341Z]     os.unlink(fullname)
[2020-02-10T14:01:25.341Z] PermissionError: [WinError 5] Access is denied: 'C:\\Windows\\TEMP\\tmpfguakubg\\cmake-3.16.1-win64-x64\\bin\\cmake.exe'
```

## Occurrences
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fwindows-gpu/detail/PR-17318/8/pipeline/

## What have you tried to solve it?
None

**Comment by leezu** [comment]
This issue occurs due to a workaround for the outdated Windows AMI (not updated as per https://github.com/apache/incubator-mxnet-ci).
@josephevans and @larroy are working on updating the Windows AMI.
