### ISSUE TITLE
mp_lamb_update float32 input type inconsistent issue

### ISSUE THREAD

**Issue by ChaiBapchya** [apache/incubator-mxnet#17568]
## Description
Upon passing all the inputs as float32, it incorrectly infers as float16.

```
> nd.mp_lamb_update_phase1(weight=weight,grad=nd.random_normal(shape=(5,5)),mean=nd.random_normal(shape=(5,5)),var=nd.random_normal(shape=(5,5)),weight32=weight,t=1,wd=0.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 120, in mp_lamb_update_phase1
  File "/home/ubuntu/incubator-mxnet/python/mxnet/_ctypes/ndarray.py", line 107, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/home/ubuntu/incubator-mxnet/python/mxnet/base.py", line 273, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: MXNetError: Type inconsistent, Provided = float32, inferred type = float16
```

**Comment by ChaiBapchya** [comment]
@access2rohit
