### ISSUE TITLE
OSError: /tmp/makepkg/sl1-mxnet-git/src/build/libmxnet.so.1.5.1: undefined symbol: _ZN4dmlc14RecordIOReader10NextRecordEPSs

### ISSUE THREAD

**Issue by sl1pkn07** [apache/incubator-mxnet#17589]
~~~
Scanning dependencies of target cpp_package_op_h
make[2]: Leaving directory '/tmp/makepkg/sl1-mxnet-git/src/build'
make -f cpp-package/CMakeFiles/cpp_package_op_h.dir/build.make cpp-package/CMakeFiles/cpp_package_op_h.dir/build
make[2]: Entering directory '/tmp/makepkg/sl1-mxnet-git/src/build'
cd /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/cpp-package/scripts && echo Running:\ OpWrapperGenerator.py
Running: OpWrapperGenerator.py
cd /tmp/makepkg/sl1-mxnet-git/src/incubator-mxnet/cpp-package/scripts && python OpWrapperGenerator.py /tmp/makepkg/sl1-mxnet-git/src/build/libmxnet.so.1.5.1
Traceback (most recent call last):
  File "OpWrapperGenerator.py", line 433, in <module>
    raise(e)
  File "OpWrapperGenerator.py", line 427, in <module>
    f.write(patternStr % ParseAllOps())
  File "OpWrapperGenerator.py", line 321, in ParseAllOps
    cdll.libmxnet = cdll.LoadLibrary(sys.argv[1])
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/makepkg/sl1-mxnet-git/src/build/libmxnet.so.1.5.1: undefined symbol: _ZN4dmlc14RecordIOReader10NextRecordEPSs
make[2]: *** [cpp-package/CMakeFiles/cpp_package_op_h.dir/build.make:59: cpp-package/CMakeFiles/cpp_package_op_h] Error 1
~~~

linux
python 3.8.1
mxnet f5a1014479351f3139b92c437d65de3a3a653196
gcc 8.3.0, also happen with gcc 9.2.1

**Comment by leezu** [comment]
Please provide full cmake configuration and build logs.

**Comment by sl1pkn07** [comment]
~~~
 cmake ../incubator-mxnet \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_INSTALL_DOCDIR=share/doc/mxnet \
    -DENABLE_CUDA_RTC=ON \
    -DBUILD_SHARED_LIBS=ON \
    -DBUILD_CPP_EXAMPLES=OFF \
    -DUSE_CCACHE=OFF \
    -DUSE_CXX14_IF_AVAILABLE=ON \
    -DUSE_CPP_PACKAGE=ON \
    -DUSE_CUDNN=ON \
    -DUSE_NCCL=ON \
    -DUSE_OPENCV=ON \
    -DUSE_OPENMP=ON \
    -DUSE_MKLDNN=OFF \
    -DUSE_LAPACK=ON \
    -DUSE_JEMALLOC=OFF \
    -DUSE_GPERFTOOLS=OFF \
    -DNCCL_ROOT=/usr \
    -DCUDA_HOST_COMPILER=/usr/bin/cc-8 \
    -DCMAKE_C_COMPILER=/usr/bin/cc-8 \
    -DCMAKE_C_COMPILER_AR=/usr/bin/gcc-ar-8 \
    -DCMAKE_C_COMPILER_RANLIB=/usr/bin/gcc-ranlib-8 \
    -DCMAKE_CXX_COMPILER=/usr/bin/c++-8 \
    -DCMAKE_CXX_COMPILER_AR=/usr/bin/gcc-ar-8 \
    -DCMAKE_CXX_COMPILER_RANLIB=/usr/bin/gcc-ranlib-8
~~~

the build log is too extense

**Comment by leezu** [comment]
Without the build log, it's impossible to advise about the root cause of your issue.

You can attach the file in a comment.

**Comment by sl1pkn07** [comment]
seems fixed

build opencv (with cuda support) and openexr with gcc 8 (instead gcc 9) the error is gone

sorry for the noise

**Comment by aws-taylor** [comment]
```_ZN4dmlc14RecordIOReader10NextRecordEPSs``` corresponds to  ```dmlc::RecordIOReader::NextRecord(std::basic_string<char, std::char_traits<char>, std::allocator<char> >*)```

I ran into this problem because I was compiling MxNet with GCC 8 but linking to a 4.9 libstdc++. Somewhere between 4.9 and 8, there was an ABI change to std::string in order to comply with C++11 requirements that resulted in std::string being moved into the **std::__cxx11** namespace. You can see this below (T ~= 'defined', 'U' ~= missing):

```
>> nm -C libmxnet.so | grep 'dmlc::RecordIOReader::NextRecord'

000000000471cc60 T dmlc::RecordIOReader::NextRecord(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)
0000000000cd897c t dmlc::RecordIOReader::NextRecord(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) [clone .cold.54]
                 U dmlc::RecordIOReader::NextRecord(std::string*)
```

If you look in libmxnet.so, you'll find tons of similarly missing symbols. For whatever reason, NextRecord(...) just happens to be the first in the compilation.

Normally it is possible to force GCC to compile using the old, pre-C++11 namespace by compiling with ```-D_GLIBCXX_USE_CXX11_ABI=0```, however there appears to have been a bug in MxNet that didn't forward CXX_FLAGS to the build correctly. I haven't tracked down precisely which commit fixed the problem, but if you run into this issue, try using a newer commit or make sure that your GCC and libstdc++ versions are compatible.
