### ISSUE TITLE
Flaky test: test np_insert

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#17606]
```
[2020-02-15T11:04:45.615Z] ======================================================================

[2020-02-15T11:04:45.615Z] FAIL: test_operator_gpu.test_np_insert

[2020-02-15T11:04:45.615Z] ----------------------------------------------------------------------

[2020-02-15T11:04:45.615Z] Traceback (most recent call last):

[2020-02-15T11:04:45.615Z]   File "/usr/local/lib/python3.6/site-packages/nose/case.py", line 198, in runTest

[2020-02-15T11:04:45.615Z]     self.test(*self.arg)

[2020-02-15T11:04:45.616Z]   File "/usr/local/lib/python3.6/site-packages/nose/util.py", line 620, in newfunc

[2020-02-15T11:04:45.616Z]     return func(*arg, **kw)

[2020-02-15T11:04:45.616Z]   File "/work/mxnet/tests/python/gpu/../unittest/common.py", line 215, in test_new

[2020-02-15T11:04:45.616Z]     orig_test(*args, **kwargs)

[2020-02-15T11:04:45.616Z]   File "/work/mxnet/python/mxnet/util.py", line 297, in _with_np_shape

[2020-02-15T11:04:45.616Z]     return func(*args, **kwargs)

[2020-02-15T11:04:45.616Z]   File "/work/mxnet/python/mxnet/util.py", line 481, in _with_np_array

[2020-02-15T11:04:45.616Z]     return func(*args, **kwargs)

[2020-02-15T11:04:45.616Z]   File "/work/mxnet/tests/python/gpu/../unittest/test_numpy_op.py", line 2740, in test_np_insert

[2020-02-15T11:04:45.616Z]     assert_almost_equal(y.asnumpy(), expected_ret, rtol=1e-3, atol=1e-5)

[2020-02-15T11:04:45.616Z]   File "/work/mxnet/python/mxnet/test_utils.py", line 638, in assert_almost_equal

[2020-02-15T11:04:45.616Z]     raise AssertionError(msg)

[2020-02-15T11:04:45.616Z] AssertionError: 

[2020-02-15T11:04:45.616Z] Items are not equal:

[2020-02-15T11:04:45.616Z] Error inf exceeds tolerance rtol=1.000000e-03, atol=1.000000e-05 (mismatch at least 5.238095%).

[2020-02-15T11:04:45.616Z] Location of maximum error: (0, 0, 0, 6), a=0.92968750, b=0.00000000

[2020-02-15T11:04:45.616Z]  ACTUAL: array([[[[ 0.3408  , -0.6255  ,  0.      , ...,  0.      , -0.849   ,

[2020-02-15T11:04:45.616Z]            0.9297  ],

[2020-02-15T11:04:45.616Z]          [-0.09344 ,  0.1501  ,  0.      , ...,  0.      , -0.5293  ,...

[2020-02-15T11:04:45.616Z]  DESIRED: array([[[[ 0.3408  ,  0.      ,  0.      , ..., -0.849   ,  0.9297  ,

[2020-02-15T11:04:45.616Z]            0.      ],

[2020-02-15T11:04:45.616Z]          [-0.09344 ,  0.      ,  0.      , ..., -0.5293  , -0.1394  ,...

[2020-02-15T11:04:45.616Z] -------------------- >> begin captured stdout << ---------------------

[2020-02-15T11:04:45.616Z] 

[2020-02-15T11:04:45.616Z] *** Maximum errors for vector of size 210:  rtol=0.001, atol=1e-05

[2020-02-15T11:04:45.616Z] 

[2020-02-15T11:04:45.616Z]   1: Error inf  Location of error: (0, 0, 0, 6), a=0.92968750, b=0.00000000

[2020-02-15T11:04:45.616Z]   2: Error inf  Location of error: (0, 1, 0, 6), a=-0.66015625, b=0.00000000

[2020-02-15T11:04:45.616Z]   3: Error inf  Location of error: (0, 1, 2, 6), a=0.93212891, b=0.00000000

[2020-02-15T11:04:45.616Z]   4: Error inf  Location of error: (1, 0, 0, 6), a=-0.74853516, b=0.00000000

[2020-02-15T11:04:45.616Z]   5: Error inf  Location of error: (1, 1, 0, 6), a=-0.96582031, b=0.00000000

[2020-02-15T11:04:45.616Z]   6: Error inf  Location of error: (1, 1, 1, 6), a=-0.67578125, b=0.00000000

[2020-02-15T11:04:45.616Z]   7: Error inf  Location of error: (2, 0, 2, 6), a=0.97753906, b=0.00000000

[2020-02-15T11:04:45.616Z]   8: Error inf  Location of error: (2, 1, 2, 6), a=0.98144531, b=0.00000000

[2020-02-15T11:04:45.616Z]   9: Error inf  Location of error: (3, 0, 0, 6), a=0.67724609, b=0.00000000

[2020-02-15T11:04:45.616Z]  10: Error inf  Location of error: (3, 0, 1, 1), a=0.89111328, b=0.00000000

[2020-02-15T11:04:45.616Z] 

[2020-02-15T11:04:45.616Z] --------------------- >> end captured stdout << ----------------------

[2020-02-15T11:04:45.616Z] -------------------- >> begin captured logging << --------------------

[2020-02-15T11:04:45.616Z] common: INFO: Setting test np/mx/python random seeds, use MXNET_TEST_SEED=769513493 to reproduce.

[2020-02-15T11:04:45.616Z] --------------------- >> end captured logging << ---------------------
```

http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/mxnet-validation%2Fcentos-gpu/detail/PR-17400/12/pipeline

@reminisce @haojin2

**Comment by haojin2** [comment]
fix merged, the fix has been verified with 500+ runs. Closing the issue for now, feel free to re-open if it pops up again.
