### ISSUE TITLE
[OPPERF] opperf error out if I use python timer instead of the builtin mxnet profiler

### ISSUE THREAD

**Issue by apeforest** [apache/incubator-mxnet#17640]
## Description
Seems the python timer did not parse the argument to broadcast_axis properly. It is fine if I use the 'native' profiler.

### Error Message
```
Traceback (most recent call last):
  File "perf.py", line 12, in <module>
    warmup=20, runs=100, profiler='python')
  File "/home/ubuntu/src/incubator-mxnet/benchmark/opperf/utils/benchmark_utils.py", line 177, in run_performance_test
    benchmark_result = _run_nd_operator_performance_test(op, inputs, run_backward, warmup, runs, kwargs_list, profiler)
  File "/home/ubuntu/src/incubator-mxnet/benchmark/opperf/utils/benchmark_utils.py", line 114, in _run_nd_operator_performance_test
    _, _ = benchmark_helper_func(op, warmup, **kwargs_list[0])
  File "/home/ubuntu/src/incubator-mxnet/benchmark/opperf/utils/profiler_utils.py", line 251, in python_profile_it
    modified_args = (args[0], 1, args[2])
```
## To Reproduce
```
#!/usr/bin/python
import mxnet as mx
from mxnet import nd

from benchmark.opperf.utils.benchmark_utils import run_performance_test

mx.random.seed(17)
res = run_performance_test(nd.broadcast_axis, run_backward=True, dtype='float32', ctx=mx.gpu(),
                           inputs=[
                               {"data" : (1, 1024, 1), "axis" : (0, 2), "size" : (1024, 8)}
                           ],
                           warmup=20, runs=100, profiler='python')
print(res)
```

**Comment by apeforest** [comment]
@ChaiBapchya @connorgoggins Would you like to take a look at this?

**Comment by connorgoggins** [comment]
@apeforest working to reproduce now.

**Comment by connorgoggins** [comment]
Reproduced on CPU, debugging now.

**Comment by connorgoggins** [comment]
Implemented fix here: [[OpPerf] Fixed Python profiler bug](https://github.com/apache/incubator-mxnet/pull/17642) @apeforest
