### ISSUE TITLE
flaky test: test_rnntanh_bidirectional on unix cpu

### ISSUE THREAD

**Issue by szhengac** [apache/incubator-mxnet#17667]
FAIL: test_operator.test_rnntanh_bidirectional

[2020-02-23T23:25:41.378Z] ----------------------------------------------------------------------

[2020-02-23T23:25:41.378Z] Traceback (most recent call last):

[2020-02-23T23:25:41.378Z]   File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest

[2020-02-23T23:25:41.378Z]     self.test(*self.arg)

[2020-02-23T23:25:41.378Z]   File "/work/mxnet/tests/python/unittest/common.py", line 215, in test_new

[2020-02-23T23:25:41.378Z]     orig_test(*args, **kwargs)

[2020-02-23T23:25:41.378Z]   File "/work/mxnet/tests/python/unittest/common.py", line 132, in test_new

[2020-02-23T23:25:41.378Z]     orig_test(*args, **kwargs)

[2020-02-23T23:25:41.378Z]   File "/work/mxnet/tests/python/unittest/test_operator.py", line 245, in test_rnntanh_bidirectional

[2020-02-23T23:25:41.378Z]     check_rnn_consistency(fused, stack, T, N, I, H, 'write')

[2020-02-23T23:25:41.378Z]   File "/work/mxnet/tests/python/unittest/test_operator.py", line 66, in check_rnn_consistency

[2020-02-23T23:25:41.378Z]     assert_allclose(mod1.get_outputs()[0].asnumpy(), mod2.get_outputs()[0].asnumpy(), rtol=rtol, atol=atol)

[2020-02-23T23:25:41.378Z]   File "/work/mxnet/python/mxnet/test_utils.py", line 641, in assert_allclose

[2020-02-23T23:25:41.378Z]     assert_almost_equal(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan)

[2020-02-23T23:25:41.378Z]   File "/work/mxnet/python/mxnet/test_utils.py", line 637, in assert_almost_equal

[2020-02-23T23:25:41.378Z]     raise AssertionError(msg)

[2020-02-23T23:25:41.378Z] AssertionError: 

[2020-02-23T23:25:41.378Z] Items are not equal:

[2020-02-23T23:25:41.378Z] Error 1.703683 exceeds tolerance rtol=1.000000e-02, atol=1.000000e-04 (mismatch at least 0.033569%).

[2020-02-23T23:25:41.378Z] Location of maximum error: (2, 0, 44), a=0.00014767, b=-0.00002309

[2020-02-23T23:25:41.378Z]  ACTUAL: array([[[ 0.00631655,  0.0087107 ,  0.00000006, ...,  0.00697532,

[2020-02-23T23:25:41.378Z]           0.005721  ,  0.00266855]],

[2020-02-23T23:25:41.378Z] ...

[2020-02-23T23:25:41.378Z]  DESIRED: array([[[ 0.00631572,  0.00879268,  0.00013917, ...,  0.00691363,

[2020-02-23T23:25:41.378Z]           0.00582113,  0.00265433]],

[2020-02-23T23:25:41.378Z] ...

[2020-02-23T23:25:41.378Z] -------------------- >> begin captured stdout << ---------------------

[2020-02-23T23:25:41.378Z] 

[2020-02-23T23:25:41.378Z] *** Maximum errors for vector of size 32768:  rtol=0.01, atol=0.0001

[2020-02-23T23:25:41.378Z] 

[2020-02-23T23:25:41.378Z]   1: Error 1.703683  Location of error: (2, 0, 44), a=0.00014767, b=-0.00002309

[2020-02-23T23:25:41.378Z]   2: Error 1.658184  Location of error: (2, 0, 822), a=-0.00034398, b=-0.00017526

[2020-02-23T23:25:41.378Z]   3: Error 1.607267  Location of error: (2, 0, 2), a=0.00019759, b=0.00036417

[2020-02-23T23:25:41.378Z]   4: Error 1.594178  Location of error: (2, 0, 555), a=-0.00044313, b=-0.00027926

[2020-02-23T23:25:41.378Z]   5: Error 1.588423  Location of error: (2, 0, 536), a=-0.00018856, b=-0.00002925

[2020-02-23T23:25:41.378Z]   6: Error 1.573926  Location of error: (2, 0, 882), a=0.00097591, b=0.00080584

[2020-02-23T23:25:41.378Z]   7: Error 1.569279  Location of error: (2, 0, 888), a=0.00120757, b=0.00138625

[2020-02-23T23:25:41.378Z]   8: Error 1.552057  Location of error: (2, 0, 1014), a=0.00117372, b=0.00100295

[2020-02-23T23:25:41.378Z]   9: Error 1.545545  Location of error: (2, 0, 639), a=0.00061197, b=0.00045046

[2020-02-23T23:25:41.378Z]  10: Error 1.540543  Location of error: (2, 0, 775), a=0.00141780, b=0.00124457

**Comment by TaoLv** [comment]
Did it happen in CI? Do you have a link of it?

**Comment by szhengac** [comment]
> Did it happen in CI? Do you have a link of it?

Yes, it is on CI. I have retriggered my PR, so the link is gone...
