### ISSUE TITLE
Rootcause for Gperftools incompatibility with MXNet

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [apache/incubator-mxnet#17720]
## Description

In this PR - https://github.com/apache/incubator-mxnet/pull/14711 USE_GPERFTOOLS was turned off. In this issue https://github.com/apache/incubator-mxnet/issues/8968 it was claimed MXNet crashes with GPerfTools.

However, we do not know fully understand the reason for the crash, hence cannot recommend turning it on / off and its effect in a deterministic way for the users.

This ticket is a place holder to understand impact of using/not-using gperftools and come out with deterministic recommendation for MXNet consumers.

## TODO

1. Will MXNet work fine with latest GPerfTools ex: 2.7?

**Comment by sandeep-krishnamurthy** [comment]
@mseth10 @access2rohit @rondogency fyi

**Comment by mseth10** [comment]
Successfully built MXNet master using cmake with USE_GPERFTOOLS=ON on an ubuntu instance with the following build flags setting:
✔ CUDA, ✔ CUDNN, ✔ NCCL, ✔ CUDA_RTC, ✖ TENSORRT, ✔ CPU_SSE, ✔ CPU_SSE2, ✔ CPU_SSE3, ✔ CPU_SSE4_1, ✔ CPU_SSE4_2, ✖ CPU_SSE4A, ✔ CPU_AVX, ✖ CPU_AVX2, ✔ OPENMP, ✖ SSE, ✔ F16C, ✖ JEMALLOC, ✔ BLAS_OPEN, ✖ BLAS_ATLAS, ✖ BLAS_MKL, ✖ BLAS_APPLE, ✔ LAPACK, ✔ MKLDNN, ✔ OPENCV, ✖ CAFFE, ✖ PROFILER, ✖ DIST_KVSTORE, ✖ CXX14, ✖ INT64_TENSOR_SIZE, ✔ SIGNAL_HANDLER, ✖ DEBUG, ✖ TVM_OP

**Comment by mseth10** [comment]
`train_mnist.py` runs successfully with the above build, so #9096 no longer an issue.
But I was able to reproduce the issue #9098

**Comment by leezu** [comment]
@mseth10 which version of gperftools did you test?

**Comment by mseth10** [comment]
I tested version 2.4-0ubuntu5.16.04.1

**Comment by wkcn** [comment]
I use the latest code(319e6c180edef80d5535e5744a4ac6c84cc143e4) to build MXNet with gperftools 2.7.1 on ArchLinux, but it fails.
```python
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
free(): invalid pointer
[1]    22124 abort (core dumped)  python
```
GDB:
```
Starting program: /usr/bin/python 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
[Detaching after fork from child process 22238]
[New Thread 0x7fffe6a7e700 (LWP 22242)]
free(): invalid pointer

Thread 1 "python" received signal SIGABRT, Aborted.
0x00007ffff7defce5 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7defce5 in raise () at /usr/lib/libc.so.6
#1  0x00007ffff7dd9857 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff7e332b0 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff7e3a74a in  () at /usr/lib/libc.so.6
#4  0x00007ffff7e3c13c in _int_free () at /usr/lib/libc.so.6
#5  0x00007fffdf25c625 in  () at /usr/lib/libopencv_dnn.so.4.2
#6  0x00007fffdf25d0ee in  () at /usr/lib/libopencv_dnn.so.4.2
#7  0x00007fffdf20dd1f in  () at /usr/lib/libopencv_dnn.so.4.2
#8  0x00007fffdeb8cc9b in  () at /usr/lib/libopencv_dnn.so.4.2
#9  0x00007fffdf208ccf in  () at /usr/lib/libopencv_dnn.so.4.2
#10 0x00007fffdeb8c5a5 in  () at /usr/lib/libopencv_dnn.so.4.2
#11 0x00007ffff7fe209a in call_init.part () at /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff7fe21a1 in _dl_init () at /lib64/ld-linux-x86-64.so.2
#13 0x00007ffff7eed905 in _dl_catch_exception () at /usr/lib/libc.so.6
#14 0x00007ffff7fe60e8 in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff7eed8a8 in _dl_catch_exception () at /usr/lib/libc.so.6
#16 0x00007ffff7fe596e in _dl_open () at /lib64/ld-linux-x86-64.so.2
#17 0x00007ffff79cf34c in  () at /usr/lib/libdl.so.2
#18 0x00007ffff7eed8a8 in _dl_catch_exception () at /usr/lib/libc.so.6
#19 0x00007ffff7eed973 in _dl_catch_error () at /usr/lib/libc.so.6
#20 0x00007ffff79cfab9 in  () at /usr/lib/libdl.so.2
#21 0x00007ffff79cf3da in dlopen () at /usr/lib/libdl.so.2
#22 0x00007ffff7c33d44 in _PyImport_FindSharedFuncptr () at /usr/lib/libpython3.8.so.1.0
#23 0x00007ffff7c692e6 in _PyImport_LoadDynamicModuleWithSpec () at /usr/lib/libpython3.8.so.1.0
#24 0x00007ffff7c6974d in  () at /usr/lib/libpython3.8.so.1.0
#25 0x00007ffff7b31e37 in  () at /usr/lib/libpython3.8.so.1.0
#26 0x00007ffff7b70be0 in PyVectorcall_Call () at /usr/lib/libpython3.8.so.1.0
#27 0x00007ffff7be90d6 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.8.so.1.0
#28 0x00007ffff7bd0e3b in _PyEval_EvalCodeWithName () at /usr/lib/libpython3.8.so.1.0
```

It seems that there is some conflict between MXNet and OpenCV, since OpenCV doesn't apply gperftools.
