### ISSUE TITLE
Solved Bug: contrib/amp/loss_scalar.py not initializing variables

### ISSUE THREAD

**Issue by swfearp** [apache/incubator-mxnet#17881]
Not sure if this has been raised before, but I couldn't find it. When training with multiple gpus using amp I get the following error message:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/sam/envs/devenv/lib/python3.6/site-packages/mxnet/kvstore.py", line 84, in updater_handle
    updater(key, lhs, rhs)
  File "/home/sam/envs/devenv/lib/python3.6/site-packages/mxnet/optimizer/optimizer.py", line 1699, in __call__
    states)
  File "/home/sam/envs/devenv/lib/python3.6/site-packages/mxnet/contrib/amp/amp.py", line 305, in new_update_multi_precision
    if not skip_update():
  File "/home/sam/envs/devenv/lib/python3.6/site-packages/mxnet/contrib/amp/loss_scaler.py", line 63, in wait_and_update
    if self._wait_for_outputs:
AttributeError: 'LossScaler' object has no attribute '_wait_for_outputs'
```

Can be fixed by just initializing the following variables in contrib/amp/loss_scalar.py:

``` 
self._wait_for_outputs = True
self.output = nd.array([])
```

**Comment by ptrendx** [comment]
Hi @swfearp, could you give a little more info on how your training loop looks like?

In particular, could you make sure that:
 - you call `amp.init_trainer` on the Gluon trainer you are using
 - you call `amp.scale_loss` inside your `with mx.autograd.record()` block
?

Generally, if everything is called as it should, you should not see that error message.

**Comment by swfearp** [comment]
Hey, here are the amp lines:

```
amp.init()
```

...
optimizer = mx.optimizer.SGD(learning_rate=self.lr, momentum=self.momentum, wd=self.wd)
trainer = gluon.Trainer(params=self.model.collect_params(), optimizer=optimizer)
amp.init_trainer(trainer)
```

```
with autograd.record():
     outputs = [self.model(X) for X in data]
     losses = [loss_function(output, label) for output, label in zip(outputs, smooth_labels)]

     with amp.scale_loss(losses, trainer) as scaled_loss:
          autograd.backward(scaled_loss)
```
