### ISSUE TITLE
Bert Training fails on MXNet 2.0

### ISSUE THREAD

**Issue by JonTanS** [apache/incubator-mxnet#17960]
## Description
Running bert training on MXNet 2.0 (Master Branch) fails. When I pip install MXNet 1.6 the training script runs fine. 

### Error Message
```
[23:02:13] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
INFO:root:Using training data at /home/ubuntu/.mxnet/datasets/bert_input/part-000.npz
INFO:root:1 files found.
[23:02:59] src/operator/contrib/../tensor/./../../common/utils.h:472: MXNET_SAFE_ACCUMULATION=1 is recommended for LayerNorm with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
[23:03:00] src/operator/nn/./../../common/utils.h:472: MXNET_SAFE_ACCUMULATION=1 is recommended for softmax with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
[23:03:00] src/operator/nn/./../../common/utils.h:472: MXNET_SAFE_ACCUMULATION=1 is recommended for softmax with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
[23:03:00] src/operator/contrib/../tensor/./../../common/utils.h:472: MXNET_SAFE_ACCUMULATION=1 is recommended for LayerNorm with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
Traceback (most recent call last):
  File "/home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/run_pretraining.py", line 237, in <module>
    train(data_train, model, nsp_loss, mlm_loss, len(vocab), ctx, store)
  File "/home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/run_pretraining.py", line 192, in train
    fp16_trainer.step(1, max_norm=1)
  File "/home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/fp16_utils.py", line 166, in step
    self.fp32_trainer.update(step_size)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/trainer.py", line 436, in update
    self._update(ignore_stale_grad)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/gluon/trainer.py", line 469, in _update
    updater(i, g, w)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mxnet/optimizer/updater.py", line 91, in __call__
    self.optimizer.update_multi_precision([i], [w], [g], [self.states[i]])
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gluonnlp/optimizer/bert_adam.py", line 91, in update_multi_precision
    use_multi_precision = self.multi_precision and weight.dtype == numpy.float16
AttributeError: 'list' object has no attribute 'dtype'
```

## To Reproduce
Grabbing the scripts from [Gluon Model Zoo BERT](https://gluon-nlp.mxnet.io/model_zoo/bert/index.html) 

### Steps to reproduce
Downloaded the scripts and ran:
```
python /home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/run_pretraining.py --data ~/.mxnet/datasets/bert_input/part-000.npz --data_eval ~/.mxnet/datasets/bert_input/part-000.npz --accumulate 4 --lr 1e-4 --num_steps 100000 --gpus 0
```

## Environment
DL AMI 27

**Comment by JonTanS** [comment]
@eric-haibin-lin @rondogency @szhengac

**Comment by szhengac** [comment]
This is due to the API change in MxNet 2.0 optimizer. And, `bert_adam` follows the old API. So we need to wait until MxNet 2.0 is released and Gluon NLP is updated to MxNet 2.0.

**Comment by szha** [comment]
@szhengac @eric-haibin-lin let's use version guard in GluonNLP to warn about usage with MXNet 2.0.

**Comment by access2rohit** [comment]
@szhengac  In order to ensure BERT performance is not degraded I am trying to benchmark BERT with Large Tensor Support(LTS) with improved broadcast_axis(was slowing down BERT training by 11%). Which branch on MXNet shall I use to benchmark BERT then?

**Comment by leezu** [comment]
@sxjscience please give @access2rohit access

**Comment by szha** [comment]
@leezu I don't think Rohit meant for the numpy version.

@access2rohit I think you will need to first test for 1.6/1.7 which is what GluonNLP 0.9 depends on.

**Comment by sxjscience** [comment]
I'll add @access2rohit to numpy repo and we can have a test also.

**Comment by access2rohit** [comment]
> @leezu I don't think Rohit meant for the numpy version.
> 
> @access2rohit I think you will need to first test for 1.6/1.7 which is what GluonNLP 0.9 depends on.

Makes sense ... I will test this first. But the changes are to be merged in master. 
@szha for making LTS as default in master do I need to test it with 2.0 too?

**Comment by szhengac** [comment]
I think you will only train the model for some steps. In order to test
gluonnlp with mxnet master, you have to change the default optimizer in the
training script to others that have been included the mxnet master such as
lamb or Adam. Then I think you can run the pretraining script or fine
tuning script with mxnet master.

**Comment by apeforest** [comment]
@access2rohit Turing int64 compiler flag on is a part of mxnet 2.0 project not mxnet 1.x. I think we should focus on testing the performance impact by training a few steps as @szhengac suggested. Thanks.

**Comment by access2rohit** [comment]
@szhengac I changed the line 
```
    trainer = mx.gluon.Trainer(model.collect_params(), 'bertadam', optim_params,
                               update_on_kvstore=False, kvstore=store)
```
to 
```
    trainer = mx.gluon.Trainer(model.collect_params(), 'lamb', optim_params,
                               update_on_kvstore=False, kvstore=store)
```
I still the the follwoing error:
```
/home/ubuntu/workspace/incubator-mxnet/python/mxnet/optimizer/optimizer.py:163: UserWarning: WARNING: New optimizer gluonnlp.optimizer.lamb.LAMB is overriding existing optimizer mxnet.optimizer.lamb.LAMB
  Optimizer.opt_registry[name].__name__))
INFO:root:Namespace(accumulate=4, batch_size=8, batch_size_eval=8, ckpt_dir='./ckpt_dir', ckpt_interval=25000, data='/home/ubuntu/.mxnet/datasets/bert_input/part-000.npz', data_eval='/home/ubuntu/.mxnet/datasets/bert_input/part-000.npz', dataset_name='book_corpus_wiki_en_uncased', dtype='float16', dummy_data_len=None, gpus='0', kvstore='device', log_interval=250, lr=0.0001, model='bert_12_768_12', num_buckets=10, num_steps=100000, pretrained=False, profile=None, start_step=0, use_avg_len=False, verbose=False, warmup_ratio=0.01)
[20:23:04] ../src/base.cc:84: Upgrade advisory: this mxnet has been built against cuDNN lib version 7501, which is older than the oldest version tested by CI (7600).  Set MXNET_CUDNN_LIB_CHECKING=0 to quiet this warning.
[20:23:10] ../src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
INFO:root:Using training data at /home/ubuntu/.mxnet/datasets/bert_input/part-000.npz
INFO:root:1 files found.
[20:23:57] ../src/kvstore/././../ndarray/../operator/tensor/../../common/utils.h:474: MXNET_SAFE_ACCUMULATION=1 is recommended for LayerNorm with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
[20:23:57] ../src/operator/nn/./../../common/utils.h:474: MXNET_SAFE_ACCUMULATION=1 is recommended for softmax with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
[20:23:57] ../src/kvstore/././../ndarray/../operator/tensor/../../common/utils.h:474: MXNET_SAFE_ACCUMULATION=1 is recommended for LayerNorm with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
[20:23:58] ../src/operator/nn/./../../common/utils.h:474: MXNET_SAFE_ACCUMULATION=1 is recommended for softmax with float16 inputs. See https://mxnet.apache.org/api/faq/env_var for more details.
Traceback (most recent call last):
  File "/home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/run_pretraining.py", line 237, in <module>
    train(data_train, model, nsp_loss, mlm_loss, len(vocab), ctx, store)
  File "/home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/run_pretraining.py", line 192, in train
    fp16_trainer.step(1, max_norm=1)
  File "/home/ubuntu/MXNet-Benchmarks/mxnet_scripts/training_scripts/bert/fp16_utils.py", line 171, in step
    self.fp32_trainer.update(step_size)
  File "/home/ubuntu/workspace/incubator-mxnet/python/mxnet/gluon/trainer.py", line 437, in update
    self._update(ignore_stale_grad)
  File "/home/ubuntu/workspace/incubator-mxnet/python/mxnet/gluon/trainer.py", line 470, in _update
    updater(i, g, w)
  File "/home/ubuntu/workspace/incubator-mxnet/python/mxnet/optimizer/updater.py", line 93, in __call__
    self.optimizer.update_multi_precision([i], [w], [g], [self.states[i]])
  File "/home/ubuntu/workspace/incubator-mxnet/python/mxnet/optimizer/optimizer.py", line 349, in update_multi_precision
    self.update(indices, weights_master_copy, grads32, original_states)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/gluonnlp/optimizer/lamb.py", line 94, in update
    assert(isinstance(weight, NDArray))
AssertionError
```

**Comment by szhengac** [comment]
Your gluonnlp version has another lamb implementation that tries to
override the lamb in mxnet master. So you need to either manually remove
the gluonnlp.optimizer.lamb or use version 0.9x
