### ISSUE TITLE
docker_cache.py: denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18031]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-docker-cache-refresh/detail/master/2780/pipeline

```
[2020-04-11T22:36:40.756Z] denied: requested access to the resource is denied

[2020-04-11T22:36:40.756Z] docker_cache.py: 2020-04-11 22:36:40,446 Unexpected exception during build of mxnetci/publish.ubuntu1404_gpu

[2020-04-11T22:36:40.756Z] Traceback (most recent call last):

[2020-04-11T22:36:40.756Z]   File "ci/docker_cache.py", line 91, in _build_save_container

[2020-04-11T22:36:40.756Z]   File "ci/docker_cache.py", line 111, in _upload_image

[2020-04-11T22:36:40.756Z]   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call

[2020-04-11T22:36:40.756Z]     raise CalledProcessError(retcode, cmd)

[2020-04-11T22:36:40.756Z] subprocess.CalledProcessError: Command '['docker', 'push', 'mxnetci/publish.ubuntu1404_gpu']' returned non-zero exit status 1
```

cc @ChaiBapchya

**Comment by leezu** [comment]
This was due to temporary use of outdated `awscli` on the AMI used by the docker cache job. Fixed ~2 weeks ago.
