### ISSUE TITLE
cannot build mxnet

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#18180]
## Description
```
git clone --recursive https://github.com/dmlc/mxnet
cd mxnet
ci/build.py --docker-registry mxnetci --platform ubuntu_build_cuda --docker-build-retries 3 --shm-size 500m /work/runtime_functions.sh build_ubuntu_gpu_cuda101_cudnn7
```

### Error Message
```
2020-04-27 20:42:11,481 - root - INFO - Running command: 'docker-compose -f docker/docker-compose.yml build --build-arg USER_ID=1000 --build-arg GROUP_ID=1000 ubuntu_build_cuda'
Traceback (most recent call last):
  File "ci/build.py", line 482, in <module>
    sys.exit(main())
  File "ci/build.py", line 392, in main
    no_cache=args.no_cache, cache_intermediate=args.cache_intermediate)
  File "ci/build.py", line 140, in build_docker
    run_cmd()
  File "/home/ubuntu/mxnet/ci/util.py", line 78, in f_retry
    return f(*args, **kwargs)
  File "ci/build.py", line 138, in run_cmd
    check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose': 'docker-compose'
```

**Comment by leezu** [comment]
`apt install docker-compose` will update doc
