### ISSUE TITLE
Error reporting for operations between different gpus

### ISSUE THREAD

**Issue by acphile** [apache/incubator-mxnet#18265]
```
import mxnet as mx
>>> a=mx.nd.array([1,2,3],ctx=mx.gpu(0))
>>> b=mx.nd.array([1,2,3],ctx=mx.gpu(1))
>>> a+=b
>>> print(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 257, in __repr__
    return '\n%s\n<%s %s @%s>' % (str(self.asnumpy()),
  File "/home/ubuntu/incubator-mxnet/python/mxnet/ndarray/ndarray.py", line 2566, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/ubuntu/incubator-mxnet/python/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../include/mshadow/./stream_gpu-inl.h", line 81
CUDA: Check failed: e == cudaSuccess: an illegal memory access was encountered
>>> a+=b
>>> 
```
when I do plus operation for two ndarray with different gpus, it will not raise any error. However, it will raise CUDA error when accessing a's data. I think it should be more reasonable to raise error when doing operations like 'a+=b'.

**Comment by szha** [comment]
This is probably not a good first issue without suggesting where to add the check.

**Comment by austinmw** [comment]
I've got this error with horovod+gluoncv recently as well

**Comment by leezu** [comment]
@austinmw can you provide more details? The bug report here mainly points out that a python level exception should be thrown instead of letting an illegal memory access to happen.

I suspect your issue is orthogonal
