### ISSUE TITLE
Fail to use mxnet.numpy.prod(a.shape)

### ISSUE THREAD

**Issue by acphile** [apache/incubator-mxnet#18300]
```
>>> mx.np.prod(a.shape)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 31, in prod
AssertionError: Argument a must have NDArray type, but got (5,)
```
while numpy supports that.

**Comment by yzhliu** [comment]
We might postpone to support it after 2.0. Let's still leave the v2.0 label and revisit if we have time before the release.
