### ISSUE TITLE
'mxnet' has no attribute 'metric'

### ISSUE THREAD

**Issue by heaseny** [apache/incubator-mxnet#18329]
## Description
On master branch, when execute the below commands,
python -c "import gluoncv" or python -c "import mxnet as mx; print(mx.metric)" , an error raised with message: 'mxnet' has no attribute 'metric'

### Error Message
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/__init__.py", line 8, in <module>
    from . import data
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/data/__init__.py", line 4, in <module>
    from . import transforms
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/data/transforms/__init__.py", line 6, in <module>
    from . import experimental
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/data/transforms/experimental/__init__.py", line 2, in <module>
    from . import bbox
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/data/transforms/experimental/bbox.py", line 6, in <module>
    from ....utils import bbox_iou
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/utils/__init__.py", line 8, in <module>
    from . import metrics
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/utils/metrics/__init__.py", line 4, in <module>
    from .coco_detection import COCODetectionMetric
  File "/home/mxnet/anacondaenv/anaconda3_mxnet/envs/mxnet_daily_py3/lib/python3.6/site-packages/gluoncv/utils/metrics/coco_detection.py", line 18, in <module>
    class COCODetectionMetric(mx.metric.EvalMetric):
AttributeError: module 'mxnet' has no attribute 'metric'

## To Reproduce
1. install MXNet with master branch lastest commit from build source 
make -j USE_MKLDNN=1 USE_OPENCV=1 USE_BLAS=mkl USE_GPERFTOOLS=0 USE_INTEL_PATH=/opt/intel/
2. Execute the below command, then the error will raise:
 python -c "import gluoncv" or python -c "import mxnet as mx; print(mx.metric)"

## Environment
CentOS7.6
Python3
GCC7.3.1
cmake:3.14.0

**Comment by leezu** [comment]
MXNet 2 moves the metric API to mx.gluon.metric 
gluoncv is not yet compatible with MXNet 2, but you can use MXNet 1.x branch 

Closing as this is not an issue in mxnet, but please reopen if there are further concerns

cc @zhreshold
