### ISSUE TITLE
ImportError: cannot import name 'SyncBatchNorm'

### ISSUE THREAD

**Issue by GasparVardanyan** [apache/incubator-mxnet#18581]
Hi! I've installed mxnet via the **mxnet-cu91** pip package, but running my script which has perfectly worked with the **mxnet** pip package I get this error:

Traceback (most recent call last):
  File "./main.py", line 44, in <module>
    from gluoncv import model_zoo
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/__init__.py", line 9, in <module>
    from . import model_zoo
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/model_zoo/__init__.py", line 3, in <module>
    from .model_zoo import get_model, get_model_list
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 9, in <module>
    from .deeplabv3 import *
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/model_zoo/deeplabv3.py", line 7, in <module>
    from .segbase import SegBaseModel
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/model_zoo/segbase.py", line 10, in <module>
    from .resnest import resnest50, resnest101, resnest200, resnest269
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/model_zoo/resnest.py", line 11, in <module>
    from ..nn.dropblock import DropBlock
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/nn/__init__.py", line 7, in <module>
    from . import feature
  File "/home/paperspace/venv/lib/python3.6/site-packages/gluoncv/nn/feature.py", line 13, in <module>
    from mxnet.symbol.contrib import SyncBatchNorm
ImportError: cannot import name 'SyncBatchNorm'

Please help me to fix this.

**Comment by SkySailing** [comment]
how to solve this problem?

**Comment by GasparVardanyan** [comment]
I've installed the latest version of cuda and the appropriate mxnet package and the problem was solved.
Ubuntu 18's repositories contain an older vesion of cuda, and I've installed the newer version by hand.
btw I hate static release distros ))
