### ISSUE TITLE
MXNET for cuda 11.0 Nvidia 450 

### ISSUE THREAD

**Issue by i55code** [apache/incubator-mxnet#18657]
## Description
(A clear and concise description of what the bug is.)

Is there a version of MXnet for cuda 11.0, Nvidia 450 , Ubuntu 18.04? Something like pip install --pre mxnet_cu102mkl -f ... ? 

Thank you! 

### Error Message
(Paste the complete error message. Please also include stack trace by setting environment variable `DMLC_LOG_STACK_TRACE_DEPTH=10` before running your script.)

## To Reproduce
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

## Environment

We recommend using our script for collecting the diagnositc information. Run the following command and paste the outputs below:
```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

# paste outputs here
```

**Comment by DickJC123** [comment]
With cuda 11.0 of course comes support for A100 and TensorFloat-32 (TF32).  FYI, I'm preparing a PR that refactors how our unittests handle tolerances, so that the proper tolerances are seamlessly applied across dtypes and contexts, including A100 contexts.  Stay tuned.

**Comment by i55code** [comment]
Thank you @DickJC123 !

**Comment by chrisroat** [comment]
Yes, thank you!

**Comment by tadam98** [comment]
Hi, I have installed WSL2 on windows 10 and things appear to be working. 
WSL2 requites CUDA 11. 
Is there a **pip install mxnet-cu110** or similar for using mxnet on this new platform?

Thanks,
Mickey

**Comment by szha** [comment]
not yet. I will open a PR to enable this build

**Comment by tadam98** [comment]
Please do. As WSL2 is now working not bad at all with my 2080 TI super GPU and some of my stuff uses mxnet.
________________________________

**Comment by tadam98** [comment]
Would cuda 9.2 or 10.x work in WSL2 ?
________________________________

**Comment by tadam98** [comment]
Is there a way I can assist with the PR?

**Comment by szha** [comment]
@tadam98 that would be really helpful. Thanks for offering to help. The changes needed are basically the same as other cuda build variants. For example, here are all the mentions of cu102 build: https://github.com/apache/incubator-mxnet/search?q=cu102. These occurrences include changes to build logic and build config, CI/CD, and package information.

Let me know if you have any question or otherwise feel free to ping me when you open a PR.

**Comment by RuRo** [comment]
@szha Sorry to bug you, but it's been 4 months. Are there any updates?

**Comment by szha** [comment]
@RuRo sorry for lack of update on this issue. The nightly build version now has the cu110 package (for development purpose only): https://dist.mxnet.io/python

For releasing on PyPI, there are some ongoing license issue that are being sorted out.

**Comment by Joaquin-aliaga** [comment]
@szha Hi, I've installed the latest mxnet_cu11 ("mxnet_cu110-2.0.0b20201214-py3-none-manylinux2014_x86_64.whl") and the following error has happened:
AttributeError: module 'mxnet' has no attribute 'mod'

Working with:
Python 3.7.8
Debian 10
GPU: NVIDIA Tesla P100
CUDA 11

How can I solve this? 
Thanks in advance

**Comment by szha** [comment]
@Joaquin-aliaga it's probably due to unclean installation. try to:
- remove all previous installation
- (if you have a local copy of mxnet source code) invoke python in a location without mxnet

**Comment by Joaquin-aliaga** [comment]
@szha I've created a new Google Cloud Platform instance (so no mxnet library was installed), then installed mxnet_cu110-2.0.0b20201218-py3-none-manylinux2014_x86_64.whl and the same error has happened.

module 'mxnet' has no attribute 'mod'

Working with:
Python 3.7.8
Debian 10
GPU: NVIDIA Tesla P100
CUDA 11

FYI: same code with mxnet-cu101 works fine, but GCP has Cuda11 by default.

**Comment by gzchenjiajun** [comment]
pip install mxnet-cu110
Tip me
ERROR: No matching distribution found for mxnet-cu110

@szha

**Comment by angus-lherrou** [comment]
Are there any updates on the progress of this?

**Comment by lgg** [comment]
@angus-lherrou details in https://github.com/apache/incubator-mxnet/pull/19764

**Comment by lgg** [comment]
@szha @i55code guess we can close this issue with 1.8.0 release? https://github.com/apache/incubator-mxnet/releases/tag/1.8.0

**Comment by RuRo** [comment]
`mxnet-cu11*` doesn't seem to be available in `pip`/[pypi.org](https://pypi.org/)?

**Comment by szha** [comment]
Working on it.

**Comment by M-Tonin** [comment]
How to install without pip ?

**Comment by szha** [comment]
@M-Tonin you can follow the guide for [building from source](https://mxnet.apache.org/get_started/build_from_source)

**Comment by cberri** [comment]
Dear All,

I am trying to get mxnet for CUDA 11.0 installed. I am using:

`pip install mxnet-cu110`

Unfortunately I get the following: 

```
ERROR: Could not find a version that satisfies the requirement mxnet-cu110
ERROR: No matching distribution found for mxnet-cu110
```

pip 21.0.1 with python 3.7.6

Do you have any suggestion how to solve the issue?

Thank you

Carlo

**Comment by lgg** [comment]
@cberri what platform you have? It's strange.

Try to find available for you version of mxnet here in constructor: https://mxnet.apache.org/versions/1.8.0/get_started?

https://pypi.org/project/mxnet-cu110/ is available in pip

**Comment by cberri** [comment]
@Igg thanks for your quick reply. 
I am trying in Windows 10 in a conda environment. 

Not sure what is going on!

**Comment by lgg** [comment]
@cberri did you try the constructor (https://mxnet.apache.org/versions/1.8.0/get_started)?
 
![image](https://user-images.githubusercontent.com/12018713/112662992-5d1faf80-8e69-11eb-910a-ce27447058dd.png)

Unfortunately I can't help you with windows, because I have linux. But I guess that there is no `mxnet-cu110` for windows yet. (just check the url and image above)

**Comment by szha** [comment]
@yajiedesign is helping with the wheels for windows for 1.8. Those would likely only appear in dist.mxnet.io because of the size limit.

**Comment by cberri** [comment]
@Igg, Excellent point, I get the same error message when I do :

```bash
$ pip install mxnet-cu102
```

I also tried:

```bash
$ pip -v install mxnet-cu102
```

And this is the output:

```
ERROR: Could not find a version that satisfies the requirement mxnet-cu102
ERROR: No matching distribution found for mxnet-cu102
Exception information:
Traceback (most recent call last):
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'mxnet-cu102'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 83, in from_requirement
    raise RequirementsConflicted(criterion)
pip._vendor.resolvelib.resolvers.RequirementsConflicted: Requirements conflict: SpecifierRequirement('mxnet-cu102')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
    requirements, max_rounds=try_to_avoid_resolution_too_deep,
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 320, in resolve
    raise ResolutionImpossible(e.criterion.information)
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('mxnet-cu102'), parent=None)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_internal\cli\base_command.py", line 189, in _main
    status = self.run(options, args)
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_internal\cli\req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_internal\commands\install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "C:\Users\CarloBeretta\anaconda3\envs\cellpose\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 127, in resolve
    six.raise_from(error, e)
  File "<string>", line 3, in raise_from
pip._internal.exceptions.DistributionNotFound: No matching distribution found for mxnet-cu102
Removed build tracker: 'C:\\Users\\CARLOB~1\\AppData\\Local\\Temp\\pip-req-tracker-ypjed3bp'
```

Maybe It helps to find the issue.

**Comment by lgg** [comment]
> dist.mxnet.io

How I can get access to it?

`{"message":"Missing Authentication Token"}`

**Comment by lgg** [comment]
@cberri hello, try installing wheel from here: https://dist.mxnet.io/python/cu102/

e.g.: `pip install mxnet-cu102 -f https://dist.mxnet.io/python`

source: https://discuss.mxnet.apache.org/t/mxnet-version-for-cuda-10-2-in-windows-10/5919/3

also check this: https://github.com/apache/incubator-mxnet/issues/17963 and this https://github.com/apache/incubator-mxnet/issues/19581

**Comment by RomanSteinberg** [comment]
I have Ubuntu 20.04 and CUDA 11.2 installed. Now I installed mxnet-cu110 successfully. But the python application is not working.
1. It demands libcusolver.so.10.0 while I have /usr/local/cuda-11.2/lib64/libcusolver.so. Why version 10 if mxnet-cu110 is about version 11? Why it not satisfied with libcusolver.so? 
Anyway I found workaround and made softlink to existing library and it passed it.

2. It demands libnvrtc.so.11.0 while I have /usr/local/cuda-11.2/lib64/libnvrtc.so.11.2 and I have a softlink libnvrtc.so -> libnvrtc.so .11.2.  Why it is not satisfied? My previous workaround is not working.

What should I do next?
