### ISSUE TITLE
import mxnet strange errors

### ISSUE THREAD

**Issue by MyraBaba** [apache/incubator-mxnet#18808]
## Description
I can't import mxnet from shell/python but can use it from PyCharm from same venv.

>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bc/.venv/CSI/lib/python3.6/site-packages/mxnet/__init__.py", line 102, in <module>
    from . import numpy_op_signature
  File "/home/bc/.venv/CSI/lib/python3.6/site-packages/mxnet/numpy_op_signature.py", line 70, in <module>
    _register_op_signatures()
  File "/home/bc/.venv/CSI/lib/python3.6/site-packages/mxnet/numpy_op_signature.py", line 65, in _register_op_signatures
    op = _get_builtin_op(op_name)
  File "/home/bc/.venv/CSI/lib/python3.6/site-packages/mxnet/numpy_op_signature.py", line 52, in _get_builtin_op
    .format(op_name[op_name_prefix:], root_module.__name__))
TypeError: slice indices must be integers or None or have an __index__ method

Really confusing error for me. 

Best

PS: Ubuntu 18.04  , mxnet-cu101mkl

**Comment by szha** [comment]
do you happen to have multiple versions of mxnet installed?

**Comment by MyraBaba** [comment]
It is happening in the virtual env.

Interesting part Pycharm can run on it but from shell sourcing activate cant import mxnet

**Comment by szha** [comment]
> Interesting part Pycharm can run on it but from shell sourcing activate cant import mxnet

This can only mean that the pycharm setting uses a different pythonpath than using it in venv. Unfortunately, unless I have a way to reproduce it I won't be able to find the cause of the problem for you.

In case the context helps, that part of the code is generating stub files so that IDE like pycharm can correctly perform auto-complete.
