### ISSUE TITLE
MacOS nightly build broken 

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#18840]
```
pip install https://repo.mxnet.io/dist/python/cpu/mxnet-2.0.0b20200802-py3-none-macosx_10_14_x86_64.whl --user 

```

`import mxnet as mx` probably caused by https://github.com/apache/incubator-mxnet/pull/18836  or #18796 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/haibilin/.local/lib/python3.7/site-packages/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/Users/haibilin/.local/lib/python3.7/site-packages/mxnet/context.py", line 20, in <module>
    from .base import _LIB
  File "/Users/haibilin/.local/lib/python3.7/site-packages/mxnet/base.py", line 288, in <module>
    _LIB = _load_lib()
  File "/Users/haibilin/.local/lib/python3.7/site-packages/mxnet/base.py", line 279, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/opt/miniconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/haibilin/.local/lib/python3.7/site-packages/mxnet/libmxnet.dylib, 6): Library not loaded: /Users/travis/build/dmlc/mxnet-distro/mxnet-build/staticdeps/lib/libprotobuf.15.dylib
  Referenced from: /Users/haibilin/.local/lib/python3.7/site-packages/mxnet/libmxnet.dylib
  Reason: image not found
```

```
curl --retry 10 -s https://raw.githubusercontent.com/dmlc/gluon-nlp/master/tools/diagnose.py | python

----------Python Info----------
Version      : 3.7.4
Compiler     : Clang 4.0.1 (tags/RELEASE_401/final)
Build        : ('default', 'Aug 13 2019 15:17:50')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 19.3.1
Directory    : /opt/miniconda3/lib/python3.7/site-packages/pip
----------MXNet Info-----------
Hashtag not found. Not installed from pre-built package.
----------System Info----------
Platform     : Darwin-18.7.0-x86_64-i386-64bit
system       : Darwin
node         : a483e7be4c92.ant.amazon.com
release      : 18.7.0
version      : Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: RDWRFSGS TSC_THREAD_OFFSET SGX BMI1 AVX2 SMEP BMI2 ERMS INVPCID FPU_CSDS MPX RDSEED ADX SMAP CLFSOPT IPT MDCLEAR TSXFA IBRS STIBP L1DF SSBD'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'
----------Network Test----------
```
@leezu  FYI

**Comment by szha** [comment]
Looks like protobuf was missing. I think in the past we've been statically linking protobuf. @leezu is the change towards dynamic linking intentional?

**Comment by leezu** [comment]
Actually it's changed to static linkage @szha:

https://github.com/apache/incubator-mxnet/blob/51340d8f40721e03938e0021c6cbb557a44dd90e/CMakeLists.txt#L157

The problem is though that there is a `AND NOT APPLE` in the `if` condition. Need to move the static linkage option to a separate if clause.
