### ISSUE TITLE
CD: FileExistsError: [Errno 17] File exists: '/home/jenkins_slave/.local'

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#18971]
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-mxnet-cd%2Fmxnet-cd-release-job/detail/mxnet-cd-release-job/1580/pipeline/

```
[2020-08-19T21:56:46.447Z] + ./ci/docker/runtime_functions.sh cd_s3_publish

[2020-08-19T21:56:46.447Z] + CI_CUDA_COMPUTE_CAPABILITIES='-gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_70,code=sm_70'

[2020-08-19T21:56:46.447Z] + CI_CMAKE_CUDA_ARCH='5.2 7.0'

[2020-08-19T21:56:46.447Z] + set +x

[2020-08-19T21:56:46.447Z] + pip3 install --user awscli

[2020-08-19T21:56:48.329Z] Collecting awscli

[2020-08-19T21:56:48.888Z]   Downloading https://files.pythonhosted.org/packages/79/e4/91f89bda78b2ba6163ce1f3d593115dfccdb22a26d0f942bc0ed326ccf85/awscli-1.18.123-py2.py3-none-any.whl (3.3MB)

[2020-08-19T21:56:49.810Z] Collecting docutils<0.16,>=0.10 (from awscli)

[2020-08-19T21:56:49.810Z]   Downloading https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl (547kB)

[2020-08-19T21:56:49.810Z] Collecting rsa<=4.5.0,>=3.1.2; python_version != "3.4" (from awscli)

[2020-08-19T21:56:49.810Z]   Downloading https://files.pythonhosted.org/packages/26/f8/8127fdda0294f044121d20aac7785feb810e159098447967a6103dedfb96/rsa-4.5-py2.py3-none-any.whl

[2020-08-19T21:56:50.064Z] Collecting botocore==1.17.46 (from awscli)

[2020-08-19T21:56:50.318Z]   Downloading https://files.pythonhosted.org/packages/d6/68/a74efb7e55e9c0ca72092f334203eaa92197af4b68a84765c5b6e4376dbf/botocore-1.17.46-py2.py3-none-any.whl (6.5MB)

[2020-08-19T21:56:51.239Z] Collecting colorama<0.4.4,>=0.2.5; python_version != "3.4" (from awscli)

[2020-08-19T21:56:51.239Z]   Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl

[2020-08-19T21:56:51.239Z] Collecting s3transfer<0.4.0,>=0.3.0 (from awscli)

[2020-08-19T21:56:51.239Z]   Downloading https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl (69kB)

[2020-08-19T21:56:51.239Z] Collecting PyYAML<5.4,>=3.10; python_version != "3.4" (from awscli)

[2020-08-19T21:56:51.239Z]   Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz

[2020-08-19T21:56:51.493Z] Collecting pyasn1>=0.1.3 (from rsa<=4.5.0,>=3.1.2; python_version != "3.4"->awscli)

[2020-08-19T21:56:51.747Z]   Downloading https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl (77kB)

[2020-08-19T21:56:51.747Z] Collecting urllib3<1.26,>=1.20; python_version != "3.4" (from botocore==1.17.46->awscli)

[2020-08-19T21:56:51.747Z]   Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl

[2020-08-19T21:56:51.747Z] Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.17.46->awscli)

[2020-08-19T21:56:51.747Z]   Using cached https://files.pythonhosted.org/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl

[2020-08-19T21:56:51.747Z] Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.17.46->awscli)

[2020-08-19T21:56:51.747Z]   Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl

[2020-08-19T21:56:51.747Z] Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore==1.17.46->awscli)

[2020-08-19T21:56:51.747Z]   Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl

[2020-08-19T21:56:51.747Z] Building wheels for collected packages: PyYAML

[2020-08-19T21:56:51.747Z]   Running setup.py bdist_wheel for PyYAML: started

[2020-08-19T21:56:58.268Z]   Running setup.py bdist_wheel for PyYAML: finished with status 'done'

[2020-08-19T21:56:58.268Z]   Stored in directory: /home/jenkins_slave/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd

[2020-08-19T21:56:58.268Z] Successfully built PyYAML

[2020-08-19T21:56:58.268Z] Installing collected packages: docutils, pyasn1, rsa, urllib3, jmespath, six, python-dateutil, botocore, colorama, s3transfer, PyYAML, awscli

[2020-08-19T21:56:58.268Z] Exception:

[2020-08-19T21:56:58.268Z] Traceback (most recent call last):

[2020-08-19T21:56:58.268Z]   File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main

[2020-08-19T21:56:58.268Z]     status = self.run(options, args)

[2020-08-19T21:56:58.268Z]   File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run

[2020-08-19T21:56:58.268Z]     prefix=options.prefix_path,

[2020-08-19T21:56:58.268Z]   File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install

[2020-08-19T21:56:58.268Z]     **kwargs

[2020-08-19T21:56:58.268Z]   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install

[2020-08-19T21:56:58.268Z]     self.move_wheel_files(self.source_dir, root=root, prefix=prefix)

[2020-08-19T21:56:58.268Z]   File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files

[2020-08-19T21:56:58.268Z]     isolated=self.isolated,

[2020-08-19T21:56:58.268Z]   File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files

[2020-08-19T21:56:58.269Z]     prefix=prefix,

[2020-08-19T21:56:58.269Z]   File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme

[2020-08-19T21:56:58.269Z]     i.finalize_options()

[2020-08-19T21:56:58.269Z]   File "/usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl/setuptools/command/install.py", line 38, in finalize_options

[2020-08-19T21:56:58.269Z]     orig.install.finalize_options(self)

[2020-08-19T21:56:58.269Z]   File "/usr/lib/python3.6/distutils/command/install.py", line 351, in finalize_options

[2020-08-19T21:56:58.269Z]     self.create_home_path()

[2020-08-19T21:56:58.269Z]   File "/usr/lib/python3.6/distutils/command/install.py", line 581, in create_home_path

[2020-08-19T21:56:58.269Z]     os.makedirs(path, 0o700)

[2020-08-19T21:56:58.269Z]   File "/usr/lib/python3.6/os.py", line 220, in makedirs

[2020-08-19T21:56:58.269Z]     mkdir(name, mode)

[2020-08-19T21:56:58.269Z] FileExistsError: [Errno 17] File exists: '/home/jenkins_slave/.local'

script returned exit code 2
```

Happened only in the cpu pipeline and not for example the native pipeline.

**Comment by mseth10** [comment]
Today it happened in the native pipeline, and not in the cpu pipeline
https://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/restricted-mxnet-cd%2Fmxnet-cd-release-job/detail/mxnet-cd-release-job/1585/pipeline

Could be due to a race condition between cpu and native runs. Needs investigating.
