### ISSUE TITLE
Multinomial sampling produces impossible values

### ISSUE THREAD

**Issue by bricksdont** [apache/incubator-mxnet#19073]
## Description
Multinomial sampling produces impossible values.

If I understand correctly, if `mx.random.multinomial` is given a distribution such as:

    dist = mx.nd.array([0.3, 0.2, 0.4, 0.1])
    sample = mx.random.multinomial(dist)

Since, [according to the documentation, outputs are 0-indexed,](https://mxnet.incubator.apache.org/versions/1.6/api/python/docs/api/ndarray/random/index.html#mxnet.ndarray.random.multinomial) the sample value can be either 0, 1, 2 or 3 - but never 4. But in Sockeye, in rare cases, 4 would be returned.

I am failing to reproduce this problem independently of Sockeye translation (see below).

**I would be grateful to know how to debug such a failure of an MXnet op.**

### Error Message

The actual error appears in Sockeye, please refer to this issue for details:

https://github.com/awslabs/sockeye/issues/866

We believe that the problem is with MXnet itself. To summarize, calling `random.multinomial` on some occasions returns an impossible value that is out-of-bounds, in the sense that it cannot be used to index the input distribution.

## To Reproduce

To reproduce the Sockeye error that is thrown:

https://gist.github.com/bricksdont/58dfa0964201c83961a30f23406baa5d

To reproduce the MXnet behaviour in isolation I tried creating random distributions, then sampling from them a large number of times with different random seeds. This never returns an impossible index.

https://gist.github.com/bricksdont/e0304b9cc6ecbcc868368353d6e6262c

### Steps to reproduce

Run the shell scripts as indicated in the gists above, e.g.

    wget https://gist.githubusercontent.com/bricksdont/58dfa0964201c83961a30f23406baa5d/raw/da84eb9f1b2f6a231860532c7b85d72528be40ba/sampling_heisenbug.sh
    ./sampling_heisenbug.sh

## Environment

```
curl --retry 10 -s https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py | python

----------Python Info----------
Version      : 3.5.2
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'Apr 16 2020 17:47:17')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 20.2.2
Directory    : /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/pip
----------MXNet Info-----------
Traceback (most recent call last):
  File "<stdin>", line 95, in check_mxnet
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/base.py", line 214, in <module>
    _LIB = _load_lib()
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/base.py", line 205, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.2: cannot open shared object file: No such file or directory

----------System Info----------
Platform     : Linux-4.15.0-101-generic-x86_64-with-Ubuntu-16.04-xenial
system       : Linux
node         : login0
release      : 4.15.0-101-generic
version      : #102~16.04.1-Ubuntu SMP Mon May 11 11:38:16 UTC 2020
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 60
Model name:            Intel Core Processor (Haswell, no TSX)
Stepping:              1
CPU MHz:               2394.454
BogoMIPS:              4788.90
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
----------Network Test----------
Setting timeout: 10
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0205 sec, LOAD: 0.4501 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.8319 sec, LOAD: 0.3664 sec.
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0049 sec, LOAD: 0.6015 sec.
Error open Conda: https://repo.continuum.io/pkgs/free/, HTTP Error 403: Forbidden, DNS finished in 0.0040705204010009766 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0578 sec, LOAD: 0.6745 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0816 sec, LOAD: 0.6879 sec.
----------Environment----------
```

**Comment by bricksdont** [comment]
Not sure if this really is a bug - closing to investigate

**Comment by sxjscience** [comment]
@bricksdont The binary search here does not seem to be correct: https://github.com/apache/incubator-mxnet/blob/9d440868603ad26b702e12ddd2587e5c4b56e42b/src/operator/random/sample_multinomial_op.h#L128-L143

We may choose to directly use the discrete distribution in std c++ http://www.cplusplus.com/reference/random/discrete_distribution/ @xidulu

**Comment by sxjscience** [comment]
@bricksdont Would you be willing to help fix it? To reproduce the wrong behavior, let's consider
```python
import mxnet as mx
dist = mx.nd.array([0.9])
for _ in range(100):
   out = mx.random.multinomial(dist).asscalar()
   if out == 1:
       print('Error!!!!')
```

Output:
```
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
Error!!!!
```

**Comment by bricksdont** [comment]
Hi @sxjscience, thanks for reviving this issue and providing a **much** simpler way to reproduce!

Unfortunately, I lack the C++ skills to read this reliably and fix it. I hope someone else can take this on.

**Comment by sxjscience** [comment]
Also ping @zixuanweeei @pengzhao-intel

**Comment by xidulu** [comment]
@sxjscience 
The implementation of the binary search is correct. 
The problem behind is that the binary search would return the index of the first element larger or equal to `value`. When no such element is found, i.e. `value` is larger than all elements in [0, K), index K will be returned, which is invalid.
In such case, one should add a special check after the loop, just like the origin version of multinomial:

https://sourcegraph.com/github.com/apache/incubator-mxnet/-/commit/e6fad30e45e6ec0ddef5c18093e8163cd2a7c62c#diff-dfa5ed462be234eb86a84d01466756cfL140

**Comment by bricksdont** [comment]
@xidulu Thanks! What exactly do you suggest be changed in the code? Could you open a PR for this?

**Comment by xidulu** [comment]
In short, you could add a check after the while loop (before https://github.com/apache/incubator-mxnet/blob/9d440868603ad26b702e12ddd2587e5c4b56e42b/src/operator/random/sample_multinomial_op.h#L141) to see if left == K (which is not in [0, K) ),  if that happens, you should manually call `left--` before so that the result still lies in [0, K).

I would love to help you but unfortunately I currently do not have any device capable of to build MXNet from source.
