### ISSUE TITLE
Could not find ONNX_LIBRARY using the following names: libonnx.so

### ISSUE THREAD

**Issue by xxxpsyduck** [apache/incubator-mxnet#19208]
## Description
Bug occurs when trying to build mxnet with tensorrt support (Ubuntu 18.04)
### Error Message
```
-- CMAKE_CROSSCOMPILING FALSE
-- CMAKE_HOST_SYSTEM_PROCESSOR x86_64
-- CMAKE_SYSTEM_PROCESSOR x86_64
-- CMAKE_SYSTEM_NAME Linux
-- CMake version '3.18.2' using generator 'Unix Makefiles'
-- Using TensorRT
CMake Error at CMakeLists.txt:239 (find_library):
  Could not find ONNX_LIBRARY using the following names: libonnx.so

-- Configuring incomplete, errors occurred!
See also "/home/indetail/work/mxnet/build/CMakeFiles/CMakeOutput.log".
See also "/home/indetail/work/mxnet/build/CMakeFiles/CMakeError.log".
```
### Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Clone mxnet repo
2. cd mxnet
3. mkdir build && cd build 
4. cmake -DUSE_TENSORRT=1 ..

## What have you tried to solve it?

1. Try to build onnx-tensorrt in mxnet/3rdparty/onnx-tensorrt/build
2. Try to build onnx in /mxnet/3rdparty/onnx-tensorrt/third_party/onnx/build

## Environment
```
----------Python Info----------
Version      : 3.6.9
Compiler     : GCC 8.4.0
Build        : ('default', 'Jul 17 2020 12:50:27')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 20.2.3
Directory    : /home/indetail/.local/lib/python3.6/site-packages/pip
----------MXNet Info-----------
No MXNet installed.
----------System Info----------
Platform     : Linux-5.4.0-47-generic-x86_64-with-Ubuntu-18.04-bionic
system       : Linux
node         : morhn1
release      : 5.4.0-47-generic
version      : #51~18.04.1-Ubuntu SMP Sat Sep 5 14:35:50 UTC 2020
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               158
Model name:          Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz
Stepping:            10
CPU MHz:             4508.051
CPU max MHz:         5000.0000
CPU min MHz:         800.0000
BogoMIPS:            7999.96
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            12288K
NUMA node0 CPU(s):   0-11
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0014 sec, LOAD: 1.3762 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0011 sec, LOAD: 0.7416 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>, DNS finished in 0.0010554790496826172 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0007 sec, LOAD: 0.8259 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0846 sec, LOAD: 0.8990 sec.
Error open Conda: https://repo.continuum.io/pkgs/free/, HTTP Error 403: Forbidden, DNS finished in 0.0008025169372558594 sec.
----------Environment----------
```

**Comment by szha** [comment]
cc @Kh4L. Serge, would you be able to help on this? Let @leezu know in case you need any information regarding cmake.

**Comment by Kh4L** [comment]
Hi @xxxpsyduck 

Have you built onnx and onnx_tensorrt as it is done here https://github.com/apache/incubator-mxnet/blob/master/ci/docker/runtime_functions.sh#L553 ?

You need this preprocessor variable to be set https://github.com/apache/incubator-mxnet/blob/master/ci/docker/runtime_functions.sh#L575

**Comment by xxxpsyduck** [comment]
@Kh4L hello. Can you explain `CI_CUDA_COMPUTE_CAPABILITIES` and `CI_CMAKE_CUDA_ARCH`?

**Comment by Kh4L** [comment]
You can ignore those and it will compile for all the devices.

If not, you can check here https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/ which cuda archs and gencodes to your target devices.

**Comment by xxxpsyduck** [comment]
@Kh4L I successfully built mxnet and installed python binding through command `python3 -m pip install --user -e ./python`. I meet the following error when trying to import mxnet:
```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/indetail/work/mxnet/python/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/indetail/work/mxnet/python/mxnet/context.py", line 20, in <module>
    from .base import _LIB
  File "/home/indetail/work/mxnet/python/mxnet/base.py", line 288, in <module>
    _LIB = _load_lib()
  File "/home/indetail/work/mxnet/python/mxnet/base.py", line 279, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libonnx_proto.so: cannot open shared object file: No such file or directory
>>> 

```

**Comment by xxxpsyduck** [comment]
@Kh4L I successfully built mxnet and wheel [](https://github.com/apache/incubator-mxnet/blob/master/ci/docker/runtime_functions.sh#L61). Then I got mxnet installed by running this command: 
```
~/work/mxnet/python/dist$ python3 -m pip install mxnet-2.0.0-py3-none-any.whl
```
I ran into this error when trying to import mxnet: 
```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
WARNING:root:MXNET_LIBRARY_PATH '/home/indetail/work/build/libmxnet.so' doesn't exist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/indetail/.local/lib/python3.6/site-packages/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/indetail/.local/lib/python3.6/site-packages/mxnet/context.py", line 20, in <module>
    from .base import _LIB
  File "/home/indetail/.local/lib/python3.6/site-packages/mxnet/base.py", line 288, in <module>
    _LIB = _load_lib()
  File "/home/indetail/.local/lib/python3.6/site-packages/mxnet/base.py", line 279, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libonnx_proto.so: cannot open shared object file: No such file or directory
```
