### ISSUE TITLE
mxnet-cu100: can't import mxnet

### ISSUE THREAD

**Issue by PascalIversen** [apache/incubator-mxnet#19248]
## Description
I can't `import mxnet`
### Error Message
---------------------------------------------------------------------------
```python
OSErrorTraceback (most recent call last)
<ipython-input-3-265f02e9c062> in <module>()
----> 1 import mxnet as mx

/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/__init__.py in <module>()
     22 from __future__ import absolute_import
     23 
---> 24 from .context import Context, current_context, cpu, gpu, cpu_pinned
     25 from . import engine
     26 from .base import MXNetError

/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/context.py in <module>()
     22 import warnings
     23 import ctypes
---> 24 from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
     25 from .base import _LIB
     26 from .base import check_call

/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/base.py in <module>()
    211 __version__ = libinfo.__version__
    212 # library instance of mxnet
--> 213 _LIB = _load_lib()
    214 
    215 # type definitions

/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/base.py in _load_lib()
    202     """Load library by searching possible path."""
    203     lib_path = libinfo.find_lib_path()
--> 204     lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
    205     # DMatrix functions
    206     lib.MXGetLastError.restype = ctypes.c_char_p

/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    364 
    365         if handle is None:
--> 366             self._handle = _dlopen(self._name, mode)
    367         else:
    368             self._handle = handle

OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```

## To Reproduce
```
!nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
```
```
!pip install mxnet-cu100
Successfully installed mxnet-cu100-1.5.1.post0

```
`import mxnet `

## Environment

```
curl --retry 10 -s https://raw.githubusercontent.com/apache/incubator-mxnet/master/tools/diagnose.py | python

----------Python Info----------
('Version      :', '2.7.17')
('Compiler     :', 'GCC 7.3.0')
('Build        :', ('default', 'Oct 21 2019 19:04:46'))
('Arch         :', ('64bit', ''))
------------Pip Info-----------
('Version      :', '19.2.3')
('Directory    :', '/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
An error occured trying to import mxnet.
This is very likely due to missing missing or incompatible library files.
Traceback (most recent call last):
  File "<stdin>", line 95, in check_mxnet
  File "/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/home/ec2-user/anaconda3/envs/mxnet_p27/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory

----------System Info----------
('Platform     :', 'Linux-4.14.186-110.268.amzn1.x86_64-x86_64-with-glibc2.2.5')
('system       :', 'Linux')
('node         :', 'ip-172-16-70-68')
('release      :', '4.14.186-110.268.amzn1.x86_64')
('version      :', '#1 SMP Tue Jul 14 02:57:34 UTC 2020')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'x86_64')
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz
Stepping:              2
CPU MHz:               2394.735
BogoMIPS:              4789.04
Hypervisor vendor:     Xen
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              30720K
NUMA node0 CPU(s):     0,1
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0022 sec, LOAD: 0.5408 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0028 sec, LOAD: 0.5230 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0066 sec, LOAD: 0.2218 sec.
Error open Conda: https://repo.continuum.io/pkgs/free/, HTTP Error 403: Forbidden, DNS finished in 0.00168514251709 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0427 sec, LOAD: 0.0903 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>, DNS finished in 0.0439269542694 sec.
----------Environment----------```

**Comment by szha** [comment]
> OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory

This means that the library cannot find the CUDA 10.0 runtime library, which is part of the CUDA 10 toolkit. You will need to set the `LD_LIBRARY_PATH` environment variable to include the path for `libcudart.so.10.0`
