### ISSUE TITLE
TopKAccuracy not working

### ISSUE THREAD

**Issue by bgawrych** [apache/incubator-mxnet#19453]
## Description
TopKAccuracy not working anymore - It was working for sure about ~2 weeks ago (maybe even 1 week)

### Error Message
```
(base) [bgawrych@mlt2-clx011 incubator-mxnet]$ python3 repro.py 
[19:13:43] ../src/storage/storage.cc:199: Using Pooled (Naive) StorageManager for CPU
WARNING:root:np.vander is a fallback operator, which is actually using official numpy's implementation.
Traceback (most recent call last):
  File "rrr.py", line 9, in <module>
    acc.update(labels, predicts)
  File "/home/bgawrych/incubator-mxnet/python/mxnet/util.py", line 299, in _with_np_shape
    return func(*args, **kwargs)
  File "/home/bgawrych/incubator-mxnet/python/mxnet/util.py", line 480, in _with_np_array
    return func(*args, **kwargs)
  File "/home/bgawrych/incubator-mxnet/python/mxnet/gluon/metric.py", line 507, in update
    pred_label = numpy.argpartition(pred_label, -self.top_k)
  File "/home/bgawrych/incubator-mxnet/python/mxnet/numpy/fallback.py", line 121, in fn
    return onp_obj(*args, **kwargs)
  File "<__array_function__ internals>", line 5, in vander
  File "/home/bgawrych/incubator-mxnet/python/mxnet/numpy/multiarray.py", line 392, in __array_function__
    out = func(*new_args, **new_kwargs)
  File "<__array_function__ internals>", line 5, in vander
  File "/home/bgawrych/anaconda3/lib/python3.8/site-packages/numpy/lib/twodim_base.py", line 550, in vander
    raise ValueError("x must be a one-dimensional array or sequence.")
ValueError: x must be a one-dimensional array or sequence.
```

## To Reproduce
Use example script from documentation
```
import mxnet as mx
import numpy as np

np.random.seed(999)
top_k = 3
labels = [mx.nd.array([2, 6, 9, 2, 3, 4, 7, 8, 9, 6])]
predicts = [mx.nd.array(np.random.rand(10, 10))]
acc = mx.gluon.metric.TopKAccuracy(top_k=top_k)
acc.update(labels, predicts)
print(acc.get())
```

**Comment by bgawrych** [comment]
@mxnet-label-bot add [Gluon]

**Comment by szha** [comment]
I verified that this is working on master.
