### ISSUE TITLE
pytest xdist internal error

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#19490]
```
[2020-11-06T23:42:35.171Z] ============================= test session starts ==============================
[2020-11-06T23:42:35.171Z] platform linux -- Python 3.6.9, pytest-5.3.5, py-1.9.0, pluggy-0.13.1 -- /opt/rh/rh-python36/root/usr/bin/python
[2020-11-06T23:42:35.171Z] cachedir: .pytest_cache
[2020-11-06T23:42:35.171Z] rootdir: /work/mxnet, inifile: pytest.ini
[2020-11-06T23:42:35.171Z] plugins: cov-2.8.1, flaky-3.6.1, timeout-1.3.4, forked-1.3.0, env-0.6.2, xdist-1.31.0
[2020-11-06T23:42:35.171Z] timeout: 1200.0s
[2020-11-06T23:42:35.171Z] timeout method: signal
[2020-11-06T23:42:35.171Z] timeout func_only: False
[2020-11-06T23:42:35.171Z] gw0 I / gw1 I / gw2 I / gw3 I
[2020-11-06T23:42:35.171Z] [23:42:32] /work/mxnet/src/engine/engine.cc:55: MXNet start using engine: NaiveEngine
[2020-11-06T23:42:35.171Z] 
[gw0] linux Python 3.6.9 cwd: /work/mxnet
[2020-11-06T23:42:35.171Z] 
[gw1] linux Python 3.6.9 cwd: /work/mxnet
[2020-11-06T23:42:35.171Z] 
[gw2] linux Python 3.6.9 cwd: /work/mxnet
[2020-11-06T23:42:35.171Z] 
[gw3] linux Python 3.6.9 cwd: /work/mxnet
[2020-11-06T23:42:43.267Z] 
[gw0] Python 3.6.9 (default, Nov 11 2019, 11:24:16)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[2020-11-06T23:42:43.267Z] 
[gw1] Python 3.6.9 (default, Nov 11 2019, 11:24:16)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[2020-11-06T23:42:43.267Z] 
[gw2] Python 3.6.9 (default, Nov 11 2019, 11:24:16)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[2020-11-06T23:42:43.524Z] 
[gw3] Python 3.6.9 (default, Nov 11 2019, 11:24:16)  -- [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[2020-11-06T23:42:47.713Z] gw0 [327] / gw1 [327] / gw2 [327] / gw3 [327]
[2020-11-06T23:42:47.713Z] 
[2020-11-06T23:42:47.713Z] scheduling tests via LoadScheduling
[2020-11-06T23:42:47.713Z] 
[2020-11-06T23:42:47.713Z] tests/python/unittest/test_autograd.py::test_operator_with_state 
[2020-11-06T23:42:47.713Z] tests/python/unittest/test_operator.py::test_concat 
[2020-11-06T23:42:47.713Z] tests/python/unittest/test_attr.py::test_operator 
[2020-11-06T23:42:47.713Z] INTERNALERROR> Traceback (most recent call last):
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/_pytest/main.py", line 197, in wrap_session
[2020-11-06T23:42:47.713Z] INTERNALERROR>     session.exitstatus = doit(config, session) or 0
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/_pytest/main.py", line 247, in _main
[2020-11-06T23:42:47.713Z] INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
[2020-11-06T23:42:47.713Z] INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
[2020-11-06T23:42:47.713Z] INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
[2020-11-06T23:42:47.713Z] INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
[2020-11-06T23:42:47.713Z] INTERNALERROR>     return outcome.get_result()
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
[2020-11-06T23:42:47.713Z] INTERNALERROR>     raise ex[1].with_traceback(ex[2])
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
[2020-11-06T23:42:47.713Z] INTERNALERROR>     res = hook_impl.function(*args)
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
[2020-11-06T23:42:47.713Z] INTERNALERROR>     self.loop_once()
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/xdist/dsession.py", line 135, in loop_once
[2020-11-06T23:42:47.713Z] INTERNALERROR>     call(**kwargs)
[2020-11-06T23:42:47.713Z] INTERNALERROR>   File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/xdist/dsession.py", line 177, in worker_workerfinished
[2020-11-06T23:42:47.713Z] INTERNALERROR>     assert not crashitem, (crashitem, node)
[2020-11-06T23:42:47.713Z] INTERNALERROR> AssertionError: ('tests/python/unittest/test_operator.py::test_RNN_float64', <WorkerController gw2>)
[2020-11-06T23:42:47.713Z] INTERNALERROR> assert not 'tests/python/unittest/test_operator.py::test_RNN_float64'
```

https://jenkins.mxnet-ci.amazon-ml.com/blue/rest/organizations/jenkins/pipelines/mxnet-validation/pipelines/centos-cpu/branches/PR-19488/runs/1/nodes/175/steps/250/log/?start=0

**Comment by leezu** [comment]
Closing based on https://github.com/apache/incubator-mxnet/pull/19491

Please reopen if issue persists
