### ISSUE TITLE
Segmentation fault when using simple_bind

### ISSUE THREAD

**Issue by zealota** [apache/incubator-mxnet#1951]
Hi, I've got a Segmentation fault like #865.

At first, I load the pre-trained model that has my custom layers.
(Using the initializer.Load, I'm success to load.)

It occurs when I predict an image.
In #876, time.sleep(10) is one of solutions, but not for me.

How do I fix it??

The backtrace of gdb:

```
#0  0x00002b10538e6fd8 in mshadow::TBlob::TBlob<float> (this=0x2b109f4e1ba0, dptr=0x1307158400, shape=..., dev_mask=2) at /data1/users/mxnet/mshadow/mshadow/./tensor_blob.h:494
#1  0x00002b10538e5853 in mxnet::NDArray::data (this=0x14e957e8) at include/mxnet/ndarray.h:68
#2  0x00002b105398bd30 in mxnet::__lambda15::operator() (__closure=0x14e957e0, ctx=...) at src/ndarray/ndarray.cc:165
#3  0x00002b1053997f91 in mxnet::Engine::__lambda0::operator() (__closure=0x14e957e0, ctx=..., on_complete=...) at include/mxnet/./engine.h:204
#4  0x00002b105399a25d in std::_Function_handler<void(mxnet::RunContext, mxnet::engine::CallbackOnComplete), mxnet::Engine::PushSync(SyncFn, mxnet::Context, const std::vector<mxnet::engine::Var*>&, const std::vector<mxnet::engine::Var*>&, mxnet::FnProperty, int) [with SyncFn = mxnet::SetValueOp(const real_t&, mxnet::NDArray*)::__lambda15]::__lambda0>::_M_invoke(const std::_Any_data &, mxnet::RunContext, mxnet::engine::CallbackOnComplete) (__functor=..., __args#0=..., __args#1=...) at /usr/include/c++/4.8/functional:2071
#5  0x00002b105391a200 in std::function<void (mxnet::RunContext, mxnet::engine::CallbackOnComplete)>::operator()(mxnet::RunContext, mxnet::engine::CallbackOnComplete) const (this=0x29860b0, __args#0=..., __args#1=...) at /usr/include/c++/4.8/functional:2471
#6  0x00002b10539247b2 in mxnet::engine::ThreadedEngine::ExecuteOprBlock (this=0x22ab270, run_ctx=..., opr_block=0x29cb100) at src/engine/./threaded_engine.h:290
#7  0x00002b1053927ba6 in mxnet::engine::ThreadedEnginePerDevice::GPUWorker<(dmlc::ConcurrentQueueType)0> (this=0x22ab270, dev_id=1, is_copy_worker=false, block=0xb33d340) at src/engine/threaded_engine_perdevice.cc:162
#8  0x00002b1053925829 in mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#3}::operator()() const::{lambda()#1}::operator()() const (__closure=0x2e2f700) at src/engine/threaded_engine_perdevice.cc:101
#9  0x00002b10539298a5 in std::_Function_handler<void (), mxnet::engine::ThreadedEnginePerDevice::PushToExecute(mxnet::engine::OprBlock*, bool)::{lambda()#3}::operator()() const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8/functional:2071
#10 0x00002b105392f6e0 in std::function<void ()>::operator()() const (this=0x11a4bc90) at /usr/include/c++/4.8/functional:2471
#11 0x00002b105392f668 in std::_Bind_simple<std::function<void ()> ()>::_M_invoke<>(std::_Index_tuple<>) (this=0x11a4bc90) at /usr/include/c++/4.8/functional:1732
#12 0x00002b105392f5bf in std::_Bind_simple<std::function<void ()> ()>::operator()() (this=0x11a4bc90) at /usr/include/c++/4.8/functional:1720
#13 0x00002b105392ee40 in std::thread::_Impl<std::_Bind_simple<std::function<void ()> ()> >::_M_run() (this=0x11a4bc78) at /usr/include/c++/4.8/thread:115
#14 0x00002b10616dca60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00002b1035805182 in start_thread (arg=0x2b109f4e2700) at pthread_create.c:312
#16 0x00002b1035b1547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
