### ISSUE TITLE
when export slowfast_4x16 from glouncv, I get err:No conversion function registered for op type slice yet.

### ISSUE THREAD

**Issue by h030162** [apache/incubator-mxnet#19527]
Traceback (most recent call last):
  File "slowfast_export.py", line 273, in <module>
    converted_model_path = onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file, verbose = True)
  File "/usr/local/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 79, in export_model
    verbose=verbose)
  File "/usr/local/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 249, in create_onnx_graph_proto
    idx=idx
  File "/usr/local/lib/python3.6/site-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 86, in convert_layer
    raise AttributeError("No conversion function registered for op type %s yet." % op)
AttributeError: No conversion function registered for op type slice yet.

**Comment by szha** [comment]
I think this is a feature request for supporting slice operator for ONNX export. cc @josephevans

**Comment by josephevans** [comment]
Hi @h030162, this is actually fixed in the v1.x branch.

**Comment by Zha0q1** [comment]
Hi @h030162 We have recently enabled support for this model. Are you still working on this? Thanks
