### ISSUE TITLE
Floating Point Exception in mxnet.contrib.ndarray.interleaved_matmul_selfatt_qk

### ISSUE THREAD

**Issue by DNXie** [apache/incubator-mxnet#19686]
## Description
Floating Point Exception in `mxnet.contrib.ndarray.interleaved_matmul_selfatt_qk`

### Error Message
In mxnet1.6:
~~~python
Floating point exception (core dumped)
~~~

In mxnet 2.0.0, floating point exception when exit. 
To reproduce: https://colab.research.google.com/drive/1SVK_U1VKWX0sKj2nHr9P8pL5eLyLIBaw?usp=sharing
~~~python
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 529, in _notify_shutdown
    check_call(_LIB.MXNotifyShutdown())
  File "/usr/local/lib/python3.6/dist-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
FloatingPointError: Traceback (most recent call last):
  File "../src/initialize.cc", line 379
FloatingPointError: Floating point exception
~~~

## Reproduce
~~~python
mxnet.contrib.ndarray.interleaved_matmul_selfatt_qk(heads=0, queries_keys_values=mxnet.nd.array ([[[1,1,0,1]]]))
~~~

## Environment

OS: ubuntu 18.04
Python: 3.7.6
pip: 20.0.2
numpy: 1.18.5
mxnet: 1.6.0

**Comment by leezu** [comment]
```
the input must be a single tensor of interleaved projections
    of queries, keys and values following the layout:
    (seq_length, batch_size, num_heads * head_dim * 3)
```

you are using a `0` shape tensor as `num_heads=0`. It's not supported in `mx.nd` interface..

We can track improving the error message

**Comment by DNXie** [comment]
@leezu  Thanks! An exception message sounds better than crash.
