### ISSUE TITLE
mxnet.ndarray.take crashes(segfault and floating point exception)

### ISSUE THREAD

**Issue by DNXie** [apache/incubator-mxnet#19941]
## Description
`mxnet.ndarray.take` crashes(segfault and floating point exception) when `a` is empty

### Error Message
Floating point exception and segmentation fault

## To Reproduce

This input throws floating point exception, the [gist](https://colab.research.google.com/drive/1sucj581DPV11dIfUkJZ-qFdO5QfWoOYY?usp=sharing)
~~~python
import mxnet
mxnet.ndarray.take(indices = mxnet.nd.array((3, 8, 19, 2)), a=mxnet.nd.array(np.ones((0))), mode='wrap')
~~~

Without passing `wrap`, it throws segfault
~~~python
import mxnet
mxnet.ndarray.take(indices = mxnet.nd.array((3, 8, 19, 2)), a=mxnet.nd.array(np.ones((0))))
~~~

## Environment

OS: ubuntu 18.04
Python: 3.7.6
pip: 20.0.2
numpy: 1.18.5
mxnet: 1.6.0

**Comment by wkcn** [comment]
Thank you for the report!

I reproduce the bug on MXNet 2.0.

**Comment by wkcn** [comment]
Thank you for the report!

I reproduce it on MXNet 2.0.

It is an invalid input, and NumPy will raise an exception.
```python
>>> np.take(a = np.ones(0), indices=np.array([3, 8, 19, 2]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 5, in take
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 191, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/usr/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
```

However, the invalid input makes the program crash on MXNet.

**Comment by DNXie** [comment]
BTW, `mxnet.ndarray.op.take` also crashes with the same input

~~~python
import mxnet
import numpy as np
mxnet.ndarray.op.take(indices = mxnet.nd.array((3, 8, 19, 2)), a=mxnet.nd.array(np.ones((0))), mode='wrap')
~~~

**Comment by TristonC** [comment]
In the c++ backend code, it only reports an error when the mode set as 'raise'. 
[indexing_op.h#L542](https://github.com/apache/incubator-mxnet/blob/5070f1abb9c8198bd7706ff3a16a0d8b8836b822/src/operator/tensor/indexing_op.h#L542)
@szhaShould it follow the NumPy way of reports error when the index out of range?

**Comment by TristonC** [comment]
I guess that clip should also work (by design) too for this corner case as it should raise the error.
