### ISSUE TITLE
AttributeError: libmxnet.so: undefined symbol: MXListDatasets

### ISSUE THREAD

**Issue by XInitialize** [apache/incubator-mxnet#20344]
## Description
I used [cross-compilation](https://mxnet.apache.org/get_started/jetson_setup) to compile the Jetson version of MXNet (v1.8.0). When I executed the script to test mxnet installation, I meet an error in ‘import mxnet as mx’

### Error Message
```
Traceback (most recent call last):
  File "test_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/home/xzw/mxnet/python/mxnet/__init__.py", line 83, in <module>
    from . import gluon
  File "/home/xzw/mxnet/python/mxnet/gluon/__init__.py", line 38, in <module>
    from . import data
  File "/home/xzw/mxnet/python/mxnet/gluon/data/__init__.py", line 30, in <module>
    from . import _internal
  File "/home/xzw/mxnet/python/mxnet/gluon/data/_internal.py", line 265, in <module>
    _init_internal_dataset_module()
  File "/home/xzw/mxnet/python/mxnet/gluon/data/_internal.py", line 258, in _init_internal_dataset_module
    check_call(_LIB.MXListDatasets(ctypes.byref(size), ctypes.byref(plist)))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: libmxnet.so: undefined symbol: MXListDatasets
```

## To Reproduce
 - cross-compilation (change some files for bad network connection)

File: ci/docker/Dockerfile.build.jetson
line49 add(already clone ccache):
```
COPY ccache /work/deps/ccache
```

line54,55 (already clone OpenBLAS):
```
COPY OpenBLAS /usr/local/OpenBLAS
# RUN git clone --recursive -b v0.3.9 https://github.com/xianyi/OpenBLAS.git && \
```
File: ci/build.py
line73-81:
```
    try:
        with open(filename,"rb") as f:
            while True:
                d = f.read(bufsiz)
                if not d:
                    break
                ctx.update(d)
    except IsADirectoryError:
        pass
```
then follow the official guide
### Steps to reproduce
(Paste the commands you ran that produced the error.)
on server
```
scp build/mxnet-1.8.0-py3-none-any.whl xxxxx:~/mxnet-1.8.0-py3-none-any.whl
scp build/libmxnet.so  xxxxx:~/libmxnet.so 
```
on Jetson Nano(2GB)
```
pip3 install mxnet-1.8.0-py3-none-any.whl
echo "import mxnet as mx">test_mxnet.py
python3  test_mxnet.py
```
## What have you tried to solve it?

At a loss

## Environment

<details>
<summary>Environment Information</summary>

```
----------Python Info----------
Version      : 3.6.9
Compiler     : GCC 8.4.0
Build        : ('default', 'Jan 26 2021 15:33:00')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 21.1.2
Directory    : /home/xzw/.local/lib/python3.6/site-packages/pip
----------MXNet Info-----------
An error occured trying to import mxnet.
This is very likely due to missing missing or incompatible library files.
Traceback (most recent call last):
  File "diag.py", line 95, in check_mxnet
    import mxnet
  File "/home/xzw/mxnet/python/mxnet/__init__.py", line 83, in <module>
    from . import gluon
  File "/home/xzw/mxnet/python/mxnet/gluon/__init__.py", line 38, in <module>
    from . import data
  File "/home/xzw/mxnet/python/mxnet/gluon/data/__init__.py", line 30, in <module>
    from . import _internal
  File "/home/xzw/mxnet/python/mxnet/gluon/data/_internal.py", line 265, in <module>
    _init_internal_dataset_module()
  File "/home/xzw/mxnet/python/mxnet/gluon/data/_internal.py", line 258, in _init_internal_dataset_module
    check_call(_LIB.MXListDatasets(ctypes.byref(size), ctypes.byref(plist)))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: libmxnet.so: undefined symbol: MXListDatasets

----------System Info----------
Platform     : Linux-4.9.201-tegra-aarch64-with-Ubuntu-18.04-bionic
system       : Linux
node         : xzw-desktop
release      : 4.9.201-tegra
version      : #1 SMP PREEMPT Wed May 5 09:31:36 PDT 2021
----------Hardware Info----------
machine      : aarch64
processor    : aarch64
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               1
Model name:          Cortex-A57
Stepping:            r1p1
CPU max MHz:         1479.0000
CPU min MHz:         102.0000
BogoMIPS:            38.40
L1d cache:           32K
L1i cache:           48K
L2 cache:            2048K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0311 sec, LOAD: 0.8538 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 4.2936 sec, LOAD: 0.7392 sec.
Error open Gluon Tutorial(cn): https://zh.gluon.ai, <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>, DNS finished in 3.1451590061187744 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.4001 sec, LOAD: 5.2658 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0419 sec, LOAD: 1.6790 sec.
Error open Conda: https://repo.continuum.io/pkgs/free/, HTTP Error 403: Forbidden, DNS finished in 0.04138970375061035 sec.
----------Environment----------
MXNET_HOME="/home/xzw/mxnet/"
```

</details>

**Comment by XInitialize** [comment]
wheel file link: [google cloud](https://drive.google.com/file/d/1LRQr_7uoazaBtcu3ItCB-BIbT8y0pMSJ/view?usp=sharing)

**Comment by XInitialize** [comment]
I have rebuild for times, finally, I got it.
