### ISSUE TITLE
when run" mxnet/example/image-classification" on Multiple Machines,what path is the "hosts"?

### ISSUE THREAD

**Issue by n080509** [apache/incubator-mxnet#2085]
when run" mxnet/example/image-classification" on Multiple Machines
i save the IPs (or hostname) of these two machines in file hosts

bus what path is the file hosts ?

THKS

**Comment by n080509** [comment]
i set IPs in the file /etc/hosts  

10.136.159.116
10.136.159.127

and  i run the "slave116@116:~/mxnet/tools$ ./launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync"

the error as follow:
"
Traceback (most recent call last):
  File "./launch.py", line 79, in <module>
    main()
  File "./launch.py", line 64, in main
    ssh.submit(args)
  File "/home/slave116/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 38, in submit
    with open(args.host_file) as f:
IOError: [Errno 2] No such file or directory: 'hosts'
slave116@116:~/mxnet/tools$ ./launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync
Traceback (most recent call last):
  File "./launch.py", line 79, in <module>
    main()
  File "./launch.py", line 64, in main
    ssh.submit(args)
  File "/home/slave116/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 38, in submit
    with open(args.host_file) as f:
IOError: [Errno 2] No such file or directory: 'hosts'

"

**Comment by n080509** [comment]
i new a file "hosts" in the path /.../mxnet/tools,and write the IP
10.136.159.116
10.136.159.127

and i run the "slave116@116:~/mxnet/tools$ sudo ./launch.py -n 2 -H hosts python train_mnist.py --kv-store dist_sync"
 the error as follow ,

slave116@116:~/mxnet/example/image-classification$ ../../tools/launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync
slave116@10.136.159.127's password: slave116@10.136.159.116's password: slave116@10.136.159.116's password: slave116@10.136.159.127's password:
Permission denied, please try again.
slave116@10.136.159.127's password:

Permission denied, please try again.
slave116@10.136.159.116's password:
Permission denied, please try again.
slave116@10.136.159.127's password:


Permission denied, please try again.
slave116@10.136.159.116's password: Permission denied, please try again.
slave116@10.136.159.127's password:
Permission denied, please try again.
slave116@10.136.159.127's password:



Permission denied (publickey,password).
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/slave116/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 52, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.136.159.127 'export LD_LIBRARY_PATH=:/usr/local/lib; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9092; export DMLC_PS_ROOT_URI=0.0.0.116; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /home/slave116/mxnet/example/image-classification/; python train_mnist.py --network lenet --kv-store dist_sync'' returned non-zero exit status 255


Permission denied (publickey,password).
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/slave116/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 52, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.136.159.127 'export LD_LIBRARY_PATH=:/usr/local/lib; export DMLC_ROLE=server; export DMLC_PS_ROOT_PORT=9092; export DMLC_PS_ROOT_URI=0.0.0.116; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /home/slave116/mxnet/example/image-classification/; python train_mnist.py --network lenet --kv-store dist_sync'' returned non-zero exit status 255

Permission denied (publickey,password).
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/slave116/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 52, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.136.159.116 'export LD_LIBRARY_PATH=:/usr/local/lib; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9092; export DMLC_PS_ROOT_URI=0.0.0.116; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /home/slave116/mxnet/example/image-classification/; python train_mnist.py --network lenet --kv-store dist_sync'' returned non-zero exit status 255

**Comment by n080509** [comment]
how can i set the ssh account&password ?

**Comment by hoaphumanoid** [comment]
The fastest way is with this command: `ssh-copy-id username@remote_host`. It autmatically copies the ssh keys to the host.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
