### ISSUE TITLE
how can i run "example/image-classification"over mpi ,on mutil-machines

### ISSUE THREAD

**Issue by n080509** [apache/incubator-mxnet#2091]
i want to run the "example/image-classification"over mpi ,on mutil-machines
i run the command as follow ,but nothing is respond

slave116@116:~/mxnet/example/image-classification$ ../../tools/launch.py -n 2 --launcher mpi -H hosts python train_mnist.py --network lenet --kv-store dist_sync
2016-05-10 02:27:59,789 INFO Start 2 workers by mpirun

pls,help me how i can run it over mpi,on mutil-machines
thanks

**Comment by Godricly** [comment]
did u miss the -s parameter? I remember there was this parameter before.

**Comment by n080509** [comment]
root@116:~/mxnet/example/image-classification#../../tools/launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync

**Comment by n080509** [comment]
now I run the "example/image-classification" with two machines
       10.136.159.116
       10.136.159.117
	
       I run the the command on the 10.136.159.116 as follow,but nothing respond,can you help me ,how can I do ?
      root@116:~/mxnet/example/image-classification#../../tools/launch.py -n 2 --launcher ssh -H hosts python train_mnist.py --network lenet --kv-store dist_sync

**Comment by Godricly** [comment]
did you try run local one ?    give it a try by add -s 1 after -n 2.

**Comment by n080509** [comment]
@Godricly    
now i  run it  as follow,how can i do next

root@116:~/mxnet/example/image-classification# export PS_VERBOSE=1; ../../tools/launch.py -n 2 -H hosts --sync-dst-dir /tmp/mxnet python train_mnist.py --kv-store dist_sync
python train_mnist.py --kv-store dist_sync
2016-05-12 05:34:37,993 INFO rsync /home/slave/mxnet/example/image-classification/ -> 10.136.159.116:/tmp/mxnet
[05:34:38] src/van.cc:65: Bind to role=scheduler, id=1, ip=0.0.0.116, port=9098
2016-05-12 05:34:38,203 INFO rsync /home/slave/mxnet/example/image-classification/ -> 10.136.159.117:/tmp/mxnet
^CTraceback (most recent call last):
  File "../../tools/launch.py", line 79, in <module>
    main()
  File "../../tools/launch.py", line 64, in main
    ssh.submit(args)
  File "/home/slave/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 76, in submit
    pscmd=(' '.join(args.command)))
  File "/home/slave/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 422, in submit
    pserver.join()
  File "/home/slave/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 371, in join
    self.thread.join(100)
  File "/usr/lib/python2.7/threading.py", line 960, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt

**Comment by n080509** [comment]
root@116:~/mxnet/example/image-classification# ../../tools/launch.py -n 2 -s 1 python train_mnist.py --kv-store dist_sync
python train_mnist.py --kv-store dist_sync
[06:29:44] src/van.cc:65: Bind to role=scheduler, id=1, ip=0.0.0.116, port=9102
[06:29:44] src/van.cc:65: Bind to role=server, ip=10.136.159.116, port=47526
[06:29:44[] src/van.cc:65: Bind to role=worker, ip=10.136.159.116, port=45587
06:29:44] src/van.cc:65: Bind to role=worker, ip=10.136.159.116, port=39873


^CTraceback (most recent call last):
  File "../../tools/launch.py", line 79, in <module>
    main()
  File "../../tools/launch.py", line 55, in main
    local.submit(args)
  File "/home/slave/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/local.py", line 83, in submit
    pscmd=(' '.join(args.command)))
  File "/home/slave/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 422, in submit
    pserver.join()
  File "/home/slave/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 371, in join
    self.thread.join(100)
  File "/usr/lib/python2.7/threading.py", line 960, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
root@116:~/mxnet/example/image-classification#

**Comment by n080509** [comment]
run on the one server  ,the same .nothing responds
