### ISSUE TITLE
Flakey test:  test_quantization_mkldnn.test_quantized_rnn

### ISSUE THREAD

**Issue by josephevans** [apache/incubator-mxnet#21061]
## Description
Test appears to be only for mkldnn (skips when native CPU or GPU,) but this is failing repeatedly in the v1.9.x branch. Can the Intel folks take a look at this? I am going to skip it for now.

```
[2022-06-08T16:11:07.819Z] ======================================================================
[2022-06-08T16:11:07.819Z] ERROR: test_quantization_mkldnn.test_quantized_rnn
[2022-06-08T16:11:07.819Z] ----------------------------------------------------------------------
[2022-06-08T16:11:07.819Z] Traceback (most recent call last):
[2022-06-08T16:11:07.819Z]   File "/usr/local/lib/python3.7/dist-packages/nose/case.py", line 198, in runTest
[2022-06-08T16:11:07.819Z]     self.test(*self.arg)
[2022-06-08T16:11:07.819Z]   File "/usr/local/lib/python3.7/dist-packages/nose/util.py", line 620, in newfunc
[2022-06-08T16:11:07.819Z]     return func(*arg, **kw)
[2022-06-08T16:11:07.819Z]   File "/work/mxnet/tests/python/mkl/../unittest/common.py", line 218, in test_new
[2022-06-08T16:11:07.819Z]     orig_test(*args, **kwargs)
[2022-06-08T16:11:07.819Z]   File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 657, in test_quantized_rnn
[2022-06-08T16:11:07.819Z]     check_quantized_rnn(1, False, 5, 2, 16, 16)
[2022-06-08T16:11:07.819Z]   File "/work/mxnet/tests/python/mkl/../quantization/test_quantization.py", line 654, in check_quantized_rnn
[2022-06-08T16:11:07.819Z]     mse = np.mean((output.asnumpy() - qoutput.asnumpy())**2)
[2022-06-08T16:11:07.819Z]   File "/work/mxnet/python/mxnet/ndarray/ndarray.py", line 2571, in asnumpy
[2022-06-08T16:11:07.819Z]     ctypes.c_size_t(data.size)))
[2022-06-08T16:11:07.819Z]   File "/work/mxnet/python/mxnet/base.py", line 246, in check_call
[2022-06-08T16:11:07.819Z]     raise get_last_ffi_error()
[2022-06-08T16:11:07.819Z] mxnet.base.MXNetError: MXNetError: could not create a primitive descriptor for a reorder primitive
[2022-06-08T16:11:07.819Z] -------------------- >> begin captured logging << --------------------
[2022-06-08T16:11:07.819Z] common: WARNING: Error seen with seeded test, use MXNET_TEST_SEED=1189878562 to reproduce.
[2022-06-08T16:11:07.819Z] --------------------- >> end captured logging << ---------------------
```

**Comment by anko-intel** [comment]
ok , we will take a look
