### ISSUE TITLE
Building 1.9.1 from source gives: "Cannot find operator all in module mxnet.numpy" at runtime using python

### ISSUE THREAD

**Issue by lorenzob** [apache/incubator-mxnet#21063]
## Description
Building 1.9.1 from source gives: "Cannot find operator all in module mxnet.numpy" at runtime using python

It works correctly with the pre-built 1.9.1 version from conda repo.

### Error Message
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/facerec39forge/lib/python3.9/site-packages/mxnet/__init__.py", line 103, in <module>
    from . import numpy_op_signature
  File "/home/user/miniconda3/envs/facerec39forge/lib/python3.9/site-packages/mxnet/numpy_op_signature.py", line 61, in <module>
    _register_op_signatures()
  File "/home/user/miniconda3/envs/facerec39forge/lib/python3.9/site-packages/mxnet/numpy_op_signature.py", line 56, in _register_op_signatures
    op = _get_builtin_op(op_name)
  File "/home/user/miniconda3/envs/facerec39forge/lib/python3.9/site-packages/mxnet/numpy_op_signature.py", line 49, in _get_builtin_op
    raise ValueError('Cannot find operator {} in module {}'
ValueError: Cannot find operator all in module mxnet.numpy

## To Reproduce
git clone...
git checkout 1.9.1
git submodule update --init --recursive     # correct? Otherwise it does not build

cp config/linux.cmake config.cmake
edit file to set USE_OPENCV and USE_OPENMP to OFF

mkdir build; cd build
cmake ..
cmake --build .

activate conda env
pip install python/

### Steps to reproduce
import mxnet

## What have you tried to solve it?

remove numpy and let mxnet install choose and install its preferred version

## Environment

Linux host 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
python 3.9.0
numpy                  1.22.4

I'm trying to do a build with no OPENMP(libgomp) dependency to use it with the NaiveEngine only (I know there is no need to rebuild it but I have a strange deadlock in libgomp so it seems it is still using it somehow and I prefer to have a clean, simple situation).

**Comment by lorenzob** [comment]
I am no longer able to reproduce this, probability was something messed up in the conda environment.
