### ISSUE TITLE
Can't install mxnet cuda on Windows Server 2016!

### ISSUE THREAD

**Issue by kprastey** [apache/incubator-mxnet#21125]
## Description
OS = Windows Server 2016 (x64)
Python system version = 3.7.13 (default, Mar 28 2022, 08:03:21) [MSC v.1916 64 bit (AMD64)]
Python platform version = 3.7.13
PIP version = pip-22.2.2
CUDA = 11.7
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0

Tried to use GPU to run inference giving context like:
`ctx = mx.gpu()`
    `net = gcv.model_zoo.get_model(
        name=*,
        pretrained=False,
        classes=*,
        ctx=ctx
        )`
But it returned this error.
### Error Message

> Traceback (most recent call last):
  File "main.py", line 24, in <module>
    net_object_detector = models.initialize_object_detector()
  File "*\src\models.py", line 43, in initialize_object_detector
    ctx=ctx
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\model_zoo.py", line 413, in get_model
    net = _models[name](**kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\ssd\presets.py", line 442, in ssd_512_resnet50_v1_custom
    pretrained_base=pretrained_base, **kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\ssd\ssd.py", line 417, in get_ssd
    minimal_opset=pretrained, anchor_generator=anchor_generator, **kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\ssd\ssd.py", line 150, in __init__
    norm_layer=norm_layer, norm_kwargs=norm_kwargs, root=root)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\nn\feature.py", line 135, in __init__
    network, outputs, inputs, pretrained, ctx, **kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\nn\feature.py", line 55, in _parse_network
    network = get_model(network, pretrained=pretrained, ctx=ctx, **kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\model_zoo.py", line 413, in get_model
    net = _models[name](**kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\resnet.py", line 635, in resnet50_v1
    return get_resnet(1, 50, use_se=False, **kwargs)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\gluoncv\model_zoo\resnet.py", line 560, in get_resnet
    tag=pretrained, root=root), ctx=ctx)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\gluon\block.py", line 556, in load_parameters
    params[name]._load_init(loaded[name], ctx, cast_dtype=cast_dtype, dtype_source=dtype_source)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\gluon\parameter.py", line 316, in _load_init
    self._init_impl(data, ctx)
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\gluon\parameter.py", line 365, in _init_impl
    self._data = [data.copyto(ctx) for ctx in self._ctx_list]
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\gluon\parameter.py", line 365, in <listcomp>
    self._data = [data.copyto(ctx) for ctx in self._ctx_list]
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\ndarray\ndarray.py", line 2666, in copyto
    return _internal._copyto(self, out=hret)
  File "<string>", line 27, in _copyto
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\_ctypes\ndarray.py", line 91, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "C:\Users\*\Anaconda3\envs\*\lib\site-packages\mxnet\base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "C:\Jenkins\workspace\mxnet-tag\mxnet\src\ndarray\ndarray.cc", line 1298
MXNetError: GPU is not enabled

- So I tried installing mxnet-cu112 using pip but that returned this error:
`ERROR: Could not find a version that satisfies the requirement mxnet-cu112 (from versions: none)`
`ERROR: No matching distribution found for mxnet-cu112`

- So instead I downloaded the `mxnet_cu112-1.9.0-py3-none-manylinux2014_x86_64.whl` from [https://dist.mxnet.io/python/cu112](https://dist.mxnet.io/python/cu112) and tried installing it using pip but that returned this error:
`ERROR: mxnet_cu112-1.9.0-py3-none-manylinux2014_x86_64.whl is not a supported wheel on this platform.` 
which is strange.

- Help me install with Cuda enabled mxnet so I can use GPU instead of CPU.

**Comment by relaxli00** [comment]
As far as I know, there is no binary wheel for windows released after 1.7.0. You'll have to build from source. I tried to build 1.9.1 for Windows 10 with MKL BLAS. Not sure if it's helpful, my steps can be found [here](https://medium.com/@relaxli/build-mxnet-1-9-1-with-cuda-11-7-and-mkl-blas-using-visual-studio-2019-on-windows-10-a9ebecb1941b) https://medium.com/@relaxli/build-mxnet-1-9-1-with-cuda-11-7-and-mkl-blas-using-visual-studio-2019-on-windows-10-a9ebecb1941b .

**Comment by quxi0001** [comment]
Hi, have you solve this problrm? I got the same problem and don't know how to fix it.
