### ISSUE TITLE
whether the symbol module has been changed?

### ISSUE THREAD

**Issue by yech1990** [apache/incubator-mxnet#2124]
neuron-art example arise error as below 

``` python
INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
Traceback (most recent call last):
  File "run.py", line 166, in <module>
    style_loss, content_loss = get_loss(gram, content)
  File "run.py", line 118, in get_loss
    gram_loss.append(mx.sym.sum(mx.sym.square(gvar - gram[i])))
AttributeError: 'module' object has no attribute 'sum'
```

**Comment by yech1990** [comment]
when I change ``mx,sym.sum`` to ``np.sum``

```python
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPEto NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

```

**Comment by yech1990** [comment]
#2137
