### ISSUE TITLE
fail to compile  scala  package test  

### ISSUE THREAD

**Issue by chengdianxuezi** [apache/incubator-mxnet#2184]
compile the code as the website https://github.com/dmlc/mxnet/issues

success: make scalapkg

fail: make scalatest

the reason:
**\* RUN ABORTED ***
  java.lang.UnsatisfiedLinkError: Couldn't find the resource libmxnet-scala.so
  at ml.dmlc.mxnet.util.NativeLibraryLoader$.loadLibrary(NativeLibraryLoader.scala:74)
  at ml.dmlc.mxnet.Base$.<init>(Base.scala:42)
  at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
  at ml.dmlc.mxnet.Symbol$.initSymbolModule(Symbol.scala:1328)
  at ml.dmlc.mxnet.Symbol$.<init>(Symbol.scala:743)
  at ml.dmlc.mxnet.Symbol$.<clinit>(Symbol.scala)
  at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply$mcV$sp(SymbolSuite.scala:7)
  at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
  at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)

**Comment by javelinjs** [comment]
On which os did you compile?

**Comment by cyq130** [comment]
I have encountered the same problem on Cantos. How can I solve this? Thanks

**Comment by javelinjs** [comment]
I think it is due to something incompatible with the linked native libs.
The core/Base is coded to try NativeLibraryLoader automatically, which will look for .so in the assembly jar. The error printed here does not explain the real reason. I'll fix this log problem.

Please temporally apply the following patch to find out the real issue:
```
diff --git a/scala-package/core/src/main/scala/ml/dmlc/mxnet/Base.scala b/scala-package/core/src/main/scala/ml/dmlc/mxnet/Base.scala
index d995176..bc910f4 100644
--- a/scala-package/core/src/main/scala/ml/dmlc/mxnet/Base.scala
+++ b/scala-package/core/src/main/scala/ml/dmlc/mxnet/Base.scala
@@ -35,6 +35,8 @@ object Base {
   type SymbolHandleRef = RefLong
 
   try {
+    tryLoadLibraryOS("mxnet-scala")
+    /*
     try {
       tryLoadLibraryOS("mxnet-scala")
     } catch {
@@ -46,6 +48,7 @@ object Base {
           "or specifying by Java cmd option -Djava.library.path=[lib path].")
         NativeLibraryLoader.loadLibrary("mxnet-scala")
     }
+    */
   } catch {
     case e: UnsatisfiedLinkError =>
       logger.error("Couldn't find native library mxnet-scala")
```

**Comment by zihaolucky** [comment]
Hi @javelinjs I encountered almost same problem when make scalapkg all success but failed in test.

Any idea I could do to fix that? BTW, I use openblas on centos7 with gpu enabled.

```
Discovery starting.
Discovery completed in 301 milliseconds.
Run starting. Expected test count is: 91
SymbolSuite:
2016-07-31 12:19:24,077 [ScalaTest-main-running-SymbolSuite] [MXNetJVM] [INFO] - Try loading mxnet-scala from native path.
2016-07-31 12:19:24,078 [ScalaTest-main-running-SymbolSuite] [MXNetJVM] [WARN] - Failed to load from native path. Exception:
java.lang.UnsatisfiedLinkError: no mxnet-scala in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryOS(Base.scala:70)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:39)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Symbol$.initSymbolModule(Symbol.scala:1396)
	at ml.dmlc.mxnet.Symbol$.<init>(Symbol.scala:773)
	at ml.dmlc.mxnet.Symbol$.<clinit>(Symbol.scala)
	at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply$mcV$sp(SymbolSuite.scala:7)
	at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
	at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at ml.dmlc.mxnet.SymbolSuite.org$scalatest$BeforeAndAfterAll$$super$run(SymbolSuite.scala:5)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at ml.dmlc.mxnet.SymbolSuite.run(SymbolSuite.scala:5)
	at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1492)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1528)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1526)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1526)
	at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
	at org.scalatest.Suite$class.run(Suite.scala:1421)
	at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.main(Runner.scala:860)
	at org.scalatest.tools.Runner.main(Runner.scala)
2016-07-31 12:19:24,080 [ScalaTest-main-running-SymbolSuite] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-gpu from native path.
2016-07-31 12:19:24,085 [ScalaTest-main-running-SymbolSuite] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-cpu from native path.
2016-07-31 12:19:24,085 [ScalaTest-main-running-SymbolSuite] [MXNetJVM] [WARN] - MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].Exception:
java.lang.UnsatisfiedLinkError: no mxnet-scala-linux-x86_64-cpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryXPU(Base.scala:96)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryOS(Base.scala:77)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:39)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Symbol$.initSymbolModule(Symbol.scala:1396)
	at ml.dmlc.mxnet.Symbol$.<init>(Symbol.scala:773)
	at ml.dmlc.mxnet.Symbol$.<clinit>(Symbol.scala)
	at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply$mcV$sp(SymbolSuite.scala:7)
	at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
	at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
	at ml.dmlc.mxnet.SymbolSuite.org$scalatest$BeforeAndAfterAll$$super$run(SymbolSuite.scala:5)
	at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:257)
	at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:256)
	at ml.dmlc.mxnet.SymbolSuite.run(SymbolSuite.scala:5)
	at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1492)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1528)
	at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1526)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
	at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1526)
	at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
	at org.scalatest.Suite$class.run(Suite.scala:1421)
	at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.main(Runner.scala:860)
	at org.scalatest.tools.Runner.main(Runner.scala)
2016-07-31 12:19:24,087 [ScalaTest-main-running-SymbolSuite] [ml.dmlc.mxnet.util.NativeLibraryLoader] [DEBUG] - Attempting to load libmxnet-scala.so
2016-07-31 12:19:24,087 [ScalaTest-main-running-SymbolSuite] [MXNetJVM] [ERROR] - Couldn't find native library mxnet-scala
*** RUN ABORTED ***
  java.lang.UnsatisfiedLinkError: Couldn't find the resource libmxnet-scala.so
  at ml.dmlc.mxnet.util.NativeLibraryLoader$.loadLibrary(NativeLibraryLoader.scala:72)
  at ml.dmlc.mxnet.Base$.<init>(Base.scala:48)
  at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
  at ml.dmlc.mxnet.Symbol$.initSymbolModule(Symbol.scala:1396)
  at ml.dmlc.mxnet.Symbol$.<init>(Symbol.scala:773)
  at ml.dmlc.mxnet.Symbol$.<clinit>(Symbol.scala)
  at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply$mcV$sp(SymbolSuite.scala:7)
  at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
  at ml.dmlc.mxnet.SymbolSuite$$anonfun$1.apply(SymbolSuite.scala:6)
  at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
  ...
2016-07-31 12:19:24,100 [Thread-0] [ml.dmlc.mxnet.util.NativeLibraryLoader] [INFO] - Deleting /tmp/mxnet2001619151824088638
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MXNet Scala Package - Parent ...................... SUCCESS [0.002s]
[INFO] MXNet Scala Package - Core ........................ FAILURE [2.185s]
[INFO] MXNet Scala Package - Native Parent ............... SKIPPED
[INFO] MXNet Scala Package - Native Linux-x86_64 GPU ..... SKIPPED
[INFO] MXNet Scala Package - Examples .................... SKIPPED
[INFO] MXNet Scala Package - Spark ML .................... SKIPPED
[INFO] MXNet Scala Package - Full Parent ................. SKIPPED
[INFO] MXNet Scala Package - Full Linux-x86_64 GPU ....... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -----------------------------------------------------
```

**Comment by javelinjs** [comment]
@zihaolucky Could you run `ls scala-package/native/linux-x86_64-gpu/target/` to check whether the .so is successfully generated?

**Comment by zihaolucky** [comment]
@javelinjs yep. Seems fine.

```
[zihao.zzh@gpu1031.et2 /home/zihao.zzh/packages/mxnet]
$ls scala-package/native/linux-x86_64-gpu/target/
custom-javah  lib  libmxnet-scala-linux-x86_64-gpu.so  objs
```

**Comment by javelinjs** [comment]
That's weird, could you make sure you're using the same `config.mk` as it was compiled? Try pasting following snippets here then I can check.

```
$ make scalatest
(cd /Users/lewis/Workspace/source-codes/forks/mxnet/scala-package; \
		mvn verify -Posx-x86_64-cpu -Dcxx="g++" \
			-Dcflags="-DMSHADOW_FORCE_STREAM -Wall -O3 -I/Users/lewis/Workspace/source-codes/forks/mxnet/mshadow/ -I/Users/lewis/Workspace/source-codes/forks/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -I/System/Library/Frameworks/Accelerate.framework/Versions/Current/Frameworks/vecLib.framework/Versions/Current/Headers/ -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp  -DMXNET_USE_DIST_KVSTORE -I/Users/lewis/Workspace/source-codes/forks/mxnet/ps-lite/include -I/Users/lewis/Workspace/source-codes/forks/mxnet/deps/include -DMXNET_USE_NVRTC=0" -Dldflags="-pthread -lm -framework Accelerate -fopenmp `pkg-config --libs opencv`  /Users/lewis/Workspace/source-codes/forks/mxnet/deps/lib/libprotobuf-lite.a /Users/lewis/Workspace/source-codes/forks/mxnet/deps/lib/libzmq.a" \
			-Dlddeps="/Users/lewis/Workspace/source-codes/forks/mxnet/ps-lite/build/libps.a /Users/lewis/Workspace/source-codes/forks/mxnet/dmlc-core/libdmlc.a" )
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
```

**Comment by zihaolucky** [comment]
```
[zihao.zzh@gpu1031.et2 /home/zihao.zzh/packages/mxnet]
$make scalatest
(cd /home/zihao.zzh/packages/mxnet/scala-package; \
	mvn verify -Plinux-x86_64-gpu -Dcxx="g++" \
		-Dcflags="-DMSHADOW_FORCE_STREAM -Wall -O3 -I/home/zihao.zzh/packages/mxnet/mshadow/ -I/home/zihao.zzh/packages/mxnet/dmlc-core/include -fPIC -Iinclude -msse3 -funroll-loops -Wno-unused-parameter -Wno-unknown-pragmas -I/usr/local/cuda-7.5/include -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_MKL=0 -DMSHADOW_RABIT_PS=0 -DMSHADOW_DIST_PS=0 -DMSDHADOW_USE_PASCAL=0 -DMXNET_USE_OPENCV=1 `pkg-config --cflags opencv` -fopenmp -DMSHADOW_USE_CUDNN=1  -DMXNET_USE_NVRTC=0" -Dldflags="-pthread -lm -lcudart -lcublas -lcurand -L/usr/local/cuda-7.5/lib64 -L/usr/local/cuda-7.5/lib -lopenblas -fopenmp -lrt `pkg-config --libs opencv` -lcudnn  -lcuda" \
		-Dlddeps="/home/zihao.zzh/packages/mxnet/dmlc-core/libdmlc.a" )
```

**Comment by zihaolucky** [comment]
Here's my info after `sudo make scalapkg`
```
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/zihao.zzh/packages/mxnet/scala-package/assembly/linux-x86_64-gpu/target/archive-tmp/mxnet-full_2.10-linux-x86_64-gpu-0.1.2-SNAPSHOT.jar
with assembly file: /home/zihao.zzh/packages/mxnet/scala-package/assembly/linux-x86_64-gpu/target/mxnet-full_2.10-linux-x86_64-gpu-0.1.2-SNAPSHOT.jar
[INFO]
[INFO] --- maven-jar-plugin:2.5:jar (default) @ mxnet-full_2.10-linux-x86_64-gpu ---
[WARNING] JAR will be empty - no content was marked for inclusion!
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MXNet Scala Package - Parent ...................... SUCCESS [0.073s]
[INFO] MXNet Scala Package - Core ........................ SUCCESS [37.148s]
[INFO] MXNet Scala Package - Native Parent ............... SUCCESS [0.002s]
[INFO] MXNet Scala Package - Native Linux-x86_64 GPU ..... SUCCESS [3.437s]
[INFO] MXNet Scala Package - Examples .................... SUCCESS [16.274s]
[INFO] MXNet Scala Package - Spark ML .................... SUCCESS [15.804s]
[INFO] MXNet Scala Package - Full Parent ................. SUCCESS [0.002s]
[INFO] MXNet Scala Package - Full Linux-x86_64 GPU ....... SUCCESS [7.194s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:20.532s
[INFO] Finished at: Mon Aug 08 16:28:29 CST 2016
[INFO] Final Memory: 60M/3035M
[INFO] ------------------------------------------------------------------------
(mxnet)
[zihao.zzh@gpu1031.et2 /home/zihao.zzh/packages/mxnet]
```

**Comment by cyq130** [comment]
I have solved this problem by extracting the libmxnet-scala.so from the mxnet-full_2.10-linux-x86_64-cpu-0.1.2-SNAPSHOT.jar. The only difference is I only used cpu mode.
$ jar -tf mxnet-full_2.10-linux-x86_64-cpu-0.1.2-SNAPSHOT.jar| grep mxnet-scala --color
$ lib/native/libmxnet-scala.so
Using "jar -xf mxnet-full_2.10-linux-x86_64-cpu-0.1.2-SNAPSHOT.jar" to extract the libmxnet-scala.so
After that, manually put the  libmxnet-scala.so to the java library path.
That works for me.

**Comment by javelinjs** [comment]
@cyq130 The problem is caused by lib name mismatch. I'm trying to figure out why it somehow happens.

**Comment by zihaolucky** [comment]
@cyq130 @javelinjs  I haven't found `libmxnet-scala.so` from the latest package in `~/packages/mxnet/scala-package/native/linux-x86_64-cpu/target/lib`, but I got `libmxnet-scala-linux-x86_64-cpu.so`. It's not `mxnet-scala` in https://github.com/dmlc/mxnet/blob/68989b68a63219a6997f9f89663938db9e37270d/scala-package/core/src/main/scala/ml/dmlc/mxnet/Base.scala#L46

**Comment by javelinjs** [comment]
It should be packed in assembly/mxnet-full-xxx.jar. The file is renamed during compile time.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by olga-gorun** [comment]
I have the same issue. Here is a result of run of GanMnist.main()

2017-12-18 13:51:27,429 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala from native path.
2017-12-18 13:51:27,431 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-gpu from native path.
2017-12-18 13:51:27,431 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-cpu from native path.
2017-12-18 13:51:27,431 [main] [MXNetJVM] [WARN] - MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].
2017-12-18 13:51:27,446 [main] [MXNetJVM] [ERROR] - Couldn't find native library mxnet-scala
2017-12-18 13:51:27,448 [Thread-0] [ml.dmlc.mxnet.util.NativeLibraryLoader] [INFO] - Deleting /tmp/mxnet2367230516169982814
Exception in thread "main" java.lang.UnsatisfiedLinkError: Couldn't find the resource libmxnet-scala.so
	at ml.dmlc.mxnet.util.NativeLibraryLoader$.loadLibrary(NativeLibraryLoader.scala:90)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:70)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Symbol$.initSymbolModule(Symbol.scala:1021)
	at ml.dmlc.mxnet.Symbol$.<init>(Symbol.scala:836)
	at ml.dmlc.mxnet.Symbol$.<clinit>(Symbol.scala)
	at ml.dmlc.mxnetexamples.imclassification.TrainMnist$.getMlp(TrainMnist.scala:32)
	at ml.dmlc.mxnetexamples.imclassification.TrainMnist$.main(TrainMnist.scala:109)
	at ml.dmlc.mxnetexamples.imclassification.TrainMnist.main(TrainMnist.scala)
