### ISSUE TITLE
Neural art save image error

### ISSUE THREAD

**Issue by Zepan** [apache/incubator-mxnet#2398]
sometimes it raise up this error:

```
INFO:root:save output to output/tmp_150.jpg
Traceback (most recent call last):
  File "run.py", line 221, in <module>
    SaveImage(new_img.asnumpy(), 'output/tmp_'+str(e+1)+'.jpg')
  File "run.py", line 89, in SaveImage
    io.imsave(filename, out)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_io.py", line 133, in imsave
    return call_plugin('imsave', fname, arr, plugin=plugin, **plugin_args)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 211, in call_plugin
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 259, in imsave
    img = ndarray_to_pil(arr, format_str=format_str)
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/pil_plugin.py", line 163, in ndarray_to_pil
    arr = img_as_ubyte(arr)
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 374, in img_as_ubyte
    return convert(image, np.uint8, force_copy)
  File "/usr/local/lib/python2.7/dist-packages/skimage/util/dtype.py", line 205, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1.
```

**Comment by antinucleon** [comment]
I think it is skimage bug. I repeat several times, sometimes it happens sometimes not.

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
