### ISSUE TITLE
error while using im2rec.py in windows

### ISSUE THREAD

**Issue by srand99** [apache/incubator-mxnet#2432]
It worked well in linux, but failed in windows.

I use release version mxnet-20160419, python 2.7.11, win7 x64

This is my bat file:
python im2rec.py ./train ./samples/ --list 1 --recursive 1 --train_ratio 0.9995
python im2rec.py ./train_train ./samples/ --color 0 --quality 100

I can get the *.lst file successfully, then I got an error:
Traceback (most recent call last):
  File "im2rec.py", line 217, in <module>
    main()
  File "im2rec.py", line 214, in main
    write_record(args, image_list)
  File "im2rec.py", line 138, in write_record
    p.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 419, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 681, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 748, in save_global
    (obj, module, name))
pickle.PicklingError: Can't pickle <function read_worker at 0x000000000311DBA8>: it's not found as __main__.read_worker
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 858, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 880, in load_eof
    raise EOFError
EOFError

I searched and tried some solutions about python, but the problem can not be fixed.
Anyone have met this problem and fixed it?
Thanks a lot!

**Comment by freddycct** [comment]
i recalled that i have problem with the threading which seems to be the problem here too. comment out the codes that involve forking and threading

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
