### ISSUE TITLE
[pooling layer] global pooling layer doesn't need kernel_size

### ISSUE THREAD

**Issue by voidrank** [apache/incubator-mxnet#2544]
```
pool10 = mx.symbol.Pooling(name='pool10', data=relu_conv10 , global_pool=True, pool_type='avg')

Traceback (most recent call last):
  File "convert_model.py", line 116, in <module>
    main()
  File "convert_model.py", line 37, in main
    prob, input_dim = proto2symbol(args.caffe_prototxt)
  File "/home/lsy/mxnet-1/tools/caffe_converter/convert_symbol.py", line 188, in proto2symbol
    exec(sym)
  File "<string>", line 67, in <module>
  File "/home/lsy/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
  File "/home/lsy/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Required parameter kernel of Shape(tuple) is not presented
```

**Comment by qiaohaijun** [comment]
```c++
 DMLC_DECLARE_PARAMETER(PoolingParam) {
    DMLC_DECLARE_FIELD(global_pool).set_default(false)
    .describe("Ignore kernel size, do global pooling based on current input feature map. "
              "This is useful for input with different shape");

    DMLC_DECLARE_FIELD(kernel)
    .set_expect_ndim(2).enforce_nonzero()
    .describe("pooling kernel size: (y, x)");

    DMLC_DECLARE_FIELD(pool_type)
    .add_enum("max", pool_enum::kMaxPooling)
    .add_enum("avg", pool_enum::kAvgPooling)
    .add_enum("sum", pool_enum::kSumPooling)
    .describe("Pooling type to be applied.");

    int stride_shape[] = {1, 1};
    DMLC_DECLARE_FIELD(stride).set_default(TShape(stride_shape, stride_shape + 2))
    .set_expect_ndim(2).enforce_nonzero()
    .describe("stride: for pooling (y, x)");

    int pad_shape[] = {0, 0};
    DMLC_DECLARE_FIELD(pad).set_default(TShape(pad_shape, pad_shape + 2))
    .set_expect_ndim(2)
    .describe("pad for pooling: (y, x)");
  }
};
```

**Comment by qiaohaijun** [comment]
```c++
    .set_expect_ndim(2).enforce_nonzero()
```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
