### ISSUE TITLE
neural-style/end-to-end : python boost_train.py  error: Check failed: (index) >= (0) 

### ISSUE THREAD

**Issue by visonpon** [apache/incubator-mxnet#2575]
**when i run the command like this**: ~/mxnet/example/neural-style/end_to_end$ python boost_train.py
i got an error as follow: 
mxnet.base.MXNetError: [09:50:43] src/storage/../common/lazy_alloc_array.h:54: **Check failed: (index) >= (0)**

**Comment by visonpon** [comment]
detail describe of the error is as follows:
[09:50:43] /home/visonpon/mxnet/dmlc-core/include/dmlc/./logging.h:235: [09:50:43] src/storage/../common/lazy_alloc_array.h:54: Check failed: (index) >= (0) 
Traceback (most recent call last):
  File "boost_train.py", line 23, in <module>
    style_mod = basic.get_style_module("style", dshape, ctx, vgg_params)
  File "/home/visonpon/mxnet/example/neural-style/end_to_end/basic.py", line 75, in get_style_module
    mod.bind(data_shapes=[("%s_data" % prefix, dshape)], for_training=False)
  File "/home/visonpon/mxnet/python/mxnet/module/module.py", line 257, in bind
    shared_group, logger=self.logger)
  File "/home/visonpon/mxnet/python/mxnet/module/executor_group.py", line 95, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/visonpon/mxnet/python/mxnet/module/executor_group.py", line 123, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "/home/visonpon/mxnet/python/mxnet/module/executor_group.py", line 391, in _bind_ith_exec
    context, self.logger)
  File "/home/visonpon/mxnet/python/mxnet/module/executor_group.py", line 369, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/home/visonpon/mxnet/python/mxnet/ndarray.py", line 801, in zeros
    arr = empty(shape, ctx, dtype)
  File "/home/visonpon/mxnet/python/mxnet/ndarray.py", line 537, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/visonpon/mxnet/python/mxnet/ndarray.py", line 68, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/home/visonpon/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:50:43] src/storage/../common/lazy_alloc_array.h:54: Check failed: (index) >= (0)

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
