### ISSUE TITLE
compile with USE_DIST_KVSTORE=1  but not work

### ISSUE THREAD

**Issue by hxiangwei** [apache/incubator-mxnet#2642]
I compiled mxnet on centos6.4 ,before make i set USE_DIST_KVSTORE=1 ,after execute "make scalapkg"  i submit the example jar with command
 "$SPARK_HOME/bin/spark-submit --master local --conf spark.dynamicAllocation.enabled=false --conf spark.speculation=false --class ml.dmlc.mxnet.spark.example.ClassificationExample --name mxnet --driver-memory 1g --executor-memory 1g --num-executors 2 --executor-cores 1 --jars mxnet/scala-package/assembly/linux-x86_64-cpu/target/mxnet-full_2.10-linux-x86_64-cpu-0.1.2-SNAPSHOT.jar,mxnet/scala-package/spark/target/classes/lib/args4j2.0.29.jar,mxnet/scala-package/spark/target/classes/lib/scala-library-2.10.4.jar,scala-package/spark/target/mxnet-spark_2.10-0.1.2-SNAPSHOT.jar mxnet/scala-package/spark/target/mxnet-spark_2.10-0.1.2-SNAPSHOT.jar --input mxnet/input --jars mxnet/scala-package/assembly/linux-x86_64-cpu/target/mxnet-full_2.10-linux-x86_64-cpu-0.1.2-SNAPSHOT.jar  --num-server 1 --num-worker 1 --java /usr/java/default/bin/java --model mlp --cpus 0,1 --num-epoch 5"

after a few minutes i got an error message:

16/07/07 16:16:57 ERROR executor.Executor: Exception in task 0.0 in stage 1.0 (TID 1)
ml.dmlc.mxnet.MXNetError: [16:16:57] include/mxnet/kvstore.h:161: compile with USE_DIST_KVSTORE=1 to init parameter server's environment
    at ml.dmlc.mxnet.Base$.checkCall(Base.scala:110)
    at ml.dmlc.mxnet.KVStoreServer$.init(KVStoreServer.scala:53)
    at ml.dmlc.mxnet.spark.MXNet$$anonfun$1.apply(MXNet.scala:134)
    at ml.dmlc.mxnet.spark.MXNet$$anonfun$1.apply(MXNet.scala:116)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
    at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
    at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
    at org.apache.spark.CacheManager.getOrCompute(CacheManager.scala:69)
    at org.apache.spark.rdd.RDD.iterator(RDD.scala:268)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
    at org.apache.spark.scheduler.Task.run(Task.scala:89)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

This confused me ,could somebody help me ?

**Comment by tylorhxw** [comment]
soved by set MXNET_USE_DIST_KVSTORE = 1

**Comment by piiswrong** [comment]
try git pull && git submodule update && make clean && make

**Comment by hoaphumanoid** [comment]
@tylorhxw I got the same problem when running the script run-mnist-example.sh. Could you please tell me how can I activate the MXNET_USE_DIST_KVSTORE  flag with this sh script? or in any other way?

**Comment by javelinjs** [comment]
Could you make sure you're using the latest version for both mxnet and its submodules?

**Comment by hoaphumanoid** [comment]
@javelinjs I have the commit 97fa49f5767421bbc717d61f40c6bdfd3c601872 which is from the 3rd of July

**Comment by titicaca** [comment]
@javelinjs  we have the same issue and are currently using the latest version.

**Comment by javelinjs** [comment]
Are you using the same jar on worker nodes?

**Comment by titicaca** [comment]
We tested on local machine by using two workers:
```
../../tools/launch.py -n 2 python train_mnist.py --kv-store dist_sync
```

**Comment by eric-haibin-lin** [comment]
Closing it for now due to inactivity. Please feel free to reopen for any follow-up discussions.
