### ISSUE TITLE
RuntimeError when running neural-style examples

### ISSUE THREAD

**Issue by atticcas** [apache/incubator-mxnet#2758]
When I try to run the neural-style example in /example/neural-style folder, I met the following problem:

```
Traceback (most recent call last):
  File "/home/myfile/mxnet/example/neural-style/run.py", line 11, in <module>
    from skimage import io, transform
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "/usr/local/lib/python2.7/dist-packages/skimage/io/collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "/usr/local/lib/python2.7/dist-packages/skimage/external/tifffile/__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "/usr/local/lib/python2.7/dist-packages/skimage/external/tifffile/tifffile.py", line 153, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version a but this version of numpy is 9
```

My python version is 2.7.6, and numpy version is 1.8. The operation system is Ubuntu 14.04.

**Comment by piiswrong** [comment]
@antinucleon

**Comment by bmorris3** [comment]
I'm also getting an issue like this from scikit-image in my [Read The Docs build](https://readthedocs.org/projects/shampoo/builds/4238986/).

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
