### ISSUE TITLE
problem of the version of im2rec.py

### ISSUE THREAD

**Issue by luoruisichuan** [apache/incubator-mxnet#2796]
when I use im2rec.py to create REC file, if I use the 20160202 version of im2rec.py, the command is
'D:\test>python im2rec.py d:/test/train2 d:/test/train/ '
it is OK, ' d:/test/train2' is the prefix of lst file,  and  'd:/test/train2.lst' and 'd:/test/train/' is the path of image files.

but if I use the 20160531 version of im2rec.py, the command is also
'D:\test>python im2rec.py d:/test/train2 d:/test/train/ '
but have the following error 

'D:\test>python im2rec.py d:/test/train2 d:/test/train/
Traceback (most recent call last):
  File "im2rec.py", line 218, in <module>
    main()
  File "im2rec.py", line 215, in main
    write_record(args, image_list)
  File "im2rec.py", line 139, in write_record
    p.start()
  File "C:\Users\Administrator\Anaconda2\lib\multiprocessing\process.py", line 1
30, in start
    self._popen = Popen(self)
  File "C:\Users\Administrator\Anaconda2\lib\multiprocessing\forking.py", line 2
77, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Users\Administrator\Anaconda2\lib\multiprocessing\forking.py", line 1
99, in dump'

does the 20160531verision of im2rec.py has bug?

@piiswrong 
thanks for your help very much.

**Comment by tornadomeet** [comment]
you can use the newest version

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
