### ISSUE TITLE
make  memcost example error

### ISSUE THREAD

**Issue by sofiawu** [apache/incubator-mxnet#3094]
Traceback (most recent call last):
File "inception_memcost.py", line 88, in 
grad_req=grad_req)
File "../../python/mxnet/symbol.py", line 671, in simple_bind
arg_shapes, _, aux_shapes = self.infer_shape(_kwargs)
File "../../python/mxnet/symbol.py", line 453, in infer_shape
return self._infer_shape_impl(False, *args, *kwargs)
File "../../python/mxnet/symbol.py", line 513, in _infer_shape_impl
ctypes.byref(complete)))
File "../../python/mxnet/base.py", line 77, in check_call
raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in ch_concat_3c_chconcat: [13:17:59] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (32,320,13,13). (first input shape: (32,576,14,14))
make: *_\* [with_inplace] Error 1

**Comment by piiswrong** [comment]
@antinucleon Seems to be pooling shape issue

**Comment by my777777** [comment]
I meet a same error, has this problem been resolved yet?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
