### ISSUE TITLE
Can mxnet use lmdb data?

### ISSUE THREAD

**Issue by IvyGongoogle** [apache/incubator-mxnet#3132]
Now caffe, Torch and Keras all  can use lmdb data. Can mxnet use lmdb data?
Thank you.

**Comment by piiswrong** [comment]
You can inherit mx.io.DataIter and read data from lmdb.
I don't recommend it though. lmdb seems to have random slowdown problems when data is bigger than memory.

**Comment by JulyUp** [comment]
@piiswrong Thank you very much. 

When I use the im2rec.py, I got a error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
Traceback (most recent call last):
IOError: [Errno 32] Broken pipe
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
    send(obj)
    send(obj)
    send(obj)
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
    send(obj)
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
    send(obj)
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
Traceback (most recent call last):
    send(obj)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
Traceback (most recent call last):
    send(obj)
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
IOError: [Errno 32] Broken pipe
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "gong2.py", line 34, in read_worker
    image_encode(item, q_out)
  File "gong2.py", line 22, in image_encode
    header = mx.recordio.IRHeader(0, item[2], item[0], 0)
AttributeError: 'module' object has no attribute 'recordio'
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    send(obj)
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "gong2.py", line 34, in read_worker
    image_encode(item, q_out)
  File "gong2.py", line 22, in image_encode
    header = mx.recordio.IRHeader(0, item[2], item[0], 0)
AttributeError: 'module' object has no attribute 'recordio'
    send(obj)
IOError: [Errno 32] Broken pipe
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "gong2.py", line 34, in read_worker
    image_encode(item, q_out)
  File "gong2.py", line 22, in image_encode
    header = mx.recordio.IRHeader(0, item[2], item[0], 0)
AttributeError: 'module' object has no attribute 'recordio'
IOError: [Errno 32] Broken pipe
Process Process-14:


What should I do?

**Comment by JulyUp** [comment]
@piiswrong  The module 'gong2.py' is a simple part of the original im2rec.py. But it should be right in syntax and function. I just do a test for my own need.

**Comment by SevenGong** [comment]
@piiswrong @piiswrong Thank you very much.

When I use the im2rec.py, I got a error:

Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
send(obj)
Traceback (most recent call last):
IOError: [Errno 32] Broken pipe
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
send(obj)
send(obj)
send(obj)
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
send(obj)
IOError: [Errno 32] Broken pipe
IOError: [Errno 32] Broken pipe
send(obj)
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
Traceback (most recent call last):
send(obj)
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
IOError: [Errno 32] Broken pipe
Traceback (most recent call last):
Traceback (most recent call last):
send(obj)
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
File "/usr/lib/python2.7/multiprocessing/queues.py", line 266, in _feed
IOError: [Errno 32] Broken pipe
Process Process-11:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(self._args, *self._kwargs)
File "gong2.py", line 34, in read_worker
image_encode(item, q_out)
File "gong2.py", line 22, in image_encode
header = mx.recordio.IRHeader(0, item[2], item[0], 0)
AttributeError: 'module' object has no attribute 'recordio'
Process Process-12:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
send(obj)
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(self._args, *self._kwargs)
File "gong2.py", line 34, in read_worker
image_encode(item, q_out)
File "gong2.py", line 22, in image_encode
header = mx.recordio.IRHeader(0, item[2], item[0], 0)
AttributeError: 'module' object has no attribute 'recordio'
send(obj)
IOError: [Errno 32] Broken pipe
Process Process-13:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(self._args, *self._kwargs)
File "gong2.py", line 34, in read_worker
image_encode(item, q_out)
File "gong2.py", line 22, in image_encode
header = mx.recordio.IRHeader(0, item[2], item[0], 0)
AttributeError: 'module' object has no attribute 'recordio'
IOError: [Errno 32] Broken pipe
Process Process-14:

What should I do?

**Comment by SevenGong** [comment]
@piiswrong The module 'gong2.py' is a simple part of the original im2rec.py. But it should be right in syntax and function. I just do a test for my own need.

**Comment by SevenGong** [comment]
@piiswrong Should this error be a problem about multiprocessing?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
