### ISSUE TITLE
Convert VGG_CNN_M_1024 Error

### ISSUE THREAD

**Issue by longwoo** [apache/incubator-mxnet#3175]
I can convert VGG16 and VGG19, but when I run `python convert_model.py VGG_CNN_M_1024_deploy.prototxt VGG_CNN_M_1024.caffemodel VGG1024`, it gives

```
Traceback (most recent call last):
  File "convert_model.py", line 108, in <module>
    main()
  File "convert_model.py", line 48, in main
    layers = parse.parse_caffemodel(args.caffe_model)
  File "/home/wulong/mxnet/tools/caffe_converter/caffe_parse/parse_from_protobuf.py", line 17, in parse_caffemodel
    netparam.ParseFromString(contents)
  File "/home/wulong/.local/lib/python2.7/site-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/home/wulong/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1082, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/home/wulong/.local/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 1118, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/home/wulong/.local/lib/python2.7/site-packages/google/protobuf/internal/decoder.py", line 610, in DecodeRepeatedField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
```

It contains `norm1 = mx.symbol.LRN(name='norm1', data=relu1 , alpha=0.000500, beta=0.750000, knorm=2.000000, nsize=5)` in VGG_CNN_M_1024 model. Is that means this layer do not belong to the `L2LayerParameter`,so the tool can not support @pluskid ?

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
