### ISSUE TITLE
Conduct prediction using pre-trained model on Android

### ISSUE THREAD

**Issue by charleslipku** [apache/incubator-mxnet#3351]
I already get compiled jni_libmnxet_predict.so, and follow the WhatsThis exmaple. But I come to an error when I try to run the code.

java.lang.UnsatisfiedLinkError: No implementation found for long org.dmlc.mxnet.Predictor.createPredictor(byte[], byte[], int, int, java.lang.String[], int[][]) (tried Java_org_dmlc_mxnet_Predictor_createPredictor and Java_org_dmlc_mxnet_Predictor_createPredictor___3B_3BII_3Ljava_lang_String_2_3_3I)

**Comment by d4wud** [comment]
I'm getting the same error.  Did you find a solution?

**Comment by sun9700** [comment]
0.9.4 still have this error, build with android-ndk-r14 for armv7a on Ubuntu 16.10

No implementation found for long org.dmlc.mxnet.Predictor.createPredictor(byte[], byte[], int, int, java.lang.String[], int[][]) 



03-31 22:20:36.468 11638-11638/com.happen.it.make.whatsthis E/art: No implementation found for long org.dmlc.mxnet.Predictor.createPredictor(byte[], byte[], int, int, java.lang.String[], int[][]) (tried Java_org_dmlc_mxnet_Predictor_createPredictor and Java_org_dmlc_mxnet_Predictor_createPredictor___3B_3BII_3Ljava_lang_String_2_3_3I)
03-31 22:20:36.501 11638-11638/com.happen.it.make.whatsthis E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.happen.it.make.whatsthis, PID: 11638
                                                                              java.lang.UnsatisfiedLinkError: No implementation found for long org.dmlc.mxnet.Predictor.createPredictor(byte[], byte[], int, int, java.lang.String[], int[][]) (tried Java_org_dmlc_mxnet_Predictor_createPredictor and Java_org_dmlc_mxnet_Predictor_createPredictor___3B_3BII_3Ljava_lang_String_2_3_3I)
                                                                                  at org.dmlc.mxnet.Predictor.createPredictor(Native Method)
                                                                                  at org.dmlc.mxnet.Predictor.<init>(Predictor.java:43)
                                                                                  at com.happen.it.make.whatisit.WhatsApplication.onCreate(WhatsApplication.java:48)
                                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
                                                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by sun9700** [comment]
@charleslipku @d4wud 
The solution is rename mxnet/amalgamation/jni_libmxnet_predict.so to libmxnet_predict.so
Do not use mxnet/lib/libmxnet_predict.so

What's more, link  with  -static-libstdc++
LDFLAGS+= -L${OPENBLAS_ROOT} -L${OPENBLAS_ROOT}/lib -static-libstdc++ 

the output is about 13.5 MB
The other steps is at
https://github.com/dmlc/mxnet/issues/4783

**Comment by sun9700** [comment]
@piiswrong is  amalgamation updating under plan?
Mxnet is much better than TensorFlow
hope for a better android support.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by dmazzoni** [comment]
@szha After building `libmxnet_predict.so` as described in #7146, and solving #8666 (where my environment is described), I experienced the same issue reported here. Unfortunately replacing `libmxnet_predict.so` with the renamed `jni_libmxnet_predict.so` didn't work, as now I get a SIGILL when starting the app on my Nexus 5:

```
11-16 14:47:32.774 10211-10211/com.happen.it.make.whatsthis A/libc: Fatal signal 4 (SIGILL), code 1, fault addr 0xa047be18 in tid 10211 (.make.whatsthis)
11-16 14:47:32.886 194-194/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-16 14:47:32.886 194-194/? A/DEBUG: Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/M4B30Z/3437181:user/release-keys'
11-16 14:47:32.886 194-194/? A/DEBUG: Revision: '11'
11-16 14:47:32.887 194-194/? A/DEBUG: ABI: 'arm'
11-16 14:47:32.887 194-194/? A/DEBUG: pid: 10211, tid: 10211, name: .make.whatsthis  >>> com.happen.it.make.whatsthis <<<
11-16 14:47:32.887 194-194/? A/DEBUG: signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr 0xa047be18
11-16 14:47:32.897 194-194/? A/DEBUG:     r0 a0cfe188  r1 00000081  r2 7fffffff  r3 00000000
11-16 14:47:32.898 194-194/? A/DEBUG:     r4 00000000  r5 00000000  r6 b4d26508  r7 beb378c8
11-16 14:47:32.898 194-194/? A/DEBUG:     r8 a03dcd60  r9 00000000  sl 00000001  fp beb37708
11-16 14:47:32.898 194-194/? A/DEBUG:     ip beb37618  sp beb37650  lr b6d32231  pc a047be18  cpsr 00070010
11-16 14:47:32.904 194-194/? A/DEBUG: backtrace:
11-16 14:47:32.904 194-194/? A/DEBUG:     #00 pc 00558e18  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (_ZN5mxnet14CopyFromToImplIN7mshadow3cpuES2_EEvRKNS_7NDArrayES5_NS_10RunContextE+200)
11-16 14:47:32.905 194-194/? A/DEBUG:     #01 pc 002b2a40  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so
11-16 14:47:32.905 194-194/? A/DEBUG:     #02 pc 004b2f9c  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (_ZNSt6__ndk110__function6__funcIZN5mxnet6Engine8PushSyncENS_8functionIFvNS2_10RunContextEEEENS2_7ContextERKNS_6vectorIPNS2_6engine3VarENS_9allocatorISC_EEEESH_NS2_10FnPropertyEiPKcEUlS5_NSA_18CallbackOnCompleteEE_NSD_ISM_EEFvS5_SL_EEclEOS5_OSL_+60)
11-16 14:47:32.905 194-194/? A/DEBUG:     #03 pc 004b9dc0  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (_ZN5mxnet6engine11NaiveEngine9PushAsyncENSt6__ndk18functionIFvNS_10RunContextENS0_18CallbackOnCompleteEEEENS_7ContextERKNS2_6vectorIPNS0_3VarENS2_9allocatorISB_EEEESG_NS_10FnPropertyEiPKc+96)
11-16 14:47:32.905 194-194/? A/DEBUG:     #04 pc 002ec6ac  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (_ZN5mxnet6Engine8PushSyncENSt6__ndk18functionIFvNS_10RunContextEEEENS_7ContextERKNS1_6vectorIPNS_6engine3VarENS1_9allocatorISA_EEEESF_NS_10FnPropertyEiPKc+276)
11-16 14:47:32.905 194-194/? A/DEBUG:     #05 pc 002499ac  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (_ZN5mxnet10CopyFromToERKNS_7NDArrayES2_i+576)
11-16 14:47:32.905 194-194/? A/DEBUG:     #06 pc 00299380  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (MXPredCreatePartialOut+9624)
11-16 14:47:32.905 194-194/? A/DEBUG:     #07 pc 002a74a0  /data/app/com.happen.it.make.whatsthis-2/lib/arm/libmxnet_predict.so (Java_org_dmlc_mxnet_Predictor_createPredictor+776)
11-16 14:47:32.905 194-194/? A/DEBUG:     #08 pc 000eaa29  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
11-16 14:47:32.905 194-194/? A/DEBUG:     #09 pc 000e6331  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
11-16 14:47:32.905 194-194/? A/DEBUG:     #10 pc 004029bb  /system/lib/libart.so (art_quick_invoke_static_stub+170)
11-16 14:47:32.905 194-194/? A/DEBUG:     #11 pc 007fd71c  [stack]
```

**Comment by billhyde** [comment]
@dmazzoni I have meet the same problem, have you solve this "Fatal signal 4 (SIGILL), code 1" problem? I tried a lot of ways to solve this, but all failed.

**Comment by dmazzoni** [comment]
@billhyde Sorry but I switched to Tensorflow, so I haven't tried anything more to make it work
