### ISSUE TITLE
Memory allocation failed after multiple call to Module.predict()

### ISSUE THREAD

**Issue by PrismQ** [apache/incubator-mxnet#3362]
Hi,
    I am using Module.predict to calculate some feature vector of my data. (outputshape=(batchsize,4096) )

After 97 calls to predict(), mxnet reported _Memory allocation failed_, and GPU monitoring software 
reported 7.6GB/8GB gpu mem usage. There are plenty of system RAM available.  Closing the python process will release GPU mem.

   Do I need to call some method to release GPU mem after predict() ?

``` python
ctx = mx.gpu(1)
mod = mx.mod.Module(out, context=ctx)
data = mx.nd.ones((1024, 3, 224, 224))  
iter = mx.io.NDArrayIter(data, batch_size=64)
mod.bind(iter.provide_data, for_training=False)
mod.set_params(arg_dict, {})

for i in range(100):
...     result = mod.predict(iter,reset=True)
...     
[02:38:03] D:\dev\mxnet\mxnet\dmlc-core\include\dmlc/logging.h:235: [02:38:03] d:\dev\mxnet\mxnet\src\storage\./pooled_storage_manager.h:62: Memory allocation failed.
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "D:\dev\mxnet\mxnet\python\mxnet\module\base_module.py", line 265, in predict
    for i in range(num_outputs)]
  File "D:\dev\mxnet\mxnet\python\mxnet\module\base_module.py", line 265, in <listcomp>
    for i in range(num_outputs)]
  File "D:\dev\mxnet\mxnet\python\mxnet\ndarray.py", line 915, in concatenate
    ret = empty((shape0,) + shape_rest, ctx=arrays[0].context, dtype=dtype)
  File "D:\dev\mxnet\mxnet\python\mxnet\ndarray.py", line 551, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "D:\dev\mxnet\mxnet\python\mxnet\ndarray.py", line 69, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "D:\dev\mxnet\mxnet\python\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [02:38:03] d:\dev\mxnet\mxnet\src\storage\./pooled_storage_manager.h:62: Memory allocation failed.
```

**Comment by piiswrong** [comment]
Could you post your full script? Is result saved somewhere in a list?

**Comment by PrismQ** [comment]
@piiswrong the script is here, the result is overwritten in every iteration of i
My Mxnet binary is compiled on ~2016/7/01.

```python
import mxnet as mx

out = mx.sym.load("d:/dev/mxnet/mxnet/tools/caffe_converter/vgg_face-symbol2.json")
# ctx = mx.cpu(0)
ctx = [mx.gpu(0), mx.gpu(1)]
arg_shapes, output_shapes, aux_shapes = out.infer_shape(data=(1, 3, 224, 224))
arg_names = out.list_arguments()
arg_dict = {}

pretrained = mx.nd.load("d:/dev/mxnet/mxnet/tools/caffe_converter/vgg_face-0001.params")
for name in arg_names:
    if name == "data":
        continue
    key = "arg:" + name
    if key in pretrained:
        arg_dict[name] = pretrained[key]
    else:
        print("Skip argument %s" % name)

print("load arg complete")
mod = mx.mod.Module(out, context=ctx)
data = mx.nd.ones((1024, 3, 224, 224))
iter = mx.io.NDArrayIter(data, batch_size=64)
mod.bind(iter.provide_data, for_training=False)
mod.set_params(arg_dict, {})
print("param set")
for i in range(1000):
    print(i, end='')
    result = mod.predict(iter, reset=True)
```

```
python test.py
load arg complete
param set
[12:09:12] D:\dev\mxnet\mxnet\dmlc-core\include\dmlc/logging.h:235: [12:09:12] d:\dev\mxnet\mxnet\src\storage\./pooled_storage_manager.h:62: Memory allocation failed.
01234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253545556575859606162636465666768697071727374757677787980818283848586878889909192939495969798991001011021031041051061071081091101111121131141151161171181191201211221231241251261271281291301311321331341351361371381
39140141142143144145146147148149150151152153154155156157158159160161162163164Traceback (most recent call last):
  File "test.py", line 29, in <module>
    result = mod.predict(iter, reset=True)
  File "d:\dev\mxnet\mxnet\python\mxnet\module\base_module.py", line 265, in predict
    for i in range(num_outputs)]
  File "d:\dev\mxnet\mxnet\python\mxnet\module\base_module.py", line 265, in <listcomp>
    for i in range(num_outputs)]
  File "d:\dev\mxnet\mxnet\python\mxnet\ndarray.py", line 915, in concatenate
    ret = empty((shape0,) + shape_rest, ctx=arrays[0].context, dtype=dtype)
  File "d:\dev\mxnet\mxnet\python\mxnet\ndarray.py", line 551, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "d:\dev\mxnet\mxnet\python\mxnet\ndarray.py", line 69, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "d:\dev\mxnet\mxnet\python\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [12:09:12] d:\dev\mxnet\mxnet\src\storage\./pooled_storage_manager.h:62: Memory allocation failed.
```

**Comment by PrismQ** [comment]
I checked if the result `ndarray.__del__()` is called by inserting `print` into `__del__()`

```python
    def __del__(self):
        if hasattr(self,"x"):
            print(self.x)
        check_call(_LIB.MXNDArrayFree(self.handle))
```

then begin the loop:
```python
for i in range(1000):
    result = mod.predict(iter, reset=True)
    result.x = i
```

the result is
```
1
2
.....
161
162
mxnet.base.MXNetError: .... Memory allocation failed. .....
163
```

seems that `__del__()` is called on every result.

**Comment by tqchen** [comment]
@piiswrong Seems was due to the memory re-allocation line too high problem

**Comment by piiswrong** [comment]
@PrismQ Could you try the current master? there was a few changes since 07/01

**Comment by PrismQ** [comment]
@piiswrong I tried the current master and got the same result (Memory allocation failed)

**Comment by piiswrong** [comment]
Could you also pose vgg_face-symbol2.json?

**Comment by PrismQ** [comment]
Here it is. It's generated by `tools/caffe_converter` then manually edited to remove the classification output layers.

[vggface-symbol2.json.txt](https://github.com/dmlc/mxnet/files/491511/vggface-symbol2.json.txt)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
