### ISSUE TITLE
How should I create the functions "provide_data" and "provide_label" properly in DataIter class?

### ISSUE THREAD

**Issue by yxchng** [apache/incubator-mxnet#3455]
``` python
from mxnet.io import DataIter
from mxnet.io import DataBatch
import mxnet as mx
import numpy as np
import h5py

class BatchIterator(DataIter):
    def __init__(self, data_path, batch_size, num_heatmaps):
        self.data_path = data_path
        self.batch_size = batch_size
        self.num_heatmaps = num_heatmaps
        self.cursor = 0
        self.batch_data = None
        self.batch_heatmaps = None
        self.data = h5py.File(data_path, 'r')
        self.num_data = len(self.data['data'])

    def reset(self):
        self.cursor = 0

    def next(self):
        if self.iter_next():
            self.batch_data = self.data['data'][self.cursor: self.cursor + self.batch_size].astype('float32') / 255.0 
            self.batch_heatmaps = [self.data['labels'][self.cursor: self.cursor + self.batch_size] * self.num_heatmaps]
            return DataBatch(data = [mx.nd.array(self.batch_data)], 
                   label = [mx.nd.array(self.batch_heatmaps)],
                   pad = self.getpad(),
                   index = None)
        else:
            raise StopIteration

    def provide_data(self):
        res = [("batch_data", tuple(list(v.shape[0:]))) for v in self.batch_data]
        return res

    def provide_label(self):
        res = [("batch_heatmaps", tuple(list(v.shape[0:]))) for v in self.batch_heatmaps]
        return res

    def iter_next(self):
        self.cursor += self.batch_size
        if self.cursor <= self.num_data:
            return True
        else:
            return False

    def getpad(self):
        return 0
```

I have encountering the following error when I run my program:

Traceback (most recent call last):
  File "stacked_hourglass_v2_mxnet.py", line 111, in <module>
    eval_metric = mx.metric.MSE
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 742, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
TypeError: unsupported operand type(s) for +: 'instancemethod' and 'instancemethod'

I am not sure what I am doing wrong.

**Comment by tornadomeet** [comment]
@yxchng try ```res = [("batch_data", tuple(list(a.shape[0:])))]``` in provide_data and provide_label funciton.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
