### ISSUE TITLE
Can't use mxnet after Quick Installation

### ISSUE THREAD

**Issue by QuantumLiu** [apache/incubator-mxnet#3739]
I'can't use mxnet after Quick Installation
I'm using Ubuntu 16.04,GTX1060,cuda8.0,cudnnv5.1
>>> import mxnet as mx
>>> a = mx.nd.ones((2, 3),
... mx.gpu())
[11:28:30] /home/quantumliu/MXNet/mxnet/dmlc-core/include/dmlc/./logging.h:235: [11:28:30] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/quantumliu/MXNet/mxnet/python/mxnet/ndarray.py", line 894, in ones
    arr = empty(shape, ctx, dtype)
  File "/home/quantumliu/MXNet/mxnet/python/mxnet/ndarray.py", line 611, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/quantumliu/MXNet/mxnet/python/mxnet/ndarray.py", line 69, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/home/quantumliu/MXNet/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:28:30] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage
>>>

**Comment by VoVAllen** [comment]
copy make/config.mk to the root directory and change USE_CUDA=0 to USE_CUDA=1
Then make clean
Then make -j8

**Comment by QuantumLiu** [comment]
quantumliu@ubuntu:~/MXNet$ sudo cp mxnet/make/config.mk .
[sudo] quantumliu 的密码： 
quantumliu@ubuntu:~/MXNet$ make clean
make: *** No rule to make target 'clean'。 停止。
quantumliu@ubuntu:~/MXNet$ make -j32
make: *** 没有指明目标并且找不到 makefile。 停止。
quantumliu@ubuntu:~/MXNet$

**Comment by VoVAllen** [comment]
你拷错目录了。应该cd mxnet然后cp make/config,mk .

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!

**Comment by zfs1212** [comment]
Why is there no make folder in my mxnet directory?
