### ISSUE TITLE
how to debug the error? 

### ISSUE THREAD

**Issue by rongrongxiangxin** [apache/incubator-mxnet#3969]
python main.py 
(41084, 3, 299, 299)
(5672, 3, 299, 299)
[23:56:46] /dev/disk2/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:56:46] include/mxnet/./tensor_blob.h:742: Check failed: (this->shape_.Size()) == (shape.Size()) TBlob.get_with_shape: new and old shape do not match total elements
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    train_iter = mx.io.NDArrayIter(data=train_data, label=train_label,batch_size=batch_size,shuffle=True)
  File "/dev/disk2/mxnet/python/mxnet/io.py", line 430, in __init__
    self.data = _init_data(data, allow_empty=False, default_name='data')
  File "/dev/disk2/mxnet/python/mxnet/io.py", line 398, in _init_data
    "should be NDArray or numpy.ndarray")
TypeError: Invalid type '<type 'numpy.ndarray'>' for data, should be NDArray or numpy.ndarray

**Comment by piiswrong** [comment]
Please post a reproducible script

**Comment by rongrongxiangxin** [comment]
@piiswrong   main scripts are as follows:
train_data = np.load('X_train.npy')
val_data = np.load('X_val.npy')
train_label = np.load('Y_train.npy')
val_label = np.load('Y_val.npy')
train_iter = mx.io.NDArrayIter(data=train_data, label=train_label,batch_size=batch_size,shuffle=True)
val_iter = mx.io.NDArrayIter(data=val_data, label=val_label,batch_size=batch_size)

**Comment by hellowilman** [comment]
same problem. any one can help? thx

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
