### ISSUE TITLE
rcnn train_end2end.py error: Cannot find custom operator type proposal

### ISSUE THREAD

**Issue by forcecore** [apache/incubator-mxnet#4007]
I've fixed all the import error and print <-> print() compatibility issue to run train_end2end.py with Python 3. (will not submit the changes since I will not test the code with Python 2) However, the training will still not run:

```
D:\work\rcnn>python
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z

D:\work\rcnn>python train_end2end.py
INFO:root:Namespace(devkit_path='D:\\work\\rcnn\\data\\VOCdevkit', factor_step=50000, frequent=20, gpu_ids='0', image_set='trainval', kv_store='device', load_epoch=0, lr=0.001, mom=0.9, monitor=False, no_flip=False, num_classes=21, num_epoch=7, prefix='D:\\work\\rcnn\\model\\faster-rcnn', pretrained='D:\\work\\rcnn\\model\\vgg16', resume=False, root_path='D:\\work\\rcnn\\data', test_image_set='test', wd=0.0005, work_load_list=None, year='2007')
INFO:root:########## TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END #############
[21:52:21] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [21:52:21] d:\chhong\mxnet\src\operator\./custom-inl.h:85: Check failed: (registry_.find(param_.op_type)) != (registry_.end()) Cannot find custom operator type proposal
Traceback (most recent call last):
  File "train_end2end.py", line 170, in <module>
    args.work_load_list, args.resume, not args.no_flip, args.factor_step)
  File "train_end2end.py", line 32, in end2end_train
    sym = get_faster_rcnn(num_classes=num_classes)
  File "D:\work\rcnn\rcnn\symbol.py", line 352, in get_faster_rcnn
    op_type='proposal', feat_stride=16, scales=(8, 16, 32), ratios=(0.5, 1, 2), is_train=True)  # TODO(be careful of cls_prob)
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:52:21] d:\chhong\mxnet\src\operator\./custom-inl.h:85: Check failed: (registry_.find(param_.op_type)) != (registry_.end()) Cannot find custom operator type proposal
```

**Comment by piiswrong** [comment]
@precedenceguo does custom operator work in python3?

**Comment by precedenceguo** [comment]
File "D:\work\rcnn\rcnn\symbol.py", line 352, in get_faster_rcnn

**Comment by forcecore** [comment]
I did change symbol.py to make it run from Python3, the above error message have an offset in the line numbers. I'll run again without the offset: (Release windows binary build 20160531)

```
D:\work\rcnn>python train_end2end.py
INFO:root:Namespace(devkit_path='D:\\work\\rcnn\\data\\VOCdevkit', factor_step=50000, frequent=20, gpu_ids='0', image_set='trainval', kv_store='device', load_epoch=0, lr=0.001, mom=0.9, monitor=False, no_flip=False, num_classes=21, num_epoch=7, prefix='D:\\work\\rcnn\\model\\faster-rcnn', pretrained='D:\\work\\rcnn\\model\\vgg16', resume=False, root_path='D:\\work\\rcnn\\data', test_image_set='test', wd=0.0005, work_load_list=None, year='2007')
INFO:root:########## TRAIN FASTER-RCNN WITH APPROXIMATE JOINT END2END #############
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\operator.py", line 579, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() keywords must be strings
Traceback (most recent call last):
  File "train_end2end.py", line 170, in <module>
    args.work_load_list, args.resume, not args.no_flip, args.factor_step)
  File "train_end2end.py", line 32, in end2end_train
    sym = get_faster_rcnn(num_classes=num_classes)
  File "D:\work\rcnn\rcnn\symbol.py", line 350, in get_faster_rcnn
    op_type='proposal', feat_stride=16, scales=(8, 16, 32), ratios=(0.5, 1, 2), is_train=True)  # TODO(be careful of cls_prob)
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
OSError: exception: access violation writing 0x0000000000000000
```

**Comment by precedenceguo** [comment]
Now the error changed.
Please try https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/custom_softmax.py to make sure customop works in your environment first.
If so, please look into rpn/proposal.py and check ProposalProp and see if there is anything that is not compatible with python3.

**Comment by forcecore** [comment]
I got a very unexpected error:

```
{ numpy-ops }  » python3 custom_softmax.py         ~/work/mxnet-master/example/numpy-ops 1
--2016-11-28 20:30:09--  http://data.mxnet.io/mxnet/data/mnist.zip
Resolving data.mxnet.io (data.mxnet.io)... 54.208.175.7
Connecting to data.mxnet.io (data.mxnet.io)|54.208.175.7|:80... connected.
,HTTP request sent, awaiting response... 200 OK
Length: 11595270 (11M) [application/zip]
Saving to: ‘data/mnist.zip.2’

mnist.zip.2             100%[==============================>]  11.06M  2.43MB/s   in 4.6s

2016-11-28 20:30:13 (2.41 MB/s) - ‘data/mnist.zip.2’ saved [11595270/11595270]

Archive:  mnist.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of mnist.zip or
        mnist.zip.zip, and cannot find mnist.zip.ZIP, period.
[20:30:13] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [20:30:13] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "data/train-images-idx3-ubyte"
Traceback (most recent call last):
  File "custom_softmax.py", line 57, in <module>
    train, val = mnist_iterator(batch_size=100, input_shape = (784,))
  File "D:\work\mxnet-master\example\numpy-ops\data.py", line 23, in mnist_iterator
    flat=flat)
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\io.py", line 582, in creator
    ctypes.byref(iter_handle)))
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:30:13] D:\chhong\mxnet\dmlc-core\src\io\local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "data/train-images-idx3-ubyte"
```

Well, I ran twice, that's why I get  mnist.zip.2.
I think the dataset download was successful but there's something wrong with unarchiving the zip file.

**Comment by forcecore** [comment]
```
{ numpy-ops }  » python3 custom_softmax.py           ~/work/mxnet-master/example/numpy-ops
--2016-11-28 20:33:42--  http://data.mxnet.io/mxnet/data/mnist.zip
Resolving data.mxnet.io (data.mxnet.io)... 54.208.175.7
Connecting to data.mxnet.io (data.mxnet.io)|54.208.175.7|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11595270 (11M) [application/zip]
Saving to: ‘data/mnist.zip’

mnist.zip               100%[==============================>]  11.06M  2.43MB/s   in 4.6s

2016-11-28 20:33:46 (2.41 MB/s) - ‘data/mnist.zip’ saved [11595270/11595270]

Archive:  mnist.zip
  inflating: t10k-images-idx3-ubyte
  inflating: t10k-labels-idx1-ubyte
  inflating: train-images-idx3-ubyte
  inflating: train-labels-idx1-ubyte
[20:33:49] D:\chhong\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[20:33:50] D:\chhong\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
INFO:root:Start training with [cpu(0)]
INFO:root:Epoch[0] Batch [100]  Speed: 39999.62 samples/sec     Train-accuracy=0.139400
INFO:root:Epoch[0] Batch [200]  Speed: 40066.83 samples/sec     Train-accuracy=0.720600
INFO:root:Epoch[0] Batch [300]  Speed: 39124.69 samples/sec     Train-accuracy=0.894900
INFO:root:Epoch[0] Batch [400]  Speed: 43626.14 samples/sec     Train-accuracy=0.920800
INFO:root:Epoch[0] Batch [500]  Speed: 39999.54 samples/sec     Train-accuracy=0.934300
INFO:root:Epoch[0] Batch [600]  Speed: 38372.48 samples/sec     Train-accuracy=0.947700
INFO:root:Epoch[0] Resetting Data Iterator
INFO:root:Epoch[0] Time cost=1.512
INFO:root:Epoch[0] Validation-accuracy=0.942200
INFO:root:Epoch[1] Batch [100]  Speed: 41464.29 samples/sec     Train-accuracy=0.951800
INFO:root:Epoch[1] Batch [200]  Speed: 38450.22 samples/sec     Train-accuracy=0.953900
INFO:root:Epoch[1] Batch [300]  Speed: 38763.54 samples/sec     Train-accuracy=0.959100
INFO:root:Epoch[1] Batch [400]  Speed: 38882.88 samples/sec     Train-accuracy=0.958700
INFO:root:Epoch[1] Batch [500]  Speed: 38797.49 samples/sec     Train-accuracy=0.964000
INFO:root:Epoch[1] Batch [600]  Speed: 44942.79 samples/sec     Train-accuracy=0.967400
INFO:root:Epoch[1] Resetting Data Iterator
```

custom_softmax.py seems to work fine.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
