### ISSUE TITLE
"compile with USE_DIST_KVSTORE=1 to use dist_sync", on Windows binary distribution

### ISSUE THREAD

**Issue by forcecore** [apache/incubator-mxnet#4083]
It seems Windows distributions don't have no distributed training support. Is this due to platform problem?

Steps to reproduce: run the commands tools/launch.py runs, on Windows

{ mxnet }  $ export DMLC_NUM_WORKER=2
{ mxnet }  $ export DMLC_ROLE=server
{ mxnet }  $ export DMLC_PS_ROOT_PORT=9098
{ mxnet }  $ export DMLC_PS_ROOT_URI=mxnet-ps0
{ mxnet }  $ export DMLC_NUM_SERVER=2
$ python3 train_mnist.py --kv-store dist_sync

[21:25:50] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:235: [21:25:50] D:\chhong\mxnet\src\kvstore\kvstore.cc:41: compile with USE_DIST_KVSTORE=1 to use dist_sync
Traceback (most recent call last):
  File "train_mnist.py", line 76, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "D:\work\mxnet\example\image-classification\common\fit.py", line 95, in fit
    kv = mx.kvstore.create(args.kv_store)
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\kvstore.py", line 378, in create
    ctypes.byref(handle)))
  File "C:\Program Files\Python35\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:25:50] D:\chhong\mxnet\src\kvstore\kvstore.cc:41: compile with USE_DIST_KVSTORE=1 to use dist_sync

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
