### ISSUE TITLE
caffe converter tools doesn't support PReLU layer in caffe

### ISSUE THREAD

**Issue by fengshikun** [apache/incubator-mxnet#4139]
It will generate the error when run the `convert_model.py`:
```

Traceback (most recent call last):
  File "convert_model.py", line 112, in <module>
    main()
  File "convert_model.py", line 39, in main
    prob, input_dim = proto2symbol(args.caffe_prototxt)
  File "/home/kun/Documents/mxnet_origin/tools/caffe_converter/convert_symbol.py", line 195, in proto2symbol
    sym, output_name, input_dim = proto2script(proto_file)
  File "/home/kun/Documents/mxnet_origin/tools/caffe_converter/convert_symbol.py", line 170, in proto2script
    raise Exception('Unknown Layer %s!' % layer[i].type)
Exception: Unknown Layer PReLU!
```
Any ideas to solve this? thanks!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
