### ISSUE TITLE
mxnet.base.MXNetError: InferShape Error in score's weight argument

### ISSUE THREAD

**Issue by Leloocker** [apache/incubator-mxnet#4147]
I fine-tuned fcn-xs  with my dataset, there 's no error during training, but when I try to segment a new image with:
python image_segmentation.py
error occurs:

Traceback (most recent call last):
  File "image_segmentaion.py", line 58, in <module>
    main()
  File "image_segmentaion.py", line 49, in main
    exector = fcnxs.bind(ctx, fcnxs_args ,args_grad=None, grad_req="null", aux_states=fcnxs_args)
  File "/home/hliu/MXNet/mxnet/python/mxnet/symbol.py", line 844, in bind
    ctypes.byref(handle)))
  File "/home/hliu/MXNet/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

**Comment by tornadomeet** [comment]
does the label name in your symbol is `softmax_label`? please post your symbol file.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
