### ISSUE TITLE
BatchNorm -> Dropout may fail when os.environ['MXNET_BACKWARD_DO_MIRROR'] = '1'

### ISSUE THREAD

**Issue by itijyou** [apache/incubator-mxnet#4187]
Given:
os.environ['MXNET_BACKWARD_DO_MIRROR'] = '1'
mxnet being built with cudnn-8.0-v5.1
a Dropout layer directly after a BatchNorm layer will cause the below error.

## Environment info
Operating System: Linux

Package used (Python/R/Scala/Julia): Python

MXNet commit hash (`git rev-parse HEAD`): 7907e452752a2d2d12d167076cdf7d375c269ade

Python version and distribution: 2.7.5

## Error Message:

```
[mxnet_origin]$ python tests/python/train/test_conv_gpu.py
[04:28:21] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(100,1,28,28)
[04:28:21] src/engine/engine.cc:36: MXNet start using engine: NaiveEngine
[04:28:22] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(100,1,28,28)
INFO:root:Start training with [gpu(0)]
Start training with [gpu(0)]
[04:29:06] /home/acvt/Documents/mxnet_origin/dmlc-core/include/dmlc/logging.h:235: [04:29:06] src/operator/./cudnn_batch_norm-inl.h:57: Check failed: (req[cudnnbatchnorm::kOut]) == (kWriteTo) 
Traceback (most recent call last):
  File "tests/python/train/test_conv_gpu.py", line 81, in <module>
    test_mnist()
  File "tests/python/train/test_conv_gpu.py", line 68, in test_mnist
    eval_data=val_dataiter)
  File "/home/acvt/Documents/mxnet_origin/python/mxnet/model.py", line 811, in fit
    sym_gen=self.sym_gen)
  File "/home/acvt/Documents/mxnet_origin/python/mxnet/model.py", line 242, in _train_multi_device
    executor_manager.backward()
  File "/home/acvt/Documents/mxnet_origin/python/mxnet/executor_manager.py", line 418, in backward
    self.curr_execgrp.backward()
  File "/home/acvt/Documents/mxnet_origin/python/mxnet/executor_manager.py", line 268, in backward
    texec.backward()
  File "/home/acvt/Documents/mxnet_origin/python/mxnet/executor.py", line 147, in backward
    ndarray))
  File "/home/acvt/Documents/mxnet_origin/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [04:29:06] src/operator/./cudnn_batch_norm-inl.h:57: Check failed: (req[cudnnbatchnorm::kOut]) == (kWriteTo) 
terminate called without an active exception
Aborted
```

## Minimum reproducible example

Just add one Dropout layer into the test case:
tests/python/train/test_conv_gpu.py

```Python
import sys
sys.path.insert(0, '../../python')
import mxnet as mx
import numpy as np
import os, pickle, gzip
import logging
from common import get_data

#os.environ['MXNET_ENGINE_TYPE'] = 'NaiveEngine'
os.environ['MXNET_BACKWARD_DO_MIRROR'] = '1'

# symbol net
batch_size = 100

data = mx.symbol.Variable('data')
conv1= mx.symbol.Convolution(data = data, name='conv1', num_filter=32, kernel=(3,3), stride=(2,2))
bn1 = mx.symbol.BatchNorm(data = conv1, name="bn1")
#
# act1 = mx.symbol.Activation(data = bn1, name='relu1', act_type="relu")
# do1 = mx.symbol.Dropout(data = act1, name='do1')
# mp1 = mx.symbol.Pooling(data = do1, name = 'mp1', kernel=(2,2), stride=(2,2), pool_type='max')
#
do1 = mx.symbol.Dropout(data = bn1, name='do1')
act1 = mx.symbol.Activation(data = do1, name='relu1', act_type="relu")
mp1 = mx.symbol.Pooling(data = act1, name = 'mp1', kernel=(2,2), stride=(2,2), pool_type='max')
#

conv2= mx.symbol.Convolution(data = mp1, name='conv2', num_filter=32, kernel=(3,3), stride=(2,2))
bn2 = mx.symbol.BatchNorm(data = conv2, name="bn2")
act2 = mx.symbol.Activation(data = bn2, name='relu2', act_type="relu")
mp2 = mx.symbol.Pooling(data = act2, name = 'mp2', kernel=(2,2), stride=(2,2), pool_type='max')


fl = mx.symbol.Flatten(data = mp2, name="flatten")
fc2 = mx.symbol.FullyConnected(data = fl, name='fc2', num_hidden=10)
softmax = mx.symbol.SoftmaxOutput(data = fc2, name = 'sm')

num_epoch = 1
model = mx.model.FeedForward(softmax, mx.gpu(0),
                             num_epoch=num_epoch,
                             learning_rate=0.1, wd=0.0001,
                             momentum=0.9)
# check data
get_data.GetMNIST_ubyte()

train_dataiter = mx.io.MNISTIter(
        image="data/train-images-idx3-ubyte",
        label="data/train-labels-idx1-ubyte",
        data_shape=(1, 28, 28),
        label_name='sm_label',
        batch_size=batch_size, shuffle=True, flat=False, silent=False, seed=10)
val_dataiter = mx.io.MNISTIter(
        image="data/t10k-images-idx3-ubyte",
        label="data/t10k-labels-idx1-ubyte",
        data_shape=(1, 28, 28),
        label_name='sm_label',
        batch_size=batch_size, shuffle=True, flat=False, silent=False)

def test_mnist():
    # print logging by default
    logging.basicConfig(level=logging.DEBUG)
    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    logging.getLogger('').addHandler(console)

    model.fit(X=train_dataiter,
              eval_data=val_dataiter)
    logging.info('Finish fit...')
    prob = model.predict(val_dataiter)
    logging.info('Finish predict...')
    val_dataiter.reset()
    y = np.concatenate([batch.label[0].asnumpy() for batch in val_dataiter]).astype('int')
    py = np.argmax(prob, axis=1)
    acc1 = float(np.sum(py == y)) / len(y)
    logging.info('final accuracy = %f', acc1)
    assert(acc1 > 0.94)


if __name__ == "__main__":
    test_mnist()
```

## Steps to reproduce

1. Run the above modified test case.

## What have you tried to solve it?

1. Inserting an ReLU layer between the BatchNorm and Dropout layers will suppress the error.
2. Building mxnet with cudnn-7.0-v4.0.7 will suppress the error.
3. Without setting os.environ['MXNET_BACKWARD_DO_MIRROR'] = '1', the error will not occur.

**Comment by piiswrong** [comment]
@tqchen

**Comment by tqchen** [comment]
This was not a problem of mirror, but problem of cudnn batchnorm. Under mirror option, the forward batchnorm recomputation won't be needed by Dropout

So https://github.com/dmlc/mxnet/blob/master/src/operator/cudnn_batch_norm-inl.h#L57 failed because the actual request should be kNullOp. This fails because CUDNN batchnorm does not support kNullOp

This problem should not occur in NNVM branch, because the actual forward recompute will get dropped. Nevethe less it would be good to add support for kNullOp to CuDNN BatchNorm

**Comment by pineking** [comment]
btw: @tqchen @piiswrong when will  be the NNVM branch merged into the master?

**Comment by piiswrong** [comment]
soon...
development is basically complete. We are doing last stage testing.
if you can give it a try and report bugs it would help a lot

**Comment by pineking** [comment]
sure, I will have a try, are there some design documents to introduce the difference and improvements compared to master branch ?

**Comment by tqchen** [comment]
see 
- https://github.com/dmlc/nnvm/blob/master/docs/overview.md
- https://github.com/dmlc/mxnet/issues/3248

**Comment by itijyou** [comment]
@tqchen Thanks a lot! So, that means it will not be fixed recently.
In that case, would it be safe to make the below change in StaticGraph::MakeBackwardPass to simply walk around this error?
```
if (nodes[nid].get_attr("force_mirroring", false)) return true;
if (nodes[nid].get_attr("no_mirroring", false)) return false;
```
After that, set the `no_mirroring' attribute for BatchNorm layers followed by Dropout layers.

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
