### ISSUE TITLE
Check failed: from.shape() == to->shape() operands shape mismatch

### ISSUE THREAD

**Issue by windmaple** [apache/incubator-mxnet#4446]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
mac

Compiler:

Package used (Python/R/Scala/Julia):
python

MXNet version:

Or if installed from source:
pip install mxnet

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
[14:51:23] ./dmlc-core/include/dmlc/logging.h:208: [14:51:23] src/ndarray/ndarray.cc:159: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "/Users/weiwe/Desktop/alexa-planestrike/mxnet_train.py", line 181, in <module>
    board_position_log, action_log, hit_log = play_game(training=TRAINING, first_game=(game==0))
  File "/Users/weiwe/Desktop/alexa-planestrike/mxnet_train.py", line 89, in play_game
    tmp = model.predict(X=predict_iter)[0]
  File "/Users/weiwe/tensorflow/lib/python2.7/site-packages/mxnet/model.py", line 641, in predict
    self._init_predictor(data_shapes)
  File "/Users/weiwe/tensorflow/lib/python2.7/site-packages/mxnet/model.py", line 576, in _init_predictor
    pred_exec.copy_params_from(self.arg_params, self.aux_params)
  File "/Users/weiwe/tensorflow/lib/python2.7/site-packages/mxnet/executor.py", line 179, in copy_params_from
    array.copyto(self.arg_dict[name])
  File "/Users/weiwe/tensorflow/lib/python2.7/site-packages/mxnet/ndarray.py", line 351, in copyto
    return NDArray._copyto(self, out=other)
  File "/Users/weiwe/tensorflow/lib/python2.7/site-packages/mxnet/ndarray.py", line 645, in unary_ndarray_function
    c_array(NDArrayHandle, (out.handle,))))
  File "/Users/weiwe/tensorflow/lib/python2.7/site-packages/mxnet/base.py", line 74, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:51:23] src/ndarray/ndarray.cc:159: Check failed: from.shape() == to->shape() operands shape mismatch

Process finished with exit code 1
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

            model = mx.model.FeedForward(symbol=mlp, num_epoch=1, learning_rate=reward*ALPHA)
            current_board_ndarray = np.array(current_board, dtype=np.int8)
            action_ndarray = np.array([action], dtype=np.int8)
            train_iter = mx.io.NDArrayIter(current_board_ndarray, action_ndarray, batch_size=1, shuffle=False)
            model.fit(X=train_iter)

            game_board_ndarray = np.array(game_board.flatten(), dtype=np.int8)
            predict_iter= mx.io.NDArrayIter(game_board_ndarray,  batch_size=1, shuffle=False)
            tmp = model.predict(X=predict_iter)[0]

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

I probably have missed sth obvious. 'current_board' is 1x36, 'game_board' is 6x6 (so after flattening the dimension should be the same w/ 'current_board'). I don't understand why I got the shape mismatch error.

## What have you tried to solve it?

1.
2.
3.

**Comment by piiswrong** [comment]
please  update to latest master

**Comment by windmaple** [comment]
OK. Updating to HEAD didn't quite cut it but gave some clue:

Traceback (most recent call last):
  File "/Users/weiwe/Desktop/alexa-planestrike/mxnet_train.py", line 180, in <module>
    board_position_log, action_log, hit_log = play_game(training=TRAINING, first_game=(game==0))
  File "/Users/weiwe/Desktop/alexa-planestrike/mxnet_train.py", line 89, in play_game
    tmp = model.predict(X=predict_iter)[0]
  File "/Users/weiwe/mxnet/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/model.py", line 621, in predict
    self._init_predictor(data_shapes, type_dict)
  File "/Users/weiwe/mxnet/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/model.py", line 545, in _init_predictor
    pred_exec.copy_params_from(self.arg_params, self.aux_params)
  File "/Users/weiwe/mxnet/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/executor.py", line 256, in copy_params_from
    array.astype(dst.dtype).copyto(dst)
  File "/Users/weiwe/mxnet/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/ndarray.py", line 556, in copyto
    return _internal._copyto(self, out=other)
  File "/Users/weiwe/mxnet/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/_ctypes/ndarray.py", line 131, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/Users/weiwe/mxnet/lib/python2.7/site-packages/mxnet-0.9.1-py2.7.egg/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:18:25] src/ndarray/ndarray.cc:239: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (15,36) to.shape=(15,1)

Stack trace returned 7 entries:
[bt] (0) 0   libmxnet.so                         0x0000000102a8c868 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x0000000102a8c1d9 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x00000001030bbe25 _ZN5mxnet10CopyFromToERKNS_7NDArrayEPS0_i + 2005
[bt] (3) 3   libmxnet.so                         0x0000000103117bd6 _ZNSt3__110__function6__funcIZN5mxnet2op20RegisterLegacyNDFuncEvE3$_4NS_9allocatorIS4_EEFvRKN4nnvm9NodeAttrsERKNS_6vectorINS2_7NDArrayENS5_ISC_EEEEPSE_EEclESA_SG_OSH_ + 1782
[bt] (4) 4   libmxnet.so                         0x000000010302acdf MXImperativeInvoke + 3375
[bt] (5) 5   libffi.dylib                        0x00007fff99b0cf14 ffi_call_unix64 + 76
[bt] (6) 6   ???                                 0x00007fff5df67620 0x0 + 140734769821216


I did some debugging and found that the error happens when the array is being copied into executor's internal array for the very first layer (15 hidden units):

#ececutor.py
    def copy_params_from(self, arg_params, aux_params=None, allow_extra_params=False):
        for name, array in arg_params.items():
            if name in self.arg_dict:
                dst = self.arg_dict[name]
                array.astype(dst.dtype).copyto(dst)              <==== error is thrown

I suspect I probably have screwed up the input somehow. Any idea?

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
