### ISSUE TITLE
[c++][win]20170110_mxnet_x64_vc14_gpu is disable ?

### ISSUE THREAD

**Issue by dxp5823625** [apache/incubator-mxnet#4621]
C:\Users\admin>python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda2\lib\site-packages\mxnet-0.9.1-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Miniconda2\lib\site-packages\mxnet-0.9.1-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Miniconda2\lib\site-packages\mxnet-0.9.1-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "C:\Miniconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 1114] 动态链接库(DLL)

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
