### ISSUE TITLE
fcn FCN8s_VGG16-symbol.json file not correct, no `param` and `backward_source_id`

### ISSUE THREAD

**Issue by sshuair** [apache/incubator-mxnet#4671]
@tornadomeet 
my output symbol file like this, and this file can not load by `mx.model.load_checkpoint()`
```json
{
  "nodes": [
    {
      "op": "null", 
      "name": "data", 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "conv1_1_weight", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "64", 
        "pad": "(100, 100)", 
        "workspace": "1536"
      }, 
      "inputs": []
    }, 
    {
      "op": "null", 
      "name": "conv1_1_bias", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "64", 
        "pad": "(100, 100)", 
        "workspace": "1536"
      }, 
      "inputs": []
    }, 
    {
      "op": "Convolution", 
      "name": "conv1_1", 
      "attr": {
        "kernel": "(3, 3)", 
        "num_filter": "64", 
        "pad": "(100, 100)", 
        "workspace": "1536"
      }, 
      "inputs": [[0, 0, 0], [1, 0, 0], [2, 0, 0]]
    }, 
...
```

**and it is not like the offical file(FCN8s_VGG16-symbol.json):**

```json
{
  "nodes": [
    {
      "op": "null", 
      "param": {}, 
      "name": "data", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_1_weight", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
    {
      "op": "null", 
      "param": {}, 
      "name": "conv1_1_bias", 
      "inputs": [], 
      "backward_source_id": -1
    }, 
...
```

there is no `param` and `backward_source_id` in my file .
could any one tell me what's going on ?

when I run the image_segmentation.py, got this error:
```
Traceback (most recent call last):
  File "image_segmentaion.py", line 61, in <module>
    main()
  File "image_segmentaion.py", line 52, in main
    exector = fcnxs.bind(ctx, fcnxs_args ,args_grad=None, grad_req="null", aux_states=fcnxs_args)
  File "/home/manager/mxnet/python/mxnet/symbol.py", line 926, in bind
    ctypes.byref(handle)))
  File "/home/manager/mxnet/python/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:44:32] src/executor/graph_executor.cc:240: Check failed: x.ctx() == default_ctx All arguments must be in global context unless group2ctx is specified
```

**Comment by bravomikekilo** [comment]
same error for me

**Comment by cloudhan** [comment]
I think that is because your data or parameters' NDArray are on different devices, e.g., data from dataiter is on cpu and other parameters are on gpu.

**Comment by lsy17096535** [comment]
@sshuair i have the same error

**Comment by Hjy20255** [comment]
i have the same error

**Comment by Hjy20255** [comment]
@sshuair   Did you solve this questions？

**Comment by lsy17096535** [comment]
@Hjy20255  Pls use the last source code. Old code cannot read new net trained by new version.

**Comment by Hjy20255** [comment]
@lsy17096535 i use v0.9.3 code .But i also meet same error

**Comment by sshuair** [comment]
@Hjy20255 not yet

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
