### ISSUE TITLE
Howto/cloud.md instructions do not work

### ISSUE THREAD

**Issue by xinwang-issaquah** [apache/incubator-mxnet#4806]
I followed the examples, but there was no test_conv file under tests/python/gpu

When I am trying to import mxnet, here is the error I got:
ubuntu@ip-172-31-47-238:~/mxnet/python$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "mxnet/base.py", line 9, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/usr/lib/python2.7/dist-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
/usr/lib/liblapack.so.3: undefined symbol: ATL_chemv

How out of date are the instructions in this .md file? Please make it clear to people. I wasted more than 1 day trying to follow the directions and debug what might be wrong.

**Comment by mli** [comment]
please try `train_mnist.py` located in `mxnet/example/image-classification`

http://mxnet.io/how_to/multi_devices.html

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
