### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by HuitingLiu** [apache/incubator-mxnet#4823]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Deep Learning on Amazon Linux with MXNet  (ami-a382c3b4)

Compiler: unknown

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.7.0

Python version and distribution: python3 

## Error Message:
Please paste the full error message, including stack trace.

```
15:35:29 INFO:root:Start training with [gpu(0)]
[15:35:30] /home/ec2-user/src/mxnet/dmlc-core/include/dmlc/./logging.h:235: [15:35:30] src/storage/./pooled_storage_manager.h:67: Memory allocation failed.
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    train()
  File "/home/ec2-user/MXNMT/nmt/trainer.py", line 110, in train
    epoch_end_callback=[mx.callback.do_checkpoint(xconfig.model_save_name, xconfig.model_save_freq),
  File "/home/ec2-user/src/mxnet/python/mxnet/model.py", line 789, in fit
    sym_gen=self.sym_gen)
  File "/home/ec2-user/src/mxnet/python/mxnet/model.py", line 192, in _train_multi_device
    logger=logger)
  File "/home/ec2-user/src/mxnet/python/mxnet/executor_manager.py", line 311, in __init__
    self.slices, train_data)
  File "/home/ec2-user/src/mxnet/python/mxnet/executor_manager.py", line 224, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "/home/ec2-user/src/mxnet/python/mxnet/executor_manager.py", line 177, in _bind_exec
    grad_req=grad_req, shared_exec=base_exec)
  File "/home/ec2-user/src/mxnet/python/mxnet/symbol.py", line 839, in bind
    ctypes.byref(handle)))
  File "/home/ec2-user/src/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:35:30] src/storage/./pooled_storage_manager.h:67: Memory allocation failed.
```

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.
https://github.com/HuitingLiu/MXNMT
I am trying to use the NMT to do a seq2seq generation. 

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. Clone the repository (I am running it on an AWS g2.2xlarge instance.) 
2. cd MXNMT/nmt/
3. python3 main.py --mode train

## What have you tried to solve it?

1. I try to use a tiny corpus. (change the data_root, model_root, log_root in nmt/xconfig.py from 'data' to 'tinydata'), the problem disappears. I think it is related to the corpus size. But I don't know how to decouple the correlation. What kind of data is stored in GPU memory?

**Comment by mli** [comment]
g2.2xl gpu only has 4gb memory. you can try p2.2xlarge

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
