### ISSUE TITLE
Googlenet crash 

### ISSUE THREAD

**Issue by zhenlinluo** [apache/incubator-mxnet#4827]
1)	Build with no MKL on CPUs
2)	Run benchmark_score.py
It’ll run “Alexnet” first and crash right away.  Again Alexnet is in quotes as it is really Googlenet

@piiswrong @mli

**Comment by nvoliver** [comment]
Indeed, same for me. See log below.
I freshly compiled the master branch today on Ubuntu 16.04 amd64.

```
username@ubuntu:~/Development/mxnet/example/image-classification$ python benchmark_score.py 
INFO:root:network: alexnet
INFO:root:device: gpu(0)
[09:58:43] /home/username/Development/mxnet/dmlc-core/include/dmlc/./logging.h:300: [09:58:43] src/operator/./pooling-inl.h:208: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (7) exceeds input (6 padded to 6)

Stack trace returned 48 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f8d1ede2dec]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZNK5mxnet2op11PoolingProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x4b5) [0x7f8d1f627aa5]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0xdbee32) [0x7f8d1f595e32]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0x1baed50) [0x7f8d20385d50]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0x1bb026a) [0x7f8d2038726a]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0x1bb11ad) [0x7f8d203881ad]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32b) [0x7f8d203ad3ab]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f8d1f8a4509]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e5) [0x7f8d1f8a9be5]
[bt] (9) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(MXSymbolInferShape+0xdeb) [0x7f8d1f89d44b]
[bt] (10) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f8d3dbcce40]
[bt] (11) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f8d3dbcc8ab]
[bt] (12) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f8d3dddc3df]
[bt] (13) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f8d3dde0d82]
[bt] (14) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (15) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (16) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (17) python() [0x4de8b8]
[bt] (18) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (19) python(PyEval_EvalFrameEx+0x2ad1) [0x4c6ad1]
[bt] (20) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (21) python() [0x4de8b8]
[bt] (22) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (23) python(PyEval_EvalFrameEx+0x2ad1) [0x4c6ad1]
[bt] (24) python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (25) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (26) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (27) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (28) python() [0x4de8b8]
[bt] (29) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (30) python() [0x4f492e]
[bt] (31) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (32) python() [0x4f46a7]
[bt] (33) python() [0x4b670c]
[bt] (34) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (35) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (36) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (37) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (38) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (39) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
[bt] (40) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (41) python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (42) python() [0x4f1def]
[bt] (43) python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (44) python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (45) python(Py_Main+0x68a) [0x49e14a]
[bt] (46) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8d3ed91830]
[bt] (47) python(_start+0x29) [0x49d9d9]

infer_shape error. Arguments:
  data: (1, 3, 224, 224)
Traceback (most recent call last):
  File "benchmark_score.py", line 63, in <module>
    speed = score(network=net, dev=d, batch_size=b, num_batches=10)
  File "benchmark_score.py", line 31, in score
    data_shapes      = data_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/module/module.py", line 342, in bind
    grad_req=grad_req)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/module/executor_group.py", line 187, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/module/executor_group.py", line 279, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/module/executor_group.py", line 483, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/symbol.py", line 538, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/symbol.py", line 605, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator pooling4: [09:58:43] src/operator/./pooling-inl.h:208: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (7) exceeds input (6 padded to 6)

Stack trace returned 48 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f8d1ede2dec]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZNK5mxnet2op11PoolingProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x4b5) [0x7f8d1f627aa5]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0xdbee32) [0x7f8d1f595e32]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0x1baed50) [0x7f8d20385d50]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0x1bb026a) [0x7f8d2038726a]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(+0x1bb11ad) [0x7f8d203881ad]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32b) [0x7f8d203ad3ab]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f8d1f8a4509]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e5) [0x7f8d1f8a9be5]
[bt] (9) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.3-py2.7.egg/mxnet/libmxnet.so(MXSymbolInferShape+0xdeb) [0x7f8d1f89d44b]
[bt] (10) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f8d3dbcce40]
[bt] (11) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f8d3dbcc8ab]
[bt] (12) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f8d3dddc3df]
[bt] (13) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f8d3dde0d82]
[bt] (14) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (15) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (16) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (17) python() [0x4de8b8]
[bt] (18) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (19) python(PyEval_EvalFrameEx+0x2ad1) [0x4c6ad1]
[bt] (20) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (21) python() [0x4de8b8]
[bt] (22) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (23) python(PyEval_EvalFrameEx+0x2ad1) [0x4c6ad1]
[bt] (24) python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (25) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (26) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (27) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (28) python() [0x4de8b8]
[bt] (29) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (30) python() [0x4f492e]
[bt] (31) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (32) python() [0x4f46a7]
[bt] (33) python() [0x4b670c]
[bt] (34) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (35) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (36) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (37) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (38) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (39) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
[bt] (40) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (41) python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (42) python() [0x4f1def]
[bt] (43) python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (44) python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (45) python(Py_Main+0x68a) [0x49e14a]
[bt] (46) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f8d3ed91830]
[bt] (47) python(_start+0x29) [0x49d9d9]

```

**Comment by phunterlau** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
