### ISSUE TITLE
batch norm fails on validation batch sizes larger than 1024

### ISSUE THREAD

**Issue by jmschrei** [apache/incubator-mxnet#4997]
I'm trying to train a network and can get my training batch size up to 1,024,000 given the small size of the inputs, but validation will fail if I have a batch size greater than 1024. The large sample size is necessary because it drastically increases speed (~1million samples/sec vs ~40k samples/sec) and allows it to converge faster. I can't set the training size to the large number and the validation size to another number or another error is raised.

Here is what it looks like when I set both to 1024 and it works:

```
INFO:root:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
INFO:root:Epoch[0] Batch [50]	Speed: 43134.38 samples/sec	Train-mse=2.974635
INFO:root:Epoch[0] Batch [100]	Speed: 41277.91 samples/sec	Train-mse=4.068618
INFO:root:Epoch[0] Batch [150]	Speed: 40782.87 samples/sec	Train-mse=9.751048
INFO:root:Epoch[0] Batch [200]	Speed: 41300.88 samples/sec	Train-mse=8.763692
INFO:root:Epoch[0] Batch [250]	Speed: 41711.20 samples/sec	Train-mse=5.875643
INFO:root:Epoch[0] Time cost=6.443
INFO:root:Saved checkpoint to "avocado-chr21-0001.params"
INFO:root:Epoch[0] Validation-mse=6.179373
INFO:root:Epoch[1] Batch [50]	Speed: 42662.65 samples/sec	Train-mse=4.892629
INFO:root:Epoch[1] Batch [100]	Speed: 41145.89 samples/sec	Train-mse=5.271115
INFO:root:Epoch[1] Batch [150]	Speed: 41511.60 samples/sec	Train-mse=5.352612
INFO:root:Epoch[1] Batch [200]	Speed: 41291.26 samples/sec	Train-mse=8.569360
INFO:root:Epoch[1] Batch [250]	Speed: 41208.87 samples/sec	Train-mse=8.101565
INFO:root:Epoch[1] Time cost=6.179
INFO:root:Saved checkpoint to "avocado-chr21-0002.params"
INFO:root:Epoch[1] Validation-mse=6.169909
```

Here is the output when I set the batch size to 1,024,000:

```
INFO:root:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
INFO:root:Epoch[0] Batch [50]	Speed: 1146240.87 samples/sec	Train-mse=4.897271
INFO:root:Epoch[0] Batch [100]	Speed: 1129582.75 samples/sec	Train-mse=4.481242
INFO:root:Epoch[0] Batch [150]	Speed: 1098659.87 samples/sec	Train-mse=4.279920
INFO:root:Epoch[0] Batch [200]	Speed: 1124307.09 samples/sec	Train-mse=3.947533
INFO:root:Epoch[0] Batch [250]	Speed: 1162055.74 samples/sec	Train-mse=4.124683
INFO:root:Epoch[0] Time cost=22.961
INFO:root:Saved checkpoint to "avocado-chr21-0001.params"
[19:24:20] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:235: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
[[19:24:20] [[19:24:20] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h19:24:20] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:19:24:20] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:235:235: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
/net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:235: [19:24:20] src/engine/./threaded_engine.h:306: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
[19:24:20] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h235: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
:235: [19:24:20] src/engine/./threaded_engine.h:306: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
terminate called recursively
  what():  [19:24:20] src/engine/./threaded_engine.h:306: [19:24:20] src/operator/./cudnn_batch_norm-inl.h:140: Check failed: (cudnnBatchNormalizationForwardInference(s->dnn_handle_, CUDNN_BATCHNORM_SPATIAL, &a, &b, io_desc_, x.dptr_, io_desc_, y.dptr_, mean_desc_, gamma.dptr_, beta.dptr_, moving_mean.dptr_, moving_inv_var.dptr_, param_.eps)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
```

Here is the output when I set the training batch size to 1,024,000 and the validation batch size to 1,024:

```
INFO:root:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
INFO:root:Epoch[0] Batch [50]	Speed: 1162164.40 samples/sec	Train-mse=4.905726
INFO:root:Epoch[0] Batch [100]	Speed: 1200327.12 samples/sec	Train-mse=4.222562
INFO:root:Epoch[0] Batch [150]	Speed: 1217945.84 samples/sec	Train-mse=3.408096
INFO:root:Epoch[0] Batch [200]	Speed: 1285835.83 samples/sec	Train-mse=2.877194
INFO:root:Epoch[0] Batch [250]	Speed: 1278156.80 samples/sec	Train-mse=2.740534
INFO:root:Epoch[0] Time cost=210.240
INFO:root:Saved checkpoint to "avocado-chr21-0001.params"
[19:34:28] /net/noble/vol1/home/jmschr/mxnet/dmlc-core/include/dmlc/logging.h:235: [19:34:28] include/mxnet/ndarray.h:244: Check failed: (shape_[0]) >= (end) Slice end index out of range
Traceback (most recent call last):
  File "avocado_test.py", line 101, in <module>
    epoch_end_callback=mx.callback.do_checkpoint("avocado-chr21")
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 787, in fit
    sym_gen=self.sym_gen)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 287, in _train_multi_device
    executor_manager.load_data_batch(eval_batch)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 394, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 245, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 88, in _load_data
    _load_general(batch.data, targets)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 84, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 241, in __getitem__
    return self._slice(in_slice.start, in_slice.stop)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 281, in _slice
    self.handle, start, stop, ctypes.byref(handle)))
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:34:28] include/mxnet/ndarray.h:244: Check failed: (shape_[0]) >= (end) Slice end index out of range
```

Is there a way that I can utilize both batch norm and large batch sizes while also using a validation set? If I only have a training set they both work, it only fails on the validation step.

Thanks!

**Comment by piiswrong** [comment]
cudnn doesn't support too big batch sizes.
If you want to change batch size between train and val you need to make a new module

**Comment by jmschrei** [comment]
Why can it train successfully with large batch sizes, just not validate?

**Comment by piiswrong** [comment]
cudnnBatchNormalizationForwardTraining vs cudnnBatchNormalizationForwardInference

**Comment by jmschrei** [comment]
Thanks for the answer. I guess I meant more conceptually, why can cudnnBatchNormalizationForwardTraining support massive batch sizes but cudnnBatchNormalizationForwardInference not?

**Comment by piiswrong** [comment]
Dunno. You have to ask nvidia @ap-hynninen

**Comment by jmschrei** [comment]
If I load up a pretrained model and predict with a large batch size (102400) it appears to work without problems. Do you know why this might work but it won't work during training?

**Comment by piiswrong** [comment]
Not sure. I'll look into it...

**Comment by ap-hynninen** [comment]
The batch size for cudnnBatchNormalizationForwardInference is limited to < 65535

**Comment by jmschrei** [comment]
Hi @ap-hynninen thanks for the response. I'm noticing it fails on batch sizes even as small as ~5000 samples. Do you know why this could be? Also, why is there a limit on the inference step but not the training step? Thanks in advance!

Also, @piiswrong I was incorrect. I had thought I was setting it higher but I don't think I was.

**Comment by ap-hynninen** [comment]
Apparently there's still a 1024 limitation when the batch normalization mode is CUDNN_BATCHNORM_PER_ACTIVATION.

**Comment by neulinux** [comment]
Update cuDNN to version 5.1 (CUDA 8.0) instead of 5.0x (CUDA 7.5).

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
