### ISSUE TITLE
bugs in example/numpy-ops/custom_softmax.py

### ISSUE THREAD

**Issue by cainiao2hao** [apache/incubator-mxnet#5068]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: windows 7, python3.6

Compiler:
vc2013
Package used (Python/R/Scala/Julia):
Python3.6
MXNet version:
0.9.3

## Error Message:
[12:14:49] E:\Projects\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[12:14:50] E:\Projects\mxnet\src\io\iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
Traceback (most recent call last):
  File "D:/wzy/mxnet-master/example/numpy-ops/custom_softmax.py", line 69, in <module>
    batch_end_callback=mx.callback.Speedometer(100,100))
  File "D:\Python36_x64\mxnet\model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "D:\Python36_x64\mxnet\model.py", line 485, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "D:\Python36_x64\mxnet\symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "D:\Python36_x64\mxnet\symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
OSError: exception: access violation writing 0x0000000000000000
Exception ignored in: <bound method Symbol.__del__ of <mxnet.symbol.Symbol object at 0x00000000057DC710>>
Traceback (most recent call last):
  File "D:\Python36_x64\mxnet\symbol.py", line 106, in __del__
OSError: exception: access violation writing 0x0000000000000000

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. just run python custom_softmax.py

## What have you tried to solve it?

1.  I found that I can not do save or bind on this mlp model, such as mlp.save('x.json'). It works only on mlp=mx.symbol.softmax(data = fc3, name = 'softmax')
2. I write a simple code to use this custom operator. The program crashed when I tried to do any computation or saving on the model. Only build-in softmax works.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
