### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Proposal'

### ISSUE THREAD

**Issue by great-thoughts** [apache/incubator-mxnet#5102]
when i run bash script/additional_deps.sh, I get the following warning:
```
bash script/additional_deps.sh
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-dev is already the newest version.
python-matplotlib is already the newest version.
unzip is already the newest version.
python-pip is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 120 not upgraded.
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: cython in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: scikit-image in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: easydict in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: dask[array]>=0.5.0 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied: six>=1.7.3 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied: matplotlib>=1.3.1 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied: pillow>=2.1.0 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied: networkx>=1.8 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied: scipy>=0.9.0 in /usr/local/lib/python2.7/dist-packages (from scikit-image)
Requirement already satisfied: numpy; extra == "array" in /usr/local/lib/python2.7/dist-packages (from dask[array]>=0.5.0->scikit-image)
Requirement already satisfied: toolz>=0.7.2; extra == "array" in /usr/local/lib/python2.7/dist-packages (from dask[array]>=0.5.0->scikit-image)
Requirement already satisfied: cycler in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->scikit-image)
Requirement already satisfied: pyparsing!=2.0.0,!=2.0.4,!=2.1.2,>=1.5.6 in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->scikit-image)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->scikit-image)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from matplotlib>=1.3.1->scikit-image)
Requirement already satisfied: olefile in /usr/local/lib/python2.7/dist-packages (from pillow>=2.1.0->scikit-image)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python2.7/dist-packages (from networkx>=1.8->scikit-image)
~/Zahraa/mxnet ~/Zahraa/mxnet/example/rcnn
Makefile:35: mshadow/make/mshadow.mk: No such file or directory
Makefile:36: /home/ubuntu/Zahraa/mxnet/dmlc-core/make/dmlc.mk: No such file or directory
Makefile:122: /home/ubuntu/Zahraa/mxnet/ps-lite/make/ps.mk: No such file or directory
make: *** No rule to make target `/home/ubuntu/Zahraa/mxnet/ps-lite/make/ps.mk'.  Stop.
~/Zahraa/mxnet/python ~/Zahraa/mxnet ~/Zahraa/mxnet/example/rcnn
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    LIB_PATH = libinfo['find_lib_path']()
  File "mxnet/libinfo.py", line 37, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/home/ubuntu/Zahraa/mxnet/python/mxnet/libmxnet.so
/home/ubuntu/Zahraa/mxnet/python/mxnet/../../lib/libmxnet.so
/home/ubuntu/Zahraa/mxnet/python/mxnet/../../build/Release/libmxnet.so
libmxnet.so
/usr/local/cuda/lib64/libmxnet.so
~/Zahraa/mxnet ~/Zahraa/mxnet/example/rcnn
~/Zahraa/mxnet/example/rcnn
cd rcnn/cython/; python setup.py build_ext --inplace; rm -rf build; cd ../../
running build_ext
skipping 'bbox.c' Cython extension (up-to-date)
skipping 'cpu_nms.c' Cython extension (up-to-date)
skipping 'gpu_nms.cpp' Cython extension (up-to-date)
cd rcnn/pycocotools/; python setup.py build_ext --inplace; rm -rf build; cd ../../
Warning: Extension name '_mask' does not match fully qualified name 'rcnn.pycocotools._mask' of '_mask.pyx'
running build_ext
```

Later when I execute  bash script/vgg_voc07.sh 0,1
```
Called with argument: Namespace(begin_epoch=0, dataset='PascalVOC', dataset_path='data/VOCdevkit', end_epoch=10, frequent=20, gpus='0,1', image_set='2007_trainval', kvstore='device', lr=0.001, lr_step='7', network='vgg', no_flip=False, no_shuffle=False, prefix='model/e2e', pretrained='model/vgg16', pretrained_epoch=0, resume=False, root_path='data', work_load_list=None)
Traceback (most recent call last):
  File "train_end2end.py", line 184, in <module>
    main()
  File "train_end2end.py", line 181, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_end2end.py", line 30, in train_net
    sym = eval('get_' + args.network + '_train')(num_classes=config.NUM_CLASSES, num_anchors=config.NUM_ANCHORS)
  File "/home/ubuntu/Zahraa/mxnet/example/rcnn/rcnn/symbol/symbol_vgg.py", line 359, in get_vgg_train
    rois = mx.symbol.Proposal(
AttributeError: 'module' object has no attribute 'Proposal'
Namespace(dataset='PascalVOC', dataset_path='data/VOCdevkit', epoch=10, gpu=0, has_rpn=True, image_set='2007_test', network='vgg', prefix='model/e2e', proposal='rpn', root_path='data', shuffle=False, thresh=0.001, vis=False)
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'FIXED_PARAMS': ['conv1', 'conv2'],
 'FIXED_PARAMS_SHARED': ['conv1', 'conv2', 'conv3', 'conv4', 'conv5'],
 'IMAGE_STRIDE': 0,
 'NUM_ANCHORS': 9,
 'NUM_CLASSES': 21,
 'PIXEL_MEANS': array([ 103.939,  116.779,  123.68 ]),
 'RCNN_FEAT_STRIDE': 16,
 'RPN_FEAT_STRIDE': 16,
 'SCALES': [(600, 1000)],
 'TEST': {'BATCH_IMAGES': 1,
          'CXX_PROPOSAL': True,
          'HAS_RPN': True,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': 16,
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 2000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 2,
           'BATCH_ROIS': 128,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': False,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_WEIGHTS': array([ 1.,  1.,  1.,  1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'CXX_PROPOSAL': True,
           'END2END': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'RPN_BATCH_SIZE': 256,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000}}
Traceback (most recent call last):
  File "test.py", line 40, in <module>
    main()
  File "test.py", line 37, in main
    args.vis, args.shuffle, args.has_rpn, args.proposal, args.thresh)
  File "/home/ubuntu/Zahraa/mxnet/example/rcnn/rcnn/tools/test_rcnn.py", line 25, in test_rcnn
    sym = eval('get_' + network + '_test')(num_classes=config.NUM_CLASSES, num_anchors=config.NUM_ANCHORS)
  File "/home/ubuntu/Zahraa/mxnet/example/rcnn/rcnn/symbol/symbol_vgg.py", line 276, in get_vgg_test
    rois = mx.symbol.Proposal(
AttributeError: 'module' object has no attribute 'Proposal'
```

**Comment by great-thoughts** [comment]
I got rid of this error when i installed glog. Now I am getting a new error:
undefined symbol: _ZN2ps4Meta6kEmptyE

**Comment by great-thoughts** [comment]
I tried ` make -f Makefile clean ` but it didnt sovle problem. I also tried `make -f Makefile clean_all` but i will get the following error:
make: *** No rule to make target `clean_all'.  Stop.

**Comment by great-thoughts** [comment]
I am back to point zero. I started fresh with a working installation of mxnet and upgraded. With that I am getting the error: AttributeError: 'module' object has no attribute 'Proposal'
This is exactly what I did:    
```
    1  cd mxnet
    2  git pull
    3  cd example/rcnn
    4  ls
    5  bash script/additional_deps.sh
    6  pip install matplotlib
    7  bash script/get_voc.sh
    8  bash script/get_pretrained_model.sh
    9  bash script/vgg_voc07.sh 0,1
   10  ls
   11  cd ..
   12  sed -i 's/EXTRA_OPERATORS =/EXTRA_OPERATORS = example\/rcnn\/operator/g' config.mk
   13  make -j"$(nproc)"
   14  cd example
   15  cd rcnn
   16  make
   17  bash script/vgg_voc07.sh 0,1
```

**Comment by joyivan** [comment]
I have the same  error

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
