### ISSUE TITLE
source_array must be array like object

### ISSUE THREAD

**Issue by hariag** [apache/incubator-mxnet#5176]
Hi!

I got following error when try some demo code, 
```python
>>> import mxnet as mx
>>> mx.__version__
'0.9.3'
>>> a=mx.nd.array([1,2,3])
>>> b=mx.nd.array(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haria/anaconda2/lib/python2.7/site-packages/mxnet-0.9.3-py2.7-linux-x86_64.egg/mxnet/ndarray.py", line 1121, in array
    raise TypeError('source_array must be array like object')
TypeError: source_array must be array like object
```
 I thought the usage is fine since there is no problems in numpy, but a TypeError occur
```python
>>> import numpy as np
>>> aa=np.array([1,2,3])
>>> bb=np.array(aa)
>>> 
```

Is that normal?

Best Regards,
Haria

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
