### ISSUE TITLE
python/gpu/test_rtc.py test fails

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#5263]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: ubuntu (AWS DL Ubuntu AMI)

Compiler: gcc version 4.8.4

Package used (Python/R/Scala/Julia): python

MXNet version:

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): a23608fcd07e348ce4818b5cde4a95feb5068b3b

If you are using python package, please provide

Python version and distribution: Python 2.7.6

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
python ./tests/python/gpu/test_rtc.py       [1/1209]
[23:20:47] /home/ubuntu/mxnet-most-recent-2/dmlc-core/include/dmlc/./logging.h:300: [23:20:47] src/common/mxrtc.cc:46: Check failed: err = cuModuleLoadDataEx(&module, ptx_, 0, 0, 0) == CUDA_SUCCESS (3 vs. 0) CudaError: 3

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/mxnet-most-recent-2/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fb5f4b5bb2c]
[bt] (1) /home/ubuntu/mxnet-most-recent-2/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet5MXRtc4pushERKSt6vectorINS_7NDArrayESaIS2_EES6_jjjjjj+0x5ab) [0x7fb5f53f610b]
[bt] (2) /home/ubuntu/mxnet-most-recent-2/python/mxnet/../../lib/libmxnet.so(MXRtcPush+0x7d0) [0x7fb5f53b5390]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fb64fa59adc]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7fb64fa5940c]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7fb64fc705fe]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7fb64fc71f9e]
[bt] (7) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (8) python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (9) python(PyEval_EvalFrameEx+0x1a10) [0x525560]

Traceback (most recent call last):
  File "./tests/python/gpu/test_rtc.py", line 15, in <module>
    rtc.push([x], [y], (1, 1, 1), (10,1,1))
  File "/home/ubuntu/mxnet-most-recent-2/python/mxnet/rtc.py", line 91, in push
    mx_uint(block_dims[2])))
  File "/home/ubuntu/mxnet-most-recent-2/python/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:20:47] src/common/mxrtc.cc:46: Check failed: err = cuModuleLoadDataEx(&module, ptx_, 0, 0, 0) == CUDA_SUCCESS (3 vs. 0) CudaError: 3

Stack trace returned 10 entries:
[bt] (0) /home/ubuntu/mxnet-most-recent-2/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fb5f4b5bb2c]
[bt] (1) /home/ubuntu/mxnet-most-recent-2/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet5MXRtc4pushERKSt6vectorINS_7NDArrayESaIS2_EES6_jjjjjj+0x5ab) [0x7fb5f53f610b]
[bt] (2) /home/ubuntu/mxnet-most-recent-2/python/mxnet/../../lib/libmxnet.so(MXRtcPush+0x7d0) [0x7fb5f53b5390]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fb64fa59adc]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7fb64fa5940c]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7fb64fc705fe]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7fb64fc71f9e]
[bt] (7) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (8) python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (9) python(PyEval_EvalFrameEx+0x1a10) [0x525560]
```

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1. python ./tests/python/gpu/test_rtc.py 
2.
3.

## What have you tried to solve it?

1. Haven't attempted it yet.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
