### ISSUE TITLE
Using different batch sizes for training and development sets

### ISSUE THREAD

**Issue by jdchoi77** [apache/incubator-mxnet#5299]
I followed the tutorial for creating a custom data iterator and it gives an unintuitive error when I use different batch sizes for training and development data.  Specifically, the attached code runs fine when I set both trn_batch_size and dev_batch_size to the same value (e.g., 128) on lines 62-63; however, it gives an error when they are set to different values:

```
trn_batch_size = 128
dev_batch_size = 64
```
A similar problem with lines 74-75 when I tried to predict:

```
ys = mod.predict(SimpleIter(num_classes, num_features, dev_batch_size))
y = mod.predict(mx.io.NDArrayIter(np.random.rand(num_features)))
```

Is there way of getting around this without zero padding to the same batch size?  Thanks!
[test.py.zip](https://github.com/dmlc/mxnet/files/826095/test.py.zip)

**Comment by Piyush3dB** [comment]
Please post the error because it might be possible to spot the cause without running your code.

**Comment by jdchoi77** [comment]
Here is the error message:

```
INFO:root:Epoch[0] Train-accuracy=0.121094
INFO:root:Epoch[0] Time cost=0.072
[16:40:48] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./logging.h:300: [16:40:48] src/operator/tensor/./matrix_op-inl.h:712: Check failed: param.begin[i] < shp[i] && param.end[i] <= shp[i] && param.begin[i] < param.end[i] 

Stack trace returned 5 entries:
[bt] (0) 0   libmxnet.so                         0x0000000105f1e6c8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010647b195 _ZN5mxnet2op9CropShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 1077
[bt] (2) 2   libmxnet.so                         0x00000001064f2f25 MXImperativeInvoke + 4373
[bt] (3) 3   _ctypes.cpython-36m-darwin.so       0x0000000104890247 ffi_call_unix64 + 79
[bt] (4) 4   Python                              0x00007fff5bffd450 Python + 140730441913424

Traceback (most recent call last):
  File "/Users/jdchoi/Documents/Software/elit/python/elit/test/test.py", line 72, in <module>
    num_epoch=1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/module/base_module.py", line 443, in fit
    batch_end_callback=eval_batch_end_callback, epoch=epoch)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/module/base_module.py", line 190, in score
    self.forward(eval_batch, is_train=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/module/module.py", line 452, in forward
    self._exec_group.forward(data_batch, is_train)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 313, in forward
    _load_data(data_batch, self.data_arrays, self.data_layouts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 43, in _load_data
    _load_general(batch.data, targets, major_axis)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 31, in _load_general
    nd.crop(d_src, begin=tuple(begin), end=tuple(end), out=d_dst)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 131, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:40:48] src/operator/tensor/./matrix_op-inl.h:712: Check failed: param.begin[i] < shp[i] && param.end[i] <= shp[i] && param.begin[i] < param.end[i] 

Stack trace returned 5 entries:
[bt] (0) 0   libmxnet.so                         0x0000000105f1e6c8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010647b195 _ZN5mxnet2op9CropShapeERKN4nnvm9NodeAttrsEPNSt3__16vectorINS1_6TShapeENS5_9allocatorIS7_EEEESB_ + 1077
[bt] (2) 2   libmxnet.so                         0x00000001064f2f25 MXImperativeInvoke + 4373
[bt] (3) 3   _ctypes.cpython-36m-darwin.so       0x0000000104890247 ffi_call_unix64 + 79
[bt] (4) 4   Python                              0x00007fff5bffd450 Python + 140730441913424
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
