### ISSUE TITLE
make: *** [bin/im2rec] Error 1

### ISSUE THREAD

**Issue by IvyGongoogle** [apache/incubator-mxnet#5327]
hello, I use ubuntu14.04, cuda8, cudnn5.1, opencv2.4.9 When I run the command 
`bash install-mxnet-ubuntu-python.sh`, it shows error:

```
/usr/bin/ld: warning: libcudart.so.7.5, needed by /usr/local/lib/libopencv_core.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFReadRGBAStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFIsTiled@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFWriteScanline@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFGetField@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFScanlineSize@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFReadEncodedTile@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFReadRGBATile@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFClose@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFRGBAImageOK@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFOpen@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFReadEncodedStrip@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFSetField@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFSetWarningHandler@LIBTIFF_4.0'
/usr/local/lib/libopencv_highgui.so: undefined reference to `TIFFSetErrorHandler@LIBTIFF_4.0'
collect2: error: ld returned 1 exit status
make: *** [bin/im2rec] Error 1
```
this seems to be the cause of opencv?
how to solve this problem, any advice is appreciated.
Thank you very much!

**Comment by IvyGongoogle** [comment]
@everytime I use the command"bash install-mxnet-ubuntu-python.sh", it again show above error. But every time I use the command"sudo bash install-mxnet-ubuntu-python.sh", there is no error. 
Why?
Besides, after I complete this successfully using 'sudo' , I get another error when I import mxnet :

```
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/congleng/work/deeplearning-tools/mxnet-cuda8/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/congleng/work/deeplearning-tools/mxnet-cuda8/python/mxnet/base.py", line 46, in <module>
    _LIB = _load_lib()
  File "/home/congleng/work/deeplearning-tools/mxnet-cuda8/python/mxnet/base.py", line 38, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/congleng/local/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory
```
But I set "USE_CUDA_PATH=/usr/local/cuda-8.0".
how to solve?

**Comment by Lyken17** [comment]
As for the first problem, it seesm you have two different versions of opencv, I guess you installed opencv with sudo?

For the second, have you tried "sudo ldconfig"?

**Comment by jay960702** [comment]
@IvyGongoogle How do you solve the problem in the end? Just add "sudo"?

**Comment by jay960702** [comment]
@IvyGongoogle I had the same error as yours

**Comment by IvyGongoogle** [comment]
@jay960702 sudo apt-get install libtiff4-dev

**Comment by jay960702** [comment]
@IvyGongoogle Thank you very much

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
