### ISSUE TITLE
MXNET distributed training segmentation fault 

### ISSUE THREAD

**Issue by salemmohammed** [apache/incubator-mxnet#5334]
I built a cluster of 1 server and 3 workers. 
I followed the MXnet installation guide. However, when I executed 
`   ../../tools/launch.py -n 2 -H hosts --sync-dst-dir /tmp/mxnet \
   python train_mnist.py --network lenet --kv-store dist_sync
`

`Assertion failed: data_ != NULL || size_ == 0 (src/msg.cpp:97)
bash: line 1:  2902 Aborted                 (core dumped) python train_mnist.py --network lenet --kv-store dist_sync
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no ip -p 22 'export DMLC_SERVER_ID=2; export DMLC_WORKER_ID=1; export DMLC_PS_ROOT_URI=ip; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9098; export DMLC_NUM_WORKER=3; export DMLC_NUM_SERVER=3; cd /tmp/mxnet; python train_mnist.py --network lenet --kv-store dist_sync'' returned non-zero exit status 134
`

any help ?

**Comment by dleen** [comment]
I can reproduce this with the follow code:

```
# crash2.py
import mxnet as mx
import numpy as np


def crash2():
    num_rows, num_cols = 100, 100

    kv = mx.kvstore.create('dist_sync')
    kv.init(0, mx.nd.zeros((num_cols, num_cols)))

    ans = mx.ndarray.ones((num_cols, num_cols))
    kv.push(0, ans)


if __name__ == "__main__":
    crash2()
```

running using the ```launcher.py``` command:

```
mxnet/tools/launch.py -n4 --launcher ssh -H hosts python crash2.py
```

It doesn't happen every time with that command. Maybe 20% of the time.

I'm debugging this now, will update if I can find a fix.

**Comment by qiyuangong** [comment]
Try to add `export PS_VERBOSE=1;` or `export PS_VERBOSE=2;`, before your running command. Then you will see more details. 

I found that sometimes the `scheduler` cannot be launched correctly on one of my working nodes.

**Comment by dleen** [comment]
Nothing stands out to me in the log with ```PS_VERBOSE=2```. What do you think?

```
env PS_VERBOSE=2 mxnet/tools/launch.py -n5 --launcher ssh -H hosts python crash2.py
2017-03-23 21:56:18,678 WARNING gethostbyname(socket.getfqdn()) failed... trying on hostname()
[21:56:19] src/van.cc:75: Bind to role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0
[21:56:19] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=192.168.1.7, port=58527, is_recovery=0 } }
[21:56:19] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=192.168.1.7, port=58529, is_recovery=0 } }
[21:56:19] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=192.168.1.7, port=58531, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=192.168.1.7, port=58535, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=192.168.1.7, port=58534, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=192.168.1.7, port=58536, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=192.168.1.7, port=58540, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=192.168.1.7, port=58543, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=192.168.1.7, port=58542, is_recovery=0 } }
[21:56:20] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=192.168.1.7, port=58546, is_recovery=0 } }
[21:56:20] src/van.cc:235: assign rank=8 to node role=server, ip=192.168.1.7, port=58527, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=9 to node role=worker, ip=192.168.1.7, port=58529, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=11 to node role=worker, ip=192.168.1.7, port=58531, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=13 to node role=worker, ip=192.168.1.7, port=58534, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=10 to node role=server, ip=192.168.1.7, port=58535, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=12 to node role=server, ip=192.168.1.7, port=58536, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=14 to node role=server, ip=192.168.1.7, port=58540, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=16 to node role=server, ip=192.168.1.7, port=58542, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=15 to node role=worker, ip=192.168.1.7, port=58543, is_recovery=0
[21:56:20] src/van.cc:235: assign rank=17 to node role=worker, ip=192.168.1.7, port=58546, is_recovery=0
[21:56:20] src/van.cc:136: ? => 9. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 11. Meta: request=0, timestamp=1, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 13. Meta: request=0, timestamp=2, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 15. Meta: request=0, timestamp=3, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 17. Meta: request=0, timestamp=4, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 8. Meta: request=0, timestamp=5, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 10. Meta: request=0, timestamp=6, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 12. Meta: request=0, timestamp=7, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 14. Meta: request=0, timestamp=8, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:136: ? => 16. Meta: request=0, timestamp=9, control={ cmd=ADD_NODE, node={ role=server, id=8, ip=192.168.1.7, port=58527, is_recovery=0 role=worker, id=9, ip=192.168.1.7, port=58529, is_recovery=0 role=worker, id=11, ip=192.168.1.7, port=58531, is_recovery=0 role=worker, id=13, ip=192.168.1.7, port=58534, is_recovery=0 role=server, id=10, ip=192.168.1.7, port=58535, is_recovery=0 role=server, id=12, ip=192.168.1.7, port=58536, is_recovery=0 role=server, id=14, ip=192.168.1.7, port=58540, is_recovery=0 role=server, id=16, ip=192.168.1.7, port=58542, is_recovery=0 role=worker, id=15, ip=192.168.1.7, port=58543, is_recovery=0 role=worker, id=17, ip=192.168.1.7, port=58546, is_recovery=0 role=scheduler, id=1, ip=192.168.1.7, port=9092, is_recovery=0 } }
[21:56:20] src/van.cc:251: the scheduler is connected to 5 workers and 5 servers
[21:56:20] src/van.cc:161: 9 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 1
[21:56:20] src/van.cc:161: 17 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 2
[21:56:20] src/van.cc:161: 1 => 1. Meta: request=1, timestamp=10, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 3
[21:56:20] src/van.cc:161: 13 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 4
[21:56:20] src/van.cc:136: ? => 1. Meta: request=1, timestamp=10, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:161: 11 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 5
[21:56:20] src/van.cc:161: 15 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 6
[21:56:20] src/van.cc:161: 8 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 7
[21:56:20] src/van.cc:161: 12 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 8
[21:56:20] src/van.cc:161: 10 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 9
[21:56:20] src/van.cc:161: 14 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 10
[21:56:20] src/van.cc:161: 16 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 11
[21:56:20] src/van.cc:136: ? => 9. Meta: request=0, timestamp=11, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 11. Meta: request=0, timestamp=12, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 13. Meta: request=0, timestamp=13, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 15. Meta: request=0, timestamp=14, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 17. Meta: request=0, timestamp=15, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 8. Meta: request=0, timestamp=16, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 10. Meta: request=0, timestamp=17, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 12. Meta: request=0, timestamp=18, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 14. Meta: request=0, timestamp=19, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 16. Meta: request=0, timestamp=20, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 1. Meta: request=0, timestamp=21, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:161: 11 => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=4 }
[21:56:20] src/van.cc:291: Barrier count for 4 : 1
[21:56:20] src/van.cc:161: 9 => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=4 }
[21:56:20] src/van.cc:291: Barrier count for 4 : 2
[21:56:20] src/van.cc:161: 13 => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=4 }
[21:56:20] src/van.cc:291: Barrier count for 4 : 3
[21:56:20] src/van.cc:161: 15 => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=4 }
[21:56:20] src/van.cc:291: Barrier count for 4 : 4
[21:56:20] src/van.cc:161: 1 => 1. Meta: request=0, timestamp=21, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:161: 17 => 1. Meta: request=1, timestamp=2, control={ cmd=BARRIER, barrier_group=4 }
[21:56:20] src/van.cc:291: Barrier count for 4 : 5
[21:56:20] src/van.cc:136: ? => 9. Meta: request=0, timestamp=23, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 11. Meta: request=0, timestamp=24, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 13. Meta: request=0, timestamp=25, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 15. Meta: request=0, timestamp=26, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:136: ? => 17. Meta: request=0, timestamp=27, control={ cmd=BARRIER, barrier_group=0 }
[21:56:20] src/van.cc:161: 1 => 1. Meta: request=1, timestamp=22, control={ cmd=BARRIER, barrier_group=7 }
[21:56:20] src/van.cc:291: Barrier count for 7 : 1
[Assertion failed: data_ != NULL || size_ == 0 (src/msg.cpp:97)
21:56:20] src/van.cc:136: ? => 1. Meta: request=1, timestamp=22, control={ cmd=BARRIER, barrier_group=7 }
bash: line 1: 83409 Abort trap: 6           python crash2.py
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no localhost -p 22 'export DMLC_SERVER_ID=4; export DMLC_WORKER_ID=3; export DMLC_PS_ROOT_URI=192.168.1.7; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9092; export DMLC_NUM_WORKER=5; export DMLC_NUM_SERVER=5; python crash2.py'' returned non-zero exit status 134
```
