### ISSUE TITLE
pooled_storage_manager.h:80: cudaMalloc failed: out of memory

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5340]
I set batch=1, and out of memory.
```
ssh://root@10.30.13.58:22/usr/bin/python -u /info/anjos/anjos_pycharm/
classification_lstm/lstm_train.py
2017-03-11 20:01:38,321 ====================[data_lstm_origin/train]数据基本信息==============================
2017-03-11 20:01:38,321 ==========桶尺寸=  30 对应样本数量= 1
2017-03-11 20:01:38,321 ==========共计数=1, 不合格数目= 0, batch数目=1, batch_size=1, 使用数=1
[20:01:40] src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[20:01:42] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./logging.h:300: [20:01:42] src/storage/./pooled_storage_manager.h:80: cudaMalloc failed: out of memory

Stack trace returned 50 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x13be6c) [0x7fb35aa3ee6c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc9b7b0) [0x7fb35b59e7b0]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc9d637) [0x7fb35b5a0637]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x99e160) [0x7fb35b2a1160]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9a4931) [0x7fb35b2a7931]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9aa344) [0x7fb35b2ad344]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9aa8a5) [0x7fb35b2ad8a5]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorBindEX+0xf90) [0x7fb35b243c40]
[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fb374d6de40]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fb374d6d8ab]
[bt] (10) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fb374f7d3df]
[bt] (11) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fb374f81d82]
[bt] (12) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (13) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (14) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (15) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (16) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (17) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (18) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (19) /usr/bin/python() [0x4de8b8]
[bt] (20) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (21) /usr/bin/python() [0x4f492e]
[bt] (22) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (23) /usr/bin/python() [0x4f46a7]
[bt] (24) /usr/bin/python() [0x4b670c]
[bt] (25) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (26) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (27) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (28) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (29) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (30) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (31) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (32) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (33) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (34) /usr/bin/python() [0x4de6fe]
[bt] (35) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (36) /usr/bin/python() [0x4f492e]
[bt] (37) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (38) /usr/bin/python() [0x4f46a7]
[bt] (39) /usr/bin/python() [0x4b670c]
[bt] (40) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (41) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (42) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (43) /usr/bin/python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (44) /usr/bin/python() [0x4f1def]
[bt] (45) /usr/bin/python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (46) /usr/bin/python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (47) /usr/bin/python(Py_Main+0x68a) [0x49e14a]
[bt] (48) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fb3764db830]
[bt] (49) /usr/bin/python(_start+0x29) [0x49d9d9]

Traceback (most recent call last):
  File "/info/anjos/anjos_pycharm/bowl_classification_lstm/lstm_train.py", line 127, in <module>
    TRAIN(data_root,model_prefix)
  File "/info/anjos/anjos_pycharm/bowl_classification_lstm/lstm_train.py", line 46, in __init__
    TRAIN.train_model(self.data_root,self.model_prefix,self.model_epochs)#开始训练
  File "/info/anjos/anjos_pycharm/bowl_classification_lstm/lstm_train.py", line 123, in train_model
    optimizer_params={'learning_rate': learning_rate, 'momentum': momentum, 'wd': wd})
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py", line 388, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 344, in bind
    grad_req=grad_req, input_types=input_types)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 193, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 232, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 532, in _bind_ith_exec
    grad_req=self.grad_req, shared_exec=shared_exec)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol.py", line 926, in bind
    ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:01:42] src/storage/./pooled_storage_manager.h:80: cudaMalloc failed: out of memory

Stack trace returned 50 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x13be6c) [0x7fb35aa3ee6c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc9b7b0) [0x7fb35b59e7b0]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xc9d637) [0x7fb35b5a0637]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x99e160) [0x7fb35b2a1160]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9a4931) [0x7fb35b2a7931]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9aa344) [0x7fb35b2ad344]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9aa8a5) [0x7fb35b2ad8a5]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorBindEX+0xf90) [0x7fb35b243c40]
[bt] (8) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fb374d6de40]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fb374d6d8ab]
[bt] (10) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fb374f7d3df]
[bt] (11) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fb374f81d82]
[bt] (12) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (13) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (14) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (15) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (16) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (17) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (18) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (19) /usr/bin/python() [0x4de8b8]
[bt] (20) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (21) /usr/bin/python() [0x4f492e]
[bt] (22) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (23) /usr/bin/python() [0x4f46a7]
[bt] (24) /usr/bin/python() [0x4b670c]
[bt] (25) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (26) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (27) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (28) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (29) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (30) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (31) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (32) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (33) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (34) /usr/bin/python() [0x4de6fe]
[bt] (35) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (36) /usr/bin/python() [0x4f492e]
[bt] (37) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (38) /usr/bin/python() [0x4f46a7]
[bt] (39) /usr/bin/python() [0x4b670c]
[bt] (40) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (41) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (42) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (43) /usr/bin/python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (44) /usr/bin/python() [0x4f1def]
[bt] (45) /usr/bin/python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (46) /usr/bin/python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (47) /usr/bin/python(Py_Main+0x68a) [0x49e14a]
[bt] (48) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fb3764db830]
[bt] (49) /usr/bin/python(_start+0x29) [0x49d9d9]


Process finished with exit code 1
```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
