### ISSUE TITLE
cudnn_convolution-inl.h:446: Check failed: cudnnSetTensorNdDescriptor CUDNN_STATUS_SUCCESS (9 vs. 0) 

### ISSUE THREAD

**Issue by whaozl** [apache/incubator-mxnet#5342]
ubuntu16.0.4 python2.7 mxnet0,9.3

```
[14:33:01] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./logging.h:300: [14:33:01] src/operator/./cudnn_convolution-inl.h:446: Check failed: cudnnSetTensorNdDescriptor(out_desc_, dtype_, static_cast<int>(oshape.ndim()), reinterpret_cast<int*>(&oshape[0]), reinterpret_cast<int*>(&ostride[0])) == CUDNN_STATUS_SUCCESS (9 vs. 0) 

Stack trace returned 51 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x13be6c) [0x7f564a0c6e6c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x15eaa51) [0x7f564b575a51]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x15e1314) [0x7f564b56c314]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xae1154) [0x7f564aa6c154]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xa6ffdc) [0x7f564a9fafdc]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9954f4) [0x7f564a9204f4]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9a9faa) [0x7f564a934faa]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9aa8a5) [0x7f564a9358a5]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorBindEX+0xf90) [0x7f564a8cbc40]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5664b8be40]
[bt] (10) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f5664b8b8ab]
[bt] (11) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f5664d9b3df]
[bt] (12) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f5664d9fd82]
[bt] (13) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (14) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (15) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (16) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (17) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (18) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (19) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (20) /usr/bin/python() [0x4de8b8]
[bt] (21) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (22) /usr/bin/python() [0x4f492e]
[bt] (23) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (24) /usr/bin/python() [0x4f46a7]
[bt] (25) /usr/bin/python() [0x4b670c]
[bt] (26) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (27) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (28) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (29) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (30) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (31) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (32) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (33) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (34) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (35) /usr/bin/python() [0x4de6fe]
[bt] (36) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (37) /usr/bin/python() [0x4f492e]
[bt] (38) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (39) /usr/bin/python() [0x4f46a7]
[bt] (40) /usr/bin/python() [0x4b670c]
[bt] (41) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (42) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (43) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (44) /usr/bin/python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (45) /usr/bin/python() [0x4f1def]
[bt] (46) /usr/bin/python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (47) /usr/bin/python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (48) /usr/bin/python(Py_Main+0x68a) [0x49e14a]
[bt] (49) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f566593a830]
[bt] (50) /usr/bin/python(_start+0x29) [0x49d9d9]

Traceback (most recent call last):
  File "/info/anjos/anjos_pycharm/bowl_classification_3d/vgg3d_train.py", line 104, in <module>
    TRAIN(data_root,model_prefix)
  File "/info/anjos/anjos_pycharm/bowl_classification_3d/vgg3d_train.py", line 41, in __init__
    TRAIN.train_model(self.data_root,self.model_prefix,self.model_epochs)#开始训练
  File "/info/anjos/anjos_pycharm/bowl_classification_3d/vgg3d_train.py", line 100, in train_model
    optimizer_params={'learning_rate': learning_rate, 'momentum': momentum, 'wd': wd})
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/base_module.py", line 388, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/module.py", line 344, in bind
    grad_req=grad_req, input_types=input_types)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 193, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 232, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/module/executor_group.py", line 532, in _bind_ith_exec
    grad_req=self.grad_req, shared_exec=shared_exec)
  File "/usr/local/lib/python2.7/dist-packages/mxnet/symbol.py", line 926, in bind
    ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:33:01] src/operator/./cudnn_convolution-inl.h:446: Check failed: cudnnSetTensorNdDescriptor(out_desc_, dtype_, static_cast<int>(oshape.ndim()), reinterpret_cast<int*>(&oshape[0]), reinterpret_cast<int*>(&ostride[0])) == CUDNN_STATUS_SUCCESS (9 vs. 0) 

Stack trace returned 51 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x13be6c) [0x7f564a0c6e6c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x15eaa51) [0x7f564b575a51]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x15e1314) [0x7f564b56c314]
[bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xae1154) [0x7f564aa6c154]
[bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0xa6ffdc) [0x7f564a9fafdc]
[bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9954f4) [0x7f564a9204f4]
[bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9a9faa) [0x7f564a934faa]
[bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(+0x9aa8a5) [0x7f564a9358a5]
[bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet/libmxnet.so(MXExecutorBindEX+0xf90) [0x7f564a8cbc40]
[bt] (9) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5664b8be40]
[bt] (10) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f5664b8b8ab]
[bt] (11) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f5664d9b3df]
[bt] (12) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f5664d9fd82]
[bt] (13) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (14) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (15) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (16) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (17) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (18) /usr/bin/python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (19) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (20) /usr/bin/python() [0x4de8b8]
[bt] (21) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (22) /usr/bin/python() [0x4f492e]
[bt] (23) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (24) /usr/bin/python() [0x4f46a7]
[bt] (25) /usr/bin/python() [0x4b670c]
[bt] (26) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (27) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (28) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (29) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (30) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (31) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (32) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (33) /usr/bin/python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (34) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (35) /usr/bin/python() [0x4de6fe]
[bt] (36) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (37) /usr/bin/python() [0x4f492e]
[bt] (38) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (39) /usr/bin/python() [0x4f46a7]
[bt] (40) /usr/bin/python() [0x4b670c]
[bt] (41) /usr/bin/python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (42) /usr/bin/python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (43) /usr/bin/python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (44) /usr/bin/python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (45) /usr/bin/python() [0x4f1def]
[bt] (46) /usr/bin/python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (47) /usr/bin/python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (48) /usr/bin/python(Py_Main+0x68a) [0x49e14a]
[bt] (49) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f566593a830]
[bt] (50) /usr/bin/python(_start+0x29) [0x49d9d9]

terminate called after throwing an instance of 'dmlc::Error'
terminate called after throwing an instance of 'dmlc::Error'
  what():  driver shutting down
  what():  driver shutting down
bash: line 1:  3899 Aborted                 (core dumped) env "PYTHONUNBUFFERED"="1" "PYTHONPATH"="/info/anjos/anjos_pycharm" "PYCHARM_HOSTED"="1" "JETBRAINS_REMOTE_RUN"="1" "PYTHONIOENCODING"="UTF-8" /usr/bin/python -u /info/anjos/anjos_pycharm/bowl_classification_3d/vgg3d_train.py

```

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
