### ISSUE TITLE
Arithmetic operations on symbols with single-element rhs

### ISSUE THREAD

**Issue by Kojoley** [apache/incubator-mxnet#5420]
## Environment info
OS: Windows-7-6.1.7601-SP2
MXNet installed from: https://github.com/yajiedesign/mxnet/releases/tag/20170316
Python version and distribution: 3.5.3 | packaged by conda-forge | (default, Feb  9 2017, 15:12:38) [MSC v.1900 64 bit (AMD64)]

## Error Message:
```
[02:25:39] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc\./logging.h:300: [02:25:39] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\operator\./elemwise_op_common.h:31: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _minus0 at 1-th input: expected (1,2,5), got (1,2,1)
infer_shape error. Arguments:
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    y.infer_shape()
  File "...\lib\site-packages\mxnet\symbol.py", line 588, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "...\lib\site-packages\mxnet\symbol.py", line 671, in _infer_shape_impl
    ctypes.byref(complete)))
  File "...\lib\site-packages\mxnet\base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator _minus0: [02:25:39] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\operator\./elemwise_op_common.h:31: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _minus0 at 1-th input: expected (1,2,5), got (1,2,1)
```

## Minimum reproducible example

```python
import mxnet as mx

x = mx.sym.var('x', shape=(1, 2, 5))
y = x - mx.sym.max(x, axis=2, keepdims=True)
y.infer_shape()
```

## `NDArray` works fine

```python
import mxnet as mx

x = mx.nd.array([[[0, 0.1, 0.5, 0.9, 1.0]]], dtype='float32')
y = x - mx.nd.max(x, axis=2, keepdims=True)
print(y.asnumpy())
```

**Comment by piiswrong** [comment]
use broadcast_sub

Symbolic API doesn't do broadcasting by default

**Comment by Kojoley** [comment]
Thanks for you reply!
Is there an option to turn on broadcasting for Symbols?
I am asking, because theno and tf are doing it, so different behavior then will require a wrapper for arithmetic operations and rewriting parts of existing code (what is not a cool thing in my case).

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
