### ISSUE TITLE
issue in example warpctc/toy_ctc.py

### ISSUE THREAD

**Issue by ilovin** [apache/incubator-mxnet#5435]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu 14.04

Compiler:make 3.81 gcc 5.4.1

cuda version: v8.0.44

cudnn: 5.05

Package used: Python

MXNet version: install from source

MXNet commit hash (`git rev-parse HEAD`): 93d00403b9d175812fdf6c749d5c4e587fd2782f

If you are using python package, please provide

Python version and distribution:  Python 3.5.2 :: Anaconda custom (64-bit)

## Error Message:
```
toy_ctc.py:152: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  initializer=mx.init.Xavier(factor_type="in", magnitude=2.34))
begin fit
[22:44:59] /data/gitRepo/mxnet/dmlc-core/include/dmlc/./logging.h:300: [22:44:59] src/operator/./slice_channel-inl.h:178: Check failed: ishape[real_axis] == param_.num_outputs (800 vs. 80) If squeeze axis is True, the size of the sliced axis must be the same as num_outputs. Input shape=(32,800), axis=1, num_outputs=80.

Stack trace returned 10 entries:
[bt] (0) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x39) [0x7f52113840e9]
[bt] (1) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op16SliceChannelProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x462) [0x7f5211eaebd2]
[bt] (2) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0xef68fa) [0x7f5211c7e8fa]
[bt] (3) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c3fc00) [0x7f52129c7c00]
[bt] (4) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c411db) [0x7f52129c91db]
[bt] (5) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c4229e) [0x7f52129ca29e]
[bt] (6) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x2f7) [0x7f52129afdf7]
[bt] (7) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x39f) [0x7f5211b2b2ef]
[bt] (8) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EESs+0x15a) [0x7f5211b31ffa]
[bt] (9) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0xdc0) [0x7f5211b24550]

infer_shape error. Arguments:
  label: (32, 4)
  l0_init_c: (32, 100)
  data: (32, 800)
  l0_init_h: (32, 100)
Traceback (most recent call last):
  File "toy_ctc.py", line 162, in <module>
    batch_end_callback=mx.callback.Speedometer(BATCH_SIZE, 50),)
  File "../../python/mxnet/model.py", line 772, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "../../python/mxnet/model.py", line 500, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "../../python/mxnet/symbol.py", line 588, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "../../python/mxnet/symbol.py", line 671, in _infer_shape_impl
    ctypes.byref(complete)))
  File "../../python/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator slicechannel0: [22:44:59] src/operator/./slice_channel-inl.h:178: Check failed: ishape[real_axis] == param_.num_outputs (800 vs. 80) If squeeze axis is True, the size of the sliced axis must be the same as num_outputs. Input shape=(32,800), axis=1, num_outputs=80.

Stack trace returned 10 entries:
[bt] (0) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x39) [0x7f52113840e9]
[bt] (1) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op16SliceChannelProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x462) [0x7f5211eaebd2]
[bt] (2) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0xef68fa) [0x7f5211c7e8fa]
[bt] (3) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c3fc00) [0x7f52129c7c00]
[bt] (4) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c411db) [0x7f52129c91db]
[bt] (5) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(+0x1c4229e) [0x7f52129ca29e]
[bt] (6) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorISsSaISsEE+0x2f7) [0x7f52129afdf7]
[bt] (7) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKSs+0x39f) [0x7f5211b2b2ef]
[bt] (8) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EESs+0x15a) [0x7f5211b31ffa]
[bt] (9) /data/gitRepo/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0xdc0) [0x7f5211b24550]
```

## Steps to reproduce
cd example/warpctc
python toy_ctc.py

## What have you tried to solve it?
1. change the config.mk and make clean&& make , python  setup.py install

**Comment by ksaluja15** [comment]
same issue

**Comment by Stardust-** [comment]
I think the mxnet vertion have some problem. I suggest you download a older vertion.I test a vertion in 2017/2/20, it's work.

**Comment by liueryun** [comment]
the same here

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
