### ISSUE TITLE
I have error in executing python_loss example

### ISSUE THREAD

**Issue by BBAUniversity** [apache/incubator-mxnet#5480]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04
Package used (Python/R/Scala/Julia):
Python
Error:
/home/facultemi/mxnet/python/mxnet/module/base_module.py:64: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/facultemi/mxnet/example/module/python_loss.py", line 60, in <module>
    num_epoch=n_epoch)
  File "/home/facultemi/mxnet/python/mxnet/module/base_module.py", line 471, in fit
    self.forward_backward(data_batch)
  File "/home/facultemi/mxnet/python/mxnet/module/base_module.py", line 195, in forward_backward
    self.backward()
  File "/home/facultemi/mxnet/python/mxnet/module/sequential_module.py", line 338, in backward
    module.backward(out_grads=out_grads)
  File "/home/facultemi/mxnet/python/mxnet/module/python_module.py", line 305, in backward
    self._backward_impl()
  File "/home/facultemi/mxnet/python/mxnet/module/python_module.py", line 319, in _backward_impl
    grad = self._grad_func(self._scores, self._labels)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
