### ISSUE TITLE
Problem about bi rnn

### ISSUE THREAD

**Issue by zhenxingjian** [apache/incubator-mxnet#5656]
I have got this error
```
infer_shape error. Arguments:
  data: (330, 1)
  softmax_label: (330, 1)
Traceback (most recent call last):
  File "form_line.py", line 237, in <module>
    train(args)
  File "form_line.py", line 158, in train
    model.fit(
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/base_module.py", line 388, in fit
    for_training=True, force_rebind=force_rebind)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/bucketing_module.py", line 186, in bind
    force_rebind=False, shared_module=None, grad_req=grad_req)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/module.py", line 345, in bind
    grad_req=grad_req)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/executor_group.py", line 197, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/executor_group.py", line 293, in bind_exec
    shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/executor_group.py", line 541, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/symbol.py", line 542, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/symbol.py", line 609, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator softmax: Shape inconsistent, Provided=(330,), inferred shape=(660,)
```
If I turn `bidirectional=False`, there will be no error. I don't know why. 

System: Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-45-generic x86_64)
Python: 2.7
MxNet: 0.9.4

**Comment by piiswrong** [comment]
Because bidirectional RNN's output shape is 2*num_hidden. @szha We need to document this

**Comment by zhenxingjian** [comment]
@piiswrong 
So should I concat the bidirectional RNN's output into num_hidden, or should I just make the num_hidden to be half of the input? 
If I should concat it, can you show me an example? 
Thanks a lot.

**Comment by szha** [comment]
@piiswrong the clarification in this issue has been documented in RNN API doc.
