### ISSUE TITLE
how to use two dist sync kv store in one job

### ISSUE THREAD

**Issue by Vogen** [apache/incubator-mxnet#5659]
I launch a distributed job using two neural network and I want both networks trained in parallel .
After launching, error occurs
```
python launcher.py -n 1 python a3c.py --kv-store=di
st_sync
libdc1394 error: Failed to initialize libdc1394
libdc1394 error: Failed to initialize libdc1394
create first dist sync kv store
libdc1394 error: Failed to initialize libdc1394
create second dist sync kv store
[09:49:58] ./include/dmlc/logging.h:208: [09:49:58] src/postoffice.cc:80: Check failed: (customers_.count(id)) == ((size_t)0) id 0 already exists
Traceback (most recent call last):
  File "a3c.py", line 172, in <module>
    train()
  File "a3c.py", line 32, in train
    kv_v = mx.kvstore.create(args.kv_store)
  File "/home/admin/mxnet/python/mxnet/kvstore.py", line 403, in create
    ctypes.byref(handle)))
  File "/home/admin/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [09:49:58] src/postoffice.cc:80: Check failed: (customers_.count(id)) == ((size_t)0) id 0 already exists
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "launcher.py", line 50, in exec_cmd
    raise RuntimeError('Get nonzero return code=%d' % ret)
RuntimeError: Get nonzero return code=1
```
Anyone can help me?

**Comment by Vogen** [comment]
@pluskid

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!

**Comment by JohnCalhoun** [comment]
I am also having this issue,
use case is trying to train a GAN, which requires two networks, over multiple GPUS/Machines
