### ISSUE TITLE
[scala] Module API: scala.MatchError in updateParams while training

### ISSUE THREAD

**Issue by benqua** [apache/incubator-mxnet#5661]
While training, I get a scala.MatchError exception in updateParams.

The network is built with the Module API.
The network is based on a pretrained VGG16 network where only the fully connected layers are replaced and trained. The task is a regression.
Part of the layers are not to be trained (listed in fixedParamNames).

The error arise when calling `fit`
## Environment info
MXNet version:
latest (about one week ago).

## Error Message:
```
[error] (run-main-0) scala.MatchError: ((ml.dmlc.mxnet.NDArray@38df5e3a,null),0) (of class scala.Tuple2)
scala.MatchError: ((ml.dmlc.mxnet.NDArray@38df5e3a,null),0) (of class scala.Tuple2)
	at ml.dmlc.mxnet.Model$$anonfun$updateParams$1$$anonfun$apply$4.apply(Model.scala:202)
	at ml.dmlc.mxnet.Model$$anonfun$updateParams$1$$anonfun$apply$4.apply(Model.scala:202)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at ml.dmlc.mxnet.Model$$anonfun$updateParams$1.apply(Model.scala:202)
	at ml.dmlc.mxnet.Model$$anonfun$updateParams$1.apply(Model.scala:194)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at ml.dmlc.mxnet.Model$.updateParams(Model.scala:194)
	at ml.dmlc.mxnet.module.Module.update(Module.scala:371)
	at ml.dmlc.mxnet.module.BaseModule$$anonfun$fit$1.apply$mcVI$sp(BaseModule.scala:375)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at ml.dmlc.mxnet.module.BaseModule.fit(BaseModule.scala:365)
	at benq.kaggle.natcons.FishDetector1$.main(FishDetector1.scala:64)
	at benq.kaggle.natcons.FishDetector1.main(FishDetector1.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
The problem is that gradArrays is null.  

## Minimum reproducible example
Data Shapes (with batch size = 128):
 - data shape: (128,3,204,204)
 - label shape: (128)

```scala
    val path = "data/fd/windowed/"
    val prefix = "vgg16n"
    val lastLayerBeforeFC = "flatten_0"

    logger.info("Loading model")
    val (sym, argParams, auxParams) = Model.loadCheckpoint(prefix, 0)
    val net = sym.getInternals.get(s"${lastLayerBeforeFC}_output")
    val newArgParams = argParams.filterNot(_._1.contains("fc"))
    val convLayers = newArgParams.keySet
    logger.info("newArgParams: " +newArgParams.mkString(" "))

    // group 6
    val fc6 = Symbol.FullyConnected("fc6")()(Map("data" -> net, "num_hidden" -> 512))
    val relu6 = Symbol.Activation("relu6")()(Map("data" -> fc6, "act_type" -> "relu"))
    // group 7
    val fc7 = Symbol.FullyConnected("fc7")()(Map("data" -> relu6, "num_hidden" -> 512))
    val relu7 = Symbol.Activation("relu7")()(Map("data" -> fc7, "act_type" -> "relu"))
    // output
    val fc8 = Symbol.FullyConnected("fc8")()(Map("data" -> relu7, "num_hidden" -> 1))
    val label = Symbol.Variable("label")
    val linReg = Symbol.LinearRegressionOutput("reg_output")()(Map("data" -> fc8, "label" -> label))

    logger.info("get data iterator")
    val imgPath = "data/fd/windowed"
    val batchSize = 128
    val (trainIter, validIter) = ImageDataIter.getTrainAndValidIterators(path, batchSize, 0.2f)

    logger.info("building network")
    val vgg16 = new Module(
      symbolVar = linReg,
      dataNames = IndexedSeq("data"),
      labelNames = IndexedSeq("label"),
      contexts = Context.gpu(0),
      fixedParamNames = Some(convLayers)
    )
    vgg16.bind(
      dataShapes = trainIter.provideData,
      labelShapes = Some(trainIter.provideLabel),
      forTraining = true
    )
    vgg16.initParams(
      argParams = newArgParams,
      allowMissing = true
    )

    logger.info("fit the network")
    val fitParams = new FitParams()
    fitParams.setEvalMetric(new MSE())
    vgg16.fit(trainIter, Some(validIter), 1, fitParams)
```

**Comment by benqua** [comment]
@javelinjs, @Ldpe2G Any idea / hint why an item of gradList in https://github.com/dmlc/mxnet/blob/master/scala-package/core/src/main/scala/ml/dmlc/mxnet/Model.scala#L201 could be null?

**Comment by Ldpe2G** [comment]
@benqua it is werid. Dit you try the intermediate level api in this Module example:
https://github.com/dmlc/mxnet/blob/master/scala-package/examples/src/main/scala/ml/dmlc/mxnetexamples/module/MnistMlp.scala#L43

**Comment by benqua** [comment]
@Ldpe2G thanks for your answer. I will try your suggestion.

In the mean time, I tried removing the fixedParamNames parameter and the error is gone.
The bug is likely in the handling of the layers that should not be trained.

**Comment by javelinjs** [comment]
@benqua Could you give the MXNet version of git commit SHA?

**Comment by benqua** [comment]
@Ldpe2G sure, it is 2735414c9f55e3e33d7eeb0c0293e0175e2644d6

I am gonna try with the latest version.

**Comment by benqua** [comment]
@javelinjs I tried with the latest version now that the compilation issue has been solved and got the same result.

**Comment by javelinjs** [comment]
I see, will look into it these days.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
