### ISSUE TITLE
Worker threads fail to join

### ISSUE THREAD

**Issue by eric-haibin-lin** [apache/incubator-mxnet#5720]
The code snippet below hangs.  It prints "done" but doesn't exit program. 

MXNet version: 0f6b6b3d98d06dbbc7748086b05b149277773839 
Env: AWS Ubuntu DL AMI

```
import os
import mxnet as mx

def test_ctx_group():
    data = mx.symbol.Variable('data')
    out  = mx.symbol.broadcast_add(data, data)
    texec = out.simple_bind(mx.cpu(0), data=(1,200))
    print("done")

if __name__ == '__main__':
    test_ctx_group()
```

If debug it with gdb, it shows it's blocked at 
```
^C
Program received signal SIGINT, Interrupt.
0x00007ffff7bc565b in pthread_join (threadid=140736057591552, thread_return=0x0) at pthread_join.c:92
92      pthread_join.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7bc565b in pthread_join (threadid=140736057591552, thread_return=0x0) at pthread_join.c:92
#1  0x00007fffedcbd857 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007fffa4155cb3 in mxnet::common::LazyAllocArray<mxnet::engine::ThreadedEnginePerDevice::ThreadWorkerBlock<(dmlc::ConcurrentQueueType)0> >::Clear() ()
   from /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so
#3  0x00007fffa41566d6 in mxnet::engine::ThreadedEnginePerDevice::~ThreadedEnginePerDevice() () from /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so
#4  0x00007fffa4156a69 in mxnet::engine::ThreadedEnginePerDevice::~ThreadedEnginePerDevice() () from /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so
#5  0x00007fffa41465da in std::shared_ptr<mxnet::Engine>::~shared_ptr() () from /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so
#6  0x00007ffff78331a9 in __run_exit_handlers (status=0, listp=0x7ffff7bb56c8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#7  0x00007ffff78331f5 in __GI_exit (status=<optimized out>) at exit.c:104
#8  0x00007ffff7818f4c in __libc_start_main (main=0x466e50 <main>, argc=2, argv=0x7fffffffddc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7fffffffddb8) at libc-start.c:321
#9  0x0000000000577c2e in _start ()
```

**Comment by cjolivier01** [comment]
Fix in this PR:  https://github.com/dmlc/mxnet/pull/6773
