### ISSUE TITLE
DataIO with mx.image.ImageIter / file to give to path_imgidx

### ISSUE THREAD

**Issue by TheJude** [apache/incubator-mxnet#5763]
Hello guys,

I've been trying to read recordIO files with mx.image.ImageIter using Python (Python version 2.7, mxnet version 0.9.5, Windows 10). my code file read_augment_data.py looks as follows:

dataiter_train = mx.image.ImageIter(
	path_imgrec="../imagerecords.rec", 
        data_shape=(3,512,512),
	path_imgidx="../imageindex.idx",
	batch_size=batch_size,
	shuffle=False,
)

#plot 16 images to see they are correctly loaded and check augmentation
dataiter_train.reset()
batch = dataiter_train.next()
data = batch.data[0]
for i in range(16):
	plt.subplot(4,4,i+1)
	plt.imshow(data[i].asnumpy().astype(np.uint8).transpose((1,2,0)))

plt.show()

The code works fine, as long as shuffle=False. If I set set shuffle=True the following error occurs:

Traceback (most recent call last):
  File "read_augment_data_02.py", line 84, in <module>
    batch = dataiter_train.next()
  File "C:\Users\hup56199\Anaconda2\envs\mxnet\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\image.py", line 439, in next
    label, s = self.next_sample()
  File "C:\Users\hup56199\Anaconda2\envs\mxnet\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\image.py", line 412, in next_sample
    s = self.imgrec.read_idx(idx)
  File "C:\Users\hup56199\Anaconda2\envs\mxnet\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\recordio.py", line 156, in read_idx
    return self.read()
  File "C:\Users\hup56199\Anaconda2\envs\mxnet\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\recordio.py", line 93, in read
    ctypes.byref(size)))
  File "C:\Users\hup56199\Anaconda2\envs\mxnet\lib\site-packages\mxnet-0.9.5-py2.7.egg\mxnet\base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:05:02] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\dmlc-core\src\recordio.cc:65: Check failed: header[0] == RecordIOWriter::kMagic Invalid RecordIO File

My first guess was that the index file I provide with path_imgidx is not correct. It has two columns: first column an index and second column a label (I shuffled the images bevor generating the recordio file, thats why numbers in first column are not in order):

456  2
123  4
45    1
...

Using the file name xy.jpg in either column also did not work.
Any help would be really appreciated here. Maybe it is possible to provide an example of how to use the ImageIter with shuffle=True?

Thanks in advance!

**Comment by piiswrong** [comment]
index file is generated by tools/im2rec.py

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
