### ISSUE TITLE
AssertionError: File "/mxnet-ssd/dataset/iterator.py", line 134, in _get_batch     assert len(batch_data) > 0

### ISSUE THREAD

**Issue by tianke0711** [apache/incubator-mxnet#5819]
hi I used this model to detect food images, there is error whe I want to run my predict code. the error is following, the cloud server is Ubuntu 16.04, thanks

`Traceback (most recent call last):
  File "predict_500_845.py", line 330, in <module>
    dump_image(out_file, image_list,test_crop_dir,debug)
  File "predict_500_845.py", line 155, in dump_image
    dets = detector.im_detect(image_list, dir, extension)
  File "i/mxnet-ssd/detect/detector.py", line 95, in im_detect
    is_train=False)
  File "i/mxnet-ssd/dataset/iterator.py", line 70, in __init__
    self._get_batch()
  File "i/mxnet-ssd/dataset/iterator.py", line 134, in _get_batch
    assert len(batch_data) > 0
AssertionError
`

**Comment by tianke0711** [comment]
I have solved it, the file name is wrong.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
