### ISSUE TITLE
Plan for mxnet version of MobileNets

### ISSUE THREAD

**Issue by AnranQi** [apache/incubator-mxnet#5891]
Google has published an article 'MobileNets: Efficient Convolutional Neural Networks for Mobile Vision
Applications' on 17 Apr.  They propose a MobileNets for mobile and embedded vision applications which is fast and small with high accuracy. And Google plan on releasing models in Tensor Flow. Is anyone interested in this? Does the Mxnet committee plan to do this project in the future? If so, when the mxnet version will be released?

**Comment by zhreshold** [comment]
I think the only thing need to be added is the channel-wise/depth-wise convolution

**Comment by austingg** [comment]
using group to implment depth-wise convolution is very slow

**Comment by mli** [comment]
@austingg can you please provide more information how slow it is?

**Comment by zhreshold** [comment]
@mli 
The num_group trick is not optimized for gpu, especially cudnn
.
I posted it on gist for the simulated version of vgg: https://gist.github.com/zhreshold/bb9ddae7e3ba371e469b9084c5cccd8c
and the results using train_imagenet.py with --benchmark
```
[14:51:08] src/operator/././cudnn_algoreg-inl.h:57: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [20]	Speed: 51.17 samples/sec	Train-accuracy=0.016369
INFO:root:Epoch[0] Batch [40]	Speed: 50.82 samples/sec	Train-accuracy=0.030469
INFO:root:Epoch[0] Train-accuracy=0.031250
INFO:root:Epoch[0] Time cost=65.989
INFO:root:Epoch[1] Batch [20]	Speed: 50.86 samples/sec	Train-accuracy=0.031250
```

Compared to original vgg in example
```
[14:44:29] src/operator/././cudnn_algoreg-inl.h:57: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
INFO:root:Epoch[0] Batch [20]	Speed: 152.05 samples/sec	Train-accuracy=0.014137
INFO:root:Epoch[0] Batch [40]	Speed: 153.50 samples/sec	Train-accuracy=0.015625
INFO:root:Epoch[0] Train-accuracy=0.015625
INFO:root:Epoch[0] Time cost=25.111
INFO:root:Epoch[1] Batch [20]	Speed: 152.22 samples/sec	Train-accuracy=0.015625

```
Theoretically we should get 9x faster, but it's 3x slower using num_group trick on gpu.

Now switch to cpu, single thread, I got 1.72 samples/sec for vgg_depthwise and 0.39 samples/sec for standard vgg, a 4.4x reasonable speed up.

Any plan to write a specialized version for channel-wise conv? We could benefit from reshaping and get rid of num_group loops.

**Comment by austingg** [comment]
@mli  The mobilenet is trainning on the way.  Currently, an epoch(ImageNet) costs about 6500 s on two GTX 1080 card. 
``` shell 
INFO:root:Epoch[35] Batch [1700]	Speed: 196.23 samples/sec	Train-accuracy=0.484453
INFO:root:Epoch[35] Batch [1750]	Speed: 196.61 samples/sec	Train-accuracy=0.474922
INFO:root:Epoch[35] Batch [1800]	Speed: 195.15 samples/sec	Train-accuracy=0.472969
INFO:root:Epoch[35] Batch [1850]	Speed: 193.84 samples/sec	Train-accuracy=0.474766
INFO:root:Epoch[35] Batch [1900]	Speed: 194.25 samples/sec	Train-accuracy=0.479375
INFO:root:Epoch[35] Batch [1950]	Speed: 194.42 samples/sec	Train-accuracy=0.480703
INFO:root:Epoch[35] Batch [2000]	Speed: 193.91 samples/sec	Train-accuracy=0.473359
INFO:root:Epoch[35] Batch [2050]	Speed: 195.30 samples/sec	Train-accuracy=0.480000
INFO:root:Epoch[35] Batch [2100]	Speed: 194.94 samples/sec	Train-accuracy=0.468125
```

**Comment by thatindiandude** [comment]
I'm experiencing an error when replacing the first 5x5 conv layer like so: 

``` 
conv1 = depthwise_conv(data=data, kernel=(5,5), pad=(1,1), num_filter=3, name="\
conv1", num_group=3)
```

in lenet when using `python train_mnist.py --network lenet`: 

```
infer_shape error. Arguments:
  data: (64, 1L, 28L, 28L)
  softmax_label: (64,)
Traceback (most recent call last):
  File "train_mnist.py", line 76, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/home/ubuntu/src/mxnet/example/image-classification/common/fit.py", line 187, in fit
    monitor            = monitor)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/base_module.py", line 445, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/module.py", line 388, in bind
    state_names=self._state_names)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/executor_group.py", line 205, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/ubuntu/src/mxnet/python/mxnet/module/executor_group.py", line 301, in bind_exec
    shared_group))
  File "/home/ubuntu/src/mxnet/python/mxnet/module/executor_group.py", line 548, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/ubuntu/src/mxnet/python/mxnet/symbol.py", line 747, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/home/ubuntu/src/mxnet/python/mxnet/symbol.py", line 871, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/ubuntu/src/mxnet/python/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator conv1_depthwise: [21:16:34] src/operator/./convolution-inl.h:396: Check failed: dshape[1] % param_.num_group == 0U (1 vs. 0) 1 3 input num_filter must divide group size
```

Is there something I'm not doing properly?

**Comment by thatindiandude** [comment]
I would like to point to some findings I had with using MKL and @zhreshold's implementation of Depthwise Separable Convolutions training on CIFAR-10 on a c4.8xlarge (Intel Xeon E5-2666 v3 CPU)

** Vanilla Resnet **
```
MKL Build:20170209
INFO:root:Epoch[0] Batch [20]	Speed: 100.25 samples/sec	Train-accuracy=0.111235
INFO:root:Epoch[0] Batch [40]	Speed: 121.83 samples/sec	Train-accuracy=0.186719
INFO:root:Epoch[0] Batch [60]	Speed: 137.36 samples/sec	Train-accuracy=0.203906
INFO:root:Epoch[0] Batch [80]	Speed: 155.15 samples/sec	Train-accuracy=0.219922
INFO:root:Epoch[0] Batch [100]	Speed: 147.89 samples/sec	Train-accuracy=0.244531
```

**Resnet w/ Depthwise Separable Convolutions **
```
MKL Build:20170209
INFO:root:Epoch[0] Batch [20]	Speed: 73.22 samples/sec	Train-accuracy=0.117188
INFO:root:Epoch[0] Batch [40]	Speed: 138.27 samples/sec	Train-accuracy=0.170313
INFO:root:Epoch[0] Batch [60]	Speed: 132.47 samples/sec	Train-accuracy=0.206250
INFO:root:Epoch[0] Batch [80]	Speed: 138.98 samples/sec	Train-accuracy=0.242578
INFO:root:Epoch[0] Batch [100]	Speed: 156.11 samples/sec	Train-accuracy=0.250781
```

Without MKL turned out, the results were more exaggerated (~2.5x speed-up). However, without using MKL, throughput is 10x slower.

**Comment by KeyKy** [comment]
[here](https://github.com/KeyKy/mobilenet-mxnet) has a mobilenet.

**Comment by pallashadow** [comment]
@KeyKy I think your version is 2.5x slower than this one? Both on CPU and GPU. 
https://github.com/pby5/MobileNet_Mxnet

**Comment by KeyKy** [comment]
@pallashadow I don't know. I implement mobilenet by group tricks.

**Comment by austingg** [comment]
@pallashadow  That's link also implement depthwise conv using group tricks.

**Comment by ysh329** [comment]
Mark

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
