### ISSUE TITLE
How to initialize a network (weights) with two loss functions?

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#5894]
I used symbol I defined (contains two loss functions). When executing `python train_cifar10.py --network snet  --pad-size 0`, it output error message below : 
```Shell
ValueError: Unknown initialization pattern for logisticRegression_label. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern
```

* Is this error message caused by another loss function? 
* Does MXNet initialize only one loss function defaultly?

## More concretely

```Shell
 yuens@Spark ~/Software/mxnet/example/image-classification$ python train_cifar10.py --network snet  --pad-size 0
INFO:root:start with arguments Namespace(batch_size=128, benchmark=0, data_nthreads=4, data_train='data/cifar10_train.rec', data_val='data/cifar10_val.rec', disp_batches=20, dtype='float32', gpus=None, image_shape='3,32,32', kv_store='device', load_epoch=None, lr=0.05, lr_factor=0.1, lr_step_epochs='200,250', max_random_aspect_ratio=0, max_random_h=36, max_random_l=50, max_random_rotate_angle=0, max_random_s=50, max_random_scale=1, max_random_shear_ratio=0, min_random_scale=1, model_prefix=None, mom=0.9, monitor=0, network='snet', num_classes=10, num_epochs=300, num_examples=50000, num_layers=110, optimizer='sgd', pad_size=0, random_crop=1, random_mirror=1, rgb_mean='123.68,116.779,103.939', test_io=0, top_k=0, wd=0.0001)
[11:30:49] src/io/iter_image_recordio_2.cc:135: ImageRecordIOParser2: data/cifar10_train.rec, use 3 threads for decoding..
[11:30:49] src/io/iter_image_recordio_2.cc:135: ImageRecordIOParser2: data/cifar10_val.rec, use 3 threads for decoding..
Traceback (most recent call last):
  File "train_cifar10.py", line 57, in <module>
    fit.fit(args, sym, data.get_rec_iter)
  File "/home/yuens/Software/mxnet/example/image-classification/common/fit.py", line 187, in fit
    monitor            = monitor)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/base_module.py", line 449, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/module.py", line 273, in init_params
    _impl(desc, arr, arg_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/module.py", line 268, in _impl
    initializer(name, arr)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/initializer.py", line 92, in __call__
    self._init_default(desc, arr)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/initializer.py", line 178, in _init_default
    'Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern' % name)
ValueError: Unknown initialization pattern for logisticRegression_label. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern

```

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
