### ISSUE TITLE
Cross Entropy doesn't change when running LSTM speech timit demo

### ISSUE THREAD

**Issue by lijianhackthon** [apache/incubator-mxnet#6175]
I am new to MXnet and have just installed the newest MXnet in my Ubuntu 14.04.5 LTS server by using `bash install-mxnet-ubuntu-python.sh` command. I have tried some matrix computation demo by using both CPU and GPU after installation. It proved that the installation was successful.

As a Kaldi user, my goal is to try using mxnet to train acoustic models. So I decided to try the [Speech LSTM Demo](http://mxnet.io/tutorials/speech_recognition/speech_lstm.html). The kaldi part of timit was already successful and after modifing all configurations related to mxnet, I ran the run_timit.sh script and the configuration file that I used was default_timit.cfg. Then I got the following error report:
```
==============================================================================
[data]
kaldi_root = 
train = exp_mxnet/data-for-mxnet/train.feats
dev = exp_mxnet/data-for-mxnet/dev.feats
test = 
out_file = |
format = kaldi
xdim = 13
ydim = 1951
label_mean = label_mean.feats

[arch]
num_hidden = 1024
num_hidden_proj = 512
num_lstm_layer = 3

[train]
batch_size = 40
buckets = 100, 200, 300, 400, 500, 600, 700, 800
num_epoch = 12
truncate_len = 20
context = gpu3
method = truncated-bptt
prefix = /home/user/tools/kaldi/egs/timit/s5/exp_mxnet/timit
learning_rate = 1
decay_factor = 2
decay_lower_bound = 1e-6
optimizer = speechSGD
momentum = 0.9
clip_gradient = 0
initializer = Uniform
init_scale = 0.05
weight_decay = 0.008
show_every = 1000                                                                                                          

Loading data into memory...
    3320 utterances loaded...
    avg-sequence-len = 304
Loading data into memory...
    376 utterances loaded...
    avg-sequence-len = 306
[14:44:29] src/operator/tensor/./matrix_op-inl.h:144: Using target_shape will be deprecated.
[14:44:29] src/operator/tensor/./matrix_op-inl.h:144: Using target_shape will be deprecated.
Traceback (most recent call last):
  File "train_lstm_proj.py", line 303, in <module>
    do_training(training_method, args, module, data_train, data_val)
  File "train_lstm_proj.py", line 197, in do_training
    module.update()
  File "/home/user/tools/mxnet/python/mxnet/module/module.py", line 569, in update
    kvstore=self._kvstore)
  File "/home/user/tools/mxnet/python/mxnet/model.py", line 116, in _update_params
    updater(index*num_device+k, g, w)
  File "/home/user/tools/mxnet/python/mxnet/optimizer.py", line 679, in __call__
    self.optimizer.update(index, weight, grad, self.states[index])
  File "/home/user/tools/kaldi/egs/timit/s5/speechSGD.py", line 100, in update
    if state:
  File "/home/user/tools/mxnet/python/mxnet/ndarray.py", line 235, in __bool__
    raise ValueError("The truth value of an NDArray with more than one element is ambiguous.")
ValueError: The truth value of an NDArray with more than one element is ambiguous.
```
The error report showed that this error was due to the judgement `if state` in speechSGD.py at No. 100 line. The return value of it was an array of boolean values rather than a `True` or `Flase`. I changed the `if state` to `if state is not None` because I have seen the definition of class SGD in optimizer.py. I think the speechSGD is just similar to SGD class. 

After this modification, the demo could be run through, but the cross-entropy of train and dev set became constant after first batch in Epoch[0]. 
```
[15:02:18] src/operator/tensor/./matrix_op-inl.h:144: Using target_shape will be deprecated.
[15:02:18] src/operator/tensor/./matrix_op-inl.h:144: Using target_shape will be deprecated.
2017-05-09 15:07:21,268 Epoch[0] Batch [1000]	Speed: 133.53 samples/sec	Train-CrossEntropy=22.763932
2017-05-09 15:07:21,269 Epoch[0] Batch [1000]	Speed: 133.53 samples/sec	Train-Acc_exclude_padding=0.001401
2017-05-09 15:08:50,952 Epoch[0] Train-CrossEntropy=23.025851
2017-05-09 15:08:50,952 Epoch[0] Train-Acc_exclude_padding=0.000000
2017-05-09 15:08:50,952 Epoch[0] Time cost=389.625
2017-05-09 15:09:10,193 Epoch[0] Dev-CrossEntropy=23.025851
2017-05-09 15:09:10,193 Epoch[0] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:09:10,687 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0001.params"
2017-05-09 15:13:50,847 Epoch[1] Batch [1000]	Speed: 142.84 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:13:50,847 Epoch[1] Batch [1000]	Speed: 142.84 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:15:19,026 Epoch[1] Train-CrossEntropy=23.025851
2017-05-09 15:15:19,026 Epoch[1] Train-Acc_exclude_padding=0.000000
2017-05-09 15:15:19,026 Epoch[1] Time cost=368.338
2017-05-09 15:15:38,196 Epoch[1] Dev-CrossEntropy=23.025851
2017-05-09 15:15:38,196 Epoch[1] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:15:38,640 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0002.params"
2017-05-09 15:20:16,112 Epoch[2] Batch [1000]	Speed: 144.23 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:20:16,112 Epoch[2] Batch [1000]	Speed: 144.23 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:21:37,365 Epoch[2] Train-CrossEntropy=23.025851
2017-05-09 15:21:37,365 Epoch[2] Train-Acc_exclude_padding=0.000000
2017-05-09 15:21:37,365 Epoch[2] Time cost=358.725
2017-05-09 15:21:55,467 Epoch[2] Dev-CrossEntropy=23.025851
2017-05-09 15:21:55,467 Epoch[2] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:21:55,946 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0003.params"
2017-05-09 15:26:42,355 Epoch[3] Batch [1000]	Speed: 139.74 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:26:42,355 Epoch[3] Batch [1000]	Speed: 139.74 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:28:16,193 Epoch[3] Train-CrossEntropy=23.025851
2017-05-09 15:28:16,193 Epoch[3] Train-Acc_exclude_padding=0.000000
2017-05-09 15:28:16,193 Epoch[3] Time cost=380.247
2017-05-09 15:28:35,114 Epoch[3] Dev-CrossEntropy=23.025851
2017-05-09 15:28:35,115 Epoch[3] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:28:36,031 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0004.params"
2017-05-09 15:33:09,541 Epoch[4] Batch [1000]	Speed: 146.31 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:33:09,541 Epoch[4] Batch [1000]	Speed: 146.31 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:34:30,677 Epoch[4] Train-CrossEntropy=23.025851
2017-05-09 15:34:30,677 Epoch[4] Train-Acc_exclude_padding=0.000000
2017-05-09 15:34:30,677 Epoch[4] Time cost=354.646
2017-05-09 15:34:48,082 Epoch[4] Dev-CrossEntropy=23.025851
2017-05-09 15:34:48,083 Epoch[4] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:34:48,567 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0005.params"
2017-05-09 15:39:06,328 Epoch[5] Batch [1000]	Speed: 155.27 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:39:06,328 Epoch[5] Batch [1000]	Speed: 155.27 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:40:27,232 Epoch[5] Train-CrossEntropy=23.025851
2017-05-09 15:40:27,233 Epoch[5] Train-Acc_exclude_padding=0.000000
2017-05-09 15:40:27,233 Epoch[5] Time cost=338.665
2017-05-09 15:40:45,322 Epoch[5] Dev-CrossEntropy=23.025851
2017-05-09 15:40:45,322 Epoch[5] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:40:45,765 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0006.params"
2017-05-09 15:45:02,533 Epoch[6] Batch [1000]	Speed: 155.84 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:45:02,533 Epoch[6] Batch [1000]	Speed: 155.84 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:46:24,032 Epoch[6] Train-CrossEntropy=23.025851
2017-05-09 15:46:24,032 Epoch[6] Train-Acc_exclude_padding=0.000000
2017-05-09 15:46:24,032 Epoch[6] Time cost=338.267
2017-05-09 15:46:42,172 Epoch[6] Dev-CrossEntropy=23.025851
2017-05-09 15:46:42,172 Epoch[6] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:46:42,730 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0007.params"
2017-05-09 15:51:16,957 Epoch[7] Batch [1000]	Speed: 145.94 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:51:16,957 Epoch[7] Batch [1000]	Speed: 145.94 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:52:46,634 Epoch[7] Train-CrossEntropy=23.025851
2017-05-09 15:52:46,635 Epoch[7] Train-Acc_exclude_padding=0.000000
2017-05-09 15:52:46,635 Epoch[7] Time cost=363.904
2017-05-09 15:53:05,300 Epoch[7] Dev-CrossEntropy=23.025851
2017-05-09 15:53:05,301 Epoch[7] Dev-Acc_exclude_padding=0.000000
2017-05-09 15:53:05,817 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0008.params"
2017-05-09 15:58:04,862 Epoch[8] Batch [1000]	Speed: 133.81 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 15:58:04,863 Epoch[8] Batch [1000]	Speed: 133.81 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 15:59:40,217 Epoch[8] Train-CrossEntropy=23.025851
2017-05-09 15:59:40,217 Epoch[8] Train-Acc_exclude_padding=0.000000
2017-05-09 15:59:40,217 Epoch[8] Time cost=394.400
2017-05-09 16:00:00,101 Epoch[8] Dev-CrossEntropy=23.025851
2017-05-09 16:00:00,101 Epoch[8] Dev-Acc_exclude_padding=0.000000
2017-05-09 16:00:00,553 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0009.params"
2017-05-09 16:05:00,288 Epoch[9] Batch [1000]	Speed: 133.51 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 16:05:00,288 Epoch[9] Batch [1000]	Speed: 133.51 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 16:06:34,220 Epoch[9] Train-CrossEntropy=23.025851
2017-05-09 16:06:34,220 Epoch[9] Train-Acc_exclude_padding=0.000000
2017-05-09 16:06:34,220 Epoch[9] Time cost=393.667
2017-05-09 16:06:53,523 Epoch[9] Dev-CrossEntropy=23.025851
2017-05-09 16:06:53,523 Epoch[9] Dev-Acc_exclude_padding=0.000000
2017-05-09 16:06:53,995 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0010.params"
2017-05-09 16:11:50,271 Epoch[10] Batch [1000]	Speed: 135.06 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 16:11:50,271 Epoch[10] Batch [1000]	Speed: 135.06 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 16:13:23,357 Epoch[10] Train-CrossEntropy=23.025851
2017-05-09 16:13:23,357 Epoch[10] Train-Acc_exclude_padding=0.000000
2017-05-09 16:13:23,357 Epoch[10] Time cost=389.362
2017-05-09 16:13:43,021 Epoch[10] Dev-CrossEntropy=23.025851
2017-05-09 16:13:43,021 Epoch[10] Dev-Acc_exclude_padding=0.000000
2017-05-09 16:13:43,499 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0011.params"
2017-05-09 16:18:40,732 Epoch[11] Batch [1000]	Speed: 134.66 samples/sec	Train-CrossEntropy=23.025851
2017-05-09 16:18:40,733 Epoch[11] Batch [1000]	Speed: 134.66 samples/sec	Train-Acc_exclude_padding=0.000000
2017-05-09 16:20:13,487 Epoch[11] Train-CrossEntropy=23.025851
2017-05-09 16:20:13,487 Epoch[11] Train-Acc_exclude_padding=0.000000
2017-05-09 16:20:13,487 Epoch[11] Time cost=389.988
2017-05-09 16:20:33,021 Epoch[11] Dev-CrossEntropy=23.025851
2017-05-09 16:20:33,021 Epoch[11] Dev-Acc_exclude_padding=0.000000
2017-05-09 16:20:33,584 Saved checkpoint to "/home/user/tools/kaldi/egs/timit/s5/checkpoints/exp_mxnet/timit-0012.params"
```
I think it's a big problem and I am still struggling with it. Can anyone give me some advice about how to debug this problem? Thanks very much.

**Comment by lijianhackthon** [comment]
In addition, I have tried this demo using my own audios rather than Timit data. The Cross-entropy of the train and dev set finally turned out to be same as Timit, i.e. **23.025851**

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
