### ISSUE TITLE
warpctc run sample error

### ISSUE THREAD

**Issue by kernel8liang** [apache/incubator-mxnet#6297]
```
lstm_ocr.py:196: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  initializer=mx.init.Xavier(factor_type="in", magnitude=2.34))
begin fit
[15:09:56] /home/liang/workspace/mxnet/dmlc-core/include/dmlc/./logging.h:304: [15:09:56] src/operator/./slice_channel-inl.h:198: Check failed: ishape[real_axis] == static_cast<size_t>(param_.num_outputs) (2400 vs. 80) If squeeze axis is True, the size of the sliced axis must be the same as num_outputs. Input shape=(32,2400), axis=1, num_outputs=80.

Stack trace returned 10 entries:
[bt] (0) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f44b834977c]
[bt] (1) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op16SliceChannelProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x5ad) [0x7f44b902c45d]
[bt] (2) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0xff62f2) [0x7f44b8d762f2]
[bt] (3) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0x212eadc) [0x7f44b9eaeadc]
[bt] (4) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0x213007a) [0x7f44b9eb007a]
[bt] (5) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0x213138d) [0x7f44b9eb138d]
[bt] (6) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7f44b9ed668c]
[bt] (7) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f44b912ff49]
[bt] (8) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e5) [0x7f44b9133435]
[bt] (9) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0xdeb) [0x7f44b91290cb]

infer_shape error. Arguments:
  label: (32, 4)
  l0_init_c: (32, 100)
  l1_init_h: (32, 100)
  l0_init_h: (32, 100)
  data: (32, 2400)
  l1_init_c: (32, 100)
Traceback (most recent call last):
  File "lstm_ocr.py", line 210, in <module>
    epoch_end_callback = mx.callback.do_checkpoint(prefix, 1))
  File "../../python/mxnet/model.py", line 782, in fit
    self._init_params(data.provide_data+data.provide_label)
  File "../../python/mxnet/model.py", line 502, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "../../python/mxnet/symbol.py", line 872, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "../../python/mxnet/symbol.py", line 998, in _infer_shape_impl
    ctypes.byref(complete)))
  File "../../python/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator slicechannel0: [15:09:56] src/operator/./slice_channel-inl.h:198: Check failed: ishape[real_axis] == static_cast<size_t>(param_.num_outputs) (2400 vs. 80) If squeeze axis is True, the size of the sliced axis must be the same as num_outputs. Input shape=(32,2400), axis=1, num_outputs=80.

Stack trace returned 10 entries:
[bt] (0) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f44b834977c]
[bt] (1) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op16SliceChannelProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x5ad) [0x7f44b902c45d]
[bt] (2) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0xff62f2) [0x7f44b8d762f2]
[bt] (3) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0x212eadc) [0x7f44b9eaeadc]
[bt] (4) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0x213007a) [0x7f44b9eb007a]
[bt] (5) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(+0x213138d) [0x7f44b9eb138d]
[bt] (6) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm11ApplyPassesENS_5GraphERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x32c) [0x7f44b9ed668c]
[bt] (7) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm9ApplyPassENS_5GraphERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c9) [0x7f44b912ff49]
[bt] (8) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4nnvm4pass10InferShapeENS_5GraphESt6vectorINS_6TShapeESaIS3_EENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1e5) [0x7f44b9133435]
[bt] (9) /home/liang/workspace/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0xdeb) [0x7f44b91290cb]
```

**Comment by tobechao** [comment]
I have encountered the same problem, may I ask you this solution?

**Comment by dreadlord1984** [comment]
me too, same problem.

**Comment by goodtogood** [comment]
same problem.

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
