### ISSUE TITLE
convert_model.py fails to convert model based on resent_50

### ISSUE THREAD

**Issue by patricianing** [apache/incubator-mxnet#6441]
protoc --version = libprotoc 3.3.0

Traceback (most recent call last):
  File "/scratch/nihao/repo/mxnet-0.9.5/tools/caffe_converter/convert_model.py", line 177, in <module>
    main()
  File "/scratch/nihao/repo/mxnet-0.9.5/tools/caffe_converter/convert_model.py", line 173, in main
    convert_model(args.prototxt, args.caffemodel, args.save_model_name)
  File "/scratch/nihao/repo/mxnet-0.9.5/tools/caffe_converter/convert_model.py", line 131, in convert_model
    rescale_factor = 1 / rescale_factor
TypeError: unsupported operand type(s) for /: 'int' and 'google.protobuf.pyext._message.RepeatedScalarContainer'

**Comment by yzou2** [comment]
The same problem here.

**Comment by yzou2** [comment]
protoc --version = libprotoc 2.6.1

**Comment by arikpoz** [comment]
I believe that this is solved now (#6489)

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
