### ISSUE TITLE
How to use kvstore with sequential module?

### ISSUE THREAD

**Issue by zazzydistsgd** [apache/incubator-mxnet#6569]
Hi,

I'm using `SequentialModule` to split layers of network (e.g. LeNet) to different modules and wiring them together. But when I tried to use `kvstore` for the wired model, I got some errors during initializing the kvstore. It seems, when the second module (second layer) are going to be initialized, the index of parameters will still start from '0', which lead to conflict with parameter indexes in the first layer (please check the error message for detailed information). Is there any solution to avoid this to make wired modules work with kvstore?

## Environment info
Operating System:
Ubuntu 14.04
Compiler:
gcc 4.8.4
Package used:
Python
MXNet version:
0.9.5, build from source
Python version and distribution:
2.7.10

## Error Message:
```
[20:58:56] /home/hwang/mxnet/dmlc-core/include/dmlc/logging.h:304: [20:58:56] src/kvstore/./kvstore_local.h:43: Check failed: local_.find(keys[i]) == local_.end() duplicate init of key 0

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f5f9a0797ac]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet7kvstore12KVStoreLocal4InitERKSt6vectorIiSaIiEERKS2_INS_7NDArrayESaIS7_EE+0x296) [0x7f5f9abadbe6]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(MXKVStoreInit+0x225) [0x7f5f9aa9efd5]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5f9cfb5adc]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f5f9cfb540c]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7f5f9d1cc5fe]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7f5f9d1cdf9e]
[bt] (7) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (8) python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (9) python(PyEval_EvalFrameEx+0x1a10) [0x525560]

Traceback (most recent call last):
  File "test_code_modified.py", line 212, in <module>
    fit(args, sym, get_mnist_iter)
  File "test_code_modified.py", line 182, in fit
    monitor            = monitor)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/module/base_module.py", line 465, in fit
    optimizer_params=optimizer_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/module/sequential_module.py", line 301, in init_optimizer
    optimizer_params=optimizer_params, force_init=force_init)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/module/module.py", line 500, in init_optimizer
    update_on_kvstore=update_on_kvstore)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/model.py", line 84, in _initialize_kvstore
    kvstore.init(idx, arg_params[param_names[idx]])
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/kvstore.py", line 100, in init
    self.handle, mx_uint(len(ckeys)), ckeys, cvals))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:58:56] src/kvstore/./kvstore_local.h:43: Check failed: local_.find(keys[i]) == local_.end() duplicate init of key 0

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f5f9a0797ac]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet7kvstore12KVStoreLocal4InitERKSt6vectorIiSaIiEERKS2_INS_7NDArrayESaIS7_EE+0x296) [0x7f5f9abadbe6]
[bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.10.0-py2.7.egg/mxnet/libmxnet.so(MXKVStoreInit+0x225) [0x7f5f9aa9efd5]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f5f9cfb5adc]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x1fc) [0x7f5f9cfb540c]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48e) [0x7f5f9d1cc5fe]
[bt] (6) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x15f9e) [0x7f5f9d1cdf9e]
[bt] (7) python(PyEval_EvalFrameEx+0x98d) [0x5244dd]
[bt] (8) python(PyEval_EvalCodeEx+0x2b1) [0x555551]
[bt] (9) python(PyEval_EvalFrameEx+0x1a10) [0x525560]
```

## Minimum reproducible example
Please check the code I used for this issue:
https://github.com/zazzydistsgd/mxnet_playground/blob/master/test_code_modified.py

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
