### ISSUE TITLE
distributed ssh launcher fails if space in script path 

### ISSUE THREAD

**Issue by undertherain** [apache/incubator-mxnet#6715]
## Environment info

MXNet 0.10.1,  installed from commit 6eb8bd16c9ef25bf039b60a32417e6fb2adb48e1
Python 3.6.1

## Error Message:
```
bash: line 0: cd: /work/alex/projects/AI: No such file or directory
bash: line 0: cd: /work/alex/projects/AI: No such file or directory
python: can't open file 'train_mnist.py': [Errno 2] No such file or directory
python: can't open file 'train_mnist.py': [Errno 2] No such file or directory
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/work/alex/opt/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/work/alex/opt/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/work/alex/src/mxnet/2017.06.12/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/work/alex/opt/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no roma7.m.gsic.titech.ac.jp -p 22 'export LD_LIBRARY_PATH=/work/alex/opt/extra/cudnn.5.1.3/lib64:/usr/local/cuda-8.0/lib64:/w
ork/alex/opt/extra/jdk1.8.0_73/lib:/work/alex/opt/extra/gcc-5.4.0/lib64:/work/alex/opt/extra/gcc-5.4.0/lib:/work/alex/opt/lib64:/work/alex/opt/lib:/usr/mpi/gcc/openmpi-1.10.5a1//lib64:/work/alex/
opt/lib/python3.6/site-packages/numpy/core/lib:/work/alex/opt/extra/cudnn.5.1.3/lib64:/usr/local/cuda-8.0/lib64:/work/alex/opt/extra/jdk1.8.0_73/lib:/work/alex/opt/extra/gcc-5.4.0/lib64:/work/ale
x/opt/extra/gcc-5.4.0/lib:/work/alex/opt/lib64:/work/alex/opt/lib:/usr/mpi/gcc/openmpi-1.10.5a1//lib64:/work/alex/opt/lib/python3.6/site-packages/numpy/core/lib:/work/alex/opt/extra/cudnn.5.1.3/l
ib64:/usr/local/cuda-8.0/lib64:/work/alex/opt/extra/jdk1.8.0_73/lib:/work/alex/opt/extra/gcc-5.4.0/lib64:/work/alex/opt/extra/gcc-5.4.0/lib:/work/alex/opt/lib64:/work/alex/opt/lib:/usr/mpi/gcc/op
enmpi-1.10.5a1//lib64:/work/alex/opt/lib/python3.6/site-packages/numpy/core/lib:; export DMLC_NUM_WORKER=2; export DMLC_NUM_SERVER=2; export DMLC_PS_ROOT_URI=131.112.28.87; export DMLC_PS_ROOT_PO
RT=9094; export DMLC_ROLE=worker; export DMLC_SERVER_ID=1; export DMLC_WORKER_ID=1; cd /work/alex/projects/AI and Machine Learning/Performance/benchmarker/_sandbox/mxnet/; python3 train_mnist.py 
--network lenet --kv-store dist_sync --gpu=0,1'' returned non-zero exit status 2.
```

## Steps to reproduce
run distributed training from directory containing spaces in its name
I had to modify launch scripts to use Python3, but don't think it makes difference. 

## What have you tried to solve it?
check if it's working with no spaces in path - it does

**Comment by undertherain** [comment]
changing line 78 of dmlc-core/tracker/dmlc_tracker/ssh.py
to
`prog = get_env(pass_envs) + ' cd ' + working_dir.replace(" ", "\ ") + '; ' + (' '.join(args.command))`
but not sure it it's the best place for this reaplace

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
