### ISSUE TITLE
how to design a new customop

### ISSUE THREAD

**Issue by bigxiuixu** [apache/incubator-mxnet#6730]
I am fresh here and encountered some problems with customop
https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/custom_softmax.py
`mlp = mx.symbol.Custom(data=fc3, name='softmax', op_type='softmax')`
I changed the name to be 'Softmax' or others, and got the following errors
```
[11:19:39] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[11:19:40] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
/Users/name/software/mxnet/example/numpy-ops/custom_softmax.py:66: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  learning_rate = 0.1, momentum = 0.9, wd = 0.00001)
[11:19:40] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [11:19:40] src/c_api/c_api_symbolic.cc:398: InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias
	[7]Softmax_label


Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010bd822b5 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x000000010c37f97f _ZN5mxnet14MatchArgumentsIN4nnvm6TShapeEEEvRKNS1_12IndexedGraphERKNSt3__113unordered_mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEET_NS6_4hashISD_EENS6_8equal_toISD_EENSB_INS6_4pairIKSD_SE_EEEEEEPNS6_6vectorISE_NSB_ISE_EEEEPKc + 3519
[bt] (2) 2   libmxnet.so                         0x000000010c37daf8 MXSymbolInferShape + 1448
[bt] (3) 3   _ctypes.so                          0x000000010b1647f7 ffi_call_unix64 + 79

Traceback (most recent call last):
  File "/Users/name/software/mxnet/example/numpy-ops/custom_softmax.py", line 69, in <module>
    batch_end_callback=mx.callback.Speedometer(100,100))
  File "/usr/local/lib/python2.7/site-packages/mxnet/model.py", line 782, in fit
    self._init_params(data.provide_data+data.provide_label)
  File "/usr/local/lib/python2.7/site-packages/mxnet/model.py", line 502, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/site-packages/mxnet/symbol.py", line 747, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mxnet/symbol.py", line 871, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:19:40] src/c_api/c_api_symbolic.cc:398: InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias
	[7]Softmax_label


Stack trace returned 4 entries:
[bt] (0) 0   libmxnet.so                         0x000000010bd822b5 _ZN4dmlc15LogMessageFatalD2Ev + 37
[bt] (1) 1   libmxnet.so                         0x000000010c37f97f _ZN5mxnet14MatchArgumentsIN4nnvm6TShapeEEEvRKNS1_12IndexedGraphERKNSt3__113unordered_mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEET_NS6_4hashISD_EENS6_8equal_toISD_EENSB_INS6_4pairIKSD_SE_EEEEEEPNS6_6vectorISE_NSB_ISE_EEEEPKc + 3519
[bt] (2) 2   libmxnet.so                         0x000000010c37daf8 MXSymbolInferShape + 1448
[bt] (3) 3   _ctypes.so                          0x000000010b1647f7 ffi_call_unix64 + 79
```
It seems that the names of operator.CustomOp and operator.CustomOpProp could be any name. But the name of symbol.Custom must be softmax. So, what should I do if I want to build a new op for my research?

**Comment by Ldpe2G** [comment]
the default label name of the iterator is 'softmax_label', you can modify the:
https://github.com/dmlc/mxnet/blob/master/example/numpy-ops/data.py to the following:
```python
    train_dataiter = mx.io.MNISTIter(
        image="data/train-images-idx3-ubyte",
        label="data/train-labels-idx1-ubyte",
        input_shape=input_shape,
        batch_size=batch_size,
        label_name="Softmax_label",
        shuffle=True,
        flat=flat)

    val_dataiter = mx.io.MNISTIter(
        image="data/t10k-images-idx3-ubyte",
        label="data/t10k-labels-idx1-ubyte",
        input_shape=input_shape,
        batch_size=batch_size,
        label_name="Softmax_label",
        flat=flat)
```
just adding the 'label_name="Softmax_label"' to iterator creation.

**Comment by bigxiuixu** [comment]
Thanks! Your suggestion can work.
And I still have some question.
1. I am confused about that I can change the name of FullyConnected like this while I can't do this with the Custom without  adding a label.
2.Why your suggestion can work?I did't find the parameter from MXNET's [document.](http://mxnet.io/api/python/io.html?highlight=mnistiter#mxnet.io.MNISTIter) 
What is the relationship between the name of my op and the  label？What should I do if I want to create more ops?
3.What is the default of req[0]?I knew the req can be 3 type . I used pycharm to find the default but got nothing. Why the req[0] is not 'null'？ It seems to be 'in place',but I can't find any assignment.

**Comment by Ldpe2G** [comment]
@piiswrong

**Comment by bigxiuixu** [comment]
@piiswrong  2333

**Comment by NodYoung** [comment]
@piiswrong

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
