### ISSUE TITLE
installation on build from source and making symbolic link to anaconda2

### ISSUE THREAD

**Issue by seongkyun** [apache/incubator-mxnet#6750]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System: Ubuntu 16.04 LTS

Compiler: nvcc (cuda 8.0, cudnn 5.1)

Package used (Python/R/Scala/Julia): python

MXNet version: latest version(current in 19 june 2017)

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): sry, i don't know what it means.

If you are using python package, please provide

Python version and distribution: anaconda2 (python 2.7)

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

`import mxnet`

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/han/anaconda2/lib/python2.7/site-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/han/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 52, in <module>
    _LIB = _load_lib()
  File "/home/han/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 44, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/han/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/han/anaconda2/bin/../lib/libgomp.so.1: version 'GOMP_4.0' not found (required by /home/han/anaconda2/lib/python2.7/site-packages/mxnet/../../lib/libmxnet.so)
`

I have to compile with my own operator files(for Deep-feature-flow)
so I tried to install mxnet with Build from Source option.
I built mxnet sources sucessfully
(While build, some Errors were occured but fixed with googling.)

finally i made an symbolic link

this folder

`/home/(myname)/mxnet/python/mxnet`

to

`/home/(myname)/anaconda2/lib/python2.7/site-packages/mxnet`

and when i try to import mxnet on python2.7(with anaconda2),

it prints out

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/han/anaconda2/lib/python2.7/site-packages/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/han/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 52, in <module>
    _LIB = _load_lib()
  File "/home/han/anaconda2/lib/python2.7/site-packages/mxnet/base.py", line 44, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/home/han/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/han/anaconda2/bin/../lib/libgomp.so.1: version 'GOMP_4.0' not found (required by /home/han/anaconda2/lib/python2.7/site-packages/mxnet/../../lib/libmxnet.so)
`

now, what should i do????

plz help me guyz!!!!

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
