### ISSUE TITLE
java.lang.NullPointerException  at ml.dmlc.mxnet.spark.MXNet.fit(MXNet.scala:108)

### ISSUE THREAD

**Issue by amanyash123** [apache/incubator-mxnet#6797]
Hi,

I am getting the error
_java.lang.NullPointerException
        at scala.collection.mutable.ArrayOps$ofRef$.length$extension(ArrayOps.scala:192)
        at scala.collection.mutable.ArrayOps$ofRef.length(ArrayOps.scala:192)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:32)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        **at ml.dmlc.mxnet.spark.MXNet.fit(MXNet.scala:108)
        at com.yash.mxnet.app.ClassificationExample$.main(ClassificationExample.scala:71)
        at com.yash.mxnet.app.ClassificationExample.main(ClassificationExample.scala)**
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)_

Code I am running is ClassificationExample.scala ( available  @ https://github.com/dmlc/mxnet/tree/master/scala-package/spark/src/main/scala/ml/dmlc/mxnet/spark/example)

        **var mxnet = new MXNet()
        .setBatchSize(128)
        .setLabelName("softmax_label")
        .setContext(devs)
        .setDimension(dimension)
        .setNetwork(network)
        .setNumEpoch(cmdLine.numEpoch)
        .setNumServer(cmdLine.numServer)
        .setNumWorker(cmdLine.numWorker)
        //.setExecutorJars(cmdLine.jars)
        .setJava(cmdLine.java)
        
     var model = mxnet.fit(trainData)**

@ mxnet.fit(trainData) I am facing Null pointer execption. I am able to set all objects received in **var mxnet** correctly.
Help me solve this issue

**Comment by tianhai123** [comment]
I've had this problem, too.Have you solved the problem?

**Comment by amanyash123** [comment]
Hi @tianhai123 ,
We were not able to solve the issue neither did anyone responded on the same
Sryy but wont be able to help in this case..!!
If you find any solution do let us know.

Thanks
Aman

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
