### ISSUE TITLE
Passing gradient between 2 networks

### ISSUE THREAD

**Issue by M4xim4l** [apache/incubator-mxnet#7224]
Hello,

I'd like to use a LSTM in combination with a CNN as a feature extractor to classify videos. I am using mxnet -cu80 0.10.0.post2 in python 2.7.9. I have a pretrained resnet-50 which is loaded and then I chop off the final classification layer:
```
    symbol, arg_params, aux_params = mx.model.load_checkpoint(model_prefix, load_epoch)
    all_layers = sym.get_internals()
    fe_sym = all_layers[last_layer + '_output']
    fe_mod = mx.mod.Module(symbol=fe_sym, data_names=('data',), label_names=None, context=cnn_dev)
    data shape = [('data', (batch_size*sequence_length, 3, 224, 224 ))]
    fe_mod.bind(for_training=True, data_shapes=data_shape)
    fe_mod.init_params(arg_params=arg_params, aux_params=aux_params, allow_missing=False)
    return fe_mod
```

The LSTM expects an input in the NTC format, thus my forward pass first puts the entire sequence through the CNN and then  reshapes the extracted features to match the LSTM. The LSTM bind looks like this (All sequences have the same length in my model so I don't use bucketing): 
```
    lstm_mod = mx.mod.Module(symbol=sym, context=lstm_dev, data_names=['data'], label_names=['softmax_label'])
    data_shape = [('data', (batch_size, sequence_length, feature_dim ))]
    label_shapes =[('softmax_label',(batch_size,))]
    lstm_mod.bind(for_training=True, data_shapes=data_shape, label_shapes=label_shapes, inputs_need_grad=True)
```
And here is the forward backward pass:

```
    #Feature extraction
    cnn_mod.forward(cnn_batch, is_train=True)
    cnn_output = cnn_mod.get_outputs()[0]

    #NTC layout
    features = mx.nd.reshape(cnn_output, shape=(batch_size,sequence_length,feature_dim))

    lstm_batch = mx.io.DataBatch([features], [labels])

    lstm_mod.forward(lstm_batch, is_train=True)
    lstm_mod.backward()
    lstm_mod.update()

    lstm_grad = lstm_mod.get_input_grads()[0]
    lstm_grad = mx.nd.reshape(lstm_grad, shape=(batch_size*sequence_length,feature_dim))

    cnn_mod.backward(lstm_grad)
    cnn_mod.update()

```

However this only works up the cnn backward pass where I get the following error which I really do not understand as the output of the CNN has exactly the same dimension as the gradient of the LSTM after reshaping and I tried to follow the dcgan example which uses a similar technique.

```
[21:46:24] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:304: [21:46:24] src/ndarray/ndarray.cc:299: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (20,) to.shape=(20,2048)

Stack trace returned 10 entries:
[bt] (0) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x19fd3c) [0x7f636ba53d3c]
[bt] (1) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe20105) [0x7f636c6d4105]
[bt] (2) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xd4c5a3) [0x7f636c6005a3]
[bt] (3) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXExecutorBackward+0x1c8) [0x7f636c59f108]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f6392eb1f60]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2f8) [0x7f6392eb19c8]
[bt] (6) /home/max/venv/venv_caffe/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x495) [0x7f63930c2055]
[bt] (7) /home/max/venv/venv_caffe/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x119b2) [0x7f63930c69b2]
[bt] (8) /home/max/venv/venv_caffe/bin/python(PyEval_EvalFrameEx+0x104b) [0x4c9e8b]
[bt] (9) /home/max/venv/venv_caffe/bin/python(PyEval_EvalCodeEx+0x3c9) [0x4c7a59]

Traceback (most recent call last):
  File "/opt/pycharm-2017.1.3/helpers/pydev/pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-2017.1.3/helpers/pydev/pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/max/hlcv_project/mxnet_network/finetuning_sequenceCombined.py", line 304, in <module>
    main()
  File "/home/max/hlcv_project/mxnet_network/finetuning_sequenceCombined.py", line 301, in main
    train_model(model, model_dir, load_subdir, load_epoch, batch_size, gpu1, gpu2, epochs, lr)
  File "/home/max/hlcv_project/mxnet_network/finetuning_sequenceCombined.py", line 182, in train_model
    feature_dim, batch_metric, epoch_metric)
  File "/home/max/hlcv_project/mxnet_network/finetuning_sequenceCombined.py", line 82, in combined_model_forward_backward
    cnn_mod.backward(grad_cpu)
  File "/home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/module/module.py", line 559, in backward
    self._exec_group.backward(out_grads=out_grads)
  File "/home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/module/executor_group.py", line 528, in backward
    exec_.backward(out_grads=out_grads_slice)
  File "/home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/executor.py", line 217, in backward
    ndarray))
  File "/home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [21:46:24] src/ndarray/ndarray.cc:299: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (20,) to.shape=(20,2048)

Stack trace returned 10 entries:
[bt] (0) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0x19fd3c) [0x7f636ba53d3c]
[bt] (1) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xe20105) [0x7f636c6d4105]
[bt] (2) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xd4c5a3) [0x7f636c6005a3]
[bt] (3) /home/max/venv/venv_caffe/local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXExecutorBackward+0x1c8) [0x7f636c59f108]
[bt] (4) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f6392eb1f60]
[bt] (5) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2f8) [0x7f6392eb19c8]
[bt] (6) /home/max/venv/venv_caffe/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x495) [0x7f63930c2055]
[bt] (7) /home/max/venv/venv_caffe/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x119b2) [0x7f63930c69b2]
[bt] (8) /home/max/venv/venv_caffe/bin/python(PyEval_EvalFrameEx+0x104b) [0x4c9e8b]
[bt] (9) /home/max/venv/venv_caffe/bin/python(PyEval_EvalCodeEx+0x3c9) [0x4c7a59]


Process finished with exit code 1

```

I should mention that 2048 is the feature dimension of the last resnet layer, the sequence lenght is fixed to 10 and batch_size (in this case the number of sequences per batch) is 2, so this explains the 20 and 2048. So lstm_grad is an NDArray of size 20x2048 and so is the cnn_output. 

Thank's for your help,
Max

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
