### ISSUE TITLE
**********!!!Error with dist-sync on two machines, Thank you

### ISSUE THREAD

**Issue by idealboy** [apache/incubator-mxnet#7396]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
centos6.4
Compiler:
gcc-4.8.5
Package used (Python/R/Scala/Julia):
python
MXNet version:
0.9.5
Or if installed from source:
Yes
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide
anaconda-python-2.7
Python version and distribution:
anaconda-python-2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1.
2.
3.

**Comment by idealboy** [comment]
When I run with dist-syn, the error occurs in one machine, the machine's operating system is centos 6.4 with gcc-4.8.5, and the python package version is python-2.7 from anaconda

I think it is because the software setup or other's machin environment, because it is fine in another machine(centos 7.2 + gcc4.8.5)

Thank you very much!

**Comment by idealboy** [comment]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/data/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/data/anaconda/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data/work/mxnetfollow-dist/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/data/anaconda/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.15.133.82 -p 22 'export LD_LIBRARY_PATH

export DMLC_SERVER_ID=1; export DMLC_WORKER_ID=0; export DMLC_PS_ROOT_URI=10.15.240.189; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9118; export DMLC_NUM_WORKER=2; export DMLC_NUM_SERVER=2; cd /tmp/mxnet; python train_mnist.py --network lenet --gpus 0,1 --kv-store dist_sync'' returned non-zero exit status 255






When training on dist-sync， the error occurs， why？ Thank you very much

**Comment by idealboy** [comment]
This is the output when "export PS_VERBOSE=2"

[00:38:29] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=10.15.240.189, port=52099, is_recovery=0 } }
[00:38:29] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=10.15.240.189, port=39902, is_recovery=0 } }
[00:38:29] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=server, ip=10.15.133.82, port=35715, is_recovery=0 } }
[00:38:29] src/van.cc:161: ? => 1. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, ip=10.15.133.82, port=37993, is_recovery=0 } }
[00:38:29] src/van.cc:235: assign rank=9 to node role=worker, ip=10.15.240.189, port=39902, is_recovery=0
[00:38:29] src/van.cc:235: assign rank=8 to node role=server, ip=10.15.240.189, port=52099, is_recovery=0
[00:38:29] src/van.cc:235: assign rank=10 to node role=server, ip=10.15.133.82, port=35715, is_recovery=0
[00:38:29] src/van.cc:235: assign rank=11 to node role=worker, ip=10.15.133.82, port=37993, is_recovery=0
[00:38:29] src/van.cc:136: ? => 9. Meta: request=0, timestamp=0, control={ cmd=ADD_NODE, node={ role=worker, id=9, ip=10.15.240.189, port=39902, is_recovery=0 role=server, id=8, ip=10.15.240.189, port=52099, is_recovery=0 role=server, id=10, ip=10.15.133.82, port=35715, is_recovery=0 role=worker, id=11, ip=10.15.133.82, port=37993, is_recovery=0 role=scheduler, id=1, ip=10.15.240.189, port=9118, is_recovery=0 } }
[00:38:29] src/van.cc:136: ? => 11. Meta: request=0, timestamp=1, control={ cmd=ADD_NODE, node={ role=worker, id=9, ip=10.15.240.189, port=39902, is_recovery=0 role=server, id=8, ip=10.15.240.189, port=52099, is_recovery=0 role=server, id=10, ip=10.15.133.82, port=35715, is_recovery=0 role=worker, id=11, ip=10.15.133.82, port=37993, is_recovery=0 role=scheduler, id=1, ip=10.15.240.189, port=9118, is_recovery=0 } }
[00:38:29] src/van.cc:136: ? => 8. Meta: request=0, timestamp=2, control={ cmd=ADD_NODE, node={ role=worker, id=9, ip=10.15.240.189, port=39902, is_recovery=0 role=server, id=8, ip=10.15.240.189, port=52099, is_recovery=0 role=server, id=10, ip=10.15.133.82, port=35715, is_recovery=0 role=worker, id=11, ip=10.15.133.82, port=37993, is_recovery=0 role=scheduler, id=1, ip=10.15.240.189, port=9118, is_recovery=0 } }
[00:38:29] src/van.cc:136: ? => 10. Meta: request=0, timestamp=3, control={ cmd=ADD_NODE, node={ role=worker, id=9, ip=10.15.240.189, port=39902, is_recovery=0 role=server, id=8, ip=10.15.240.189, port=52099, is_recovery=0 role=server, id=10, ip=10.15.133.82, port=35715, is_recovery=0 role=worker, id=11, ip=10.15.133.82, port=37993, is_recovery=0 role=scheduler, id=1, ip=10.15.240.189, port=9118, is_recovery=0 } }
[00:38:29] src/van.cc:251: the scheduler is connected to 2 workers and 2 servers
[00:38:29] src/van.cc:161: 9 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[00:38:29] src/van.cc:291: Barrier count for 7 : 1
[00:38:29] src/van.cc:161: 8 => 1. Meta: request=1, timestamp=1, control={ cmd=BARRIER, barrier_group=7 }
[00:38:29] src/van.cc:291: Barrier count for 7 : 2
[00:38:29] src/van.cc:136: [00:38:29] src/van.cc:161: 1 => 1. Meta: request=1, timestamp=4, control={ cmd=BARRIER, barrier_group=7 }
[00:38:29] src/van.cc:291: Barrier count for 7 : 3
? => 1. Meta: request=1, timestamp=4, control={ cmd=BARRIER, barrier_group=7 }


Now, it seems the program is blobked at somewhere, but I don't know how to debug this problerm

I try to run "python train_mnist.py --network lenet --gpus 0 " on 10.15.133.82 in /tmp/mxnet, IT begin to train normally

but I run "python train_mnist.py --network lenet --gpus 0" on 10.15.240.189 in /tmp/mxnet, error occurs :  src/van.cc:76: Check failed: (my_node_.port) != (-1) bind failed

**Comment by idealboy** [comment]
thr program is looping in van.cc:Start function  when mx.kvstore.create

while(!ready_){ LOG(INFO) << "wait ready"}

why ?

**Comment by szha** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to ping me to reopen if this is still an active issue. Thanks!
Also, do please check out our [forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) for general "how-to" questions.
