### ISSUE TITLE
train_mnist.py failed: TypeError: __init__() got an unexpected keyword argument 'multi_precision'

### ISSUE THREAD

**Issue by ysh329** [apache/incubator-mxnet#7424]
Release 0.10.0 is okay.   
However, Current master branch (git clone --recursive https://github.com/apache/incubator-mxnet.git) occurs this problem as below (running in the official docker, then I cloned from github.com and run this train_mnist.py) :   
```Shell
root@8acd2b8afd12:~/incubator-mxnet-origin/example/image-classification# python train_mnist.py
INFO:root:start with arguments Namespace(add_stn=False, batch_size=64, disp_batches=100, dtype='float32', gpus=None, kv_store='device', load_epoch=None, lr=0.05, lr_factor=0.1, lr_step_epochs='10', model_prefix=None, mom=0.9, monitor=0, network='mlp', num_classes=10, num_epochs=20, num_examples=60000, num_layers=None, optimizer='sgd', test_io=0, top_k=0, wd=0.0001)
Traceback (most recent call last):
  File "train_mnist.py", line 91, in <module>
    eval_end_callback = eval_end_callbacks)
  File "/root/incubator-mxnet-origin/example/image-classification/common/fit.py", line 207, in fit
    monitor            = monitor)
  File "/mxnet/python/mxnet/module/base_module.py", line 465, in fit
    optimizer_params=optimizer_params)
  File "/mxnet/python/mxnet/module/module.py", line 478, in init_optimizer
    **optimizer_params)
  File "/mxnet/python/mxnet/optimizer.py", line 128, in create_optimizer
    return Optimizer.opt_registry[name.lower()](**kwargs)
  File "/mxnet/python/mxnet/optimizer.py", line 328, in __init__
    super(SGD, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_precision'
```

**Comment by ysh329** [comment]
@ptrendx @mli @howard0su 
After I comment this line below about `multi_precision`, it's fixed. It seems a not complete feature?
```Python
    optimizer_params = {
            'learning_rate': lr,
            'momentum' : args.mom,
            'wd' : args.wd,
            'lr_scheduler': lr_scheduler,}
            #'multi_precision': True}
```

**Comment by ptrendx** [comment]
Strange, I can't reproduce that... Are you sure you compiled and "pip install -e ." the cloned version?

**Comment by ysh329** [comment]
@ptrendx So stupid I am, I forgot `make` and `pip install -e .`. It's okay on current master branch. Issue closed. :rofl:
