### ISSUE TITLE
threaded_engine error when running distributed training program

### ISSUE THREAD

**Issue by starimpact** [apache/incubator-mxnet#7837]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
```
ubuntu 14.04, 6 pcs and 42 gtx1080 cards
```
Compiler:
g++
Package used (Python/R/Scala/Julia):
python
MXNet version:
v0.8.0
Or if installed from source:
yes
MXNet commit hash (`git rev-parse HEAD`):
http://github.com/starimpact/mxnet_v0.8.0
If you are using python package, please provide
yes
Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
```
[04:22:48] /home/mingzhang/work/dmlc/mxnet_v0.8.0/dmlc-core/include/dmlc/logging.h:235: [04:22:48] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
[04:22:48] /home/mingzhang/work/dmlc/mxnet_v0.8.0/dmlc-core/include/dmlc/logging.h:235: [04:22:48] src/engine/./threaded_engine.h:306: [04:22:48] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [04:22:48] src/engine/./threaded_engine.h:306: [04:22:48] src/engine/threaded_engine.cc:87: Check failed: (num_pending_reads_) > (0) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.

```

I have no idea how to fix it, give me some idea.

**Comment by szha** [comment]
@piiswrong suggested a try on this https://github.com/apache/incubator-mxnet/pull/6084

**Comment by starimpact** [comment]
@szha i will have a try, thank you very much!

**Comment by starimpact** [comment]
got another error:
```
[20:49:12] /home/mingzhang/work/dmlc/mxnet_v0.8.0/dmlc-core/include/dmlc/logging.h:235: [20:49:12] src/operator/./cudnn_softmax_activation-inl.h:91: Check failed: (cudnnSoftmaxForward(s->dnn_handle_, CUDNN_SOFTMAX_ACCURATE, softmax_mode, &alpha, shape_desc_, data.dptr_, &beta, shape_desc_, out.dptr_)) == (CUDNN_STATUS_SUCCESS) 
[20:49:12] /home/mingzhang/work/dmlc/mxnet_v0.8.0/dmlc-core/include/dmlc/logging.h:235: [20:49:12] src/engine/./threaded_engine.h:306: [20:49:12] src/operator/./cudnn_softmax_activation-inl.h:91: Check failed: (cudnnSoftmaxForward(s->dnn_handle_, CUDNN_SOFTMAX_ACCURATE, softmax_mode, &alpha, shape_desc_, data.dptr_, &beta, shape_desc_, out.dptr_)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [20:49:12] src/engine/./threaded_engine.h:306: [20:49:12] src/operator/./cudnn_softmax_activation-inl.h:91: Check failed: (cudnnSoftmaxForward(s->dnn_handle_, CUDNN_SOFTMAX_ACCURATE, softmax_mode, &alpha, shape_desc_, data.dptr_, &beta, shape_desc_, out.dptr_)) == (CUDNN_STATUS_SUCCESS) 
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
bash: line 1: 41816 Aborted                 python Train_Dist_Batch_Plate.py
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mingzhang/work/reid/face_reid/distribution/./dmlc-core/tracker/dmlc_tracker/ssh.py", line 63, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.1.3.105 -p 22 'export MXNET_ENABLE_GPU_P2P=0; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9093; export DMLC_PS_ROOT_URI=192.168.3.104; export DMLC_NUM_SERVER=36; export DMLC_NUM_WORKER=6;export DMLC_INTERFACE=p15p1; cd /tmp/mxnet_face2; python Train_Dist_Batch_Plate.py'' returned non-zero exit status 134

```

**Comment by szha** [comment]
The call to cudnn on a worker failed. You need to check whether that worker can run cudnn-supported softmax on the single machine.

**Comment by starimpact** [comment]
yes, the cudnn should be supported in that machine, because the error happened after a few hours of training start.

**Comment by starimpact** [comment]
seems that the crash probability is much lower now.

**Comment by szha** [comment]
Feel free to reopen if the issue persists.
