### ISSUE TITLE
SSD Training failing with different number of classes

### ISSUE THREAD

**Issue by Prasad9** [apache/incubator-mxnet#8069]
OS: Ubuntu 16.04
MXNet version: 0.11.0
Python: 3.5.2

I am trying to train SSD with different number of classes (not 20) but it is failing to train. However, if I change the number of classes to 20 for the same set of data input, it works. I have tried setting number of classes from 10 to 21. Let me know if any more details are required.
```

$ python train.py --pretrained=/my/path/incubator-mxnet/example/ssd/model/ssd_300 --num-class=10 --class-names='Zero, One, Two, Three, Four, Five, Six, Seven, Eight, Nine' --use-difficult=True --epoch=0
[20:38:39] src/io/iter_image_det_recordio.cc:280: ImageDetRecordIOParser: /my/path/incubator-mxnet/example/ssd/data/train.rec, use 7 threads for decoding..
[20:38:46] src/io/iter_image_det_recordio.cc:333: ImageDetRecordIOParser: /my/path/incubator-mxnet/example/ssd/data/train.rec, label padding width: 350
[20:38:48] src/io/iter_image_det_recordio.cc:280: ImageDetRecordIOParser: /my/path/incubator-mxnet/example/ssd/data/val.rec, use 7 threads for decoding..
[20:38:49] src/io/iter_image_det_recordio.cc:333: ImageDetRecordIOParser: /my/path/incubator-mxnet/example/ssd/data/val.rec, label padding width: 350
INFO:root:Start training with (gpu(0)) from pretrained model /my/path/incubator-mxnet/example/ssd/model/ssd_300
[20:38:52] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.9.5. Attempting to upgrade...
[20:38:52] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
INFO:root:Freezed parameters: [conv1_1_weight,conv1_1_bias,conv1_2_weight,conv1_2_bias,conv2_1_weight,conv2_1_bias,conv2_2_weight,conv2_2_bias]
[20:38:58] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUN
E_DEFAULT to 0 to disable)
[20:39:03] src/operator/convolution.cu:119: This convolution is not supported by cudnn, MXNET convolution is applied.
[20:39:03] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [20:39:03] src/ndarray/ndarray.cc:348: Check failed: from.shape() == to->shape() operan
ds shape mismatchfrom.shape = (126,1024,3,3) to.shape=(66,1024,3,3)



Stack trace returned 10 entries:
[bt] (0) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff65b64b7cc]
[bt] (1) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0xf408c2) [0x7ff65c3b68c2]
[bt] (2) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0xfa1737) [0x7ff65c417737]
[bt] (3) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0xdf2a95) [0x7ff65c268a95]
[bt] (4) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(MXImperativeInvoke+0x254) [0x7ff65c2697a4]
[bt] (5) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7ff680f048cc]
[bt] (6) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x165) [0x7ff680f03a15]
[bt] (7) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x283) [0x7ff680efbe43]
[bt] (8) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(+0x96af) [0x7ff680ef36af]
[bt] (9) /my/path/bin/../lib/libpython3.5m.so.1.0(PyObject_Call+0x6a) [0x7ff6828c3eca]



Traceback (most recent call last):
  File "train.py", line 151, in <module>
    voc07_metric=args.use_voc07_metric)
  File "/my/path/incubator-mxnet/example/ssd/train/train_net.py", line 275, in train_net
    monitor=monitor)
  File "/my/path/lib/python3.5/site-packages/mxnet/module/base_module.py", line 464, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "/my/path/lib/python3.5/site-packages/mxnet/module/module.py", line 296, in init_params
    _impl(desc, arr, arg_params)
  File "/my/path/lib/python3.5/site-packages/mxnet/module/module.py", line 284, in _impl
    cache_arr.copyto(arr)
  File "/my/path/lib/python3.5/site-packages/mxnet/ndarray.py", line 989, in copyto
    return _internal._copyto(self, out=other)
  File "<string>", line 10, in _copyto
  File "/my/path/lib/python3.5/site-packages/mxnet/_ctypes/ndarray.py", line 89, in _imperative_invoke
    c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
  File "/my/path/lib/python3.5/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:39:03] src/ndarray/ndarray.cc:348: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (126,1024,3,3) to.shape=(66,1024,3,3)



Stack trace returned 10 entries:
[bt] (0) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x1d57cc) [0x7ff65b64b7cc]
[bt] (1) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0xf408c2) [0x7ff65c3b68c2]
[bt] (2) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0xfa1737) [0x7ff65c417737]
[bt] (3) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(+0xdf2a95) [0x7ff65c268a95]
[bt] (4) /my/path/lib/python3.5/site-packages/mxnet/libmxnet.so(MXImperativeInvoke+0x254) [0x7ff65c2697a4]
[bt] (5) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7ff680f048cc]
[bt] (6) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x165) [0x7ff680f03a15]
[bt] (7) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x283) [0x7ff680efbe43]
[bt] (8) /my/path/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(+0x96af) [0x7ff680ef36af]
[bt] (9) /my/path/bin/../lib/libpython3.5m.so.1.0(PyObject_Call+0x6a) [0x7ff6828c3eca]
```

**Comment by zhreshold** [comment]
train.py --num-class 10 --class-names '1,2,3...'

**Comment by Prasad9** [comment]
I would like to close this issue as my problem has been explained in this [thread](https://github.com/zhreshold/mxnet-ssd/issues/124).
