### ISSUE TITLE
[scala] Module api: label (1,1,868,868) and prediction (1,868,868)should have the same length

### ISSUE THREAD

**Issue by benqua** [apache/incubator-mxnet#8129]
It seems that the batch size dimension is lost at prediction time.

## Environment info
Operating System:
Linux
Compiler:

Package used (Python/R/Scala/Julia):
Scala
MXNet version:
0.11
Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide

Python version and distribution:

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
I get this error message:
`label (1,1,868,868) and prediction (1,868,868)should have the same length.`
when calling fit() on a module.

It seems the prediction shape is missing the batch size dimension.

How can I set the batch size dimension for the predictions?

```
[error] (run-main-2) java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
	at scala.Predef$.require(Predef.scala:224)
	at ml.dmlc.mxnet.Accuracy$$anonfun$update$4.apply(EvalMetric.scala:111)
	at ml.dmlc.mxnet.Accuracy$$anonfun$update$4.apply(EvalMetric.scala:109)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.mxnet.Accuracy.update(EvalMetric.scala:109)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$updateMetric$2.apply(DataParallelExecutorGroup.scala:602)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$updateMetric$2.apply(DataParallelExecutorGroup.scala:588)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup.updateMetric(DataParallelExecutorGroup.scala:588)
	at ml.dmlc.mxnet.module.Module.updateMetric(Module.scala:530)
	at ml.dmlc.mxnet.module.BaseModule$$anonfun$fit$1.apply$mcVI$sp(BaseModule.scala:411)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at ml.dmlc.mxnet.module.BaseModule.fit(BaseModule.scala:400)
	at TrainModuleUNet$.main(TrainModuleUnet.scala:39)
	at TrainModuleUNet.main(TrainModuleUnet.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```
## code
```scala
  def main(args: Array[String]): Unit = {
    val logger = Logger("TrainModuleUNet")

    val imgPath = Options.imgPath
    val maskPath = Options.maskPath
    val input = Symbol.Variable("data")
    val symbol = UNet.unet(input)
    val numEpoch = 10
    val init = new Xavier()
    val optimizer = new SGD(
      learningRate = 0.001f,
      momentum     = 0.99f
    )
    val batchSize = 1

    // get iterators
    val (trainIter, testIter) = FileImgIters.getIterators(imgPath, maskPath)

    // construct the module
    val mod = new Module(symbol)
    val providedData = trainIter.provideData
    val providedLabel = trainIter.provideLabel
    logger.info("providedData" + providedData.mkString)
    logger.info("provi3dedLabel" + providedLabel.mkString)
    mod.bind(dataShapes  = trainIter.provideData, labelShapes = Some(trainIter.provideLabel))
    logger.info("bound!")
    mod.initParams(init)
    logger.info("initialized!")
    mod.fit(trainIter,
      evalData = scala.Option(testIter),
      numEpoch = numEpoch,
      fitParams = new FitParams().setOptimizer(optimizer))
}
```

**Comment by benqua** [comment]
If that helps, the last layer of my network is:
```scala
val out    = Symbol.SoftmaxOutput()()(Map("data" -> conv10, "label" -> label, "multi_output" -> true))
```
@javelinjs , @Ldpe2G , any idea?

**Comment by Ldpe2G** [comment]
@benqua It seems like the error occurs when calling the `update` method  of the Accuracy mertic. May be you should first check the output shape of your network by calling the inferShape method of the symbol.

**Comment by benqua** [comment]
@Ldpe2G all right, I am going to check that (pretty sure it was (1,1,868,868), but I will cross-check once I arrive home).

**Comment by benqua** [comment]
ok, I checked and log the shapes as suggested and realize that it is not the batch size dimension that is lost but the channel one (I had 1 for both, so I didn't realize at first).

The network is a u-net very similar as the one describe in the original u-net paper.
Each pixel can be in one of two classes, as in the original paper.
So, the last layers are:
```scala
    // output
    val conv10 = Symbol.Convolution()()(Map("data" -> conv9, "num_filter" -> 2, "kernel" -> "(1,1)"))
    val label  = Symbol.Variable("softmax_label")
    val so     = Symbol.SoftmaxOutput()()(Map("data" -> conv10, "label" -> label, "multi_output" -> true))
```
Now, when I run the code to train the network (posted above) with more logging, I get the following:
```
2017-10-03 23:40:37,808 [run-main-0] [UNet] [INFO] - so - Shape: Vector((1,2,868,868))
2017-10-03 23:40:37,897 [run-main-0] [TrainModuleUNet] [INFO] - symbol shape: Vector((1,2,868,868))
2017-10-03 23:40:37,899 [run-main-0] [TrainModuleUNet] [INFO] - providedData: data -> (1,1,1052,1052)
2017-10-03 23:40:37,900 [run-main-0] [TrainModuleUNet] [INFO] - providedLabel: softmax_label -> (1,1,868,868)
2017-10-03 23:40:38,038 [run-main-0] [TrainModuleUNet] [INFO] - bound!
2017-10-03 23:40:38,088 [run-main-0] [TrainModuleUNet] [INFO] - initialized!
2017-10-03 23:40:38,089 [run-main-0] [ml.dmlc.mxnet.module.Module] [WARN] - Already binded, ignoring bind()
MKL Build:20170720
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
	at scala.Predef$.require(Predef.scala:224)
	at ml.dmlc.mxnet.Accuracy$$anonfun$update$4.apply(EvalMetric.scala:111)
(...)
```
The output of my network has a shape of (1, 2, 868, 868). However, the error message said that prediction shape is (1, 868, 868). How can this be?

I also see that my label is likely not in the right shape (one channel, with either 0 or 1 instead of two channels with the probability of 0 and 1). However, the bind function seems ok, which makes me think that there is possibly a implicit conversion done somewhere.

Another very strange thing is that the program doesn't really stop after this exception. Memory and CPU usage continue to grow up until I kill sbt. Despite the filed require, the C++ backend continues to work...

Any hint about how to correctly use SoftmaxOutput with muli_output would be greatly appreciate. :)

**Comment by Ldpe2G** [comment]
@benqua  are you conducting the segmentation task? If so, the shape of label  has only one channel, just like the normal softmax. The multi_output parameter means to calculate the softmax along the channel axis . 

And I suggest you first print the output shapes by calling the `outputShapes` method of Module just after you call the `bing` method.

**Comment by benqua** [comment]
Yes, I am conducting a segmentation tasks.
My label has only one channel, with value being either 1 or 0, depending on the class (providedLabel: softmax_label -> (1,1,868,868)).

The output of outputShapes on the module is 
OutShapes (module): ArrayBuffer((softmaxoutput0_output,(1,2,868,868)))

You mean I shouldn't use the multi_output parameter?

**Comment by Ldpe2G** [comment]
No you should. And I suggest you to try the intermediate api 
https://github.com/apache/incubator-mxnet/blob/8a4221bca2ddd4fa05840f7951a7216775021237/scala-package/examples/src/main/scala/ml/dmlc/mxnetexamples/module/MnistMlp.scala#L43 

Since the output shape is correct, it is strange to get such error message.

**Comment by benqua** [comment]
Right, I also find this error message very strange after looking closely at the issue. All the shapes of the module look fine and I see no reason for this unexpected shape returned by the predict function.

I will take the opportunity to have a look at the intermediate api and report back here (but not in the next 12 hours).
I should logically get the exact same error when calling mod.updateMetric, but let's see.
Thanks for your guidance in debbuging this tricky issue.

**Comment by benqua** [comment]
I changed to the intermediate api
```scala
    val logger = Logger("TrainModuleUNet")

    val imgPath = Options.imgPath
    val maskPath = Options.maskPath
    val input = Symbol.Variable("data")
    val symbol = UNet.unet(input)
    val numEpoch = 10
    val init = new Xavier()
    val optimizer = new SGD(
      learningRate = 0.001f,
      momentum     = 0.99f
    )
    val metric = new Accuracy()
    val batchSize = 1

    // get iterators
    val (trainIter, testIter) = FileImgIters.getIterators(imgPath, maskPath, Options.batchSize)

    // construct the module
    val mod = new Module(symbol)
    val (_, shape, _) =
      symbol.inferShape(Map("data" -> Shape(Options.batchSize, Options.inputNC, Options.inputSize, Options.inputSize)))
    logger.info(s"symbol shape: $shape")
    val providedData = trainIter.provideData
    val providedLabel = trainIter.provideLabel
    logger.info("providedData: " + providedData.mkString)
    logger.info("providedLabel: " + providedLabel.mkString)
    mod.bind(dataShapes  = trainIter.provideData, labelShapes = Some(trainIter.provideLabel))
    logger.info("bound")
    mod.initParams(init)
    logger.info("initialized")
    mod.initOptimizer(optimizer = optimizer)
    logger.info("optimizer initialized")
    val outShapes = mod.outputShapes
    logger.info(s"OutShapes (module): $outShapes")

    for (epoch <- 0 until numEpoch) {
      while (trainIter.hasNext) {
        val batch = trainIter.next()
        mod.forward(batch)
        mod.updateMetric(metric, batch.label)
        mod.backward()
        mod.update()
      }
    }
```
and got the same result:
```
2017-10-04 20:57:21,830 [run-main-0] [UNet] [INFO] - so - Shape: Vector((1,2,868,868))
2017-10-04 20:57:21,928 [run-main-0] [TrainModuleUNet] [INFO] - symbol shape: Vector((1,2,868,868))
2017-10-04 20:57:21,931 [run-main-0] [TrainModuleUNet] [INFO] - providedData: data -> (1,1,1052,1052)
2017-10-04 20:57:21,931 [run-main-0] [TrainModuleUNet] [INFO] - providedLabel: softmax_label -> (1,1,868,868)
2017-10-04 20:57:22,028 [run-main-0] [TrainModuleUNet] [INFO] - bound
2017-10-04 20:57:22,103 [run-main-0] [TrainModuleUNet] [INFO] - initialized
2017-10-04 20:57:22,123 [run-main-0] [TrainModuleUNet] [INFO] - optimizer initialized
2017-10-04 20:57:22,142 [run-main-0] [TrainModuleUNet] [INFO] - OutShapes (module): ArrayBuffer((softmaxoutput0_output,(1,2,868,868)))
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
MKL Build:20170720
java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
	at scala.Predef$.require(Predef.scala:224)
	at ml.dmlc.mxnet.Accuracy$$anonfun$update$4.apply(EvalMetric.scala:111)
	at ml.dmlc.mxnet.Accuracy$$anonfun$update$4.apply(EvalMetric.scala:109)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.mxnet.Accuracy.update(EvalMetric.scala:109)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$updateMetric$2.apply(DataParallelExecutorGroup.scala:602)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$updateMetric$2.apply(DataParallelExecutorGroup.scala:588)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup.updateMetric(DataParallelExecutorGroup.scala:588)
	at ml.dmlc.mxnet.module.Module.updateMetric(Module.scala:530)
	at TrainModuleUNet$$anonfun$main$1.apply$mcVI$sp(TrainModuleUnet.scala:52)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at TrainModuleUNet$.main(TrainModuleUnet.scala:48)
	at TrainModuleUNet.main(TrainModuleUnet.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```
If I change the metric to RMSE, I get almost the same error, without the requirement message:
```
[error] (run-main-0) java.lang.IllegalArgumentException: requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at ml.dmlc.mxnet.RMSE$$anonfun$update$24.apply(EvalMetric.scala:300)
	at ml.dmlc.mxnet.RMSE$$anonfun$update$24.apply(EvalMetric.scala:297)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.mxnet.RMSE.update(EvalMetric.scala:297)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$updateMetric$2.apply(DataParallelExecutorGroup.scala:602)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$updateMetric$2.apply(DataParallelExecutorGroup.scala:588)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:733)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:732)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup.updateMetric(DataParallelExecutorGroup.scala:588)
	at ml.dmlc.mxnet.module.Module.updateMetric(Module.scala:530)
	at TrainModuleUNet$$anonfun$main$1.apply$mcVI$sp(TrainModuleUnet.scala:52)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at TrainModuleUNet$.main(TrainModuleUnet.scala:48)
	at TrainModuleUNet.main(TrainModuleUnet.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

**Comment by Ldpe2G** [comment]
try call the `getOutputsMerged` method after `forward` and see whether the shape of output NDArray is
`(1,2,868,868)`

**Comment by benqua** [comment]
Yes, I is.
```scala
        mod.forward(batch)
        val m = mod.getOutputsMerged
        logger.info(s"shape after forward: ${m(0).shape}")
```
gives
```
[TrainModuleUNet] [INFO] - shape after forward: (1,2,868,868)
[error] (run-main-1) java.lang.IllegalArgumentException: requirement failed: label (1,1,868,868) and prediction (1,868,868)should have the same length.
```
Weird.

**Comment by Ldpe2G** [comment]
ok, then you can then change ` mod.updateMetric(metric, batch.label)` to `metric(batch.label, mod.getOutputsMerged)`

**Comment by Ldpe2G** [comment]
I need to check the code of Module to see what's going on. But you can first use the intermediate api.

**Comment by Ldpe2G** [comment]
@javelinjs

**Comment by benqua** [comment]
Ok, will try with metric instead of updateMetric.

I did a self contained example to reproduce the issue:
```scala
import ml.dmlc.mxnet._
import ml.dmlc.mxnet.optimizer.SGD
import ml.dmlc.mxnet.module._
import com.typesafe.scalalogging.Logger
import scala.collection.immutable.ListMap


object BugShape {
  def main(args: Array[String]): Unit = {
    val logger = Logger("TrainModuleUNet")

    def outShape(s: Symbol, inShape: Shape): Shape = {
      val  (_, shape, _) = s.inferShape(Map("data" -> inShape))
      shape(0)
    }

    val batchSize  = 2
    val dataShape  = Shape(batchSize, 1, 1052, 1052)
    val labelShape = Shape(batchSize, 1, 868, 868)

    val dataNDA  = NDArray.ones(dataShape, Context.cpu())
    val labelNDA = NDArray.ones(labelShape, Context.cpu())
    val batch    = new DataBatch(IndexedSeq(dataNDA), IndexedSeq(labelNDA), (0l to batchSize.toLong).toIndexedSeq, 0)

    val sliceDiff  = (1052 - 868) / 2
    val sliceBegin = Shape(0, 0, sliceDiff, sliceDiff)
    val sliceEnd   = Shape(batchSize, 2, 1052 - sliceDiff, 1052 - sliceDiff)

    val input   = Symbol.Variable("data")
    val label   = Symbol.Variable("softmax_label")
    val conv    = Symbol.Convolution()()(Map("data" -> input, "num_filter" -> 2, "kernel" -> "(1,1)"))
    val sliced  = Symbol.slice()()(Map("data" -> conv, "begin" -> sliceBegin, "end" -> sliceEnd))
    val so      = Symbol.SoftmaxOutput()()(Map("data" -> sliced, "label" -> label, "multi_output" -> true))

    logger.info(s"data shape $dataShape, label shape $labelShape")
    logger.info("sliced shape: " + outShape(sliced, dataShape))
    logger.info("so shape: " + outShape(so, dataShape))

    val mod = new Module(so)
    mod.bind(dataShapes = ListMap("data" -> dataShape), labelShapes = Some(ListMap("softmax_label" -> labelShape)))
    logger.info(s"mod output shape: ${mod.outputShapes}")
    mod.initParams(new Xavier())
    mod.initOptimizer(optimizer = new SGD())
    mod.forward(batch)
    val outputMerged = mod.getOutputsMerged
    logger.info(s"mod output merged: ${outputMerged(0).shape}")
    mod.updateMetric(new Accuracy(), batch.label)   // fails here
    logger.info(s"updateMetric done")
  }
}
```
(or as a gist: https://gist.github.com/benqua/a60169693561d6939c3c00964953ae7e )

**Comment by benqua** [comment]
FYI 
`metric.update(batch.label, mod.getOutputsMerged)`
throws the exact same error.

**Comment by Ldpe2G** [comment]
thanks. I will take a look.

**Comment by Ldpe2G** [comment]
@benqua I know what cause this error. You can think of it as a bug of the Accuracy metric:
https://github.com/apache/incubator-mxnet/blob/759f5091eb5feae68ffc5914d6cf8798dd2af6d7/scala-package/core/src/main/scala/ml/dmlc/mxnet/EvalMetric.scala#L110

The `argmax_channel ` will automatically reduce the dimentation if it is one. One way to solve that is to write your own Accuracy metric then simply change the line 
`val predLabel = NDArray.argmax_channel(pred) ` 
to
`val predLabel = NDArray.argmax(Map("axis" -> 1， "keepdims" -> true))(pred) `

**Comment by benqua** [comment]
ok, will check once home.

I had the same issue with RMSE if I remember well.

Shouldn't we correct the Accuracy in mxnet-scala if it is a bug?

**Comment by Ldpe2G** [comment]
I will make a pr later. I think you shouldn't use RMSE becuase your label should have the same shape with the output.

**Comment by benqua** [comment]
Yhea, you're right. Almost same error message with RMSE, but this time it is legit.

**Comment by benqua** [comment]
FYI works perfectly with your suggestion.
Thanks for your help @Ldpe2G .

I keep the issue open, because the identified bug in mxnet is not solved.

**Comment by benqua** [comment]
@Ldpe2G I did a first PR to fix this before #8226, but it seems stuck in the automated build process.
