### ISSUE TITLE
when import, error: libmxnet.so: undefined symbol: _gfortran_concat_string

### ISSUE THREAD

**Issue by fye881** [apache/incubator-mxnet#8169]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:
Ubuntu 16.04
Compiler:
g++ (5.4)
Package used (Python/R/Scala/Julia):
Python
MXNet version:

Or if installed from source:
just synced and build, only difference is in make/config.mk, changed to: USE_BLAS = openblas
MXNet commit hash (`git rev-parse HEAD`):

If you are using python package, please provide
python2.7
   sudo apt-get install --reinstall libopenblas-dev
   sudo apt-get install --reinstall python-numpy
   sudo apt-get install --reinstall libopenblas-base

Python version and distribution:
2.7
If you are using R package, please provide

R `sessionInfo()`:

## Error Message:
Please paste the full error message, including stack trace.
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/local/ANT/fengy/mxnet.ubuntu/mxnet/python/mxnet/__init__.py", line 25, in <module>
    from .base import MXNetError
  File "/home/local/ANT/fengy/mxnet.ubuntu/mxnet/python/mxnet/base.py", line 110, in <module>
    _LIB = _load_lib()
  File "/home/local/ANT/fengy/mxnet.ubuntu/mxnet/python/mxnet/base.py", line 102, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/local/ANT/fengy/mxnet.ubuntu/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: _gfortran_concat_string
>>> exit()

## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

1.
2.
3.

## What have you tried to solve it?

1. If I set USE_LAPACK=0 in config.mk I can import
2. Checked liblapack:
locate liblapack.so output:
/etc/alternatives/liblapack.so
/etc/alternatives/liblapack.so.3
/etc/alternatives/liblapack.so.3gf
/usr/lib/liblapack.so
/usr/lib/liblapack.so.3
/usr/lib/liblapack.so.3gf
/usr/lib/lapack/liblapack.so
/usr/lib/lapack/liblapack.so.3
/usr/lib/lapack/liblapack.so.3.6.0
/usr/lib/openblas-base/liblapack.so
/usr/lib/openblas-base/liblapack.so.3
/var/lib/dpkg/alternatives/liblapack.so
/var/lib/dpkg/alternatives/liblapack.so.3

tried to change this without success:
LD_LIBRARY_PATH=/usr/lib/openblas-base:~/mxnet.ubuntu/mxnet/lib
(tried to add /usr/lib/lapack)
3.

**Comment by fye881** [comment]
ok seems can be resolved by:
sudo apt-get install --reinstall gfortran
export LD_LIBRARY_PATH=usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
