### ISSUE TITLE
AttributeError using gluon HybridBlock 

### ISSUE THREAD

**Issue by tornadomeet** [apache/incubator-mxnet#8217]
```python
import mxnet as mx
from mxnet import gluon
from mxnet.gluon import nn

class TestNet(gluon.HybridBlock):
    def __init__(self, **kwargs):
        super(TestNet, self).__init__(**kwargs)
        with self.name_scope:
            self.fc = nn.Dense(128)

    def hybrid_block(self, F, x):
        return self.fc(x)

net = TestNet()
```

error log:
```shell
Traceback (most recent call last):
  File "test_hybridblock.py", line 14, in <module>
    net = TestNet()
  File "test_hybridblock.py", line 8, in __init__
    with self.name_scope:
AttributeError: __exit__
```
same error whith this tutorial: https://mxnet.incubator.apache.org/tutorials/gluon/hybrid.html#hybridblock  

git rev-parse HEAD  
```7232b1292221adf3ed19169540f8813dcd63bb71```

**Comment by ZiyueHuang** [comment]
Seems that you forgot the bracket, 
```
with self.name_scope():
```
