### ISSUE TITLE
Gluon mnist loader not working

### ISSUE THREAD

**Issue by lutzroeder** [apache/incubator-mxnet#8272]
## Description
Trying to run a simple MNIST sample but failing with an error. See steps below.

## Environment info (Required)
```
----------Python Info----------
('Version      :', '2.7.10')
('Compiler     :', 'GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)')
('Build        :', ('default', 'Jul 15 2017 17:16:57'))
('Arch         :', ('64bit', ''))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/Library/Python/2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '0.11.0')
('Directory    :', '/Library/Python/2.7/site-packages/mxnet')
('Commit Hash   :', '53274b4a2b0d73f3fbdb10cfb5f9ed0c8263fda7')
----------System Info----------
('Platform     :', 'Darwin-17.0.0-x86_64-i386-64bit')
('system       :', 'Darwin')
('node         :', 'Lutzs-MacBook.local')
('release      :', '17.0.0')
('version      :', 'Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64')
----------Hardware Info----------
('machine      :', 'x86_64')
('processor    :', 'i386')
machdep.cpu.brand_string: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX SMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C
machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 HLE AVX2 BMI2 INVPCID RTM SMAP RDSEED ADX IPT SGX FPU_CSDS MPX CLFSOPT
machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0082 sec, LOAD: 0.6771 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0325 sec, LOAD: 0.2308 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0123 sec, LOAD: 0.1061 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0119 sec, LOAD: 0.0667 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0635 sec, LOAD: 0.0429 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0976 sec, LOAD: 0.2623 sec.
```

## Error Message:
```
~/Projects/gluon: ./mnist.py 
Downloading /Users/lutzroeder/.mxnet/datasets/train-images-idx3-ubyte.gz from http://data.mxnet.io/data/mnist/train-images-idx3-ubyte.gz...
Traceback (most recent call last):
  File "./mnist.py", line 7, in <module>
    train_data = gluon.data.DataLoader(gluon.data.vision.MNIST(train=True, transform=lambda data, label: (data.astype(np.float32)/255, label)), batch_size=32, shuffle=True)
  File "/Library/Python/2.7/site-packages/mxnet/gluon/data/vision.py", line 75, in __init__
    super(MNIST, self).__init__(root, train, transform)
  File "/Library/Python/2.7/site-packages/mxnet/gluon/data/vision.py", line 43, in __init__
    self._get_data()
  File "/Library/Python/2.7/site-packages/mxnet/gluon/data/vision.py", line 83, in _get_data
    sha1_hash='6c95f4b05d2bf285e1bfb0e7960c31bd3b3f8a7d')
  File "/Library/Python/2.7/site-packages/mxnet/gluon/utils.py", line 200, in download
    r = requests.get(url, stream=True)
AttributeError: type object 'requests_failed_to_import' has no attribute 'get'
```

## Minimum reproducible example

```
#!/usr/bin/python

import numpy as np
import mxnet as mx
from mxnet import gluon, autograd, ndarray

train_data = gluon.data.DataLoader(gluon.data.vision.MNIST(train=True, transform=lambda data, label: (data.astype(np.float32)/255, label)), batch_size=32, shuffle=True)
test_data = gluon.data.DataLoader(gluon.data.vision.MNIST(train=False, transform=lambda data, label: (data.astype(np.float32)/255, label)), batch_size=32, shuffle=False)

net = gluon.nn.Sequential()
```

## Steps to reproduce
1. `sudo -H pip install mxnet`
2. Add example above to `./mnist.py` 
3. `python ./mnist.py`

**Comment by zhreshold** [comment]
The 0.11.0 version pip wheel didn't include request as dependency, we have fixed it in the recent nightly builds.
You have two options

- Install request manually: `sudo -H pip install request`
- Install the latest build by `sudo -H pip install -U mxnet --pre`

**Comment by xiongyifan** [comment]
@zhreshold Thanks for your answer. It solve my problem.
It should be `pip install requests`, not `request`
