### ISSUE TITLE
v0.12 autograd regression

### ISSUE THREAD

**Issue by leezu** [apache/incubator-mxnet#8280]
I'm getting some

`mxnet.base.MXNetError: [14:13:02] src/imperative/./imperative_utils.h:601: Check failed: num_unknown == 0 (18446744073709551615 vs. 0) Unabled to decied context for nodes`

errors when using a hybridized encoder decoder architecture and calling `.backward` on the loss:

```
    with autograd.record():
        _, hidden = encoder(data, begin_state)
        prediction, _ = decoder(data, hidden)
        ae_l = ae_loss(prediction, expected_label)

    ae_l.backward()
```

this works fine on v0.11.
encoder and decoder are (manually) unrolled RNN cells + embeddings + projection. In case its not obvious what is causing the error I can try to build a simple example that triggers the error. Please let me know.

**Comment by leezu** [comment]
#8286 fixes the issue for me. Thanks.

**Comment by leezu** [comment]
@piiswrong Reopening as there are still some remaining issues when training on CPU. GPU works fine now.

`mxnet.base.MXNetError: [12:43:36] src/imperative/./imperative_utils.h:596: Check failed: vctx[i].dev_type != -1 (-1 vs. -1) Cannot decide context for node zeros`

**Comment by leezu** [comment]
@piiswrong this regression is still not fixed on CPU. I'm attaching a code example that triggers the regression:

```
import mxnet as mx
from mxnet import gluon, autograd

vocab_size = 10
num_embed = 100
num_hidden = 1024
layout = "TNC"


class Encoder(gluon.Block):
    def __init__(self):
        super().__init__()
        with self.name_scope():
            self.embedding = mx.gluon.nn.Embedding(vocab_size, num_embed)
            self.rnn = mx.gluon.rnn.GRU(hidden_size=num_hidden, layout=layout)

    def forward(self, inputs, hidden):
        emb = self.embedding(inputs)
        output, hidden = self.rnn(emb, hidden)
        return output, hidden


class Decoder(gluon.Block):
    def __init__(self):
        super().__init__()
        with self.name_scope():
            self.embedding = mx.gluon.nn.Embedding(vocab_size, num_embed)
            self.rnn = mx.gluon.rnn.GRU(hidden_size=num_hidden, layout=layout)
            self.projection = mx.gluon.nn.Dense(units=vocab_size)

    def forward(self, inputs, hidden):
        emb = self.embedding(inputs)
        output, hidden = self.rnn(emb, hidden)
        projection = self.projection(output.reshape((-1, num_hidden)))
        projection = projection.reshape((-1, inputs.shape[1], vocab_size))
        return projection, hidden


encoder = Encoder()
decoder = Decoder()
loss = gluon.loss.SoftmaxCrossEntropyLoss(batch_axis=1)

encoder.collect_params().initialize()
decoder.collect_params().initialize()

encoder.hybridize()
decoder.hybridize()

data = mx.nd.zeros((10, 8), mx.cpu())
begin_state = encoder.rnn.begin_state(
    func=mx.nd.zeros, batch_size=8, ctx=mx.cpu())
with autograd.record():
    output, hidden = encoder(data, begin_state)
    projection, _ = decoder(data, hidden)
    l = loss(projection, data)
l.backward()

```

If hybridization is deactivated, the example works. It also works when run on gpu. It seems **un**related to MKL.

This is the error on cpu:


```
[19:46:34] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [19:46:34] src/imperative/./imperative_utils.h:596: Check failed: vctx[i].dev_type != -1 (-1 vs. -1) Cannot decide context for node zeros

Stack trace returned 10 entries:
[bt] (0) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(+0x175b6c) [0x7f32ddec3b6c]
[bt] (1) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(+0x2051907) [0x7f32dfd9f907]
[bt] (2) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(+0x204a903) [0x7f32dfd98903]
[bt] (3) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(MXAutogradBackwardEx+0x778) [0x7f32dfcf3448]
[bt] (4) /usr/lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x7f32f0b94028]
[bt] (5) /usr/lib64/libffi.so.6(ffi_call+0x32a) [0x7f32f0b93a8a]
[bt] (6) /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ef) [0x7f32f0dfc51f]
[bt] (7) /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0xa6aa) [0x7f32f0df66aa]
[bt] (8) /usr/lib64/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x89) [0x7f32f23a5f09]
[bt] (9) /usr/lib64/libpython3.6m.so.1.0(+0x12bb73) [0x7f32f2464b73]

Traceback (most recent call last):
  File "testmxnet.py", line 56, in <module>
    l.backward()
  File "/home/leonard/.local/lib64/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1761, in backward
    ctypes.c_void_p(0)))
  File "/home/leonard/.local/lib64/python3.6/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:46:34] src/imperative/./imperative_utils.h:596: Check failed: vctx[i].dev_type != -1 (-1 vs. -1) Cannot decide context for node zeros

Stack trace returned 10 entries:
[bt] (0) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(+0x175b6c) [0x7f32ddec3b6c]
[bt] (1) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(+0x2051907) [0x7f32dfd9f907]
[bt] (2) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(+0x204a903) [0x7f32dfd98903]
[bt] (3) /home/leonard/.local/lib64/python3.6/site-packages/mxnet/libmxnet.so(MXAutogradBackwardEx+0x778) [0x7f32dfcf3448]
[bt] (4) /usr/lib64/libffi.so.6(ffi_call_unix64+0x4c) [0x7f32f0b94028]
[bt] (5) /usr/lib64/libffi.so.6(ffi_call+0x32a) [0x7f32f0b93a8a]
[bt] (6) /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ef) [0x7f32f0dfc51f]
[bt] (7) /usr/lib64/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0xa6aa) [0x7f32f0df66aa]
[bt] (8) /usr/lib64/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x89) [0x7f32f23a5f09]
[bt] (9) /usr/lib64/libpython3.6m.so.1.0(+0x12bb73) [0x7f32f2464b73]

```

**Comment by ykim362** [comment]
Autograd and gluon are not tested and looks not supporting MKL. The current re-factoring with MKL storage might help this problem. At least, the debugging will be started based on that re-factoring as a baseline.

**Comment by leezu** [comment]
@ykim362 note this issue happen irrespective of MKL. I.e. it is also present when compiling mxnet without mkl support.

**Comment by szha** [comment]
#8450 was a fix for a problem with the same symptom. Is the problem not fixed even after this PR?

**Comment by leezu** [comment]
@szha indeed the example provided above works after #8450. I was not careful enough when checking that the issue still persists on master. While this particular issue is fixed there is another regressions with v0.12:

```
mxnet.base.MXNetError: [13:04:27] src/imperative/imperative.cc:301: Check failed: !ndinputs.back()->is_none() node_254 0

Stack trace returned 10 entries:
[bt] (0) /home/data/lelausen/software/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x29) [0x7f45e0a28df9]
[bt] (1) /home/data/lelausen/software/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet10Imperative8RunGraphEbRKN4nnvm12IndexedGraphESt6vectorIPNS_7NDArrayESaIS7_EEmmOS5_INS_9OpReqTypeESaISA_EEOS5_IjSaIjEEPS5_INS_10OpStatePtrESaISH_EERKS5_INS_12DispatchModeESaISL_EE+0x15f3) [0x7f45e2f3f273]
[bt] (2) /home/data/lelausen/software/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet10Imperative8BackwardERKSt6vectorIPNS_7NDArrayESaIS3_EES7_S7_bbb+0x3b42) [0x7f45e2f431b2]
[bt] (3) /home/data/lelausen/software/mxnet/python/mxnet/../../lib/libmxnet.so(MXAutogradBackwardEx+0x96a) [0x7f45e33851aa]
[bt] (4) /usr/local/software/python-3.6.2/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f46653df186]
[bt] (5) /usr/local/software/python-3.6.2/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(ffi_call+0x2d2) [0x7f46653dec62]
[bt] (6) /usr/local/software/python-3.6.2/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2cf) [0x7f46653d7f7f]
[bt] (7) /usr/local/software/python-3.6.2/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0xb3eb) [0x7f46653d23eb]
[bt] (8) /usr/local/software/python-3.6.2/lib/libpython3.6m.so.1.0(_PyObject_FastCallDict+0x8b) [0x7f4671eae2db]
[bt] (9) /usr/local/software/python-3.6.2/lib/libpython3.6m.so.1.0(+0x163f73) [0x7f4671f68f73]
```

It occurs when extending the example above with a free running decoder which shares its parameters with the original decoder, and using the professor forcing training objective:

```
        with autograd.record():
            output, hidden = self.encoder(data, encoder_begin_state)
            prediction, outputs, decoder_hidden = self.decoder(data, hidden)
            prediction_free, outputs_free, decoder_hidden_free = self.pf_free_decoder(
                data, hidden)

            discriminator_prediction = self.professor_forcing_discriminator(
                outputs_free)
#            l_pf_gan = self.professor_forcing_gan_composable.gan_loss(
#                discriminator_prediction,
#                self.professor_forcing_gan_composable.get_discriminator_label(
#                    data=discriminator_prediction))
            l_ae = self.ae_loss(prediction, expected_label)
            l = l_ae  # + l_pf_gan

```

Uncommenting the lines above will trigger the error. Let me know if you need a self-contained example that triggers the error.

**Comment by szha** [comment]
@piiswrong

**Comment by piiswrong** [comment]
@leezu Could you post a complete example?

**Comment by leezu** [comment]
The issue seems to be fixed in v1. Perhaps by #8701? Anyways, thanks!
