### ISSUE TITLE
mx.autograd.grad's works or fails depending on use of slices

### ISSUE THREAD

**Issue by kpot** [apache/incubator-mxnet#8337]
Hello guys,

Testing latest master branch 349ebc36ff3693376287098d280b11069dafbb55, I found that the same code using `autograd.grad` works fine or fails depending on whether I use full slice of a variable or not.

Working example:
```
import mxnet as mx
from mxnet import nd, autograd

ctx = mx.cpu()

a = mx.nd.array([1, 2, 3, 4], ctx=ctx)
a.attach_grad()

with autograd.record():
    b = nd.sum(2 * (a ** 2))   # works without slicing

grads = autograd.grad(b, [a], create_graph=True, retain_graph=True)
da_sym = autograd.get_symbol(grads[0])
executor = da_sym.bind(ctx=ctx, args=[mx.nd.ones_like(b), a])
executor.forward()
print(executor.outputs[0])
```

but if I change the line `b = nd.sum(2 * (a ** 2))` with a technically identical expression `b = nd.sum(2 * (a[0:4] ** 2))` with variable `a` being sliced, the code begins to fail on `da_sym.bind(...)` with message

```
Traceback (most recent call last):
  File "autograd_test.py", line 14, in <module>
    executor = da_sym.bind(ctx=ctx, args=[mx.nd.ones_like(b), a])
  File "/home/kpot/pyves/mxnet/lib/python3.6/site-packages/mxnet-0.12.0-py3.6.egg/mxnet/symbol/symbol.py", line 1666, in bind
    ctypes.byref(handle)))
  File "/home/kpot/pyves/mxnet/lib/python3.6/site-packages/mxnet-0.12.0-py3.6.egg/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:32:23] src/executor/graph_executor.cc:451: InferShape pass cannot decide shapes for the following arguments (0s means unknown dimensions). Please consider providing them as inputs:

<just blank lines here>

Stack trace returned 10 entries:
[bt] (0) /home/kpot/pyves/mxnet/lib/python3.6/site-packages/mxnet-0.12.0-py3.6.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fe624ac93cc]
...
```

Environment: Ubuntu 14.04, latest master branch of mxnet (rev 349ebc36ff3693376287098d280b11069dafbb55) built from sources following [official instructions](http://mxnet.incubator.apache.org/get_started/install.html) with `make USE_OPENCV=1 USE_BLAS=openblas`

My initial goal was to try to build a computational graph for back-propagation so I could later use it with nnvm and thus launch it on OpenCL devices. I would appreciate any help, if my approach is wrong and I should try do this differently.

Full diagnostics:
```
----------Python Info----------
Version      : 3.6.3
Compiler     : GCC 4.8.4
Build        : ('default', 'Oct 13 2017 11:22:10')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/kpot/pyves/mxnet/lib/python3.6/site-packages/pip
----------MXNet Info-----------
Version      : 0.12.0
Directory    : /home/kpot/pyves/mxnet/lib/python3.6/site-packages/mxnet-0.12.0-py3.6.egg/mxnet
Traceback (most recent call last):
  File "diagnose.py", line 108, in check_mxnet
    with open(commit_hash, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/kpot/pyves/mxnet/lib/python3.6/site-packages/mxnet-0.12.0-py3.6.egg/mxnet/COMMIT_HASH'

----------System Info----------
Platform     : Linux-3.13.0-133-generic-x86_64-with-debian-jessie-sid
system       : Linux
node         : eagle
release      : 3.13.0-133-generic
version      : #182-Ubuntu SMP Tue Sep 19 15:49:21 UTC 2017
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 1
Stepping:              2
CPU MHz:               3800.000
BogoMIPS:              7634.99
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             64K
L2 cache:              2048K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.1282 sec, LOAD: 2.0946 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.3062 sec, LOAD: 0.6475 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.3328 sec, LOAD: 1.3280 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.1119 sec, LOAD: 1.1860 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0681 sec, LOAD: 0.4717 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.1242 sec, LOAD: 0.3178 sec.
```

**Comment by piiswrong** [comment]
a's first dimension has length 1. Slicing it with 0:4 doesn't really make sense. It should raise an error.

**Comment by kpot** [comment]
I'm afraid you miss the point.
The failing code works fine being run using ordinary `.backward()` call:

```
import mxnet as mx
from mxnet import nd, autograd

ctx = mx.cpu()

a = mx.nd.array([1, 2, 3, 4], ctx=ctx)
a.attach_grad()

with autograd.record():
    b = nd.sum(2 * (a[0:4] ** 2))

b.backward()
print(a.grad)
```

Why does it fail when I retain the graph by using `autograd.grad` and then re-use this graph again directly via `.bind`? And such re-use fails *only* when the slicing is used. I deliberately made slicing `a[0:4]` because it doesn't change the shape of the expression and technically should be equal to just `a`. Without slicing both `autograd.grad` and `.bind` do their jobs perfectly well.

**Comment by ZiyueHuang** [comment]
`a`'s shape is `(4,)`.  Why "a's first dimension has length 1 and slicing it with 0:4 doesn't really make sense"? @piiswrong 

@kpot Could you please use `da_sym.list_arguments() ` to see what are the arguments? Why `args=[mx.nd.ones_like(b), a]`?

**Comment by ZiyueHuang** [comment]
Is this a bug or wrong usage of autograd? Do you have any idea? @szha

**Comment by kpot** [comment]
@ZiyueHuang `a`s first dimension is 4, and slicing it like `a[0:4]` is absolutely valid and I didn't care about effectiveness here. But after you asked, I tried different expressions. I tried different sizes of `a` (for example, `a = mx.nd.array([ [ 1, 2, 3, 4] ])` and slicing it in the expression as `a[0]`). None of that has worked. I still see the same error every time I use slicing.

`da_sym.list_arguments()` returns `['', 'var0']`. One must be the head gradient for the chain rule and another one is a placeholder the  for variable `a`. That's why I used such arguments. Which is which I determined experimentally, since both have different shapes, and I could easilly check the result of `executor.forward()` knowing derivative `db / da = 4 * a`.

**Comment by ZiyueHuang** [comment]
I think the empty line in the error massage is the argument `''`.

Please try replace  `mx.nd.ones_like(b)` with `mx.nd.ones((1,))`, it works fine for me.

**Comment by kpot** [comment]
@ZiyueHuang Yes, I think the empty line is indeed the argument `''`.
But when I replace `mx.nd.ones_like(b)` with `mx.nd.ones((1,))` I still get the same error. Are you sure that when it worked for you, you actually did use slicing?

Just to be on the same page, here's the full code that fails, even though I believe it shouldn't:
```
import mxnet as mx
from mxnet import nd, autograd

ctx = mx.cpu()

a = mx.nd.array([1, 2, 3, 4], ctx=ctx)
a.attach_grad()

with autograd.record():
    b = nd.sum(2 * (a[0:4] ** 2))   # works without slicing

grads = autograd.grad(b, [a], create_graph=True, retain_graph=True)
da_sym = autograd.get_symbol(grads[0])
executor = da_sym.bind(ctx=ctx, args=[nd.ones_like(b), a])
executor.forward()
print(executor.outputs[0])
```

**Comment by ZiyueHuang** [comment]
Sorry, I just paste the codes you posted at first comment, without adding slice.

**Comment by piiswrong** [comment]
Looks like it might be a bug. I'll look into it.

But getting the symbol from a autograd NDArray and binding it is not recommended.

**Comment by kpot** [comment]
@piiswrong Is there any better way to get the graph/symbol from autograd? Because the method I use seems logical to me: I did forward propagation, then I launched back-propagation, then I saved the graph, so now I can re-use it again without the need of recording it. I know, it's not very flexible, but I have a reason for that.

I'm trying to get the graph explicitly because I want to use nnvm to compile and run this graph on an OpenCL device. Currently nnvm-mxnet frontend supports only forward-propagating `HybridBlock`s or mxnet.symbol -based graphs. That's why I'm trying to get the last one.

**Comment by sxjscience** [comment]
@leezu Could you help simplify this a little bit? I'll look at this tomorrow.

**Comment by leezu** [comment]
@sxjscience I have simplified the code until any change makes the bug disappear:
```
class Loss(mx.gluon.Block):
    def forward(self, score, target):
        bsz = score.shape[0]
        mag = (score**2).sum(1).broadcast_to((bsz, bsz))
        sim = mx.nd.dot(score, score.T)
        dist = (mag + mag.T - 2 * sim)
        dist = mx.nd.Activation(dist, act_type="relu")
        dist = mx.nd.sqrt(dist)
        return mx.nd.mean(dist)


if __name__ == "__main__":
    import numpy as np
    np.random.seed(123)

    score = np.random.uniform(0, 1, (20, 3))
    target = np.random.choice(range(3), 20)

    loss = Loss()

    score = mx.nd.array(score)
    target = mx.nd.array(target)
    score.attach_grad()
    with mx.autograd.record():
        l = loss(score, target)
    l.backward()
    print(score.grad)

```
It seems this bug may not be related to slicing after all, sorry @kpot for putting this wrongly in your issue ;)

**Comment by sxjscience** [comment]
@leezu I find that `dist[0, 0]` will always be 0 and the `sqrt` function is non-differentiable at 0. The result will be correct if we add a small epsilon to the dist
```python
import mxnet as mx
import numpy as np

class Loss(mx.gluon.Block):
    def forward(self, score, target):
        bsz = score.shape[0]
        mag = (score**2).sum(1).broadcast_to((bsz, bsz))
        sim = mx.nd.dot(score, score.T)
        dist = (mag + mag.T - 2 * sim)
        dist = mx.nd.Activation(dist, act_type="relu") + 1E-9
        dist = mx.nd.sqrt(dist)
        return mx.nd.mean(dist)


if __name__ == "__main__":
    import numpy as np
    np.random.seed(123)

    score = np.random.uniform(0, 1, (20, 3))
    target = np.random.choice(range(3), 20)

    loss = Loss()

    score = mx.nd.array(score)
    target = mx.nd.array(target)
    score.attach_grad()
    with mx.autograd.record():
        l = loss(score, target)
    l.backward()
    print(score.grad)
```

**Comment by roywei** [comment]
@kpot  may I know what's the purpose of slice? let's say if you want a[0:2], how you want to use it?
`a[0:4]` is a shallow copy of `a` , using slice in autograd may not be the idea way.
In your case for OpenCL device, could you try to use symbolic gradient directly from nnvm? refer to [gradient](https://github.com/dmlc/nnvm/blob/master/src/pass/gradient.cc) and [test](https://github.com/dmlc/nnvm/blob/master/tests/python/compiler/test_optimizer.py#L33)

```
a = mx.nd.array([1, 2, 3, 4], ctx=ctx)
print(id(a))
print(id(a[0:4]))

>>>4387046120
>>>4387048864

**Comment by kpot** [comment]
@roywei To be honest, over the last months I've already lost the context and don't remember what I was using the slicing for. You're correct by saying it may not be an ideal way. But as a developer I know how a seemingly insignificant issue can help to discover really big bugs in a software project. So I decided "If I discovered the bug anyway, I might as well go on and report it. Perhaps it would help the guys to improve autograd" :)

About symbolic gradient via NNVM: I'm trying to do exactly that now. Unfortunately both NNVM and TVM have rather thin documentation, and to understand some things requires digging through C++ code, so the progress is slow. Simply don't have much time. Hence the attempt to use mxnet's autograd as a shortcut.

**Comment by sandeep-krishnamurthy** [comment]
@piiswrong - Any updates or directions to take for fixing this issue?

**Comment by 610v4nn1** [comment]
I am also facing something which seems to be the same problem. Is there an update on this bug?
