### ISSUE TITLE
model_converter.py fails to convert GoogLeNet caffe model

### ISSUE THREAD

**Issue by GengZ** [apache/incubator-mxnet#8421]
## Description
When using model_converter.py to convert resnet_50 downloaded from caffe community, it works fine. But when using model_converter.py to convert [googlenet](http://dl.caffe.berkeleyvision.org/bvlc_googlenet.caffemodel), it failed with the following error:

## Error Massage
```
Traceback (most recent call last):
  File "/home/alfa/baseline/mxnet/tools/caffe_converter/convert_model.py", line 162, in <module>
    main()
  File "/home/alfa/baseline/mxnet/tools/caffe_converter/convert_model.py", line 158, in main
    convert_model(args.prototxt, args.caffemodel, args.save_model_name)
  File "/home/alfa/baseline/mxnet/tools/caffe_converter/convert_model.py", line 34, in convert_model
    sym, input_dim = convert_symbol(prototxt_fname)
  File "/home/alfa/baseline/mxnet/tools/caffe_converter/convert_symbol.py", line 223, in convert_symbol
    sym, output_name, input_dim = _parse_proto(prototxt_fname)
  File "/home/alfa/baseline/mxnet/tools/caffe_converter/convert_symbol.py", line 80, in _parse_proto
    input_name, input_dim, layer = _get_input(proto)
  File "/home/alfa/baseline/mxnet/tools/caffe_converter/convert_symbol.py", line 16, in _get_input
    layer.pop(0)
AttributeError: 'RepeatedCompositeFieldContainer' object has no attribute 'pop'
```

Thanks in advance.

**Comment by badstones** [comment]
I've met the same question,  could you @GengZ  get the solution?  Thank you

**Comment by kitstar** [comment]
Hi @badstones you can try [MMdnn](https://www.github.com/Microsoft/MMdnn) to convert the google pre-trained caffe model.

**Comment by szha** [comment]
We are deprecating caffe converter
