### ISSUE TITLE
TypeError: zip argument #2 must support iteration

### ISSUE THREAD

**Issue by FCInter** [apache/incubator-mxnet#8465]
## Description
(Brief description of the problem in no more than 2 sentences.)
The error happens when loading the pre-trained models. The pre-trained model is the resnet which can be downloaded [here](http://data.dmlc.ml/mxnet/models/imagenet/resnet/18-layers/).
## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.13')
('Compiler     :', 'GCC 4.4.7 20120313 (Red Hat 4.4.7-1)')
('Build        :', ('default', 'Dec 20 2016 23:09:15'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/home/mypath/anaconda2/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '0.11.0')
('Directory    :', '/home/mypath/software/try_mxnet2/mxnet/python/mxnet')
Traceback (most recent call last):
  File "diagnose.py", line 171, in <module>
    check_mxnet()
  File "diagnose.py", line 113, in check_mxnet
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

Package used (Python/R/Scala/Julia):
Python

Compiler (gcc/clang/mingw/visual studio):
gcc

## Error Message:
```
[16:29:52] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[16:29:52] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
[16:29:59] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[16:30:09] src/io/iter_image_recordio_2.cc:153: ImageRecordIOParser2: ../meta/train.rec, use 4 threads for decoding..
WARNING:root:Already bound, ignoring bind()
kk.py:18: UserWarning: Parameters already initialized and force_init=False. init_params call ignored.
  my_model.init_params(initializer=mx.init.Uniform(scale=.1))
Traceback (most recent call last):
  File "kk.py", line 26, in <module>
    my_model.update_metric(metric, batch.label)  # accumulate prediction accuracy
  File "/home/mypath/software/try_mxnet2/mxnet/python/mxnet/module/module.py", line 735, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/mypath/software/try_mxnet2/mxnet/python/mxnet/module/executor_group.py", line 567, in update_metric
    for label, axis in zip(labels, self.label_layouts):
TypeError: zip argument #2 must support iteration
```

## Minimum reproducible example
```
import mxnet as mx
im_size = 240
batch_size = 1000
num_epoch = 5
# load model
sym, arg_params, aux_params = mx.model.load_checkpoint('../model/resnet-18', 0)
my_model = mx.mod.Module(symbol=sym, context=[mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3)], label_names=None)
my_model.bind(for_training=True, data_shapes=[('data', (batch_size,3,im_size,im_size))], 
         label_shapes=my_model._label_shapes)
my_model.set_params(arg_params, aux_params, allow_missing=True)
# load model end
train_iter = mx.io.ImageRecordIter(
	path_imgrec="../meta/train.rec", 
	data_shape=(3, im_size, im_size), 
	batch_size=batch_size 
	)
my_model.bind(data_shapes=train_iter.provide_data, label_shapes=train_iter.provide_label)
my_model.init_params(initializer=mx.init.Uniform(scale=.1))
my_model.init_optimizer(optimizer='sgd', optimizer_params=(('learning_rate', 0.0001), ))
metric = mx.metric.create('acc')
for epoch in range(num_epoch):
	train_iter.reset()
	metric.reset()
	for batch in train_iter:
		my_model.forward(batch, is_train=True)	   # compute predictions
		my_model.update_metric(metric, batch.label)  # accumulate prediction accuracy
		my_model.backward()						  # compute gradients
		my_model.update()							# update parameters
	info = 'a Epoch %d, Training %s' % (epoch, metric.get())
	print(info)
```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Simply put the code in a file, say `a.py`, then run `python a.py`

## What have you tried to solve it?

1. I tried to load other pre-trained models, such as the [densenet](https://github.com/bruinxiong/densenet.mxnet), but the problem is the same.
2. I also tried to build a model by myself, train it using the data file. The training process will succeed. This means perhaps there is no problem in the data file.
Thank you all for helping me!

**Comment by arundasan91** [comment]
Hi @FCInter, I've had similar issues and found that I missed to pass proper `data_name` and `label_name` to my `ImageRecordIter` function. Here is something which works for me all the time with `symbols` and `params` downloaded from ModelZoo.

```python
data_val = 'path_to_val.rec'
data_val_lst = "path_to_val.lst"
data_train = 'path_to_train.rec'
data_shape = (3, 224, 224)
label_name = 'softmax_label'
data_name = 'data'
data_nthreads = 8

val = mx.io.ImageRecordIter(
        path_imgrec        = data_val,
        path_imglist       = data_val_lst,
        label_width        = 1,
        preprocess_threads = data_nthreads,
        batch_size         = batch_size,
        data_shape         = data_shape,
        label_name         = label_name,
        rand_crop          = False,
        rand_mirror        = False
```

Also, `Module` may be used with `label_names` and when binding using `mod.bind`, pass the data and label shapes.

```python
mod = mx.mod.Module(symbol=sym, context=devs, label_names=[label_name,])
mod.bind(for_training=False,
         data_shapes=val.provide_data,
         label_shapes=val.provide_label)
mod.set_params(arg_params, aux_params)
```

Please let me know if this works. We can try other methods if this doesn't.

Cheers,
Arun

**Comment by cjolivier01** [comment]
This appears to be answered, closing. Please reopen if your issue remains.

**Comment by Vert53** [comment]
I'm having the same problem. The solution does not work for me.
