### ISSUE TITLE
ValueError: Unknown initialization pattern for softmax_label

### ISSUE THREAD

**Issue by FCInter** [apache/incubator-mxnet#8466]
## Description
ValueError happens when I'm initializing the parameters of a model.

## Environment info (Required)

```
----------Python Info----------
('Version      :', '2.7.13')
('Compiler     :', 'GCC 4.4.7 20120313 (Red Hat 4.4.7-1)')
('Build        :', ('default', 'Dec 20 2016 23:09:15'))
('Arch         :', ('64bit', 'ELF'))
------------Pip Info-----------
('Version      :', '9.0.1')
('Directory    :', '/home/mypath/anaconda2/lib/python2.7/site-packages/pip')
----------MXNet Info-----------
('Version      :', '0.11.0')
('Directory    :', '/home/mypath/software/try_mxnet2/mxnet/python/mxnet')
Traceback (most recent call last):
  File "diagnose.py", line 171, in <module>
    check_mxnet()
  File "diagnose.py", line 113, in check_mxnet
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

Package used (Python/R/Scala/Julia):
Python

Compiler (gcc/clang/mingw/visual studio):
gcc

## Error Message:
```
[18:38:17] src/nnvm/legacy_json_util.cc:190: Loading symbol saved by previous version v0.8.0. Attempting to upgrade...
[18:38:17] src/nnvm/legacy_json_util.cc:198: Symbol successfully upgraded!
0
[18:38:17] src/io/iter_image_recordio_2.cc:153: ImageRecordIOParser2: ../meta/train.rec, use 4 threads for decoding..
/home/mypath/software/try_mxnet2/mxnet/python/mxnet/module/base_module.py:65: UserWarning: Data provided by label_shapes don't match names specified by label_names ([DataDesc[softmax_label,(1000L,),<type 'numpy.float32'>,NCHW]] vs. [])
  warnings.warn(msg)
[18:38:27] src/operator/././cudnn_algoreg-inl.h:112: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "kk.py", line 61, in <module>
    my_model.init_params(initializer=mx.init.Uniform(scale=.1))
  File "/home/mypath/software/try_mxnet2/mxnet/python/mxnet/module/module.py", line 296, in init_params
    _impl(desc, arr, arg_params)
  File "/home/mypath/software/try_mxnet2/mxnet/python/mxnet/module/module.py", line 291, in _impl
    initializer(name, arr)
  File "/home/mypath/software/try_mxnet2/mxnet/python/mxnet/initializer.py", line 156, in __call__
    self._init_default(desc, arr)
  File "/home/mypath/software/try_mxnet2/mxnet/python/mxnet/initializer.py", line 242, in _init_default
    'Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern' % name)
ValueError: Unknown initialization pattern for softmax_label. Default initialization is now limited to "weight", "bias", "gamma" (1.0), and "beta" (0.0).Please use mx.sym.Variable(init=mx.init.*) to set initialization pattern
```

## Minimum reproducible example
```
import mxnet as mx

num_classes = 5270
im_size = 240
batch_size = 1000
num_epoch = 5
sym, arg_params, aux_params = mx.model.load_checkpoint('../model/resnet-18', 0)
def get_fine_tune_model(symbol, arg_params, num_classes, layer_name='flatten0'):
	all_layers = symbol.get_internals()
	net = all_layers[layer_name+'_output']
	net = mx.symbol.FullyConnected(data=net, num_hidden=num_classes, name='fc1')
	net = mx.symbol.SoftmaxOutput(data=net, name='softmax')
	new_args = dict({k:arg_params[k] for k in arg_params if 'fc1' not in k})
	return (net, new_args)
print 0
sym, arg_params = get_fine_tune_model(sym,arg_params,num_classes, layer_name = 'flatten0')
my_model = mx.mod.Module(symbol=sym, context=[mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3)], label_names=None)
train_iter = mx.io.ImageRecordIter(
	path_imgrec="../meta/train.rec", 
	data_shape=(3, im_size, im_size), 
	batch_size=batch_size 
	)
my_model.bind(for_training=True, data_shapes=train_iter.provide_data, label_shapes=train_iter.provide_label,force_rebind=True)
initializer = mx.init.Uniform(scale=.1)
my_model.init_params(initializer=mx.init.Uniform(scale=.1))
my_model.set_params(arg_params, aux_params, allow_missing=True)
my_model.init_optimizer(optimizer='sgd', optimizer_params=(('learning_rate', 0.0001), ))
metric = mx.metric.create('acc')
exit()
print 'start training'
for epoch in range(num_epoch):
	train_iter.reset()
	metric.reset()
	for batch in train_iter:
		my_model.forward(batch, is_train=True)	   # compute predictions
		my_model.update_metric(metric, batch.label)  # accumulate prediction accuracy
		my_model.backward()						  # compute gradients
		my_model.update()							# update parameters
	info = 'a Epoch %d, Training %s' % (epoch, metric.get())
	print(info)
```

## Steps to reproduce
(Paste the commands you ran that produced the error.)

1. Simply put the code in a file, say `a.py`, then run `python a.py`.

## What have you tried to solve it?

1. I find that if I comment the line `my_model.init_params(initializer=mx.init.Uniform(scale=.1))`. Then no bug was reported. But I don't know why. As far as I can understand, if I don't run the `init_params` first, the parameters will not be initialized. Since I change the network structure after I load the model, even if I run `set_params` to set the parameter values saved in `arg_params`, the network has been changed now and the parameters of the newly-added fully connect layer does not have values in `arg_params`. If I did not initialize it first, would it lead to other problems?

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by indhub** [comment]
Looks like you are trying to initialize softmax label which shouldn't be initialized by the iniliatizer. This is not an issue but a problem with the training script. Could you please post this question in the [user forum](https://discuss.mxnet.io/)? Thanks!
