### ISSUE TITLE
[Gluon] F.pad(...) doesn't accept symbol input even in HybridBlock?

### ISSUE THREAD

**Issue by masahi** [apache/incubator-mxnet#8537]
Hi, I am trying to dump a json string from [this](https://github.com/apache/incubator-mxnet/tree/master/example/gluon/style_transfer) very nice style transfer model, written in gluon API.

I modified the net definition so that all blocks inherent from HybridBlock and use HybridSequential. The modified one is [here](https://gist.github.com/masahi/9c70bfc86fe0d63b1b690d991f5e8916).

I think this is enough to dump a json from gluon model. But when I try this,

```
    style_model = net.Net(ngf=args.ngf)
    x = mx.sym.var("x")
    y = style_model(x)
    y.save("style_model.json")
```

It gives me the following error:
```
Traceback (most recent call last):
  File "main.py", line 234, in <module>
    main()
  File "main.py", line 223, in main
    evaluate(args)
  File "main.py", line 146, in evaluate
    y = style_model(x)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 290, in __call__
    return self.forward(*args)
  File "D:\project\dev\incubator-mxnet\example\gluon\style_transfer\net.py", line 231, in forward
    return self.model(input)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 290, in __call__
    return self.forward(*args)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 481, in forward
    return self.hybrid_forward(symbol, x, *args, **params)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\nn\basic_layers.py", line 107, in hybrid_forward
    x = block(x)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 290, in __call__
    return self.forward(*args)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 481, in forward
    return self.hybrid_forward(symbol, x, *args, **params)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\nn\basic_layers.py", line 107, in hybrid_forward
    x = block(x)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 290, in __call__
    return self.forward(*args)
  File "D:\project\dev\incubator-mxnet\example\gluon\style_transfer\net.py", line 139, in forward
    x = self.pad(x)
  File "C:\Users\masah\Anaconda3\lib\site-packages\mxnet-0.12.0-py3.6.egg\mxnet\gluon\block.py", line 290, in __call__
    return self.forward(*args)
  File "D:\project\dev\incubator-mxnet\example\gluon\style_transfer\net.py", line 60, in forward
    return F.pad(x, mode='reflect', pad_width=self.pad_width)
  File "<string>", line 112, in pad
AssertionError: Argument data must have NDArray type, but got <Symbol x>
```

The error is occurring at [here](https://gist.github.com/masahi/9c70bfc86fe0d63b1b690d991f5e8916#file-net_modified-py-L60), inside HybridBlock.

Am I missing something, or is F.pad(...) indeed supposed to only accept NDArray inputs?

Thanks

**Comment by masahi** [comment]
@zhanghang1989

**Comment by masahi** [comment]
Sorry, I was not updating forward(...) to hybrid_forward(...).

**Comment by samhodge** [comment]
Did you commit your updated hybrid forward function I am coming across the same issue

**Comment by masahi** [comment]
no. 

Updating to hybrid_forward() did solve my original problem. But it turned out, for other reasons, this neural style transfer example can't work with Symbol input.

**Comment by samhodge** [comment]
Thanks @masahi Did you find a style transfer that was fast that could take a Symbol input?

**Comment by masahi** [comment]
I tried the one [here](https://github.com/zhaw/neural_style/tree/master/perceptual)
Not as high quality as the gluon example, but it works.
