### ISSUE TITLE
Sparse tensors causing a deadlock

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#8675]
We identified some issues with a deadlock. We suspect that they are caused by running multiple tests on the same machine.

Trace:
```

(gdb) bt full                                                                                                                                                                                       [0/1330]
#0  pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
No locals.
#1  0x00002b35021f64dc in std::condition_variable::wait(std::unique_lock<std::mutex>&) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#2  0x00002b34feb4a0e1 in wait<mxnet::engine::ThreadedEngine::WaitForVar(mxnet::Engine::VarHandle)::__lambda18> (__p=..., __lock=..., this=0xa93bb8) at /usr/include/c++/4.8/condition_variable:93
No locals.
#3  mxnet::engine::ThreadedEngine::WaitForVar (this=0xa93b70, var=<optimized out>)
    at src/engine/threaded_engine.cc:358
        lock = {_M_device = 0xa93b90, _M_owns = true}
        threaded_var = <optimized out>
        done = {<std::atomic_bool> = {_M_base = {_M_i = false}}, <No data fields>}
#4  0x00002b34feccda74 in WaitToRead (this=0x47dc580) at include/mxnet/ndarray.h:317
No locals.
#5  mxnet::NDArray::SyncCopyToCPU (this=0x47dc580, data=0x47d6a10, size=6)
    at src/ndarray/ndarray.cc:1197
        dshape = {<nnvm::Tuple<long>> = {static kStackCache = <optimized out>, ndim_ = 2,
            num_heap_allocated_ = 0, data_stack_ = {3, 2, 10928297, 0},
            data_heap_ = 0x0}, <No data fields>}
        dst = {dptr_ = 0x47d6a10, shape_ = {<nnvm::Tuple<long>> = {
              static kStackCache = <optimized out>, ndim_ = 2, num_heap_allocated_ = 0,
              data_stack_ = {3, 2, 10928144, 75293601}, data_heap_ = 0x0}, <No data fields>},
          type_flag_ = 0, dltensor_ = {data = 0x47d6a10, ctx = {device_type = kCPU, device_id = 0},
            ndim = 2, dtype = {code = 2 '\002', bits = 32 ' ', lanes = 1}, shape = 0x7ffe6eee8200,
            strides = 0x0, byte_offset = 0}}
#6  0x00002b34feaf9dba in MXNDArraySyncCopyToCPU (handle=<optimized out>, data=<optimized out>,
    size=<optimized out>) at src/c_api/c_api.cc:253
No locals.
#7  0x00002b34fc488264 in _wrap_NDArraySyncCopyToCPU (my_perl=<optimized out>, cv=<optimized out>)
    at mxnet_wrap.cxx:4814
        arg2 = 0x47d6a10
        val3 = <optimized out>
        ecode3 = <optimized out>
        argvi = 0
        mark = <optimized out>
        items = <optimized out>
        arg3 = <optimized out>
        argp1 = 0x47dc580
        sp = <optimized out>
        ax = <optimized out>
        arg1 = <optimized out>
        res1 = <optimized out>
        result = <optimized out>
#8  0x00002b34f8cd5c46 in Perl_pp_entersub () from /usr/lib/libperl.so.5.18
No symbol table info available.
#9  0x00002b34f8cce266 in Perl_runops_standard () from /usr/lib/libperl.so.5.18
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
```

**Comment by marcoabreu** [comment]
Closing until we gathered more details

**Comment by lialie** [comment]
@marcoabreu Have figured it out?

**Comment by marcoabreu** [comment]
@lialie Our current research shows that this is caused by ubuntu 14.04 (in our case inside docker) on the new Skylake Processors with AVX-512 instruction set while using OpenBlas running MXNet on the CPU. The OpenBlas driver on ubuntu 14.04 is not yet updated to be compatible with the latest processor architectures and thus tries to execute a Kernel that is optimized for a Pentium IV - this results in a deadlock.

**Comment by lialie** [comment]
@marcoabreu I have the same issue with Win7/GPU 1060/CPU i5. At first, the OpenBlas may be a problem, after change it with MKL package, but without lucky.
