### ISSUE TITLE
running Gluon's SymbolBlock seems to give a List type instead of Nd.array type

### ISSUE THREAD

**Issue by tz-hmc** [apache/incubator-mxnet#8700]
Hi,
I'm trying to use Resnet as a feature extractor, but for some reason, it returns a list instead of a ndarray. This breaks everything after it (the concatenation, passing it to another network, etc.) 
Here's the relevant code:

```
    inputs = mx.sym.var('data')
    resnet = models.resnet152_v1(pretrained=True)
    internals = resnet(inputs).get_internals()
    # print(internals.list_outputs())
    outputs = [internals['resnetv10_flatten0_reshape0_output']]
    net_siamese = gluon.SymbolBlock(outputs, inputs, params=resnet.collect_params())

.... 

        for i, ((data1, label1), (data2, label2)) in enumerate(zip(train_data1, train_data2)):
            data1 = data1.as_in_context(ctx).reshape((BATCH_SIZE, HEIGHT, WIDTH, DEPTH))
            data2 = data2.as_in_context(ctx).reshape((BATCH_SIZE, HEIGHT, WIDTH, DEPTH))
            print type(data1)
            with autograd.record():
                inter1 = net_siamese(data1)
                inter2 = net_siamese(data2)
                print(type(inter1), type(inter2))
                #print(inter1.shape, inter2.shape)
                inter = mx.nd.concat(inter1, inter2, dim=1)
                output = net_out(inter) # another network after it
```
Not sure why this is happeneing -- my inputs, data1 and data2, are definitely ndarray objects as well. 
Output for the code above: 

```
<class 'mxnet.ndarray.NDArray'>
(<type 'list'>, <type 'list'>) <------- returns a list! not the ndarrays I expected
Traceback (most recent call last):
  File "mxnet_shared_example_test.py", line 207, in <module>
    main()
  File "mxnet_shared_example_test.py", line 182, in main
    inter = mx.nd.concat(inter1, inter2, dim=1)
  File "<string>", line 7, in concat
AssertionError: Positional arguments must have NDArray type, but got [
[[ 0.96338123  0.32423893  1.4566021  ...,  0.65769273  0.01815998
   0.29373285]
 [ 1.15678489  0.42640418  0.37154302 ...,  0.36421105  0.10881857
   0.10574293]
 [ 0.82367706  0.15637174  1.03548419 ...,  0.3314977   0.50468075
   1.54076731]
 ..., 
 [ 0.03157235  0.08601706  0.36874363 ...,  0.23690662  0.36709765
   0.08842831]
 [ 1.04645705  0.50840384  1.06173313 ...,  0.20731537  0.05717596
   0.37697673]
 [ 0.24901849  1.06380773  1.90573788 ...,  0.11043268  1.08995724
   0.25933489]]
<NDArray 64x2048 @cpu(0)>]
```

Strange why this only happens here -- I tested the [Alexnet feature extractor example from the MxNet website](https://mxnet.incubator.apache.org/api/python/gluon.html#mxnet.gluon.SymbolBlock) and it works fine, returning an ndarray as expected.

Does anyone know why this is happening? Would really appreciate any help regarding this issue. Thanks!

**Comment by piiswrong** [comment]
Because you specified output to be
`outputs = [internals['resnetv10_flatten0_reshape0_output']]`
notice the list.
You should instead set it to
`outputs = internals['resnetv10_flatten0_reshape0_output']`

**Comment by tz-hmc** [comment]
I did what you said, and it still says the output is a list type. And then the concatenation doesn't work. 

```
    # print(internals.list_outputs())
    outputs = internals['resnetv10_flatten0_reshape0_output']
    net_siamese = gluon.SymbolBlock(outputs, inputs, params=resnet.collect_params())
```

```
<type 'list'> <type 'list'>
Traceback (most recent call last):
  File "mxnet_shared_example_test.py", line 207, in <module>
    main()
  File "mxnet_shared_example_test.py", line 182, in main
    inter = mx.nd.concat(inter1, inter2, dim=1)
  File "<string>", line 7, in concat
AssertionError: Positional arguments must have NDArray type, but got [
[[ 0.83837587  0.28437173  1.43111885 ...,  0.30856618  0.73537797
   0.37734053]
 [ 0.59360677  0.85604697  1.11530054 ...,  0.47662133  0.07492419
   0.1135995 ]
 [ 0.40139517  0.29931211  1.13199711 ...,  0.38304275  0.67213672
   0.17700131]
 ..., 
 [ 1.16614783  0.60681313  0.27831089 ...,  0.1811825   0.42340329
   0.79479188]
 [ 0.06270231  0.58780235  0.26465079 ...,  0.75709373  0.07269836
   0.91913676]
 [ 1.15597522  0.06181324  0.50482339 ...,  0.3330026   0.62427616
   0.39908502]]
<NDArray 64x2048 @cpu(0)>]
```

**Comment by sxjscience** [comment]
@tz-hmc You can still use `concat` for list objects. You can do the following:
```python
inter = mx.nd.concat(*(inter1 + inter2), dim=1)
```

**Comment by tz-hmc** [comment]
Alright, nevermind. Looks like SymbolBlock returns a list of an NdArray, I think? 
Kept:
`outputs = internals['resnetv10_flatten0_reshape0_output']`

And also did:
```
                inter1 = net_siamese(data1)[0]
                inter2 = net_siamese(data2)[0]
                inter = mx.nd.concat(inter1, inter2, dim=1)
```
Seems to work fine and concatenates.
Thanks!
