### ISSUE TITLE
Predicting with batch size lower than the one used for training gives error

### ISSUE THREAD

**Issue by aijanai** [apache/incubator-mxnet#8802]
## Description
I train with dataset size = 904 and batch size = 50.
If I try then to predict with the model with a test set of arbitrary size and batch size < 50, it goes in segmentation fault.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.5.2
Compiler     : GCC 5.4.0 20160609
Build        : ('default', 'Sep 14 2017 22:51:06')
Arch         : ('64bit', 'ELF')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /home/ai_ja_nai/pischool/mxnet/venv3/local/lib/python3.5/site-packages/pip
----------MXNet Info-----------
Version      : 0.12.1
Directory    : /home/ai_ja_nai/pischool/mxnet/venv3/local/lib/python3.5/site-packages/mxnet
Commit Hash   : e0c7906693f0c79b0ce34a4d777c26a6bf1903c1
----------System Info----------
Platform     : Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial
system       : Linux
node         : aiMacBookPro
release      : 4.4.0-98-generic
version      : #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017
----------Hardware Info----------
machine      : x86_64
processor    : x86_64
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 69
Model name:            Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
Stepping:              1
CPU MHz:               2900.531
CPU max MHz:           2900,0000
CPU min MHz:           800,0000
BogoMIPS:              4800.02
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
----------Network Test----------
Setting timeout: 10
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0745 sec, LOAD: 0.1277 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.1750 sec, LOAD: 4.3842 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0590 sec, LOAD: 0.6070 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0557 sec, LOAD: 0.3190 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0468 sec, LOAD: 0.1626 sec.
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0343 sec, LOAD: 0.8834 sec.


```

Package used (Python/R/Scala/Julia):
I'm using Python

## Error Message:
```
Traceback (most recent call last):
  File "rnn_reverse_string.py", line 226, in <module>
    predictions=model.predict(test_iter)
  File "/home/ai_ja_nai/pischool/mxnet/venv3/local/lib/python3.5/site-packages/mxnet/module/base_module.py", line 354, in predict
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
  File "/home/ai_ja_nai/pischool/mxnet/venv3/local/lib/python3.5/site-packages/mxnet/module/base_module.py", line 354, in <listcomp>
    outputs = [out[0:out.shape[0]-pad].copy() for out in self.get_outputs()]
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

## Minimum reproducible example
[crashing_mxnet.tar.gz](https://github.com/apache/incubator-mxnet/files/1499701/crashing_mxnet.tar.gz)

## Steps to reproduce
Run `rnn_reverse_string.py` and enjoy the crash ;)

**NOTE**: this will train a seq2seq neural network (on "For whom the bell tolls" by Hemingway) to invert input sentences. Trains in 5-10 mins and 5GB of memory on a NVIDIA K80 GPU (on AWS, p2.xlarge). It will also checkpoint a 1.2GB model on disk at each epoch to resume and avoid retraining at each test you may want to take.

**Comment by aijanai** [comment]
Ok, looks like it was dealt it https://github.com/apache/incubator-mxnet/issues/6752: adding pad=0 to the `DataBatch` returned by my custom iterator solves the problem.

Wonder why this can't be the default option....

**Comment by aijanai** [comment]
#6752
