### ISSUE TITLE
compile error in plugin opencv

### ISSUE THREAD

**Issue by TX2012LH** [apache/incubator-mxnet#9203]
There is no such file `src/c_api_error.h' when I compiled it.

**Comment by mwbyeon** [comment]
@TX2012LH  please specify more information.

**Comment by TX2012LH** [comment]
## Description
`undefined symbol MXCVResize` after compiling plugin opencv.

## Environment info
ubuntu 14.04
mxnet v0.12.0
cuda 8.0+cudnn6.0
build from source

## Build config:
USE_CUDA=1
USE_CUDA_PATH=/usr/local/cuda
USE_CUDNN=1
USE_OPENCV=1
MXNET_PLUGINS+=plugin/opencv/opencv.mk

## Error Message:
No such file `src/c_api/c_api_error.h` included in `cv_api.cc`.
I find there is no `c_api_error.h` in directory `src/c_api` and I replace '#include "../../src/c_api/c_api_error.h"` with `#include "../../src/c_api/c_api-common.h"`. It is resolved and can be compiled successfully. 
But now when I call the `resize` function in `plugin/opencv/opencv.py`, `undefined symbol _LIB.MXCVResize' appears.

**Comment by mwbyeon** [comment]
@TX2012LH 
Thanks. It's a bug in `cv_api.cc`.
I created a new PR(#9206) to fix this issue.

**Comment by TX2012LH** [comment]
Although it is compiled successfully, `undefined symbol _LIB.MXCVResize` appears when call it. What may be the problem ?
@mwbyeon

**Comment by mwbyeon** [comment]
@TX2012LH  
Sorry. I missed that.
Please check below.

1. package path of mxnet
```bash
$ python
>>> import mxnet
>>> mxnet.base._LIB
<CDLL '{HIDDEN}/python3.6/site-packages/mxnet-1.0.1-py3.6.egg/mxnet/libmxnet.so', handle 11ec660 at 0x7fc0e0122fd0>
>>>
```

2. show functions using `nm` command
```bash
$ nm -gC {HIDDEN}/python3.6/site-packages/mxnet-1.0.1-py3.6.egg/mxnet/libmxnet.so  | grep MXCV
00000000032ec150 T MXCVResize(void*, unsigned int, unsigned int, int, void**)
00000000032ea2e0 T MXCVImdecode(unsigned char const*, unsigned int, int, void**)
00000000032e7170 T MXCVcopyMakeBorder(void*, int, int, int, int, int, double, void**)
```

if `MXCV*` functions not exists, rebuild and reinstall mxnet.

**Comment by TX2012LH** [comment]
Actually I have tried rebuilding and reinstalling mxnet several times. Messages are as follows:
```
(mxnet-v0.12.0) ➜  opencv git:(master) ✗ pwd
/data/xx/mxnet-v0.12.0/plugin/opencv
(mxnet-v0.12.0) ➜  opencv git:(master) ✗ python
Python 2.7.14 |Anaconda, Inc.| (default, Nov 20 2017, 18:04:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
mxnet.>>> mxnet.base._LIB
<CDLL '/data/xx/mxnet-v0.12.0/python/mxnet/../../lib/libmxnet.so', handle 55c617e7d750 at 7fe343717ad0>
>>> exit()
(mxnet-v0.12.0) ➜  opencv git:(master) ✗ nm -gC /data/xx/mxnet-v0.12.0/python/mxnet/../../lib/libmxnet.so | grep MXCV
00000000032242e0 T MXCVResize(void*, unsigned int, unsigned int, int, void**)
00000000032239a0 T MXCVImdecode(unsigned char const*, unsigned int, int, void**)
0000000003224a70 T MXCVcopyMakeBorder(void*, int, int, int, int, int, double, void**)
(mxnet-v0.12.0) ➜  opencv git:(master) ✗ python
Python 2.7.14 |Anaconda, Inc.| (default, Nov 20 2017, 18:04:19)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import opencv
import >>> import numpy as np
>>> a = np.random.randint(20, size=(30,30,3))
>>> b = opencv.resize(a, (100,100)
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opencv.py", line 70, in resize
    check_call(_LIB.MXCVResize(src.handle, mx_uint(size[0]), mx_uint(size[1]),
  File "/data/xx/anaconda2/envs/mxnet-v0.12.0/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/data/xx/anaconda2/envs/mxnet-v0.12.0/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /data/xx/mxnet-v0.12.0/python/mxnet/../../lib/libmxnet.so: undefined symbol: MXCVResize
>>>

```
@mwbyeon
