### ISSUE TITLE
AttributeError: function 'MXGetLastError' not found

### ISSUE THREAD

**Issue by zsong** [apache/incubator-mxnet#9325]
I am on windows 7 with python 3.60 64 bit version.

I installed numpy `numpy-1.13.3+mkl-cp36-cp36m-win_amd64.whl`
And then install mxnet
```
pip install --upgrade mxnet
Requirement already up-to-date: mxnet in c:\python36x64\lib\site-packages
Requirement already up-to-date: graphviz in c:\python36x64\lib\site-packages (from mxnet)
Requirement already up-to-date: numpy in c:\python36x64\lib\site-packages (from mxnet)
Requirement already up-to-date: requests in c:\python36x64\lib\site-packages (from mxnet)
Requirement already up-to-date: certifi>=2017.4.17 in c:\python36x64\lib\site-packages (from requests->mxnet)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in c:\python36x64\lib\site-packages (from requests->mxnet)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in c:\python36x64\lib\site-packages (from requests->mxnet)
Requirement already up-to-date: idna<2.7,>=2.5 in c:\python36x64\lib\site-packages (from requests->mxnet)
```

Then I am getting this error.

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36x64\lib\site-packages\mxnet\__init__.py", line 25, in <module>
    from . import engine
  File "C:\Python36x64\lib\site-packages\mxnet\engine.py", line 23, in <module>
    from .base import _LIB, check_call
  File "C:\Python36x64\lib\site-packages\mxnet\base.py", line 111, in <module>
    _LIB = _load_lib()
  File "C:\Python36x64\lib\site-packages\mxnet\base.py", line 105, in _load_lib
    lib.MXGetLastError.restype = ctypes.c_char_p
  File "C:\Python36x64\lib\ctypes\__init__.py", line 357, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python36x64\lib\ctypes\__init__.py", line 362, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'MXGetLastError' not found
```

**Comment by ankkhedia** [comment]
@zsong How did you install mxnet. Could you please uninstall existing mxnet and follow instruction from the following documentation to install mxnet for your windows.
https://mxnet.incubator.apache.org/get_started/windows_setup.html 

@sandeep-krishnamurthy 
Please add the following tags:
- pending requester info
- Installation

**Comment by sandeep-krishnamurthy** [comment]
This is the right install guide - https://mxnet.incubator.apache.org/install/index.html

**Comment by lanking520** [comment]
Hi @zsong are you still facing the same issue?

**Comment by ankkhedia** [comment]
@sandeep-krishnamurthy @nswamy @anirudh2290 Could you please close the issue due to lack of activity.

@zsong Please feel free to re-open the issue in case closed in error.

**Comment by kalyc** [comment]
@mxnet-label-bot add [suggest-closed]
