### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by larroy** [apache/incubator-mxnet#9467]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/PR-9457/2/pipeline/

```
(py2) C:\jenkins_slave\workspace\ut-python-gpu@2>nosetests --verbose tests/python/gpu/test_forward.py 

test_forward.test_consistency ... ERROR



======================================================================

ERROR: test_forward.test_consistency

----------------------------------------------------------------------

Traceback (most recent call last):

  File "C:\Anaconda3\envs\py2\lib\site-packages\nose\case.py", line 197, in runTest

    self.test(*self.arg)

  File "C:\jenkins_slave\workspace\ut-python-gpu@2\tests\python\gpu\test_forward.py", line 56, in test_consistency

    data = np.load('data/test_images_%d_%d.npy'%shape)

  File "C:\Anaconda3\envs\py2\lib\site-packages\numpy\lib\npyio.py", line 419, in load

    pickle_kwargs=pickle_kwargs)

  File "C:\Anaconda3\envs\py2\lib\site-packages\numpy\lib\format.py", line 681, in read_array

    array.shape = shape

ValueError: cannot reshape array of size 2503444 into shape (16,3,299,299)

-------------------- >> begin captured logging << --------------------

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): data.mxnet.io

requests.packages.urllib3.connectionpool: DEBUG: http://data.mxnet.io:80 "GET /data/test_images_299_299.npy HTTP/1.1" 200 17165088

root: INFO: downloaded http://data.mxnet.io/data/test_images_299_299.npy into data\test_images_299_299.npy successfully

requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): data.mxnet.io

requests.packages.urllib3.connectionpool: DEBUG: http://data.mxnet.io:80 "GET /data/inception-v3-dump.npz HTTP/1.1" 200 64726

root: INFO: downloaded http://data.mxnet.io/data/inception-v3-dump.npz into data\inception-v3-dump.npz successfully

--------------------- >> end captured logging << ---------------------



----------------------------------------------------------------------

Ran 1 test in 754.124s



FAILED (errors=1)

```

**Comment by karan6181** [comment]
@sandeep-krishnamurthy Can you please add labels:
- CI

Thanks!

**Comment by vandanavk** [comment]
@larroy This test doesn't fail on latest CI builds. Closing this issue. Please feel free to reopen if it has been closed in error.

@sandeep-krishnamurthy Please close this issue.
