### ISSUE TITLE
MXNet bucking custom weighted loss error

### ISSUE THREAD

**Issue by opringle** [apache/incubator-mxnet#9523]
## Description

When using a custom loss function which multiplies the loss by weight array, in a bucketing module, the code fails if I include a predefined weight matrix.

## Environment info (Required)

```
----------Python Info----------
Version      : 3.6.3
Compiler     : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
Build        : ('default', 'Oct  6 2017 12:04:38')
Arch         : ('64bit', '')
------------Pip Info-----------
Version      : 9.0.1
Directory    : /Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/pip
----------MXNet Info-----------
/Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL
Version      : 0.11.0
Directory    : /Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet
Commit Hash   : 53274b4a2b0d73f3fbdb10cfb5f9ed0c8263fda7
----------System Info----------
Platform     : Darwin-17.3.0-x86_64-i386-64bit
system       : Darwin
node         : Olivers-MacBook-Pro.local
release      : 17.3.0
version      : Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
----------Hardware Info----------
machine      : x86_64
processor    : i386
b'machdep.cpu.brand_string: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz'
b'machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 PCLMULQDQ DTES64 MON DSCPL VMX EST TM2 SSSE3 FMA CX16 TPR PDCM SSE4.1 SSE4.2 x2APIC MOVBE POPCNT AES PCID XSAVE OSXSAVE SEGLIM64 TSCTMR AVX1.0 RDRAND F16C'
b'machdep.cpu.leaf7_features: SMEP ERMS RDWRFSGS TSC_THREAD_OFFSET BMI1 HLE AVX2 BMI2 INVPCID RTM SMAP RDSEED ADX IPT SGX FPU_CSDS MPX CLFSOPT'
b'machdep.cpu.extfeatures: SYSCALL XD 1GBPAGE EM64T LAHF LZCNT PREFETCHW RDTSCP TSCI'
----------Network Test----------
Setting timeout: 10
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0061 sec, LOAD: 0.7022 sec.
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0677 sec, LOAD: 0.0303 sec.
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0868 sec, LOAD: 0.1899 sec.
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ubyte.gz, DNS: 0.0140 sec, LOAD: 0.0910 sec.
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0097 sec, LOAD: 0.1285 sec.
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0547 sec, LOAD: 0.1798 sec.
```
I'm using python

## Error Message:

```
[19:44:31] /Users/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/logging.h:308: [19:44:31] src/operator/nn/../tensor/../elemwise_op_common.h:59: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _mul42 at 1-th input: expected (360,20), got (18,20,20)

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x00000001045dbad8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x00000001045d98a9 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x00000001046933f5 _ZZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ENKUlPNSB_IS3_NSD_IS3_EEEEmPKcE_clESL_mSN_ + 549
[bt] (3) 3   libmxnet.so                         0x0000000104693093 _ZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ + 227
[bt] (4) 4   libmxnet.so                         0x000000010468fdc2 _ZN5mxnet2op13ElemwiseShapeILi2ELi1EEEbRKN4nnvm9NodeAttrsEPNSt3__16vectorINS2_6TShapeENS6_9allocatorIS8_EEEESC_ + 242
[bt] (5) 5   libmxnet.so                         0x00000001056569aa _ZZN4nnvm4pass12_GLOBAL__N_19InferAttrINS_6TShapeEZNKS1_3$_0clENS_5GraphEEUlRKS3_E_DnEES5_OS5_T_PKcSC_SC_SC_SC_T0_T1_ENKUljbE_clEjb + 2250
[bt] (6) 6   libmxnet.so                         0x000000010565537a _ZNSt3__110__function6__funcIN4nnvm4pass12_GLOBAL__N_13$_0ENS_9allocatorIS5_EEFNS2_5GraphES8_EEclEOS8_ + 3178
[bt] (7) 7   libmxnet.so                         0x000000010563f6ab _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 795
[bt] (8) 8   libmxnet.so                         0x0000000104ce98bb _ZN4nnvm9ApplyPassENS_5GraphERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 187
[bt] (9) 9   libmxnet.so                         0x0000000104ced14b _ZN4nnvm4pass10InferShapeENS_5GraphENSt3__16vectorINS_6TShapeENS2_9allocatorIS4_EEEENS2_12basic_stringIcNS2_11char_traitsIcEENS5_IcEEEE + 891

infer_shape error. Arguments:
  data: (18, 20)
  softmax_label: (18, 20)
Traceback (most recent call last):
  File "mwe.py", line 99, in <module>
    model = mx.mod.BucketingModule(sym_gen=sym_gen, default_bucket_key=train_iter.default_bucket_key, context=mx.cpu())
  File "/Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet/module/bucketing_module.py", line 65, in __init__
    symbol, data_names, label_names = sym_gen(default_bucket_key)
  File "mwe.py", line 91, in sym_gen
    print("\ncross entropy loss shape: ", loss.infer_shape(data = data_shape, softmax_label=label_shape)[1][0])
  File "/Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet/symbol.py", line 978, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet/symbol.py", line 1107, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/Users/opringle/anaconda3/envs/py36/lib/python3.6/site-packages/mxnet/base.py", line 129, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator _mul42: [19:44:31] src/operator/nn/../tensor/../elemwise_op_common.h:59: Check failed: assign(&dattr, (*vec)[i]) Incompatible attr in node _mul42 at 1-th input: expected (360,20), got (18,20,20)

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x00000001045dbad8 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x00000001045d98a9 _ZN4dmlc15LogMessageFatalD1Ev + 9
[bt] (2) 2   libmxnet.so                         0x00000001046933f5 _ZZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ENKUlPNSB_IS3_NSD_IS3_EEEEmPKcE_clESL_mSN_ + 549
[bt] (3) 3   libmxnet.so                         0x0000000104693093 _ZN5mxnet2op12ElemwiseAttrIN4nnvm6TShapeEXadL_ZNS0_13shape_is_noneERKS3_EEXadL_ZNS0_12shape_assignEPS3_S5_EELb1EXadL_ZNS0_12shape_stringES5_EELin1ELin1EEEbRKNS2_9NodeAttrsEPNSt3__16vectorIT_NSA_9allocatorISC_EEEESG_RKSC_ + 227
[bt] (4) 4   libmxnet.so                         0x000000010468fdc2 _ZN5mxnet2op13ElemwiseShapeILi2ELi1EEEbRKN4nnvm9NodeAttrsEPNSt3__16vectorINS2_6TShapeENS6_9allocatorIS8_EEEESC_ + 242
[bt] (5) 5   libmxnet.so                         0x00000001056569aa _ZZN4nnvm4pass12_GLOBAL__N_19InferAttrINS_6TShapeEZNKS1_3$_0clENS_5GraphEEUlRKS3_E_DnEES5_OS5_T_PKcSC_SC_SC_SC_T0_T1_ENKUljbE_clEjb + 2250
[bt] (6) 6   libmxnet.so                         0x000000010565537a _ZNSt3__110__function6__funcIN4nnvm4pass12_GLOBAL__N_13$_0ENS_9allocatorIS5_EEFNS2_5GraphES8_EEclEOS8_ + 3178
[bt] (7) 7   libmxnet.so                         0x000000010563f6ab _ZN4nnvm11ApplyPassesENS_5GraphERKNSt3__16vectorINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS6_IS8_EEEE + 795
[bt] (8) 8   libmxnet.so                         0x0000000104ce98bb _ZN4nnvm9ApplyPassENS_5GraphERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 187
[bt] (9) 9   libmxnet.so                         0x0000000104ced14b _ZN4nnvm4pass10InferShapeENS_5GraphENSt3__16vectorINS_6TShapeENS2_9allocatorIS4_EEEENS2_12basic_stringIcNS2_11char_traitsIcEENS5_IcEEEE + 891
```

## Minimum reproducible example

```python
import mxnet as mx
import random
import sys

#parameter to break this code or not
break_code = sys.argv[1].lower() == "true"

#synthetically create 1000 encoded sentences
encoded_sentences = []
for i in list(range(1000)):
    sentence_length = random.randint(1, 20)
    sentence = random.sample(range(20), sentence_length)
    encoded_sentences.append(sentence)

#define hyperparameters/info
vocab = list(set(index for list in encoded_sentences for index in list))
batch_size = 18
num_embed = 10
num_hidden = 3
buckets = [5, 10, 15, 20]
epochs = 15

# Create and register a custom initializer
@mx.init.register
class WeightInit(mx.init.Initializer):
    def __init__(self):
        super(WeightInit, self).__init__()
    def _init_weight(self, _, arr):
        #set all weights to 1
        arr[:] = 1
        #scale the weight for not entity values
        arr[:,5,:] /= 5
    def _init_bias(self, _, arr):
        arr[:] =1

#use mxnet bucketing iterator, label is next value in sentence
train_iter = mx.rnn.BucketSentenceIter(sentences=encoded_sentences,
                                       batch_size=batch_size,
                                       buckets=buckets,
                                       data_name='data',
                                       label_name='softmax_label')

#define recurrent cell
r_cell = mx.rnn.LSTMCell(num_hidden=num_hidden)

#architecture is defined in a function, to allow variable length input sequences
def sym_gen(seq_len):
    """function that creates a network graph, depending on sequence length"""

    #define data shapes
    data_shape = (batch_size, seq_len)
    label_shape = (batch_size, seq_len)

    data = mx.sym.Variable('data')
    print("\ndata shape: ", data.infer_shape(data=data_shape)[1][0], "\n")

    label = mx.sym.Variable('softmax_label')
    print("\nlabel shape: ", label.infer_shape(softmax_label=label_shape)[1][0], "\n")

    #initialize weight array for use in our loss function, using a custom initializer and prevent the weights from being updated
    label_weights = mx.sym.BlockGrad(mx.sym.Variable(shape=(1, len(vocab), 1), init=WeightInit(), name='label_weights'),name = "blocked_weights")
    broadcast_label_weights = mx.sym.broadcast_to(label_weights, shape = (batch_size, len(vocab), seq_len), name = 'broadcast_weights')
    print("\ninput weights shape: ", broadcast_label_weights.infer_shape()[1][0])

    embed = mx.sym.Embedding(data, input_dim=len(vocab), output_dim=num_embed,name='embed')
    print("\nembed layer shape: ", embed.infer_shape(data=data_shape)[1][0], "\n")

    output, shapes = r_cell.unroll(seq_len, inputs=embed, merge_outputs=True)
    print("\nconcatenated recurrent layer shape: ", output.infer_shape(data=data_shape)[1][0], "after ", seq_len, " unrolls\n")

    reshape = mx.sym.Reshape(output, shape=(-1, num_hidden))
    print("\nafter reshaping: ", reshape.infer_shape(data=data_shape)[1][0], "\n")

    fc = mx.sym.FullyConnected(reshape, num_hidden=len(vocab), name='pred')
    print("\nfully connected layer shape: ", fc.infer_shape(data=data_shape)[1][0], "\n")

    label = mx.sym.Reshape(label, shape=(-1,))
    print("\nlabel shape after reshaping: ", label.infer_shape(softmax_label=label_shape)[1][0], "\n")

    onehot_label = mx.sym.one_hot(indices=label, depth=len(vocab), name='one_hot_labels')
    print("\none hot label shape: ", onehot_label.infer_shape(softmax_label=label_shape)[1][0], "\n")

    sm = mx.sym.softmax(fc, name='predicted_proba')
    print("\nsoftmax shape: ", sm.infer_shape(data=data_shape)[1][0], "\n")

    if break_code == False:
        loss = -((onehot_label * mx.sym.log(sm)) + ((1 - onehot_label) * mx.sym.log(1 - sm)))
    else:
        loss = -((onehot_label * mx.sym.log(sm)) + ((1 - onehot_label) * mx.sym.log(1 - sm))) * broadcast_label_weights

    print("\ncross entropy loss shape: ", loss.infer_shape(data = data_shape, softmax_label=label_shape)[1][0])

    loss_grad = mx.sym.MakeLoss(loss, name = 'loss')
    print("\nloss grad shape: ", loss_grad.infer_shape(data=data_shape, softmax_label=label_shape)[1][0])

    return loss_grad, ('data',), ('softmax_label',)

#create a trainable bucketing module on cpu
model = mx.mod.BucketingModule(sym_gen=sym_gen, default_bucket_key=train_iter.default_bucket_key, context=mx.cpu())

#fit the module
metric = mx.metric.create('loss')
model.bind(data_shapes=train_iter.provide_data,
           label_shapes=train_iter.provide_label)
model.init_params()
model.init_optimizer(optimizer='Adam')
for epoch in range(epochs):
    train_iter.reset()
    metric.reset()
    for batch in train_iter:
        model.forward(batch, is_train=True)             # compute predictions
        model.backward()                                # compute gradients
        model.update()                                  # update parameters
        model.update_metric(metric, batch.label)        # update metric
    print('\n', 'Epoch %d, Training %s' % (epoch, metric.get()))
```

## Steps to reproduce/solve

1. `python mwe.py false` to train successfully
2. `python mwe.py true` to reproduce error

**Comment by opringle** [comment]
I found the solution to this problem was to flatten the shape of the weights, labels and predictions before applying the custom loss function:

```python
reshaped_sm = mx.sym.Reshape(sm, shape=(-1))
reshaped_label = mx.sym.Reshape(onehot_label, shape=(-1))
reshaped_weights = mx.sym.Reshape(broadcast_label_weights, shape=(-1))

loss = -((reshaped_label * mx.sym.log(reshaped_sm)) + ((1 - reshaped_label ) * mx.sym.log(1 - reshaped_sm)))
```

I don't understand why I need to do this, since the shapes through my network appear to be correct.
