### ISSUE TITLE
zeros does not support int64

### ISSUE THREAD

**Issue by analog-cbarber** [apache/incubator-mxnet#9536]
mxnet 1.0.0, built from source

~~~python
>>> mx.ndarray.zeros((3,5), dtype=np.int64)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../python/mxnet/ndarray/utils.py", line 67, in zeros
    return _zeros_ndarray(shape, ctx, dtype, **kwargs)
  File ".../python/mxnet/ndarray/ndarray.py", line 3387, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype, **kwargs)
  File "<string>", line 34, in _zeros
  File ".../python/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File ".../python/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
MXNetError: Invalid Input: 'int64', valid values are: {'float16', 'float32', 'float64', 'int32', 'uint8'}, in operator _zeros(name="", dtype="int64", ctx="cpu(0)", shape="(3, 4)")
~~~

Because this is used by `gluon.Parameter`, it makes it difficult to use int64 as a parameter dtype.

**Comment by analog-cbarber** [comment]
BTW, are the list of officially supported dtypes documented anywhere? I cannot find it.
