### ISSUE TITLE
Flaky test_gluon_model_zoo_gpu.test_inference

### ISSUE THREAD

**Issue by marcoabreu** [apache/incubator-mxnet#9665]
http://jenkins.mxnet-ci.amazon-ml.com/blue/organizations/jenkins/incubator-mxnet/detail/master/333/pipeline/420

```
======================================================================

FAIL: test_gluon_model_zoo_gpu.test_inference

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/workspace/tests/python/gpu/test_gluon_model_zoo_gpu.py", line 84, in test_inference

    assert_almost_equal(out / max_val, gpu_out.asnumpy() / max_val, rtol=1e-2, atol=1e-2)

  File "/workspace/python/mxnet/test_utils.py", line 495, in assert_almost_equal

    raise AssertionError(msg)

AssertionError: 

Items are not equal:

Error 6.342113 exceeds tolerance rtol=0.010000, atol=0.010000.  Location of maximum error:(8, 827), a=0.103465, b=0.037656

 a: array([[ 0.35166606, -0.58146119, -0.10414348, ..., -0.37396723,

        -0.37157992, -0.14361246],

       [ 0.2298771 , -0.43115559, -0.08568203, ..., -0.24552163,...

 b: array([[ 0.35166582, -0.58146071, -0.10414336, ..., -0.37396693,

        -0.37157983, -0.14361246],

       [ 0.22987714, -0.43115517, -0.08568195, ..., -0.24552152,...

-------------------- >> begin captured logging << --------------------

urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): data.mxnet.io

urllib3.connectionpool: DEBUG: http://data.mxnet.io:80 "GET /data/val-5k-256.rec HTTP/1.1" 200 150874780

root: INFO: downloaded http://data.mxnet.io/data/val-5k-256.rec into data/val-5k-256.rec successfully

--------------------- >> end captured logging << ---------------------
```

tests/ci_build/ci_build.sh gpu_mklml PYTHONPATH=./python/ nosetests-2.7 --with-timer --verbose tests/python/gpu

@piiswrong @szha

**Comment by szha** [comment]
@zheng-da

**Comment by szha** [comment]
I just realized the change that caused this problem has been reverted. @marcoabreu

**Comment by marcoabreu** [comment]
Okay, so this was actually caused by MKLDNN?

**Comment by szha** [comment]
There wasn't a gpu version of model zoo test before. The test was introduced in the mkldnn change. Also, the failure was found in mkldnn test.

**Comment by marcoabreu** [comment]
Okay, thanks!

Am 01.02.2018 10:14 vorm. schrieb "Sheng Zha" <notifications@github.com>:
