### ISSUE TITLE
how to use the transforms 

### ISSUE THREAD

**Issue by HuangZhanPeng** [apache/incubator-mxnet#9729]
I take a try the mxnet.gluon.data.vision.transforms, the code is following

```
from mxnet import gluon
from mxnet.gluon.data.vision import transforms

train_data = gluon.data.vision.MNIST(train=True, transform=transforms.ToTensor())
test_data = gluon.data.vision.MNIST(train=False, transform=transforms.ToTensor())

train_loader = gluon.data.DataLoader(train_data, 100, shuffle=True)
test_loader = gluon.data.DataLoader(test_data, 100, shuffle=False)

for epoch in range(2):
    for i, data in enumerate(train_loader, 0):
        inputs, labels = data
        print(type(inputs), type(labels))
```

but it raise following error:

Traceback (most recent call last):
  File "E:/project/GluonZeroToAll/test.py", line 11, in <module>
    for i, data in enumerate(train_loader, 0):
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\data\dataloader.py", line 202, in __iter__
    yield self._batchify_fn([self._dataset[idx] for idx in batch])
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\data\dataloader.py", line 202, in <listcomp>
    yield self._batchify_fn([self._dataset[idx] for idx in batch])
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\data\dataset.py", line 207, in __getitem__
    return self._transform(self._data[idx], self._label[idx])
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 360, in __call__
    return self.forward(*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 575, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
TypeError: hybrid_forward() takes 3 positional arguments but 4 were given

**Comment by piiswrong** [comment]
`train_data = gluon.data.vision.MNIST(train=True).transform_first(transforms.ToTensor())`

**Comment by HuangZhanPeng** [comment]
thank you very much

**Comment by Roshrini** [comment]
@HuangZhanPeng You can also ask questions via the [Discuss Forum](https://discuss.mxnet.io/), not via issues. :)

@sandeep-krishnamurthy The question was answered.
Can you add labels - 
- Gluon, 
- HowTo, 
- Question 
and close the issue.

**Comment by szha** [comment]
@piiswrong maybe TransformFirst can be a transformer, instead of having a special transformer method?
