### ISSUE TITLE
Example SSD demo doesn't work

### ISSUE THREAD

**Issue by tholcman** [apache/incubator-mxnet#9817]
I have trained network with command 
```
$ python train.py --train-path data/train.rec --val-path data/val.rec --class-names 1,2 --num-class 2 --end-epoch 9999
```
But when I try demo it is failing
```
$ ./demo.py --prefix model6/ssd_vgg16_reduced_300 --images 63671599ab75a93b688ba51f2cef5bb9.jpg --class-names 1,2 --data-shape 300 --cpu --thresh 0.3 --nms 0.3
[14:38:10] src/nnvm/legacy_json_util.cc:209: Loading symbol saved by previous version v0.11.1. Attempting to upgrade...
[14:38:10] src/nnvm/legacy_json_util.cc:217: Symbol successfully upgraded!
Traceback (most recent call last):
  File "./demo.py", line 155, in <module>
    ctx, len(class_names), args.nms_thresh, args.force_nms)
  File "./demo.py", line 60, in get_detector
    detector = Detector(net, prefix, epoch, data_shape, mean_pixels, ctx=ctx)
  File "/home/ubuntu/incubator-mxnet/example/ssd/detect/detector.py", line 59, in __init__
    self.mod.set_params(args, auxs)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/module/module.py", line 348, in set_params
    allow_extra=allow_extra)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/module/module.py", line 307, in init_params
    _impl(desc, arr, arg_params)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/module/module.py", line 298, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: bn_data_gamma is not presented
```

I have tried python3 mxnet (0.11.1, 1.0.0), cpu/gpu, fresh trained/deployed model but error is always the same.

**Comment by marcoabreu** [comment]
@larroy might be interested

@tholcman you might want to try out https://github.com/apache/incubator-mxnet/pull/9808
