### ISSUE TITLE
Undefined name `get_cifar10_iterator` in gluon image_classification example

### ISSUE THREAD

**Issue by arokem** [apache/incubator-mxnet#9894]
Note: Providing complete information in the most concise form is the best way to get help. This issue template serves as the checklist for essential information to most of the technical issues and bug reports. For non-technical issues and feature requests, feel free to present the information in what you believe is the best form.

For Q & A and discussion, please start a discussion thread at https://discuss.mxnet.io 

## Description

Undefined name `get_cifar10_iterator` in this example:

https://github.com/apache/incubator-mxnet/blob/master/example/gluon/image_classification.py

## Environment info (Required)

```
$python diagnose.py

----------Python Info----------                                                                                                     
Version      : 3.4.3                                                                                                                
Compiler     : GCC 4.8.4                                                                                                            
Build        : ('default', 'Sep 14 2016 12:36:27')                                                                                  
Arch         : ('64bit', 'ELF')                                                                                                     
------------Pip Info-----------                                                                                                     
Version      : 9.0.1                                                                                                                
Directory    : /usr/local/lib/python3.4/dist-packages/pip                                                                           
----------MXNet Info-----------                                                                                                     
Version      : 1.2.0                                                                                                                
Directory    : /home/ariel/.local/lib/python3.4/site-packages/mxnet                                                                 
Commit Hash   : 5c5a904209900e21b20ca206b043ea7a8252ebfc                                                                            
----------System Info----------                                                                                                     
Platform     : Linux-4.4.0-38-generic-x86_64-with-Ubuntu-14.04-trusty                                                               
system       : Linux                                                                                                                
node         : titanx                                                                                                               
release      : 4.4.0-38-generic                                                                                                     
version      : #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016                                                                   
----------Hardware Info----------                                                                                                   
machine      : x86_64                                                                                                               
processor    : x86_64                                                                                                               
Architecture:          x86_64                                                                                                       
CPU op-mode(s):        32-bit, 64-bit                                                                                               
Byte Order:            Little Endian                                                                                                
CPU(s):                8                                                                                                            
On-line CPU(s) list:   0-7                                                                                                          
Thread(s) per core:    2                                                                                                            
Core(s) per socket:    4                                                                                                            
Socket(s):             1                                                                                                            
NUMA node(s):          1                                                                                                            
Vendor ID:             GenuineIntel                                                                                                 
CPU family:            6                                                                                                            
Model:                 94                                                                                                           
Stepping:              3                                                                                                            
CPU MHz:               3700.292                                                                                                     
BogoMIPS:              7007.87                                                                                                      
Virtualization:        VT-x                                                                                                         
L1d cache:             32K                                                                                                          
L1i cache:             32K                                                                                                          
L2 cache:              256K                                                                                                         
L3 cache:              8192K                                                                                                        
NUMA node0 CPU(s):     0-7                                                                                                          
----------Network Test----------                                                                                                    
Setting timeout: 10                                                                                                                 
Timing for Gluon Tutorial(cn): https://zh.gluon.ai, DNS: 0.0564 sec, LOAD: 0.1074 sec.                                              
Timing for Gluon Tutorial(en): http://gluon.mxnet.io, DNS: 0.0702 sec, LOAD: 0.0271 sec.                                            
Timing for Conda: https://repo.continuum.io/pkgs/free/, DNS: 0.0011 sec, LOAD: 0.0222 sec.                                          
Timing for FashionMNIST: https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/dataset/fashion-mnist/train-labels-idx1-ub
yte.gz, DNS: 0.1280 sec, LOAD: 0.0668 sec.                                                                                          
Timing for MXNet: https://github.com/apache/incubator-mxnet, DNS: 0.0010 sec, LOAD: 0.5486 sec.                                     
Timing for PYPI: https://pypi.python.org/pypi/pip, DNS: 0.0014 sec, LOAD: 0.2274 sec.              

```

Package used (Python/R/Scala/Julia):
(I'm using ...)

Python

For Scala user, please provide:
1. Java version: (`java -version`)
2. Maven version: (`mvn -version`)
3. Scala runtime if applicable: (`scala -version`)

For R user, please provide R `sessionInfo()`:

## Error Message:
```
$ python image_classification.py  --model vgg16                                                                      
INFO:root:Namespace(batch_norm=False, batch_size=32, dataset='cifar10', epochs=3, kvstore='device', log_interval=50, lr=0.01, mode=N
one, model='vgg16', momentum=0.9, num_gpus=0, profile=False, seed=123, train_data='', use_pretrained=False, use_thumbnail=False, val
_data='', wd=0.0001)                                                                                                                
Traceback (most recent call last):                                                                                                  
  File "image_classification.py", line 274, in <module>                                                                             
    main()                                                                                                                          
  File "image_classification.py", line 261, in main                                                                                 
    train(opt.epochs, context)                                                                                                      
  File "image_classification.py", line 197, in train                                                                                
    train_data, val_data = get_data_iters(dataset, batch_size, kv.num_workers, kv.rank)                                             
  File "image_classification.py", line 162, in get_data_iters                                                                       
    num_parts=num_workers, part_index=rank)                                                                                         
TypeError: get_cifar10_iterator() got an unexpected keyword argument 'num_parts'                                                    
ariel@titanx:~$ python3 image_classification.py  --model vgg16                                                                      
INFO:root:Namespace(batch_norm=False, batch_size=32, dataset='cifar10', epochs=3, kvstore='device', log_interval=50, lr=0.01, mode=N
one, model='vgg16', momentum=0.9, num_gpus=0, profile=False, seed=123, train_data='', use_pretrained=False, use_thumbnail=False, val
_data='', wd=0.0001)                                                                                                                
Traceback (most recent call last):                                                                                                  
  File "image_classification.py", line 215, in <module>                                                                             
    main()                                                                                                                          
  File "image_classification.py", line 202, in main                                                                                 
    train(opt.epochs, context)                                                                                                      
  File "image_classification.py", line 138, in train                                                                                
    train_data, val_data = get_data_iters(dataset, batch_size, kv.num_workers, kv.rank)                                             
  File "image_classification.py", line 102, in get_data_iters                                                                       
    train_data, val_data = get_cifar10_iterator(batch_size, (3, 32, 32),                                                            
NameError: name 'get_cifar10_iterator' is not defined      
```

## Minimum reproducible example

https://github.com/apache/incubator-mxnet/blob/master/example/gluon/image_classification.py

## Steps to reproduce

1. python image_classification.py  --model vgg16

## What have you tried to solve it?

1. I tried implementing my own `get_cifar10_iterator`, based on the example of `get_mnist_iterator` seems to depend closely on the format of the MNIST data.

**Comment by lupesko** [comment]
@sandeep-krishnamurthy please add these labels:
- Gluon
- Python

**Comment by lupesko** [comment]
@arokem I just tried and it is working as expected.
`get_cifar10_iterator`is defined in /example/gluon/data.py

Please try the following:
- To make sure you have the latest and greatest:
`$ pip install mxnet --pre --upgrade`
- To make sure you have the latest version of the code
`$ git pull`
- Then try to run the example:
`$ python image_classification.py --model vgg16`

We'll close this issue, please re-open if closed in error.
Thanks!

**Comment by lupesko** [comment]
@sandeep-krishnamurthy please close. thanks!
