### ISSUE TITLE
mxnet installation issue on Win 10 - module gluon.data.dataset has no attribute DownloadedDataset

### ISSUE THREAD

**Issue by KishoreKarunakaran** [apache/incubator-mxnet#9938]
I have used **pip install mxnet** to install mxnet and now I'm getting an **AttributeError: module 'mxnet.gluon.data.dataset' has no attribute '_DownloadedDataset'**
```
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as ms
E:\Programs\Anaconda3\envs\mxnet\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Programs\Anaconda3\envs\mxnet\lib\site-packages\mxnet\__init__.py", line 81, in <module>
    from . import gluon
  File "E:\Programs\Anaconda3\envs\mxnet\lib\site-packages\mxnet\gluon\__init__.py", line 36, in <module>
    from . import data
  File "E:\Programs\Anaconda3\envs\mxnet\lib\site-packages\mxnet\gluon\data\__init__.py", line 28, in <module>
    from . import vision
  File "E:\Programs\Anaconda3\envs\mxnet\lib\site-packages\mxnet\gluon\data\vision\__init__.py", line 22, in <module>
    from .datasets import *
  File "E:\Programs\Anaconda3\envs\mxnet\lib\site-packages\mxnet\gluon\data\vision\datasets.py", line 36, in <module>
    class MNIST(dataset._DownloadedDataset):
AttributeError: module 'mxnet.gluon.data.dataset' has no attribute '_DownloadedDataset'
>>>
```

**Comment by szha** [comment]
@yajiedesign

**Comment by KishoreKarunakaran** [comment]
I fixed it by first uninstalling current mxnet packages and updating my conda packages and installed it again. Now it works.
